Repository artsy/eigen, pull requests merged in 2019-11, with the labels that each got.

#2944 Updates Extraction #trivial
  Podfile.lock
Labels: Jira Synced

#2946 Update emission to 1.18.23
  CHANGELOG.yml
  Podfile.lock
Labels: Merge On Green

#2948 Updates release notes for 6.0.0 release #trivial
  fastlane/metadata/en-US/release_notes.txt
Labels: Merge On Green

#2950 Adds partner locations routing
  Artsy/App/ARSwitchBoard.m
  Podfile.lock
Labels: Merge On Green

#2951 Updates emission
  Podfile.lock
Labels: Merge On Green

#2952 Updates viewcontrollers background colors
  Artsy/View_Controllers/ARMutableLinkViewController.m
  Artsy/View_Controllers/Fair/ARProfileViewController.m
  CHANGELOG.yml
Labels: Merge On Green

#2953 Updates Emission
  Podfile.lock
Labels: Merge On Green

#2937 ⚠️ Do not merge: Add a new flag for Price Transparency to Echo
  Artsy/App/ARAppDelegate+Emission.m
  CHANGELOG.yml
Labels: Merge On Green

#2954 Update emission
  CHANGELOG.yml
  Podfile
  Podfile.lock
Labels: Merge On Green

#2955 Bumps version to 6.1.0
  Artsy Stickers/Info.plist
  Artsy/App_Resources/Artsy-Info.plist
  CHANGELOG.yml
Labels: Merge On Green

#2956 Update emission to 1.18.39
  CHANGELOG.yml
  Podfile.lock
Labels: Merge On Green

#2958 MX-115 - Fixes landscape partner page
  Artsy/View_Controllers/ARMutableLinkViewController.m
  Podfile.lock
Labels: Jira Synced, Merge On Green
