Repository artsy/eigen, pull requests merged in 2019-09, with the labels that each got.

#2895 PURCHASE-1454 Open web view target='_blank' links by pushing to navigation stack
  Artsy/View_Controllers/Web_Browsing/ARExternalWebBrowserViewController.m
  Artsy_Tests/View_Controller_Tests/Web_Browsing/ARExternalWebBrowserViewControllerTests.m
  CHANGELOG.yml
Labels: Jira Synced, Merge On Green

#2899 Update emission
  Podfile
  Podfile.lock
Labels: Merge On Green

#2901 [PURCHASE-1481] Removes ARReactNativeArtworkEnableAlways Echo flag #trivial
  Artsy/View_Controllers/Artwork/ARArtworkViewController.m
  Artsy_Tests/View_Controller_Tests/Artwork/ARArtworkViewControllerTests.m
Labels: Jira Synced

#2902 Fixes crash when AuctionViewController re-appears without a populated view model
  Artsy/App/SwiftExtensions.swift
  Artsy/View_Controllers/Auction/AuctionViewController.swift
  CHANGELOG.yml
Labels: Merge On Green

#2903 Fixes show the new RN artwork view for sale artworks (that are inquirable) #trivial
  Artsy/View_Controllers/Artwork/ARArtworkViewController.m
  Artsy_Tests/View_Controller_Tests/Artwork/ARArtworkViewControllerTests.m
Labels: Merge On Green

#2909 PURCHASE-1511 PURCHASE-1512 Fix conditions-of-sale sublinks
  Artsy/View_Controllers/Web_Browsing/ARInternalMobileWebViewController.m
Labels: Jira Synced

#2913 Updates Emission to 1.17.3
  Podfile.lock
Labels: Merge On Green
