Repository artsy/eigen, pull requests merged in 2019-05, with the labels that each got.

#2824 Clears Relay cache when a PUT, POST, or DELETE is made to our API.
  Artsy/Networking/API_Modules/ARUserManager.m
  Artsy/Networking/ArtsyAPI.m
  Artsy_Tests/Networking_Tests/API_Modules/ArtsyAPI+PrivateTests.m
  CHANGELOG.yml
Labels: Jira Synced, Merge On Green

#2826 [PLATFORM-1399] Reconfigures Echo
  .gitignore
  Artsy/App/ARAppDelegate+Emission.m
  Artsy/App/Echo.json
  Artsy/App/Echo.json.example
  CHANGELOG.yml
  Makefile
  Podfile
  Podfile.lock
  README.md
Labels: Jira Synced

#2825 [Artwork] Show RN version when non-commercial only.
  Artsy.xcodeproj/project.pbxproj
  Artsy/View_Controllers/Artwork/ARArtworkSetViewController.h
  Artsy/View_Controllers/Artwork/ARArtworkSetViewController.m
  Artsy/View_Controllers/Artwork/ARArtworkViewController+ButtonActions.h
  Artsy/View_Controllers/Artwork/ARArtworkViewController+ButtonActions.m
  Artsy/View_Controllers/Artwork/ARArtworkViewController.h
  Artsy/View_Controllers/Artwork/ARArtworkViewController.m
  Artsy/View_Controllers/Artwork/ARLegacyArtworkViewController.h
  Artsy/View_Controllers/Artwork/ARLegacyArtworkViewController.m
  Artsy/Views/Artwork/ARArtworkRelatedArtworksView.h
  Artsy/Views/Artwork/ARArtworkView.h
  Artsy/Views/Artwork/ARArtworkView.m
  Artsy_Tests/App_Tests/ARAppActivityContinuationDelegateTests.m
  Artsy_Tests/ReferenceImages/ARLegacyArtworkViewControllerSpec/Artworks look right on iPad with no related data@2x.png
  Artsy_Tests/ReferenceImages/ARLegacyArtworkViewControllerSpec/Artworks look right on iPhone with no related data@2x.png
  Artsy_Tests/ReferenceImages/ARLegacyArtworkViewControllerSpec/at_a_closed_auction_displays_artwork_on_iPad@2x.png
  Artsy_Tests/ReferenceImages/ARLegacyArtworkViewControllerSpec/at_a_closed_auction_displays_artwork_on_iPhone@2x.png
  Artsy_Tests/ReferenceImages/ARLegacyArtworkViewControllerSpec/at_an_auction_requireing_registration_displays_artwork_on_iPhone@2x.png
  Artsy_Tests/ReferenceImages/ARLegacyArtworkViewControllerSpec/no_related_data_shows_artwork_on_iPad@2x.png
  Artsy_Tests/ReferenceImages/ARLegacyArtworkViewControllerSpec/no_related_data_shows_artwork_on_iPhone@2x.png
  Artsy_Tests/ReferenceImages/ARLegacyArtworkViewControllerSpec/shows_an_upublished_banner@2x.png
  Artsy_Tests/ReferenceImages/ARLegacyArtworkViewControllerSpec/with_related_artworks_iPad_displays_related_artworks@2x.png
  Artsy_Tests/ReferenceImages/ARLegacyArtworkViewControllerSpec/with_related_artworks_iPad_related_artworks_view_looks_correct@2x.png
  Artsy_Tests/ReferenceImages/ARLegacyArtworkViewControllerSpec/with_related_artworks_iPhone_displays_related_artworks@2x.png
  Artsy_Tests/ReferenceImages/ARLegacyArtworkViewControllerSpec/with_related_artworks_iPhone_related_artworks_view_looks_correct@2x.png
  Artsy_Tests/ReferenceImages/ARLegacyArtworkViewControllerSpec/with_related_artworks_shows_the_price_when_applicable@2x.png
  Artsy_Tests/View_Controller_Tests/Artwork/ARArtworkViewControllerTests.m
  Artsy_Tests/View_Controller_Tests/Artwork/ARLegacyArtworkViewControllerBuyButtonTests.m
  Artsy_Tests/View_Controller_Tests/Artwork/ARLegacyArtworkViewControllerTests.m
  Podfile
  Podfile.lock
Labels: Jira Synced

#2827 [Artwork] Put new RN view behind a lab option.
  Artsy/App/AROptions.h
  Artsy/App/AROptions.m
  Artsy/View_Controllers/Artwork/ARArtworkViewController.m
  Artsy_Tests/View_Controller_Tests/Artwork/ARArtworkViewControllerTests.m
Labels: Jira Synced

#2831 Updates release notes for 5.0.3 #trivial
  fastlane/metadata/en-US/release_notes.txt
Labels: Merge On Green

#2832 Emission update to 1.11.1
  Podfile
  Podfile.lock
Labels: Merge On Green

#2833 Updates Emission to 1.11.2
  Podfile
  Podfile.lock
Labels: Merge On Green

#2834 Updates version/etc after 5.0.3 release #trivial
  Artsy Stickers/Info.plist
  Artsy/App_Resources/Artsy-Info.plist
  CHANGELOG.yml
  Podfile.lock
Labels: Merge On Green

#2840 Adds lab feature to view new React Native Artwork View
  Artsy.xcodeproj/project.pbxproj
  Artsy/App/AROptions.h
  Artsy/App/AROptions.m
  Artsy/View_Controllers/Artwork/ARArtworkSetViewController.h
  Artsy/View_Controllers/Artwork/ARArtworkSetViewController.m
  Artsy/View_Controllers/Artwork/ARArtworkViewController+ButtonActions.h
  Artsy/View_Controllers/Artwork/ARArtworkViewController+ButtonActions.m
  Artsy/View_Controllers/Artwork/ARArtworkViewController.h
  Artsy/View_Controllers/Artwork/ARArtworkViewController.m
  Artsy/View_Controllers/Artwork/ARLegacyArtworkViewController.h
  Artsy/View_Controllers/Artwork/ARLegacyArtworkViewController.m
  Artsy/Views/Artwork/ARArtworkRelatedArtworksView.h
  Artsy/Views/Artwork/ARArtworkView.h
  Artsy/Views/Artwork/ARArtworkView.m
  Artsy_Tests/App_Tests/ARAppActivityContinuationDelegateTests.m
  Artsy_Tests/ReferenceImages/ARLegacyArtworkViewControllerSpec/Artworks look right on iPad with no related data@2x.png
  Artsy_Tests/ReferenceImages/ARLegacyArtworkViewControllerSpec/Artworks look right on iPhone with no related data@2x.png
  Artsy_Tests/ReferenceImages/ARLegacyArtworkViewControllerSpec/at_a_closed_auction_displays_artwork_on_iPad@2x.png
  Artsy_Tests/ReferenceImages/ARLegacyArtworkViewControllerSpec/at_a_closed_auction_displays_artwork_on_iPhone@2x.png
  Artsy_Tests/ReferenceImages/ARLegacyArtworkViewControllerSpec/at_an_auction_requireing_registration_displays_artwork_on_iPhone@2x.png
  Artsy_Tests/ReferenceImages/ARLegacyArtworkViewControllerSpec/no_related_data_shows_artwork_on_iPad@2x.png
  Artsy_Tests/ReferenceImages/ARLegacyArtworkViewControllerSpec/no_related_data_shows_artwork_on_iPhone@2x.png
  Artsy_Tests/ReferenceImages/ARLegacyArtworkViewControllerSpec/shows_an_upublished_banner@2x.png
  Artsy_Tests/ReferenceImages/ARLegacyArtworkViewControllerSpec/with_related_artworks_iPad_displays_related_artworks@2x.png
  Artsy_Tests/ReferenceImages/ARLegacyArtworkViewControllerSpec/with_related_artworks_iPad_related_artworks_view_looks_correct@2x.png
  Artsy_Tests/ReferenceImages/ARLegacyArtworkViewControllerSpec/with_related_artworks_iPhone_displays_related_artworks@2x.png
  Artsy_Tests/ReferenceImages/ARLegacyArtworkViewControllerSpec/with_related_artworks_iPhone_related_artworks_view_looks_correct@2x.png
  Artsy_Tests/ReferenceImages/ARLegacyArtworkViewControllerSpec/with_related_artworks_shows_the_price_when_applicable@2x.png
  Artsy_Tests/View_Controller_Tests/Artwork/ARArtworkViewControllerTests.m
  Artsy_Tests/View_Controller_Tests/Artwork/ARLegacyArtworkViewControllerBuyButtonTests.m
  Artsy_Tests/View_Controller_Tests/Artwork/ARLegacyArtworkViewControllerTests.m
  Podfile
  Podfile.lock
Labels: Jira Synced
