Repository artsy/eigen, pull requests merged in 2019-10, with the labels that each got.

#2916 [PURCHASE-1548] Duplicate view controller crash fix
  Artsy/App/ARAppDelegate+Analytics.m
  Artsy/View_Controllers/Util/ARNavigationController.m
  Artsy/View_Controllers/Web_Browsing/ARInternalMobileWebViewController.m
  CHANGELOG.yml
Labels: Jira Synced

#2917 Dependency cleanup #trivial
  Gemfile
  Gemfile.lock
  Podfile
  Podfile.lock
Labels: Jira Synced

#2919 5.0.8 patch, re-disables Echo check for artwork view, Emission update
  Artsy Stickers/Info.plist
  Artsy/App_Resources/Artsy-Info.plist
  Artsy/View_Controllers/Artwork/ARArtworkViewController.m
  Artsy_Tests/View_Controller_Tests/Artwork/ARArtworkViewControllerTests.m
  CHANGELOG.yml
  Podfile.lock
  fastlane/metadata/en-US/release_notes.txt
Labels: Merge On Green

#2920 Bump rubyzip from 1.2.1 to 1.3.0
  Gemfile.lock
Labels: Merge On Green

#2924 Update danger swift #trivial
  Dangerfile.swift
  Package.resolved
Labels: Merge On Green

#2922 [PURCHASE-1537] Fix search transition animation
  Artsy/Navigation_Transitions/ARAppSearchTransition.m
  Artsy/Navigation_Transitions/ARDefaultNavigationTransition.m
  CHANGELOG.yml
Labels: Jira Synced

#2925 ME-43 - Adds killSwitch
  Artsy/App/ARAppDelegate.m
  CHANGELOG.yml
Labels: Jira Synced, Merge On Green

#2929 ME-11 Fix conversations push notification handling
  Artsy/App/ARAppDelegate.m
Labels: Jira Synced

#2928 ME-33 - Fixes circle height
  Artsy/View_Controllers/App_Navigation/ARTopMenuViewController.m
  CHANGELOG.yml
Labels: Jira Synced

#2932 Update emission
  Artsy/App/ARAppDelegate+Emission.m
  Artsy_Tests/Supporting_Files/ARTestHelper.m
  CHANGELOG.yml
  Podfile.lock
Labels: Merge On Green

#2931 ME-15 Fix ARSerifNavigationBar element positions
  Artsy/View_Controllers/ARSerifNavigationViewController.m
  Artsy_Tests/ReferenceImages/ARSerifNavigationViewControllerSpec/_handles_the_back_button_correctly@2x.png
  Artsy_Tests/ReferenceImages/AuctionInformationViewControllerTests/FAQ_Entry__Bidding@2x.png
  Artsy_Tests/ReferenceImages/AuctionInformationViewControllerTests/FAQ_Entry__Buyer_s_Premium__Taxes___Fees@2x.png
  Artsy_Tests/ReferenceImages/AuctionInformationViewControllerTests/FAQ_Entry__Conditions_of_Sale@2x.png
  Artsy_Tests/ReferenceImages/AuctionInformationViewControllerTests/FAQ_Entry__Emails_and_Alerts@2x.png
  Artsy_Tests/ReferenceImages/AuctionInformationViewControllerTests/FAQ_Entry__Payments_and_Shipping@2x.png
  Artsy_Tests/ReferenceImages/AuctionInformationViewControllerTests/FAQ_Initial_Entry@2x.png
  Artsy_Tests/ReferenceImages/AuctionInformationViewControllerTests/a_closed_sale__shows_the_sale_is_closed@2x.png
  Artsy_Tests/ReferenceImages/AuctionInformationViewControllerTests/a_current_sale__has_a_root_view_that_shows_information_about_the_auction_and_looks_good_on_iPad@2x.png
  Artsy_Tests/ReferenceImages/AuctionInformationViewControllerTests/a_current_sale__has_a_root_view_that_shows_information_about_the_auction_and_looks_good_on_iPhone@2x.png
  Artsy_Tests/ReferenceImages/AuctionInformationViewControllerTests/a_current_sale__shows_a_button_for_buyer_s_premium_when_needed@2x.png
  Artsy_Tests/ReferenceImages/LiveAuctionViewControllerTests/handles_splitting_in_an_iPad@2x.png
  Artsy_Tests/ReferenceImages/LiveAuctionViewControllerTests/looks_good_by_default@2x.png
  Artsy_Tests/ReferenceImages/LiveAuctionViewControllerTests/shows_a_removes_disconnected_screen_when_socket_reconnects@2x.png
  Artsy_Tests/ReferenceImages/LiveAuctionViewControllerTests/shows_a_socket_disconnect_screen_when_socket_fails@2x.png
  Artsy_Tests/ReferenceImages/LiveAuctionViewControllerTests/shows_an_operator_disconnect_screen_when_operator_disconnects@2x.png
  Artsy_Tests/ReferenceImages/LiveAuctionViewControllerTests/shows_an_operator_disconnected_screen_when_operator_reconnects@2x.png
  CHANGELOG.yml
  Podfile.lock
Labels: Jira Synced

#2934 Add a feature flag for Price Transparency
  Artsy/App/ARAppDelegate+Emission.m
  Artsy/App/AROptions.h
  Artsy/App/AROptions.m
  CHANGELOG.yml
Labels: Jira Synced

#2939 Fix test failure in ARAppDelegateEmissionSpec
  Artsy_Tests/App_Tests/ARAppDelegateEmissionSpec.m
Labels: Merge On Green

#2941 Killswitch to ascending
  Artsy/App/ARAppDelegate.m
Labels: Merge On Green
