Repository artsy/eigen, pull requests merged in 2019-02, with the labels that each got.

#2765 Update Adjust to the latest version
  Podfile.lock
Labels: Merge On Green

#2769 Fixes some fair routing issues
  Artsy/App/ARAppDelegate+Emission.m
  Artsy/App/ARSwitchboard+Eigen.m
  Artsy/View_Controllers/Fair/ARProfileViewController.m
  CHANGELOG.yml
Labels: Jira Synced

#2770 Update the Live Auctions UI
  Artsy/Categories/Apple/NSString+StringCase.h
  Artsy/Categories/Apple/NSString+StringCase.m
  Artsy/Resources/Artsy-Bridging-Header.h
  Artsy/View_Controllers/Live_Auctions/LiveActionStateReconciler.swift
  Artsy/View_Controllers/Live_Auctions/LiveAuctionBidButton.swift
  Artsy/View_Controllers/Live_Auctions/LiveAuctionBidViewModel.swift
  Artsy/View_Controllers/Live_Auctions/LiveAuctionPlaceMaxBidViewController.swift
  Artsy/View_Controllers/Live_Auctions/LiveAuctionStateManager.swift
  Artsy/View_Controllers/Live_Auctions/Resources/LiveAuctions.storyboard
  Artsy/View_Controllers/Live_Auctions/ViewModels/LiveAuctionEventViewModel.swift
  Artsy/View_Controllers/Live_Auctions/ViewModels/LiveAuctionLotViewModel.swift
  Artsy/View_Controllers/Live_Auctions/Views/LiveAuctionBiddingViewModel.swift
  Artsy/View_Controllers/Live_Auctions/Views/LiveAuctionCurrentLotView.swift
  Artsy/View_Controllers/Live_Auctions/Views/LiveBidProgressOverlayView.swift
  Artsy_Tests/Networking_Tests/LiveAuctionLotViewModelSpecs.swift
  Artsy_Tests/ReferenceImages/LiveAuctionBidButtonTests/has_valid_snapshot_failed@2x.png
  Artsy_Tests/ReferenceImages/LiveAuctionBidButtonTests/has_valid_snapshot_highest_bidder@2x.png
  Artsy_Tests/ReferenceImages/LiveAuctionBidButtonTests/has_valid_snapshot_highest_bidder__and_can_re_bid@2x.png
  Artsy_Tests/ReferenceImages/LiveAuctionBidButtonTests/has_valid_snapshot_passed@2x.png
  Artsy_Tests/ReferenceImages/LiveAuctionBidButtonTests/has_valid_snapshot_registration_closed@2x.png
  Artsy_Tests/ReferenceImages/LiveAuctionBidButtonTests/has_valid_snapshot_registration_pending@2x.png
  Artsy_Tests/ReferenceImages/LiveAuctionBidButtonTests/has_valid_snapshot_registration_required@2x.png
  Artsy_Tests/ReferenceImages/LiveAuctionBidButtonTests/has_valid_snapshot_waiting@2x.png
  Artsy_Tests/ReferenceImages/LiveAuctionBidButtonTests/has_valid_snapshot_waiting_on_auctioneer_confirmation@2x.png
  Artsy_Tests/ReferenceImages/LiveAuctionBidHistoryViewControllerTests/looks_right_on_a_comprehensive_set_of_events@2x.png
  Artsy_Tests/ReferenceImages/LiveAuctionBidViewControllerTests/networking__has_valid_snapshot_in_progress@2x.png
  Artsy_Tests/ReferenceImages/LiveAuctionBidViewControllerTests/networking__has_valid_snapshot_network_issues@2x.png
  Artsy_Tests/ReferenceImages/LiveAuctionBidViewControllerTests/networking__has_valid_snapshot_waiting@2x.png
  Artsy_Tests/ReferenceImages/LiveAuctionLotViewControllerTests/snapshots__looks_good_for_passed_lots@2x.png
  Artsy_Tests/ReferenceImages/LiveAuctionLotViewControllerTests/snapshots__looks_good_for_upcoming_lots_that_the_user_is_winning@2x.png
  Artsy_Tests/ReferenceImages/LiveAuctionViewControllerTests/handles_splitting_in_an_iPad@2x.png
  Artsy_Tests/ReferenceImages/LiveAuctionViewControllerTests/looks_good_by_default@2x.png
  Artsy_Tests/ReferenceImages/LiveAuctionViewControllerTests/shows_a_removes_disconnected_screen_when_socket_reconnects@2x.png
  Artsy_Tests/ReferenceImages/LiveAuctionViewControllerTests/shows_an_operator_disconnected_screen_when_operator_reconnects@2x.png
  Artsy_Tests/View_Controller_Tests/Live_Auction/LiveAuctionBidButtonTests.swift
  Artsy_Tests/View_Controller_Tests/Live_Auction/LiveAuctionBidViewControllerTests.swift
  Artsy_Tests/View_Controller_Tests/Live_Auction/LiveAuctionLotSetViewControllerTests.swift
  Artsy_Tests/View_Controller_Tests/Live_Auction/LiveAuctionLotViewControllerTests.swift
  CHANGELOG.yml
Labels: Auctions

#2772 Improves the search for fairs where their profileID is different
  Artsy/Models/API_Models/Application/SearchSuggestion.h
  Artsy/Models/API_Models/Application/SearchSuggestion.m
  CHANGELOG.yml
Labels: Jira Synced

#2773 Fix for fair component search 📱
  Artsy.xcodeproj/project.pbxproj
  Artsy/View_Controllers/App_Navigation/ARTopMenuViewController.m
  Artsy/View_Controllers/Fair/ARFairComponentViewController+Eigen.h
  Artsy/View_Controllers/Fair/ARFairComponentViewController+Eigen.m
  Artsy/View_Controllers/Fair/ARFairSearchViewController.m
  Artsy/View_Controllers/Fair/ARFairViewController.m
  Artsy/View_Controllers/Search/ARSearchViewController+Private.h
  Artsy/View_Controllers/Search/ARSearchViewController.m
  Artsy/View_Controllers/Search/UIViewController+Search.h
  Artsy/View_Controllers/Search/UIViewController+Search.m
  Artsy_Tests/View_Controller_Tests/Fair/ARFairSearchViewControllerTests.m
  Artsy_Tests/View_Controller_Tests/Fair/ARFairViewControllerTests.m
  CHANGELOG.yml
Labels: Jira Synced

#2776 Fixes crash with opening search on Fair/Show components
  Artsy/View_Controllers/Util/ARNavigationController.m
  Artsy_Tests/View_Controller_Tests/Util/ARNavigationControllerTests.m
  CHANGELOG.yml
Labels: Jira Synced

#2782 Fix back button hiding, routing improvements
  Artsy/App/ARAppDelegate+Emission.m
  Artsy/App/ARSwitchBoard.m
  Artsy/View_Controllers/App_Navigation/ARTopMenuViewController.m
  Artsy/View_Controllers/Fair/ARFairSearchViewController.m
  CHANGELOG.yml
  Podfile.lock
Labels: Jira Synced

#2785 Fixes beta deploys #trivial
  fastlane/Fastfile
Labels: Merge On Green
