Repository artsy/eigen, pull requests merged in 2019-06, with the labels that each got.

#2841 [Artwork] Load below the fold content of legacy VC
  Artsy/View_Controllers/Artwork/ARArtworkViewController.m
  Artsy_Tests/View_Controller_Tests/Artwork/ARArtworkViewControllerTests.m
  CHANGELOG.yml
Labels: Jira Synced, Merge On Green

#2844 Updates Emission to 1.12.1
  Podfile.lock
Labels: Merge On Green

#2848 PURCHASE-1182: Append /v2 to the metaphysics config sent to emission from eigen
  Artsy/App/ARAppDelegate+Emission.m
Labels: Jira Synced

#2849 Adds route for artwork classifications FAQ page
  Artsy/App/ARSwitchBoard.m
  Podfile.lock
Labels: Merge On Green
