Repository artsy/eigen, pull requests merged in 2020-05, with the labels that each got.

#3234 Suppress build log output from beta builds #trivial
  fastlane/Fastfile
Labels: Merge On Green

#3261 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3241 [MX-300] - Feature flag for consignments tab
  Artsy.xcodeproj/project.pbxproj
  Artsy/App/ARAppDelegate+Emission.m
  Artsy/App/ARAppNotificationsDelegate.m
  Artsy/App/AROptions.h
  Artsy/App/AROptions.m
  Artsy/Resources/Assets/Navigation/nav_sales@2x.png
  Artsy/Resources/Assets/Navigation/nav_sales@3x.png
  Artsy/View_Controllers/App_Navigation/ARNavigationTabButtonWithBadge.h
  Artsy/View_Controllers/App_Navigation/ARNavigationTabButtonWithBadge.m
  Artsy/View_Controllers/App_Navigation/ARTopMenuNavigationDataSource.h
  Artsy/View_Controllers/App_Navigation/ARTopMenuNavigationDataSource.m
  Artsy/View_Controllers/App_Navigation/ARTopMenuViewController.h
  Artsy/View_Controllers/App_Navigation/ARTopMenuViewController.m
  Artsy/View_Controllers/Web_Browsing/ARTopMenuInternalMobileWebViewController.h
  Artsy/View_Controllers/Web_Browsing/ARTopMenuInternalMobileWebViewController.m
  Artsy/Views/Utilities/ARTabContentView.h
  Artsy_Tests/View_Controller_Tests/App_Menu/ARTopMenuNavigationDataSourceSpec.m
  Artsy_Tests/View_Controller_Tests/App_Menu/ARTopMenuViewControllerSpec.m
  CHANGELOG.yml
  docs/developing_a_feature.md
  emission/Pod/Classes/ViewControllers/ARSalesComponentViewController.h
  emission/Pod/Classes/ViewControllers/ARSalesComponentViewController.m
  emission/Pod/Classes/ViewControllers/ARSearchComponentViewController.m
  src/lib/AppRegistry.tsx
  src/lib/Components/Consignments/Screens/Confirmation.tsx
  src/lib/Components/Consignments/Screens/__tests__/Confirmation-tests.tsx
Labels: Merge On Green

#3272 [Refactor] Move consign app to Scenes folder
  src/lib/AppRegistry.tsx
  src/lib/Containers/Inquiry.tsx
  src/lib/Scenes/Consignments/Components/ArtworkConsignmentTodo.tsx
  src/lib/Scenes/Consignments/Components/BottomAlignedButton.tsx
  src/lib/Scenes/Consignments/Components/CircleImage.tsx
  src/lib/Scenes/Consignments/Components/CloseButton.tsx
  src/lib/Scenes/Consignments/Components/FormElements.tsx
  src/lib/Scenes/Consignments/Components/ImageSelection.tsx
  src/lib/Scenes/Consignments/Components/NavButton.tsx
  src/lib/Scenes/Consignments/Components/SearchResults.tsx
  src/lib/Scenes/Consignments/Components/TextArea.tsx
  src/lib/Scenes/Consignments/Components/TextInput.tsx
  src/lib/Scenes/Consignments/Components/Toggle.tsx
  src/lib/Scenes/Consignments/Components/__tests__/ArtworkConsignmentTodo-tests.tsx
  src/lib/Scenes/Consignments/Components/__tests__/CircleImage-tests.tsx
  src/lib/Scenes/Consignments/Components/__tests__/FormElements-tests.tsx
  src/lib/Scenes/Consignments/Components/__tests__/ImageSelection-tests.tsx
  src/lib/Scenes/Consignments/Components/__tests__/TextArea-tests.tsx
  src/lib/Scenes/Consignments/Components/__tests__/TextInput-tests.tsx
  src/lib/Scenes/Consignments/Components/__tests__/Toggle-tests.tsx
  src/lib/Scenes/Consignments/Screens/Confirmation.tsx
  src/lib/Scenes/Consignments/Screens/ConsignmentsArtist.tsx
  src/lib/Scenes/Consignments/Screens/Edition.tsx
  src/lib/Scenes/Consignments/Screens/Location.tsx
  src/lib/Scenes/Consignments/Screens/Metadata.tsx
  src/lib/Scenes/Consignments/Screens/Overview.tsx
  src/lib/Scenes/Consignments/Screens/Provenance.tsx
  src/lib/Scenes/Consignments/Screens/SelectFromPhotoLibrary.tsx
  src/lib/Scenes/Consignments/Screens/Welcome.tsx
  src/lib/Scenes/Consignments/Screens/__tests__/Confirmation-tests.tsx
  src/lib/Scenes/Consignments/Screens/__tests__/ConsignmentsArtist-tests.tsx
  src/lib/Scenes/Consignments/Screens/__tests__/Edition-tests.tsx
  src/lib/Scenes/Consignments/Screens/__tests__/Location-tests.tsx
  src/lib/Scenes/Consignments/Screens/__tests__/Metadata-tests.tsx
  src/lib/Scenes/Consignments/Screens/__tests__/Overview-analytics-tests.tsx
  src/lib/Scenes/Consignments/Screens/__tests__/Overview-local-storage-tests.tsx
  src/lib/Scenes/Consignments/Screens/__tests__/Overview-tests.tsx
  src/lib/Scenes/Consignments/Screens/__tests__/Overview-uploading-tests.tsx
  src/lib/Scenes/Consignments/Screens/__tests__/Provenance-tests.tsx
  src/lib/Scenes/Consignments/Screens/__tests__/SelectFromPhotoLibrary-tests.tsx
  src/lib/Scenes/Consignments/Screens/__tests__/Welcome-tests.tsx
  src/lib/Scenes/Consignments/Screens/__tests__/__snapshots__/Metadata-tests.tsx.snap
  src/lib/Scenes/Consignments/Submission/Gemini/createGeminiAssetWithS3Credentials.ts
  src/lib/Scenes/Consignments/Submission/Gemini/getConvectionGeminiKey.ts
  src/lib/Scenes/Consignments/Submission/Gemini/getGeminiCredentialsForEnvironment.ts
  src/lib/Scenes/Consignments/Submission/__tests__/consignmentSetupToSubmission-tests.ts
  src/lib/Scenes/Consignments/Submission/addAssetToConsignment.ts
  src/lib/Scenes/Consignments/Submission/consignmentSetupToSubmission.ts
  src/lib/Scenes/Consignments/Submission/createConsignmentSubmission.ts
  src/lib/Scenes/Consignments/Submission/geminiUploadToS3.ts
  src/lib/Scenes/Consignments/Submission/updateConsignmentSubmission.ts
  src/lib/Scenes/Consignments/Submission/uploadPhotoToGemini.ts
  src/lib/Scenes/Consignments/Typography/index.tsx
  src/lib/Scenes/Consignments/__tests__/fixtures/places.json
  src/lib/Scenes/Consignments/__tests__/index-tests.tsx
  src/lib/Scenes/Consignments/index.tsx
Labels: Merge On Green

#3273 [Consignments] Stub v2 folder structure
  src/lib/Scenes/Consignments/Screens/Overview.tsx
  src/lib/Scenes/Consignments/index.tsx
  src/lib/Scenes/Consignments/v2/Components/.gitkeep
  src/lib/Scenes/Consignments/v2/Screens/ConsignmentsHome/index.tsx
  src/lib/Scenes/Consignments/v2/Screens/ConsignmentsSubmission/Components/.gitkeep
  src/setupJest.ts
  typings/emission.d.ts
Labels: Consignments, Merge On Green

#3269 Fastlane notify on beta deploy Sentry failures #trivial
  fastlane/Fastfile
  fastlane/README.md
Labels: Merge On Green

#3266 [MX-309] Fixes missing artworks from partner page
  CHANGELOG.yml
  src/__generated__/PartnerArtwork_partner.graphql.ts
  src/__generated__/PartnerQuery.graphql.ts
  src/__generated__/PartnerRefetchQuery.graphql.ts
  src/lib/Scenes/Partner/Components/PartnerArtwork.tsx
Labels: Merge On Green

#3276 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3278 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3274 [Consignments] Build out static v2 landing
  src/lib/Scenes/Consignments/index.tsx
  src/lib/Scenes/Consignments/v2/Screens/ConsignmentsHome/index.tsx
Labels: Consignments

#3275 [MX-310] Improved Artist Rail interactions
  CHANGELOG.yml
  src/__generated__/ArtistCard_artist.graphql.ts
  src/__generated__/ArtistRailFollowMutation.graphql.ts
  src/__generated__/ArtistRailNewSuggestionQuery.graphql.ts
  src/__generated__/ArtistRail_rail.graphql.ts
  src/__generated__/HomeQuery.graphql.ts
  src/__generated__/HomeRefetchQuery.graphql.ts
  src/lib/Components/Disappearable.tsx
  src/lib/Components/Home/ArtistRails/ArtistCard.tsx
  src/lib/Components/Home/ArtistRails/ArtistRail.tsx
  src/lib/Components/Home/CardRailFlatList.tsx
  src/lib/Components/SectionTitle.tsx
  src/lib/Components/__tests__/Disappearable-tests.tsx
  src/lib/Scenes/Home/Components/ArtworkRail.tsx
  src/lib/Scenes/Home/Home.tsx
  src/setupJest.ts
Labels: Merge On Green

#3264 [MX-297] - Add city guide entry in search behind flag
  Artsy/App/ARAppDelegate+Emission.m
  Artsy/App/ARSwitchBoard.m
  Artsy/Navigation_Transitions/ARDefaultNavigationTransition.m
  Artsy/View_Controllers/App_Navigation/ARTopMenuViewController.m
  Artsy/View_Controllers/Util/ARNavigationController.m
  Artsy_Tests/View_Controller_Tests/App_Menu/ARTopMenuViewControllerSpec.m
  CHANGELOG.yml
  emission/Pod/Classes/ViewControllers/ARMapContainerViewController.m
  images/city-guide-bg.png
  images/city-guide-bg@2x.png
  images/city-guide-bg@3x.png
  src/lib/Scenes/Artwork/Components/AboutArtist.tsx
  src/lib/Scenes/Artwork/Components/AboutWork.tsx
  src/lib/Scenes/Artwork/Components/ArtworkDetails.tsx
  src/lib/Scenes/Artwork/Components/ArtworkHistory.tsx
  src/lib/Scenes/Artwork/Components/ImageCarousel/ImageCarousel.tsx
  src/lib/Scenes/Artwork/Components/ImageCarousel/ImageCarouselEmbedded.tsx
  src/lib/Scenes/Artwork/Components/__tests__/AboutWork-tests.tsx
  src/lib/Scenes/City/CityPicker.tsx
  src/lib/Scenes/Map/GlobalMap.tsx
  src/lib/Scenes/Search/Search.tsx
  src/lib/Scenes/Search/SearchEmptyState.tsx
  src/lib/Scenes/Search/__tests__/Search-tests.tsx
  src/lib/Scenes/Search/__tests__/SearchEmptyState-tests.tsx
  src/lib/utils/__tests__/hardware-tests.ts
  src/lib/utils/hardware.ts
Labels: Merge On Green

#3282 Update metaphysics schema
  data/schema.graphql
  src/__generated__/ViewingRoomHeader_viewingRoom.graphql.ts
  src/__generated__/ViewingRoom_viewingRoom.graphql.ts
Labels: Merge On Green

#3279 Show number of full days in emission Ticker, not just number of days in month
  src/lib/Components/Countdown/Ticker.tsx
  src/lib/Components/Countdown/__tests__/Ticker-tests.tsx
Labels: Jira Synced

#3286 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3284 [MX-291] Adds collections to home page
  CHANGELOG.yml
  src/__generated__/CollectionsRailTestsQuery.graphql.ts
  src/__generated__/CollectionsRail_collectionsModule.graphql.ts
  src/__generated__/HomeQuery.graphql.ts
  src/__generated__/HomeRefetchQuery.graphql.ts
  src/__generated__/Home_homePage.graphql.ts
  src/lib/Scenes/Home/Components/CollectionsRail.tsx
  src/lib/Scenes/Home/Components/__tests__/CollectionsRail-tests.tsx
  src/lib/Scenes/Home/Home.tsx
Labels: Merge On Green

#3288 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3287 [MX-308] Fixes Home tab's skeleton loader
  CHANGELOG.yml
  src/lib/Scenes/Home/Home.tsx
Labels: Jira Synced, Merge On Green

#3289 Scrolls rails back to starting position without animation #trivial
  src/lib/Components/Home/ArtistRails/ArtistRail.tsx
  src/lib/Scenes/Home/Components/ArtworkRail.tsx
  src/lib/Scenes/Home/Components/CollectionsRail.tsx
  src/lib/Scenes/Home/Components/FairsRail.tsx
  src/lib/Scenes/Home/Components/SalesRail.tsx
Labels: Merge On Green

#3294 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3281 [FX-1916] add border for collection zero state
  src/lib/Scenes/Collection/Screens/CollectionArtworks.tsx
Labels: Merge On Green

#3295 Finishing touches for 6.4.4 release #trivial
  fastlane/metadata/en-US/release_notes.txt
  src/__generated__/HomeQuery.graphql.ts
  src/__generated__/HomeRefetchQuery.graphql.ts
  src/__generated__/Home_homePage.graphql.ts
  src/lib/Scenes/Home/Components/FairsRail.tsx
  src/lib/Scenes/Home/Components/SmallTileRail.tsx
  src/lib/Scenes/Home/Home.tsx
Labels: Jira Synced, Merge On Green

#3300 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3293 Adding some docs for the tracking
  docs/analytics_and_tracking.md
Labels: Merge On Green

#3302 Updates for 6.4.5 development
  Artsy Stickers/Info.plist
  Artsy/App_Resources/Artsy-Info.plist
  CHANGELOG.yml
Labels: Merge On Green

#3296 Refine static layout of sell tab's artist list
  src/lib/Scenes/Consignments/v2/Screens/ConsignmentsHome/ArtistList.tsx
  src/lib/Scenes/Consignments/v2/Screens/ConsignmentsHome/index.tsx
Labels: Merge On Green

#3290 Updates the app map
  docs/map_to_the_app.md
Labels: Merge On Green

#3298 Adds total # to collections on Home #trivial
  src/__generated__/CollectionsRailTestsQuery.graphql.ts
  src/__generated__/CollectionsRail_collectionsModule.graphql.ts
  src/__generated__/HomeQuery.graphql.ts
  src/__generated__/HomeRefetchQuery.graphql.ts
  src/lib/Scenes/Home/Components/CollectionsRail.tsx
Labels: Merge On Green

#3311 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3304 [CSGN-186] Connect sell tab/landing page/artist list to MP via relay
  src/__generated__/ArtistList_artists.graphql.ts
  src/__generated__/ConsignmentsHomeQuery.graphql.ts
  src/__generated__/ConsignmentsHome_artists.graphql.ts
  src/lib/Scenes/Consignments/index.tsx
  src/lib/Scenes/Consignments/v2/Screens/ConsignmentsHome/ArtistList.tsx
  src/lib/Scenes/Consignments/v2/Screens/ConsignmentsHome/index.tsx
Labels: Merge On Green

#3299 [MX-277] - Home analytics
  CHANGELOG.yml
  package.json
  src/__generated__/FairsRail_fairsModule.graphql.ts
  src/__generated__/HomeQuery.graphql.ts
  src/__generated__/HomeRefetchQuery.graphql.ts
  src/__generated__/SalesRail_salesModule.graphql.ts
  src/__generated__/SmallTileRail_artworks.graphql.ts
  src/lib/Components/ArtworkGrids/ArtworkGridItem.tsx
  src/lib/Components/ArtworkGrids/GenericGrid.tsx
  src/lib/Components/Home/ArtistRails/ArtistCard.tsx
  src/lib/Components/Home/ArtistRails/ArtistRail.tsx
  src/lib/Containers/WorksForYou.tsx
  src/lib/Scenes/Home/Components/ArtworkRail.tsx
  src/lib/Scenes/Home/Components/CollectionsRail.tsx
  src/lib/Scenes/Home/Components/FairsRail.tsx
  src/lib/Scenes/Home/Components/SalesRail.tsx
  src/lib/Scenes/Home/Components/SmallTileRail.tsx
  src/lib/Scenes/Home/Components/__tests__/CollectionsRail-tests.tsx
  src/lib/Scenes/Home/Components/__tests__/FairsRail-tests.tsx
  src/lib/Scenes/Home/Components/__tests__/SalesRail-tests.tsx
  src/lib/Scenes/Home/Home.tsx
  src/lib/Scenes/Home/__tests__/homeAnalytics-tests.ts
  src/lib/Scenes/Home/homeAnalytics.ts
  yarn.lock
Labels: Merge On Green

#3312 [CSGN-188] Update sell landing page layout according to new specs
  src/lib/Scenes/Consignments/v2/Screens/ConsignmentsHome/ArtistList.tsx
  src/lib/Scenes/Consignments/v2/Screens/ConsignmentsHome/index.tsx
Labels: Merge On Green

#3317 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3320 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3315 Wire up existing form to new landing
  Artsy/App/ARSwitchBoard.m
  emission/Pod/Classes/ViewControllers/ARNewSubmissionFormComponentViewController.h
  emission/Pod/Classes/ViewControllers/ARNewSubmissionFormComponentViewController.m
  src/lib/AppRegistry.tsx
  src/lib/Scenes/Consignments/index.tsx
  src/lib/Scenes/Consignments/v2/Screens/ConsignmentsHome/index.tsx
  src/lib/Scenes/MyCollection/NewSubmissionForm/NewSubmissionForm.tsx
  src/lib/Scenes/MyCollection/NewSubmissionForm/index.tsx
Labels: Merge On Green

#3314 Viewing rooms header updates [GALL-2845]
  Artsy.xcodeproj/project.pbxproj
  Artsy/App/ARSwitchBoard.m
  Artsy/View_Controllers/AREigenViewingRoomComponentViewController.h
  Artsy/View_Controllers/AREigenViewingRoomComponentViewController.m
  CHANGELOG.yml
  emission/Pod/Classes/ViewControllers/ARViewingRoomComponentViewController.h
  emission/Pod/Classes/ViewControllers/ARViewingRoomComponentViewController.m
  src/__generated__/ViewingRoomHeaderTestsQuery.graphql.ts
  src/__generated__/ViewingRoomHeader_viewingRoom.graphql.ts
  src/__generated__/ViewingRoomQuery.graphql.ts
  src/__generated__/ViewingRoomTestsQuery.graphql.ts
  src/lib/Scenes/ViewingRoom/Components/ViewingRoomHeader.tsx
  src/lib/Scenes/ViewingRoom/Components/__tests__/ViewingRoomHeader-tests.tsx
Labels: Merge On Green

#3326 Add react-native-linear-gradient + viewing rooms tweaks
  CHANGELOG.yml
  Podfile
  Podfile.lock
  package.json
  src/lib/Components/ArtworkTileRail/ArtworkTileRail.tsx
  src/lib/Scenes/ViewingRoom/Components/ViewingRoomArtworkRail.tsx
  src/lib/Scenes/ViewingRoom/Components/ViewingRoomHeader.tsx
  src/lib/Scenes/ViewingRoom/ViewingRoom.tsx
  src/lib/Scenes/ViewingRoom/ViewingRoomArtworks.tsx
  yarn.lock
Labels: Merge On Green

#3321 Update metaphysics schema
  .circleci/config.yml
  data/schema.graphql
Labels: Merge On Green

#3331 Update metaphysics schema
  data/schema.graphql
  src/__generated__/ViewingRoomHeader_viewingRoom.graphql.ts
  src/__generated__/ViewingRoom_viewingRoom.graphql.ts
Labels: Merge On Green

#3333 [CSGN-203] Replace icon for Receive Payment section of sell tab landing page
  src/lib/Scenes/Consignments/v2/Screens/ConsignmentsHome/index.tsx
Labels: Merge On Green

#3334 [CSGN-174] Hide consign sash when sell tab feature flag is enabled
  CHANGELOG.yml
  src/lib/Scenes/Home/Home.tsx
Labels: Merge On Green

#3337 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3342 Update metaphysics schema
  data/schema.graphql
  src/__generated__/ArtistHeaderFollowArtistMutation.graphql.ts
  src/__generated__/ArtistListItemFollowArtistMutation.graphql.ts
  src/__generated__/ArtistRailFollowMutation.graphql.ts
  src/__generated__/ArtworkActionsSaveMutation.graphql.ts
  src/__generated__/CollectionTestsQuery.graphql.ts
  src/__generated__/ConfirmBidCreateBidderPositionMutation.graphql.ts
  src/__generated__/ConfirmBidCreateCreditCardMutation.graphql.ts
  src/__generated__/ConfirmBidUpdateUserMutation.graphql.ts
  src/__generated__/ContextCardFollowMutation.graphql.ts
  src/__generated__/EventMutation.graphql.ts
  src/__generated__/FairBoothHeaderMutation.graphql.ts
  src/__generated__/FairBoothPreviewMutation.graphql.ts
  src/__generated__/FollowArtistButtonMutation.graphql.ts
  src/__generated__/HeaderFollowGeneMutation.graphql.ts
  src/__generated__/PartnerCardFollowMutation.graphql.ts
  src/__generated__/PartnerFollowButtonFollowMutation.graphql.ts
  src/__generated__/RegistrationCreateBidderMutation.graphql.ts
  src/__generated__/RegistrationCreateCreditCardMutation.graphql.ts
  src/__generated__/RegistrationUpdateUserMutation.graphql.ts
  src/__generated__/SavedFairItemRowMutation.graphql.ts
  src/__generated__/SendConversationMessageMutation.graphql.ts
  src/__generated__/ShowHeaderFollowShowMutation.graphql.ts
  src/__generated__/ShowItemRowMutation.graphql.ts
  src/__generated__/UpdateConversationMutation.graphql.ts
  src/__generated__/createGeminiAssetWithS3CredentialsMutation.graphql.ts
  src/__generated__/getGeminiCredentialsForEnvironmentMutation.graphql.ts
Labels: Merge On Green

#3339 Add artwork description to Viewing Room artworks view
  CHANGELOG.yml
  src/__generated__/ViewingRoomArtworksQuery.graphql.ts
  src/__generated__/ViewingRoomArtworksRendererQuery.graphql.ts
  src/__generated__/ViewingRoomArtworksTestsQuery.graphql.ts
  src/__generated__/ViewingRoomArtworks_viewingRoom.graphql.ts
  src/__generated__/ViewingRoomQuery.graphql.ts
  src/__generated__/ViewingRoomTestsQuery.graphql.ts
  src/lib/Scenes/ViewingRoom/ViewingRoomArtworks.tsx
  src/lib/Scenes/ViewingRoom/__tests__/ViewingRoomArtworks-tests.tsx
Labels: Merge On Green

#3335 Add docs for deploying a hotfix #trivial
  docs/deploy_a_hotfix.md
Labels: Merge On Green

#3348 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3349 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3343 [Consignments] Wire up Recently Sold
  src/__generated__/ConsignmentsHomeQuery.graphql.ts
  src/__generated__/ConsignmentsHome_artists.graphql.ts
  src/__generated__/RecentlySold_artists.graphql.ts
  src/lib/Scenes/Consignments/v2/Screens/ConsignmentsHome/ArtistList.tsx
  src/lib/Scenes/Consignments/v2/Screens/ConsignmentsHome/Components/ArtistList.tsx
  src/lib/Scenes/Consignments/v2/Screens/ConsignmentsHome/Components/Footer.tsx
  src/lib/Scenes/Consignments/v2/Screens/ConsignmentsHome/Components/Header.tsx
  src/lib/Scenes/Consignments/v2/Screens/ConsignmentsHome/Components/HowItWorks.tsx
  src/lib/Scenes/Consignments/v2/Screens/ConsignmentsHome/Components/RecentlySold.tsx
  src/lib/Scenes/Consignments/v2/Screens/ConsignmentsHome/Components/TextContainer.tsx
  src/lib/Scenes/Consignments/v2/Screens/ConsignmentsHome/index.tsx
  src/lib/utils/track/schema.ts
Labels: Merge On Green

#3355 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3358 [CSGN-201] make copy changes to consignment app
  src/lib/Scenes/Consignments/v2/Screens/ConsignmentsHome/Components/ArtistList.tsx
  src/lib/Scenes/Consignments/v2/Screens/ConsignmentsHome/Components/Footer.tsx
  src/lib/Scenes/Consignments/v2/Screens/ConsignmentsHome/Components/Header.tsx
  src/lib/Scenes/Consignments/v2/Screens/ConsignmentsHome/Components/HowItWorks.tsx
  src/lib/Scenes/Consignments/v2/Screens/ConsignmentsHome/Components/RecentlySold.tsx
Labels: Merge On Green

#3360 Fix show href creation
  fastlane/metadata/en-US/release_notes.txt
  src/lib/utils/router.ts
Labels: Merge On Green

#3357 Don't show 'sold for' message if no realized price
  src/lib/Scenes/Consignments/v2/Screens/ConsignmentsHome/Components/RecentlySold.tsx
  src/lib/Scenes/Consignments/v2/Screens/ConsignmentsHome/Components/__tests__/RecentlySold-tests.tsx
Labels: Merge On Green

#3370 [CSGN-212] Make consignment landing page rails full-bleed on swipe
  src/lib/Scenes/Consignments/v2/Screens/ConsignmentsHome/Components/ArtistList.tsx
  src/lib/Scenes/Consignments/v2/Screens/ConsignmentsHome/Components/RecentlySold.tsx
Labels: Merge On Green

#3369 Preparing for development, version 6.4.7 #trivial
  Artsy Stickers/Info.plist
  Artsy/App_Resources/Artsy-Info.plist
  CHANGELOG.yml
Labels: Merge On Green

#3367 [MX-323] Put BMW attribution on city guide CTA
  CHANGELOG.yml
  src/lib/Scenes/City/CityBMWSponsorship.tsx
  src/lib/Scenes/City/CityPicker.tsx
  src/lib/Scenes/City/Components/SavedEventSection/index.tsx
  src/lib/Scenes/Fair/Screens/FairBMWArtActivation.tsx
  src/lib/Scenes/Search/CityGuideCTA.tsx
  src/lib/Scenes/Search/__tests__/CityGuideCTA-tests.tsx
  src/lib/data/ScreenSizes/screenSizes.tsx
Labels: Merge On Green

#3366 [MX-277] - Fix updated analytics actions being tracked as screen views
  Artsy/App/ARAppDelegate+Emission.m
  CHANGELOG.yml
Labels: Merge On Green

#3372 Replace enzyme usages with react-test-renderer
  src/lib/Scenes/Home/Components/__tests__/EmailConfirmationBanner-tests.tsx
Labels: Merge On Green

#3373 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3374 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3375 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3376 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3380 Fix no-text-outside-Text issue
  src/lib/Components/ArtworkTileRail/ArtworkTileRailCard.tsx
Labels: Merge On Green

#3381 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3363 Viewing room QA [GALL-2865]
  CHANGELOG.yml
  src/__generated__/ViewingRoomArtworksQuery.graphql.ts
  src/__generated__/ViewingRoomArtworksRendererQuery.graphql.ts
  src/__generated__/ViewingRoomArtworksTestsQuery.graphql.ts
  src/__generated__/ViewingRoomArtworks_viewingRoom.graphql.ts
  src/__generated__/ViewingRoomQuery.graphql.ts
  src/__generated__/ViewingRoomTestsQuery.graphql.ts
  src/__generated__/ViewingRoom_viewingRoom.graphql.ts
  src/lib/Components/ArtworkTileRail/ArtworkTileRail.tsx
  src/lib/Scenes/ViewingRoom/Components/ViewingRoomArtworkRail.tsx
  src/lib/Scenes/ViewingRoom/Components/ViewingRoomViewWorksButton.tsx
  src/lib/Scenes/ViewingRoom/ViewingRoom.tsx
  src/lib/Scenes/ViewingRoom/ViewingRoomArtworks.tsx
  src/lib/Scenes/ViewingRoom/__tests__/ViewingRoom-tests.tsx
  src/lib/Scenes/ViewingRoom/__tests__/ViewingRoomArtworks-tests.tsx
  src/lib/utils/track/schema.ts
Labels: Merge On Green
