Repository artsy/eigen, pull requests merged in 2020-07, with the labels that each got.

#3492 [MX-361] Change Password Screen
  Artsy/App/ARSwitchBoard.m
  CHANGELOG.yml
  jest.config.js
  src/lib/AppRegistry.tsx
  src/lib/Components/Input/Input.tsx
  src/lib/Scenes/MyAccount/Components/MyAccountFieldEditScreen.tsx
  src/lib/Scenes/MyAccount/MyAccount.tsx
  src/lib/Scenes/MyAccount/MyAccountEditEmail.tsx
  src/lib/Scenes/MyAccount/MyAccountEditName.tsx
  src/lib/Scenes/MyAccount/MyAccountEditPassword.tsx
  src/lib/Scenes/MyAccount/MyAccountEditPhone.tsx
  src/lib/Scenes/MyAccount/__tests__/MyAccountEditPassword-tests.tsx
Labels: Merge On Green

#3519 [MX-380] Tweaks to BMW sponsorship #trivial
  images/bmw-logo.png
  images/bmw-logo@2x.png
  images/bmw-logo@3x.png
  src/lib/Scenes/City/CityBMWSponsorship.tsx
  src/lib/Scenes/City/CityPicker.tsx
Labels: Merge On Green

#3524 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3521 [CSGN-269] Stub out my collection artwork list
  src/lib/Scenes/Consignments/v2/Screens/MyCollectionArtworkList/MyCollectionArtworkList.tsx
Labels: Merge On Green

#3527 Add rake to gem file #trivial
  fastlane/Gemfile
Labels: Merge On Green

#3528 [MX-395] Privacy Request visual tweaks
  src/lib/Scenes/PrivacyRequest/PrivacyRequest.tsx
Labels: Jira Synced, Merge On Green

#3525 Update metaphysics schema
  data/schema.graphql
  src/__generated__/ViewingRoomSubsections_viewingRoom.graphql.ts
Labels: Merge On Green

#3517 [MX-336] Adds tracking for home promo space #trivial
  src/lib/Scenes/Home/Components/HomeHero.tsx
  src/lib/Scenes/Home/Components/__tests__/HomeHero-tests.tsx
Labels: Jira Synced, Merge On Green

#3539 remove some lines from settings
  .vscode/settings.json
Labels: Merge On Green

#3534 [MX-387][MX-388][MX-389] - Remove noisy sentry errors
  CHANGELOG.yml
  src/lib/Scenes/Artwork/Components/ImageCarousel/ImageCarousel.tsx
  src/lib/Scenes/Home/homeAnalytics.ts
  src/lib/utils/volleyClient.ts
Labels: Merge On Green

#3540 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3541 [MX-171] - Add referrer to deeplink analytics #trivial
  Artsy/App/ARAppActivityContinuationDelegate.m
  Artsy/App/ARAppDelegate+Analytics.h
  Artsy/App/ARAppDelegate+Analytics.m
  Artsy/App/ARAppDelegate.m
  Artsy_Tests/App_Tests/ARAppActivityContinuationDelegateTests.m
  CHANGELOG.yml
Labels: Merge On Green

#3526 [CSGN-268] Drive collection artwork detail with data
  Artsy/App/ARSwitchBoard.m
  emission/Pod/Classes/ViewControllers/ARMyCollectionArtworkDetailComponentViewController.h
  emission/Pod/Classes/ViewControllers/ARMyCollectionArtworkDetailComponentViewController.m
  src/lib/AppRegistry.tsx
  src/lib/Scenes/Consignments/v2/Screens/MyCollectionArtworkDetail/ArtworkMeta.tsx
  src/lib/Scenes/Consignments/v2/Screens/MyCollectionArtworkDetail/AuctionResults.tsx
  src/lib/Scenes/Consignments/v2/Screens/MyCollectionArtworkDetail/ConsignCTA.tsx
  src/lib/Scenes/Consignments/v2/Screens/MyCollectionArtworkDetail/Field.tsx
  src/lib/Scenes/Consignments/v2/Screens/MyCollectionArtworkDetail/Insights.tsx
  src/lib/Scenes/Consignments/v2/Screens/MyCollectionArtworkDetail/MyCollectionArtworkDetail.tsx
  src/lib/Scenes/Consignments/v2/Screens/MyCollectionArtworkList/MyCollectionArtworkList.tsx
  src/lib/Scenes/Consignments/v2/Screens/MyCollectionHome/MyCollectionHome.tsx
  src/lib/Scenes/Consignments/v2/State/navigationModel.tsx
Labels: Merge On Green

#3544 [My Collection] Update to use new FancyModal and select
  src/lib/Components/Select.tsx
  src/lib/Scenes/Consignments/v2/Boot.tsx
  src/lib/Scenes/Consignments/v2/Components/Modal.tsx
  src/lib/Scenes/Consignments/v2/Screens/MyCollectionAddArtwork/Components/MediumPicker.tsx
  src/lib/Scenes/Consignments/v2/Screens/MyCollectionAddArtwork/Components/SizePicker.tsx
  src/lib/Scenes/Consignments/v2/Screens/MyCollectionAddArtwork/Form/artworkSchema.tsx
  src/lib/Scenes/Consignments/v2/Screens/MyCollectionAddArtwork/Form/useArtworkForm.ts
  src/lib/Scenes/Consignments/v2/Screens/MyCollectionAddArtwork/MyCollectionAddArtwork.tsx
  src/lib/Scenes/Consignments/v2/Screens/MyCollectionAddArtwork/Screens/MyCollectionAddArtworkTitleAndYear.tsx
  src/lib/Scenes/Consignments/v2/Screens/MyCollectionArtworkList/MyCollectionArtworkList.tsx
  src/lib/Scenes/Consignments/v2/Screens/MyCollectionArtworkList/MyCollectionArtworkListItem.tsx
  src/lib/Scenes/Consignments/v2/Screens/MyCollectionHome/MyCollectionHome.tsx
  src/lib/Scenes/Consignments/v2/SellTabApp.tsx
  src/lib/Scenes/Consignments/v2/State/navigationModel.tsx
Labels: Consignments

#3545 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3543 Fix types in filter helper, remove strictness comments #trivial
  src/lib/Scenes/Collection/Helpers/FilterArtworksHelpers.ts
Labels: Merge On Green

#3546 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3547 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3550 [MX-251] Adds pull-to-refresh control on empty states of Favourites view
  CHANGELOG.yml
  src/lib/Scenes/Favorites/Components/Artists/index.tsx
  src/lib/Scenes/Favorites/Components/Artworks/index.tsx
  src/lib/Scenes/Favorites/Components/Categories/index.tsx
  src/lib/Scenes/Favorites/Components/Fairs/index.tsx
  src/lib/Scenes/Favorites/Components/Shows/index.tsx
Labels: Jira Synced

#3552 Minor tweak to Priacy Request typography #trivial
  src/lib/Scenes/PrivacyRequest/PrivacyRequest.tsx
Labels: Jira Synced, Merge On Green

#3553 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3548 Metaphysics v2 migration
  Artsy/App/ARAppDelegate+Emission.m
  Artsy/Constants/ARDefaults.m
  Artsy/Models/API_Models/Auctions/SaleArtwork.m
  Artsy/Models/API_Models/Live/LiveSale.m
  Artsy/Networking/ARNetworkConstants.m
  Artsy/Networking/ARRouter.m
  Artsy/Networking/conversations.graphql
  Artsy/Networking/favorites.graphql
  Artsy/Networking/static_sale_data.graphql
  Artsy/View_Controllers/Live_Auctions/LiveAuctionStaticDataFetcher.swift
  Artsy/View_Controllers/live_auctions_static.json
  Artsy_Tests/Model_Tests/SaleArtworkTests.m
  Artsy_Tests/Networking_Tests/API_Modules/ArtsyAPI+ArtworksTests.m
  Artsy_Tests/Networking_Tests/Live_Auctions/LiveAuctionStaticDataFetcherSpec.swift
  Artsy_Tests/Networking_Tests/Networking_Models/ARArtworkFavoritesNetworkModelTests.m
  Artsy_Tests/ReferenceImages/LiveAuctionLotListViewControllerTests/looks_good_by_default@3x.png
  Artsy_Tests/ReferenceImages/LiveAuctionLotListViewControllerTests/shows_the_selected_lot@3x.png
  Artsy_Tests/ReferenceImages/LiveAuctionViewControllerTests/handles_splitting_in_an_iPad@3x.png
  Artsy_Tests/View_Controller_Tests/Auction/AuctionViewControllerTests.swift
  CHANGELOG.yml
Labels: Jira Synced, Merge On Green

#3551 Fixes blank alert after successful password change #trivial
  src/lib/Scenes/MyAccount/MyAccountEditPassword.tsx
Labels: Jira Synced, Merge On Green

#3457 Viewing room list cards
  CHANGELOG.yml
  package.json
  patches/relay-hooks+3.5.1.patch
  src/__generated__/ViewingRoomsListItem_item.graphql.ts
  src/__generated__/ViewingRoomsListQuery.graphql.ts
  src/__generated__/ViewingRoomsListTestsQuery.graphql.ts
  src/__generated__/ViewingRoomsList_query.graphql.ts
  src/__generated__/ViewingRoomsList_viewingRooms.graphql.ts
  src/lib/AppRegistry.tsx
  src/lib/Scenes/ViewingRoom/Components/ViewingRoomsListItem.tsx
  src/lib/Scenes/ViewingRoom/ViewingRoomsList.tsx
  src/lib/Scenes/ViewingRoom/__tests__/ViewingRoomsList-tests.tsx
  storybook/storyLoader.js
  yarn.lock
Labels: Merge On Green

#3555 [MX-431] - Fix some warnings
  Artsy.xcodeproj/project.pbxproj
  Artsy/App/ARAnalyticsConstants.h
  Artsy/App/ARAnalyticsConstants.m
  Artsy/App/ARAppNotificationsDelegate.m
  Artsy/Categories/Apple/NSAttributedString+Additions.swift
  Artsy/Categories/Apple/UILabel+Styling.swift
  Artsy/Categories/Apple/UILabel+Typography.h
  Artsy/Categories/Apple/UILabel+Typography.m
  Artsy/Models/API_Models/LiveAuctionLot.h
  Artsy/View_Controllers/ARSerifNavigationViewController.h
  Artsy/View_Controllers/Auction/AuctionInformationViewController.swift
  Artsy/View_Controllers/Auction/AuctionViewController.swift
  Artsy/View_Controllers/Auction/RefinementOptionsViewController+Private.swift
  Artsy/View_Controllers/Core/ARModelInfiniteScrollViewController.swift
  Artsy/View_Controllers/Core/UIViewController+BlurredStatusView.swift
  Artsy/View_Controllers/Fair/ARProfileViewController.m
  Artsy/View_Controllers/Live_Auctions/LiveAuctionLotSetViewController.swift
  Artsy/View_Controllers/Live_Auctions/LiveAuctionLotViewController.swift
  Artsy/View_Controllers/Live_Auctions/LiveAuctionPlaceMaxBidViewController.swift
  Artsy/View_Controllers/Live_Auctions/LiveAuctionViewController.swift
  Artsy/View_Controllers/Live_Auctions/LiveAuctionsAdminViewController.swift
  Artsy/View_Controllers/Live_Auctions/ViewModels/LiveAuctionEventViewModel.swift
  Artsy/View_Controllers/Live_Auctions/ViewModels/LiveAuctionLotViewModel.swift
  Artsy/View_Controllers/SerifModalWebNavigationController.swift
  Artsy/View_Controllers/Web_Browsing/ARExternalWebBrowserViewController.m
  CHANGELOG.yml
  emission/Pod/Classes/Core/RCTScrollView+Artsy.m
Labels: Merge On Green

#3558 Enable noFallThroughCasesInSwitch typescript check #trivial
  tsconfig.json
Labels: Merge On Green

#3549 [MX-206] Fixes layout problem on LAI max bid selection screen
  Artsy/View_Controllers/Live_Auctions/Resources/LiveAuctions.storyboard
  Artsy_Tests/ReferenceImages/LiveAuctionBidViewControllerTests/bidding_on_0@3x.png
  Artsy_Tests/ReferenceImages/LiveAuctionBidViewControllerTests/bidding_on_2@3x.png
  Artsy_Tests/ReferenceImages/LiveAuctionBidViewControllerTests/networking__has_valid_snapshot_is_max_bidder@3x.png
  Artsy_Tests/ReferenceImages/LiveAuctionBidViewControllerTests/networking__has_valid_snapshot_network_issues@3x.png
  Artsy_Tests/ReferenceImages/LiveAuctionBidViewControllerTests/networking__has_valid_snapshot_not_max_bidder@3x.png
  Artsy_Tests/ReferenceImages/LiveAuctionBidViewControllerTests/networking__has_valid_snapshot_sold@3x.png
  Artsy_Tests/ReferenceImages/LiveAuctionBidViewControllerTests/networking__has_valid_snapshot_waiting@3x.png
  CHANGELOG.yml
Labels: Jira Synced

#3561 Create pull requests template
  docs/pull_request_template.md
Labels: Merge On Green

#3560 Visual QA #trivial
  src/lib/Scenes/MyProfile/MyProfile.tsx
  src/lib/Scenes/PrivacyRequest/PrivacyRequest.tsx
Labels: Jira Synced, Merge On Green

#3566 [MX-398] Fixes greyscale images getting displayed as red in AR VIR
  Artsy.xcodeproj/project.pbxproj
  Artsy/View_Controllers/ARVIR/ARAugmentedRealityConfig.m
  Artsy_Tests/View_Controller_Tests/ARVIR/ARAugmentedRealityConfigSpec.m
  Artsy_Tests/View_Controller_Tests/ARVIR/greyscaleImage.jpg
  CHANGELOG.yml
Labels: Jira Synced

#3564 [MX-422] - Fix rendering issue for filters with many options #trivial
  CHANGELOG.yml
  src/lib/Components/FilterModal.tsx
Labels: Merge On Green

#3567 Fixes problem displaying alert after promise await
  src/lib/Scenes/MyAccount/MyAccountEditPassword.tsx
Labels: Jira Synced, Merge On Green

#3568 [MX-423][MX-428] - Update show and artist page fonts #trivial
  src/lib/Components/LocationMap/index.tsx
  src/lib/Components/Show/ShowArtistsPreview.tsx
  src/lib/Components/Show/ShowArtworksPreview.tsx
  src/lib/Components/WorksForYou/Notification.tsx
  src/lib/Scenes/Show/Components/ShowHeader/ShowHeader.tsx
  src/lib/Scenes/Show/Components/Shows/Components/ShowItem.tsx
  src/lib/Scenes/Show/Components/Shows/index.tsx
  src/lib/Scenes/Show/Screens/Detail.tsx
Labels: Merge On Green

#3569 [MX-410] Feature screen
  Artsy/App/ARSwitchBoard.m
  Artsy/View_Controllers/Admin/ARAdminSettingsViewController.m
  CHANGELOG.yml
  src/__generated__/FeatureFeaturedLink_featuredLink.graphql.ts
  src/__generated__/FeatureHeader_feature.graphql.ts
  src/__generated__/FeatureQuery.graphql.ts
  src/__generated__/Feature_feature.graphql.ts
  src/lib/AppRegistry.tsx
  src/lib/Scenes/Feature/Feature.tsx
  src/lib/Scenes/Feature/__tests__/Feature-tests.tsx
  src/lib/Scenes/Feature/components/FeatureFeaturedLink.tsx
  src/lib/Scenes/Feature/components/FeatureHeader.tsx
  src/lib/Scenes/Feature/components/FeatureMarkdown.tsx
  src/lib/Scenes/Feature/components/__tests__/FeatureMarkdown-tests.tsx
  src/lib/tests/extractText.ts
Labels: Merge On Green

#3571 Add payment placeholder
  CHANGELOG.yml
  src/lib/Scenes/MyProfile/MyProfilePayment.tsx
Labels: Merge On Green

#3570 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3578 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3579 Make bottom tabs all black
  src/lib/Scenes/BottomTabs/BottomTabsIcon.tsx
Labels: Merge On Green

#3583 [MX-428] - Update fonts, spacing on show page #trivial
  src/lib/Components/HoursCollapsible.tsx
  src/lib/Scenes/Show/Components/Shows/Components/ShowItem.tsx
Labels: Merge On Green

#3584 Adding some links for QAing a new feature #trivial
  docs/developing_a_feature.md
Labels: Merge On Green

#3586 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3585 Update pull_request_template.md
  docs/pull_request_template.md
Labels: Jira Synced

#3581 [MX-424] Partner page design refresh
  CHANGELOG.yml
  src/__generated__/PartnerHeaderTestsQuery.graphql.ts
  src/__generated__/PartnerOverviewTestsQuery.graphql.ts
  src/lib/Components/Artist/ArtistHeader.tsx
  src/lib/Scenes/Partner/Components/PartnerFollowButton.tsx
  src/lib/Scenes/Partner/Components/PartnerHeader.tsx
  src/lib/Scenes/Partner/Components/PartnerLocationSection.tsx
  src/lib/Scenes/Partner/Components/PartnerOverview.tsx
  src/lib/Scenes/Partner/Components/PartnerShowRailItem.tsx
  src/lib/Scenes/Partner/Components/PartnerShows.tsx
  src/lib/Scenes/Partner/Components/PartnerShowsRail.tsx
  src/lib/Scenes/Partner/Components/__tests__/PartnerHeader-tests.tsx
  src/lib/Scenes/Partner/Components/__tests__/PartnerOverview-tests.tsx
  src/lib/utils/__tests__/formatText-tests.ts
  src/lib/utils/formatText.ts
Labels: Jira Synced, Merge On Green

#3588 Small things #trivial
  Artsy.xcodeproj/project.pbxproj
  Podfile
  Podfile.lock
  src/lib/Scenes/ViewingRoom/ViewingRoomArtwork.tsx
  src/lib/Scenes/ViewingRoom/ViewingRoomsList.tsx
Labels: Merge On Green

#3589 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3590 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3591 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3592 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3596 Update metaphysics schema
  data/schema.graphql
  src/__generated__/ConfirmBidUpdateUserMutation.graphql.ts
  src/__generated__/RegistrationUpdateUserMutation.graphql.ts
  src/__generated__/updateMyUserProfileMutation.graphql.ts
Labels: Merge On Green

#3597 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3593 simpler text #trivial
  docs/pull_request_template.md
Labels: Merge On Green

#3599 Prepare for next release #trivial
  Artsy Stickers/Info.plist
  Artsy/App_Resources/Artsy-Info.plist
  CHANGELOG.yml
Labels: Merge On Green

#3600 update relay-hooks and remove patch
  package.json
  patches/relay-hooks+3.5.1.patch
  yarn.lock
Labels: Merge On Green

#3603 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3605 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3602 Adds animation to filter button appearing / disappearing.
  CHANGELOG.yml
  src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
  src/lib/Components/FilterModal.tsx
  src/lib/Scenes/Collection/Collection.tsx
Labels: Merge On Green

#3604 Fixes problem selecting home tab initially
  Artsy/View_Controllers/App_Navigation/ARTopMenuViewController.m
  CHANGELOG.yml
Labels: Merge On Green

#3595 Viewing room featured rail
  Artsy/View_Controllers/Admin/ARAdminSettingsViewController.m
  CHANGELOG.yml
  src/__generated__/ViewingRoomsListFeaturedTestsQuery.graphql.ts
  src/__generated__/ViewingRoomsListFeatured_featured.graphql.ts
  src/__generated__/ViewingRoomsListQuery.graphql.ts
  src/lib/Scenes/ViewingRoom/Components/ViewingRoomArtworkRail.tsx
  src/lib/Scenes/ViewingRoom/Components/ViewingRoomsListFeatured.tsx
  src/lib/Scenes/ViewingRoom/Components/__tests__/ViewingRoomsListFeatured-tests.tsx
  src/lib/Scenes/ViewingRoom/ViewingRoomArtwork.tsx
  src/lib/Scenes/ViewingRoom/ViewingRoomsList.tsx
Labels: Jira Synced

#3607 Viewing rooms home rail
  CHANGELOG.yml
  src/__generated__/HomeQuery.graphql.ts
  src/__generated__/HomeRefetchQuery.graphql.ts
  src/__generated__/Home_featured.graphql.ts
  src/lib/Components/SectionTitle.tsx
  src/lib/Scenes/Home/Home.tsx
Labels: Jira Synced

#3608 Move card in eigen and fix
  CHANGELOG.yml
  jest.config.js
  src/lib/Scenes/ViewingRoom/Components/ViewingRoomsListFeatured.tsx
  src/lib/Scenes/ViewingRoom/Components/ViewingRoomsListItem.tsx
  src/lib/Scenes/ViewingRoom/Components/__tests__/ViewingRoomsListFeatured-tests.tsx
  src/lib/Scenes/ViewingRoom/ViewingRoomArtwork.tsx
  src/lib/Scenes/ViewingRoom/ViewingRoomsList.tsx
  src/palette/elements/Cards/CardTag.tsx
  src/palette/elements/Cards/LargeCard.tsx
  src/palette/elements/Cards/MediumCard.tsx
  src/palette/elements/Cards/SmallCard.tsx
  src/palette/elements/Cards/index.tsx
  src/palette/elements/index.tsx
  src/palette/index.tsx
  src/palette/package.json
Labels: Merge On Green

#3606 [MyCollection] Add artist search
  CHANGELOG.yml
  src/__generated__/AutosuggestResultsPaginationQuery.graphql.ts
  src/__generated__/AutosuggestResultsQuery.graphql.ts
  src/__generated__/AutosuggestResults_results.graphql.ts
  src/lib/Scenes/Consignments/v2/Screens/MyCollectionAddArtwork/Components/ArtistAutosuggest.tsx
  src/lib/Scenes/Consignments/v2/Screens/MyCollectionAddArtwork/Components/ArtistSearchResult.tsx
  src/lib/Scenes/Consignments/v2/Screens/MyCollectionAddArtwork/MyCollectionAddArtwork.tsx
  src/lib/Scenes/Consignments/v2/State/artworkModel.tsx
  src/lib/Scenes/Search/AutosuggestResults.tsx
  src/lib/Scenes/Search/Search.tsx
  src/lib/Scenes/Search/SearchContext.tsx
  src/lib/Scenes/Search/SearchResult.tsx
  src/lib/Scenes/Search/__tests__/AutosuggestResults-tests.tsx
  src/lib/Scenes/Search/__tests__/SearchResult-tests.tsx
  tsconfig.json
Labels: Consignments

#3609 [My Collection] Cleanup AddArtwork screen
  CHANGELOG.yml
  src/lib/AppRegistry.tsx
  src/lib/Components/ArtworkFilterOptions/ColorOptions.tsx
  src/lib/Components/ArtworkFilterOptions/FilterHeader.tsx
  src/lib/Components/ArtworkFilterOptions/MultiSelectOption.tsx
  src/lib/Components/ArtworkFilterOptions/SingleSelectOption.tsx
  src/lib/Components/FancyModal/FancyModal.tsx
  src/lib/Components/FancyModal/FancyModalHeader.tsx
  src/lib/Components/FilterModal.tsx
  src/lib/Components/Input/Input.tsx
  src/lib/Components/Input/InputTitle.tsx
  src/lib/Components/Select.tsx
  src/lib/Scenes/Consignments/v2/Boot.tsx
  src/lib/Scenes/Consignments/v2/Components/Modal.tsx
  src/lib/Scenes/Consignments/v2/Screens/MyCollectionAddArtwork/Components/ArrowButton.tsx
  src/lib/Scenes/Consignments/v2/Screens/MyCollectionAddArtwork/Components/ArtistAutosuggest.tsx
  src/lib/Scenes/Consignments/v2/Screens/MyCollectionAddArtwork/Components/MediumPicker.tsx
  src/lib/Scenes/Consignments/v2/Screens/MyCollectionAddArtwork/Components/PhotoPicker.tsx
  src/lib/Scenes/Consignments/v2/Screens/MyCollectionAddArtwork/Components/SizePicker.tsx
  src/lib/Scenes/Consignments/v2/Screens/MyCollectionAddArtwork/Form/artworkSchema.tsx
  src/lib/Scenes/Consignments/v2/Screens/MyCollectionAddArtwork/MyCollectionAddArtwork.tsx
  src/lib/Scenes/Consignments/v2/Screens/MyCollectionAddArtwork/Screens/MyCollectionAddArtworkAddPhotos.tsx
  src/lib/Scenes/Consignments/v2/Screens/MyCollectionAddArtwork/Screens/MyCollectionAddArtworkTitleAndYear.tsx
  src/lib/Scenes/Consignments/v2/State/artworkModel.tsx
  src/lib/Scenes/Consignments/v2/State/navigationModel.tsx
Labels: Consignments, Merge On Green

#3610 Prepares for 6.6.0 development
  Artsy Stickers/Info.plist
  Artsy/App_Resources/Artsy-Info.plist
  CHANGELOG.yml
  fastlane/metadata/en-US/release_notes.txt
Labels: Merge On Green

#3613 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3614 Temporarily removes Horizon deploy blocks.
  .circleci/config.yml
Labels: Merge On Green

#3612 [FX-2011] Enable Pagination By Click Button On Infinite Scroll Artworks Grid
  CHANGELOG.yml
  src/__generated__/ArtistSeriesArtworksInfiniteScrollGridQuery.graphql.ts
  src/__generated__/ArtistSeriesArtworksTestsQuery.graphql.ts
  src/__generated__/ArtistSeriesArtworks_artistSeries.graphql.ts
  src/__generated__/ArtistSeriesQuery.graphql.ts
  src/__generated__/ArtistSeriesTestsQuery.graphql.ts
  src/__generated__/InfiniteScrollArtworksGridTestsQuery.graphql.ts
  src/lib/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx
  src/lib/Components/ArtworkGrids/__tests__/InfiniteScrollArtworksGrid-tests.tsx
  src/lib/Scenes/ArtistSeries/ArtistSeries.tsx
  src/lib/Scenes/ArtistSeries/ArtistSeriesArtworks.tsx
  src/lib/Scenes/ArtistSeries/__tests__/ArtistSeries-tests.tsx
  src/lib/Scenes/ArtistSeries/__tests__/ArtistSeriesArtworks-tests.tsx
  src/lib/data/constants.ts
Labels: Merge On Green

#3618 Adds react-native-image-crop-picker
  Artsy.xcodeproj/project.pbxproj
  Podfile
  Podfile.lock
  package.json
  patches/react-native-image-crop-picker+0.32.2.patch
  yarn.lock
Labels: Merge On Green

#3617 Require only one app launch for an echo change to apply
  Artsy/App/ARSwitchBoard.h
  Artsy/App/ARSwitchBoard.m
  Artsy/App/ArtsyEcho.m
  Artsy/View_Controllers/Admin/AREchoContentsViewController.m
  Artsy_Tests/App_Tests/ARSwitchboard+EchoSpec.m
  CHANGELOG.yml
  emission/Pod/Classes/Core/AREmission.h
  emission/Pod/Classes/Core/AREmission.m
  emission/Pod/Classes/EigenCommunications/ARNotificationsManager.h
  emission/Pod/Classes/EigenCommunications/ARNotificationsManager.m
  src/lib/Scenes/Home/Home.tsx
  src/lib/Scenes/Home/__tests__/Home-tests.tsx
  src/lib/store/AppStore.tsx
  src/lib/store/NativeModel.ts
  src/setupJest.ts
  typings/emission.d.ts
Labels: Merge On Green

#3622 generalize and use in vr #trivial
  src/lib/Components/AnimatedBottomButton.tsx
  src/lib/Components/FilterModal.tsx
  src/lib/Scenes/Collection/__tests__/Collection-tests.tsx
  src/lib/Scenes/ViewingRoom/Components/ViewingRoomViewWorksButton.tsx
  src/lib/Scenes/ViewingRoom/ViewingRoom.tsx
  src/lib/Scenes/ViewingRoom/__tests__/ViewingRoom-tests.tsx
Labels: Merge On Green

#3620 dont crash if no image. just show an empty one. #trivial
  src/lib/Scenes/ViewingRoom/Components/ViewingRoomsListItem.tsx
Labels: Merge On Green

#3619 [MX-472] -Cleanup unused lab options, standardize keys
  Artsy/App/AROptions.h
  Artsy/App/AROptions.m
  Artsy_Tests/App_Tests/ARAppDelegateEmissionSpec.m
  CHANGELOG.yml
  src/setupJest.ts
  typings/emission.d.ts
Labels: Jira Synced, Merge On Green

#3625 add packager debug support to VS Code
  .vscode/launch.json
Labels: Merge On Green

#3624 [My Collection] Add ability for user to select photos
  src/lib/AppRegistry.tsx
  src/lib/Scenes/Consignments/v2/Boot.tsx
  src/lib/Scenes/Consignments/v2/Components/Modal.tsx
  src/lib/Scenes/Consignments/v2/Screens/AddArtwork/Components/ArrowButton.tsx
  src/lib/Scenes/Consignments/v2/Screens/AddArtwork/Components/ArtistAutosuggest.tsx
  src/lib/Scenes/Consignments/v2/Screens/AddArtwork/Components/ArtistSearchResult.tsx
  src/lib/Scenes/Consignments/v2/Screens/AddArtwork/Components/MediumPicker.tsx
  src/lib/Scenes/Consignments/v2/Screens/AddArtwork/Components/PhotoPicker.tsx
  src/lib/Scenes/Consignments/v2/Screens/AddArtwork/Components/SizePicker.tsx
  src/lib/Scenes/Consignments/v2/Screens/AddArtwork/Form/artworkSchema.tsx
  src/lib/Scenes/Consignments/v2/Screens/AddArtwork/Form/useArtworkForm.ts
  src/lib/Scenes/Consignments/v2/Screens/AddArtwork/Mutations/MyCollectionAddArtworkMutation.ts
  src/lib/Scenes/Consignments/v2/Screens/AddArtwork/Mutations/MyCollectionEditArtworkMutation.ts
  src/lib/Scenes/Consignments/v2/Screens/AddArtwork/MyCollectionAddArtwork.tsx
  src/lib/Scenes/Consignments/v2/Screens/AddArtwork/Screens/MyCollectionAddArtworkAddPhotos.tsx
  src/lib/Scenes/Consignments/v2/Screens/AddArtwork/Screens/MyCollectionAddArtworkTitleAndYear.tsx
  src/lib/Scenes/Consignments/v2/Screens/ArtworkDetail/ArtworkMeta.tsx
  src/lib/Scenes/Consignments/v2/Screens/ArtworkDetail/AuctionResults.tsx
  src/lib/Scenes/Consignments/v2/Screens/ArtworkDetail/ConsignCTA.tsx
  src/lib/Scenes/Consignments/v2/Screens/ArtworkDetail/Field.tsx
  src/lib/Scenes/Consignments/v2/Screens/ArtworkDetail/Insights.tsx
  src/lib/Scenes/Consignments/v2/Screens/ArtworkDetail/MyCollectionArtworkDetail.tsx
  src/lib/Scenes/Consignments/v2/Screens/ArtworkList/MyCollectionArtworkList.tsx
  src/lib/Scenes/Consignments/v2/Screens/ArtworkList/MyCollectionArtworkListItem.tsx
  src/lib/Scenes/Consignments/v2/Screens/Home/MyCollectionHome.tsx
  src/lib/Scenes/Consignments/v2/Screens/Home/MyCollectionMarketingHome.tsx
  src/lib/Scenes/Consignments/v2/Screens/MyCollectionAddArtwork/Screens/MyCollectionAddArtworkAddPhotos.tsx
  src/lib/Scenes/Consignments/v2/SellTabApp.tsx
  src/lib/Scenes/Consignments/v2/State/artworkModel.tsx
  src/lib/Scenes/Consignments/v2/State/navigationModel.tsx
Labels: Merge On Green

#3629 Removes partner follow count, fixes partner page for partners without profiles
  CHANGELOG.yml
  src/__generated__/PartnerHeaderTestsQuery.graphql.ts
  src/__generated__/PartnerHeader_partner.graphql.ts
  src/__generated__/PartnerQuery.graphql.ts
  src/__generated__/PartnerRefetchQuery.graphql.ts
  src/lib/Scenes/Partner/Components/PartnerFollowButton.tsx
  src/lib/Scenes/Partner/Components/PartnerHeader.tsx
  src/lib/Scenes/Partner/Components/__tests__/PartnerHeader-tests.tsx
Labels: Jira Synced, Merge On Green

#3630 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3631 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3633 [MX-467] Integrates Sailthru SDK
  Artsy.xcodeproj/project.pbxproj
  Artsy/App/ARAppDelegate.h
  Artsy/App/ARAppDelegate.m
  Artsy/App/ARAppNotificationsDelegate.m
  CHANGELOG.yml
  Podfile
  Podfile.lock
Labels: Jira Synced, Merge On Green

#3638 Removes Adjust SDK #trivial
  Artsy/App/ARAnalyticsConstants.h
  Artsy/App/ARAnalyticsConstants.m
  Artsy/App/ARAppActivityContinuationDelegate.m
  Artsy/App/ARAppDelegate+Analytics.m
  Artsy/App/ARAppDelegate.m
  Artsy/Networking/API_Modules/ARUserManager.m
  CHANGELOG.yml
  Podfile
  Podfile.lock
Labels: Merge On Green

#3623 Starts tracking auction page load time
  Artsy/View_Controllers/Auction/AuctionViewController.swift
  CHANGELOG.yml
Labels: Jira Synced, Merge On Green

#3636 Some fixes after VR QA session
  src/__generated__/HomeQuery.graphql.ts
  src/__generated__/HomeRefetchQuery.graphql.ts
  src/__generated__/ViewingRoomArtworkQuery.graphql.ts
  src/__generated__/ViewingRoomArtwork_artworksList.graphql.ts
  src/__generated__/ViewingRoomArtwork_viewingRoomInfo.graphql.ts
  src/__generated__/ViewingRoomHeaderTestsQuery.graphql.ts
  src/__generated__/ViewingRoomHeader_viewingRoom.graphql.ts
  src/__generated__/ViewingRoomQuery.graphql.ts
  src/__generated__/ViewingRoomSubsectionsTestsQuery.graphql.ts
  src/__generated__/ViewingRoomSubsections_viewingRoom.graphql.ts
  src/__generated__/ViewingRoomTestsQuery.graphql.ts
  src/__generated__/ViewingRoomsListFeaturedTestsQuery.graphql.ts
  src/__generated__/ViewingRoomsListFeatured_featured.graphql.ts
  src/__generated__/ViewingRoomsListItem_item.graphql.ts
  src/__generated__/ViewingRoomsListQuery.graphql.ts
  src/lib/Components/OpaqueImageView/OpaqueImageView.tsx
  src/lib/Scenes/Home/Home.tsx
  src/lib/Scenes/ViewingRoom/Components/ViewingRoomHeader.tsx
  src/lib/Scenes/ViewingRoom/Components/ViewingRoomSubsections.tsx
  src/lib/Scenes/ViewingRoom/Components/ViewingRoomViewWorksButton.tsx
  src/lib/Scenes/ViewingRoom/Components/ViewingRoomsListFeatured.tsx
  src/lib/Scenes/ViewingRoom/Components/ViewingRoomsListItem.tsx
  src/lib/Scenes/ViewingRoom/Components/__tests__/ViewingRoomHeader-tests.tsx
  src/lib/Scenes/ViewingRoom/ViewingRoom.tsx
  src/lib/Scenes/ViewingRoom/ViewingRoomArtwork.tsx
  src/lib/Scenes/ViewingRoom/ViewingRoomsList.tsx
  src/lib/Scenes/ViewingRoom/__tests__/ViewingRoom-tests.tsx
  src/palette/elements/Cards/LargeCard.tsx
  src/palette/elements/Cards/MediumCard.tsx
  src/palette/elements/Cards/SmallCard.tsx
Labels: Merge On Green

#3641 [MX-476] Ungates Home Promo space.
  Artsy/App/AROptions.h
  Artsy/App/AROptions.m
  CHANGELOG.yml
  src/lib/Scenes/Home/Home.tsx
  src/setupJest.ts
  typings/emission.d.ts
Labels: Jira Synced, Merge On Green

#3639 [MX-453] Add FancyModal nesting support
  CHANGELOG.yml
  src/__generated__/BottomTabsModelFetchCurrentUnreadConversationCountQuery.graphql.ts
  src/lib/AppRegistry.tsx
  src/lib/Components/FancyModal/FancyModal.tsx
  src/lib/Components/FancyModal/FancyModalCard.tsx
  src/lib/Components/FancyModal/FancyModalContext.tsx
  src/lib/Components/FancyModal/FancyModalHeader.tsx
  src/lib/Components/FilterModal.tsx
  src/lib/Scenes/BottomTabs/BottomTabsModel.ts
  src/lib/Scenes/MyAccount/Components/MyAccountFieldEditScreen.tsx
  src/lib/Scenes/MyProfile/MyProfilePaymentNewCreditCard.tsx
  src/lib/tests/flushPromiseQueue.ts
  src/lib/utils/ExecutionQueue.ts
  src/lib/utils/__tests__/ExecutionQueue-tests.ts
Labels: Merge On Green

#3642 [MyCollection] Cleanup AddArtwork screen
  src/lib/Scenes/Consignments/v2/Screens/AddArtwork/Form/artworkSchema.tsx
  src/lib/Scenes/Consignments/v2/Screens/AddArtwork/MyCollectionAddArtwork.tsx
  src/lib/Scenes/Consignments/v2/Screens/AddArtwork/Screens/MyCollectionAddArtworkAddPhotos.tsx
  src/lib/Scenes/Consignments/v2/Screens/AddArtwork/Screens/MyCollectionAddArtworkTitleAndYear.tsx
Labels: Merge On Green

#3640 [MX-469] Sends data to Sailthru
  Artsy.xcodeproj/project.pbxproj
  Artsy/App/ARAppDelegate+Analytics.m
  Artsy/App/ARSailthruIntegration.h
  Artsy/App/ARSailthruIntegration.m
  Artsy/Networking/API_Modules/ARUserManager.m
  CHANGELOG.yml
Labels: Jira Synced, Merge On Green

#3643 Fixes Sailthru SDK crash #trivial
  Artsy/App/ARSailthruIntegration.m
Labels: Merge On Green

#3644 Qa fixes 2
  package.json
  src/__generated__/PartnerQuery.graphql.ts
  src/__generated__/PartnerRefetchQuery.graphql.ts
  src/__generated__/PartnerShowsInfiniteScrollGridQuery.graphql.ts
  src/__generated__/PartnerShowsTestsQuery.graphql.ts
  src/__generated__/PartnerShows_partner.graphql.ts
  src/__generated__/ViewingRoomArtworkQuery.graphql.ts
  src/__generated__/ViewingRoomArtwork_viewingRoomInfo.graphql.ts
  src/lib/Components/ArtworkTileRail/ArtworkTileRail.tsx
  src/lib/Scenes/Home/Home.tsx
  src/lib/Scenes/Partner/Components/PartnerShows.tsx
  src/lib/Scenes/Partner/Components/__tests__/PartnerShows-tests.tsx
  src/lib/Scenes/ViewingRoom/Components/ViewingRoomArtworkRail.tsx
  src/lib/Scenes/ViewingRoom/Components/ViewingRoomViewWorksButton.tsx
  src/lib/Scenes/ViewingRoom/Components/ViewingRoomsListFeatured.tsx
  src/lib/Scenes/ViewingRoom/Components/ViewingRoomsListItem.tsx
  src/lib/Scenes/ViewingRoom/ViewingRoom.tsx
  src/lib/Scenes/ViewingRoom/ViewingRoomArtwork.tsx
  src/lib/Scenes/ViewingRoom/ViewingRoomArtworks.tsx
  src/lib/Scenes/ViewingRoom/ViewingRoomsList.tsx
  src/lib/Scenes/ViewingRoom/__tests__/ViewingRoom-tests.tsx
  src/lib/Scenes/ViewingRoom/__tests__/ViewingRoomArtworks-tests.tsx
  src/lib/utils/track/schema.ts
  tslint.json
Labels: Merge On Green

#3645 Add ArtistSeriesMoreSeries component
  .gitignore
  Artsy/App/ARSwitchBoard.m
  Artsy/View_Controllers/Admin/ARAdminSettingsViewController.m
  src/__generated__/ArtistSeriesMoreSeriesTestsQuery.graphql.ts
  src/__generated__/ArtistSeriesMoreSeries_artist.graphql.ts
  src/__generated__/ArtistSeriesQuery.graphql.ts
  src/__generated__/ArtistSeriesTestsQuery.graphql.ts
  src/__generated__/ArtistSeries_artistSeries.graphql.ts
  src/lib/Scenes/ArtistSeries/ArtistSeries.tsx
  src/lib/Scenes/ArtistSeries/ArtistSeriesMoreSeries.tsx
  src/lib/Scenes/ArtistSeries/__tests__/ArtistSeries-tests.tsx
  src/lib/Scenes/ArtistSeries/__tests__/ArtistSeriesMoreSeries-tests.tsx
Labels: Jira Synced

#3653 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3652 [MX-356] - Move show/hide button outside text field to avoid clear overlap #trivial
  Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/3_-_Sign_Up_+_Log_In/ARLoginFieldsView.m
  CHANGELOG.yml
Labels: Jira Synced

#3655 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3656 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green
