Repository artsy/eigen, pull requests merged in 2020-06, with the labels that each got.

#3384 Use maxWorkers: 0 on CI to prevent OOMs during bundle on CI
  metro.config.js
Labels: Merge On Green

#3377 Send users to the new sell tab when they tap on the artist consign CTA
  src/lib/Components/Artist/ArtistConsignButton.tsx
  src/lib/Components/Artist/__tests__/ArtistConsignButton-tests.tsx
Labels: Merge On Green

#3385 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3388 [MX-320] handles image fallbacks on SalesRail
  CHANGELOG.yml
  src/lib/Scenes/Home/Components/SalesRail.tsx
  src/lib/Scenes/Home/Components/__tests__/SalesRail-tests.tsx
Labels: Jira Synced, Merge On Green

#3395 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3391 [MX-305] Fix scroll-to-top on home tab (+ other tabs)
  Artsy/View_Controllers/App_Navigation/ARTopMenuViewController.m
  CHANGELOG.yml
Labels: Merge On Green

#3398 Fix a typo in the email confirmation sash
  CHANGELOG.yml
  src/lib/Scenes/Home/Components/EmailConfirmationBanner.tsx
  src/lib/Scenes/Home/Components/__tests__/EmailConfirmationBanner-tests.tsx
Labels: Merge On Green

#3401 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3404 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3405 Prevent false positives in strictness migration check
  scripts/strictness-migration.js
Labels: Merge On Green

#3397 [MX-347] Add new TSLint rule for preventing accidental strings/numbers in JSX
  CHANGELOG.yml
  src/lib/Components/Artist/Articles/Article.tsx
  src/lib/Components/Artist/ArtistConsignButton.tsx
  src/lib/Components/Artist/ArtistHeader.tsx
  src/lib/Components/ArtworkGrids/ArtworkGridItem.tsx
  src/lib/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx
  src/lib/Components/Bidding/Components/Animation/Fade.tsx
  src/lib/Components/Bidding/Screens/BidResult.tsx
  src/lib/Components/Bidding/Screens/ConfirmBid/index.tsx
  src/lib/Components/Bidding/Screens/CreditCardForm.tsx
  src/lib/Components/Bidding/Screens/Registration.tsx
  src/lib/Components/Countdown/Ticker.tsx
  src/lib/Components/GenericArtistSeriesRail.tsx
  src/lib/Components/Home/ArtistRails/ArtistCard.tsx
  src/lib/Components/Inbox/Conversations/ConversationSnippet.tsx
  src/lib/Components/Inbox/Conversations/Conversations.tsx
  src/lib/Components/Inbox/Conversations/Message.tsx
  src/lib/Components/Inbox/Conversations/Preview/ArtworkPreview.tsx
  src/lib/Components/Lists/SavedFairItemRow.tsx
  src/lib/Components/Lists/ShowItemRow.tsx
  src/lib/Components/SectionTitle.tsx
  src/lib/Components/States/ZeroState.tsx
  src/lib/Components/WorksForYou/Notification.tsx
  src/lib/Scenes/Artwork/Components/AboutWork.tsx
  src/lib/Scenes/Artwork/Components/ArtworkActions.tsx
  src/lib/Scenes/Artwork/Components/ArtworkTombstone.tsx
  src/lib/Scenes/Artwork/Components/AuctionPrice.tsx
  src/lib/Scenes/Artwork/Components/CommercialInformation.tsx
  src/lib/Scenes/Artwork/Components/CommercialInformationSizeInfo.tsx
  src/lib/Scenes/Artwork/Components/PartnerCard.tsx
  src/lib/Scenes/City/Components/TabFairItemRow/index.tsx
  src/lib/Scenes/Collection/Collection.tsx
  src/lib/Scenes/Collection/Components/CollectionHubsRails/FeaturedCollections/FeaturedCollectionsRail.tsx
  src/lib/Scenes/Consignments/Components/FormElements.tsx
  src/lib/Scenes/Consignments/Components/SearchResults.tsx
  src/lib/Scenes/Consignments/Components/TextInput.tsx
  src/lib/Scenes/Consignments/Screens/Overview.tsx
  src/lib/Scenes/Home/Home.tsx
  src/lib/Scenes/Map/GlobalMap.tsx
  src/lib/Scenes/Partner/Components/PartnerHeader.tsx
  src/lib/Scenes/Partner/Components/PartnerLocationSection.tsx
  src/lib/Scenes/Partner/Components/PartnerOverview.tsx
  src/lib/Scenes/Search/Input.tsx
  src/lib/Scenes/Search/Search.tsx
  src/lib/Scenes/Search/SearchResult.tsx
  src/lib/Scenes/ViewingRoom/Components/ViewingRoomHeader.tsx
  src/lib/Scenes/ViewingRoom/Components/ViewingRoomSubsections.tsx
  src/lib/Scenes/ViewingRoom/ViewingRoom.tsx
  src/lib/Scenes/ViewingRoom/ViewingRoomArtworks.tsx
  src/lib/tests/__tests__/MockRelayRendererFixtures.tsx
  tslint-rules/jsxSafeConditionalsRule.js
  tslint.json
Labels: Merge On Green

#3394 [WIP] Upgrades to styled-system v5
  package.json
  tsconfig.json
  yarn.lock
Labels: Merge On Green

#3400 Add a bridge to identify the currently selected tab name
  Artsy/App/ARAppDelegate+Emission.m
  Artsy/View_Controllers/App_Navigation/ARTopMenuNavigationDataSource.h
  Artsy/View_Controllers/App_Navigation/ARTopMenuNavigationDataSource.m
  Artsy/View_Controllers/App_Navigation/ARTopMenuViewController.h
  Artsy/View_Controllers/App_Navigation/ARTopMenuViewController.m
  CHANGELOG.yml
  emission/Pod/Classes/Core/AREmission.h
  emission/Pod/Classes/Core/AREmission.m
  emission/Pod/Classes/Core/ARTopMenuModule.h
  emission/Pod/Classes/Core/ARTopMenuModule.m
  src/lib/NativeModules/TopMenu.tsx
Labels: Merge On Green

#3403 [MX-189] - Fix for auctions pointy modal corner and non-fullscreen display
  Artsy/View_Controllers/ARSerifNavigationViewController.m
  Artsy/View_Controllers/App_Navigation/ARTopMenuViewController.h
  Artsy/View_Controllers/App_Navigation/ARTopMenuViewController.m
  CHANGELOG.yml
Labels: Merge On Green

#3407 [CSGN-172] Update content of consignment submission confirmation
  src/lib/Scenes/Consignments/Screens/Confirmation.tsx
  src/lib/Scenes/Consignments/Screens/__tests__/Confirmation-tests.tsx
Labels: Merge On Green

#3410 Update metaphysics schema
  data/schema.graphql
  src/__generated__/createConsignmentSubmissionMutation.graphql.ts
Labels: Merge On Green

#3409 [Consignments] Pass userAgent over when creating submission
  CHANGELOG.yml
  data/schema.graphql
  src/lib/Scenes/Consignments/Submission/createConsignmentSubmission.ts
Labels: Consignments, Merge On Green

#3415 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3399 Remove the feature flag for email confirmation sash in Eigen
  Artsy/App/AROptions.h
  Artsy/App/AROptions.m
  src/lib/Scenes/Home/Home.tsx
  src/lib/Scenes/Home/__tests__/Home-tests.tsx
  src/setupJest.ts
  typings/emission.d.ts
Labels: Merge On Green

#3421 Remove AROptionsEnableSales lab option entry
  Artsy/App/AROptions.m
  Artsy_Tests/ReferenceImages/ARTopMenuViewControllerSpec/selects 'home' by default as ipad@3x.png
  Artsy_Tests/ReferenceImages/ARTopMenuViewControllerSpec/selects 'home' by default as iphone@3x.png
  dangerfile.ts
Labels: Merge On Green

#3422 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3425 Fix auction registration back button layout issue
  Artsy/View_Controllers/ARSerifNavigationViewController.m
  src/lib/Components/Bidding/Components/BackButton.tsx
Labels: Merge On Green

#3417 [MX-349] Set up new profile tab
  Artsy.xcodeproj/project.pbxproj
  Artsy/App/ARAppDelegate+Emission.m
  Artsy/App/AROptions.h
  Artsy/App/AROptions.m
  Artsy/App/ARSwitchBoard.m
  Artsy/Resources/Assets/Navigation/nav_profile@2x.png
  Artsy/Resources/Assets/Navigation/nav_profile@3x.png
  Artsy/View_Controllers/App_Navigation/ARTopMenuNavigationDataSource.h
  Artsy/View_Controllers/App_Navigation/ARTopMenuNavigationDataSource.m
  Artsy/View_Controllers/App_Navigation/ARTopMenuViewController.m
  CHANGELOG.yml
  images/package.json
  jest.config.js
  src/__generated__/MyProfileQuery.graphql.ts
  src/__generated__/MyProfileRefetchQuery.graphql.ts
  src/__generated__/MyProfile_me.graphql.ts
  src/lib/AppRegistry.tsx
  src/lib/Scenes/Favorites/index.tsx
  src/lib/Scenes/Home/Components/ArtworkRail.tsx
  src/lib/Scenes/Home/Components/SmallTileRail.tsx
  src/lib/Scenes/Settings/MyProfile.tsx
  src/lib/Scenes/Settings/SettingsOld.tsx
  src/lib/Scenes/Settings/__tests__/MyProfile-tests.tsx
  src/setupJest.ts
  typings/emission.d.ts
Labels: Merge On Green

#3431 Add extractNodes to lib/utils
  CHANGELOG.yml
  src/lib/Components/Artist/ArtistAbout.tsx
  src/lib/Components/Artist/ArtistShows/ArtistShows.tsx
  src/lib/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx
  src/lib/Components/ArtworkTileRail/ArtworkTileRail.tsx
  src/lib/Components/GenericArtistSeriesRail.tsx
  src/lib/Components/Home/ArtistRails/ArtistCard.tsx
  src/lib/Components/Inbox/Conversations/Conversations.tsx
  src/lib/Components/Inbox/Conversations/Messages.tsx
  src/lib/Components/Show/ShowArtworksPreview.tsx
  src/lib/Components/WorksForYou/Notification.tsx
  src/lib/Containers/Inbox.tsx
  src/lib/Containers/WorksForYou.tsx
  src/lib/Scenes/Artwork/Components/OtherWorks/OtherWorks.tsx
  src/lib/Scenes/City/CityBMWList.tsx
  src/lib/Scenes/City/CitySavedList.tsx
  src/lib/Scenes/City/CitySectionList.tsx
  src/lib/Scenes/City/Components/EventList.tsx
  src/lib/Scenes/Consignments/Screens/ConsignmentsArtist.tsx
  src/lib/Scenes/Consignments/Screens/SelectFromPhotoLibrary.tsx
  src/lib/Scenes/Fair/Components/ArtworksPreview.tsx
  src/lib/Scenes/Fair/Components/FairBoothPreview/Components/FairBoothPreviewHeader.tsx
  src/lib/Scenes/Fair/Components/FairBoothPreview/index.tsx
  src/lib/Scenes/Fair/Components/FairHeader/index.tsx
  src/lib/Scenes/Fair/Screens/FairArtists.tsx
  src/lib/Scenes/Favorites/Components/Artists/index.tsx
  src/lib/Scenes/Favorites/Components/Artworks/index.tsx
  src/lib/Scenes/Favorites/Components/Categories/index.tsx
  src/lib/Scenes/Favorites/Components/Fairs/index.tsx
  src/lib/Scenes/Favorites/Components/Shows/index.tsx
  src/lib/Scenes/Home/Components/CollectionsRail.tsx
  src/lib/Scenes/Home/Components/FairsRail.tsx
  src/lib/Scenes/Home/Components/SalesRail.tsx
  src/lib/Scenes/Map/GlobalMap.tsx
  src/lib/Scenes/Partner/Components/PartnerOverview.tsx
  src/lib/Scenes/Partner/Components/PartnerShows.tsx
  src/lib/Scenes/Partner/Components/PartnerShowsRail.tsx
  src/lib/Scenes/Partner/Screens/PartnerLocations.tsx
  src/lib/Scenes/Sales/Components/LotsByFollowedArtists.tsx
  src/lib/Scenes/Sales/index.tsx
  src/lib/Scenes/Settings/MyProfile.tsx
  src/lib/Scenes/Show/Components/ShowHeader/ShowHeader.tsx
  src/lib/Scenes/ViewingRoom/ViewingRoomArtworks.tsx
  src/lib/utils/__tests__/extractNodes-tests.ts
  src/lib/utils/extractNodes.ts
Labels: Merge On Green

#3441 Prep for 6.4.8.
  Artsy Stickers/Info.plist
  Artsy/App_Resources/Artsy-Info.plist
  CHANGELOG.yml
Labels: Merge On Green

#3438 [My Collection] Stub out skeleton nav flow
  Artsy/App/ARSwitchBoard.m
  emission/Pod/Classes/ViewControllers/ARMyCollectionAddArtworkComponentViewController.h
  emission/Pod/Classes/ViewControllers/ARMyCollectionAddArtworkComponentViewController.m
  emission/Pod/Classes/ViewControllers/ARMyCollectionArtworkDetailComponentViewController.h
  emission/Pod/Classes/ViewControllers/ARMyCollectionArtworkDetailComponentViewController.m
  emission/Pod/Classes/ViewControllers/ARMyCollectionArtworkListComponentViewController.h
  emission/Pod/Classes/ViewControllers/ARMyCollectionArtworkListComponentViewController.m
  emission/Pod/Classes/ViewControllers/ARMyCollectionHomeComponentViewController.h
  emission/Pod/Classes/ViewControllers/ARMyCollectionHomeComponentViewController.m
  src/lib/AppRegistry.tsx
  src/lib/Scenes/Consignments/v2/Screens/MyCollectionAddArtwork/index.tsx
  src/lib/Scenes/Consignments/v2/Screens/MyCollectionArtworkList/index.tsx
  src/lib/Scenes/Consignments/v2/Screens/MyCollectionHome/index.tsx
  src/lib/Scenes/Consignments/v2/State/navigationState.ts
  src/lib/Scenes/Consignments/v2/State/store.tsx
Labels: Merge On Green

#3446 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3449 Revert "Revert "[My Collection] Stub out skeleton nav flow ""
  Artsy/App/ARSwitchBoard.m
  emission/Pod/Classes/ViewControllers/ARMyCollectionAddArtworkComponentViewController.h
  emission/Pod/Classes/ViewControllers/ARMyCollectionAddArtworkComponentViewController.m
  emission/Pod/Classes/ViewControllers/ARMyCollectionArtworkDetailComponentViewController.h
  emission/Pod/Classes/ViewControllers/ARMyCollectionArtworkDetailComponentViewController.m
  emission/Pod/Classes/ViewControllers/ARMyCollectionArtworkListComponentViewController.h
  emission/Pod/Classes/ViewControllers/ARMyCollectionArtworkListComponentViewController.m
  emission/Pod/Classes/ViewControllers/ARMyCollectionHomeComponentViewController.h
  emission/Pod/Classes/ViewControllers/ARMyCollectionHomeComponentViewController.m
  src/lib/AppRegistry.tsx
  src/lib/Scenes/Consignments/v2/Screens/MyCollectionAddArtwork/index.tsx
  src/lib/Scenes/Consignments/v2/Screens/MyCollectionArtworkList/index.tsx
  src/lib/Scenes/Consignments/v2/Screens/MyCollectionHome/index.tsx
  src/lib/Scenes/Consignments/v2/State/navigationState.ts
  src/lib/Scenes/Consignments/v2/State/store.tsx
Labels: Merge On Green

#3450 [MyCollection] Rename index files
  Artsy/App/ARSwitchBoard.m
  emission/Pod/Classes/ViewControllers/ARSellTabAppViewController.h
  emission/Pod/Classes/ViewControllers/ARSellTabAppViewController.m
  emission/Pod/Classes/ViewControllers/ARSellTabLandingViewController.m
  src/lib/AppRegistry.tsx
  src/lib/Scenes/Consignments/index.tsx
  src/lib/Scenes/Consignments/v2/Screens/ConsignmentsHome/ConsignmentsHome.tsx
  src/lib/Scenes/Consignments/v2/Screens/ConsignmentsHome/__tests__/index-tests.tsx
  src/lib/Scenes/Consignments/v2/Screens/MyCollectionAddArtwork/MyCollectionAddArtwork.tsx
  src/lib/Scenes/Consignments/v2/Screens/MyCollectionArtworkDetail/MyCollectionArtworkDetail.tsx
  src/lib/Scenes/Consignments/v2/Screens/MyCollectionArtworkList/MyCollectionArtworkList.tsx
  src/lib/Scenes/Consignments/v2/Screens/MyCollectionHome/MyCollectionHome.tsx
  src/lib/Scenes/Consignments/v2/SellTabApp.tsx
Labels: Merge On Green

#3448 Updates readme image
  README.md
  docs/screenshots/overview.jpg
  docs/screenshots/overview.png
Labels: Merge On Green

#3443 [MX-349] added placeholder to my profile screen
  src/lib/Scenes/Settings/MyProfile.tsx
Labels: Merge On Green

#3427 [MX-319] Support principalField extension
  src/__generated__/FairQuery.graphql.ts
  src/lib/Scenes/Fair/Components/FairBoothPreview/index.tsx
  src/lib/Scenes/Fair/Fair.tsx
  src/lib/relay/createEnvironment.ts
  src/lib/relay/middlewares/__tests__/cacheMiddleware-tests.ts
  src/lib/relay/middlewares/__tests__/principalFieldErrorMiddleware-tests.ts
  src/lib/relay/middlewares/cacheMiddleware.ts
  src/lib/relay/middlewares/principalFieldErrorMiddleware.ts
  src/lib/utils/errors.tsx
Labels: Merge On Green

#3460 [Lib] Add formik and yupp
  package.json
  yarn.lock
Labels: Merge On Green, library

#3454 Add Notable Works rail to Artist pages
  CHANGELOG.yml
  src/__generated__/ArtistAboveTheFoldQuery.graphql.ts
  src/__generated__/ArtistArtworksQuery.graphql.ts
  src/__generated__/ArtistArtworks_artist.graphql.ts
  src/__generated__/ArtistNotableWorksRailTestsQuery.graphql.ts
  src/__generated__/ArtistNotableWorksRail_artist.graphql.ts
  src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
  src/lib/Components/Artist/ArtistArtworks/ArtistCollectionsRail.tsx
  src/lib/Components/Artist/ArtistArtworks/ArtistNotableWorksRail.tsx
  src/lib/Components/Artist/ArtistArtworks/__tests__/ArtistNotableWorksRail-tests.tsx
  src/lib/Components/ArtworkTileRail/ArtworkTileRailCard.tsx
  src/lib/Scenes/Collection/Collection.tsx
Labels: Merge On Green

#3437 [CSGN-230] Re-architect selected tab bridge
  Artsy/App/ARAppDelegate+Emission.m
  Artsy/View_Controllers/App_Navigation/ARTopMenuViewController.m
  CHANGELOG.yml
  emission/Pod/Classes/Core/AREmission.h
  emission/Pod/Classes/Core/AREmission.m
  emission/Pod/Classes/Core/ARSelectedTab.h
  emission/Pod/Classes/Core/ARSelectedTab.m
  emission/Pod/Classes/Core/ARTopMenuModule.h
  emission/Pod/Classes/Core/ARTopMenuModule.m
  src/lib/AppRegistry.tsx
  src/lib/Components/Artist/ArtistConsignButton.tsx
  src/lib/Components/Artist/__tests__/ArtistConsignButton-tests.tsx
  src/lib/NativeModules/SelectedTab/SelectedTab.tsx
  src/lib/NativeModules/SelectedTab/TabName.ts
  src/lib/NativeModules/TopMenu.tsx
  src/setupJest.ts
Labels: Merge On Green

#3465 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3467 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3468 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3469 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3464 [MyCollection] Add Add/Edit artwork patterns
  package.json
  src/lib/Scenes/Consignments/v2/Boot.tsx
  src/lib/Scenes/Consignments/v2/Form/artworkSchema.tsx
  src/lib/Scenes/Consignments/v2/Form/useFormikSync.ts
  src/lib/Scenes/Consignments/v2/Screens/MyCollectionAddArtwork/Mutations/MyCollectionAddArtworkMutation.ts
  src/lib/Scenes/Consignments/v2/Screens/MyCollectionAddArtwork/Mutations/MyCollectionEditArtworkMutation.ts
  src/lib/Scenes/Consignments/v2/Screens/MyCollectionAddArtwork/MyCollectionAddArtwork.tsx
  src/lib/Scenes/Consignments/v2/Screens/MyCollectionAddArtwork/Screens/MyCollectionAddArtworkAddPhotos.tsx
  src/lib/Scenes/Consignments/v2/Screens/MyCollectionAddArtwork/Screens/MyCollectionAddArtworkTitleAndYear.tsx
  src/lib/Scenes/Consignments/v2/Screens/MyCollectionArtworkDetail/MyCollectionArtworkDetail.tsx
  src/lib/Scenes/Consignments/v2/Screens/MyCollectionArtworkList/MyCollectionArtworkList.tsx
  src/lib/Scenes/Consignments/v2/State/artworkModel.tsx
  src/lib/Scenes/Consignments/v2/State/hooks.tsx
  src/lib/Scenes/Consignments/v2/State/navigationModel.tsx
  src/lib/Scenes/Consignments/v2/State/store.tsx
  yarn.lock
Labels: Merge On Green

#3459 Bumps @artsy/palette => 11.0.0
  package.json
  src/lib/Components/Lists/SavedFairItemRow.tsx
  yarn.lock
Labels: Merge On Green

#3470 Track a screenview on the Sell Tab
  CHANGELOG.yml
  src/lib/Scenes/Consignments/v2/SellTabApp.tsx
  src/lib/utils/track/schema.ts
Labels: Merge On Green

#3477 [MX-363] hide change password for users signed up using facebook and apple
  src/__generated__/MyAccountQuery.graphql.ts
  src/__generated__/MyAccount_me.graphql.ts
  src/lib/Scenes/MyAccount/MyAccount.tsx
Labels: Merge On Green

#3455 [MX-368] Change Profile Full Name
  Artsy/App/ARSwitchBoard.m
  emission/Pod/Classes/GraphQL/ARGraphQLQueryMap.generated.objc
  src/__generated__/MyAccountEditNameMutation.graphql.ts
  src/__generated__/MyAccountEditNameQuery.graphql.ts
  src/__generated__/MyAccountEditName_me.graphql.ts
  src/lib/AppRegistry.tsx
  src/lib/Components/Input/Input.tsx
  src/lib/Components/Modals/LoadingModal.tsx
  src/lib/Components/Modals/__tests__/LoadingModal-tests.tsx
  src/lib/NativeModules/SwitchBoard.tsx
  src/lib/Scenes/Consignments/v2/Screens/MyCollectionAddArtwork/Components/MediumPicker.tsx
  src/lib/Scenes/Consignments/v2/Screens/MyCollectionAddArtwork/Components/SizePicker.tsx
  src/lib/Scenes/Consignments/v2/Screens/MyCollectionAddArtwork/MyCollectionAddArtwork.tsx
  src/lib/Scenes/Consignments/v2/Screens/MyCollectionAddArtwork/Screens/MyCollectionAddArtworkTitleAndYear.tsx
  src/lib/Scenes/MyAccount/MyAccount.tsx
  src/lib/Scenes/MyAccountEditName/MyAccountEditName.tsx
  src/lib/Scenes/MyAccountEditName/__tests__/MyAccountEditName-tests.tsx
  src/lib/Scenes/Search/Search.tsx
  src/lib/Scenes/Search/SearchContext.tsx
Labels: Merge On Green

#3481 Smarter back button hiding + generic field edit screen
  Artsy/App/ARSwitchBoard.m
  emission/Pod/Classes/ViewControllers/ARComponentViewController.h
  emission/Pod/Classes/ViewControllers/ARComponentViewController.m
  src/lib/AppRegistry.tsx
  src/lib/Scenes/MyAccount/Components/MyAccountFieldEditScreen.tsx
  src/lib/Scenes/MyAccount/MyAccountEditName.tsx
  src/lib/Scenes/MyAccount/__tests__/MyAccountEditName-tests.tsx
  src/lib/Scenes/MyAccountEditName/MyAccountEditName.tsx
Labels: Merge On Green

#3485 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3486 [MyCollection] Add static ArtworkDetail view
  Artsy/App/main.m
  src/lib/Scenes/Consignments/v2/Form/artworkSchema.tsx
  src/lib/Scenes/Consignments/v2/Screens/MyCollectionAddArtwork/MyCollectionAddArtwork.tsx
  src/lib/Scenes/Consignments/v2/Screens/MyCollectionArtworkDetail/MyCollectionArtworkDetail.tsx
  src/lib/Scenes/Consignments/v2/State/artworkModel.tsx
  src/lib/Scenes/Consignments/v2/State/navigationModel.tsx
Labels: Merge On Green

#3480 [MX-380] Visual Tweaks
  CHANGELOG.yml
  images/BMW_Grey-Colour_RGB.png
  images/bmw-logo.png
  images/bmw-logo@2x.png
  images/bmw-logo@3x.png
  src/lib/Scenes/City/CityBMWSponsorship.tsx
  src/lib/Scenes/City/CityPicker.tsx
  src/lib/Scenes/Home/Home.tsx
  src/lib/Scenes/Search/CityGuideCTA.tsx
  src/lib/Scenes/Search/RecentSearches.tsx
  src/lib/Scenes/Search/__tests__/CityGuideCTA-tests.tsx
  src/lib/Scenes/Search/__tests__/Search-tests.tsx
Labels: Merge On Green

#3478 [MX-382] fixed ZeroStateInbox layout on iPad
  src/lib/Components/Inbox/Conversations/ZeroStateInbox.tsx
Labels: Merge On Green

#3482 adjusted principalFieldMiddleware
  src/lib/relay/createEnvironment.ts
  src/lib/relay/middlewares/__tests__/cacheMiddleware-tests.ts
  src/lib/relay/middlewares/__tests__/principalFieldErrorMiddleware-tests.ts
  src/lib/relay/middlewares/cacheMiddleware.ts
  src/lib/relay/middlewares/principalFieldErrorMiddleware.ts
  src/lib/relay/middlewares/types.ts
Labels: Merge On Green

#3490 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3491 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3487 [MX-360] Change email address
  Artsy/App/ARSwitchBoard.m
  CHANGELOG.yml
  emission/Pod/Classes/GraphQL/ARGraphQLQueryMap.generated.objc
  src/__generated__/MyAccountEditEmailMutation.graphql.ts
  src/__generated__/MyAccountEditEmailQuery.graphql.ts
  src/__generated__/MyAccountEditEmail_me.graphql.ts
  src/lib/AppRegistry.tsx
  src/lib/Scenes/MyAccount/MyAccount.tsx
  src/lib/Scenes/MyAccount/MyAccountEditEmail.tsx
  src/lib/Scenes/MyAccount/__tests__/MyAccountEditEmail-tests.tsx
Labels: Merge On Green

#3493 added change phone number screen
  Artsy/App/ARSwitchBoard.m
  src/__generated__/MyAccountEditPhoneMutation.graphql.ts
  src/__generated__/MyAccountEditPhoneQuery.graphql.ts
  src/__generated__/MyAccountEditPhone_me.graphql.ts
  src/lib/AppRegistry.tsx
  src/lib/Scenes/MyAccount/MyAccount.tsx
  src/lib/Scenes/MyAccount/MyAccountEditPhone.tsx
  src/lib/Scenes/MyAccount/__tests__/MyAccountEditPhone-tests.tsx
Labels: Merge On Green

#3494 Add check for new dev agreements in nightly job #trivial
  .circleci/config.yml
  Makefile
  fastlane/Fastfile
Labels: Merge On Green

#3495 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3499 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3502 [MX-340] Fixes promotion script #trivial
  fastlane/Fastfile
Labels: Jira Synced, Merge On Green

#3500 Update image for nightly job to use macOS #trivial
  .circleci/config.yml
Labels: Merge On Green

#3504 [MX-269] Delete Unused Files
  src/__generated__/ArtworksPreviewTestsQuery.graphql.ts
  src/__generated__/ArtworksPreview_fair.graphql.ts
  src/__generated__/CommercialInformationSizeInfo_piece.graphql.ts
  src/__generated__/Header_sale.graphql.ts
  src/lib/Components/Bidding/Components/Animation/Fade.tsx
  src/lib/Components/Carousel.tsx
  src/lib/Components/Events.tsx
  src/lib/Components/Sale/Header.tsx
  src/lib/Components/Sale/__tests__/Header-tests.tsx
  src/lib/Components/ScrollView.tsx
  src/lib/Components/TabView.tsx
  src/lib/Components/Video.tsx
  src/lib/Components/__tests__/Carousel-tests.tsx
  src/lib/Components/__tests__/TabView-tests.tsx
  src/lib/Icons/PinGalleryOn.tsx
  src/lib/Scenes/Artwork/Components/CommercialInformationSizeInfo.tsx
  src/lib/Scenes/Artwork/Components/ImageCarousel/ImageCarousel.tsx.rej
  src/lib/Scenes/Collection/index.tsx
  src/lib/Scenes/Consignments/Components/CircleImage.tsx
  src/lib/Scenes/Consignments/Components/NavButton.tsx
  src/lib/Scenes/Consignments/Components/__tests__/CircleImage-tests.tsx
  src/lib/Scenes/Fair/Components/ArtworksPreview.tsx
  src/lib/Scenes/Fair/Components/__tests__/ArtworksPreview-tests.tsx
  src/lib/Scenes/Map/MapDataSource.tsx
  src/lib/utils/__tests__/formatDates-tests.tsx
  src/lib/utils/formatDates.tsx
Labels: Merge On Green

#3501 Removes Unused Metaphysics v1 Queries #trivial
  Artsy.xcodeproj/project.pbxproj
  Artsy/Models/API_Models/Auctions/Sale.h
  Artsy/Models/API_Models/Auctions/Sale.m
  Artsy/Models/API_Models/Partner_Metadata/Artwork.h
  Artsy/Models/API_Models/Partner_Metadata/Artwork.m
  Artsy/Networking/API_Modules/ArtsyAPI+Artworks.h
  Artsy/Networking/API_Modules/ArtsyAPI+Artworks.m
  Artsy/Networking/API_Modules/ArtsyAPI+Sales.h
  Artsy/Networking/API_Modules/ArtsyAPI+Sales.m
  Artsy/Networking/ARRouter+GraphQL.h
  Artsy/Networking/ARRouter+GraphQL.m
  Artsy/Networking/ARRouter.h
  Artsy/Networking/ARRouter.m
  Artsy/Networking/artwork.graphql
  Artsy/Networking/artworks_in_sale.graphql
  Artsy/Networking/create_offer.graphql
  Artsy/Networking/create_order.graphql
  Artsy/Networking/record_artwork_view_mutation.graphql
  Artsy_Tests/Networking_Tests/API_Modules/ArtsyAPI+ArtworksTests.m
  Artsy_Tests/Networking_Tests/Networking_Models/ArtsyAPI+SalesTests.m
Labels: Jira Synced, Merge On Green

#3508 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3506 update Personal Data Request Page
  src/lib/Scenes/PrivacyRequest/PrivacyRequest.tsx
Labels: Merge On Green

#3510 Prepares for 6.4.9 development
  Artsy Stickers/Info.plist
  Artsy/App_Resources/Artsy-Info.plist
  CHANGELOG.yml
Labels: Merge On Green

#3511 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3515 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green
