Repository artsy/eigen, pull requests merged in 2020-11, with the labels that each got.

#4089 fix: fix title for add artwork modal #trivial
  CHANGELOG.yml
  src/lib/Scenes/MyCollection/Screens/AddArtwork/AddEditArtwork.tsx
Labels: Jira Synced, Squash On Green

#4084 feat: submit inquiry request
  CHANGELOG.yml
  src/__generated__/ArtworkAboveTheFoldQuery.graphql.ts
  src/__generated__/ArtworkRefetchQuery.graphql.ts
  src/__generated__/CommercialButtonsTestsMutationQuery.graphql.ts
  src/__generated__/CommercialButtonsTestsRenderQuery.graphql.ts
  src/__generated__/InquiryModalTestsQuery.graphql.ts
  src/__generated__/InquiryModal_artwork.graphql.ts
  src/__generated__/SubmitInquiryRequestMutation.graphql.ts
  src/lib/Scenes/Artwork/Components/CommercialButtons/InquiryModal.tsx
  src/lib/Scenes/Artwork/Components/CommercialButtons/__tests__/CommercialButtons-tests.tsx
  src/lib/Scenes/Artwork/Components/Mutation/SubmitInquiryRequest.ts
  src/lib/utils/ArtworkInquiry/ArtworkInquiryStore.tsx
  src/lib/utils/ArtworkInquiry/ArtworkInquiryTypes.ts
  src/lib/utils/ArtworkInquiry/__tests__/ArtworkInquiryStore-tests.tsx
Labels: Jira Synced, Squash On Green

#4065 Updates inquiryType text and ensures the modal has the correct title based on the CTA clicked
  CHANGELOG.yml
  src/lib/Scenes/Artwork/Components/CommercialButtons/InquiryModal.tsx
  src/lib/Scenes/Artwork/Components/CommercialButtons/__tests__/CommercialButtons-tests.tsx
  src/lib/utils/ArtworkInquiry/ArtworkInquiryTypes.ts
  src/lib/utils/ArtworkInquiry/__tests__/ArtworkInquiryStore-tests.tsx
Labels: Jira Synced

#4078 User can see empty state when they don't have any active bids
  CHANGELOG.yml
  src/lib/Scenes/MyBids/Components/NoBids.tsx
  src/lib/Scenes/MyBids/MyBids.tsx
  src/lib/Scenes/MyBids/__tests__/MyBids-tests.tsx
  src/lib/Scenes/MyBids/__tests__/MyBids2-tests.tsx
Labels: Jira Synced

#4094 fix(fx-2407): adjusts show2 install shots query #trivial
  src/__generated__/Show2InstallShots_show.graphql.ts
  src/__generated__/Show2Query.graphql.ts
  src/__generated__/Show2TestsQuery.graphql.ts
  src/__generated__/Show2_show.graphql.ts
  src/lib/Scenes/Show2/Components/Show2InstallShots.tsx
  src/lib/Scenes/Show2/Show2.tsx
Labels: Jira Synced

#4095 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4088 fix(auction): hide register to bid button on closed auctions #trivial
  src/lib/Scenes/SaleInfo/SaleInfo.tsx
  src/lib/Scenes/SaleInfo/__tests__/SaleInfo-tests.tsx
Labels: Jira Synced

#4093 fix: reset form when leaving edit modal
  CHANGELOG.yml
  src/lib/Scenes/MyCollection/State/MyCollectionArtworkModel.tsx
Labels: Jira Synced

#4087 fix(my collection): artwork list empty state alignment #trivial
  src/lib/Components/States/ZeroState.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkList/MyCollectionArtworkList.tsx
Labels: Jira Synced

#4092 fix: prevent keyboard touch intercept #trivial
  CHANGELOG.yml
  src/lib/Scenes/MyCollection/Screens/AddArtwork/AddEditArtwork.tsx
Labels: Jira Synced, Squash On Green

#4098 fix(my collection add/edit artwork): truncate artist name
  CHANGELOG.yml
  src/lib/Scenes/MyCollection/Screens/AddArtwork/Components/ArtistSearchResult.tsx
Labels: Jira Synced

#4097 fix(my collection): photo list layout in add artwork
  CHANGELOG.yml
  src/lib/Scenes/MyCollection/Screens/AddArtwork/Screens/AddPhotos.tsx
  src/palette/svgs/XCircleIcon.tsx
Labels: Jira Synced

#4099 fix(SaleHeader): auction closed bug
  src/lib/Scenes/Sale/Components/SaleHeader.tsx
  src/lib/Scenes/Sale/__tests__/SaleHeader-tests.tsx
Labels: Jira Synced

#4086 fix(my collection): set correct keyboard types #trivial
  src/lib/Scenes/MyCollection/Screens/AddArtwork/Components/Dimensions.tsx
  src/lib/Scenes/MyCollection/Screens/AddArtwork/Screens/AdditionalDetails.tsx
Labels: Jira Synced

#4101 fix(my collection): button improvements in add artwork form
  CHANGELOG.yml
  src/lib/Scenes/MyCollection/Screens/AddArtwork/AddEditArtwork.tsx
  src/palette/elements/Button/Button.tsx
Labels: Jira Synced, Squash On Green

#4074 feat: add markdown to auction info
  src/lib/Scenes/Sale/Sale.tsx
  src/lib/Scenes/SaleInfo/SaleInfo.tsx
Labels: Jira Synced, Squash On Green

#4100 fix(fx-2408): improves guards for rendering hours and locations #trivial
  src/__generated__/Show2MoreInfoQuery.graphql.ts
  src/__generated__/Show2MoreInfoTestsQuery.graphql.ts
  src/__generated__/Show2MoreInfo_show.graphql.ts
  src/lib/Scenes/Show2/Components/Show2Hours.tsx
  src/lib/Scenes/Show2/Components/Show2Location.tsx
  src/lib/Scenes/Show2/Screens/Show2MoreInfo.tsx
  src/lib/Scenes/Show2/__tests__/Show2MoreInfo-tests.tsx
Labels: Jira Synced

#4103 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4104 fix: add missing prop to above the fold query renderer
  src/lib/utils/AboveTheFoldQueryRenderer.tsx
Labels: Jira Synced, Squash On Green

#4105 fix: reverted sale artworks sorting options
  src/lib/Components/ArtworkFilterOptions/SortOptions.tsx
  src/lib/Scenes/Sale/__tests__/SaleLotsList-tests.tsx
Labels: Jira Synced, Squash On Green

#4109 fix(show2): updates remaining time once per second #trivial
  src/lib/Scenes/Show2/Components/Show2Header.tsx
Labels: Jira Synced, Squash On Green

#4110 fix: add keyboard type for phone number on billing address
  src/lib/Components/Bidding/Screens/BillingAddress.tsx
Labels: Jira Synced

#4107 fix: extra padding on single option filters screens
  src/lib/Components/ArtworkFilterOptions/MediumOptions.tsx
  src/lib/Components/ArtworkFilterOptions/SingleSelectOption.tsx
Labels: Jira Synced

#4106 fix: add feedback to more info about this auction
  src/lib/Components/Buttons/CaretButton.tsx
  src/lib/Components/Buttons/__tests__/CaretButton-tests.tsx
Labels: Jira Synced

#4108 fix: fix sale info bugs
  src/lib/Scenes/SaleFAQ/SaleFAQ.tsx
  src/lib/Scenes/SaleFAQ/__tests__/SaleFAQ-tests.tsx
  src/lib/Scenes/SaleInfo/SaleInfo.tsx
Labels: Jira Synced, Squash On Green

#4090 fix: fix upper limit label of demand rank #trivial
  src/lib/Scenes/MyCollection/Screens/ArtworkDetail/Components/ArtworkInsights/MyCollectionArtworkDemandIndex.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkDetail/Components/ArtworkInsights/__tests__/MyCollectionArtworkDemandIndex-tests.tsx
Labels: Jira Synced

#4116 fix: Add screen tracking for sale screen
  src/lib/Scenes/Sale/Sale.tsx
Labels: Jira Synced

#4091 fix: text wrapping fixes in my collection #trivial
  src/lib/Scenes/MyCollection/Screens/ArtworkDetail/Components/Field.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkList/MyCollectionArtworkListItem.tsx
Labels: Jira Synced

#4118 chore: remove show2 lab option in favor of using Echo
  Artsy/App/AROptions.m
Labels: Jira Synced

#4120 feat(fair): show up to 5 marketing collections on fair screen
  CHANGELOG.yml
  src/__generated__/Fair2CollectionsTestsQuery.graphql.ts
  src/__generated__/Fair2Collections_fair.graphql.ts
  src/__generated__/Fair2Query.graphql.ts
  src/__generated__/Fair2TestsQuery.graphql.ts
  src/__generated__/Fair2_fair.graphql.ts
  src/__generated__/VanityURLEntityQuery.graphql.ts
  src/lib/Scenes/Fair2/Components/Fair2Collections.tsx
  src/lib/Scenes/Fair2/Fair2.tsx
Labels: Jira Synced

#4111 fix(fx-2413): handles empty state for shows/booths without artworks
  src/__generated__/Show2ArtworksEmptyStateTestsQuery.graphql.ts
  src/__generated__/Show2ArtworksEmptyState_show.graphql.ts
  src/__generated__/Show2Query.graphql.ts
  src/__generated__/Show2TestsQuery.graphql.ts
  src/__generated__/Show2_show.graphql.ts
  src/lib/Scenes/Show2/Components/Show2ArtworksEmptyState.tsx
  src/lib/Scenes/Show2/Components/Show2ContextCard.tsx
  src/lib/Scenes/Show2/Show2.tsx
  src/lib/Scenes/Show2/__tests__/Show2ArtworksEmptyState-tests.tsx
Labels: Jira Synced

#4122 chore: migrate AROptionsNewSalePage to echo
  Artsy/App/AROptions.m
  Artsy/App/ARScreenPresenterModule.m
Labels: Jira Synced, Squash On Green

#4080 feat: add tracking to artwork taps
  CHANGELOG.yml
  src/lib/Components/SaleArtworkTileRailCard/SaleArtworkTileRailCard.tsx
  src/lib/Scenes/Sale/Components/SaleArtworkList.tsx
  src/lib/Scenes/Sale/Components/SaleArtworkListItem.tsx
  src/lib/Scenes/Sale/Components/SaleArtworksRail.tsx
  src/lib/Scenes/Sale/Components/SaleLotsList.tsx
Labels: Jira Synced, Squash On Green

#4115 fix: Add buyers premium to sale info page
  src/__generated__/SaleInfoQueryRendererQuery.graphql.ts
  src/__generated__/SaleInfoTestsQuery.graphql.ts
  src/__generated__/SaleInfo_sale.graphql.ts
  src/lib/Scenes/SaleInfo/SaleInfo.tsx
  src/lib/Scenes/SaleInfo/__tests__/SaleInfo-tests.tsx
Labels: Jira Synced, Squash On Green

#4121 feat: enable markdown for auctions
  src/lib/Components/StyledWebView.tsx
  src/lib/Scenes/SaleInfo/SaleInfo.tsx
Labels: Jira Synced, Squash On Green

#4096 test: checkbox functionality
  src/lib/Scenes/Artwork/Components/CommercialButtons/InquiryModal.tsx
  src/lib/Scenes/Artwork/Components/CommercialButtons/__tests__/InquiryModal-tests.tsx
Labels: Jira Synced

#4125 fix(echo): Echo config sort and only skip update if `_OSS_=true`
  Artsy/App/ArtsyEcho.m
  Artsy/View_Controllers/Admin/AREchoContentsViewController.m
  CHANGELOG.yml
Labels: Jira Synced

#4112 fix: reset form when returning to artwork screen
  src/lib/Scenes/Artwork/Components/CommercialButtons/InquiryModal.tsx
  src/lib/Scenes/Artwork/Components/CommercialButtons/__tests__/InquiryModal-tests.tsx
  src/lib/utils/ArtworkInquiry/ArtworkInquiryStore.tsx
  src/lib/utils/ArtworkInquiry/ArtworkInquiryTypes.ts
Labels: Squash On Green

#4126 fix: sale status on sale screen
  src/__generated__/RegisterToBidButtonTestsQuery.graphql.ts
  src/__generated__/RegisterToBidButton_sale.graphql.ts
  src/__generated__/SaleAboveTheFoldQuery.graphql.ts
  src/__generated__/SaleInfoQueryRendererQuery.graphql.ts
  src/__generated__/SaleInfoTestsQuery.graphql.ts
  src/__generated__/SaleInfo_sale.graphql.ts
  src/__generated__/SaleRefetchQuery.graphql.ts
  src/__generated__/Sale_sale.graphql.ts
  src/lib/Scenes/Sale/Components/RegisterToBidButton.tsx
  src/lib/Scenes/Sale/Sale.tsx
  src/lib/Scenes/Sale/__tests__/helpers-tests.ts
  src/lib/Scenes/Sale/helpers.ts
  src/lib/Scenes/SaleInfo/SaleInfo.tsx
Labels: Squash On Green

#4119 fix: round down to one decimal in demand label #trivial
  src/lib/Scenes/MyCollection/Screens/ArtworkDetail/Components/ArtworkInsights/MyCollectionArtworkDemandIndex.tsx
Labels: Squash On Green

#4123 fix: register to bid button tracking
  package.json
  src/__generated__/RegisterToBidButtonTestsQuery.graphql.ts
  src/__generated__/RegisterToBidButton_sale.graphql.ts
  src/__generated__/SaleAboveTheFoldQuery.graphql.ts
  src/__generated__/SaleInfoQueryRendererQuery.graphql.ts
  src/__generated__/SaleInfoTestsQuery.graphql.ts
  src/__generated__/SaleInfo_sale.graphql.ts
  src/__generated__/SaleRefetchQuery.graphql.ts
  src/lib/Scenes/Sale/Components/RegisterToBidButton.tsx
  src/lib/Scenes/Sale/Sale.tsx
  src/lib/Scenes/Sale/__tests__/RegisterToBidButton-tests.tsx
  src/lib/Scenes/SaleInfo/SaleInfo.tsx
  src/lib/utils/track/schema.ts
  yarn.lock
Labels: Jira Synced

#4127 chore: add filter params changed tracking event
  src/lib/Components/FilterModal/FilterModal.tsx
Labels: Jira Synced, Squash On Green

#4129 fix: set close button property in modals
  CHANGELOG.yml
  src/lib/AppRegistry.tsx
Labels: Jira Synced

#4132 fix: show 2 skeleton adjustment
  CHANGELOG.yml
  src/lib/Scenes/Show2/Show2.tsx
Labels: Jira Synced, Squash On Green

#4133 fix: add feedback to more info about this auction button
  CHANGELOG.yml
  src/lib/Components/Buttons/CaretButton.tsx
  src/lib/Components/Buttons/__tests__/CaretButton-tests.tsx
Labels: Jira Synced, Squash On Green

#4134 fix(show): only display sort/filter control if eligible artworks present
  CHANGELOG.yml
  src/lib/Scenes/Show2/Show2.tsx
  src/lib/Scenes/Show2/__tests__/Show2-tests.tsx
Labels: Jira Synced

#4128 fix: add extra padding to new show screen
  CHANGELOG.yml
  src/lib/Scenes/Show2/Show2.tsx
Labels: Jira Synced, Squash On Green

#4130 fix: link sort and filter screen to scroll position on new show screen
  CHANGELOG.yml
  src/lib/Scenes/Show2/Show2.tsx
Labels: Jira Synced, Squash On Green

#4135 fix: pass id into event instead of slug
  CHANGELOG.yml
  src/lib/Scenes/Sale/Sale.tsx
Labels: Jira Synced

#4136 Preparing for development, version 6.7.1
  Artsy Stickers/Info.plist
  Artsy/App_Resources/Artsy-Info.plist
  CHANGELOG.yml
Labels: Jira Synced, Squash On Green

#4114 Display error message when an inquiry is unable to be sent
  src/lib/Scenes/Artwork/Components/CommercialButtons/InquiryModal.tsx
  src/lib/Scenes/Artwork/Components/CommercialButtons/__tests__/InquiryModal-tests.tsx
  src/lib/Scenes/Artwork/Components/Mutation/SubmitInquiryRequest.ts
Labels: Jira Synced

#4139 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4145 fix(tooling): reorganize podfile a tiny bit and fix RN version in podfile.lock
  Artsy.xcodeproj/project.pbxproj
  Podfile
  Podfile.lock
Labels: Jira Synced

#4148 chore: remove back arrow analytics tracking
  Artsy/App/ARAnalyticsConstants.h
  Artsy/App/ARAnalyticsConstants.m
  Artsy/View_Controllers/Util/ARNavigationController.m
  CHANGELOG.yml
Labels: Jira Synced

#4149 fix: persist shipping location for inquiry requests
  src/lib/Scenes/Artwork/Components/CommercialButtons/InquiryModal.tsx
  src/lib/Scenes/Artwork/Components/CommercialButtons/LocationAutocomplete.tsx
  src/lib/Scenes/Artwork/Components/CommercialButtons/ShippingModal.tsx
  src/lib/Scenes/Artwork/Components/CommercialButtons/__tests__/InquiryModal-tests.tsx
  src/lib/Scenes/Artwork/Components/CommercialButtons/__tests__/LocationAutocomplete-tests.tsx
  src/lib/Scenes/Artwork/Components/Mutation/SubmitInquiryRequest.ts
  src/lib/utils/ArtworkInquiry/ArtworkInquiryTypes.ts
  src/lib/utils/__tests__/googleMaps-tests.ts
  src/lib/utils/googleMaps.ts
Labels: Jira Synced, Squash On Green

#4150 fix: minimize startup api requests
  Artsy/App/ARAppNotificationsDelegate.m
  Artsy/Networking/API_Modules/ARUserManager.m
  Artsy/Networking/ARRouter.h
  Artsy/Networking/ARRouter.m
  Artsy/Tooling/ARWebViewCacheHost.m
  CHANGELOG.yml
Labels: Jira Synced

#4152 feat: add insights tab to artist tab
  Artsy/App/AROptions.h
  Artsy/App/AROptions.m
  images/info.png
  images/info@2x.png
  images/info@3x.png
  src/lib/AppRegistry.tsx
  src/lib/Components/Artist/ArtistInsights/ArtistInsights.tsx
  src/lib/Components/Artist/ArtistInsights/__tests__/ArtistInsights-tests.tsx
  src/lib/Scenes/Artist/Artist.tsx
  src/lib/Scenes/Artist/Components/ArtistMarketStats.tsx
  src/lib/Scenes/Artist/__tests__/Artist-tests.tsx
  src/lib/store/NativeModel.ts
  src/setupJest.ts
Labels: Squash On Green

#4153 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4155 fix: my collection visual qa #trivial
  src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkArtistArticles.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkArtistAuctionResults.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkInsights.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/__tests__/MyCollectionArtworkArtistArticles-tests.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/Components/WhySell.tsx
Labels: Jira Synced, Squash On Green

#4143 [PURCHASE-2099] Enhancement: Enable inquiry request notifications
  src/__generated__/InquiryButtonsTestsQuery.graphql.ts
  src/lib/Scenes/Artwork/Components/CommercialButtons/InquiryButtons.tsx
  src/lib/Scenes/Artwork/Components/CommercialButtons/InquiryModal.tsx
  src/lib/Scenes/Artwork/Components/CommercialButtons/InquirySuccessNotification.tsx
  src/lib/Scenes/Artwork/Components/CommercialButtons/__tests__/InquiryButtons-tests.tsx
  src/lib/Scenes/Artwork/Components/CommercialButtons/__tests__/InquiryModal-tests.tsx
  src/lib/Scenes/Artwork/Components/Mutation/SubmitInquiryRequest.ts
Labels: Jira Synced, Merge On Green

#4157 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4156 feat: change title and ordering of artwork price range filter
  src/lib/Components/ArtworkFilterOptions/PriceRangeOptions.tsx
  src/lib/Components/ArtworkFilterOptions/__tests__/PriceRangeOptions-tests.tsx
  src/lib/utils/ArtworkFilter/FilterArtworksHelpers.ts
Labels: Jira Synced

#4159 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4158 fix: Ensure image still renders if first message empty
  src/lib/Scenes/Inbox/Components/Conversations/MessageGroup.tsx
  src/lib/Scenes/Inbox/Components/Conversations/Messages.tsx
Labels: Jira Synced, Squash On Green

#4147 feat: Remove request price CTA in favor of only contact gallery
  src/lib/Scenes/Artwork/Components/CommercialButtons/InquiryButtons.tsx
  src/lib/Scenes/Artwork/Components/CommercialButtons/__tests__/CommercialButtons-tests.tsx
Labels: Jira Synced, Squash On Green

#4161 feat: first inquiry custom message
  src/lib/Scenes/Artwork/Components/CommercialButtons/InquiryModal.tsx
  src/lib/Scenes/Artwork/Components/CommercialButtons/__tests__/CommercialButtons-tests.tsx
  src/lib/Scenes/Artwork/Components/CommercialButtons/__tests__/InquiryModal-tests.tsx
  src/lib/Scenes/Artwork/Components/Mutation/SubmitInquiryRequest.ts
  src/lib/utils/ArtworkInquiry/ArtworkInquiryStore.tsx
  src/lib/utils/ArtworkInquiry/ArtworkInquiryTypes.ts
  src/lib/utils/ArtworkInquiry/__tests__/ArtworkInquiryStore-tests.tsx
Labels: Jira Synced, Squash On Green

#4167 Update metaphysics schema
  data/schema.graphql
  src/__generated__/createConsignmentSubmissionMutation.graphql.ts
Labels: Merge On Green

#4166 fix: Form now resets on successful mutation
  src/lib/Scenes/Artwork/Components/CommercialButtons/InquiryModal.tsx
Labels: Jira Synced

#4168 chore: don't pass email to segment #trivial
  Artsy/App/ARSegmentProvider.m
  CHANGELOG.yml
Labels: Jira Synced

#4169 feat: respect artwork size when showing price estimates
  src/__generated__/MyCollectionArtworkInsightsTestsQuery.graphql.ts
  src/__generated__/MyCollectionArtworkPriceEstimateTestsQuery.graphql.ts
  src/__generated__/MyCollectionArtworkPriceEstimate_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkPriceEstimate_marketPriceInsights.graphql.ts
  src/__generated__/MyCollectionArtworkQuery.graphql.ts
  src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkPriceEstimate.tsx
Labels: Jira Synced

#4172 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4175 fix(analytics): updates fair/show screen schema naming
  src/lib/utils/track/schema.ts
Labels: Jira Synced

#4173 chore: update colors
  CHANGELOG.yml
  Podfile.lock
  src/lib/Scenes/Artwork/Components/__tests__/CommercialInformation-tests.tsx
  src/palette/Theme.tsx
Labels: Squash On Green

#4183 fix: add spinner to artist artworks infinite scroll
  CHANGELOG.yml
  src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
Labels: Jira Synced, Squash On Green

#4180 feat(my collection): dynamic helper text
  CHANGELOG.yml
  src/__generated__/MyCollectionArtworkInsightsTestsQuery.graphql.ts
  src/__generated__/MyCollectionArtworkInsights_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkQuery.graphql.ts
  src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkInsights.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/__tests__/MyCollectionArtworkInsights-tests.tsx
Labels: Jira Synced

#4184 fix: avoid shrinking the background on non-fullscreen fancy modals
  CHANGELOG.yml
  src/lib/Components/FancyModal/FancyModal.tsx
  src/lib/Components/FancyModal/FancyModalCard.tsx
  src/lib/Components/FancyModal/FancyModalContext.tsx
Labels: Jira Synced

#4186 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4185 tooling(relay-tests): add default mock resolvers and an array generator and some helpers
  CHANGELOG.yml
  patches/@types+relay-test-utils+6.0.1.patch
  src/lib/Scenes/Sale/__tests__/RegisterToBidButton-tests.tsx
  src/lib/Scenes/ViewingRoom/Components/__tests__/ViewingRoomSubsections-tests.tsx
  src/lib/Scenes/ViewingRoom/__tests__/ViewingRoomArtworks-tests.tsx
  src/lib/tests/mockEnvironmentPayload.ts
Labels: Jira Synced, Squash On Green

#4181 feat: create past shows view
  CHANGELOG.yml
  src/__generated__/ArtistShows2PastShowsQuery.graphql.ts
  src/__generated__/ArtistShows2Query.graphql.ts
  src/__generated__/ArtistShows2TestsQuery.graphql.ts
  src/__generated__/ArtistShows2_artist.graphql.ts
  src/lib/AppRegistry.tsx
  src/lib/Components/Artist/ArtistShows/ArtistShow.tsx
  src/lib/Components/Artist/ArtistShows/SmallList.tsx
  src/lib/Scenes/ArtistShows/ArtistShows2.tsx
  src/lib/Scenes/ArtistShows/__tests__/ArtistShows2-tests.tsx
  src/lib/navigation/routes.tsx
Labels: Jira Synced

#4187 Preparing for development, version 6.7.3
  Artsy Stickers/Info.plist
  Artsy/App_Resources/Artsy-Info.plist
  CHANGELOG.yml
Labels: Jira Synced, Squash On Green

#4188 Fix: Contact gallery should be primary
  src/lib/Scenes/Artwork/Components/CommercialButtons/InquiryButtons.tsx
Labels: Jira Synced, Squash On Green

#4190 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green
