Repository artsy/eigen, pull requests merged in 2020-01, with the labels that each got.

#2977 Adds log out button to app
  Artsy/App/ARSwitchBoard.h
  Artsy/App/ARSwitchBoard.m
  Artsy/Networking/API_Modules/ARUserManager.m
  Artsy/View_Controllers/App_Navigation/ARTopMenuViewController.h
  Artsy/View_Controllers/App_Navigation/ARTopMenuViewController.m
  CHANGELOG.yml
  Podfile
  Podfile.lock
Labels: Merge On Green

#2986 update emission to v 1.21.6
  Podfile
  Podfile.lock
Labels: Merge On Green

#2964 [MX-50] - Clean up from Artwork rebuild release
  Artsy.xcodeproj/project.pbxproj
  Artsy/App/ARAppDelegate+Analytics.m
  Artsy/App/ARAppDelegate+Emission.m
  Artsy/App/AROptions.h
  Artsy/App/AROptions.m
  Artsy/App/ARSwitchBoard+Eigen.h
  Artsy/App/ARSwitchBoard.h
  Artsy/App/ARSwitchBoard.m
  Artsy/App/ARSwitchboard+Eigen.m
  Artsy/Navigation_Transitions/ARNavigationTransitionController.m
  Artsy/Navigation_Transitions/ARViewInRoomTransition.h
  Artsy/Navigation_Transitions/ARViewInRoomTransition.m
  Artsy/Navigation_Transitions/ARZoomImageTransition.h
  Artsy/Navigation_Transitions/ARZoomImageTransition.m
  Artsy/Resources/Artsy-Bridging-Header.h
  Artsy/View_Controllers/App_Navigation/ARContentViewControllers.h
  Artsy/View_Controllers/Artwork/ARArtworkInfoViewController.h
  Artsy/View_Controllers/Artwork/ARArtworkInfoViewController.m
  Artsy/View_Controllers/Artwork/ARArtworkViewController+ButtonActions.h
  Artsy/View_Controllers/Artwork/ARArtworkViewController+ButtonActions.m
  Artsy/View_Controllers/Artwork/ARArtworkViewController.h
  Artsy/View_Controllers/Artwork/ARArtworkViewController.m
  Artsy/View_Controllers/Artwork/ARLegacyArtworkViewController.h
  Artsy/View_Controllers/Artwork/ARLegacyArtworkViewController.m
  Artsy/View_Controllers/Artwork/ARZoomArtworkImageViewController.h
  Artsy/View_Controllers/Artwork/ARZoomArtworkImageViewController.m
  Artsy/View_Controllers/Auction/AuctionViewController.swift
  Artsy/View_Controllers/AuctionBuyNowView.swift
  Artsy/View_Controllers/Auction_Results/ARAuctionWebViewController.m
  Artsy/View_Controllers/Image/ARTiledImageDataSourceWithImage.h
  Artsy/View_Controllers/Image/ARTiledImageDataSourceWithImage.m
  Artsy/View_Controllers/Search/UIViewController+Search.m
  Artsy/Views/Artwork/ARArtworkRelatedArtworksView.h
  Artsy/Views/Artwork/ARArtworkRelatedArtworksView.m
  Artsy/Views/Artwork/ARArtworkView.h
  Artsy/Views/Artwork/ARArtworkView.m
  Artsy/Views/Table_View_Cells/Feed_Items/Modern/ARModernPartnerShowTableViewCell.m
  Artsy/Views/Utilities/Image/ARTile+ASCII.h
  Artsy/Views/Utilities/Image/ARTile+ASCII.m
  Artsy/Views/Utilities/Image/ARZoomView.h
  Artsy/Views/Utilities/Image/ARZoomView.m
  Artsy_Tests/App_Tests/ARAppActivityContinuationDelegateTests.m
  Artsy_Tests/App_Tests/ARSwitchBoardTests.m
  Artsy_Tests/View_Controller_Tests/Artwork/ARArtworkInfoViewControllerTests.m
  Artsy_Tests/View_Controller_Tests/Artwork/ARArtworkViewControllerTests.m
  Artsy_Tests/View_Controller_Tests/Artwork/ARLegacyArtworkViewControllerBuyButtonTests.m
  Artsy_Tests/View_Controller_Tests/Image/ARTiledImageDataSourceWithImageTests.m
  Artsy_Tests/View_Controller_Tests/Web_Browsing/ARAuctionWebViewControllerTests.m
  Artsy_Tests/View_Tests/ARArtworkRelatedArtworksViewTests.m
  CHANGELOG.yml
  Podfile
  Podfile.lock
Labels: Jira Synced, Merge On Green

#2987 Change default collection + upgrade emission
  Artsy/View_Controllers/Admin/ARAdminSettingsViewController.m
  Podfile
  Podfile.lock
Labels: Merge On Green

#2988 [MX-149] Enables new Search for all users
  Artsy/View_Controllers/App_Navigation/ARTopMenuNavigationDataSource.m
  Artsy/Views/Utilities/ARTabContentView.m
  CHANGELOG.yml
Labels: Jira Synced

#2989 Update emission
  Podfile
  Podfile.lock
Labels: Merge On Green

#2992 upgrade emission to 1.21.11
  Podfile
  Podfile.lock
Labels: Merge On Green

#2994 [MX-151] clear search history on log out
  Artsy/Networking/API_Modules/ARUserManager.m
  CHANGELOG.yml
Labels: Merge On Green

#2995 [MX-96] Remove redundant analytics for Artist screen views
  Artsy/App/ARAnalyticsConstants.h
  Artsy/App/ARAnalyticsConstants.m
  Artsy/App/ARAppDelegate+Analytics.m
Labels: Merge On Green

#2996 [MX-154] - Fix auction banner display on iOS 13
  Artsy/Views/Auction/AuctionBannerView.swift
  Artsy_Tests/ReferenceImages/AuctionViewControllerTests/looking_correct_when_an_auction_is_closed@3x.png
  Artsy_Tests/ReferenceImages/AuctionViewControllerTests/lot_standings__looks_good_with_lot_standings@3x.png
  Artsy_Tests/ReferenceImages/AuctionViewControllerTests/shows_a_message_about_an_upcoming_live_auction@3x.png
  CHANGELOG.yml
Labels: Merge On Green

#2999 Upgrade Emission to 1.21.24
  Artsy/View_Controllers/Admin/ARAdminSettingsViewController.m
  Podfile
  Podfile.lock
Labels: Merge On Green

#3001 Upgrades Emission to 1.21.27
  Podfile
  Podfile.lock
Labels: Merge On Green

#3004 Upgrades emission to 1.21.28
  Podfile
  Podfile.lock
Labels: Merge On Green

#3005 Upgrades Emission to 1.21.29
  Podfile
  Podfile.lock
Labels: Merge On Green

#3006 Upgrades Emission to 1.21.31
  Podfile
  Podfile.lock
Labels: Merge On Green
