Repository artsy/eigen, pull requests merged in 2020-09, with the labels that each got.

#3741 [MX-482] Update auction artwork tiles
  emission/Pod/Classes/GraphQL/ARGraphQLQueryMap.generated.objc
  src/__generated__/ArtistAboveTheFoldQuery.graphql.ts
  src/__generated__/ArtistArtworksQuery.graphql.ts
  src/__generated__/ArtistSeriesArtworksInfiniteScrollGridQuery.graphql.ts
  src/__generated__/ArtistSeriesArtworksTestsQuery.graphql.ts
  src/__generated__/ArtistSeriesQuery.graphql.ts
  src/__generated__/ArtistSeriesTestsQuery.graphql.ts
  src/__generated__/ArtworkBelowTheFoldQuery.graphql.ts
  src/__generated__/ArtworkGridItem_artwork.graphql.ts
  src/__generated__/ArtworkRefetchQuery.graphql.ts
  src/__generated__/ArtworksInSeriesRailTestsQuery.graphql.ts
  src/__generated__/ArtworksInSeriesRail_artwork.graphql.ts
  src/__generated__/CollectionArtworksInfiniteScrollGridQuery.graphql.ts
  src/__generated__/CollectionArtworksTestsQuery.graphql.ts
  src/__generated__/CollectionQuery.graphql.ts
  src/__generated__/CollectionTestsQuery.graphql.ts
  src/__generated__/DetailTestsQuery.graphql.ts
  src/__generated__/FairArtworksQuery.graphql.ts
  src/__generated__/FairBoothQuery.graphql.ts
  src/__generated__/FairDetailShowsQuery.graphql.ts
  src/__generated__/FairQuery.graphql.ts
  src/__generated__/FavoriteArtworksPaginationQuery.graphql.ts
  src/__generated__/FavoriteArtworksQuery.graphql.ts
  src/__generated__/FeatureQuery.graphql.ts
  src/__generated__/FilterModalTestsQuery.graphql.ts
  src/__generated__/FilteredInfiniteScrollGridQuery.graphql.ts
  src/__generated__/GenePaginationQuery.graphql.ts
  src/__generated__/GeneQuery.graphql.ts
  src/__generated__/HomeQuery.graphql.ts
  src/__generated__/HomeRefetchQuery.graphql.ts
  src/__generated__/InfiniteScrollArtworksGridTestsQuery.graphql.ts
  src/__generated__/LotsByFollowedArtistsQuery.graphql.ts
  src/__generated__/MyProfileQuery.graphql.ts
  src/__generated__/MyProfileRefetchQuery.graphql.ts
  src/__generated__/PartnerArtworkInfiniteScrollGridQuery.graphql.ts
  src/__generated__/PartnerArtworkTestsQuery.graphql.ts
  src/__generated__/PartnerQuery.graphql.ts
  src/__generated__/PartnerRefetchQuery.graphql.ts
  src/__generated__/SalesQuery.graphql.ts
  src/__generated__/SalesQueryRendererQuery.graphql.ts
  src/__generated__/ShowArtworksPreviewTestsQuery.graphql.ts
  src/__generated__/ShowArtworksQuery.graphql.ts
  src/__generated__/ShowArtworksTestsQuery.graphql.ts
  src/__generated__/ShowQuery.graphql.ts
  src/__generated__/ShowTestsQuery.graphql.ts
  src/__generated__/SmallTileRail_artworks.graphql.ts
  src/__generated__/VanityURLEntityQuery.graphql.ts
  src/__generated__/WorksForYouPaginationQuery.graphql.ts
  src/__generated__/WorksForYouQuery.graphql.ts
  src/__generated__/indexTestsQuery.graphql.ts
  src/lib/Components/ArtworkGrids/ArtworkGridItem.tsx
  src/lib/Components/ArtworkGrids/__tests__/ArtworkGridItem-tests.tsx
  src/lib/Components/ArtworkTileRail/ArtworkTileRailCard.tsx
  src/lib/Scenes/Artwork/Components/ArtworksInSeriesRail.tsx
  src/lib/Scenes/Home/Components/SmallTileRail.tsx
  src/lib/utils/__tests__/getUrgencytag-tests.ts
  src/lib/utils/getUrgencyTag.ts
Labels: Jira Synced, Merge On Green

#3763 [PURCHASE-2053] Restyled conversations list to look closer to web
  src/__generated__/ConversationSnippet_conversation.graphql.ts
  src/__generated__/ConversationsQuery.graphql.ts
  src/__generated__/Conversations_me.graphql.ts
  src/__generated__/InboxQuery.graphql.ts
  src/__generated__/InboxRefetchQuery.graphql.ts
  src/lib/Components/Inbox/Conversations/ConversationSnippet.tsx
  src/lib/Components/Inbox/Conversations/Conversations.tsx
Labels: Jira Synced

#3801 [MX-526] - Fix fair map crash, more reliable directions links
  CHANGELOG.yml
  src/lib/Components/LocationMap/index.tsx
  src/lib/Scenes/Partner/Components/PartnerMap.tsx
Labels: Jira Synced, Merge On Green

#3806 Removes AFNetworking/UIKit subspec
  Artsy/App/ARAppDelegate+Analytics.m
  Artsy/Categories/AFNetworking/AFHTTPRequestOperation+JSON.m
  Artsy/Models/API_Models/Partner_Metadata/Artwork.m
  Artsy/Networking/API_Modules/ArtsyAPI+Artworks.m
  Artsy/Networking/API_Modules/ArtsyAPI+ErrorHandlers.m
  Artsy/Networking/API_Modules/ArtsyAPI+ListCollection.h
  Artsy/Networking/API_Modules/ArtsyAPI+Notifications.h
  Artsy/Networking/API_Modules/ArtsyAPI+Sailthru.m
  Artsy/Networking/ARRouter.m
  Artsy/Networking/Network_Models/ARFavoritesNetworkModel.m
  Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/5-_Onboarding_Personalization/ARPersonalizeViewController.m
  Artsy/View_Controllers/Util/Logging/ARHTTPRequestOperationLogger.m
  Artsy_Tests/Networking_Tests/AFHTTPRequestOperationJSONTests.m
  Artsy_Tests/Stubs/OHHTTPStubs+Artsy.m
  Artsy_Tests/Supporting_Files/Artsy_Tests-Prefix.pch
  CHANGELOG.yml
  Podfile
  Podfile.lock
Labels: Jira Synced, Merge On Green

#3807 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3808 Create Lab Option to develop new inquiry UI features
  Artsy/App/ARAppDelegate+Emission.m
  Artsy/App/AROptions.h
  Artsy/App/AROptions.m
  Artsy_Tests/App_Tests/ARAppDelegateEmissionSpec.m
  CHANGELOG.yml
  src/lib/Scenes/Artwork/Components/CommercialInformation.tsx
  src/lib/store/NativeModel.ts
  src/setupJest.ts
Labels: Jira Synced, Merge On Green

#3809 [MX-462] - Disable idfa access by Facebook sdk
  Artsy/App_Resources/Artsy-Info.plist
  Artsy/Networking/ARAuthProviders.m
  Artsy/View_Controllers/Admin/ARAdminSettingsViewController.m
  CHANGELOG.yml
  Podfile
  Podfile.lock
Labels: Jira Synced, Merge On Green

#3805 [MX-463] - Disable idfa collection in segment
  Artsy.xcodeproj/project.pbxproj
  Artsy/App/ARAppDelegate+Analytics.m
  Artsy/App/ARSegmentProvider.h
  Artsy/App/ARSegmentProvider.m
  CHANGELOG.yml
Labels: Jira Synced, Merge On Green

#3811 Prepares for 6.6.3 development
  Artsy Stickers/Info.plist
  Artsy/App_Resources/Artsy-Info.plist
  CHANGELOG.yml
Labels: Jira Synced, Merge On Green

#3804 Typeable app module definitions
  CHANGELOG.yml
  src/lib/AppRegistry.tsx
Labels: Merge On Green

#3810 Avoids installing CocoaPods on CI if cache is available #trivial
  .circleci/config.yml
Labels: Jira Synced

#3815 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3816 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3817 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3818 chore: remove swift build flags
  Makefile
Labels: Jira Synced

#3813 chore: [MX-286] migrate away from UIWebView
  Artsy_Tests/View_Controller_Tests/Web_Browsing/ARExternalWebBrowserViewControllerTests.m
  Artsy_Tests/View_Controller_Tests/Web_Browsing/ARInternalMobileWebViewControllerTests.m
  CHANGELOG.yml
Labels: Jira Synced

#3812 Feature flag doc updates cleanup remove unnecessary OR #trivial
  Artsy/App/ARAppDelegate+Emission.m
  Artsy_Tests/View_Controller_Tests/Auction/AuctionViewControllerTests.swift
  Artsy_Tests/View_Controller_Tests/Auction/SaleArtworkViewModelTests.swift
  Artsy_Tests/View_Controller_Tests/SaleOnHoldOverlayViewTests.swift
  Artsy_Tests/View_Tests/Auctions/AuctionTitleViewTests.swift
  docs/developing_a_feature.md
Labels: Merge On Green

#3820 Bidding status messages match most specs
  src/__generated__/ClosedLot_lotStanding.graphql.ts
  src/__generated__/MyBidsQuery.graphql.ts
  src/__generated__/MyBids_me.graphql.ts
  src/lib/Scenes/MyBids/Components/ActiveLot.tsx
  src/lib/Scenes/MyBids/Components/BiddingStatuses.tsx
  src/lib/Scenes/MyBids/Components/ClosedLot.tsx
  src/lib/Scenes/MyBids/Components/index.tsx
  src/lib/Scenes/MyBids/__tests__/index-tests.tsx
  src/lib/Scenes/MyBids/helpers/__tests__/saleTime-tests.tsx
  src/lib/Scenes/MyBids/helpers/saleTime.tsx
  src/lib/Scenes/MyBids/index.tsx
  src/palette/svgs/ArrowCircleFillIcons.tsx
  src/palette/svgs/index.tsx
Labels: Jira Synced

#3822 [MyCollection] Comment out TBD sections
  src/lib/Scenes/MyCollection/Screens/ArtworkDetail/MyCollectionArtworkDetail.tsx
Labels: Merge On Green

#3823 Fixes deploys by removing Fastfile check #trivial
  fastlane/Fastfile
Labels: Jira Synced, Merge On Green

#3824 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3831 Enable autofill on email field on login
  Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/3_-_Sign_Up_+_Log_In/ARLoginFieldsView.m
Labels: Jira Synced

#3834 Resolutions
  HACKS.md
  package.json
  yarn.lock
Labels: Jira Synced

#3832 Clean up Makefile; fix broken links in documentation
  Makefile
  README.md
  docs/getting_started.md
Labels: Merge On Green

#3840 Update metaphysics schema
  data/schema.graphql
  src/__generated__/MyCollectionArtworkModelCreateArtworkMutation.graphql.ts
  src/__generated__/MyCollectionArtworkModelUpdateArtworkMutation.graphql.ts
Labels: Merge On Green

#3842 IDFA toggle
  CHANGELOG.yml
  fastlane/Fastfile
Labels: Jira Synced

#3846 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3837 Erikdstock mybids statuses
  src/lib/Scenes/MyBids/Components/BiddingStatuses.tsx
  src/lib/Scenes/MyBids/Components/ClosedLot.tsx
  src/lib/Scenes/MyBids/Components/Lot.tsx
  src/lib/Scenes/MyBids/Components/SaleCard.tsx
  src/lib/Scenes/MyBids/Components/SaleTime.tsx
  src/lib/Scenes/MyBids/__tests__/ActiveLot-tests.tsx
  src/lib/Scenes/MyBids/__tests__/ClosedLot-tests.tsx
  src/lib/Scenes/MyBids/__tests__/SaleTime-tests.tsx
  src/lib/Scenes/MyBids/helpers/__tests__/saleTime-tests.tsx
  src/lib/Scenes/MyBids/helpers/index.tsx
  src/lib/Scenes/MyBids/helpers/saleTime.tsx
  src/palette/svgs/Icon.tsx
  src/palette/svgs/sf/BoltCircleFill.tsx
  src/palette/svgs/sf/BoltFill.tsx
  src/palette/svgs/sf/BookmarkFill.tsx
  src/palette/svgs/sf/ClockFill.tsx
  src/palette/svgs/sf/ExclamationMarkCircleFill.tsx
  src/palette/svgs/sf/README.md
  src/palette/svgs/sf/StarCircleFill.tsx
  src/palette/svgs/sf/Stopwatch.tsx
  src/palette/svgs/sf/index.ts
Labels: Jira Synced

#3849 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3850 Fix auction tiles layout
  src/lib/Components/ArtworkGrids/ArtworkGridItem.tsx
  src/lib/utils/__tests__/getUrgencytag-tests.ts
  src/lib/utils/getUrgencyTag.ts
Labels: Jira Synced

#3845 [MX-409] - Add react-native-webview and feature flag
  Artsy/App/ARAppDelegate+Emission.m
  Artsy/App/AROptions.h
  Artsy/App/AROptions.m
  CHANGELOG.yml
  Podfile
  Podfile.lock
  emission/Pod/Classes/TemporaryAPI/ARTemporaryAPIModule.h
  emission/Pod/Classes/TemporaryAPI/ARTemporaryAPIModule.m
  package.json
  src/lib/Components/WebView/RelativeURLWebView.tsx
  src/lib/Components/WebView/__tests__/RelativeURLWebView-tests.tsx
  src/lib/Scenes/VanityURL/VanityURLEntity.tsx
  src/lib/Scenes/VanityURL/__tests__/VanityURLEntity-tests.tsx
  src/lib/store/NativeModel.ts
  src/setupJest.ts
  typings/emission.d.ts
  yarn.lock
Labels: Jira Synced, Merge On Green

#3844 [MX-506] Fix gene tabs strange transition
  src/lib/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx
  src/lib/Containers/Gene.tsx
Labels: Jira Synced, Merge On Green

#3838 Add new buttons with clear call to action in commercial information
  CHANGELOG.yml
  src/__generated__/ArtworkAboveTheFoldQuery.graphql.ts
  src/__generated__/ArtworkRefetchQuery.graphql.ts
  src/__generated__/CommercialButtonsTestsMutationQuery.graphql.ts
  src/__generated__/CommercialButtonsTestsRenderQuery.graphql.ts
  src/__generated__/CommercialButtons_artwork.graphql.ts
  src/__generated__/InquiryButtons_artwork.graphql.ts
  src/lib/Scenes/Artwork/Components/CommercialButtons/CommercialButtons.tsx
  src/lib/Scenes/Artwork/Components/CommercialButtons/InquiryButtons.tsx
  src/lib/Scenes/Artwork/Components/CommercialButtons/InquiryModal.tsx
  src/lib/Scenes/Artwork/Components/CommercialButtons/__tests__/CommercialButtons-tests.tsx
Labels: Jira Synced

#3851 [MX-306] fixed new works for you rail sorting
  CHANGELOG.yml
  Podfile.lock
  src/__generated__/WorksForYouPaginationQuery.graphql.ts
  src/__generated__/WorksForYouQuery.graphql.ts
  src/__generated__/WorksForYou_me.graphql.ts
  src/lib/Containers/WorksForYou.tsx
Labels: Jira Synced

#3798 Update Artwork Details section to display colored dot that indicates the availability of the artwork
  CHANGELOG.yml
  src/lib/Scenes/Artwork/Components/CommercialInformation.tsx
  src/lib/Scenes/Artwork/Components/__tests__/CommercialInformation-tests.tsx
Labels: Jira Synced, Merge On Green

#3858 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3855 Adds contributors to the thanks doc
  docs/thanks.md
Labels: Jira Synced, Squash On Green

#3857 docs: Rename map_to_app, add relay container docs #trivial
  docs/overview.md
  docs/preferred_practices.md
Labels: Jira Synced

#3853 Remove local VR flag
  Artsy/App/AROptions.h
  Artsy/App/AROptions.m
  Artsy/View_Controllers/Admin/ARAdminSettingsViewController.m
  src/lib/Scenes/Home/Home.tsx
  src/lib/store/NativeModel.ts
  src/setupJest.ts
Labels: Jira Synced

#3860 fix for vr subsections margin
  src/lib/Scenes/ViewingRoom/Components/ViewingRoomSubsections.tsx
  src/lib/Scenes/ViewingRoom/Components/__tests__/ViewingRoomSubsections-tests.tsx
Labels: Jira Synced

#3861 tiny palette cleanup, removing names for primitives
  src/palette/platform/primitives.ts
Labels: Jira Synced, Merge On Green

#3863 fix ArtworkArtists padding
  src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
Labels: Merge On Green

#3856 group lots by whether sale is closed, not per-lot
  CHANGELOG.yml
  src/__generated__/MyBidsQuery.graphql.ts
  src/__generated__/MyBids_me.graphql.ts
  src/__generated__/MyProfileQuery.graphql.ts
  src/__generated__/MyProfileRefetchQuery.graphql.ts
  src/__generated__/MyProfile_me.graphql.ts
  src/lib/Scenes/MyBids/Components/ClosedLot.tsx
  src/lib/Scenes/MyBids/__fixtures__/MyBidsQuery.ts
  src/lib/Scenes/MyBids/__tests__/index-tests.tsx
  src/lib/Scenes/MyBids/helpers/lotStanding.ts
  src/lib/Scenes/MyBids/index.tsx
  src/lib/Scenes/MyProfile/MyProfile.tsx
Labels: Jira Synced

#3862 Fix issue with register by field on auctions rail
  CHANGELOG.yml
  src/lib/Scenes/Home/Components/SalesRail.tsx
Labels: Jira Synced, Merge On Green

#3839 [MyCollection] Update create / edit form fields
  src/__generated__/MyCollectionArtworkDetailQuery.graphql.ts
  src/__generated__/MyCollectionArtworkMeta_artwork.graphql.ts
  src/lib/AppRegistry.tsx
  src/lib/Components/FancyModal/FancyModalHeader.tsx
  src/lib/Components/Select.tsx
  src/lib/Scenes/MyCollection/Screens/AddArtwork/AddEditArtwork.tsx
  src/lib/Scenes/MyCollection/Screens/AddArtwork/Components/Dimensions.tsx
  src/lib/Scenes/MyCollection/Screens/AddArtwork/Components/MediumPicker.tsx
  src/lib/Scenes/MyCollection/Screens/AddArtwork/Form/artworkSchema.tsx
  src/lib/Scenes/MyCollection/Screens/AddArtwork/Screens/AddDimensions.tsx
  src/lib/Scenes/MyCollection/Screens/AddArtwork/Screens/AdditionalDetails.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkDetail/Components/ArtworkMeta.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkDetail/Components/Field.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkDetail/Components/MyCollectionArtworkMeta.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkDetail/Components/WhySell.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkDetail/MyCollectionArtworkDetail.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkDetail/Screens/ViewAllDetails.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkList/MyCollectionArtworkList.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkList/MyCollectionArtworkListItem.tsx
  src/lib/Scenes/MyCollection/SellTabApp.tsx
  src/lib/Scenes/MyCollection/State/MyCollectionArtworkModel.tsx
  src/lib/Scenes/MyCollection/State/MyCollectionNavigationModel.tsx
Labels: Jira Synced, Merge On Green

#3836 feat: create a sale header component
  src/__generated__/SaleQueryRendererQuery.graphql.ts
  src/__generated__/Sale_sale.graphql.ts
  src/lib/Scenes/Sale/Components/SaleHeader.tsx
  src/lib/Scenes/Sale/Sale.tsx
  src/lib/Scenes/Sale/helpers/__tests__/auctionTime-tests.ts
  src/lib/Scenes/Sale/helpers/saleTime.ts
Labels: Jira Synced

#3865 [Consignments] Updates layout on My Collection Insights view
  src/__generated__/MyCollectionArtworkListItem_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkListQuery.graphql.ts
  src/lib/Scenes/MyCollection/Screens/ArtworkList/MyCollectionArtworkList.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkList/MyCollectionArtworkListItem.tsx
  src/lib/Scenes/MyCollection/utils/formatArtworkMedium.ts
Labels: Jira Synced

#3852 Add auctions CTA button
  CHANGELOG.yml
  src/__generated__/RegisterToBidButtonTestsQuery.graphql.ts
  src/__generated__/RegisterToBidButton_sale.graphql.ts
  src/__generated__/SaleQueryRendererQuery.graphql.ts
  src/__generated__/Sale_sale.graphql.ts
  src/lib/Scenes/Sale/Components/RegisterToBidButton.tsx
  src/lib/Scenes/Sale/Sale.tsx
  src/lib/Scenes/Sale/__tests__/RegisterToBidButton-tests.tsx
  src/lib/Scenes/Sale/__tests__/helpers-tests.ts
  src/lib/Scenes/Sale/helpers.ts
Labels: Jira Synced

#3869 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3870 [MyCollection] Update artwork detail screen to match latest comps
  src/__generated__/MyCollectionArtworkDetailQuery.graphql.ts
  src/__generated__/MyCollectionArtworkInsights_artwork.graphql.ts
  src/lib/Scenes/MyCollection/Components/ScreenMargin.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkDetail/Components/AuctionResults.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkDetail/Components/Insights.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkDetail/Components/MyCollectionArtworkInsights.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkDetail/Components/MyCollectionArtworkMeta.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkDetail/Components/WhySell.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkDetail/MyCollectionArtworkDetail.tsx
Labels: Merge On Green

#3868 Fix artwork page consignment link
  CHANGELOG.yml
  src/lib/Scenes/Artwork/Components/ArtworkExtraLinks/__tests__/index-tests.tsx
  src/lib/Scenes/Artwork/Components/ArtworkExtraLinks/index.tsx
  src/lib/Scenes/Artwork/Components/__tests__/CommercialInformation-tests.tsx
Labels: Jira Synced

#3875 Preparing for development, version 6.6.4
  Artsy Stickers/Info.plist
  Artsy/App_Resources/Artsy-Info.plist
  CHANGELOG.yml
  fastlane/metadata/en-US/release_notes.txt
Labels: Jira Synced, Squash On Green

#3876 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3878 Move artwork categories to a common util file
  CHANGELOG.yml
  src/lib/Scenes/Consignments/Screens/Metadata.tsx
  src/lib/Scenes/MyCollection/Screens/AddArtwork/Components/MediumPicker.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkList/MyCollectionArtworkListItem.tsx
  src/lib/utils/__tests__/artworkMediumCategories-tests.ts
  src/lib/utils/artworkMediumCategories.ts
Labels: Jira Synced

#3874 FX-2264/FX-2253/FX-2266: Small QA items for artist series
  src/lib/Components/Artist/ArtistArtworks/ArtistNotableWorksRail.tsx
  src/lib/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx
  src/lib/Components/HeaderTabGridPlaceholder.tsx
  src/lib/Scenes/ArtistSeries/ArtistSeries.tsx
  src/lib/Scenes/ArtistSeries/ArtistSeriesFullArtistSeriesList.tsx
  src/lib/Scenes/ArtistSeries/__tests__/ArtistSeriesFullArtistSeriesList-tests.tsx
  src/lib/utils/placeholders.tsx
Labels: Jira Synced, Squash On Green

#3882 remove Constants.h ref
  Artsy.xcodeproj/project.pbxproj
Labels: Jira Synced

#3871 [MyCollection] Wire up artwork details view to real data
  data/schema.graphql
  src/__generated__/MyCollectionArtworkArtistArticles_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkArtistAuctionResults_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkArtistMarket_marketPriceInsights.graphql.ts
  src/__generated__/MyCollectionArtworkDemandIndex_marketPriceInsights.graphql.ts
  src/__generated__/MyCollectionArtworkDetailMarketInsightsQuery.graphql.ts
  src/__generated__/MyCollectionArtworkDetailQuery.graphql.ts
  src/__generated__/MyCollectionArtworkHeader_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkInsights_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkInsights_marketPriceInsights.graphql.ts
  src/__generated__/MyCollectionArtworkMeta_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkPriceEstimate_marketPriceInsights.graphql.ts
  src/lib/Components/Select.tsx
  src/lib/Icons/TriangleDown.tsx
  src/lib/Scenes/Consignments/Screens/__tests__/Metadata-tests.tsx
  src/lib/Scenes/Consignments/index.tsx
  src/lib/Scenes/MyCollection/Screens/AddArtwork/AddEditArtwork.tsx
  src/lib/Scenes/MyCollection/Screens/AddArtwork/Screens/AdditionalDetails.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkDetail/Components/ArtworkInsights/InfoButton.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkDetail/Components/ArtworkInsights/InfoModal.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkDetail/Components/ArtworkInsights/MyCollectionArtworkArtistArticles.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkDetail/Components/ArtworkInsights/MyCollectionArtworkArtistAuctionResults.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkDetail/Components/ArtworkInsights/MyCollectionArtworkArtistMarket.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkDetail/Components/ArtworkInsights/MyCollectionArtworkDemandIndex.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkDetail/Components/ArtworkInsights/MyCollectionArtworkInsights.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkDetail/Components/ArtworkInsights/MyCollectionArtworkPriceEstimate.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkDetail/Components/ConsignCTA.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkDetail/Components/MyCollectionArtworkHeader.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkDetail/Components/MyCollectionArtworkInsights.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkDetail/Components/MyCollectionArtworkMeta.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkDetail/Components/WhySell.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkDetail/MyCollectionArtworkDetail.tsx
  src/lib/Scenes/MyCollection/State/MyCollectionArtworkModel.tsx
  src/lib/Scenes/MyCollection/State/MyCollectionNavigationModel.tsx
  src/lib/Scenes/MyCollection/utils/formatArtworkDimensions.ts
  src/lib/utils/__tests__/artworkMediumCategories-tests.ts
  src/lib/utils/artworkMediumCategories.ts
Labels: Consignments, Merge On Green

#3888 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3885 [MX-543] - Send id token from apple sign in
  Artsy/Networking/API_Modules/ARUserManager.h
  Artsy/Networking/API_Modules/ARUserManager.m
  Artsy/Networking/ARRouter.h
  Artsy/Networking/ARRouter.m
  Artsy/View_Controllers/Login_and_Onboarding/AROnboardingViewController.m
  Artsy_Tests/Networking_Tests/API_Modules/ARUserManagerTests.m
  Artsy_Tests/Stubs/ARUserManager+Stubs.m
  CHANGELOG.yml
Labels: Jira Synced

#3864 Unified Touchable
  CHANGELOG.yml
  src/lib/Components/Home/ArtistRails/ArtistCard.tsx
  src/lib/Components/Inbox/Conversations/ConversationSnippet.tsx
  src/lib/Components/Inbox/Conversations/Preview/ArtworkPreview.tsx
  src/lib/Components/Inbox/Conversations/Preview/Attachment/AttachmentPreview.tsx
  src/lib/Components/Inbox/Conversations/Preview/ShowPreview.tsx
  src/lib/Components/Lists/SavedItemRow.tsx
  src/lib/Components/Lists/ShowItemRow.tsx
  src/lib/Components/Select.tsx
  src/lib/Scenes/Collection/Components/CollectionHubsRails/FeaturedCollections/FeaturedCollectionsRail.tsx
  src/lib/Scenes/Consignments/Components/ImageSelection.tsx
  src/lib/Scenes/MyBids/Components/Lot.tsx
  src/lib/Scenes/MyBids/Components/SaleCard.tsx
  src/lib/Scenes/MyProfile/Components/MyProfileMenuItem.tsx
Labels: Jira Synced, Merge On Green

#3886 [MyCollection] Update my collection artwork detail data
  src/__generated__/MyCollectionArtworkArtistMarket_marketPriceInsights.graphql.ts
  src/__generated__/MyCollectionArtworkDetailMarketInsightsQuery.graphql.ts
  src/__generated__/MyCollectionArtworkListPaginationQuery.graphql.ts
  src/__generated__/MyCollectionArtworkListQuery.graphql.ts
  src/__generated__/MyCollectionArtworkList_me.graphql.ts
  src/__generated__/MyCollectionArtworkPriceEstimate_marketPriceInsights.graphql.ts
  src/lib/AppRegistry.tsx
  src/lib/Scenes/MyCollection/Components/Modal.tsx
  src/lib/Scenes/MyCollection/Components/Navigator.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkDetail/Components/ArtworkInsights/MyCollectionArtworkArtistArticles.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkDetail/Components/ArtworkInsights/MyCollectionArtworkArtistAuctionResults.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkDetail/Components/ArtworkInsights/MyCollectionArtworkArtistMarket.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkDetail/Components/ArtworkInsights/MyCollectionArtworkDemandIndex.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkDetail/Components/ArtworkInsights/MyCollectionArtworkInsights.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkDetail/Components/ArtworkInsights/MyCollectionArtworkPriceEstimate.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkDetail/Components/MyCollectionArtworkMeta.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkDetail/Components/WhySell.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkDetail/MyCollectionArtworkDetail.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkDetail/Screens/ViewAllDetails.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkList/MyCollectionArtworkList.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkList/MyCollectionArtworkListHeader.tsx
  src/lib/Scenes/MyCollection/Screens/Home/MyCollectionHome.tsx
  src/lib/Scenes/MyCollection/Screens/Home/MyCollectionMarketingHome.tsx
  src/lib/Scenes/MyCollection/State/MyCollectionArtworkModel.tsx
  src/lib/Scenes/MyCollection/State/MyCollectionNavigationModel.tsx
  src/lib/Scenes/MyCollection/utils/formatCentsToDollars.ts
Labels: Consignments, Merge On Green

#3892 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3884 Add skeleton Fair2 view
  .circleci/config.yml
  Artsy.xcodeproj/project.pbxproj
  Artsy/App/ARSwitchBoard.m
  Artsy/View_Controllers/Admin/ARAdminSettingsViewController.m
  CHANGELOG.yml
  src/__generated__/Fair2Query.graphql.ts
  src/__generated__/Fair2_fair.graphql.ts
  src/lib/AppRegistry.tsx
  src/lib/Scenes/Fair2/Fair2.tsx
Labels: Merge On Green

#3893 [MyCollection] Clean up navigation between MyCollection and consignments
  src/lib/Scenes/Consignments/Screens/Overview.tsx
  src/lib/Scenes/MyCollection/Boot.tsx
  src/lib/Scenes/MyCollection/Components/Navigator.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkDetail/MyCollectionArtworkDetail.tsx
  src/lib/Scenes/MyCollection/Screens/ConsignmentsHome/ConsignmentsHome.tsx
  src/lib/Scenes/MyCollection/Screens/ConsignmentsHome/ConsignmentsSubmissionForm.tsx
  src/lib/Scenes/MyCollection/State/MyCollectionNavigationModel.tsx
Labels: Jira Synced

#3895 [My Collection] Artist insights Navigation -> Editorial & Auction Results
  src/__generated__/MyCollectionArtworkArtistArticles_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkArtistAuctionResults_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkDetailQuery.graphql.ts
  src/lib/Scenes/MyCollection/Components/ScreenMargin.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkDetail/Components/ArtworkInsights/MyCollectionArtworkArtistArticles.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkDetail/Components/ArtworkInsights/MyCollectionArtworkArtistAuctionResults.tsx
  src/lib/Scenes/MyCollection/State/MyCollectionNavigationModel.tsx
Labels: Jira Synced, Merge On Green

#3889 Handle auction lot artwork onPress
  src/lib/Scenes/Sale/Components/SaleArtworksRail.tsx
  src/lib/Scenes/Sale/Sale.tsx
Labels: Jira Synced

#3835 Haptic feedback trial
  CHANGELOG.yml
  Podfile
  Podfile.lock
  package.json
  patches/react-native-haptic-feedback+1.10.0.patch
  src/lib/Components/Inbox/Conversations/Preview/__tests__/ArtworkPreview-tests.tsx
  src/lib/Scenes/Artwork/Components/ArtworkActions.tsx
  src/lib/Scenes/Artwork/Components/__tests__/ArtworkActions-tests.tsx
  src/palette/elements/Button/Button.tsx
  src/palette/elements/Touchable/Touchable.tsx
  yarn.lock
Labels: Jira Synced, Merge On Green

#3899 Update metaphysics schema
  data/schema.graphql
  src/__generated__/MyCollectionArtworkModelCreateArtworkMutation.graphql.ts
  src/__generated__/MyCollectionArtworkModelUpdateArtworkMutation.graphql.ts
Labels: Merge On Green

#3900 protect from having a nil string
  Artsy/App/ARSwitchBoard+Eigen.m
Labels: Jira Synced

#3902 [MX-548] - Change Echo.json to EchoNew.json, update Aerodramus
  .circleci/config.yml
  .gitignore
  Artsy.xcodeproj/project.pbxproj
  Artsy/App/ARSwitchBoard.m
  Artsy/App/ArtsyEcho.m
  CHANGELOG.yml
  HACKS.md
  Makefile
  Podfile
  Podfile.lock
  README.md
Labels: Jira Synced

#3891 My Bids QA items
  .env.example
  src/__generated__/ActiveLot_lotStanding.graphql.ts
  src/__generated__/ClosedLot_lotStanding.graphql.ts
  src/__generated__/MyBidsQuery.graphql.ts
  src/__generated__/MyBids_me.graphql.ts
  src/__generated__/SaleCard_sale.graphql.ts
  src/lib/Scenes/MyBids/Components/ActiveLot.tsx
  src/lib/Scenes/MyBids/Components/ClosedLot.tsx
  src/lib/Scenes/MyBids/Components/SaleCard.tsx
  src/lib/Scenes/MyBids/Components/SaleInfo.tsx
  src/lib/Scenes/MyBids/Components/SaleTime.tsx
  src/lib/Scenes/MyBids/__fixtures__/MyBidsQuery.ts
  src/lib/Scenes/MyBids/__tests__/ActiveLot-tests.tsx
  src/lib/Scenes/MyBids/__tests__/ClosedLot-tests.tsx
  src/lib/Scenes/MyBids/__tests__/SaleInfo-tests.tsx
  src/lib/Scenes/MyBids/__tests__/SaleTime-tests.tsx
  src/lib/Scenes/MyBids/__tests__/index-tests.tsx
  src/lib/Scenes/MyBids/helpers/lotStanding.ts
  src/lib/Scenes/MyBids/helpers/timely.ts
  src/lib/Scenes/MyBids/index.tsx
  src/lib/Scenes/MyProfile/MyProfile.tsx
Labels: Jira Synced

#3903 Feature/auction screen lots list
  CHANGELOG.yml
  Podfile.lock
  src/__generated__/SaleArtworkListItem_artwork.graphql.ts
  src/__generated__/SaleArtworkListQuery.graphql.ts
  src/__generated__/SaleArtworkList_me.graphql.ts
  src/__generated__/SaleLotsListTestsQuery.graphql.ts
  src/__generated__/SaleLotsList_me.graphql.ts
  src/__generated__/SaleQueryRendererQuery.graphql.ts
  src/lib/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx
  src/lib/Components/SwitchMenu.tsx
  src/lib/Scenes/MyProfile/MyProfilePushNotifications.tsx
  src/lib/Scenes/MyProfile/__tests__/MyProfilePushNotifications-tests.tsx
  src/lib/Scenes/Sale/Components/SaleArtworkList.tsx
  src/lib/Scenes/Sale/Components/SaleArtworkListItem.tsx
  src/lib/Scenes/Sale/Components/SaleLotsList.tsx
  src/lib/Scenes/Sale/Sale.tsx
  src/lib/Scenes/Sale/__tests__/SaleLotsList-tests.tsx
Labels: Jira Synced

#3904 revert util file use in Metadata component
  src/lib/Scenes/Consignments/Screens/Metadata.tsx
  src/lib/Scenes/Consignments/Screens/__tests__/Metadata-tests.tsx
Labels: Jira Synced, Merge On Green

#3901 FX-2265: User can filter artworks within an artist series
  CHANGELOG.yml
  src/__generated__/ArtistSeriesArtworksInfiniteScrollGridQuery.graphql.ts
  src/__generated__/ArtistSeriesArtworksTestsQuery.graphql.ts
  src/__generated__/ArtistSeriesArtworks_artistSeries.graphql.ts
  src/__generated__/ArtistSeriesQuery.graphql.ts
  src/__generated__/ArtistSeriesTestsQuery.graphql.ts
  src/__generated__/ArtistSeries_artistSeries.graphql.ts
  src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
  src/lib/Components/ArtworkGrids/FilteredArtworkGridZeroState.tsx
  src/lib/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx
  src/lib/Components/FilterModal.tsx
  src/lib/Scenes/ArtistSeries/ArtistSeries.tsx
  src/lib/Scenes/ArtistSeries/ArtistSeriesArtworks.tsx
  src/lib/Scenes/ArtistSeries/ArtistSeriesMeta.tsx
  src/lib/Scenes/ArtistSeries/__tests__/ArtistSeries-tests.tsx
  src/lib/Scenes/ArtistSeries/__tests__/ArtistSeriesArtworks-tests.tsx
  src/lib/Scenes/Collection/Screens/CollectionArtworks.tsx
Labels: Jira Synced, Merge On Green

#3909 [My Collection] Use product defined ranges to display liquidity values as text
  src/lib/Scenes/MyCollection/Screens/ArtworkDetail/Components/ArtworkInsights/MyCollectionArtworkArtistMarket.tsx
Labels: Jira Synced, Merge On Green

#3906 Preparing for development, version 6.6.5.
  Artsy Stickers/Info.plist
  Artsy/App_Resources/Artsy-Info.plist
  CHANGELOG.yml
Labels: Jira Synced, Squash On Green

#3912 [My Collection] Fix scroll bug on my collections artwork list
  src/lib/Scenes/MyCollection/Screens/ArtworkList/MyCollectionArtworkList.tsx
Labels: Jira Synced, Merge On Green

#3915 Update flip_table to include echo update
  Makefile
Labels: Merge On Green

#3914 [FX-2210] Implements fair editorial display
  CHANGELOG.yml
  src/__generated__/Fair2EditorialTestsQuery.graphql.ts
  src/__generated__/Fair2Editorial_fair.graphql.ts
  src/__generated__/Fair2Query.graphql.ts
  src/__generated__/Fair2TestsQuery.graphql.ts
  src/__generated__/Fair2_fair.graphql.ts
  src/lib/Scenes/Fair2/Components/Fair2Editorial.tsx
  src/lib/Scenes/Fair2/Fair2.tsx
  src/lib/Scenes/Fair2/__tests__/Fair2-tests.tsx
  src/lib/Scenes/Fair2/__tests__/Fair2Editorial-tests.tsx
Labels: Jira Synced, Merge On Green

#3917 [My Collection] Removes unnecessary refs from my collection Switchboard links
  src/lib/Scenes/MyCollection/Screens/ArtworkDetail/Components/ArtworkInsights/MyCollectionArtworkArtistArticles.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkDetail/Components/ArtworkInsights/MyCollectionArtworkArtistAuctionResults.tsx
Labels: Jira Synced

#3919 Update metaphysics schema
  data/schema.graphql
  src/__generated__/MyCollectionArtworkModelCreateArtworkMutation.graphql.ts
  src/__generated__/MyCollectionArtworkModelUpdateArtworkMutation.graphql.ts
Labels: Merge On Green

#3916 Refactors conditional section display #trivial
  src/__generated__/Fair2Query.graphql.ts
  src/__generated__/Fair2TestsQuery.graphql.ts
  src/__generated__/Fair2_fair.graphql.ts
  src/lib/Scenes/Fair2/Fair2.tsx
Labels: Merge On Green

#3918 [MyCollection] Fix invalid payload
  src/__generated__/MyCollectionArtworkModelCreateArtworkMutation.graphql.ts
  src/lib/Scenes/MyCollection/Screens/AddArtwork/Screens/AdditionalDetails.tsx
  src/lib/Scenes/MyCollection/State/MyCollectionArtworkModel.tsx
  src/lib/Scenes/MyCollection/utils/__tests__/cleanArtworkPayload-tests.ts
  src/lib/Scenes/MyCollection/utils/cleanArtworkPayload.ts
Labels: Merge On Green

#3921 fix(profile): long email truncate 🙄
  CHANGELOG.yml
  src/__generated__/MyAccountTestsQuery.graphql.ts
  src/lib/Scenes/MyAccount/MyAccount.tsx
  src/lib/Scenes/MyAccount/__tests__/MyAccount-tests.tsx
  src/lib/Scenes/MyProfile/Components/MyProfileMenuItem.tsx
Labels: Jira Synced

#3926 Code cleanup from #3771.
  Artsy/App/ARAppDelegate+Echo.m
  Artsy/App/ARAppDelegate.h
  Artsy/App/ARScreenPresenterModule.h
  Artsy/App/ARScreenPresenterModule.m
Labels: Jira Synced, Merge On Green

#3924 [FX-2211] Fair collections rail
  CHANGELOG.yml
  src/__generated__/Fair2CollectionsTestsQuery.graphql.ts
  src/__generated__/Fair2Collections_fair.graphql.ts
  src/__generated__/Fair2Query.graphql.ts
  src/__generated__/Fair2TestsQuery.graphql.ts
  src/__generated__/Fair2_fair.graphql.ts
  src/lib/Scenes/Fair2/Components/Fair2Collections.tsx
  src/lib/Scenes/Fair2/Fair2.tsx
  src/lib/Scenes/Fair2/__tests__/Fair2-tests.tsx
  src/lib/Scenes/Fair2/__tests__/Fair2Collections-tests.tsx
  src/palette/elements/Cards/SmallCard.tsx
  src/palette/elements/Touchable/TouchableWithScale.tsx
  src/palette/elements/Touchable/index.tsx
Labels: Jira Synced, Merge On Green

#3905 feat: show up to 50 artist series in the full list of series by an artist
  CHANGELOG.yml
  src/__generated__/ArtistSeriesFullArtistSeriesListQuery.graphql.ts
  src/__generated__/ArtistSeriesFullArtistSeriesListTestsQuery.graphql.ts
  src/__generated__/ArtistSeriesFullArtistSeriesList_artist.graphql.ts
  src/lib/Scenes/ArtistSeries/ArtistSeriesFullArtistSeriesList.tsx
Labels: Jira Synced, Merge On Green

#3920 Make mocked relay error more obvious
  src/lib/tests/renderWithWrappers.tsx
Labels: Merge On Green

#3927 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3928 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3922 feat: add LoadFailureViews on Viewing room screens
  CHANGELOG.yml
  src/lib/Scenes/ViewingRoom/ViewingRoom.tsx
  src/lib/Scenes/ViewingRoom/ViewingRoomArtwork.tsx
  src/lib/Scenes/ViewingRoom/ViewingRoomsList.tsx
Labels: Jira Synced

#3908 [FX-2246] Utilizes state to track loading
  src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
  src/lib/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx
  src/lib/Components/ArtworkGrids/__tests__/InfiniteScrollArtworksGrid-tests.tsx
  src/lib/Components/FilteredInfiniteScrollGrid/FilteredInfiniteScrollGrid.tsx
  src/lib/Containers/Gene.tsx
  src/lib/Scenes/ArtistSeries/ArtistSeriesArtworks.tsx
  src/lib/Scenes/Collection/Screens/CollectionArtworks.tsx
  src/lib/Scenes/Partner/Components/PartnerArtwork.tsx
  src/lib/Scenes/Sales/Components/LotsByFollowedArtists.tsx
Labels: Jira Synced, Merge On Green

#3930 fix: fix MyProfileMenuItem
  src/lib/Scenes/MyProfile/Components/MyProfileMenuItem.tsx
Labels: Jira Synced

#3933 Fixes automatic echo udpate in pod install #trivial
  Podfile
  Podfile.lock
Labels: Jira Synced

#3935 [MX-549] - align internal webview to parent vc, add dedicated routes for faqs
  Artsy/View_Controllers/Web_Browsing/ARInternalWebView.m
  CHANGELOG.yml
  src/lib/navigation/routes.tsx
Labels: Jira Synced, Merge On Green

#3932 Updates SailThru SDK #trivial
  Podfile.lock
Labels: Jira Synced, Merge On Green

#3867 Improve @prinicipalField behaviour
  CHANGELOG.yml
  src/lib/Scenes/Artwork/Artwork.tsx
  src/lib/relay/middlewares/__tests__/principalFieldErrorMiddleware-tests.ts
  src/lib/relay/middlewares/principalFieldErrorMiddleware.ts
Labels: Jira Synced, Merge On Green

#3936 [MX-553] fix: Bottom buttons in modals are obscured by keyboard
  src/lib/Components/Buttons/BottomAlignedButtonWrapper.tsx
  src/lib/Scenes/Consignments/Components/BottomAlignedButton.tsx
Labels: Jira Synced

#3934 FX-2213, FX-2214, FX-2215: Adds the Artworks and Exhibitors content to fair page
  CHANGELOG.yml
  src/__generated__/Fair2ArtworksInfiniteScrollGridQuery.graphql.ts
  src/__generated__/Fair2ArtworksTestsQuery.graphql.ts
  src/__generated__/Fair2Artworks_fair.graphql.ts
  src/__generated__/Fair2ExhibitorRailTestsQuery.graphql.ts
  src/__generated__/Fair2ExhibitorRail_show.graphql.ts
  src/__generated__/Fair2ExhibitorsQuery.graphql.ts
  src/__generated__/Fair2ExhibitorsTestsQuery.graphql.ts
  src/__generated__/Fair2Exhibitors_fair.graphql.ts
  src/__generated__/Fair2Query.graphql.ts
  src/__generated__/Fair2TestsQuery.graphql.ts
  src/__generated__/Fair2_fair.graphql.ts
  src/lib/Scenes/Fair2/Components/Fair2Artworks.tsx
  src/lib/Scenes/Fair2/Components/Fair2Collections.tsx
  src/lib/Scenes/Fair2/Components/Fair2Editorial.tsx
  src/lib/Scenes/Fair2/Components/Fair2ExhibitorRail.tsx
  src/lib/Scenes/Fair2/Components/Fair2Exhibitors.tsx
  src/lib/Scenes/Fair2/Components/SimpleTabs.tsx
  src/lib/Scenes/Fair2/Fair2.tsx
  src/lib/Scenes/Fair2/__tests__/Fair2-tests.tsx
  src/lib/Scenes/Fair2/__tests__/Fair2Artworks-tests.tsx
  src/lib/Scenes/Fair2/__tests__/Fair2ExhibitorRail-tests.tsx
  src/lib/Scenes/Fair2/__tests__/Fair2Exhibitors-tests.tsx
Labels: Jira Synced

#3937 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3939 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3940 Make access safer
  src/lib/Scenes/Collection/Components/FullFeaturedArtistList.tsx
Labels: Merge On Green

#3907 [MX-477] feat: added about page
  CHANGELOG.yml
  emission/Pod/Classes/TemporaryAPI/ARTemporaryAPIModule.m
  src/lib/AppRegistry.tsx
  src/lib/Components/MenuItem.tsx
  src/lib/Scenes/About/About.tsx
  src/lib/Scenes/About/__tests__/About-tests.tsx
  src/lib/Scenes/MyAccount/MyAccount.tsx
  src/lib/Scenes/MyProfile/MyProfile.tsx
  src/lib/Scenes/MyProfile/MyProfilePayment.tsx
  src/lib/navigation/__tests__/routes-tests.tsx
  src/lib/navigation/routes.tsx
  src/setupJest.ts
  typings/emission.d.ts
Labels: Jira Synced, Merge On Green

#3929 [MX-547] fix: center filters modal title
  CHANGELOG.yml
  src/lib/Components/FilterModal.tsx
Labels: Jira Synced, Squash On Green

#3938 Fix various build-time warnings #trivial
  Artsy/App/ARAppDelegate+Emission.m
  Artsy/Networking/API_Modules/ArtsyAPI+Search.h
  Artsy/View_Controllers/App_Navigation/ARTopMenuViewController.m
  Artsy/View_Controllers/Util/Errors/ARNetworkErrorManager.m
  Podfile
  Podfile.lock
Labels: Jira Synced

#3945 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3946 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3949 FX-2216: Allows filtering on new fair page by defaults + Artists I Follow
  CHANGELOG.yml
  src/__generated__/Fair2ArtworksInfiniteScrollGridQuery.graphql.ts
  src/__generated__/Fair2ArtworksTestsQuery.graphql.ts
  src/__generated__/Fair2Artworks_fair.graphql.ts
  src/__generated__/Fair2Query.graphql.ts
  src/__generated__/Fair2TestsQuery.graphql.ts
  src/__generated__/Fair2_fair.graphql.ts
  src/lib/Components/ArtworkFilterOptions/ArtistsIFollowOptions.tsx
  src/lib/Components/FilterModal.tsx
  src/lib/Scenes/Collection/Helpers/FilterArtworksHelpers.ts
  src/lib/Scenes/Collection/Helpers/__tests__/FilterArtworksHelpers-tests.tsx
  src/lib/Scenes/Fair2/Components/Fair2Artworks.tsx
  src/lib/Scenes/Fair2/Components/SimpleTabs.tsx
  src/lib/Scenes/Fair2/Fair2.tsx
  src/lib/Scenes/Fair2/__tests__/Fair2Artworks-tests.tsx
  src/lib/utils/ArtworkFiltersStore.tsx
Labels: Jira Synced

#3952 chore: update podfile #trivial
  Podfile
  Podfile.lock
Labels: Jira Synced, Squash On Green

#3943 feat(My Collection): show edition data in form by default
  data/schema.graphql
  src/__generated__/MyCollectionArtworkDetailQuery.graphql.ts
  src/__generated__/MyCollectionArtworkDetail_sharedProps.graphql.ts
  src/__generated__/MyCollectionArtworkListItemTestsQuery.graphql.ts
  src/__generated__/MyCollectionArtworkListItem_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkListPaginationQuery.graphql.ts
  src/__generated__/MyCollectionArtworkListQuery.graphql.ts
  src/__generated__/MyCollectionArtworkListTestsQuery.graphql.ts
  src/__generated__/MyCollectionArtworkMetaTestsQuery.graphql.ts
  src/__generated__/MyCollectionArtworkMeta_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkModelCreateArtworkMutation.graphql.ts
  src/__generated__/MyCollectionArtworkModelUpdateArtworkMutation.graphql.ts
  src/lib/Scenes/MyCollection/Screens/AddArtwork/Screens/AdditionalDetails.tsx
  src/lib/Scenes/MyCollection/Screens/AddArtwork/Screens/__tests__/AdditionalDetails-tests.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkDetail/Components/MyCollectionArtworkMeta.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkDetail/Components/__tests__/MyCollectionArtworkMeta-tests.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkDetail/MyCollectionArtworkDetail.tsx
  src/lib/Scenes/MyCollection/State/MyCollectionArtworkModel.tsx
  src/lib/Scenes/MyCollection/State/MyCollectionNavigationModel.tsx
Labels: Jira Synced, Squash On Green

#3956 chore: update TOCropViewController to resolve hack #trivial
  HACKS.md
  Podfile
  Podfile.lock
Labels: Jira Synced, Squash On Green

#3881 [PURCHASE-2049][PURCHASE-2050]feat: group messages by date and update styles
  src/__generated__/ArtworkPreview_artwork.graphql.ts
  src/__generated__/ConversationQuery.graphql.ts
  src/__generated__/ImagePreview_attachment.graphql.ts
  src/__generated__/InquiryQuery.graphql.ts
  src/__generated__/Message_message.graphql.ts
  src/__generated__/MessagesQuery.graphql.ts
  src/__generated__/Messages_conversation.graphql.ts
  src/__generated__/SendConversationMessageMutation.graphql.ts
  src/__generated__/ShowPreview_show.graphql.ts
  src/lib/Components/Inbox/Conversations/Avatar.tsx
  src/lib/Components/Inbox/Conversations/Message.tsx
  src/lib/Components/Inbox/Conversations/MessageGroup.tsx
  src/lib/Components/Inbox/Conversations/Messages.tsx
  src/lib/Components/Inbox/Conversations/Preview/ArtworkPreview.tsx
  src/lib/Components/Inbox/Conversations/Preview/Attachment/AttachmentPreview.tsx
  src/lib/Components/Inbox/Conversations/Preview/Attachment/ImagePreview.tsx
  src/lib/Components/Inbox/Conversations/Preview/Attachment/PDFPreview.tsx
  src/lib/Components/Inbox/Conversations/Preview/Attachment/__tests__/ImagePreview-tests.tsx
  src/lib/Components/Inbox/Conversations/Preview/ShowPreview.tsx
  src/lib/Components/Inbox/Conversations/Preview/__tests__/ShowPreview-tests.tsx
  src/lib/Components/Inbox/Conversations/SendConversationMessage.ts
  src/lib/Components/Inbox/Conversations/TimeSince.tsx
  src/lib/Components/Inbox/Conversations/__tests__/Conversations-tests.tsx
  src/lib/Components/Inbox/Conversations/__tests__/Message-tests.tsx
  src/lib/Components/Inbox/Conversations/__tests__/Messages-tests.tsx
  src/lib/Components/Inbox/Conversations/utils/groupMessages.ts
  src/lib/Containers/Conversation.tsx
  src/lib/Scenes/ViewingRoom/ViewingRoomArtwork.tsx
  src/palette/elements/Touchable/Touchable.tsx
Labels: Jira Synced, Squash On Green
