Repository artsy/eigen, pull requests merged in 2020-08, with the labels that each got.

#3657 [MX-427] Update type on Artwork Pages
  src/lib/Scenes/Artwork/Components/AboutArtist.tsx
  src/lib/Scenes/Artwork/Components/AboutWork.tsx
  src/lib/Scenes/Artwork/Components/ArtworkDetails.tsx
  src/lib/Scenes/Artwork/Components/ArtworkHistory.tsx
  src/lib/Scenes/Artwork/Components/ArtworkTombstone.tsx
  src/lib/Scenes/Artwork/Components/OtherWorks/Header.tsx
  src/lib/Scenes/Artwork/Components/OtherWorks/__tests__/Header-tests.tsx
  src/lib/Scenes/Artwork/Components/PartnerCard.tsx
  src/lib/Scenes/Artwork/Components/__tests__/OtherWorks-tests.tsx
Labels: Jira Synced

#3658 [MX-437] Update type on Artwork Classifications
  src/lib/Scenes/ArtworkAttributionClassFAQ/ArtworkAttributionClassFAQ.tsx
  src/lib/Scenes/ArtworkAttributionClassFAQ/__tests__/ArtworkAttributionClassFAQ-tests.tsx
Labels: Jira Synced

#3660 [MX-458] - Add spacing beneath header on gallery page #trivial
  src/lib/Scenes/Partner/Components/PartnerHeader.tsx
Labels: Jira Synced

#3664 Update metaphysics schema
  data/schema.graphql
  src/__generated__/AutosuggestResultsPaginationQuery.graphql.ts
  src/__generated__/AutosuggestResultsQuery.graphql.ts
Labels: Merge On Green

#3662 Final qa vrs
  src/__generated__/ViewingRoomsListQuery.graphql.ts
  src/__generated__/ViewingRoomsList_query.graphql.ts
  src/lib/Scenes/ViewingRoom/Components/ViewingRoomsHomeRail.tsx
  src/lib/Scenes/ViewingRoom/ViewingRoomsList.tsx
  src/lib/Scenes/ViewingRoom/__tests__/ViewingRoomsList-tests.tsx
Labels: Merge On Green

#3667 [MX-492] - Disable sailthru swizzling to fix existing notifications
  Artsy/App/ARAppDelegate.m
  Artsy/App/ARAppNotificationsDelegate.m
Labels: Jira Synced, Merge On Green

#3661 fixed issue with push notification stickiness
  src/lib/Scenes/MyProfile/MyProfilePushNotifications.tsx
Labels: Merge On Green

#3669 Fix initial jump on tab load
  src/lib/Components/FancyModal/FancyModalContext.tsx
Labels: Merge On Green

#3670 Fix black background flash on intial tab load
  src/lib/Components/FancyModal/FancyModalContext.tsx
Labels: Merge On Green

#3663 Small ios things for vrs
  CHANGELOG.yml
  src/__generated__/ViewingRoomQuery.graphql.ts
  src/__generated__/ViewingRoomSubsectionsTestsQuery.graphql.ts
  src/__generated__/ViewingRoomSubsections_viewingRoom.graphql.ts
  src/__generated__/ViewingRoomTestsQuery.graphql.ts
  src/lib/Components/ReadMore.tsx
  src/lib/Scenes/ArtistSeries/ArtistSeriesMeta.tsx
  src/lib/Scenes/Artwork/Components/AboutArtist.tsx
  src/lib/Scenes/Artwork/Components/AboutWork.tsx
  src/lib/Scenes/Artwork/Components/ArtworkDetails.tsx
  src/lib/Scenes/Artwork/Components/ArtworkHistory.tsx
  src/lib/Scenes/Collection/Screens/CollectionHeader.tsx
  src/lib/Scenes/Partner/Components/PartnerOverview.tsx
  src/lib/Scenes/ViewingRoom/Components/ViewingRoomSubsections.tsx
  src/lib/Scenes/ViewingRoom/ViewingRoom.tsx
  src/lib/Scenes/ViewingRoom/ViewingRoomArtworks.tsx
Labels: Merge On Green

#3659 Partner view on ipad
  Artsy/View_Controllers/Fair/ARProfileViewController.m
  Artsy_Tests/View_Controller_Tests/Fair/ARProfileViewControllerTests.m
Labels: Merge On Green

#3672 Refactor push notifications settings
  src/__generated__/MyProfilePushNotificationsMutation.graphql.ts
  src/lib/Scenes/MyProfile/MyProfilePushNotifications.tsx
  src/lib/Scenes/MyProfile/__tests__/MyProfilePushNotifications-tests.tsx
Labels: Merge On Green

#3671 Maxwidth vr
  src/lib/Scenes/ViewingRoom/Components/ViewingRoomSubsections.tsx
  src/lib/Scenes/ViewingRoom/ViewingRoom.tsx
  src/palette/elements/Typography.tsx
  src/palette/elements/index.tsx
Labels: Jira Synced, Merge On Green

#3654 [MX-435] Refactor follows and saves
  CHANGELOG.yml
  src/__generated__/ArtistsMeQuery.graphql.ts
  src/__generated__/Artists_me.graphql.ts
  src/__generated__/FavoriteArtistsPaginationQuery.graphql.ts
  src/__generated__/FavoriteArtistsQuery.graphql.ts
  src/__generated__/FavoriteArtists_me.graphql.ts
  src/__generated__/FavoriteArtworksPaginationQuery.graphql.ts
  src/__generated__/FavoriteArtworksQuery.graphql.ts
  src/__generated__/FavoriteArtworks_me.graphql.ts
  src/__generated__/FavoriteCategoriesPaginationQuery.graphql.ts
  src/__generated__/FavoriteCategoriesQuery.graphql.ts
  src/__generated__/FavoriteCategories_me.graphql.ts
  src/__generated__/FavoriteFairsQuery.graphql.ts
  src/__generated__/FavoriteShowsPaginationQuery.graphql.ts
  src/__generated__/FavoriteShowsQuery.graphql.ts
  src/__generated__/FavoriteShows_me.graphql.ts
  src/__generated__/SavedFairItemRowMutation.graphql.ts
  src/lib/AppRegistry.tsx
  src/lib/Components/ArtworkGrids/ArtworkGridItem.tsx
  src/lib/Components/ArtworkGrids/GenericGrid.tsx
  src/lib/Components/Lists/SavedFairItemRow.tsx
  src/lib/Components/Lists/SavedItemRow.tsx
  src/lib/Components/Lists/ShowItemRow.tsx
  src/lib/Components/Lists/__tests__/SavedItemRow-tests.tsx
  src/lib/Components/States/ZeroState.tsx
  src/lib/Components/StickyTabPage/StickyTabPage.tsx
  src/lib/Components/StickyTabPage/StickyTabPageFlatList.tsx
  src/lib/Components/StickyTabPage/StickyTabPageTabBar.tsx
  src/lib/Containers/WorksForYou.tsx
  src/lib/Scenes/Favorites/Components/Artists/Relay/FavoriteArtists.tsx
  src/lib/Scenes/Favorites/Components/Artists/__tests__/index-tests.tsx
  src/lib/Scenes/Favorites/Components/Artworks/Relay/FavoriteArtworks.tsx
  src/lib/Scenes/Favorites/Components/Artworks/__tests__/index-tests.tsx
  src/lib/Scenes/Favorites/Components/Categories/Relay/FavoriteCategories.tsx
  src/lib/Scenes/Favorites/Components/Categories/__tests__/index-tests.tsx
  src/lib/Scenes/Favorites/Components/Fairs/Relay/FavoriteFairs.tsx
  src/lib/Scenes/Favorites/Components/Fairs/__tests__/index-tests.tsx
  src/lib/Scenes/Favorites/Components/Fairs/index.tsx
  src/lib/Scenes/Favorites/Components/Shows/Relay/FavoriteShows.tsx
  src/lib/Scenes/Favorites/Components/Shows/__tests__/index-tests.tsx
  src/lib/Scenes/Favorites/FavoriteArtists.tsx
  src/lib/Scenes/Favorites/FavoriteArtworks.tsx
  src/lib/Scenes/Favorites/FavoriteCategories.tsx
  src/lib/Scenes/Favorites/FavoriteShows.tsx
  src/lib/Scenes/Favorites/Favorites.tsx
  src/lib/Scenes/Favorites/__tests__/index-tests.tsx
  src/lib/Scenes/Favorites/index.tsx
  src/lib/utils/placeholders.tsx
Labels: Merge On Green

#3675 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3674 Use standard page template on featured artist list
  src/lib/Scenes/Collection/Components/FullFeaturedArtistList.tsx
Labels: Merge On Green

#3677 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3676 Adjust artwork separator horizontal margin
  src/lib/Scenes/Artwork/Artwork.tsx
Labels: Merge On Green

#3678 [MX-493] - Push notification authorization not determined state
  Artsy/App/ARAppDelegate+Emission.m
  Artsy/App/ARAppNotificationsDelegate.h
  Artsy/App/ARAppNotificationsDelegate.m
  CHANGELOG.yml
  emission/Pod/Classes/TemporaryAPI/ARTemporaryAPIModule.h
  emission/Pod/Classes/TemporaryAPI/ARTemporaryAPIModule.m
  src/lib/Scenes/MyProfile/MyProfilePushNotifications.tsx
  src/lib/Scenes/MyProfile/__tests__/MyProfilePushNotifications-tests.tsx
  src/setupJest.ts
  typings/emission.d.ts
Labels: Jira Synced, Merge On Green

#3679 Remove horizon block check for now #trivial
  .circleci/config.yml
Labels: Merge On Green

#3681 Fix fancy modal cleanup logic
  src/lib/Components/FancyModal/FancyModalContext.tsx
Labels: Merge On Green

#3685 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3683 docs
  docs/deploy_to_app_store.md
Labels: Merge On Green

#3682 Preparing for development, version 6.6.1
  Artsy Stickers/Info.plist
  Artsy/App_Resources/Artsy-Info.plist
  CHANGELOG.yml
Labels: Merge On Green

#3687 Revert "Remove horizon block check for now #trivial"
  .circleci/config.yml
Labels: Merge On Green

#3637 Adds Danger rules for unit testing best practices
  dangerfile.ts
  docs/map_to_the_app.md
Labels: Merge On Green

#3695 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3691 [MX-451] - Prevent follow button going off screen #trivial
  CHANGELOG.yml
  src/lib/Components/Artist/ArtistHeader.tsx
Labels: Jira Synced, Merge On Green

#3693 [MX-452] - Prevent follow button going off screen partner/artist page
  CHANGELOG.yml
  src/lib/Components/ArtistListItem.tsx
Labels: Jira Synced, Merge On Green

#3696 Use consistent max-width on HomeHero iPad
  CHANGELOG.yml
  src/lib/Scenes/Home/Components/HomeHero.tsx
Labels: Jira Synced, Merge On Green

#3697 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3698 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3703 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3694 [FX-2017] View Artist series on Artist Page
  Artsy/App/ARAppDelegate+Emission.m
  Artsy/App/AROptions.h
  Artsy/App/AROptions.m
  Artsy_Tests/App_Tests/ARAppDelegateEmissionSpec.m
  CHANGELOG.yml
  src/__generated__/ArtistAboveTheFoldQuery.graphql.ts
  src/__generated__/ArtistArtworksQuery.graphql.ts
  src/__generated__/ArtistArtworks_artist.graphql.ts
  src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
  src/lib/Scenes/ArtistSeries/ArtistSeries.tsx
  src/lib/Scenes/ArtistSeries/ArtistSeriesListItem.tsx
  src/lib/Scenes/ArtistSeries/ArtistSeriesMoreSeries.tsx
  src/lib/Scenes/ArtistSeries/__tests__/ArtistSeriesMoreSeries-tests.tsx
  src/setupJest.ts
  typings/emission.d.ts
Labels: Merge On Green

#3699 Users can see related artworks from an artist series on the artwork page
  CHANGELOG.yml
  src/__generated__/ArtistAboveTheFoldQuery.graphql.ts
  src/__generated__/ArtistArtworksQuery.graphql.ts
  src/__generated__/ArtistNotableWorksRailTestsQuery.graphql.ts
  src/__generated__/ArtistNotableWorksRail_artist.graphql.ts
  src/__generated__/ArtworkBelowTheFoldQuery.graphql.ts
  src/__generated__/ArtworkRefetchQuery.graphql.ts
  src/__generated__/Artwork_artworkBelowTheFold.graphql.ts
  src/__generated__/ArtworksInSeriesRailTestsQuery.graphql.ts
  src/__generated__/ArtworksInSeriesRail_artwork.graphql.ts
  src/lib/Components/Artist/ArtistArtworks/ArtistNotableWorksRail.tsx
  src/lib/Components/Artist/ArtistArtworks/__tests__/ArtistNotableWorksRail-tests.tsx
  src/lib/Components/ArtworkTileRail/ArtworkTileRail.tsx
  src/lib/Components/ArtworkTileRail/ArtworkTileRailCard.tsx
  src/lib/Components/ArtworkTileRail/__tests__/ArtworkTileRailCard-tests.tsx
  src/lib/Scenes/Artwork/Artwork.tsx
  src/lib/Scenes/Artwork/Components/ArtworksInSeriesRail.tsx
  src/lib/Scenes/Artwork/Components/__tests__/ArtworksInSeriesRail-tests.tsx
  src/lib/Scenes/Consignments/v2/Screens/ConsignmentsHome/Components/RecentlySold.tsx
  src/lib/Scenes/Home/Components/SmallTileRail.tsx
Labels: Merge On Green

#3706 [MX-458] - Update copy, spacing in partner header #trivial
  src/lib/Scenes/Partner/Components/PartnerHeader.tsx
  src/lib/Scenes/Partner/Components/__tests__/PartnerHeader-tests.tsx
Labels: Jira Synced, Merge On Green

#3707 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3709 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3708 make `Read more` text use the new type styles #trivial
  src/lib/Components/ReadMore.tsx
  src/lib/Components/__tests__/ReadMore-tests.tsx
Labels: Jira Synced, Merge On Green

#3710 Fix Artist Series header image border radius
  src/lib/Scenes/ArtistSeries/ArtistSeriesHeader.tsx
Labels: Jira Synced

#3711 Cleans up uses of createPaginationContainer
  CHANGELOG.yml
  src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
  src/lib/Components/FilteredInfiniteScrollGrid/FilteredInfiniteScrollGrid.tsx
  src/lib/Components/Inbox/Conversations/Conversations.tsx
  src/lib/Components/Inbox/Conversations/Messages.tsx
  src/lib/Containers/Gene.tsx
  src/lib/Containers/WorksForYou.tsx
  src/lib/Scenes/ArtistSeries/ArtistSeriesArtworks.tsx
  src/lib/Scenes/City/CityBMWList.tsx
  src/lib/Scenes/City/CityFairList.tsx
  src/lib/Scenes/City/CitySavedList.tsx
  src/lib/Scenes/City/CitySectionList.tsx
  src/lib/Scenes/Collection/Screens/CollectionArtworks.tsx
  src/lib/Scenes/Fair/Screens/FairArtists.tsx
  src/lib/Scenes/Fair/Screens/FairDetail.tsx
  src/lib/Scenes/Favorites/FavoriteArtists.tsx
  src/lib/Scenes/Favorites/FavoriteArtworks.tsx
  src/lib/Scenes/Favorites/FavoriteCategories.tsx
  src/lib/Scenes/Favorites/FavoriteShows.tsx
  src/lib/Scenes/MyProfile/MyProfilePayment.tsx
  src/lib/Scenes/Partner/Components/PartnerArtwork.tsx
  src/lib/Scenes/Partner/Components/PartnerOverview.tsx
  src/lib/Scenes/Partner/Components/PartnerShows.tsx
  src/lib/Scenes/Partner/Components/PartnerShowsRail.tsx
  src/lib/Scenes/Partner/Screens/PartnerLocations.tsx
  src/lib/Scenes/Sales/Components/LotsByFollowedArtists.tsx
  src/lib/Scenes/Search/AutosuggestResults.tsx
Labels: Merge On Green

#3716 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3717 User can see artist's artist series on the artwork page
  CHANGELOG.yml
  src/__generated__/ArtworkBelowTheFoldQuery.graphql.ts
  src/__generated__/ArtworkRefetchQuery.graphql.ts
  src/__generated__/Artwork_artworkBelowTheFold.graphql.ts
  src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
  src/lib/Scenes/ArtistSeries/ArtistSeries.tsx
  src/lib/Scenes/ArtistSeries/ArtistSeriesFullArtistSeriesList.tsx
  src/lib/Scenes/ArtistSeries/ArtistSeriesListItem.tsx
  src/lib/Scenes/ArtistSeries/ArtistSeriesMoreSeries.tsx
  src/lib/Scenes/Artwork/Artwork.tsx
  src/lib/Scenes/Artwork/__tests__/Artwork-tests.tsx
Labels: Merge On Green

#3721 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3720 [MX-483] Update subtitles to sentence case
  src/lib/Components/Home/ArtistRails/ArtistRail.tsx
  src/lib/Scenes/City/CityPicker.tsx
  src/lib/Scenes/City/Components/SavedEventSection/index.tsx
  src/lib/Scenes/MyProfile/MyProfile.tsx
  src/lib/Scenes/Search/CityGuideCTA.tsx
  src/lib/Scenes/Search/RecentSearches.tsx
  src/lib/Scenes/Search/__tests__/CityGuideCTA-tests.tsx
  src/lib/Scenes/Search/__tests__/Search-tests.tsx
  src/lib/Scenes/ViewingRoom/Components/ViewingRoomsHomeRail.tsx
Labels: Jira Synced, Merge On Green

#3723 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3726 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3728 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3729 [FX-2123] Update artworks counts for Artist Series
  CHANGELOG.yml
  src/__generated__/ArtistAboveTheFoldQuery.graphql.ts
  src/__generated__/ArtistArtworksQuery.graphql.ts
  src/__generated__/ArtistSeriesFullArtistSeriesListQuery.graphql.ts
  src/__generated__/ArtistSeriesFullArtistSeriesListTestsQuery.graphql.ts
  src/__generated__/ArtistSeriesFullArtistSeriesList_artist.graphql.ts
  src/__generated__/ArtistSeriesMoreSeriesTestsQuery.graphql.ts
  src/__generated__/ArtistSeriesMoreSeries_artist.graphql.ts
  src/__generated__/ArtistSeriesQuery.graphql.ts
  src/__generated__/ArtistSeriesTestsQuery.graphql.ts
  src/__generated__/ArtworkBelowTheFoldQuery.graphql.ts
  src/__generated__/ArtworkRefetchQuery.graphql.ts
  src/lib/Scenes/ArtistSeries/ArtistSeriesFullArtistSeriesList.tsx
  src/lib/Scenes/ArtistSeries/ArtistSeriesListItem.tsx
  src/lib/Scenes/ArtistSeries/ArtistSeriesMoreSeries.tsx
  src/lib/Scenes/ArtistSeries/__tests__/ArtistSeries-tests.tsx
  src/lib/Scenes/ArtistSeries/__tests__/ArtistSeriesFullArtistSeriesList-tests.tsx
  src/lib/Scenes/ArtistSeries/__tests__/ArtistSeriesListItem-tests.tsx
  src/lib/Scenes/ArtistSeries/__tests__/ArtistSeriesMoreSeries-tests.tsx
Labels: Jira Synced

#3733 [PURCHASE-2026] Add deep-link for force conversation inbox URL
  Artsy/App/ARSwitchBoard.m
Labels: Merge On Green

#3718 [MX-437] Update type gene category
  CHANGELOG.yml
  emission/Pod/Classes/SwitchViewComponent/ARSwitchViewManager.h
  emission/Pod/Classes/SwitchViewComponent/ARSwitchViewManager.m
  src/lib/Components/Gene/About.tsx
  src/lib/Components/Gene/Header.tsx
  src/lib/Components/StickyTabPage/StickyTabPage.tsx
  src/lib/Components/SwitchView.tsx
  src/lib/Components/Text/Headline.tsx
  src/lib/Containers/Gene.tsx
  src/lib/Containers/__tests__/Gene-tests.tsx
  src/setupJest.ts
Labels: Jira Synced, Merge On Green

#3719 [MX-496] Use palette's EntityHeader on FavoriteArtists list
  CHANGELOG.yml
  src/__generated__/FavoriteArtistsPaginationQuery.graphql.ts
  src/__generated__/FavoriteArtistsQuery.graphql.ts
  src/__generated__/FavoriteArtists_me.graphql.ts
  src/lib/Components/ArtistListItem.tsx
  src/lib/Components/__tests__/ArtistListItem-tests.tsx
  src/lib/Scenes/Favorites/FavoriteArtists.tsx
Labels: Jira Synced, Merge On Green

#3740 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3736 [MX-481] Hide artists with no published works
  CHANGELOG.yml
  src/__generated__/PartnerOverviewInfiniteScrollQuery.graphql.ts
  src/__generated__/PartnerOverviewTestsQuery.graphql.ts
  src/__generated__/PartnerOverview_partner.graphql.ts
  src/__generated__/PartnerQuery.graphql.ts
  src/__generated__/PartnerRefetchQuery.graphql.ts
  src/lib/Scenes/Partner/Components/PartnerOverview.tsx
  src/lib/Scenes/Partner/Components/__tests__/PartnerOverview-tests.tsx
Labels: Jira Synced, Merge On Green

#3737 [MX-483] Use sentence case for feature fairs
  src/lib/Scenes/Home/Components/FairsRail.tsx
Labels: Jira Synced, Merge On Green

#3738 updated type on about screen on gene
  src/lib/Components/Gene/About.tsx
  src/lib/Components/Gene/Biography.tsx
Labels: Jira Synced, Merge On Green

#3742 Fixes UI bugs found in QA #trivial
  src/lib/Scenes/Consignments/v2/SellTabApp.tsx
  src/lib/Scenes/Favorites/FavoriteArtists.tsx
  src/lib/Scenes/Favorites/FavoriteArtworks.tsx
  src/lib/Scenes/Favorites/FavoriteCategories.tsx
  src/lib/Scenes/Favorites/FavoriteShows.tsx
  src/lib/Scenes/ViewingRoom/ViewingRoom.tsx
  src/lib/Scenes/ViewingRoom/ViewingRoomArtwork.tsx
Labels: Jira Synced

#3743 Fix partner rendering
  CHANGELOG.yml
  src/__generated__/PartnerOverviewInfiniteScrollQuery.graphql.ts
  src/__generated__/PartnerOverviewTestsQuery.graphql.ts
  src/__generated__/PartnerOverview_partner.graphql.ts
  src/__generated__/PartnerQuery.graphql.ts
  src/__generated__/PartnerRefetchQuery.graphql.ts
  src/__generated__/PartnerShowsInfiniteScrollGridQuery.graphql.ts
  src/__generated__/PartnerShowsRailQuery.graphql.ts
  src/__generated__/PartnerShowsRail_partner.graphql.ts
  src/__generated__/PartnerShowsTestsQuery.graphql.ts
  src/__generated__/PartnerShows_partner.graphql.ts
  src/lib/Scenes/Partner/Components/PartnerOverview.tsx
  src/lib/Scenes/Partner/Components/PartnerShows.tsx
  src/lib/Scenes/Partner/Components/PartnerShowsRail.tsx
  src/lib/Scenes/Partner/Components/__tests__/PartnerOverview-tests.tsx
  src/lib/Scenes/Partner/Components/__tests__/PartnerShows-tests.tsx
Labels: Jira Synced, Merge On Green

#3746 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3747 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3749 Prepares for 6.6.2 development.
  Artsy Stickers/Info.plist
  Artsy/App_Resources/Artsy-Info.plist
  CHANGELOG.yml
Labels: Jira Synced, Merge On Green

#3752 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3754 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3725 [Hold] [MX-489] React native config
  .circleci/config.yml
  .env.example
  .gitignore
  Artsy/App/ARAppDelegate+Analytics.m
  Artsy/App/ARAppDelegate+Emission.m
  Artsy/App/ARAppDelegate.m
  Artsy/App/ArtsyEcho.m
  Artsy/Networking/ARAuthProviders.m
  Artsy/Networking/ARRouter.m
  Artsy_Tests/Supporting_Files/ARTestHelper.m
  CHANGELOG.yml
  Gemfile
  Gemfile.lock
  Makefile
  Podfile
  Podfile.lock
  docs/adding_new_keys.md
  emission/Pod/Classes/Core/AREmission.h
  emission/Pod/Classes/Core/AREmission.m
  fastlane/Fastfile
  package.json
  patches/react-native-config+1.3.3.patch
  scripts/generate-env.js
  src/lib/Components/Bidding/Screens/SelectCountry.tsx
  src/lib/Components/LocationMap/index.tsx
  src/lib/Scenes/Consignments/Screens/Location.tsx
  src/lib/Scenes/Map/GlobalMap.tsx
  src/lib/Scenes/Partner/Components/PartnerMap.tsx
  src/setupJest.ts
  typings/emission.d.ts
  yarn.lock
Labels: Jira Synced

#3755 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3735 adding names to migration versions
  CHANGELOG.yml
  docs/adding_state_migrations.md
  src/lib/store/__tests__/migration-tests.ts
  src/lib/store/migration.ts
Labels: Jira Synced, Merge On Green

#3750 Fix save button on shows
  CHANGELOG.yml
  src/lib/Components/Lists/ShowItemRow.tsx
Labels: Jira Synced, Merge On Green

#3756 [MyCollection] Wire up basic MP queries
  src/__generated__/MyCollectionArtworkDetailQuery.graphql.ts
  src/__generated__/MyCollectionArtworkListItem_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkListQuery.graphql.ts
  src/lib/AppRegistry.tsx
  src/lib/Scenes/Consignments/v2/Screens/ArtworkDetail/MyCollectionArtworkDetail.tsx
  src/lib/Scenes/Consignments/v2/Screens/ArtworkList/MyCollectionArtworkList.tsx
  src/lib/Scenes/Consignments/v2/Screens/ArtworkList/MyCollectionArtworkListItem.tsx
Labels: Consignments, Merge On Green

#3757 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3758 Update readme for react-native-config setup #trivial
  README.md
Labels: Merge On Green

#3751 [MX-510] Removes url request VCR developer tool
  Artsy/App/ARAppDelegate.m
  Artsy/App/AROptions.h
  Artsy/App/AROptions.m
  Artsy/View_Controllers/Admin/ARAdminSettingsViewController.m
  CHANGELOG.yml
  Podfile
  Podfile.lock
Labels: Jira Synced, Merge On Green

#3764 [PURCHASE-2051] Restyle reply box
  src/lib/Components/Inbox/Conversations/Composer.tsx
  src/lib/Components/Inbox/Conversations/__tests__/Composer-tests.tsx
Labels: Jira Synced

#3769 fix: change "sold by" to "from" in comm partner info
  src/lib/Scenes/Artwork/Components/CommercialPartnerInformation.tsx
  src/lib/Scenes/Artwork/Components/__tests__/CommercialPartnerInformation-tests.tsx
Labels: Jira Synced

#3776 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3770 fix: conform ipad empty search screen to iphone
  CHANGELOG.yml
  src/lib/Scenes/Search/Search.tsx
  src/lib/Scenes/Search/__tests__/Search-tests.tsx
Labels: Jira Synced

#3772 fix: empty search message font should be sans
  src/lib/Scenes/Search/AutosuggestResults.tsx
Labels: Jira Synced, Merge On Green

#3777 Fix modally-presented RN views
  CHANGELOG.yml
  patches/react-native+0.62.1.patch
  src/lib/AppRegistry.tsx
  src/lib/Containers/RegistrationFlow.tsx
Labels: Merge On Green

#3786 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3785 [MX-512] Adds new sale page
  Artsy/App/AROptions.h
  Artsy/App/AROptions.m
  Artsy/App/ARSwitchBoard+Eigen.m
  CHANGELOG.yml
  src/__generated__/SaleQueryRendererQuery.graphql.ts
  src/__generated__/Sale_sale.graphql.ts
  src/lib/AppRegistry.tsx
  src/lib/Scenes/Sale/Sale.tsx
  src/lib/Scenes/Sale/index.tsx
Labels: Jira Synced, Merge On Green

#3775 Removed unused API classes
  Artsy.xcodeproj/project.pbxproj
  Artsy/App/ARAppDelegate.m
  Artsy/Models/API_Models/Artwork_Metadata/Gene.h
  Artsy/Models/API_Models/Artwork_Metadata/Gene.m
  Artsy/Models/API_Models/Fair/Fair.h
  Artsy/Models/API_Models/Fair/Fair.m
  Artsy/Models/API_Models/Partner_Metadata/Artist.h
  Artsy/Models/API_Models/Partner_Metadata/Artist.m
  Artsy/Models/API_Models/Partner_Metadata/Artwork.h
  Artsy/Models/API_Models/Partner_Metadata/Artwork.m
  Artsy/Models/API_Models/Partner_Metadata/PartnerShow.h
  Artsy/Models/API_Models/Partner_Metadata/PartnerShow.m
  Artsy/Models/Feed_Timelines/ARFeedSubclasses.h
  Artsy/Models/Feed_Timelines/ARFeedSubclasses.m
  Artsy/Networking/API_Modules/ArtsyAPI+Artists.h
  Artsy/Networking/API_Modules/ArtsyAPI+Artists.m
  Artsy/Networking/API_Modules/ArtsyAPI+Artworks.h
  Artsy/Networking/API_Modules/ArtsyAPI+Artworks.m
  Artsy/Networking/API_Modules/ArtsyAPI+Fairs.h
  Artsy/Networking/API_Modules/ArtsyAPI+Fairs.m
  Artsy/Networking/API_Modules/ArtsyAPI+Feed.h
  Artsy/Networking/API_Modules/ArtsyAPI+Feed.m
  Artsy/Networking/API_Modules/ArtsyAPI+Genes.m
  Artsy/Networking/API_Modules/ArtsyAPI+ListCollection.h
  Artsy/Networking/API_Modules/ArtsyAPI+ListCollection.m
  Artsy/Networking/API_Modules/ArtsyAPI+RelatedModels.h
  Artsy/Networking/API_Modules/ArtsyAPI+RelatedModels.m
  Artsy/Networking/API_Modules/ArtsyAPI+Search.m
  Artsy/Networking/API_Modules/ArtsyAPI+Shows.h
  Artsy/Networking/API_Modules/ArtsyAPI+Shows.m
  Artsy/Networking/API_Modules/ArtsyAPI+SiteFunctions.h
  Artsy/Networking/API_Modules/ArtsyAPI+SiteFunctions.m
  Artsy/Networking/ARRouter.h
  Artsy/Networking/ARRouter.m
  Artsy/Networking/ArtworkSources/ARGeneArtworksNetworkModel.h
  Artsy/Networking/ArtworkSources/ARGeneArtworksNetworkModel.m
  Artsy/Networking/Network_Models/ARArtistNetworkModel.h
  Artsy/Networking/Network_Models/ARArtistNetworkModel.m
  Artsy/Networking/Network_Models/ARShowNetworkModel.h
  Artsy/Networking/Network_Models/ARShowNetworkModel.m
  Artsy/Resources/Artsy-Bridging-Header.h
  Artsy/View_Controllers/Fair/Network_Models/ARFairNetworkModel.h
  Artsy/View_Controllers/Fair/Network_Models/ARFairNetworkModel.m
  Artsy_Tests/Networking_Tests/API_Modules/ArtsyAPI+ArtworksTests.m
  Artsy_Tests/Networking_Tests/ARRouterTests.m
  Artsy_Tests/Networking_Tests/Collection/ARGeneArtworksNetworkModelTests.m
  Artsy_Tests/Networking_Tests/Networking_Models/ARFairNetworkModelTests.m
  Artsy_Tests/Networking_Tests/Networking_Models/ARShowNetworkModelTests.m
  Artsy_Tests/Supporting_Files/Artsy_Tests-Prefix.pch
  CHANGELOG.yml
Labels: Jira Synced, Merge On Green

#3791 Updates query used for artworks in series rail
  src/__generated__/ArtworkBelowTheFoldQuery.graphql.ts
  src/__generated__/ArtworkRefetchQuery.graphql.ts
  src/__generated__/Artwork_artworkBelowTheFold.graphql.ts
  src/__generated__/ArtworksInSeriesRailTestsQuery.graphql.ts
  src/__generated__/ArtworksInSeriesRail_artwork.graphql.ts
  src/lib/Scenes/Artwork/Artwork.tsx
  src/lib/Scenes/Artwork/Components/ArtworksInSeriesRail.tsx
  src/lib/Scenes/Artwork/Components/__tests__/ArtworksInSeriesRail-tests.tsx
Labels: Jira Synced, Merge On Green

#3789 [MX-480] Fix App crash when opened from a 404 page
  CHANGELOG.yml
  src/lib/Scenes/Artwork/Artwork.tsx
Labels: Jira Synced, Merge On Green

#3739 [MX-459] - Add skeleton loader for partner page, move unknown route logic to react side
  Artsy.xcodeproj/project.pbxproj
  Artsy/App/ARAppDelegate+Analytics.m
  Artsy/App/ARAppDelegate+Emission.m
  Artsy/App/ARSwitchBoard+Eigen.m
  Artsy/App/ARSwitchBoard.m
  Artsy/Categories/Apple/UIViewController+SimpleChildren.h
  Artsy/Categories/Apple/UIViewController+SimpleChildren.m
  Artsy/Models/API_Models/Social/Profile.m
  Artsy/View_Controllers/ARMutableLinkViewController.m
  Artsy/View_Controllers/Auction/AuctionViewController.swift
  Artsy/View_Controllers/Fair/AREigenFairComponentViewController.h
  Artsy/View_Controllers/Fair/AREigenFairComponentViewController.m
  Artsy/View_Controllers/Fair/ARProfileViewController.h
  Artsy/View_Controllers/Web_Browsing/ARInternalWebView.h
  Artsy/View_Controllers/Web_Browsing/ARInternalWebView.m
  Artsy/View_Controllers/Web_Browsing/ARInternalWebViewManager.h
  Artsy/View_Controllers/Web_Browsing/ARInternalWebViewManager.m
  Artsy_Tests/App_Tests/ARSwitchBoardTests.m
  Artsy_Tests/View_Controller_Tests/Fair/ARFairViewControllerTests.m
  Artsy_Tests/View_Controller_Tests/Fair/ARProfileViewControllerTests.m
  Artsy_Tests/View_Controller_Tests/Fair/square.png
  Artsy_Tests/View_Controller_Tests/Fair/wide.jpg
  CHANGELOG.yml
  emission/Pod/Classes/ViewControllers/ARFairComponentViewController.h
  emission/Pod/Classes/ViewControllers/ARFairComponentViewController.m
  src/__generated__/VanityURLEntityQuery.graphql.ts
  src/__generated__/VanityURLEntity_fairOrPartner.graphql.ts
  src/lib/AppRegistry.tsx
  src/lib/Components/HeaderTabGridPlaceholder.tsx
  src/lib/Components/InternalWebView.tsx
  src/lib/Containers/Artist.tsx
  src/lib/NativeModules/SwitchBoard.tsx
  src/lib/Scenes/Artwork/Components/PartnerCard.tsx
  src/lib/Scenes/City/Components/FairEventSection/Components/FairEventSectionCard.tsx
  src/lib/Scenes/City/Components/TabFairItemRow/index.tsx
  src/lib/Scenes/Fair/Fair.tsx
  src/lib/Scenes/Fair/__fixtures__/index.ts
  src/lib/Scenes/Home/Components/FairsRail.tsx
  src/lib/Scenes/Map/Components/ShowCard.tsx
  src/lib/Scenes/Partner/Partner.tsx
  src/lib/Scenes/Search/SearchResult.tsx
  src/lib/Scenes/Show/Components/ShowHeader/ShowHeader.tsx
  src/lib/Scenes/VanityURL/VanityURLEntity.tsx
  src/lib/Scenes/VanityURL/__tests__/VanityURLEntity-tests.tsx
Labels: Jira Synced, Merge On Green

#3793 [MX-505] - Add back deleted slider assets #trivial
  Artsy.xcodeproj/project.pbxproj
  Artsy/Resources/Assets/Range@2x.png
  Artsy/Resources/Assets/Thumb.png
  Artsy/Resources/Assets/Thumb@2x.png
  Artsy/Resources/Assets/Track@2x.png
  Artsy_Tests/ReferenceImages/RefinementOptionsViewControllerTests/enables_apply_reset_buttons_when_options_are_changed@3x.png
  Artsy_Tests/ReferenceImages/RefinementOptionsViewControllerTests/looks_good_by_default@3x.png
  Artsy_Tests/ReferenceImages/RefinementOptionsViewControllerTests/looks_good_when_configured_with_options_and_changed_options@3x.png
  Artsy_Tests/ReferenceImages/RefinementOptionsViewControllerTests/looks_good_when_reset@3x.png
  Artsy_Tests/ReferenceImages/RefinementOptionsViewControllerTests/looks_good_with_gene_refine_settings_showing_price@3x.png
  CHANGELOG.yml
Labels: Jira Synced

#3794 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3796 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3787 Erikstock mybids causality
  CHANGELOG.yml
  src/__generated__/ActiveLot_lotStanding.graphql.ts
  src/__generated__/Lot_saleArtwork.graphql.ts
  src/__generated__/MyBidsQuery.graphql.ts
  src/__generated__/MyBids_me.graphql.ts
  src/__generated__/MyBids_sales.graphql.ts
  src/__generated__/RecentlyClosedLot_lotStanding.graphql.ts
  src/__generated__/SaleCard_sale.graphql.ts
  src/lib/Scenes/MyBids/Components/ActiveLot.tsx
  src/lib/Scenes/MyBids/Components/Lot.tsx
  src/lib/Scenes/MyBids/Components/MyBidsPlaceholder.tsx
  src/lib/Scenes/MyBids/Components/RecentlyClosedLot.tsx
  src/lib/Scenes/MyBids/Components/SaleCard.tsx
  src/lib/Scenes/MyBids/Components/index.tsx
  src/lib/Scenes/MyBids/__fixtures__/MyBidsQuery.ts
  src/lib/Scenes/MyBids/__tests__/index-tests.tsx
  src/lib/Scenes/MyBids/helpers/__tests__/saleTime-tests.tsx
  src/lib/Scenes/MyBids/helpers/saleTime.tsx
  src/lib/Scenes/MyBids/index.tsx
Labels: Jira Synced, Merge On Green

#3802 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green
