Repository artsy/eigen, pull requests merged in 2020-12, with the labels that each got.

#4192 Update metaphysics schema
  data/schema.graphql
  src/__generated__/ConfirmBidUpdateUserMutation.graphql.ts
  src/__generated__/RegistrationUpdateUserMutation.graphql.ts
  src/__generated__/updateMyUserProfileMutation.graphql.ts
Labels: Merge On Green

#4182 fix: use MP money fields for My Bids floor selling price and online asking price (PURCHASE-2171)
  CHANGELOG.yml
  data/schema.graphql
  src/__generated__/ActiveLot_lotStanding.graphql.ts
  src/__generated__/ClosedLot_lotStanding.graphql.ts
  src/__generated__/MyBids2TestsQuery.graphql.ts
  src/__generated__/MyBidsQuery.graphql.ts
  src/lib/Scenes/MyBids/Components/ActiveLot.tsx
  src/lib/Scenes/MyBids/Components/ClosedLot.tsx
  src/lib/Scenes/MyBids/__tests__/ActiveLot-tests.tsx
  src/lib/Scenes/MyBids/__tests__/ClosedLot-tests.tsx
Labels: Jira Synced

#4191 fix(MyCollection): upload images synchronously, not async
  Podfile.lock
  src/lib/Scenes/MyCollection/Screens/ArtworkFormModal/MyCollectionArtworkFormModal.tsx
Labels: Jira Synced

#4193 [PURCH-2170] Fix My Bids text layout bugs on small screen devices
  Podfile.lock
  src/lib/Scenes/MyBids/Components/ActiveLot.tsx
  src/lib/Scenes/MyBids/Components/Lot.tsx
  src/lib/Scenes/MyBids/Components/SaleCard.tsx
  src/lib/Scenes/MyBids/MyBids.tsx
  src/lib/Scenes/MyBids/helpers/screenDimensions.ts
Labels: Jira Synced

#4197 Bugfix: Resolve broken master build
  src/__generated__/InboxQuery.graphql.ts
  src/__generated__/InboxRefetchQuery.graphql.ts
  src/__generated__/InboxTestsQuery.graphql.ts
  src/lib/Containers/__tests__/Inbox-tests.tsx
Labels: Jira Synced

#4201 [PURCH-2252] Fix drop shadow and padding on inquiry msg notification
  src/lib/Scenes/Artwork/Components/CommercialButtons/InquirySuccessNotification.tsx
Labels: Jira Synced

#4203 fix(fx-2397): changes artists filter label
  src/lib/utils/ArtworkFilter/ArtworkFiltersStore.tsx
  src/lib/utils/ArtworkFilter/__tests__/ArtworkFiltersStore-tests.tsx
Labels: Jira Synced

#4202 fix: Fix artwork information overlap in first inquiry collapse
  src/lib/Scenes/Artwork/Components/CommercialButtons/CollapsibleArtworkDetails.tsx
  src/lib/Scenes/Artwork/Components/CommercialButtons/__tests__/CollapsibleArtworkDetails-tests.tsx
  src/palette/elements/Collapse/Collapse.tsx
Labels: Jira Synced, Squash On Green

#4206 [PURCHASE-2253] Fix: enable active state on border when inq question selected
  src/lib/Scenes/Artwork/Components/CommercialButtons/InquiryModal.tsx
Labels: Jira Synced, Squash On Green

#4204 [PURCHASE-2249] First inquiry visual qa
  src/lib/Scenes/Artwork/Components/CommercialButtons/InquiryModal.tsx
Labels: Jira Synced

#4211 chore: add Sentry commit integration
  fastlane/Fastfile
Labels: Jira Synced, Squash On Green

#4209 enhancement: Remove the 'X' to exit the confirmation modal
  CHANGELOG.yml
  src/lib/Scenes/Artwork/Components/CommercialButtons/InquirySuccessNotification.tsx
Labels: Jira Synced

#4210 In the inquiry modal change 'Add Message' to 'Add message'
  src/lib/Scenes/Artwork/Components/CommercialButtons/InquiryModal.tsx
Labels: Jira Synced, Squash On Green

#4196 Update metaphysics schema
  data/schema.graphql
  src/__generated__/myCollectionAddArtworkMutation.graphql.ts
  src/__generated__/myCollectionEditArtworkMutation.graphql.ts
Labels: Merge On Green

#4212 fix: scroll to add message input on input focus
  CHANGELOG.yml
  src/lib/Scenes/Artwork/Components/CommercialButtons/InquiryModal.tsx
Labels: Jira Synced, Squash On Green

#4200 chore: Remove first inquiry flag
  Artsy/App/AROptions.m
  CHANGELOG.yml
Labels: Jira Synced

#4205 fix: handle iOS 14 photo picker UI in my collection
  CHANGELOG.yml
  Podfile.lock
  emission/Pod/Classes/Core/AREmission.h
  emission/Pod/Classes/Core/AREmission.m
  emission/Pod/Classes/EigenCommunications/ARPHPhotoPickerModule.h
  emission/Pod/Classes/EigenCommunications/ARPHPhotoPickerModule.m
  emission/Pod/Classes/TemporaryAPI/ARTemporaryAPIModule.m
  package.json
  patches/react-native-image-crop-picker+0.35.1.patch
  src/lib/Scenes/MyCollection/Screens/ArtworkFormModal/__tests__/MyCollectionArtworkFormModal-tests.tsx
  src/lib/Scenes/MyCollection/State/MyCollectionArtworkModel.tsx
  src/lib/Scenes/MyCollection/State/__tests__/MyCollectionArtworkModel-tests.tsx
  src/lib/utils/__tests__/hardware-tests.ts
  src/lib/utils/__tests__/requestPhotos-tests.ts
  src/lib/utils/hardware.ts
  src/lib/utils/requestPhotos.ts
  src/setupJest.ts
  typings/emission.d.ts
  yarn.lock
Labels: Jira Synced, Squash On Green

#4214 chore: Update demand index copy
  src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkDemandIndex.tsx
Labels: Jira Synced

#4216 chore(my collection): final copy changes
  CHANGELOG.yml
  src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkArtistAuctionResults.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkArtistMarket.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkFormModal/Components/Dimensions.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkFormModal/MyCollectionArtworkFormModal.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkFormModal/Screens/MyCollectionArtworkFormAdditionalDetails.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkFormModal/Screens/MyCollectionArtworkFormMain.tsx
Labels: Jira Synced

#4207 fix: selecting search suggestion requires double tap (to clear keyboard)
  Podfile.lock
  src/lib/Scenes/Artwork/Artwork.tsx
  src/lib/Scenes/Artwork/Components/CommercialButtons/LocationAutocomplete.tsx
  src/lib/Scenes/Artwork/Components/CommercialButtons/ShippingModal.tsx
Labels: Jira Synced

#4195 fix(my collection): save changes button state #trivial
  src/lib/Scenes/MyCollection/Screens/ArtworkFormModal/Screens/MyCollectionArtworkFormMain.tsx
Labels: Jira Synced

#4220 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4215 Bugfix: Conversation does not move to the top of the inbox when a gallery responds
  src/lib/Containers/Inbox/Inbox.tsx
  src/lib/Scenes/Inbox/Components/Conversations/Conversations.tsx
Labels: Jira Synced

#4223 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4224 fix: point to Pulley fork with iOS 14 fixes
  CHANGELOG.yml
  Podfile
  Podfile.lock
Labels: Jira Synced

#4222 chore: small copy fix: s/had/owned #minor
  src/lib/Scenes/Consignments/Screens/Provenance.tsx
Labels: Jira Synced

#4213 feat: wrap first inquiry checkbox with touchable
  src/lib/Components/Bidding/Components/Checkbox.tsx
  src/lib/Scenes/Artwork/Components/CommercialButtons/InquiryModal.tsx
Labels: Jira Synced

#4199 fix(fx-2415): adds footer whitespace
  src/lib/Scenes/Fair2/Fair2.tsx
Labels: Jira Synced

#4227 fix: ensure we do not override the onFocus prop
  CHANGELOG.yml
  src/lib/Components/TextArea.tsx
Labels: Jira Synced

#4232 chore(release): for 6.7.4 development work.
  Artsy Stickers/Info.plist
  Artsy/App_Resources/Artsy-Info.plist
  CHANGELOG.yml
Labels: Jira Synced, Squash On Green

#4231 feat(ci): add slack notification when betas fail
  CHANGELOG.yml
  fastlane/Fastfile
Labels: Squash On Green

#4226 feat: add auction lots history to Artist Insights Tab
  CHANGELOG.yml
  src/__generated__/ArtistBelowTheFoldQuery.graphql.ts
  src/__generated__/ArtistInsightsAuctionResultTestsQuery.graphql.ts
  src/__generated__/ArtistInsightsAuctionResult_auctionResult.graphql.ts
  src/__generated__/ArtistInsightsAuctionResultsQuery.graphql.ts
  src/__generated__/ArtistInsightsAuctionResultsTestsQuery.graphql.ts
  src/__generated__/ArtistInsightsAuctionResults_artist.graphql.ts
  src/__generated__/ArtistInsightsTestsQuery.graphql.ts
  src/__generated__/ArtistInsights_artist.graphql.ts
  src/lib/Components/Artist/ArtistHeader.tsx
  src/lib/Components/Artist/ArtistInsights/ArtistInsights.tsx
  src/lib/Components/Artist/ArtistInsights/ArtistInsightsAuctionResult.tsx
  src/lib/Components/Artist/ArtistInsights/ArtistInsightsAuctionResults.tsx
  src/lib/Components/Artist/ArtistInsights/__tests__/ArtistInsights-tests.tsx
  src/lib/Components/Artist/ArtistInsights/__tests__/ArtistInsightsAuctionResult-tests.tsx
  src/lib/Components/Artist/ArtistInsights/__tests__/ArtistInsightsAuctionResults-tests.tsx
  src/lib/Components/Bidding/Components/PaymentInfo.tsx
  src/lib/Components/CreditCardDetails.tsx
  src/lib/Components/HeaderTabGridPlaceholder.tsx
  src/lib/Components/StickyTabPage/StickyTabPageFlatList.tsx
  src/lib/Scenes/Artist/Artist.tsx
  src/lib/Scenes/Home/Components/FairsRail.tsx
  src/lib/Scenes/Home/Components/SalesRail.tsx
  src/palette/elements/EntityHeader/EntityHeader.tsx
  src/palette/elements/Typography/Typography.tsx
Labels: Jira Synced, Squash On Green

#4230 feat: Update inbox and my bids layout
  src/lib/Containers/Inbox/Inbox.tsx
  src/lib/Containers/__tests__/Inbox-tests.tsx
  src/lib/Scenes/Inbox/Components/Conversations/Conversations.tsx
  src/lib/Scenes/MyBids/Components/Lot.tsx
  src/lib/Scenes/MyBids/Components/NoBids.tsx
  src/lib/Scenes/MyBids/MyBids.tsx
  src/lib/Scenes/MyBids/__tests__/MyBids2-tests.tsx
  src/setupJest.ts
Labels: Jira Synced

#4234 fix: Fix check for checked property on Checkbox
  src/lib/Components/Bidding/Components/Checkbox.tsx
Labels: Jira Synced

#4235 chore: adds --no-verify to Makefile commands #trivial
  Makefile
Labels: Jira Synced

#4238 fix: Allow conversations to take up full height
  src/lib/Containers/Inbox/Inbox.tsx
  src/lib/Scenes/Inbox/Components/Conversations/Conversations.tsx
Labels: Jira Synced, Squash On Green

#4239 Fix: live lots a user is winning always appear as 'reserve not met'
  src/lib/Scenes/MyBids/Components/ActiveLot.tsx
  src/lib/Scenes/MyBids/__tests__/ActiveLot-tests.tsx
Labels: Jira Synced, Squash On Green

#4219 doc(HACKS): follow-up from #4185
  HACKS.md
Labels: Jira Synced

#4237 feat: Display interim status auctions in My Bids, and small UI fixes
  src/__generated__/InboxQuery.graphql.ts
  src/__generated__/InboxRefetchQuery.graphql.ts
  src/__generated__/InboxTestsQuery.graphql.ts
  src/__generated__/MyBidsPaginatedQuery.graphql.ts
  src/__generated__/MyBidsQuery.graphql.ts
  src/__generated__/MyBidsTestsQuery.graphql.ts
  src/__generated__/MyBids_me.graphql.ts
  src/lib/Scenes/MyBids/Components/Lot.tsx
  src/lib/Scenes/MyBids/Components/MyBidsPlaceholder.tsx
  src/lib/Scenes/MyBids/Components/SaleCard.tsx
  src/lib/Scenes/MyBids/MyBids.tsx
  src/lib/Scenes/MyBids/__fixtures__/MyBidsQuery.ts
  src/lib/Scenes/MyBids/__tests__/MyBids-tests.tsx
  src/lib/Scenes/MyBids/__tests__/MyBids2-tests.tsx
  src/lib/Scenes/MyBids/__tests__/SaleCard-tests.tsx
Labels: Jira Synced

#4236 fix(fx-2517): set default sort to "gallery curated"
  src/__generated__/Show2ArtworksTestsQuery.graphql.ts
  src/__generated__/Show2Artworks_show.graphql.ts
  src/__generated__/Show2Query.graphql.ts
  src/__generated__/Show2TestsQuery.graphql.ts
  src/lib/Components/ArtworkFilterOptions/SortOptions.tsx
  src/lib/Components/ArtworkFilterOptions/__tests__/SortOptions-tests.tsx
  src/lib/Scenes/Sale/Components/SaleLotsList.tsx
  src/lib/Scenes/Show2/Components/Show2Artworks.tsx
  src/lib/utils/ArtworkFilter/ArtworkFiltersStore.tsx
  src/lib/utils/ArtworkFilter/FilterArtworksHelpers.ts
  src/lib/utils/ArtworkFilter/__tests__/ArtworkFiltersStore-tests.tsx
  src/lib/utils/ArtworkFilter/__tests__/FilterArtworksHelpers-tests.tsx
Labels: Jira Synced, Squash On Green

#4242 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4240 fix: multi image upload in my collection and fallback for processing photos
  CHANGELOG.yml
  src/lib/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionArtworkHeader.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/Components/__tests__/MyCollectionArtworkHeader-tests.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkFormModal/MyCollectionArtworkFormModal.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkFormModal/__tests__/MyCollectionArtworkFormModal-tests.tsx
Labels: Jira Synced

#4246 fix: Copy Changes for Inbox/MyBids
  src/lib/Scenes/Home/Components/SalesRail.tsx
  src/lib/Scenes/MyBids/Components/NoBids.tsx
  src/lib/Scenes/MyBids/Components/SaleInfo.tsx
  src/lib/Scenes/MyBids/MyBids.tsx
  src/lib/Scenes/MyBids/__tests__/SaleInfo-tests.tsx
Labels: Jira Synced

#4249 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4250 fix: switch to preferred lot and sellingPrice fields
  src/__generated__/ActiveLot_lotStanding.graphql.ts
  src/__generated__/ClosedLot_lotStanding.graphql.ts
  src/__generated__/InboxQuery.graphql.ts
  src/__generated__/InboxRefetchQuery.graphql.ts
  src/__generated__/InboxTestsQuery.graphql.ts
  src/__generated__/MyBidsPaginatedQuery.graphql.ts
  src/__generated__/MyBidsQuery.graphql.ts
  src/__generated__/MyBidsTestsQuery.graphql.ts
  src/__generated__/MyBids_me.graphql.ts
  src/lib/Scenes/MyBids/Components/ActiveLot.tsx
  src/lib/Scenes/MyBids/Components/ClosedLot.tsx
  src/lib/Scenes/MyBids/MyBids.tsx
  src/lib/Scenes/MyBids/__tests__/ActiveLot-tests.tsx
  src/lib/Scenes/MyBids/__tests__/ClosedLot-tests.tsx
  src/lib/Scenes/MyBids/__tests__/MyBids-tests.tsx
  src/lib/Scenes/MyBids/helpers/timely.ts
Labels: Jira Synced

#4243 feat: Add empty messages notice and cta for new inbox
  src/__generated__/ConversationsTestsQuery.graphql.ts
  src/lib/Scenes/Inbox/Components/Conversations/Conversations.tsx
  src/lib/Scenes/Inbox/Components/Conversations/NoMessages.tsx
  src/lib/Scenes/Inbox/Components/Conversations/__tests__/Conversations-tests.tsx
Labels: Jira Synced

#4245 fix: Visual QA fixes for new Inbox
  src/lib/Containers/Inbox/Inbox.tsx
  src/lib/Scenes/MyBids/Components/Lot.tsx
  src/lib/Scenes/MyBids/Components/SaleCard.tsx
  src/lib/Scenes/MyBids/MyBids.tsx
Labels: Jira Synced

#4251 fix: low quality my collection images
  CHANGELOG.yml
  emission/Pod/Classes/EigenCommunications/ARPHPhotoPickerModule.m
  src/__generated__/MyCollectionArtworkHeaderTestsQuery.graphql.ts
  src/__generated__/MyCollectionArtworkHeader_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkImagesQuery.graphql.ts
  src/__generated__/MyCollectionArtworkImages_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkQuery.graphql.ts
  src/lib/Scenes/Artwork/Components/ImageCarousel/ImageCarousel.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionArtworkHeader.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkFormModal/Screens/MyCollectionArtworkFormAddPhotos.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkImages/MyCollectionArtworkImages.tsx
  src/lib/Scenes/MyCollection/State/MyCollectionArtworkModel.tsx
Labels: Jira Synced, Squash On Green

#4241 feat: phone number input
  CHANGELOG.yml
  Podfile.lock
  __mocks__/svgMock.js
  package.json
  src/lib/Components/FancyModal/FancyModal.tsx
  src/lib/Components/Input/Input.tsx
  src/lib/Components/PhoneInput/PhoneInput.tsx
  src/lib/Components/PhoneInput/__tests__/PhoneInput-tests.tsx
  src/lib/Components/PhoneInput/__tests__/cleanUserPhoneNumber-tests.ts
  src/lib/Components/PhoneInput/__tests__/formatPhoneNumber-tests.ts
  src/lib/Components/PhoneInput/__tests__/getCountryIso2FromPhoneNumber-tests.ts
  src/lib/Components/PhoneInput/cleanUserPhoneNumber.ts
  src/lib/Components/PhoneInput/countries.ts
  src/lib/Components/PhoneInput/formatPhoneNumber.ts
  src/lib/Components/PhoneInput/getCountryIso2FromPhoneNumber.ts
  src/lib/Components/Select.tsx
  src/lib/Icons/TriangleDown.tsx
  src/lib/Scenes/MyAccount/Components/MyAccountFieldEditScreen.tsx
  src/lib/Scenes/MyAccount/MyAccountEditPhone.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkDemandIndex.tsx
  src/lib/tests/extractText.ts
  src/setupJest.ts
  typings/react-native-country-flags.d.ts
  yarn.lock
Labels: Jira Synced, Squash On Green

#4252 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4263 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4256 fix(my collection): allow deleting photos in my collection
  CHANGELOG.yml
  src/__generated__/MyCollectionArtworkFullDetailsQuery.graphql.ts
  src/__generated__/MyCollectionArtworkFullDetails_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkHeaderTestsQuery.graphql.ts
  src/__generated__/MyCollectionArtworkHeader_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkImagesQuery.graphql.ts
  src/__generated__/MyCollectionArtworkImages_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkListItemTestsQuery.graphql.ts
  src/__generated__/MyCollectionArtworkQuery.graphql.ts
  src/__generated__/MyCollectionArtwork_sharedProps.graphql.ts
  src/__generated__/deleteArtworkImageMutation.graphql.ts
  src/__generated__/myCollectionAddArtworkMutation.graphql.ts
  src/__generated__/myCollectionEditArtworkMutation.graphql.ts
  src/lib/Scenes/Consignments/Submission/geminiUploadToS3.ts
  src/lib/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionArtworkHeader.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkFormModal/MyCollectionArtworkFormModal.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkImages/MyCollectionArtworkImages.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkList/__tests__/MyCollectionArtworkListItem-tests.tsx
  src/lib/Scenes/MyCollection/State/MyCollectionArtworkModel.tsx
  src/lib/Scenes/MyCollection/mutations/deleteArtworkImage.ts
  src/lib/Scenes/MyCollection/utils/__tests__/deletedPhotoIDs-tests.ts
  src/lib/Scenes/MyCollection/utils/deletedPhotoIDs.ts
Labels: Squash On Green

#4272 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4259 feat: My Collection analytics tracking
  CHANGELOG.yml
  docs/analytics_and_tracking.md
  docs/preferred_practices.md
  package.json
  src/__generated__/MyCollectionArtworkArtistAuctionResultsTestsQuery.graphql.ts
  src/__generated__/MyCollectionArtworkArtistAuctionResults_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkArtistMarketTestsQuery.graphql.ts
  src/__generated__/MyCollectionArtworkArtistMarket_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkDemandIndexTestsQuery.graphql.ts
  src/__generated__/MyCollectionArtworkDemandIndex_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkFullDetailsTestsQuery.graphql.ts
  src/__generated__/MyCollectionArtworkFullDetails_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkHeaderTestsQuery.graphql.ts
  src/__generated__/MyCollectionArtworkHeader_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkInsightsTestsQuery.graphql.ts
  src/__generated__/MyCollectionArtworkInsights_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkListItem_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkPriceEstimateTestsQuery.graphql.ts
  src/__generated__/MyCollectionArtworkPriceEstimate_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkQuery.graphql.ts
  src/__generated__/MyCollectionPaginationQuery.graphql.ts
  src/__generated__/MyCollectionQuery.graphql.ts
  src/__generated__/MyCollectionTestsQuery.graphql.ts
  src/lib/Scenes/BottomTabs/bottomTabsConfig.tsx
  src/lib/Scenes/MyCollection/MyCollection.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/InfoButton.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkArtistAuctionResults.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkArtistMarket.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkDemandIndex.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkInsights.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkPriceEstimate.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/__tests__/InfoButton-tests.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/__tests__/MyCollectionArtworkArtistAuctionResults-tests.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/__tests__/MyCollectionArtworkArtistMarket-tests.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/__tests__/MyCollectionArtworkDemandIndex-tests.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/__tests__/MyCollectionArtworkPriceEstimate-tests.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionArtworkHeader.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/Components/__tests__/MyCollectionArtworkHeader-tests.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/__tests__/MyCollectionArtwork-tests.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkFormModal/MyCollectionArtworkFormModal.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkFullDetails/MyCollectionArtworkFullDetails.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkFullDetails/__tests__/MyCollectionArtworkFullDetails-tests.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkList/MyCollectionArtworkListItem.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkList/__tests__/MyCollectionArtworkListItem-tests.tsx
  src/lib/Scenes/MyCollection/__tests__/MyCollection-tests.tsx
  yarn.lock
Labels: Jira Synced

#4273 chore: Preparing for development, version 6.7.5
  Artsy Stickers/Info.plist
  Artsy/App_Resources/Artsy-Info.plist
  CHANGELOG.yml
Labels: Squash On Green

#4275 fix(my collection): centre empty state msg #trivial
  src/lib/Scenes/MyCollection/MyCollection.tsx
Labels: Jira Synced, Squash On Green

#4278 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4264 enhancement : add analytics tracking to My Bids
  CHANGELOG.yml
  src/__generated__/ActiveLot_lotStanding.graphql.ts
  src/__generated__/ClosedLot_lotStanding.graphql.ts
  src/__generated__/ConversationsQuery.graphql.ts
  src/__generated__/ConversationsTestsQuery.graphql.ts
  src/__generated__/Conversations_me.graphql.ts
  src/__generated__/InboxOldQuery.graphql.ts
  src/__generated__/InboxOldRefetchQuery.graphql.ts
  src/__generated__/InboxQuery.graphql.ts
  src/__generated__/InboxRefetchQuery.graphql.ts
  src/__generated__/InboxTestsQuery.graphql.ts
  src/__generated__/Lot_saleArtwork.graphql.ts
  src/__generated__/MyBidsPaginatedQuery.graphql.ts
  src/__generated__/MyBidsQuery.graphql.ts
  src/__generated__/MyBidsTestsQuery.graphql.ts
  src/__generated__/SaleAboveTheFoldQuery.graphql.ts
  src/__generated__/SaleActiveBidItemTestsQuery.graphql.ts
  src/__generated__/SaleActiveBidsRefetchQuery.graphql.ts
  src/__generated__/SaleActiveBidsTestsQuery.graphql.ts
  src/__generated__/SaleCardTestsQuery.graphql.ts
  src/__generated__/SaleCard_sale.graphql.ts
  src/__generated__/SaleRefetchQuery.graphql.ts
  src/lib/Containers/Inbox/Inbox.tsx
  src/lib/Scenes/Inbox/Components/Conversations/Conversations.tsx
  src/lib/Scenes/Inbox/Components/Conversations/NoMessages.tsx
  src/lib/Scenes/MyBids/Components/ActiveLot.tsx
  src/lib/Scenes/MyBids/Components/ClosedLot.tsx
  src/lib/Scenes/MyBids/Components/CompleteRegistrationCTAWrapper.tsx
  src/lib/Scenes/MyBids/Components/Lot.tsx
  src/lib/Scenes/MyBids/Components/NoBids.tsx
  src/lib/Scenes/MyBids/Components/SaleCard.tsx
  src/lib/Scenes/MyBids/MyBids.tsx
  src/lib/Scenes/MyBids/__tests__/SaleCard-tests.tsx
  src/lib/Scenes/MyBids/helpers/timely.ts
  src/lib/utils/track/index.tsx
  src/lib/utils/track/schema.ts
Labels: Jira Synced

#4271 fix(my collection): additional details edit screen layout
  CHANGELOG.yml
  src/lib/Scenes/MyCollection/Screens/ArtworkFormModal/Screens/MyCollectionArtworkFormAdditionalDetails.tsx
Labels: Squash On Green

#4279 bug: Increase height of DemandRankScale box to match purple linear gradient
  src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkDemandIndex.tsx
Labels: Jira Synced

#4270 bug: Center artist name and metadata on artwork page About the artist section
  src/palette/elements/EntityHeader/EntityHeader.tsx
Labels: Jira Synced

#4277 chore: Add artist name to auctions and articles section in my collection artwork view
  src/__generated__/MyCollectionArtworkArtistArticlesTestsQuery.graphql.ts
  src/__generated__/MyCollectionArtworkArtistArticles_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkArtistAuctionResultsTestsQuery.graphql.ts
  src/__generated__/MyCollectionArtworkArtistAuctionResults_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkInsightsTestsQuery.graphql.ts
  src/__generated__/MyCollectionArtworkQuery.graphql.ts
  src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkArtistArticles.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkArtistAuctionResults.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/__tests__/MyCollectionArtworkArtistArticles-tests.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/__tests__/MyCollectionArtworkArtistAuctionResults-tests.tsx
Labels: Jira Synced

#4282 fix(my collection): remove double separator in artwork details
  CHANGELOG.yml
  src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkArtistArticles.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkArtistAuctionResults.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkInsights.tsx
Labels: Jira Synced, Squash On Green

#4286 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4287 chore: Add missing artwork placeholder in My Collection Artwork page for empty state
  src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkArtistAuctionResults.tsx
Labels: Jira Synced

#4289 Update metaphysics schema
  data/schema.graphql
  src/__generated__/ConfirmBidUpdateUserMutation.graphql.ts
  src/__generated__/RegistrationUpdateUserMutation.graphql.ts
  src/__generated__/updateMyUserProfileMutation.graphql.ts
Labels: Merge On Green

#4293 chore: adds first inquiry analytics to messaging events
  src/__generated__/ArtworkAboveTheFoldQuery.graphql.ts
  src/__generated__/ArtworkRefetchQuery.graphql.ts
  src/__generated__/CommercialButtonsTestsMutationQuery.graphql.ts
  src/__generated__/CommercialButtonsTestsRenderQuery.graphql.ts
  src/__generated__/InquiryButtonsTestsQuery.graphql.ts
  src/__generated__/InquiryButtons_artwork.graphql.ts
  src/__generated__/InquiryModalTestsQuery.graphql.ts
  src/__generated__/InquiryModal_artwork.graphql.ts
  src/lib/Scenes/Artwork/Components/CommercialButtons/InquiryButtons.tsx
  src/lib/Scenes/Artwork/Components/CommercialButtons/InquiryModal.tsx
  src/lib/Scenes/Artwork/Components/Mutation/SubmitInquiryRequest.ts
Labels: Jira Synced

#4229 upgrade(deps): mapbox
  Artsy.xcodeproj/project.pbxproj
  CHANGELOG.yml
  Gemfile
  Gemfile.lock
  HACKS.md
  Podfile
  Podfile.lock
  emission/Emission.podspec
  emission/Pod/Classes/Core/AREmission.m
  emission/Pod/Classes/ViewControllers/ARMapContainerViewController.m
  package.json
  src/lib/Components/LocationMap/index.tsx
  src/lib/Scenes/City/CityPicker.tsx
  src/lib/Scenes/Map/Components/PinsShapeLayer.tsx
  src/lib/Scenes/Map/GlobalMap.tsx
  src/lib/Scenes/Map/__tests__/GlobalMap-tests.tsx
  src/lib/Scenes/Map/types.ts
  src/lib/Scenes/Partner/Components/PartnerMap.tsx
  src/setupJest.ts
  yarn.lock
Labels: Jira Synced

#4290 fix(deps): useEffect bug
  src/lib/AppRegistry.tsx
  src/lib/utils/useAppState.tsx
  tslint.json
Labels: Jira Synced

#4281 logic(bought-in): change the logic for the string in auction insights results
  CHANGELOG.yml
  src/lib/Components/Artist/ArtistInsights/ArtistInsightsAuctionResult.tsx
Labels: Jira Synced

#4291 chore: my collection analytics part 2
  CHANGELOG.yml
  docs/analytics_and_tracking.md
  docs/preferred_practices.md
  src/__generated__/MyCollectionArtworkArtistArticlesTestsQuery.graphql.ts
  src/__generated__/MyCollectionArtworkArtistArticles_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkFullDetailsQuery.graphql.ts
  src/__generated__/MyCollectionArtworkFullDetailsTestsQuery.graphql.ts
  src/__generated__/MyCollectionArtworkInsightsTestsQuery.graphql.ts
  src/__generated__/MyCollectionArtworkMetaTestsQuery.graphql.ts
  src/__generated__/MyCollectionArtworkMeta_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkQuery.graphql.ts
  src/lib/Scenes/MyCollection/MyCollection.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkArtistArticles.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkArtistAuctionResults.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/__tests__/MyCollectionArtworkArtistArticles-tests.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/__tests__/MyCollectionArtworkArtistAuctionResults-tests.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionArtworkMeta.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/Components/__tests__/MyCollectionArtworkMeta-tests.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/__tests__/MyCollectionArtwork-tests.tsx
  yarn.lock
Labels: Jira Synced

#4283 fix: workaround for iOS 14 password alert issue
  CHANGELOG.yml
  HACKS.md
  src/lib/Scenes/MyAccount/Components/MyAccountFieldEditScreen.tsx
  src/lib/Scenes/MyAccount/MyAccountEditPassword.tsx
Labels: Jira Synced
