Repository artsy/eigen, pull requests merged in 2020-04, with the labels that each got.

#3135 Prepares for 6.4.1 development #trivial
  Artsy Stickers/Info.plist
  Artsy/App_Resources/Artsy-Info.plist
  CHANGELOG.yml
Labels: Merge On Green

#3136 Sync MP schema
  data/schema.graphql
Labels: Merge On Green

#3132 [AUCT-941] - Identity verification text
  Artsy/Models/API_Models/Auctions/Sale.h
  Artsy/Models/API_Models/Auctions/Sale.m
  Artsy/Models/API_Models/Social/User.h
  Artsy/Models/API_Models/Social/User.m
  Artsy/View_Controllers/Auction/AuctionViewController.swift
  Artsy/View_Controllers/Live_Auctions/LiveAuctionLotSetViewController.swift
  Artsy/Views/Auction/AuctionTitleView.swift
  Artsy/Views/Auction/SaleViewModel.swift
  Artsy_Tests/ReferenceImages/AuctionTitleViewTests/with_the_registration_button_having_side_insets__title_view__looks_good_with_a_sale_and_user_requiring_identity_verification@3x.png
  Artsy_Tests/ReferenceImages/AuctionTitleViewTests/with_the_registration_button_having_side_insets__title_view__looks_good_with_a_sale_and_user_who_has_already_been_identity_verified@3x.png
  Artsy_Tests/ReferenceImages/AuctionTitleViewTests/with_the_registration_button_having_side_insets__title_view__looks_good_with_a_user_requiring_identity_verification@3x.png
  Artsy_Tests/ReferenceImages/AuctionTitleViewTests/with_the_registration_button_spanning_the_full_width__title_view__looks_good_with_a_sale_and_user_requiring_identity_verification@3x.png
  Artsy_Tests/ReferenceImages/AuctionTitleViewTests/with_the_registration_button_spanning_the_full_width__title_view__looks_good_with_a_sale_and_user_who_has_already_been_identity_verified@3x.png
  Artsy_Tests/ReferenceImages/AuctionTitleViewTests/with_the_registration_button_spanning_the_full_width__title_view__looks_good_with_a_user_requiring_identity_verification@3x.png
  Artsy_Tests/View_Controller_Tests/Auction/AuctionInformationViewControllerTests.swift
  Artsy_Tests/View_Controller_Tests/Auction/AuctionViewControllerTests.swift
  Artsy_Tests/View_Tests/Auctions/AuctionTitleViewTests.swift
  CHANGELOG.yml
Labels: Merge On Green

#3133 [Consignments] Add ArtistConsignButton to Artist page
  CHANGELOG.yml
  src/__generated__/ArtistAbout_artist.graphql.ts
  src/__generated__/ArtistBelowTheFoldQuery.graphql.ts
  src/__generated__/ArtistConsignButtonTestsQuery.graphql.ts
  src/__generated__/ArtistConsignButton_artist.graphql.ts
  src/lib/Components/Artist/ArtistAbout.tsx
  src/lib/Components/Artist/ArtistConsignButton.tsx
  src/lib/Components/Artist/__tests__/About-tests.tsx
  src/lib/Components/Artist/__tests__/ArtistConsignButton-tests.tsx
  src/lib/Components/Artist/__tests__/__snapshots__/About-tests.tsx.snap
  src/lib/Components/Artist/__tests__/__snapshots__/ArtistConsignButton-tests.tsx.snap
  src/lib/utils/track/schema.ts
Labels: Consignments

#3139 Attempt to fix an issue where whatsNew in AppStore can not be updated
  CHANGELOG.yml
Labels: Merge On Green

#3138 Non-IDV new bidder registering through typical registration form sees information about identity verification
  CHANGELOG.yml
  src/__generated__/RegistrationFlowQuery.graphql.ts
  src/__generated__/Registration_me.graphql.ts
  src/__generated__/Registration_sale.graphql.ts
  src/lib/Components/Bidding/Screens/Registration.tsx
  src/lib/Components/Bidding/Screens/__tests__/Registration-tests.tsx
  src/lib/Components/Bidding/Screens/__tests__/__snapshots__/Registration-tests.tsx.snap
  src/lib/Containers/__tests__/__snapshots__/RegistrationFlow-tests.tsx.snap
Labels: Merge On Green

#3151 [Bugfix/Consignments] Ensure inner button triggers action
  src/lib/Components/Artist/ArtistConsignButton.tsx
  src/lib/Components/Artist/__tests__/ArtistConsignButton-tests.tsx
  src/lib/Components/Artist/__tests__/__snapshots__/ArtistConsignButton-tests.tsx.snap
Labels: Consignments

#3155 Add documentation for updating screenshots
  CHANGELOG.yml
  docs/getting_started.md
Labels: Merge On Green

#3156 Adds tracking to collections artworks filters
  CHANGELOG.yml
  src/lib/Components/FilterModal.tsx
  src/lib/Components/__tests__/FilterModal-tests.tsx
  src/lib/Scenes/Collection/Collection.tsx
  src/lib/Scenes/Collection/Components/__fixtures__/CollectionFixture.ts
  src/lib/Scenes/Collection/Helpers/FilterArtworksHelpers.ts
  src/lib/Scenes/Collection/Screens/CollectionArtworks.tsx
  src/lib/Scenes/Collection/Screens/CollectionZeroState.tsx
  src/lib/Scenes/Collection/Screens/__tests__/CollectionArtworks-tests.tsx
Labels: Merge On Green

#3110 [MX-214] - Sign in with apple
  Artsy.xcodeproj/project.pbxproj
  Artsy/App/ARAnalyticsConstants.h
  Artsy/App/ARAnalyticsConstants.m
  Artsy/App/ARAppDelegate+Analytics.m
  Artsy/App_Resources/Artsy.Store.entitlements
  Artsy/App_Resources/Artsy.entitlements
  Artsy/Models/Feed_Items/ARFollowArtistFeedItem.m
  Artsy/Networking/API_Modules/ARUserManager.h
  Artsy/Networking/API_Modules/ARUserManager.m
  Artsy/Networking/ARAuthProviders.h
  Artsy/Networking/ARAuthProviders.m
  Artsy/Networking/ARRouter.h
  Artsy/Networking/ARRouter.m
  Artsy/Resources/onboarding/apple-login@2x.png
  Artsy/Resources/onboarding/apple-login@3x.png
  Artsy/Resources/onboarding/facebook-login@2x.png
  Artsy/Resources/onboarding/facebook-login@3x.png
  Artsy/View_Controllers/Login_and_Onboarding/AROnboardingViewController.h
  Artsy/View_Controllers/Login_and_Onboarding/AROnboardingViewController.m
  Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/3_-_Sign_Up_+_Log_In/ARLoginButtonsView.h
  Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/3_-_Sign_Up_+_Log_In/ARLoginButtonsView.m
  Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/5-_Onboarding_Personalization/ARPersonalizeViewController.m
  Artsy/View_Controllers/Util/ARNavigationController.m
  Artsy_Tests/Networking_Tests/API_Modules/ARUserManagerTests.m
  Artsy_Tests/Stubs/ARUserManager+Stubs.h
  Artsy_Tests/Stubs/ARUserManager+Stubs.m
Labels: Merge On Green

#3165 Always compile query map
  .circleci/config.yml
Labels: Merge On Green

#3168 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3169 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3170 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3171 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3172 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3173 [ArtistConsignButton] Visual QA
  src/lib/Components/Artist/ArtistConsignButton.tsx
Labels: Merge On Green

#3180 Allow 7 character TLDs instead of 5
  Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/5-_Onboarding_Personalization/ARPersonalizeViewController.m
Labels: Merge On Green

#3183 [MX-283] - Home design tweaks
  src/lib/Components/SectionTitle.tsx
  src/lib/Scenes/Home/Home.tsx
Labels: Merge On Green

#3182 Defers Sign In with Apple until next release
  Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/5-_Onboarding_Personalization/ARPersonalizeViewController.m
  CHANGELOG.yml
Labels: Merge On Green

#3184 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3186 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3190 Updates beta docs
  docs/deploy_to_beta.md
Labels: Merge On Green

#3191 Preparing for development version 6.4.2 #trivial
  Artsy Stickers/Info.plist
  Artsy/App_Resources/Artsy-Info.plist
  CHANGELOG.yml
Labels: Merge On Green

#3192 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3197 Allow manually approved users to bid even when they are not verified
  CHANGELOG.yml
  src/lib/Components/Bidding/Screens/Registration.tsx
  src/lib/Components/Bidding/Screens/__tests__/Registration-tests.tsx
  src/lib/Scenes/Artwork/Components/CommercialButtons/BidButton.tsx
  src/lib/Scenes/Artwork/Components/CommercialButtons/__tests__/BidButton-tests.tsx
  src/lib/utils/auction/bidderNeedsIdentityVerification.ts
  src/lib/utils/auction/index.tsx
Labels: Merge On Green

#3199 Add null check before attempting to store in keychain #trivial
  Artsy/View_Controllers/Login_and_Onboarding/AROnboardingViewController.m
Labels: Merge On Green

#3202 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3201 [MX-138] - Update empty state for auctions
  CHANGELOG.yml
  package.json
  src/lib/Scenes/Sales/Components/ZeroState/__tests__/index-tests.tsx
  src/lib/Scenes/Sales/Components/ZeroState/index.html
  src/lib/Scenes/Sales/Components/ZeroState/index.tsx
  src/lib/Scenes/Sales/__tests__/index-tests.tsx
  yarn.lock
Labels: Merge On Green

#3203 Updates City Guide BMW Logo
  CHANGELOG.yml
  images/BMW-logo.jpg
  images/BMW_Grey-Colour_RGB.png
  src/lib/Scenes/City/CityBMWSponsorship.tsx
  src/lib/Scenes/City/CityPicker.tsx
  src/lib/Scenes/City/Components/SavedEventSection/index.tsx
  src/lib/Scenes/Fair/Screens/FairBMWArtActivation.tsx
Labels: Merge On Green

#3207 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3208 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3117 Viewing room v0.0 [GALL-2685]
  Artsy/App/ARSwitchBoard.m
  CHANGELOG.yml
  emission/Pod/Classes/ViewControllers/ARViewingRoomArtworksComponentViewController.h
  emission/Pod/Classes/ViewControllers/ARViewingRoomArtworksComponentViewController.m
  src/__generated__/ViewingRoomArtworkRail_viewingRoomArtworks.graphql.ts
  src/__generated__/ViewingRoomArtworksQuery.graphql.ts
  src/__generated__/ViewingRoomArtworksRendererQuery.graphql.ts
  src/__generated__/ViewingRoomArtworks_viewingRoom.graphql.ts
  src/__generated__/ViewingRoomQuery.graphql.ts
  src/__generated__/ViewingRoomStatement_viewingRoom.graphql.ts
  src/__generated__/ViewingRoomSubsections_viewingRoomSubsections.graphql.ts
  src/__generated__/ViewingRoom_viewingRoom.graphql.ts
  src/lib/AppRegistry.tsx
  src/lib/Scenes/ViewingRoom/Components/ViewingRoomArtworkRail.tsx
  src/lib/Scenes/ViewingRoom/Components/ViewingRoomHeader.tsx
  src/lib/Scenes/ViewingRoom/Components/ViewingRoomStatement.tsx
  src/lib/Scenes/ViewingRoom/Components/ViewingRoomSubsections.tsx
  src/lib/Scenes/ViewingRoom/Components/__tests__/ViewingRoomArtworkRail-tests.tsx
  src/lib/Scenes/ViewingRoom/Components/__tests__/ViewingRoomHeader-tests.tsx
  src/lib/Scenes/ViewingRoom/Components/__tests__/ViewingRoomStatement-tests.tsx
  src/lib/Scenes/ViewingRoom/Components/__tests__/ViewingRoomSubsections-tests.tsx
  src/lib/Scenes/ViewingRoom/ViewingRoom.tsx
  src/lib/Scenes/ViewingRoom/ViewingRoomArtworks.tsx
  src/lib/Scenes/ViewingRoom/__tests__/ViewingRoomArtworks-tests.tsx
  src/lib/Scenes/ViewingRoom/index.tsx
Labels: Merge On Green

#3223 Preparing for development version 6.4.3 #trivial
  Artsy Stickers/Info.plist
  Artsy/App_Resources/Artsy-Info.plist
  CHANGELOG.yml
Labels: Merge On Green

#3222 [MX-263] Removes individual artist artwork rails from home
  CHANGELOG.yml
  src/__generated__/HomeQuery.graphql.ts
  src/__generated__/HomeRefetchQuery.graphql.ts
  src/__generated__/Home_homePage.graphql.ts
  src/lib/Scenes/Home/Home.tsx
Labels: Merge On Green

#3231 [MX-299] [MX-7] New Back button, visual cleanup
  Artsy.xcodeproj/project.pbxproj
  Artsy/Resources/Assets/ActionButton@2x.png
  Artsy/Resources/Assets/Artwork_Icon_Share.png
  Artsy/Resources/Assets/Artwork_Icon_Share@2x.png
  Artsy/Resources/Assets/Artwork_Icon_VIR.png
  Artsy/Resources/Assets/Artwork_Icon_VIR@2x.png
  Artsy/Resources/Assets/BackArrow@2x.png
  Artsy/Resources/Assets/BackArrowBlack@2x.png
  Artsy/Resources/Assets/BackChevron.png
  Artsy/Resources/Assets/BackChevron@2x.png
  Artsy/Resources/Assets/BackChevron@3x.png
  Artsy/Resources/Assets/Heart_Black@2x.png
  Artsy/Resources/Assets/Heart_Shortcut.png
  Artsy/Resources/Assets/Heart_White@2x.png
  Artsy/Resources/Assets/HomeButton@2x.png
  Artsy/Resources/Assets/Image_Shadow_Overlay@2x.png
  Artsy/Resources/Assets/MapButtonAction@2x.png
  Artsy/Resources/Assets/MapIcon@2x.png
  Artsy/Resources/Assets/MenuButtonBG@2x.png
  Artsy/Resources/Assets/MenuClose@2x.png
  Artsy/Resources/Assets/MenuHamburger@2x.png
  Artsy/Resources/Assets/NotificationsButton@2x.png
  Artsy/Resources/Assets/Parallax_Overlay_Bottom@2x.png
  Artsy/Resources/Assets/Parallax_Overlay_Top@2x.png
  Artsy/Resources/Assets/Range@2x.png
  Artsy/Resources/Assets/SearchButtonWhite@2x.png
  Artsy/Resources/Assets/SearchIcon_HeavyGrey@2x.png
  Artsy/Resources/Assets/SearchIcon_LightGrey@2x.png
  Artsy/Resources/Assets/SearchIcon_MediumGrey@2x.png
  Artsy/Resources/Assets/SearchIcon_White@2x.png
  Artsy/Resources/Assets/SearchThumb_HeavyGrey@2x.png
  Artsy/Resources/Assets/SearchThumb_LightGrey@2x.png
  Artsy/Resources/Assets/SettingsButton@2x.png
  Artsy/Resources/Assets/SidebarButtonBG@2x.png
  Artsy/Resources/Assets/SidebarButtonHighlightBG@2x.png
  Artsy/Resources/Assets/TextfieldClearButton.png
  Artsy/Resources/Assets/Thumb.png
  Artsy/Resources/Assets/Thumb@2x.png
  Artsy/Resources/Assets/Track@2x.png
  Artsy/View_Controllers/ARMutableLinkViewController.m
  Artsy/View_Controllers/Admin/ARAdminSettingsViewController.m
  Artsy/View_Controllers/Admin/AREchoContentsViewController.m
  Artsy/View_Controllers/Auction/AuctionViewController.swift
  Artsy/View_Controllers/Auction_Results/ARAuctionWebViewController.m
  Artsy/View_Controllers/Fair/ARProfileViewController.m
  Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/Views/AROnboardingNavBarView.h
  Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/Views/AROnboardingNavBarView.m
  Artsy/View_Controllers/Util/ARBackButton.h
  Artsy/View_Controllers/Util/ARBackButton.m
  Artsy/View_Controllers/Util/ARNavigationController.m
  Artsy_Tests/ReferenceImages/ARNavigationControllerSpec/visuals_should_be_show_a_back_button_with_2_view_controllers@3x.png
  Artsy_Tests/ReferenceImages/RefinementOptionsViewControllerTests/enables_apply_reset_buttons_when_options_are_changed@3x.png
  Artsy_Tests/ReferenceImages/RefinementOptionsViewControllerTests/looks_good_by_default@3x.png
  Artsy_Tests/ReferenceImages/RefinementOptionsViewControllerTests/looks_good_when_configured_with_options_and_changed_options@3x.png
  Artsy_Tests/ReferenceImages/RefinementOptionsViewControllerTests/looks_good_when_reset@3x.png
  Artsy_Tests/ReferenceImages/RefinementOptionsViewControllerTests/looks_good_with_gene_refine_settings_showing_price@3x.png
  CHANGELOG.yml
Labels: Jira Synced, Merge On Green

#3230 [Minor Bug Fix] Filter button not appearing on Collection Artworks
  src/lib/Scenes/Collection/Collection.tsx
Labels: Merge On Green

#3237 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3238 Removes comments from Dangerfile #trivial
  dangerfile.ts
Labels: Merge On Green

#3226 Add Artist Series/Iconic Collections Rail to the Artist Page in iOS
  CHANGELOG.yml
  src/__generated__/ArtistAboveTheFoldQuery.graphql.ts
  src/__generated__/ArtistArtworksQuery.graphql.ts
  src/__generated__/ArtistArtworks_artist.graphql.ts
  src/__generated__/ArtistCollectionsRail_collections.graphql.ts
  src/__generated__/CollectionArtistSeriesRailTestsQuery.graphql.ts
  src/__generated__/CollectionArtistSeriesRail_collectionGroup.graphql.ts
  src/__generated__/CollectionHubsRails_linkedCollections.graphql.ts
  src/__generated__/CollectionQuery.graphql.ts
  src/__generated__/CollectionTestsQuery.graphql.ts
  src/lib/Components/Artist/ArtistArtworks/ArtistCollectionsRail.tsx
  src/lib/Components/Artist/ArtistArtworks/__tests__/ArtistCollectionsRail-tests.tsx
  src/lib/Components/Artist/ArtistArtworks/index.tsx
  src/lib/Components/GenericArtistSeriesRail.tsx
  src/lib/Scenes/Collection/Components/CollectionHubsRails/ArtistSeries/ArtistSeriesRail.tsx
  src/lib/Scenes/Collection/Components/CollectionHubsRails/ArtistSeries/CollectionArtistSeriesRail.tsx
  src/lib/Scenes/Collection/Components/CollectionHubsRails/ArtistSeries/__tests__/CollectionArtistSeriesRail-tests.tsx
  src/lib/Scenes/Collection/Components/CollectionHubsRails/index.tsx
Labels: Merge On Green

#3239 move github actions to correct place
  .github/workflows/beta.yml
  .github/workflows/promote.yml
Labels: Merge On Green

#3243 Visual QA Launch Blocker Fixes for v2 Collections Filters
  src/lib/Components/ArtworkFilterOptions/SingleSelectOption.tsx
  src/lib/Components/FilterModal.tsx
  src/lib/Components/__tests__/FilterModal-tests.tsx
  src/lib/Scenes/Collection/Collection.tsx
  src/lib/Scenes/Collection/Screens/CollectionArtworks.tsx
Labels: Merge On Green

#3244 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3246 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#3248 Prepares for 6.4.4 release.
  Artsy Stickers/Info.plist
  Artsy/App_Resources/Artsy-Info.plist
  CHANGELOG.yml
Labels: Merge On Green

#3249 Confirm there are no artworks left to render before ending loadMore Relay call
  src/lib/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx
Labels: Merge On Green

#3252 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green
