Repository artsy/eigen, pull requests merged in 2021-05, with the labels that each got.

#4701 fix(xcode): update things to make it compatible and buildable with xcode 12.5
  Artsy.xcodeproj/project.pbxproj
  Gemfile.lock
  Podfile
  Podfile.lock
Labels: Jira Synced

#4700 refactor: move rails on artist artwork tab to overview (about) tab
  CHANGELOG.yml
  Podfile.lock
  src/__generated__/ArtistAboutTestsQuery.graphql.ts
  src/__generated__/ArtistAbout_artist.graphql.ts
  src/__generated__/ArtistAboveTheFoldQuery.graphql.ts
  src/__generated__/ArtistArtworksQuery.graphql.ts
  src/__generated__/ArtistArtworks_artist.graphql.ts
  src/__generated__/ArtistBelowTheFoldQuery.graphql.ts
  src/lib/Components/Artist/ArtistAbout/ArtistAbout.tsx
  src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
  src/lib/Components/Artist/ArtistArtworks/ArtistCollectionsRail.tsx
  src/lib/Components/Artist/ArtistArtworks/ArtistNotableWorksRail.tsx
  src/lib/Components/GenericArtistSeriesRail.tsx
  src/lib/Scenes/Artist/Artist.tsx
Labels: Jira Synced

#4699 chore(CX-1013): update copy on onboarding
  CHANGELOG.yml
  src/lib/Scenes/Onboarding/ForgotPassword.tsx
  src/lib/Scenes/Onboarding/OnboardingCreateAccount/OnboardingCreateAccountName.tsx
  src/lib/Scenes/Onboarding/OnboardingWelcome.tsx
Labels: Jira Synced

#4706 fix: Stop showing text on loading login button
  src/lib/Scenes/Onboarding/OnboardingCreateAccount/OnboardingCreateAccount.tsx
  src/lib/Scenes/Onboarding/OnboardingLogin.tsx
Labels: Jira Synced

#4709 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4710 fix: add spinner and padding to infinite scroll artworks grid
  CHANGELOG.yml
  src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
  src/lib/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx
  src/lib/Scenes/Fair/Components/FairArtworks.tsx
  src/lib/Scenes/Show/Components/ShowArtworks.tsx
Labels: Jira Synced

#4696 chore: remove old login from android
  CHANGELOG.yml
  src/lib/Scenes/Onboarding/OldLogIn/LogIn.tsx
  src/lib/Scenes/Onboarding/OldLogIn/LogInEmail.tsx
  src/lib/Scenes/Onboarding/OldLogIn/LogInEnterPassword.tsx
  src/lib/Scenes/Onboarding/OldLogIn/LogInStore.tsx
  src/lib/Scenes/Onboarding/Onboarding.tsx
  src/lib/Scenes/Onboarding/__tests__/Onboarding-tests.tsx
  src/lib/store/config/features.ts
Labels: Jira Synced

#4708 fix: make billing form country input text visible
  CHANGELOG.yml
  src/lib/Components/Bidding/Screens/BillingAddress.tsx
Labels: Jira Synced, Squash On Green

#4713 chore (CX-1219): animate welcome screen
  CHANGELOG.yml
  src/lib/Scenes/Onboarding/OnboardingWelcome.tsx
  typings/images.d.ts
Labels: Jira Synced

#4715 fix: make filter modal close and clear all tappable again
  src/lib/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx
Labels: Squash On Green

#4711 feat: support dark and light themes on android
  CHANGELOG.yml
  Podfile.lock
  android/app/src/main/java/net/artsy/app/ArtsyNativeModule.java
  src/lib/AndroidApp.tsx
  src/lib/NativeModules/ArtsyNativeModule.tsx
  src/lib/Scenes/Onboarding/OnboardingWelcome.tsx
  src/lib/Scenes/Onboarding/__tests__/OnboardingWelcome-tests.tsx
Labels: Jira Synced

#4716 fix: screen transition not fading when transitioning from sign up to login
  CHANGELOG.yml
  src/lib/Scenes/Onboarding/OnboardingCreateAccount/OnboardingCreateAccount.tsx
  src/lib/Scenes/Onboarding/OnboardingLogin.tsx
Labels: Jira Synced, Squash On Green

#4717 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4703 refactor: move artist artworks sort & filter button into header
  CHANGELOG.yml
  Podfile.lock
  src/__generated__/ArtistAboveTheFoldQuery.graphql.ts
  src/__generated__/ArtistArtworksQuery.graphql.ts
  src/__generated__/ArtistArtworks_artist.graphql.ts
  src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
Labels: Jira Synced, Squash On Green

#4712 [PURCHASE-2574]: Swipe down dismiss modal
  Artsy/App/ARModalViewController.m
  CHANGELOG.yml
  emission/Pod/Classes/EigenCommunications/ARNotificationsManager.h
  emission/Pod/Classes/EigenCommunications/ARNotificationsManager.m
  src/lib/Scenes/Inbox/Screens/Conversation.tsx
  src/lib/Scenes/Inbox/Screens/__tests__/Conversation-tests.tsx
  src/lib/navigation/navigate.ts
  src/lib/store/NativeModel.ts
Labels: Jira Synced

#4714 feat: Update home screen modules (change order and remove recently saved)
  CHANGELOG.yml
  src/__generated__/HomeQuery.graphql.ts
  src/__generated__/HomeRefetchQuery.graphql.ts
  src/__generated__/Home_homePage.graphql.ts
  src/lib/Scenes/Home/Components/HomeHero.tsx
  src/lib/Scenes/Home/Home.tsx
Labels: Jira Synced, Squash On Green

#4652 feat: live auctions android
  CHANGELOG.yml
  src/lib/Components/ArtsyReactWebView.tsx
  src/lib/Components/__tests__/ArtsyReactWebView-tests.tsx
  src/lib/navigation/routes.tsx
Labels: Jira Synced

#4720 chore: Add iOS and Android test item to checklist in PR template
  docs/pull_request_template.md
Labels: Jira Synced

#4704 fix(analytics): send JSON in filter change events
  CHANGELOG.yml
  src/lib/Components/ArtworkFilter/ArtworkFilter.tsx
  src/lib/Components/ArtworkFilter/__tests__/FilterModal-tests.tsx
Labels: Jira Synced, Squash On Green

#4723 feat: Route artist auction results route to artist insights
  CHANGELOG.yml
  src/lib/Components/StickyTabPage/StickyTabPage.tsx
  src/lib/Scenes/Artist/Artist.tsx
  src/lib/navigation/__tests__/routes-tests.tsx
  src/lib/navigation/routes.tsx
Labels: Jira Synced

#4724 feat: Support staging deep links on android
  CHANGELOG.yml
  android/app/src/main/AndroidManifest.xml
  src/lib/utils/useDeepLinks.ts
Labels: Jira Synced, Squash On Green

#4707 feat: add PR description parser for changelog generation
  jest.config.js
  scripts/changelog/changelog-types.d.ts
  scripts/changelog/generateChangelogSectionTemplate.js
  scripts/changelog/parsePRDescription-tests.ts
  scripts/changelog/parsePRDescription.js
  tsconfig.json
Labels: Jira Synced, Squash On Green

#4721 feature(analytics): adding analytics to android
  .env.example
  Artsy/App/ARAppDelegate+Analytics.m
  CHANGELOG.yml
  Podfile.lock
  package.json
  patches/@segment+analytics-react-native+1.4.4.patch
  src/lib/AndroidApp.tsx
  src/lib/AppProviders.tsx
  src/lib/AppRegistry.tsx
  src/lib/Components/Home/ArtistRails/ArtistRail.tsx
  src/lib/Containers/WorksForYou.tsx
  src/lib/NativeModules/Events.tsx
  src/lib/NativeModules/LegacyNativeModules.tsx
  src/lib/Scenes/Artist/__tests__/Artist-tests.tsx
  src/lib/Scenes/Artwork/Components/ArtworkExtraLinks/__tests__/index-tests.tsx
  src/lib/Scenes/Artwork/Components/__tests__/RequestConditionReport-analytics-tests.tsx
  src/lib/Scenes/Collection/Components/__tests__/FeaturedArtists-tests.tsx
  src/lib/Scenes/Consignments/Screens/__tests__/Overview-analytics-tests.tsx
  src/lib/Scenes/ViewingRoom/Components/__tests__/ViewingRoomArtworkRail-tests.tsx
  src/lib/store/AuthModel.ts
  src/lib/tests/mockTracking.ts
  src/lib/tests/renderWithWrappers.tsx
  src/lib/utils/track/SegmentTrackingProvider.android.ts
  src/lib/utils/track/SegmentTrackingProvider.ios.ts
  src/lib/utils/track/__tests__/tracking-tests.tsx
  src/lib/utils/track/constants.ts
  src/lib/utils/track/index.tsx
  src/lib/utils/track/providers.tsx
  src/lib/utils/track/schema.ts
  src/lib/utils/useDeepLinks.ts
  src/setupJest.ts
  tsconfig.json
  typings/react-native-config.d.ts
  yarn.lock
Labels: Jira Synced, Squash On Green

#4729 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4728 followup(analytics): review suggestions
  src/lib/AndroidApp.tsx
  src/lib/AppRegistry.tsx
  src/lib/utils/track/ConsoleTrackingProvider.ts
  src/lib/utils/track/SegmentTrackingProvider.ios.ts
  src/lib/utils/track/SegmentTrackingProvider.ts
  src/lib/utils/track/providers.tsx
  src/setupJest.ts
  tsconfig.json
Labels: Jira Synced

#4719 feat: Add "lots by artists I follow" to home screen
  CHANGELOG.yml
  src/__generated__/HomeQuery.graphql.ts
  src/__generated__/HomeRefetchQuery.graphql.ts
  src/__generated__/Home_me.graphql.ts
  src/__generated__/SaleArtworksHomeRailQuery.graphql.ts
  src/__generated__/SaleArtworksHomeRailTestsQuery.graphql.ts
  src/__generated__/SaleArtworksHomeRail_me.graphql.ts
  src/lib/Scenes/Home/Components/SaleArtworksHomeRail.tsx
  src/lib/Scenes/Home/Components/__tests__/SaleArtworksHomeRail-tests.tsx
  src/lib/Scenes/Home/Home.tsx
  src/lib/Scenes/Sale/Components/SaleArtworksRail.tsx
Labels: Jira Synced, Squash On Green

#4730 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4733 update(gem): update json
  Gemfile
  Gemfile.lock
  scripts/test-ios
Labels: Jira Synced, Squash On Green

#4698 fix: address cache issue for make offer button
  src/lib/Scenes/Inbox/Components/Conversations/OpenInquiryModalButton.tsx
Labels: Jira Synced

#4722 fix: fastlane promote and beta archive issues
  Artsy.xcodeproj/project.pbxproj
  CHANGELOG.yml
  Gemfile
  Gemfile.lock
  HACKS.md
  Podfile
  Podfile.lock
  fastlane/Fastfile
  package.json
  patches/@react-native-mapbox-gl+maps+8.2.0-beta2.patch
  yarn.lock
Labels: Jira Synced, Squash On Green

#4734 Add buyer guarantee message and link to inquiry make offer button
  CHANGELOG.yml
  src/lib/Scenes/Inbox/Components/Conversations/OpenInquiryModalButton.tsx
  src/lib/Scenes/Inbox/Components/Conversations/ReviewOfferButton.tsx
  src/lib/Scenes/Inbox/Components/Conversations/__tests__/OpenInquiryModalButton-tests.tsx
Labels: Jira Synced, Squash On Green

#4736 fix: revert base64 encode of key for beta ship
  fastlane/Fastfile
Labels: Squash On Green

#4737 feat: add env var to silence beta failures #trivial
  fastlane/Fastfile
Labels: Squash On Green

#4738 fix: don't show personalize on iOS
  src/lib/AppRegistry.tsx
Labels: Squash On Green

#4739 fix(CX-1436): User unable to search on iOS
  CHANGELOG.yml
  src/lib/Components/Spinner.tsx
Labels: Jira Synced, Squash On Green

#4742 fix(CX-1375) Artist Icon is not round
  src/palette/elements/Avatar/Avatar.tsx
Labels: Jira Synced

#4750 chore: handle dismiss modal for andriod
  src/lib/Scenes/Inbox/Screens/Conversation.tsx
  src/lib/Scenes/Inbox/Screens/__tests__/Conversation-tests.tsx
  src/lib/navigation/navigate.ts
Labels: Jira Synced

#4748 feat: Change home screen "lots for you" copy
  src/lib/Scenes/Home/Components/SaleArtworksHomeRail.tsx
  src/lib/Scenes/Home/Components/__tests__/SaleArtworksHomeRail-tests.tsx
Labels: Jira Synced

#4755 fix: remove separator on home sale artworks rail when no sale artwork…
  CHANGELOG.yml
  src/lib/Scenes/Home/Components/SaleArtworksHomeRail.tsx
  src/lib/Scenes/Home/Components/__tests__/SaleArtworksHomeRail-tests.tsx
  src/lib/Scenes/Home/Home.tsx
Labels: Jira Synced

#4752 feat: CTA and modal for collector confirming IC provisional offer
  CHANGELOG.yml
  src/__generated__/ComposerTestsQuery.graphql.ts
  src/__generated__/ConversationCTATestsQuery.graphql.ts
  src/__generated__/ConversationCTA_conversation.graphql.ts
  src/__generated__/ConversationQuery.graphql.ts
  src/__generated__/ConversationRefetchQuery.graphql.ts
  src/__generated__/ConversationTestsQuery.graphql.ts
  src/__generated__/MessagesQuery.graphql.ts
  src/__generated__/MessagesTestsQuery.graphql.ts
  src/__generated__/OrderUpdateTestsQuery.graphql.ts
  src/__generated__/OrderUpdate_event.graphql.ts
  src/lib/Scenes/Inbox/Components/Conversations/ConversationCTA.tsx
  src/lib/Scenes/Inbox/Components/Conversations/OrderUpdate.tsx
  src/lib/Scenes/Inbox/Components/Conversations/ReviewOfferButton.tsx
  src/lib/Scenes/Inbox/Components/Conversations/__tests__/Composer-tests.tsx
  src/lib/Scenes/Inbox/Components/Conversations/__tests__/ConversationCTA-tests.tsx
  src/lib/Scenes/Inbox/Components/Conversations/__tests__/Messages-tests.tsx
  src/lib/Scenes/Inbox/Components/Conversations/__tests__/OrderUpdate-tests.tsx
  src/lib/Scenes/Inbox/Components/Conversations/__tests__/ReviewOfferButton-tests.tsx
Labels: Jira Synced

#4756 fix(CX-841): iOS push notification permission shows up everytime
  Artsy/Constants/ARDefaults.m
  CHANGELOG.yml
  Podfile.lock
Labels: Jira Synced

#4762 chore: cut down welcome screen animation speed by half
  src/lib/Scenes/Onboarding/OnboardingWelcome.tsx
Labels: Jira Synced

#4740 Fix(cx 1371)/phone input misaligned
  CHANGELOG.yml
  src/lib/Components/Input/Input.tsx
  src/lib/Components/PhoneInput/PhoneInput.tsx
Labels: Jira Synced

#4764 fix(analytics): fix off by one error, the fresh install event was not firing.
  src/lib/AndroidApp.tsx
Labels: Jira Synced, Squash On Green

#4763 fix(CX-1379): “cancel” button doesn’t clear terms and results
  CHANGELOG.yml
  src/lib/Components/SearchInput.tsx
Labels: Jira Synced, Squash On Green

#4761 feat: lock screen orientation to portrait on android phones
  CHANGELOG.yml
  android/app/src/main/java/net/artsy/app/ArtsyNativeModule.java
  src/lib/AndroidApp.tsx
  src/lib/NativeModules/ArtsyNativeModule.tsx
Labels: Jira Synced

#4766 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4765 enhancement(country select): replace the old one with the new one
  src/lib/Components/Bidding/Screens/BillingAddress.tsx
  src/lib/Components/Bidding/Screens/SelectCountry.tsx
  src/lib/Components/Bidding/Screens/__tests__/BillingAddress-tests.tsx
  src/lib/Components/Bidding/Screens/__tests__/SelectCountry-tests.tsx
  src/lib/Components/CountrySelect.tsx
  src/lib/Components/Select.tsx
  src/palette/Theme.tsx
Labels: Jira Synced

#4767 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4768 chore(dev): some quick access info for artwork
  src/lib/Scenes/Artwork/Artwork.tsx
Labels: Jira Synced

#4773 fix(CX-1322): incorrect action name
  CHANGELOG.yml
  src/lib/Components/Artist/ArtistHeader.tsx
  src/lib/Scenes/Artwork/Components/FollowArtistButton.tsx
Labels: Jira Synced

#4775 fix: minor visual qa for make offer modal
  src/lib/Scenes/Artwork/Components/CommercialButtons/CollapsibleArtworkDetails.tsx
  src/lib/Scenes/Inbox/Components/Conversations/MakeOfferModal.tsx
Labels: Jira Synced

#4776 UI tweaks to coversation page for make offer button
  src/lib/Scenes/Inbox/Components/Conversations/OpenInquiryModalButton.tsx
  src/lib/Scenes/Inbox/Components/ShadowSeparator.tsx
  src/lib/Scenes/Inbox/Screens/Conversation.tsx
Labels: Jira Synced

#4772 Inquiry checkout copy additions from legal
  CHANGELOG.yml
  src/lib/Scenes/Inbox/Components/Conversations/MakeOfferModal.tsx
  src/lib/Scenes/Inbox/Components/Conversations/MessageGroup.tsx
Labels: Jira Synced

#4751 Make offer countdown not showing correct number of hours
  src/lib/Scenes/Inbox/Components/Conversations/ReviewOfferButton.tsx
  src/lib/Scenes/Inbox/Components/Conversations/__tests__/ReviewOfferButton-tests.tsx
  src/lib/utils/__tests__/useEventTiming-tests.tsx
  src/lib/utils/useEventTiming.tsx
Labels: Jira Synced, Squash On Green

#4781 fix: add webViewRoute for buyer guarantee page
  src/lib/Scenes/Inbox/Components/Conversations/OpenInquiryModalButton.tsx
  src/lib/Scenes/Inbox/Components/Conversations/__tests__/OpenInquiryModalButton-tests.tsx
  src/lib/navigation/routes.tsx
Labels: Jira Synced

#4770 analytics(screens): add tracking in profile and fix track event not being a `screen` event.
  Artsy/App/ARAppDelegate+Emission.m
  Podfile.lock
  docs/analytics_and_tracking.md
  src/lib/Components/Artist/ArtistInsights/ArtistInsights.tsx
  src/lib/Components/Artist/ArtistInsights/__tests__/ArtistInsights-tests.tsx
  src/lib/Scenes/AuctionResult/AuctionResult.tsx
  src/lib/Scenes/MyBids/MyBids.tsx
  src/lib/Scenes/MyCollection/MyCollection.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tsx
  src/lib/Scenes/MyProfile/MyProfile.tsx
  src/lib/utils/track/SegmentTrackingProvider.ts
  src/lib/utils/track/helpers.ts
  src/lib/utils/track/providers.tsx
Labels: Jira Synced

#4779 enhancement(documentation): you get a feature flag, and you get a feature flag, and you get a feature flag
  docs/pull_request_template.md
Labels: Jira Synced

#4777 fix(CX-852): fix spaces between items in SaleList for tablets
  CHANGELOG.yml
  src/lib/Scenes/Sales/Components/SaleList.tsx
  src/lib/Scenes/Sales/Components/SaleListItem.tsx
  src/lib/Scenes/Sales/Components/__tests__/SaleListItem-tests.tsx
Labels: Jira Synced

#4749 fix: add border radius for auction image item
  src/lib/Components/Lists/AuctionResultListItem.tsx
Labels: Jira Synced

#4786 feat: do not render make offer button when fetching artwork fails (PURCHASE-2685)
  CHANGELOG.yml
  src/lib/Scenes/Inbox/Components/Conversations/OpenInquiryModalButton.tsx
Labels: Jira Synced

#4754 Fix(cx 1075)/fix formatted large numbers display
  CHANGELOG.yml
  src/lib/utils/__tests__/formatLargeNumber-tests.ts
  src/lib/utils/__tests__/formatLargeNumberOfItems-tests.ts
  src/lib/utils/formatLargeNumber.ts
Labels: Jira Synced

#4788 vscode autoupdate of tasks
  .vscode/tasks.json
Labels: Jira Synced, Squash On Green

#4778 fix(filters): removes max height on modal
  CHANGELOG.yml
  src/lib/Components/ArtworkFilter/ArtworkFilter.tsx
Labels: Jira Synced

#4791 fix: reregister for push notifications on login every time
  Artsy/App/ARAppNotificationsDelegate.m
  CHANGELOG.yml
Labels: Jira Synced, Squash On Green

#4792 fix: fix changelog #trivial
  CHANGELOG.yml
Labels: Squash On Green

#4782 feat: enable Inquiry Checkout (PURCHASE-2684)
  CHANGELOG.yml
  src/lib/store/config/features.ts
Labels: Squash On Green

#4789 update(gemfile.lock): remove a gem after running `bundle install`
  Gemfile.lock
Labels: Jira Synced

#4795 feat(PX-4061): Order history feature flag
  src/lib/store/config/features.ts
Labels: Jira Synced, Squash On Green

#4784 fix(CX-1442): wrong input font on android
  CHANGELOG.yml
  src/lib/Components/Input/Input.tsx
Labels: Jira Synced

#4796 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4785 cleanup(old echo): removed some methods and code that were not used
  Artsy/App/ArtsyEcho.h
  Artsy/App/ArtsyEcho.m
  src/lib/store/config/EchoModel.tsx
Labels: Jira Synced

#4753 feat: allow sticky tabs to add additional sticky header content
  CHANGELOG.yml
  src/__generated__/ArtistBelowTheFoldQuery.graphql.ts
  src/__generated__/ArtistShows_artist.graphql.ts
  src/lib/Components/Artist/ArtistAbout/ArtistAbout.tsx
  src/lib/Components/Artist/ArtistAbout/__tests__/ArtistAbout-tests.tsx
  src/lib/Components/Artist/ArtistAbout/__tests__/ArtistAboutShows-tests.tsx
  src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
  src/lib/Components/Artist/ArtistShows/ArtistShows.tsx
  src/lib/Components/StickyTabPage/SnappyHorizontalRail.tsx
  src/lib/Components/StickyTabPage/StickyTabPage.tsx
  src/lib/Components/StickyTabPage/StickyTabPageFlatList.tsx
  src/lib/Scenes/Artist/Artist.tsx
  src/lib/Scenes/Artist/__tests__/Artist-tests.tsx
  src/lib/navigation/routes.tsx
  src/lib/store/config/features.ts
  src/setupJest.ts
Labels: Jira Synced, Squash On Green

#4809 feat: pass argument for artworksConnection
  src/__generated__/CollectionArtworksInfiniteScrollGridQuery.graphql.ts
  src/__generated__/CollectionArtworksTestsQuery.graphql.ts
  src/__generated__/CollectionArtworks_collection.graphql.ts
  src/__generated__/CollectionQuery.graphql.ts
  src/__generated__/CollectionTestsQuery.graphql.ts
  src/__generated__/Collection_collection.graphql.ts
  src/__generated__/FilterModalTestsQuery.graphql.ts
  src/lib/Scenes/Collection/Collection.tsx
  src/lib/Scenes/Collection/Screens/CollectionArtworks.tsx
Labels: Jira Synced, Squash On Green

#4810 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4806 fix: stop crashing when rendering artworks tabs
  src/lib/Components/StickyTabPage/StickyTabPageFlatList.tsx
Labels: Jira Synced, Squash On Green

#4805 fix(actionsheet): gallery locations actionsheet crash fix
  src/lib/Components/LocationMap/index.tsx
  src/lib/Scenes/Partner/Components/PartnerMap.tsx
  src/lib/Scenes/Partner/Screens/PartnerLocations.tsx
Labels: Jira Synced

#4812 chore: update android metadata
  CHANGELOG.yml
  fastlane/metadata/android/en-US/changelogs/91.txt
  fastlane/metadata/android/en-US/full_description.txt
  fastlane/metadata/android/en-US/images/featureGraphic.png
  fastlane/metadata/android/en-US/images/icon.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/1_en-US.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/2_en-US.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/3_en-US.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/4_en-US.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/5_en-US.png
  fastlane/metadata/android/en-US/images/sevenInchScreenshots/1_en-US.png
  fastlane/metadata/android/en-US/images/sevenInchScreenshots/2_en-US.png
  fastlane/metadata/android/en-US/images/tenInchScreenshots/1_en-US.png
  fastlane/metadata/android/en-US/images/tenInchScreenshots/2_en-US.png
  fastlane/metadata/android/en-US/images/tenInchScreenshots/3_en-US.png
  fastlane/metadata/android/en-US/images/tenInchScreenshots/4_en-US.png
  fastlane/metadata/android/en-US/images/tenInchScreenshots/5_en-US.png
  fastlane/metadata/android/en-US/short_description.txt
  fastlane/metadata/android/en-US/title.txt
  fastlane/metadata/android/en-US/video.txt
Labels: Jira Synced, Squash On Green

#4811 fix: sentry error tagging, update app.json before bundling apk
  fastlane/Fastfile
Labels: Jira Synced

#4818 feat(FX-2632): add material filter without search UI
  CHANGELOG.yml
  src/__generated__/ArtistAboveTheFoldQuery.graphql.ts
  src/__generated__/ArtistArtworksQuery.graphql.ts
  src/__generated__/ArtistArtworks_artist.graphql.ts
  src/__generated__/ArtistSeriesArtworksInfiniteScrollGridQuery.graphql.ts
  src/__generated__/ArtistSeriesArtworksTestsQuery.graphql.ts
  src/__generated__/ArtistSeriesArtworks_artistSeries.graphql.ts
  src/__generated__/ArtistSeriesQuery.graphql.ts
  src/__generated__/ArtistSeriesTestsQuery.graphql.ts
  src/__generated__/CollectionArtworksInfiniteScrollGridQuery.graphql.ts
  src/__generated__/CollectionArtworksTestsQuery.graphql.ts
  src/__generated__/CollectionArtworks_collection.graphql.ts
  src/__generated__/CollectionQuery.graphql.ts
  src/__generated__/CollectionTestsQuery.graphql.ts
  src/__generated__/FairAllFollowedArtistsQuery.graphql.ts
  src/__generated__/FairAllFollowedArtistsTestsQuery.graphql.ts
  src/__generated__/FairArtworksInfiniteScrollGridQuery.graphql.ts
  src/__generated__/FairArtworksTestsQuery.graphql.ts
  src/__generated__/FairArtworks_fair.graphql.ts
  src/__generated__/FairQuery.graphql.ts
  src/__generated__/FairTestsQuery.graphql.ts
  src/__generated__/FilterModalTestsQuery.graphql.ts
  src/__generated__/PartnerArtworkInfiniteScrollGridQuery.graphql.ts
  src/__generated__/PartnerArtworkTestsQuery.graphql.ts
  src/__generated__/PartnerArtwork_partner.graphql.ts
  src/__generated__/PartnerQuery.graphql.ts
  src/__generated__/PartnerRefetchQuery.graphql.ts
  src/__generated__/ShowArtworksInfiniteScrollGridQuery.graphql.ts
  src/__generated__/ShowArtworksTestsQuery.graphql.ts
  src/__generated__/ShowArtworks_show.graphql.ts
  src/__generated__/ShowQuery.graphql.ts
  src/__generated__/ShowTestsQuery.graphql.ts
  src/__generated__/VanityURLEntityQuery.graphql.ts
  src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
  src/lib/Components/ArtworkFilter/ArtworkFilter.tsx
  src/lib/Components/ArtworkFilter/ArtworkFilterHelpers.ts
  src/lib/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx
  src/lib/Components/ArtworkFilter/ArtworkFilterStore.tsx
  src/lib/Components/ArtworkFilter/Filters/MaterialsTermsOptions.tsx
  src/lib/Components/ArtworkFilter/Filters/__tests__/MaterialsTermsOptions-tests.tsx
  src/lib/Components/ArtworkFilter/__tests__/ArtworkFiltersStore-tests.tsx
  src/lib/Components/ArtworkFilter/__tests__/FilterArtworksHelpers-tests.tsx
  src/lib/Scenes/ArtistSeries/ArtistSeriesArtworks.tsx
  src/lib/Scenes/Collection/Screens/CollectionArtworks.tsx
  src/lib/Scenes/Fair/Components/FairArtworks.tsx
  src/lib/Scenes/Partner/Components/PartnerArtwork.tsx
  src/lib/Scenes/Show/Components/ShowArtworks.tsx
Labels: Jira Synced

#4815 feat: add danger changelog validation
  __tests__/dangerRules/validateChangelogYMLFile-tests.ts
  dangerfile.ts
  docs/pull_request_template.md
  jest.config.js
  package.json
  scripts/changelog/generateChangelogSectionTemplate.js
  scripts/changelog/parsePRDescription.js
  src/setupJest.ts
  tsconfig.json
  tslint.json
  yarn.lock
Labels: Jira Synced

#4823 fix: Use string for user agent when debugging
  CHANGELOG.yml
  src/lib/store/GlobalStore.tsx
Labels: Jira Synced

#4825 fix(CX-1488): broken slider
  CHANGELOG.yml
  src/lib/Components/CircleWithBorder/CircleWithBorder.tsx
Labels: Jira Synced

#4797 fix: don't rerender home when logged out
  CHANGELOG.yml
  src/lib/Scenes/Home/Home.tsx
Labels: Jira Synced

#4824 Fix(cx-1485): ensure android dark mode can overridden inapp
  CHANGELOG.yml
  android/app/src/main/res/values/styles.xml
Labels: Jira Synced

#4829 feat(FX-2646): add material filter with search UI
  CHANGELOG.yml
  src/lib/Components/ArtworkFilter/Filters/MaterialsTermsOptions.tsx
  src/lib/Components/ArtworkFilter/Filters/MultiSelectOption.tsx
Labels: Jira Synced

#4790 feat(fx-2634): Custom size filter
  .gitignore
  CHANGELOG.yml
  src/lib/Components/ArtworkFilter/ArtworkFilterHelpers.ts
  src/lib/Components/ArtworkFilter/Filters/PriceRangeOptionsNew.tsx
  src/lib/Components/ArtworkFilter/Filters/SizeOptions.tsx
  src/lib/Components/ArtworkFilter/Filters/SizeOptionsNew.tsx
  src/lib/Components/ArtworkFilter/Filters/SizeOptionsOld.tsx
  src/lib/Components/ArtworkFilter/Filters/__tests__/SizeOptionsNew-tests.tsx
  src/lib/Components/ArtworkFilter/Filters/__tests__/helpers-tests.tsx
  src/lib/Components/ArtworkFilter/Filters/helpers.ts
Labels: Jira Synced, Squash On Green

#4834 chore: add whitelist paths for android applinks
  android/app/src/main/AndroidManifest.xml
Labels: Jira Synced

#4832 updates(security): update lodash, remove nokogiri, update kramdown
  Gemfile
  Gemfile.lock
  package.json
  yarn.lock
Labels: Jira Synced

#4831 fix(search input): fix a bug in search where the clear button doesnt go away
  src/lib/Components/Input/Input.tsx
  src/lib/Components/SearchInput.tsx
Labels: Jira Synced

#4839 feat: add admin menu item to clear relay cache
  CHANGELOG.yml
  src/lib/utils/AdminMenu.tsx
Labels: Squash On Green

#4783 docs(flags): removing a feature flag
  docs/developing_a_feature.md
Labels: Jira Synced

#4835 tweak(analytics): fire inboxInquiries screen event, and dont send Inbox screen event
  src/lib/AppRegistry.tsx
  src/lib/Scenes/Inbox/Components/Conversations/Conversations.tsx
  src/lib/utils/track/schema.ts
Labels: Jira Synced, Squash On Green

#4841 fix(FX-2934): add ability to unselected ways to buy options
  CHANGELOG.yml
  src/lib/Components/ArtworkFilter/ArtworkFilterStore.tsx
  src/lib/Components/ArtworkFilter/__tests__/ArtworkFiltersStore-tests.tsx
Labels: Jira Synced, Squash On Green

#4837 fix: fix fastlane failure #trivial
  CHANGELOG.yml
  fastlane/Fastfile
Labels: Squash On Green

#4842 feat: Revert "remove lotsByFollowedArtists rail for now (#4759)" #trivial
  CHANGELOG.yml
  Podfile.lock
  src/lib/Scenes/Home/Home.tsx
Labels: Squash On Green

#4803 feat: add new route for order history & render order's id PX-4062
  CHANGELOG.yml
  src/__generated__/OrderHistoryPaginationQuery.graphql.ts
  src/__generated__/OrderHistoryQuery.graphql.ts
  src/__generated__/OrderHistoryTestsQuery.graphql.ts
  src/__generated__/OrderHistory_me.graphql.ts
  src/lib/AppRegistry.tsx
  src/lib/Scenes/MyProfile/MyProfile.tsx
  src/lib/Scenes/OrderHistory/OrderHistory.tsx
  src/lib/Scenes/OrderHistory/__tests__/OrderHistory-tests.tsx
  src/lib/navigation/routes.tsx
Labels: Jira Synced, Squash On Green

#4807 Fix(cx 939): fix url decoding in navigation infra code
  CHANGELOG.yml
  Podfile.lock
  src/lib/navigation/__tests__/routes-tests.tsx
  src/lib/navigation/routes.tsx
Labels: Jira Synced

#4821 fix(CX-1482): sign up validation
  CHANGELOG.yml
  src/lib/Scenes/Onboarding/OnboardingCreateAccount/OnboardingCreateAccount.tsx
  src/lib/Scenes/Onboarding/OnboardingCreateAccount/OnboardingCreateAccountEmail.tsx
  src/lib/Scenes/Onboarding/OnboardingCreateAccount/OnboardingCreateAccountName.tsx
  src/lib/Scenes/Onboarding/OnboardingCreateAccount/OnboardingCreateAccountPassword.tsx
  src/lib/Scenes/Onboarding/OnboardingCreateAccount/__tests__/OnboardingCreateAccount-tests.tsx
  src/lib/Scenes/Onboarding/OnboardingCreateAccount/__tests__/OnboardingCreateAccountEmail-tests.tsx
  src/lib/Scenes/Onboarding/OnboardingCreateAccount/__tests__/OnboardingCreateAccountName-tests.tsx
  src/lib/Scenes/Onboarding/OnboardingCreateAccount/__tests__/OnboardingCreateAccountPassword-tests.tsx
Labels: Jira Synced, Squash On Green

#4828 fix(1378): vanishing artist series
  CHANGELOG.yml
  src/lib/Scenes/ArtistSeries/ArtistSeriesMoreSeries.tsx
Labels: Jira Synced, Squash On Green

#4822 Fix(cx 1481): [android] fix keyboard covers cta add credit card
  CHANGELOG.yml
  android/app/src/main/java/net/artsy/app/ArtsyNativeModule.java
Labels: Jira Synced

#4850 new release!
  fastlane/metadata/en-US/release_notes.txt
Labels: Jira Synced, Squash On Green

#4830 cleanup(hacks): just some reodering of lines to follow the template
  HACKS.md
Labels: Jira Synced

#4849 analytics(android): send to segment release when not in __DEV__
  src/lib/utils/track/SegmentTrackingProvider.ts
Labels: Jira Synced

#4846 enhancement(CX-1287): improve admin menu
  CHANGELOG.yml
  src/lib/utils/AdminMenu.tsx
Labels: Jira Synced

#4847 fix(layout): button and checkbox were not layed out right
  src/lib/Scenes/Onboarding/ForgotPassword.tsx
  src/lib/Scenes/Onboarding/OnboardingCreateAccount/OnboardingCreateAccount.tsx
  src/lib/Scenes/Onboarding/OnboardingLogin.tsx
Labels: Jira Synced

#4848 Enhancement(layout): add the scrollbar bar for smaller screens
  src/lib/Scenes/Onboarding/ForgotPassword.tsx
  src/lib/Scenes/Onboarding/OnboardingCreateAccount/OnboardingCreateAccount.tsx
  src/lib/Scenes/Onboarding/OnboardingLogin.tsx
  src/lib/Scenes/Onboarding/OnboardingPersonalization/OnboardingPersonalization.tsx
Labels: Jira Synced

#4744 enhancement: Update auction registration flow UI
  CHANGELOG.yml
  src/__generated__/RegistrationQuery.graphql.ts
  src/__generated__/Registration_me.graphql.ts
  src/__generated__/Registration_sale.graphql.ts
  src/lib/Components/Bidding/Components/BidInfoRow.tsx
  src/lib/Components/Bidding/Components/__tests__/PaymentInfo-tests.tsx
  src/lib/Components/Bidding/Screens/Registration.tsx
  src/lib/Components/Bidding/Screens/__tests__/ConfirmBid-tests.tsx
  src/lib/Components/Bidding/Screens/__tests__/Registration-tests.tsx
Labels: Jira Synced, Squash On Green

#4833 workaround(android placeholders): make a workaround to not have android placeholders be cut-off
  HACKS.md
  src/lib/Components/Input/Input.tsx
  src/lib/Scenes/Search/Search.tsx
Labels: Jira Synced, Squash On Green

#4838 analytics(add screen): add screen event for `auctions`
  src/lib/Scenes/Home/Components/SalesRail.tsx
  src/lib/utils/track/schema.ts
Labels: Jira Synced, Squash On Green

#4827 fix(CX-1226): lock screen orientation to portrait on android
  HACKS.md
  package.json
  patches/react-native-screens+2.17.1.patch
  src/lib/AndroidApp.tsx
  yarn.lock
Labels: Jira Synced, Squash On Green

#4853 fix: app links on android
  CHANGELOG.yml
  android/app/src/main/AndroidManifest.xml
  src/lib/utils/useDeepLinks.ts
Labels: Jira Synced, Squash On Green

#4855 chore: trigger android build #trivial
  CHANGELOG.yml
Labels: Squash On Green

#4857 fix(search input): cancel button was not cancelling
  src/lib/Components/Input/Input.tsx
Labels: Jira Synced, Squash On Green

#4852 enhancement(admin menu): show version, build number, commit short hash
  .gitignore
  Artsy.xcodeproj/project.pbxproj
  Artsy/App/ARTArtsyNativeModule.h
  Artsy/App/ARTArtsyNativeModule.m
  Artsy/App_Resources/Artsy-Info.plist
  Artsy/View_Controllers/Admin/ARAdminSettingsViewController.m
  Podfile.lock
  android/app/build.gradle
  android/app/src/main/java/net/artsy/app/ArtsyNativeModule.java
  fastlane/Fastfile
  src/lib/NativeModules/ArtsyNativeModule.tsx
  src/lib/NativeModules/LegacyNativeModules.tsx
  src/lib/Scenes/About/About.tsx
  src/lib/store/__tests__/GlobalStoreModel-tests.ts
  src/lib/utils/AdminMenu.tsx
  src/setupJest.ts
Labels: Jira Synced

#4854 fix: Prevent multiline input placeholder on Android
  CHANGELOG.yml
  src/lib/Components/Input/Input.tsx
Labels: Jira Synced, Squash On Green

#4858 fix(CX-1504): onboarding back button is flying off
  CHANGELOG.yml
  src/lib/Scenes/Onboarding/ForgotPassword.tsx
  src/lib/Scenes/Onboarding/OnboardingCreateAccount/OnboardingCreateAccount.tsx
  src/lib/Scenes/Onboarding/OnboardingLogin.tsx
Labels: Jira Synced, Squash On Green

#4802 feat: add artwork location filter to filter modal
  CHANGELOG.yml
  src/__generated__/ArtistAboveTheFoldQuery.graphql.ts
  src/__generated__/ArtistArtworksQuery.graphql.ts
  src/__generated__/ArtistArtworks_artist.graphql.ts
  src/__generated__/ArtistSeriesArtworksInfiniteScrollGridQuery.graphql.ts
  src/__generated__/ArtistSeriesArtworksTestsQuery.graphql.ts
  src/__generated__/ArtistSeriesArtworks_artistSeries.graphql.ts
  src/__generated__/ArtistSeriesQuery.graphql.ts
  src/__generated__/ArtistSeriesTestsQuery.graphql.ts
  src/__generated__/CollectionArtworksInfiniteScrollGridQuery.graphql.ts
  src/__generated__/CollectionArtworksTestsQuery.graphql.ts
  src/__generated__/CollectionArtworks_collection.graphql.ts
  src/__generated__/CollectionQuery.graphql.ts
  src/__generated__/CollectionTestsQuery.graphql.ts
  src/__generated__/FairAllFollowedArtistsQuery.graphql.ts
  src/__generated__/FairAllFollowedArtistsTestsQuery.graphql.ts
  src/__generated__/FairArtworksInfiniteScrollGridQuery.graphql.ts
  src/__generated__/FairArtworksTestsQuery.graphql.ts
  src/__generated__/FairArtworks_fair.graphql.ts
  src/__generated__/FairQuery.graphql.ts
  src/__generated__/FairTestsQuery.graphql.ts
  src/__generated__/FilterModalTestsQuery.graphql.ts
  src/__generated__/ShowArtworksInfiniteScrollGridQuery.graphql.ts
  src/__generated__/ShowArtworksTestsQuery.graphql.ts
  src/__generated__/ShowArtworks_show.graphql.ts
  src/__generated__/ShowQuery.graphql.ts
  src/__generated__/ShowTestsQuery.graphql.ts
  src/__generated__/VanityURLEntityQuery.graphql.ts
  src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
  src/lib/Components/ArtworkFilter/ArtworkFilter.tsx
  src/lib/Components/ArtworkFilter/ArtworkFilterHelpers.ts
  src/lib/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx
  src/lib/Components/ArtworkFilter/ArtworkFilterStore.tsx
  src/lib/Components/ArtworkFilter/Filters/LocationCitiesOptions.tsx
  src/lib/Components/ArtworkFilter/Filters/__tests__/LocationCitiesOptions-tests.tsx
  src/lib/Components/ArtworkFilter/__tests__/ArtworkFiltersStore-tests.tsx
  src/lib/Scenes/ArtistSeries/ArtistSeriesArtworks.tsx
  src/lib/Scenes/Collection/Screens/CollectionArtworks.tsx
  src/lib/Scenes/Fair/Components/FairArtworks.tsx
  src/lib/Scenes/Show/Components/ShowArtworks.tsx
Labels: Jira Synced, Squash On Green

#4860 fix: deep link issue when the app is in the background
  android/app/src/main/AndroidManifest.xml
  src/lib/utils/useDeepLinks.ts
Labels: Jira Synced, Squash On Green

#4862 ci 🤞
  .circleci/config.yml
  .github/workflows/promote.yml
  fastlane/Fastfile
  fastlane/metadata/android/en-US/changelogs/default.txt
Labels: Jira Synced

#4800 provided a util method for decoding an env var
  CHANGELOG.yml
  android/app/src/main/java/net/artsy/app/utils/ReactNativeConfigUtils.java
Labels: Jira Synced

#4866 fix: iOS app blank screen
  CHANGELOG.yml
  src/lib/NativeModules/LegacyNativeModules.tsx
Labels: Jira Synced, Squash On Green

#4865 no need to bother david :)
  renovate.json
Labels: Jira Synced

#4861 feat: update order of filters
  CHANGELOG.yml
  src/__generated__/ArtistSeriesArtworksInfiniteScrollGridQuery.graphql.ts
  src/__generated__/ArtistSeriesArtworksTestsQuery.graphql.ts
  src/__generated__/ArtistSeriesArtworks_artistSeries.graphql.ts
  src/__generated__/ArtistSeriesQuery.graphql.ts
  src/__generated__/ArtistSeriesTestsQuery.graphql.ts
  src/lib/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx
  src/lib/Components/ArtworkFilter/__tests__/FilterModal-tests.tsx
  src/lib/Scenes/ArtistSeries/ArtistSeriesArtworks.tsx
Labels: Jira Synced

#4867 enhancement(CX-1441): info button hitslop
  CHANGELOG.yml
  src/lib/Scenes/Inbox/Screens/Conversation.tsx
Labels: Jira Synced, Squash On Green

#4872 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4874 cleanup(metadata): dont upload metadata for android beta, and remove images
  fastlane/Fastfile
  fastlane/metadata/android/en-US/images/featureGraphic.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/1_en-US.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/2_en-US.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/3_en-US.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/4_en-US.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/5_en-US.png
  fastlane/metadata/android/en-US/images/tenInchScreenshots/1_en-US.png
  fastlane/metadata/android/en-US/images/tenInchScreenshots/2_en-US.png
  fastlane/metadata/android/en-US/images/tenInchScreenshots/3_en-US.png
  fastlane/metadata/android/en-US/images/tenInchScreenshots/4_en-US.png
  fastlane/metadata/android/en-US/images/tenInchScreenshots/5_en-US.png
Labels: Jira Synced, Squash On Green

#4873 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4870 fix: webview top padding
  CHANGELOG.yml
  src/lib/Components/ArtsyReactWebView.tsx
Labels: Jira Synced, Squash On Green

#4871 chore: Prepare for development, 6.9.3
  CHANGELOG.yml
  app.json
Labels: Squash On Green

#4864 fix: correct mismatch of time until live auction
  CHANGELOG.yml
  src/lib/utils/__tests__/saleTime-tests.ts
  src/lib/utils/saleTime.ts
Labels: Jira Synced

#4844 feat: User can see order info on each row PX-4065
  CHANGELOG.yml
  src/__generated__/OrderHistoryPaginationQuery.graphql.ts
  src/__generated__/OrderHistoryQuery.graphql.ts
  src/__generated__/OrderHistoryRow_order.graphql.ts
  src/__generated__/OrderHistoryTestsQuery.graphql.ts
  src/__generated__/OrderHistory_me.graphql.ts
  src/lib/Scenes/OrderHistory/OrderHistory.tsx
  src/lib/Scenes/OrderHistory/OrderHistoryRow.tsx
  src/lib/Scenes/OrderHistory/__tests__/OrderHistory-tests.tsx
  src/lib/Scenes/OrderHistory/__tests__/OrderHistoryRow-tests.tsx
Labels: Jira Synced

#4851 fix: select filter item on swipe
  CHANGELOG.yml
  src/palette/elements/Touchable/Touchable.tsx
  src/setupJest.ts
Labels: Jira Synced

#4878 fix(filters): uses correct copy for title
  src/lib/Components/ArtworkFilter/Filters/ArtistNationalitiesOptions.tsx
Labels: Squash On Green

#4876 feat: order details page initialization
  CHANGELOG.yml
  src/__generated__/OrderDetailsQuery.graphql.ts
  src/__generated__/OrderDetails_order.graphql.ts
  src/lib/AppRegistry.tsx
  src/lib/Scenes/OrderHistory/OrderDetails/OrderDetails.tsx
  src/lib/navigation/__tests__/routes-tests.tsx
  src/lib/navigation/routes.tsx
Labels: Jira Synced

#4885 fix: replace "color" filter with "colors" filter
  CHANGELOG.yml
  src/lib/Components/ArtworkFilter/ArtworkFilterHelpers.ts
  src/lib/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx
  src/lib/Components/ArtworkFilter/Filters/ColorsOptions.tsx
  src/lib/Components/ArtworkFilter/Filters/__tests__/ColorsOptions-tests.tsx
Labels: Jira Synced

#4884 fix: Decode html entities in markdown
  CHANGELOG.yml
  package.json
  src/lib/utils/renderMarkdown.tsx
  yarn.lock
Labels: Jira Synced

#4877 fix: show error modal on all registration errors
  CHANGELOG.yml
  src/lib/Components/Bidding/Screens/Registration.tsx
  src/lib/Components/Bidding/Screens/__tests__/Registration-tests.tsx
Labels: Jira Synced, Squash On Green

#4879 fix disabled button bug for works with only one edition
  src/lib/Scenes/Inbox/Components/Conversations/MakeOfferModal.tsx
  src/lib/Scenes/Inbox/Components/Conversations/__tests__/MakeOfferModal-tests.tsx
Labels: Jira Synced

#4898 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4900 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4890 fix: change order detail page route
  CHANGELOG.yml
  android/app/src/main/AndroidManifest.xml
  src/lib/Scenes/OrderHistory/OrderHistoryRow.tsx
  src/lib/navigation/__tests__/routes-tests.tsx
  src/lib/navigation/routes.tsx
  src/palette/elements/Touchable/Touchable.tsx
Labels: Jira Synced, Squash On Green
