Repository artsy/eigen, pull requests merged in 2021-03, with the labels that each got.

#4488 Update metaphysics schema
  data/schema.graphql
  src/__generated__/InboxTestsQuery.graphql.ts
  src/__generated__/MyBidsTestsQuery.graphql.ts
  src/__generated__/MyBids_me.graphql.ts
  src/__generated__/WatchedLot_lot.graphql.ts
  src/lib/Scenes/MyBids/MyBids.tsx
Labels: Merge On Green

#4493 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4494 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4496 chore: move MP freshness check to cron job
  .circleci/config.yml
Labels: Squash On Green

#4491 fix(android): sticky tabs
  CHANGELOG.yml
  src/lib/Components/Artist/ArtistInsights/ArtistInsights.tsx
  src/lib/Components/StickyTabPage/SitckyTabPageContext.tsx
  src/lib/Components/StickyTabPage/StickyTabPage.tsx
  src/lib/Components/StickyTabPage/StickyTabPageFlatList.tsx
  src/lib/Components/StickyTabPage/StickyTabPageTabBar.tsx
Labels: Jira Synced

#4497 fix: env migration issue
  CHANGELOG.yml
  src/lib/store/migration.ts
Labels: Squash On Green

#4479 Update Eigen to call the MP mutation
  CHANGELOG.yml
  src/__generated__/InquiryMakeOfferButtonOrderMutation.graphql.ts
  src/__generated__/InquiryMakeOfferButtonTestsQuery.graphql.ts
  src/__generated__/InquiryMakeOfferButton_artwork.graphql.ts
  src/__generated__/MakeOfferModalQuery.graphql.ts
  src/__generated__/MakeOfferModal_artwork.graphql.ts
  src/lib/Scenes/Artwork/Components/CommercialButtons/MakeOfferButton.tsx
  src/lib/Scenes/Artwork/Components/CommercialButtons/__tests__/CommercialButtons-tests.tsx
  src/lib/Scenes/Inbox/Components/Conversations/Composer.tsx
  src/lib/Scenes/Inbox/Components/Conversations/InquiryMakeOfferButton.tsx
  src/lib/Scenes/Inbox/Components/Conversations/MakeOfferModal.tsx
  src/lib/Scenes/Inbox/Components/Conversations/OpenInquiryModalButton.tsx
  src/lib/Scenes/Inbox/Components/Conversations/__tests__/InquiryMakeOfferButton-tests.tsx
  src/lib/Scenes/Inbox/Screens/Conversation.tsx
Labels: Jira Synced, Squash On Green

#4502 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4501 fix: save pricePaid currency on edit #trivial
  src/lib/Scenes/MyCollection/Screens/ArtworkFormModal/MyCollectionArtworkFormModal.tsx
Labels: Jira Synced

#4503 volunteer to help with the upgrades
  renovate.json
Labels: Squash On Green

#4490 feat: support deep links on android
  CHANGELOG.yml
  android/app/src/main/AndroidManifest.xml
  src/lib/AndroidApp.tsx
  src/lib/store/AuthModel.ts
Labels: Jira Synced

#4505 fix: android auction mount
  Artsy/App/ARModalWithBottomSafeAreaViewController.h
  Artsy/App/ARModalWithBottomSafeAreaViewController.m
  Artsy/App/ARScreenPresenterModule.m
  Artsy/View_Controllers/ARSerifNavigationViewController.m
  CHANGELOG.yml
  Podfile.lock
  src/lib/AppRegistry.tsx
  src/lib/Components/Bidding/Screens/Registration.tsx
  src/lib/Components/ModalHeader.tsx
  src/lib/Containers/BidFlow.tsx
  src/lib/Containers/RegistrationFlow.tsx
  src/lib/Scenes/Consignments/ConsignmentsHome/ConsignmentsSubmissionForm.tsx
  src/lib/navigation/__tests__/routes-tests.tsx
  src/lib/navigation/routes.tsx
  src/lib/utils/platformUtil.ts
Labels: Jira Synced, Squash On Green

#4508 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4512 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4513 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4510 fix: android keyboard height on android
  CHANGELOG.yml
  src/lib/Components/FancyModal/FancyModal.tsx
  src/lib/utils/useScreenDimensions.tsx
Labels: Jira Synced

#4511 fix: setup router before emission bootstraps #trivial
  Artsy/Networking/API_Modules/ArtsyAPI+Sailthru.m
  CHANGELOG.yml
Labels: Jira Synced, Squash On Green

#4517 fix: fancy modal status bar
  CHANGELOG.yml
  src/lib/Components/FancyModal/FancyModal.tsx
Labels: Jira Synced

#4518 fix: fancy modal border radius animating on non shrinking backgrounds
  CHANGELOG.yml
  src/lib/Components/FancyModal/FancyModalCard.tsx
Labels: Jira Synced

#4506 feat: only show make offer button in conversation when there is no active order (PURCHASE-2463)
  CHANGELOG.yml
  src/__generated__/ConversationQuery.graphql.ts
  src/__generated__/Conversation_me.graphql.ts
  src/lib/Scenes/Inbox/Screens/Conversation.tsx
  src/lib/Scenes/Inbox/Screens/__tests__/Conversation-tests.tsx
Labels: Jira Synced, Merge On Green

#4520 fix(stickers): fixing ios imessage stickers
  Artsy Stickers/Info.plist
  Artsy Stickers/LICENSE.md
  Artsy Stickers/Stickers.xcassets/Contents.json
  Artsy Stickers/Stickers.xcassets/Sticker Pack.stickerpack/Contents.json
  Artsy Stickers/icon_assets/README.md
  Artsy Stickers/icon_assets/ios10-imessage-stickers-icon-sketch-template.sketch
  Artsy.xcodeproj/project.pbxproj
  Artsy.xcodeproj/xcshareddata/xcschemes/Artsy Stickers.xcscheme
  Artsy.xcodeproj/xcshareddata/xcschemes/Artsy.xcscheme
  CHANGELOG.yml
  Podfile
  Podfile.lock
  emission/Emission.podspec
Labels: Jira Synced

#4519 Fix/fancy modal keyboard issues
  CHANGELOG.yml
  src/lib/Components/Bidding/Components/Input.tsx
  src/lib/Components/Bidding/Screens/BillingAddress.tsx
  src/lib/Components/TextArea.tsx
  src/lib/Scenes/Artwork/Components/CommercialButtons/InquiryModal.tsx
  src/lib/Scenes/Artwork/Components/CommercialButtons/ShippingModal.tsx
  src/lib/Scenes/MyAccount/Components/MyAccountFieldEditScreen.tsx
Labels: Jira Synced, Squash On Green

#4521 feat: add login feature flag
  CHANGELOG.yml
  src/lib/AndroidApp.tsx
  src/lib/Scenes/Onboarding/OldLogIn/LogIn.tsx
  src/lib/Scenes/Onboarding/OldLogIn/LogInEmail.tsx
  src/lib/Scenes/Onboarding/OldLogIn/LogInEnterPassword.tsx
  src/lib/Scenes/Onboarding/OldLogIn/LogInStore.tsx
  src/lib/Scenes/Onboarding/Onboarding.tsx
  src/lib/Scenes/Onboarding/__tests__/Onboarding-tests.tsx
  src/lib/store/GlobalStore.tsx
  src/lib/store/config/features.ts
Labels: Jira Synced

#4526 Update metaphysics schema
  data/schema.graphql
  src/__generated__/ArtistArtworks_artist.graphql.ts
  src/__generated__/ArtistSeriesArtworksTestsQuery.graphql.ts
  src/__generated__/ArtistSeriesArtworks_artistSeries.graphql.ts
  src/__generated__/ArtistSeriesTestsQuery.graphql.ts
  src/__generated__/CollectionArtworksTestsQuery.graphql.ts
  src/__generated__/CollectionArtworks_collection.graphql.ts
  src/__generated__/CollectionTestsQuery.graphql.ts
  src/__generated__/FairAllFollowedArtistsTestsQuery.graphql.ts
  src/__generated__/FairAllFollowedArtists_fairForFilters.graphql.ts
  src/__generated__/FairArtworksTestsQuery.graphql.ts
  src/__generated__/FairArtworks_fair.graphql.ts
  src/__generated__/FairTestsQuery.graphql.ts
  src/__generated__/FilterModalTestsQuery.graphql.ts
  src/__generated__/Filters_filteredArtworks.graphql.ts
  src/__generated__/Gene_gene.graphql.ts
  src/__generated__/PartnerArtworkTestsQuery.graphql.ts
  src/__generated__/PartnerArtwork_partner.graphql.ts
  src/__generated__/ShowArtworksTestsQuery.graphql.ts
  src/__generated__/ShowArtworks_show.graphql.ts
  src/__generated__/ShowTestsQuery.graphql.ts
Labels: Merge On Green

#4507 feat: multi-selection time period filters
  CHANGELOG.yml
  src/lib/Components/ArtworkFilterOptions/TimePeriodMultiOptions.tsx
  src/lib/Components/ArtworkFilterOptions/__tests__/TimePeriodMultiOptions-tests.tsx
  src/lib/Components/FilterModal/FilterModal.tsx
  src/lib/Components/FilterModal/__tests__/FilterModal-tests.tsx
  src/lib/utils/ArtworkFilter/ArtworkFiltersStore.tsx
  src/lib/utils/ArtworkFilter/FilterArtworksHelpers.ts
  src/lib/utils/ArtworkFilter/__tests__/ArtworkFiltersStore-tests.tsx
Labels: Jira Synced

#4495 fix: back button on last 2 consignments screens
  CHANGELOG.yml
  src/lib/Scenes/Consignments/Screens/ConfirmContactInfo.tsx
  src/lib/Scenes/Consignments/Screens/Confirmation.tsx
  src/lib/Scenes/Consignments/Screens/Overview.tsx
  src/lib/Scenes/Consignments/Screens/__tests__/ConfirmContactInfo-tests.tsx
Labels: Jira Synced

#4516 fix: Bid + Registration flows modal header
  Artsy/App/ARAppNotificationsDelegate.m
  Artsy/App/ARScreenPresenterModule.h
  Artsy/App/ARScreenPresenterModule.m
  Artsy/View_Controllers/ARSerifNavigationViewController.m
  Artsy/View_Controllers/Live_Auctions/LiveAuctionLotSetViewController.swift
  Artsy/View_Controllers/Live_Auctions/LiveAuctionLotViewController.swift
  Artsy_Tests/App_Tests/ARAppNotificationsDelegateTests.m
  CHANGELOG.yml
  emission/Pod/Classes/ViewControllers/ARBidFlowViewController.h
  emission/Pod/Classes/ViewControllers/ARBidFlowViewController.m
  src/__generated__/BidFlow_me.graphql.ts
  src/__generated__/BidFlow_sale_artwork.graphql.ts
  src/__generated__/RegistrationFlow_me.graphql.ts
  src/__generated__/RegistrationFlow_sale.graphql.ts
  src/__generated__/RegistrationQuery.graphql.ts
  src/__generated__/SelectMaxBidQuery.graphql.ts
  src/lib/AppRegistry.tsx
  src/lib/Components/Bidding/Screens/BidResult.tsx
  src/lib/Components/Bidding/Screens/BillingAddress.tsx
  src/lib/Components/Bidding/Screens/ConfirmBid/index.tsx
  src/lib/Components/Bidding/Screens/CreditCardForm.tsx
  src/lib/Components/Bidding/Screens/Registration.tsx
  src/lib/Components/Bidding/Screens/RegistrationResult.tsx
  src/lib/Components/Bidding/Screens/SelectCountry.tsx
  src/lib/Components/Bidding/Screens/SelectMaxBid.tsx
  src/lib/Components/Bidding/Screens/SelectMaxBidEdit.tsx
  src/lib/Components/Bidding/Screens/__tests__/BillingAddress-tests.tsx
  src/lib/Components/Bidding/Screens/__tests__/ConfirmBid-tests.tsx
  src/lib/Components/Bidding/Screens/__tests__/CreditCardForm-tests.tsx
  src/lib/Components/Bidding/Screens/__tests__/SelectMaxBid-tests.tsx
  src/lib/Components/Bidding/Screens/__tests__/SelectMaxBidEdit-tests.tsx
  src/lib/Components/Bidding/__tests__/BidFlow-tests.tsx
  src/lib/Containers/BidFlow.tsx
  src/lib/Containers/RegistrationFlow.tsx
  src/lib/Containers/__tests__/BidFlow-tests.tsx
  src/lib/Containers/__tests__/RegistrationFlow-tests.tsx
Labels: Jira Synced, Merge On Green

#4527 fix(signout): await clearUserData
  Artsy/App/ARAppDelegate+Emission.m
  Artsy/Networking/API_Modules/ARUserManager.h
  Artsy/Networking/API_Modules/ARUserManager.m
  CHANGELOG.yml
  emission/Pod/Classes/TemporaryAPI/ARTemporaryAPIModule.h
  emission/Pod/Classes/TemporaryAPI/ARTemporaryAPIModule.m
  src/lib/NativeModules/LegacyNativeModules.tsx
  src/lib/relay/middlewares/checkAuthenticationMiddleware.ts
  src/lib/store/GlobalStoreModel.ts
Labels: Jira Synced

#4522 refactor: match artwork filter feature flag name to project name
  CHANGELOG.yml
  src/lib/Components/ArtworkFilterOptions/__tests__/TimePeriodMultiOptions-tests.tsx
  src/lib/Components/FilterModal/FilterModal.tsx
  src/lib/store/config/features.ts
  src/lib/utils/ArtworkFilter/FilterArtworksHelpers.ts
Labels: Jira Synced

#4529 chore: update release notes
  fastlane/metadata/en-US/release_notes.txt
Labels: Squash On Green

#4530 Prepare for next release (v6.8.2)
  CHANGELOG.yml
  app.json
Labels: Squash On Green

#4531 fix: set system navigation bar color to white on modals for android
  CHANGELOG.yml
  android/app/src/main/res/values/styles.xml
Labels: Jira Synced, Squash On Green

#4532 fix: search input layout animation
  CHANGELOG.yml
  src/lib/AndroidApp.tsx
  src/lib/Components/SearchInput.tsx
Labels: Jira Synced

#4533 fix: change password screen title
  CHANGELOG.yml
  src/lib/Scenes/MyAccount/MyAccountEditPassword.tsx
  src/lib/Scenes/MyAccount/__tests__/MyAccountEditPassword-tests.tsx
Labels: Jira Synced, Squash On Green

#4536 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4539 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4541 fix: don't clear launch count on logout
  Artsy/Constants/ARDefaults.m
  CHANGELOG.yml
Labels: Jira Synced

#4540 fix: modal presentation on iOS
  Artsy.xcodeproj/project.pbxproj
  Artsy/App/ARModalViewController.h
  Artsy/App/ARModalViewController.m
  Artsy/App/ARModalWithBottomSafeAreaViewController.m
  Artsy/App/ARScreenPresenterModule.m
  Artsy/View_Controllers/Util/ARNavigationController.m
  Artsy_Tests/ReferenceImages/ARNavigationControllerSpec/visuals_should_be_show_a_back_button_with_2_view_controllers@3x.png
  CHANGELOG.yml
  src/lib/AppRegistry.tsx
Labels: Jira Synced, Squash On Green

#4535 fix: android consign photos action sheet
  CHANGELOG.yml
  package.json
  src/lib/AndroidApp.tsx
  src/lib/AppRegistry.tsx
  src/lib/Components/LocationMap/index.tsx
  src/lib/Components/Photos/AddEditPhotos.tsx
  src/lib/Scenes/Consignments/ConsignmentsHome/ConsignmentsSubmissionForm.tsx
  src/lib/Scenes/Consignments/Screens/Overview.tsx
  src/lib/Scenes/Consignments/Screens/__tests__/Overview-analytics-tests.tsx
  src/lib/Scenes/Consignments/Screens/__tests__/Overview-local-storage-tests.tsx
  src/lib/Scenes/Consignments/Screens/__tests__/Overview-tests.tsx
  src/lib/Scenes/Consignments/Screens/__tests__/Overview-uploading-tests.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkFormModal/MyCollectionArtworkFormModal.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkFormModal/Screens/MyCollectionArtworkFormAddPhotos.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkFormModal/Screens/MyCollectionArtworkFormMain.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkFormModal/Screens/__tests__/MyCollectionArtworkFormAddPhotos-tests.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkFormModal/Screens/__tests__/MyCollectionArtworkFormMain-tests.tsx
  src/lib/Scenes/MyCollection/State/MyCollectionArtworkModel.tsx
  src/lib/utils/requestPhotos.ts
  yarn.lock
Labels: Jira Synced

#4542 feature: add react web view module
  Artsy/App/ARScreenPresenterModule.m
  CHANGELOG.yml
  package.json
  src/lib/AppRegistry.tsx
  src/lib/Components/ArtsyReactWebView.tsx
  src/lib/Components/ArtsyWebView.tsx
  src/lib/Components/__tests__/ArtsyReactWebView-tests.tsx
  src/lib/Scenes/VanityURL/VanityURLPossibleRedirect.tsx
  src/lib/navigation/ModalStack.tsx
  src/lib/navigation/__tests__/routes-tests.tsx
  src/lib/navigation/routes.tsx
  src/lib/store/GlobalStore.tsx
  src/lib/store/config/features.ts
  yarn.lock
Labels: Jira Synced, Squash On Green

#4543 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4544 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4534 feat(fx-2623): Colors multi-select filter options screen
  CHANGELOG.yml
  src/__generated__/ArtistAboveTheFoldQuery.graphql.ts
  src/__generated__/ArtistArtworksQuery.graphql.ts
  src/__generated__/ArtistArtworks_artist.graphql.ts
  src/__generated__/ArtistSeriesArtworksInfiniteScrollGridQuery.graphql.ts
  src/__generated__/ArtistSeriesArtworksTestsQuery.graphql.ts
  src/__generated__/ArtistSeriesArtworks_artistSeries.graphql.ts
  src/__generated__/ArtistSeriesQuery.graphql.ts
  src/__generated__/ArtistSeriesTestsQuery.graphql.ts
  src/__generated__/CollectionArtworksInfiniteScrollGridQuery.graphql.ts
  src/__generated__/CollectionArtworksTestsQuery.graphql.ts
  src/__generated__/CollectionArtworks_collection.graphql.ts
  src/__generated__/CollectionQuery.graphql.ts
  src/__generated__/CollectionTestsQuery.graphql.ts
  src/__generated__/FairAllFollowedArtistsQuery.graphql.ts
  src/__generated__/FairAllFollowedArtistsTestsQuery.graphql.ts
  src/__generated__/FairArtworksInfiniteScrollGridQuery.graphql.ts
  src/__generated__/FairArtworksTestsQuery.graphql.ts
  src/__generated__/FairArtworks_fair.graphql.ts
  src/__generated__/FairQuery.graphql.ts
  src/__generated__/FairTestsQuery.graphql.ts
  src/__generated__/FilterModalTestsQuery.graphql.ts
  src/__generated__/PartnerArtworkInfiniteScrollGridQuery.graphql.ts
  src/__generated__/PartnerArtworkTestsQuery.graphql.ts
  src/__generated__/PartnerArtwork_partner.graphql.ts
  src/__generated__/PartnerQuery.graphql.ts
  src/__generated__/PartnerRefetchQuery.graphql.ts
  src/__generated__/ShowArtworksInfiniteScrollGridQuery.graphql.ts
  src/__generated__/ShowArtworksTestsQuery.graphql.ts
  src/__generated__/ShowArtworks_show.graphql.ts
  src/__generated__/ShowQuery.graphql.ts
  src/__generated__/ShowTestsQuery.graphql.ts
  src/__generated__/VanityURLEntityQuery.graphql.ts
  src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
  src/lib/Components/ArtworkFilterOptions/AttributionClassOptions.tsx
  src/lib/Components/ArtworkFilterOptions/ColorsOptions.tsx
  src/lib/Components/ArtworkFilterOptions/ColorsSwatch.tsx
  src/lib/Components/ArtworkFilterOptions/__tests__/AttributionClassOptions-tests.tsx
  src/lib/Components/ArtworkFilterOptions/__tests__/useMultiSelect-tests.tsx
  src/lib/Components/ArtworkFilterOptions/useMultiSelect.ts
  src/lib/Components/FilterModal/FilterModal.tsx
  src/lib/Components/FilterModal/__tests__/FilterModal-tests.tsx
  src/lib/Scenes/ArtistSeries/ArtistSeriesArtworks.tsx
  src/lib/Scenes/Collection/Screens/CollectionArtworks.tsx
  src/lib/Scenes/Fair/Components/FairArtworks.tsx
  src/lib/Scenes/Partner/Components/PartnerArtwork.tsx
  src/lib/Scenes/Show/Components/ShowArtworks.tsx
  src/lib/utils/ArtworkFilter/ArtworkFiltersStore.tsx
  src/lib/utils/ArtworkFilter/FilterArtworksHelpers.ts
  src/lib/utils/ArtworkFilter/__tests__/ArtworkFiltersStore-tests.tsx
  src/lib/utils/ArtworkFilter/__tests__/FilterArtworksHelpers-tests.tsx
  src/lib/utils/useLayout.tsx
  src/palette/elements/Touchable/Touchable.tsx
Labels: Jira Synced

#4546 chore: disable metaphysics-check job
  .circleci/config.yml
Labels: Squash On Green

#4547 chore: update react-native-webview pod
  Podfile.lock
Labels: Jira Synced, Squash On Green

#4551 feat: Add onboarding navigation infra
  src/lib/Scenes/Onboarding/Onboarding.tsx
  src/lib/Scenes/Onboarding/OnboardingCreateAccount.tsx
  src/lib/Scenes/Onboarding/OnboardingForgotPassword.tsx
  src/lib/Scenes/Onboarding/OnboardingLogin.tsx
  src/lib/Scenes/Onboarding/OnboardingWelcome.tsx
Labels: Jira Synced

#4550 feat: react web view cookies
  CHANGELOG.yml
  Podfile.lock
  package.json
  src/lib/AndroidApp.tsx
  src/lib/AppRegistry.tsx
  src/lib/Components/ArtsyReactWebView.tsx
  src/lib/Components/__tests__/ArtsyReactWebView-tests.tsx
  src/lib/store/GlobalStoreModel.ts
  src/lib/store/__tests__/GlobalStoreModel-tests.ts
  src/setupJest.ts
  yarn.lock
Labels: Jira Synced

#4553 fix(UI): quick fix in the Inquiries UI
  CHANGELOG.yml
  scripts/download-fonts
  src/lib/Scenes/Inbox/Components/Conversations/ConversationSnippet.tsx
Labels: Jira Synced

#4545 add analytics tracking for make offer and view offer buttons
  src/lib/Scenes/Inbox/Components/Conversations/Composer.tsx
  src/lib/Scenes/Inbox/Components/Conversations/MakeOfferModal.tsx
  src/lib/Scenes/Inbox/Components/Conversations/OpenInquiryModalButton.tsx
  src/lib/Scenes/Inbox/Components/Conversations/ReviewOfferButton.tsx
  src/lib/Scenes/Inbox/Components/Conversations/__tests__/ReviewOfferButton-tests.tsx
  yarn.lock
Labels: Jira Synced

#4552 feat: react web view navigation
  CHANGELOG.yml
  src/lib/Components/ArtsyReactWebView.tsx
  src/lib/Components/__tests__/ArtsyReactWebView-tests.tsx
  src/lib/Scenes/Artwork/Components/CommercialButtons/BuyNowButton.tsx
  src/lib/Scenes/Artwork/Components/CommercialButtons/MakeOfferButton.tsx
  src/lib/Scenes/Artwork/Components/CommercialButtons/__tests__/CommercialButtons-tests.tsx
  src/lib/Scenes/Inbox/Components/Conversations/InquiryMakeOfferButton.tsx
  src/lib/Scenes/Inbox/Components/Conversations/ReviewOfferButton.tsx
  src/lib/Scenes/Inbox/Components/Conversations/__tests__/InquiryMakeOfferButton-tests.tsx
  src/lib/Scenes/Inbox/Components/Conversations/__tests__/ReviewOfferButton-tests.tsx
  src/lib/Scenes/Inbox/Screens/Checkout.tsx
  src/lib/navigation/routes.tsx
Labels: Jira Synced

#4554 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4555 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4556 fix:round buyer's premium correctly on SaleInfo screen
  src/lib/Scenes/SaleInfo/SaleInfo.tsx
Labels: Jira Synced

#4538 feat: enable sentry for android
  CHANGELOG.yml
  android/app/src/main/java/net/artsy/app/MainApplication.java
  android/settings.gradle
  app.json
  fastlane/Fastfile
  src/lib/ErrorReporting.ts
  src/lib/utils/AdminMenu.tsx
Labels: Jira Synced

#4559 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4558 fix: fix os version check in modal header
  CHANGELOG.yml
  src/lib/Components/ModalHeader.tsx
  src/lib/utils/__tests__/hardware-tests.ts
  src/lib/utils/__tests__/platformUtil-tests.ts
  src/lib/utils/hardware.ts
  src/lib/utils/platformUtil.ts
  src/lib/utils/requestPhotos.ts
Labels: Jira Synced

#4560 fix: add camera permissions setup for android
  CHANGELOG.yml
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
Labels: Jira Synced

#4562 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4500 feat: Support echo kill switches
  Artsy/App/ARAppDelegate.m
  package.json
  src/lib/AndroidApp.tsx
  src/lib/AppRegistry.tsx
  src/lib/Scenes/ForceUpdate/ForceUpdate.tsx
  src/lib/package.json
  src/lib/store/GlobalStore.tsx
  src/lib/store/config/EchoModel.tsx
  src/lib/store/config/__tests__/EchoModel-tests.tsx
  src/lib/store/config/features.ts
  src/lib/utils/AdminMenu.tsx
  yarn.lock
Labels: Jira Synced

#4564 fix: use killedVersions instead of excludedVersions
  src/lib/store/config/EchoModel.tsx
  src/lib/store/config/__tests__/EchoModel-tests.tsx
Labels: Jira Synced, Squash On Green

#4566 fix: use artistAuctionResults instead of artistInsights for contextScreenOwnerType
  CHANGELOG.yml
  package.json
  src/lib/Components/Artist/ArtistInsights/ArtistInsightsAuctionResults.tsx
  src/lib/Components/Artist/ArtistInsights/MarketStats.tsx
  src/lib/Components/Artist/ArtistInsights/__tests__/MarketStats-tests.tsx
  src/lib/Scenes/AuctionResult/AuctionResult.tsx
  yarn.lock
Labels: Jira Synced, Squash On Green

#4570 chore: release notes for 6.8.2
  fastlane/metadata/en-US/release_notes.txt
Labels: Squash On Green

#4567 feat: make back button hide-able on Android
  CHANGELOG.yml
  src/lib/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx
  src/lib/Components/FilteredInfiniteScrollGrid/FilteredInfiniteScrollGrid.tsx
  src/lib/Components/StickyTabPage/StickyTabPage.tsx
  src/lib/Scenes/Fair/Fair.tsx
  src/lib/navigation/BackButton.tsx
  src/lib/navigation/NavStack.tsx
  src/lib/utils/__tests__/hideBackButtonOnScroll-tests.tsx
  src/lib/utils/hideBackButtonOnScroll.tsx
Labels: Jira Synced

#4573 fix market stats typo #trivial
  src/lib/Components/Artist/ArtistInsights/__tests__/MarketStats-tests.tsx
Labels: Jira Synced, Squash On Green

#4569 chore: Switch on react native web views behind echo flag
  CHANGELOG.yml
  src/lib/Scenes/VanityURL/__tests__/VanityURLPossibleRedirect-tests.tsx
  src/lib/navigation/__tests__/routes-tests.tsx
  src/lib/store/config/__tests__/features-tests.ts
  src/lib/store/config/features.ts
Labels: Squash On Green

#4563 enhancement(json files and tests): rework how we load json files and how we test with them
  src/lib/Scenes/BottomTabs/BottomTabsModel.ts
  src/lib/Scenes/MyCollection/State/MyCollectionModel.tsx
  src/lib/Scenes/Search/SearchModel.tsx
  src/lib/store/AuthModel.ts
  src/lib/store/ConfigModel.ts
  src/lib/store/GlobalStore.tsx
  src/lib/store/GlobalStoreModel.ts
  src/lib/store/NativeModel.ts
  src/lib/store/__tests__/GlobalStoreModel-tests.ts
  src/lib/store/config/EchoModel.tsx
  src/lib/store/config/EnvironmentModel.tsx
  src/lib/store/config/FeaturesModel.tsx
  src/lib/store/config/__tests__/EchoModel-tests.tsx
  src/lib/store/config/__tests__/FeaturesModel-tests.tsx
  src/lib/store/config/__tests__/features-tests.ts
  src/lib/store/config/features.ts
  src/lib/store/migration.ts
  src/lib/utils/jsonFiles.ts
Labels: Jira Synced

#4576 upgrades to bring all relay things in the same versions
  CHANGELOG.yml
  package.json
  patches/relay-compiler+10.1.3.patch
  yarn.lock
Labels: Jira Synced, Merge On Green

#4577 fix: android ci install sentry cli #trivial
  scripts/setup-distribute-linux
Labels: Squash On Green

#4579 fix: conditional installation of sentry-cli to avoid non-zero exit #trivial
  scripts/setup-distribute-linux
Labels: Squash On Green

#4581 chore: prepare for 6.8.3 #trivial
  CHANGELOG.yml
  app.json
Labels: Jira Synced, Squash On Green

#4571 chore: update consignments modal headers
  CHANGELOG.yml
  src/lib/Components/ModalHeader.tsx
  src/lib/Components/Photos/AddEditPhotos.tsx
  src/lib/Scenes/Consignments/Components/FormElements.tsx
  src/lib/Scenes/Consignments/ConsignmentsHome/ConsignmentsSubmissionForm.tsx
  src/lib/Scenes/Consignments/Screens/ConfirmContactInfo.tsx
  src/lib/Scenes/Consignments/Screens/Confirmation.tsx
  src/lib/Scenes/Consignments/Screens/ConsignmentsArtist.tsx
  src/lib/Scenes/Consignments/Screens/Edition.tsx
  src/lib/Scenes/Consignments/Screens/Location.tsx
  src/lib/Scenes/Consignments/Screens/Metadata.tsx
  src/lib/Scenes/Consignments/Screens/Overview.tsx
  src/lib/Scenes/Consignments/Screens/Provenance.tsx
  src/lib/Scenes/Consignments/Screens/SelectFromPhotoLibrary.tsx
  src/lib/Scenes/Consignments/Screens/__tests__/SelectFromPhotoLibrary-tests.tsx
Labels: Jira Synced, Squash On Green

#4548 feat: add splash screen to android
  CHANGELOG.yml
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/net/artsy/app/ArtsyNativeModule.java
  android/app/src/main/java/net/artsy/app/MainActivity.java
  android/app/src/main/res/drawable/bootsplash.xml
  android/app/src/main/res/mipmap-hdpi/bootsplash_logo.png
  android/app/src/main/res/mipmap-mdpi/bootsplash_logo.png
  android/app/src/main/res/mipmap-xhdpi/bootsplash_logo.png
  android/app/src/main/res/mipmap-xxhdpi/bootsplash_logo.png
  android/app/src/main/res/mipmap-xxxhdpi/bootsplash_logo.png
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/styles.xml
  package.json
  src/lib/AndroidApp.tsx
  src/lib/NativeModules/ArtsyNativeModule.tsx
  yarn.lock
Labels: Jira Synced

#4575 Avoid multiple-modal stack in the inquiry checkout/offer flow
  Artsy/App/ARScreenPresenterModule.m
  CHANGELOG.yml
  src/lib/Scenes/Inbox/Components/Conversations/InquiryMakeOfferButton.tsx
  src/lib/Scenes/Inbox/Components/Conversations/__tests__/InquiryMakeOfferButton-tests.tsx
  src/lib/navigation/__tests__/navigate-tests.tsx
  src/lib/navigation/navigate.ts
Labels: Jira Synced, Squash On Green
