Repository artsy/eigen, pull requests merged in 2021-02, with the labels that each got.

#4376 fix: update metaphsyics schema
  data/schema.graphql
  src/__generated__/CityBMWList_city.graphql.ts
  src/__generated__/CityFairList_city.graphql.ts
  src/__generated__/CitySavedList_city.graphql.ts
  src/__generated__/CitySectionList_city.graphql.ts
  src/__generated__/GlobalMapTestsQuery.graphql.ts
  src/__generated__/GlobalMap_viewer.graphql.ts
  src/lib/Scenes/City/CityBMWList.tsx
Labels: Jira Synced

#4377 feat: auction results QA updates
  CHANGELOG.yml
  src/__generated__/ArtistBelowTheFoldQuery.graphql.ts
  src/__generated__/ArtistInsightsAuctionResultsQuery.graphql.ts
  src/__generated__/ArtistInsightsAuctionResultsTestsQuery.graphql.ts
  src/__generated__/ArtistInsightsTestsQuery.graphql.ts
  src/__generated__/AuctionResultQuery.graphql.ts
  src/__generated__/AuctionResultTestsQuery.graphql.ts
  src/__generated__/AuctionResult_auctionResult.graphql.ts
  src/__generated__/MyCollectionArtworkArtistAuctionResultsTestsQuery.graphql.ts
  src/__generated__/MyCollectionArtworkInsightsTestsQuery.graphql.ts
  src/__generated__/MyCollectionArtworkQuery.graphql.ts
  src/lib/Components/Artist/ArtistInsights/ArtistInsightsAuctionResults.tsx
  src/lib/Components/AuctionResult/AuctionResultMidEstimate.tsx
  src/lib/Components/AuctionResult/__tests__/AuctionResultMidEstimate-tests.tsx
  src/lib/Components/Lists/AuctionResult.tsx
  src/lib/Components/Lists/__tests__/AuctionResult-tests.tsx
  src/lib/Scenes/AuctionResult/AuctionResult.tsx
  src/lib/Scenes/AuctionResult/__tests__/AuctionResult-tests.tsx
  src/palette/elements/Separator/Separator.tsx
Labels: Jira Synced

#4379 chore: remove artist insights lab feature flag
  Artsy/App/AROptions.h
  Artsy/App/AROptions.m
  CHANGELOG.yml
Labels: Jira Synced, Squash On Green

#4380 fix: add '~' to sentry source path #trivial
  fastlane/Fastfile
  src/lib/ErrorReporting.ts
Labels: Jira Synced, Squash On Green

#4381 fix: update sentry, react-native-sentry
  Artsy.xcodeproj/project.pbxproj
  Artsy/App/ARSentryAnalyticsProvider.m
  Artsy/View_Controllers/Admin/ARAdminSentryBreadcrumbViewController.h
  Artsy/View_Controllers/Admin/ARAdminSentryBreadcrumbViewController.m
  Artsy/View_Controllers/Admin/ARAdminSettingsViewController.m
  Podfile.lock
  package.json
  patches/@sentry+react-native+1.3.2.patch
  yarn.lock
Labels: Jira Synced, Squash On Green

#4356 (feat) connect market stats to real data
  src/__generated__/ArtistBelowTheFoldQuery.graphql.ts
  src/__generated__/ArtistInsightsTestsQuery.graphql.ts
  src/__generated__/ArtistInsights_artist.graphql.ts
  src/__generated__/MarketStatsQuery.graphql.ts
  src/__generated__/MarketStats_priceInsights.graphql.ts
  src/lib/Components/Artist/ArtistHeader.tsx
  src/lib/Components/Artist/ArtistInsights/ArtistInsights.tsx
  src/lib/Components/Artist/ArtistInsights/MarketStats.tsx
  src/lib/Scenes/Partner/Components/PartnerHeader.tsx
  src/lib/utils/__tests__/formatLargeNumber-tests.ts
  src/lib/utils/__tests__/formatLargeNumberOfItems-tests.ts
  src/lib/utils/__tests__/formatText-tests.ts
  src/lib/utils/formatLargeNumber.ts
  src/lib/utils/formatLargeNumberOfItems.ts
  src/lib/utils/formatText.ts
Labels: Jira Synced, Squash On Green

#4378 Add watched lots to Inbox 'bids' tab
  src/__generated__/ActiveLotStanding_lotStanding.graphql.ts
  src/__generated__/ClosedLotStanding_lotStanding.graphql.ts
  src/__generated__/InboxQuery.graphql.ts
  src/__generated__/InboxRefetchQuery.graphql.ts
  src/__generated__/InboxTestsQuery.graphql.ts
  src/__generated__/LotStatusListItem_lot.graphql.ts
  src/__generated__/LotStatusListItem_lotStanding.graphql.ts
  src/__generated__/MyBidsPaginatedQuery.graphql.ts
  src/__generated__/MyBidsQuery.graphql.ts
  src/__generated__/MyBidsTestsQuery.graphql.ts
  src/__generated__/MyBids_me.graphql.ts
  src/__generated__/WatchedLot_lot.graphql.ts
  src/lib/Scenes/MyBids/Components/ActiveLotStanding.tsx
  src/lib/Scenes/MyBids/Components/BiddingStatuses.tsx
  src/lib/Scenes/MyBids/Components/ClosedLotStanding.tsx
  src/lib/Scenes/MyBids/Components/LotStatusListItem.tsx
  src/lib/Scenes/MyBids/Components/WatchedLot.tsx
  src/lib/Scenes/MyBids/Components/index.tsx
  src/lib/Scenes/MyBids/MyBids.tsx
  src/lib/Scenes/MyBids/__tests__/ActiveLotStanding-tests.tsx
  src/lib/Scenes/MyBids/__tests__/ClosedLotStanding-tests.tsx
  src/lib/Scenes/MyBids/__tests__/MyBids-tests.tsx
  src/lib/Scenes/MyBids/helpers/timely.ts
Labels: Jira Synced

#4382 revert "chore: remove artist insights lab feature flag (#4379)"
  Artsy/App/AROptions.h
  Artsy/App/AROptions.m
  CHANGELOG.yml
Labels: Squash On Green

#4366 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4385 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4386 Update metaphysics schema
  data/schema.graphql
  src/__generated__/ArtistArtworks_artist.graphql.ts
  src/__generated__/ArtistSeriesArtworksTestsQuery.graphql.ts
  src/__generated__/ArtistSeriesArtworks_artistSeries.graphql.ts
  src/__generated__/ArtistSeriesTestsQuery.graphql.ts
  src/__generated__/CollectionArtworksTestsQuery.graphql.ts
  src/__generated__/CollectionArtworks_collection.graphql.ts
  src/__generated__/CollectionTestsQuery.graphql.ts
  src/__generated__/FairAllFollowedArtistsTestsQuery.graphql.ts
  src/__generated__/FairAllFollowedArtists_fairForFilters.graphql.ts
  src/__generated__/FairArtworksTestsQuery.graphql.ts
  src/__generated__/FairArtworks_fair.graphql.ts
  src/__generated__/FairTestsQuery.graphql.ts
  src/__generated__/FilterModalTestsQuery.graphql.ts
  src/__generated__/Filters_filteredArtworks.graphql.ts
  src/__generated__/Gene_gene.graphql.ts
  src/__generated__/ShowArtworksTestsQuery.graphql.ts
  src/__generated__/ShowArtworks_show.graphql.ts
  src/__generated__/ShowTestsQuery.graphql.ts
Labels: Merge On Green

#4384 bugfix: Fix layout issue preventing Inbox pull to refresh
  CHANGELOG.yml
  src/lib/Containers/Inbox/Inbox.tsx
Labels: Jira Synced

#4383 [WiP] feat: add market price insights picker
  src/__generated__/MarketStatsQuery.graphql.ts
  src/__generated__/MarketStats_priceInsightsConnection.graphql.ts
  src/lib/Components/Artist/ArtistInsights/MarketStats.tsx
Labels: Jira Synced

#4388 fix: make arrow icons grey when the percentage is between -5 and 5
  src/lib/Components/AuctionResult/AuctionResultMidEstimate.tsx
  src/lib/Components/AuctionResult/__tests__/AuctionResultMidEstimate-tests.tsx
Labels: Jira Synced

#4389 fix: properly format large numbers
  src/lib/Components/Artist/ArtistInsights/ArtistInsightsAuctionResults.tsx
Labels: Jira Synced

#4391 Update metaphysics schema
  data/schema.graphql
  src/__generated__/ArtistArtworks_artist.graphql.ts
  src/__generated__/ArtistSeriesArtworksTestsQuery.graphql.ts
  src/__generated__/ArtistSeriesArtworks_artistSeries.graphql.ts
  src/__generated__/ArtistSeriesTestsQuery.graphql.ts
  src/__generated__/CollectionArtworksTestsQuery.graphql.ts
  src/__generated__/CollectionArtworks_collection.graphql.ts
  src/__generated__/CollectionTestsQuery.graphql.ts
  src/__generated__/FairAllFollowedArtistsTestsQuery.graphql.ts
  src/__generated__/FairAllFollowedArtists_fairForFilters.graphql.ts
  src/__generated__/FairArtworksTestsQuery.graphql.ts
  src/__generated__/FairArtworks_fair.graphql.ts
  src/__generated__/FairTestsQuery.graphql.ts
  src/__generated__/FilterModalTestsQuery.graphql.ts
  src/__generated__/Filters_filteredArtworks.graphql.ts
  src/__generated__/Gene_gene.graphql.ts
  src/__generated__/ShowArtworksTestsQuery.graphql.ts
  src/__generated__/ShowArtworks_show.graphql.ts
  src/__generated__/ShowTestsQuery.graphql.ts
Labels: Merge On Green

#4392 update release notes for 6.7.7
  fastlane/metadata/en-US/release_notes.txt
Labels: Squash On Green

#4393 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4361 Integrate offer checkout flow into inquiry checkout modal
  CHANGELOG.yml
  src/__generated__/MakeOfferModalQuery.graphql.ts
  src/__generated__/MakeOfferModal_artwork.graphql.ts
  src/lib/AppRegistry.tsx
  src/lib/Scenes/Artwork/Components/CommercialButtons/MakeOfferButton.tsx
  src/lib/Scenes/Artwork/Components/CommercialButtons/__tests__/CommercialButtons-tests.tsx
  src/lib/Scenes/Inbox/Components/Conversations/InquiryMakeOfferButton.tsx
  src/lib/Scenes/Inbox/Components/Conversations/MakeOfferModal.tsx
  src/lib/Scenes/Inbox/Screens/Checkout.tsx
  src/lib/navigation/routes.tsx
Labels: Jira Synced

#4399 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4397 chore: use a different text variant for auction result nav title
  src/lib/Scenes/AuctionResult/AuctionResult.tsx
Labels: Jira Synced

#4396 feat: add a loading skeleton for Market Stats
  CHANGELOG.yml
  src/lib/Components/Artist/ArtistInsights/MarketStats.tsx
Labels: Jira Synced

#4395 fix: show correct arrows on MarketStats sale price over estimate
  CHANGELOG.yml
  src/lib/Components/Artist/ArtistInsights/MarketStats.tsx
  src/lib/Components/Artist/ArtistInsights/__tests__/MarketStats-tests.tsx
Labels: Jira Synced

#4403 fix: move separator to market stats module #trivial
  src/lib/Components/Artist/ArtistInsights/ArtistInsights.tsx
  src/lib/Components/Artist/ArtistInsights/MarketStats.tsx
Labels: Jira Synced

#4401 fix: move spacer into modal content #trivial
  src/lib/Components/Artist/ArtistInsights/ArtistInsightsAuctionResults.tsx
  src/lib/Components/Artist/ArtistInsights/MarketStats.tsx
  src/lib/Components/Buttons/InfoButton.tsx
  src/lib/Scenes/AuctionResult/AuctionResult.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkArtistAuctionResults.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkArtistMarket.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkDemandIndex.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkPriceEstimate.tsx
Labels: Jira Synced

#4373 fix: auction result text QA fixes
  src/lib/Components/Lists/AuctionResult.tsx
Labels: Jira Synced

#4406 fix: convert cents to dollars in MarketStats
  CHANGELOG.yml
  src/lib/Components/Artist/ArtistInsights/MarketStats.tsx
Labels: Jira Synced

#4408 fix: remove heritage from the market stats text #trivial
  src/lib/Components/Artist/ArtistInsights/MarketStats.tsx
Labels: Jira Synced, Squash On Green

#4405 chore: prepare for 6.7.8 development
  CHANGELOG.yml
  app.json
Labels: Squash On Green

#4394 chore: market stats tests
  CHANGELOG.yml
  src/lib/Components/Artist/ArtistInsights/ArtistInsights.tsx
  src/lib/Components/Artist/ArtistInsights/MarketStats.tsx
  src/lib/Components/Artist/ArtistInsights/__tests__/MarketStats-tests.tsx
Labels: Jira Synced, Squash On Green

#4411 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4412 Update metaphysics schema
  data/schema.graphql
  src/__generated__/ArtistArtworks_artist.graphql.ts
  src/__generated__/ArtistSeriesArtworksTestsQuery.graphql.ts
  src/__generated__/ArtistSeriesArtworks_artistSeries.graphql.ts
  src/__generated__/ArtistSeriesTestsQuery.graphql.ts
  src/__generated__/CollectionArtworksTestsQuery.graphql.ts
  src/__generated__/CollectionArtworks_collection.graphql.ts
  src/__generated__/CollectionTestsQuery.graphql.ts
  src/__generated__/FairAllFollowedArtistsTestsQuery.graphql.ts
  src/__generated__/FairAllFollowedArtists_fairForFilters.graphql.ts
  src/__generated__/FairArtworksTestsQuery.graphql.ts
  src/__generated__/FairArtworks_fair.graphql.ts
  src/__generated__/FairTestsQuery.graphql.ts
  src/__generated__/FilterModalTestsQuery.graphql.ts
  src/__generated__/Filters_filteredArtworks.graphql.ts
  src/__generated__/Gene_gene.graphql.ts
  src/__generated__/ShowArtworksTestsQuery.graphql.ts
  src/__generated__/ShowArtworks_show.graphql.ts
  src/__generated__/ShowTestsQuery.graphql.ts
Labels: Merge On Green

#4417 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4400 feat(android): Feature flag infra
  .circleci/config.yml
  Artsy.xcodeproj/project.pbxproj
  Artsy/App/ARAppDelegate+Echo.m
  Artsy/App/ARAppDelegate+Emission.h
  Artsy/App/ARAppDelegate+Emission.m
  Artsy/App/ARAppDelegate.m
  Artsy/App/AROptions.h
  Artsy/App/AROptions.m
  Artsy/Categories/Apple/UIViewController+FullScreenLoading.m
  Artsy_Tests/App_Tests/ARAppDelegateEmissionSpec.m
  CHANGELOG.yml
  Podfile
  docs/developing_a_feature.md
  emission/Pod/Classes/EigenCommunications/ARNotificationsManager.h
  emission/Pod/Classes/EigenCommunications/ARNotificationsManager.m
  package.json
  patches/@react-navigation+core+5.15.1.patch
  src/lib/AndroidApp.tsx
  src/lib/AppRegistry.tsx
  src/lib/Components/Artist/ArtistAbout/ArtistAbout.tsx
  src/lib/Components/Artist/ArtistAbout/__tests__/ArtistAbout-tests.tsx
  src/lib/Components/Artist/ArtistAbout/__tests__/ArtistAboutShows-tests.tsx
  src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
  src/lib/Components/ArtsyWebView.tsx
  src/lib/Components/Bidding/Screens/ConfirmBid/index.tsx
  src/lib/Components/Bidding/Screens/__tests__/ConfirmBid-tests.tsx
  src/lib/Components/__tests__/ArtsyWebView-tests.tsx
  src/lib/Containers/Inbox/index.tsx
  src/lib/Containers/__tests__/InboxWrapper-tests.tsx
  src/lib/Scenes/Artist/Artist.tsx
  src/lib/Scenes/Artist/__tests__/Artist-tests.tsx
  src/lib/Scenes/Artwork/Artwork.tsx
  src/lib/Scenes/Artwork/Components/ArtworkDetails.tsx
  src/lib/Scenes/Artwork/Components/CommercialButtons/CommercialButtons.tsx
  src/lib/Scenes/Artwork/Components/CommercialButtons/__tests__/CommercialButtons-tests.tsx
  src/lib/Scenes/Artwork/Components/__tests__/ArtworkDetails-tests.tsx
  src/lib/Scenes/Artwork/__tests__/Artwork-tests.tsx
  src/lib/Scenes/Home/Home.tsx
  src/lib/Scenes/Inbox/Components/Conversations/Composer.tsx
  src/lib/Scenes/Inbox/Components/Conversations/Conversations.tsx
  src/lib/Scenes/Inbox/Components/Conversations/__tests__/Composer-tests.tsx
  src/lib/Scenes/MyProfile/MyProfile.tsx
  src/lib/navigation/__tests__/routes-tests.tsx
  src/lib/navigation/routes.tsx
  src/lib/store/ConfigModel.ts
  src/lib/store/GlobalStore.tsx
  src/lib/store/NativeModel.ts
  src/lib/store/__tests__/ConfigModel-tests.ts
  src/lib/store/features.ts
  src/lib/store/migration.ts
  src/lib/utils/AdminMenu.tsx
  src/lib/utils/AdminMenuWrapper.tsx
  src/setupJest.ts
  yarn.lock
Labels: Jira Synced

#4420 fix: Dedupe currencies on auction result (CX-973)
  CHANGELOG.yml
  Podfile.lock
  src/__generated__/AuctionResultQuery.graphql.ts
  src/lib/Scenes/AuctionResult/AuctionResult.tsx
Labels: Jira Synced

#4422 Update metaphysics schema
  data/schema.graphql
  src/__generated__/myCollectionAddArtworkMutation.graphql.ts
  src/__generated__/myCollectionEditArtworkMutation.graphql.ts
Labels: Merge On Green

#4418 chore: Add money icon for use in inquiry checkout
  src/lib/Scenes/Inbox/Components/Conversations/OfferIcon.tsx
Labels: Jira Synced

#4407 fix: year created design updates #trivial
  src/lib/Components/ArtworkFilterOptions/YearOptions.tsx
  src/lib/Components/ArtworkFilterOptions/__tests__/YearOptions-tests.tsx
  src/lib/Components/CircleWithBorder/CircleWithBorder.tsx
Labels: Jira Synced

#4426 Update metaphysics schema
  src/__generated__/PartnerArtworkTestsQuery.graphql.ts
  src/__generated__/PartnerArtwork_partner.graphql.ts
Labels: Merge On Green

#4424 fixes(small): 4 small things, packaged nicely into one PR
  package.json
  src/lib/AndroidApp.tsx
  src/lib/Components/CreditCardDetails.tsx
  src/lib/Scenes/Artwork/Components/ArtworkTombstone.tsx
Labels: Jira Synced

#4370 feature(share): custom sharesheet and instagram stories sharing, and toast
  Artsy/App_Resources/Artsy-Info.plist
  CHANGELOG.yml
  HACKS.md
  Podfile.lock
  package.json
  patches/react-native-share+5.1.0.patch
  src/lib/AppRegistry.tsx
  src/lib/Components/CustomShareSheet.tsx
  src/lib/Components/LocationMap/index.tsx
  src/lib/Components/Toast/Toast.tsx
  src/lib/Components/Toast/__tests__/Toast-tests.tsx
  src/lib/Components/Toast/toastHook.tsx
  src/lib/Scenes/Artwork/Components/ArtworkActions.tsx
  src/lib/Scenes/Artwork/Components/ArtworkHeader.tsx
  src/lib/Scenes/Artwork/Components/IGStoryViewShot.tsx
  src/lib/Scenes/Artwork/Components/__tests__/ArtworkHeader-tests.tsx
  src/lib/Scenes/BottomTabs/BottomTabs.tsx
  src/lib/Scenes/BottomTabs/BottomTabsNavigator.tsx
  src/lib/Scenes/BottomTabs/__tests__/BottomTabs-tests.tsx
  src/lib/Scenes/Fair/FairArticles.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionArtworkHeader.tsx
  src/lib/Scenes/MyProfile/MyProfilePaymentNewCreditCard.tsx
  src/lib/Scenes/MyProfile/MyProfilePushNotifications.tsx
  src/lib/Scenes/Sale/Components/SaleActiveBids.tsx
  src/lib/Scenes/Sale/Sale.tsx
  src/lib/Scenes/Search/AutosuggestResults.tsx
  src/lib/store/features.ts
  src/lib/tests/renderWithWrappers.tsx
  src/lib/utils/useCanOpenURL.ts
  src/lib/utils/useInterval.ts
  src/lib/utils/usePrevious.ts
  src/palette/elements/Text/Text.tsx
  src/palette/elements/Text/tokens.ts
  src/palette/elements/Touchable/Touchable.tsx
  src/palette/svgs/InstagramAppIcon.tsx
  src/palette/svgs/InstagramIcon.tsx
  src/palette/svgs/LinkIcon.tsx
  src/palette/svgs/MessageIcon.tsx
  src/palette/svgs/MessagesAppIcon.tsx
  src/palette/svgs/MoreIcon.tsx
  src/palette/svgs/PageViewsIcon.tsx
  src/palette/svgs/WhatsAppAppIcon.tsx
  src/palette/svgs/index.tsx
  src/palette/svgs/sf/StarCircleFill.tsx
  src/setupJest.ts
  yarn.lock
Labels: Jira Synced, Squash On Green

#4427 fix: update support email, fix optional bridge param issue
  Artsy/App/ARScreenPresenterModule.m
  CHANGELOG.yml
  src/lib/NativeModules/LegacyNativeModules.tsx
  src/lib/NativeModules/presentEmailComposer.ts
  src/lib/Scenes/MyProfile/MyProfile.tsx
  src/lib/Scenes/PrivacyRequest/PrivacyRequest.tsx
  src/lib/Scenes/PrivacyRequest/__tests__/PrivacyRequest-tests.tsx
  src/setupJest.ts
Labels: Jira Synced

#4428 fix: auction results more QA fixes
  src/lib/Components/Artist/ArtistInsights/ArtistInsightsAuctionResults.tsx
  src/lib/Components/Artist/ArtistInsights/MarketStats.tsx
  src/lib/Components/ArtworkFilterOptions/YearOptions.tsx
  src/lib/Components/ArtworkGrids/FilteredArtworkGridZeroState.tsx
  src/lib/Components/AuctionResult/AuctionResultMidEstimate.tsx
  src/lib/Components/Lists/AuctionResult.tsx
  src/lib/Scenes/ArtistSeries/__tests__/ArtistSeriesArtworks-tests.tsx
  src/lib/Scenes/AuctionResult/AuctionResult.tsx
  src/lib/Scenes/Collection/Screens/__tests__/CollectionArtworks-tests.tsx
  src/lib/Scenes/Fair/__tests__/FairArtworks-tests.tsx
  src/lib/utils/ArtworkFilter/FilterArtworksHelpers.ts
Labels: Jira Synced

#4430 fix: markets stats qa fixes
  CHANGELOG.yml
  src/__generated__/MarketStatsQuery.graphql.ts
  src/lib/Components/Artist/ArtistInsights/MarketStats.tsx
Labels: Jira Synced

#4429 enhancement(analytics): use cohesion
  package.json
  src/__generated__/ArtworkAboveTheFoldQuery.graphql.ts
  src/__generated__/ArtworkHeader_artwork.graphql.ts
  src/__generated__/ArtworkRefetchQuery.graphql.ts
  src/lib/Scenes/Artwork/Components/ArtworkHeader.tsx
  yarn.lock
Labels: Jira Synced, Squash On Green

#4432 feat: fix screen tracking on auction results
  package.json
  src/__generated__/ArtistBelowTheFoldQuery.graphql.ts
  src/__generated__/ArtistInsightsAuctionResultsQuery.graphql.ts
  src/__generated__/ArtistInsightsAuctionResultsTestsQuery.graphql.ts
  src/__generated__/ArtistInsightsAuctionResults_artist.graphql.ts
  src/__generated__/ArtistInsightsTestsQuery.graphql.ts
  src/lib/Components/Artist/ArtistInsights/ArtistInsights.tsx
  src/lib/Components/Artist/ArtistInsights/ArtistInsightsAuctionResults.tsx
  src/lib/Components/FilterModal/FilterModal.tsx
  src/lib/Scenes/AuctionResult/AuctionResult.tsx
  yarn.lock
Labels: Jira Synced

#4436 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4437 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4439 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4431 feat: scroll to the top after applying a filter on auction results
  CHANGELOG.yml
  src/lib/Components/Artist/ArtistInsights/ArtistInsights.tsx
  src/lib/Components/Artist/ArtistInsights/ArtistInsightsAuctionResults.tsx
  src/lib/Components/Artist/ArtistInsights/__tests__/ArtistInsightsAuctionResults-tests.tsx
  src/lib/Components/ArtworkFilterOptions/ArtistIDsSaleArtworksOptionsScreen.tsx
  src/lib/Components/ArtworkFilterOptions/MultiSelectCheckOption.tsx
  src/lib/Components/StickyTabPage/StickyTabPageFlatList.tsx
Labels: Jira Synced, Squash On Green

#4441 feat: add fonts to android
  .circleci/config.yml
  .gitignore
  CHANGELOG.yml
  scripts/download-fonts
  scripts/setup-env-for-artsy
Labels: Jira Synced

#4413 enchancement(docs|ci): android beta promotion docs and ci
  CHANGELOG.yml
  Gemfile.lock
  docs/deploy_to_app_store.md
  docs/deploy_to_play_store.md
  fastlane/Fastfile
  fastlane/metadata/android/en-US/changelogs/default.txt
  scripts/promote-beta-to-submission-android
  scripts/promote-beta-to-submission-ios
  scripts/promote-if-playstore-submission-branch
Labels: Jira Synced, Squash On Green

#4442 chore: auction results copy updates #trivial
  src/lib/Components/Artist/ArtistInsights/MarketStats.tsx
Labels: Jira Synced

#4443 chore: update artist insights flag
  CHANGELOG.yml
  src/lib/Components/Artist/ArtistAbout/ArtistAbout.tsx
  src/lib/Components/Artist/ArtistAbout/__tests__/ArtistAbout-tests.tsx
  src/lib/Components/Artist/ArtistAbout/__tests__/ArtistAboutShows-tests.tsx
  src/lib/Scenes/Artist/Artist.tsx
  src/lib/Scenes/Artist/__tests__/Artist-tests.tsx
  src/lib/navigation/routes.tsx
  src/lib/store/features.ts
Labels: Jira Synced, Squash On Green

#4445 enhancement(palette): position (left, top, bottom, right) is the same as space (ml, mx, etc) now, and we added %
  CHANGELOG.yml
  package.json
  src/lib/Components/AuctionResult/AuctionResultMidEstimate.tsx
  src/lib/Scenes/Fair/Components/SimpleTabs.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkDemandIndex.tsx
  src/palette/elements/Box/Box.tsx
  src/palette/elements/Box/__tests__/Box-tests.tsx
  src/palette/elements/Cards/CardTag.tsx
  src/palette/helpers/styled-system/position.ts
  src/palette/helpers/styled-system/space.ts
  src/palette/helpers/styled-system/transforms.ts
  src/palette/helpers/types.ts
  src/palette/svgs/Icon.tsx
  yarn.lock
Labels: Jira Synced, Squash On Green

#4409 fix: Center auction results rows vertically
  src/lib/Scenes/AuctionResult/AuctionResult.tsx
Labels: Jira Synced, Squash On Green

#4448 chore: rename: sentry 'staging' -> 'beta'
  .env.example
  Artsy/App/ARAppDelegate+Analytics.m
  Artsy/App/ARAppDelegate+Emission.m
  fastlane/Fastfile
  src/lib/ErrorReporting.ts
  src/lib/store/GlobalStore.tsx
  src/setupJest.ts
  typings/react-native-config.d.ts
Labels: Squash On Green

#4450 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4438 fix: simplify watched lots refreshing
  CHANGELOG.yml
  src/__generated__/InboxQuery.graphql.ts
  src/__generated__/InboxRefetchQuery.graphql.ts
  src/__generated__/InboxTestsQuery.graphql.ts
  src/__generated__/MyBidsQuery.graphql.ts
  src/__generated__/MyBidsRefetchQuery.graphql.ts
  src/__generated__/MyBidsTestsQuery.graphql.ts
  src/__generated__/MyBids_me.graphql.ts
  src/lib/Scenes/MyBids/MyBids.tsx
Labels: Jira Synced

#4453 chore: remove heritage from auction results info modal #trivial
  src/lib/Components/Artist/ArtistInsights/ArtistInsightsAuctionResults.tsx
Labels: Jira Synced

#4454 fix(android): send email
  CHANGELOG.yml
  src/lib/NativeModules/presentEmailComposer.ts
  src/lib/Scenes/MyProfile/MyProfile.tsx
Labels: Jira Synced

#4456 chore: update market signals copy
  src/lib/Components/Artist/ArtistInsights/MarketStats.tsx
Labels: Jira Synced

#4452 feat: migrate LoadFailureView to typescript
  CHANGELOG.yml
  Gemfile.lock
  emission/Pod/Classes/LoadFailureComponent/ARLoadFailureViewManager.h
  emission/Pod/Classes/LoadFailureComponent/ARLoadFailureViewManager.m
  src/lib/Components/LoadFailureView.tsx
  src/lib/Components/RetryErrorBoundary.tsx
  src/lib/Scenes/Sale/Sale.tsx
  src/lib/Scenes/ViewingRoom/ViewingRoomArtwork.tsx
  src/lib/Scenes/ViewingRoom/ViewingRoomsList.tsx
  src/lib/utils/renderWithPlaceholder.tsx
Labels: Jira Synced

#4460 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4458 fix fast reload
  Gemfile
  Gemfile.lock
  HACKS.md
  patches/relay-compiler+10.0.1.patch
Labels: Squash On Green

#4461 fix: improve bottom tabs dev state management
  CHANGELOG.yml
  src/lib/Scenes/BottomTabs/BottomTabsModel.ts
  src/lib/navigation/useReloadedDevNavigationState.ts
  src/lib/store/GlobalStore.tsx
Labels: Jira Synced

#4435 fix: update consignments photo selection for iOS 14
  CHANGELOG.yml
  src/lib/Components/Photos/AddEditPhotos.tsx
  src/lib/Components/Photos/__tests__/AddEditPhotos_tests.tsx
  src/lib/Scenes/Consignments/Components/ArtworkConsignmentTodo.tsx
  src/lib/Scenes/Consignments/Screens/Overview.tsx
  src/lib/Scenes/Consignments/Screens/__tests__/Overview-local-storage-tests.tsx
  src/lib/Scenes/Consignments/Screens/__tests__/Overview-tests.tsx
  src/lib/Scenes/Consignments/Screens/__tests__/Overview-uploading-tests.tsx
  src/lib/Scenes/Consignments/index.tsx
  src/lib/Scenes/MyCollection/State/MyCollectionArtworkModel.tsx
  src/lib/utils/requestPhotos.ts
Labels: Jira Synced, Squash On Green

#4464 enhancement(sentry): enable release health tracking
  Podfile.lock
  package.json
  src/lib/ErrorReporting.ts
  yarn.lock
Labels: Jira Synced, Squash On Green

#4466 enable release health tracking fixup
  src/lib/ErrorReporting.ts
Labels: Jira Synced

#4468 Update metaphysics schema
  data/schema.graphql
  src/__generated__/ArtistArtworks_artist.graphql.ts
  src/__generated__/ArtistSeriesArtworksTestsQuery.graphql.ts
  src/__generated__/ArtistSeriesArtworks_artistSeries.graphql.ts
  src/__generated__/ArtistSeriesTestsQuery.graphql.ts
  src/__generated__/CollectionArtworksTestsQuery.graphql.ts
  src/__generated__/CollectionArtworks_collection.graphql.ts
  src/__generated__/CollectionTestsQuery.graphql.ts
  src/__generated__/FairAllFollowedArtistsTestsQuery.graphql.ts
  src/__generated__/FairAllFollowedArtists_fairForFilters.graphql.ts
  src/__generated__/FairArtworksTestsQuery.graphql.ts
  src/__generated__/FairArtworks_fair.graphql.ts
  src/__generated__/FairTestsQuery.graphql.ts
  src/__generated__/FilterModalTestsQuery.graphql.ts
  src/__generated__/Filters_filteredArtworks.graphql.ts
  src/__generated__/Gene_gene.graphql.ts
  src/__generated__/PartnerArtworkTestsQuery.graphql.ts
  src/__generated__/PartnerArtwork_partner.graphql.ts
  src/__generated__/ShowArtworksTestsQuery.graphql.ts
  src/__generated__/ShowArtworks_show.graphql.ts
  src/__generated__/ShowTestsQuery.graphql.ts
Labels: Merge On Green

#4469 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4433 Offer status CTA
  CHANGELOG.yml
  src/__generated__/ReviewOfferButtonTestsQuery.graphql.ts
  src/__generated__/ReviewOfferButton_order.graphql.ts
  src/lib/Scenes/Inbox/Components/Conversations/ReviewOfferButton.tsx
  src/lib/Scenes/Inbox/Components/Conversations/__tests__/ReviewOfferButton-tests.tsx
  src/lib/Scenes/Inbox/Components/Conversations/utils/returnButtonMessaging.ts
  src/palette/svgs/AlertCircleFillIcon.tsx
  src/palette/svgs/MoneyFillIcon.tsx
  src/palette/svgs/index.tsx
Labels: Jira Synced

#4472 chore: enable hermes on android
  CHANGELOG.yml
  android/app/build.gradle
Labels: Jira Synced

#4477 fix:use correct time zone for start of bidding on Auction More Info screen
  src/lib/Scenes/SaleInfo/SaleInfo.tsx
Labels: Jira Synced

#4478 fix(ci): make aws install idempotent
  scripts/setup-distribute-linux
Labels: Squash On Green

#4470 feat: allow adding/editing pricePaid in myCollection
  CHANGELOG.yml
  src/__generated__/MyCollectionArtworkFullDetailsQuery.graphql.ts
  src/__generated__/MyCollectionArtworkFullDetailsTestsQuery.graphql.ts
  src/__generated__/MyCollectionArtworkFullDetails_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkInsightsTestsQuery.graphql.ts
  src/__generated__/MyCollectionArtworkListItemTestsQuery.graphql.ts
  src/__generated__/MyCollectionArtworkMetaTestsQuery.graphql.ts
  src/__generated__/MyCollectionArtworkMeta_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkPriceEstimateTestsQuery.graphql.ts
  src/__generated__/MyCollectionArtworkPriceEstimate_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkQuery.graphql.ts
  src/__generated__/MyCollectionArtwork_sharedProps.graphql.ts
  src/__generated__/myCollectionAddArtworkMutation.graphql.ts
  src/__generated__/myCollectionEditArtworkMutation.graphql.ts
  src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkPriceEstimate.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/__tests__/MyCollectionArtworkPriceEstimate-tests.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionArtworkMeta.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/Components/__tests__/MyCollectionArtworkMeta-tests.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkFormModal/MyCollectionArtworkFormModal.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkFormModal/Screens/MyCollectionArtworkFormAdditionalDetails.tsx
  src/lib/Scenes/MyCollection/State/MyCollectionArtworkModel.tsx
  src/lib/Scenes/MyCollection/State/__tests__/MyCollectionArtworkModel-tests.tsx
  src/lib/Scenes/MyCollection/utils/__tests__/cleanArtworkPayload-tests.ts
  src/lib/Scenes/MyCollection/utils/cleanArtworkPayload.ts
Labels: Jira Synced

#4481 Update metaphysics schema
  data/schema.graphql
  src/__generated__/ConfirmBidUpdateUserMutation.graphql.ts
  src/__generated__/RegistrationUpdateUserMutation.graphql.ts
  src/__generated__/updateMyUserProfileMutation.graphql.ts
Labels: Merge On Green

#4474 fix: Android keyboard issues
  CHANGELOG.yml
  android/app/src/main/AndroidManifest.xml
  src/lib/Components/FancyModal/FancyModal.tsx
Labels: Jira Synced

#4483 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4485 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4462 MP query freshness checker prototype
  .circleci/config.yml
  metaphysics-queries-freshness-tests/test-freshness.ts
  package.json
  yarn.lock
Labels: Jira Synced
