Repository artsy/eigen, pull requests merged in 2021-12, with the labels that each got.

#5835 feat: Move home screen separators into modules
  src/lib/Components/Home/ArtistRails/ArtistRail.tsx
  src/lib/Components/LotsByArtistsYouFollowRail/LotsByFollowedArtistsRail.tests.tsx
  src/lib/Components/LotsByArtistsYouFollowRail/LotsByFollowedArtistsRail.tsx
  src/lib/Scenes/Home/Components/ArticlesRail.tsx
  src/lib/Scenes/Home/Components/ArtworkRail.tsx
  src/lib/Scenes/Home/Components/AuctionResultsRail.tsx
  src/lib/Scenes/Home/Components/CollectionsRail.tsx
  src/lib/Scenes/Home/Components/FairsRail.tsx
  src/lib/Scenes/Home/Components/NewWorksForYouRail.tsx
  src/lib/Scenes/Home/Components/SalesRail.tsx
  src/lib/Scenes/Home/Components/ShowsRail.tsx
  src/lib/Scenes/Home/Components/Trove.tsx
  src/lib/Scenes/Home/Home.tsx
  src/lib/Scenes/ViewingRoom/Components/ViewingRoomsHomeRail.tsx
Labels: Jira Synced

#5844 feat(FX-3615): Display artist name as pill in create/edit alert forms
  src/lib/Scenes/SavedSearchAlert/SavedSearchAlertForm.tests.tsx
  src/lib/Scenes/SavedSearchAlert/SavedSearchAlertForm.tsx
  src/lib/Scenes/SavedSearchAlert/helpers.tests.ts
Labels: Jira Synced, Squash On Green

#5852 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#5848 feat: Enable comparable works for auction results
  src/lib/store/config/features.ts
Labels: Jira Synced

#5854 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#5842 fix: Reduce size of fairs and shows header
  src/lib/Components/HeaderArtworksFilter/HeaderArtworksFilter.tsx
  src/lib/Scenes/Show/Show.tsx
Labels: Jira Synced

#5862 fix: failed tests
  src/lib/Scenes/Search/SearchArtworksGrid.tests.tsx
Labels: Squash On Green

#5863 fix: tests for PartnerShows
  src/lib/Scenes/Partner/Components/PartnerShows.tests.tsx
Labels: Squash On Green

#5868 Update metaphysics schema
  data/schema.graphql
  src/__generated__/CreateSavedSearchContentContainerV2Query.graphql.ts
  src/__generated__/CreateSavedSearchContentContainerV2RefetchQuery.graphql.ts
  src/__generated__/SavedSearchButtonQuery.graphql.ts
  src/__generated__/SavedSearchButtonRefetchQuery.graphql.ts
  src/__generated__/SavedSearchButtonTestsQuery.graphql.ts
  src/__generated__/createSavedSearchAlertMutation.graphql.ts
Labels: Merge On Green

#5845 feat(FX-3614): Update visual design of artwork grid filter menu
  src/lib/Components/ArtworkFilter/ArtworkFilter.tsx
  src/lib/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx
  src/lib/Components/ArtworkFilter/FilterModal.tests.tsx
  src/lib/Components/ArtworkFilter/Filters/AdditionalGeneIDsOptions.tests.tsx
  src/lib/Components/ArtworkFilter/Filters/AttributionClassOptions.tests.tsx
  src/lib/Components/ArtworkFilter/Filters/ColorsOptions.tsx
  src/lib/Components/ArtworkFilter/Filters/GalleriesAndInstitutionsOptions.tests.tsx
  src/lib/Components/ArtworkFilter/Filters/LocationCitiesOptions.tests.tsx
  src/lib/Components/ArtworkFilter/Filters/MaterialsTermsOptions.tests.tsx
  src/lib/Components/ArtworkFilter/Filters/MultiSelectCheckOption.tsx
  src/lib/Components/ArtworkFilter/Filters/MultiSelectOption.tsx
  src/lib/Components/ArtworkFilter/Filters/SingleSelectOption.tsx
  src/lib/Components/ArtworkFilter/Filters/TimePeriodOptions.tests.tsx
  src/lib/Components/ArtworkFilter/Filters/WaysToBuyOptions.tests.tsx
  src/lib/Components/ArtworkFilter/Filters/YearOptions.tsx
  src/lib/Components/ArtworkFilter/components/ArtworkFilterApplyButton.tests.tsx
  src/lib/Components/ArtworkFilter/components/ArtworkFilterApplyButton.tsx
  src/lib/Components/ArtworkFilter/components/ArtworkFilterBackHeader.tests.tsx
  src/lib/Components/ArtworkFilter/components/ArtworkFilterBackHeader.tsx
  src/lib/Components/ArtworkFilter/components/ArtworkFilterOptionItem.tests.tsx
  src/lib/Components/ArtworkFilter/components/ArtworkFilterOptionItem.tsx
  src/lib/Components/ArtworkFilter/components/ArtworkFilterOptionsHeader.tests.tsx
  src/lib/Components/ArtworkFilter/components/ArtworkFilterOptionsHeader.tsx
  src/lib/Components/ArtworkFilter/types.ts
  src/lib/Components/Gene/GeneArtworks.tests.tsx
  src/lib/Components/Tag/TagArtworks.tests.tsx
Labels: Jira Synced

#5742 feature(mycollection): add sort and filter in header
  src/__generated__/InfiniteScrollArtworksGrid_myCollectionConnection.graphql.ts
  src/__generated__/MyCollectionPaginationQuery.graphql.ts
  src/__generated__/MyCollectionQuery.graphql.ts
  src/__generated__/MyCollectionTestsQuery.graphql.ts
  src/__generated__/MyCollection_me.graphql.ts
  src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
  src/lib/Components/Artist/ArtistInsights/ArtistInsights.tsx
  src/lib/Components/ArtworkFilter/ArtworkFilterHelpers.ts
  src/lib/Components/ArtworkFilter/ArtworkFilterNavigator.tsx
  src/lib/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx
  src/lib/Components/ArtworkFilter/ArtworkFilterStore.tsx
  src/lib/Components/ArtworkFilter/ArtworkFiltersStore.tests.tsx
  src/lib/Components/ArtworkFilter/FilterModal.tests.tsx
  src/lib/Components/ArtworkFilter/Filters/AdditionalGeneIDsOptions.tsx
  src/lib/Components/ArtworkFilter/Filters/ArtistNationalitiesOptions.tsx
  src/lib/Components/ArtworkFilter/Filters/MaterialsTermsOptions.tsx
  src/lib/Components/ArtworkFilter/Filters/SortOptions.tsx
  src/lib/Components/ArtworkFilter/Filters/WaysToBuyOptions.tsx
  src/lib/Components/ArtworkFilter/index.ts
  src/lib/Components/ArtworkFilter/types.ts
  src/lib/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx
  src/lib/Components/Gene/GeneArtworks.tsx
  src/lib/Components/StickyTabPage/StickyTabPage.tsx
  src/lib/Components/StickyTabPage/StickyTabPageFlatList.tsx
  src/lib/Components/Tag/TagArtworks.tsx
  src/lib/Scenes/ArtistSeries/ArtistSeries.tsx
  src/lib/Scenes/Collection/Components/CollectionArtworksFilter.tsx
  src/lib/Scenes/Fair/Fair.tsx
  src/lib/Scenes/Fair/FairAllFollowedArtists.tsx
  src/lib/Scenes/Map/GlobalMap.tsx
  src/lib/Scenes/MyCollection/MyCollection.tests.tsx
  src/lib/Scenes/MyCollection/MyCollection.tsx
  src/lib/Scenes/Partner/Components/PartnerArtwork.tsx
  src/lib/Scenes/Sale/Sale.tsx
  src/lib/Scenes/Search/SearchArtworksGrid.tsx
  src/lib/Scenes/Show/Components/ShowArtworks.tsx
  src/lib/Scenes/Show/Show.tsx
  src/lib/store/config/features.ts
  src/lib/utils/useAutoCollapsingMeasuredView.tsx
Labels: Jira Synced, Squash On Green

#5858 feat(FX-3613): Add "Create alert" button within Artist screen's artwork grid filter menu
  src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
  src/lib/Components/Artist/ArtistArtworks/CreateSavedSearchModal.tsx
  src/lib/Components/ArtworkFilter/ArtworkFilterNavigator.tsx
  src/lib/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx
  src/lib/Components/ArtworkFilter/FilterModal.tests.tsx
  src/lib/Components/ArtworkFilter/components/ArtworkFilterApplyButton.tests.tsx
  src/lib/Components/ArtworkFilter/components/ArtworkFilterApplyButton.tsx
  src/lib/Scenes/SavedSearchAlert/containers/CreateSavedSearchContentContainerV2.tsx
Labels: Jira Synced, Squash On Green

#5851 Chore: Refactor Add My Collection Artwork form from Modal to Individual Pages
  HACKS.md
  src/lib/AppRegistry.tsx
  src/lib/Components/ArtworkFilter/ArtworkFilterNavigator.tsx
  src/lib/Components/SearchInput.tsx
  src/lib/Scenes/MyCollection/MyCollection.tests.tsx
  src/lib/Scenes/MyCollection/MyCollection.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/Components/ArrowDetails.tests.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/Components/ArrowDetails.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtistAutosuggest.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtistSearchResult.tests.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtistSearchResult.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/Components/Dimensions.tests.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/Components/Dimensions.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/Components/MediumPicker.tests.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/Components/MediumPicker.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/Form/artworkSchema.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/Form/useArtworkForm.tests.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/Form/useArtworkForm.ts
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tests.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormAddPhotos.tests.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormAddPhotos.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormAdditionalDetails.tests.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormAdditionalDetails.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormMain.tests.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormMain.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkFullDetails/MyCollectionArtworkFullDetails.tsx
  src/lib/Scenes/MyCollection/State/MyCollectionArtworkModel.tsx
  src/lib/navigation/navigate.ts
  src/lib/navigation/routes.tsx
  src/lib/store/PropsStore.tests.ts
  src/lib/store/PropsStore.ts
  src/palette/elements/Input/Input.tsx
Labels: Jira Synced

#5878 chore: remove master references in eigen
  .circleci/config.yml
  .github/workflows/beta-android.yml
  .github/workflows/beta-ios-manual.yml
  .github/workflows/beta-ios.yml
  .github/workflows/promote-android.yml
  .github/workflows/promote-ios.yml
  Artsy/View_Controllers/Admin/Networking/ARAdminNetworkModel.h
  Artsy/View_Controllers/Admin/Networking/ARAdminNetworkModel.m
  HACKS.md
  README.md
  docs/deploy_a_hotfix.md
  docs/deploy_to_app_store.md
  docs/deploy_to_play_store.md
  docs/getting_started.md
  docs/preferred_practices.md
  docs/pull_request_template.md
  docs/release_candidate_code_freeze.md
  fastlane/Fastfile
  scripts/changelog/commitChangelog.js
  scripts/generate-cities-objc.js
  scripts/strictness-migration.js
  src/lib/Scenes/Artwork/Components/ImageCarousel/FullScreen/ImageCarouselFullScreen.tsx
  src/lib/relay/middlewares/metaphysicsMiddleware.ts
Labels: Squash On Green

#5884 fix: add missing assets directory
  scripts/build-for-tests-android
Labels: Squash On Green

#5886 chore: store build artifacts on android
  .circleci/config.yml
Labels: Squash On Green

#5885 Update metaphysics schema
  data/schema.graphql
  src/__generated__/addAssetToConsignmentMutation.graphql.ts
Labels: Merge On Green

#5166 feat(CX-1778): Relay query prefetching
  package.json
  src/lib/AndroidApp.tsx
  src/lib/AppRegistry.tsx
  src/lib/Components/AboveTheFoldFlatList.tsx
  src/lib/Components/Home/ArtistRails/ArtistRail.tsx
  src/lib/Components/Home/CardRailFlatList.tsx
  src/lib/Components/PrefetchFlatList.tsx
  src/lib/Containers/Inbox/Inbox.tsx
  src/lib/Containers/WorksForYou.tsx
  src/lib/Scenes/Artist/Artist.tsx
  src/lib/Scenes/Artwork/Artwork.tsx
  src/lib/Scenes/ArtworkAttributionClassFAQ/ArtworkAttributionClassFAQ.tsx
  src/lib/Scenes/ArtworkMedium/ArtworkMedium.tsx
  src/lib/Scenes/BottomTabs/BottomTabs.tsx
  src/lib/Scenes/Fair/FairArticles.tsx
  src/lib/Scenes/Fair/FairBMWArtActivation.tsx
  src/lib/Scenes/Home/Components/ArtworkRail.tsx
  src/lib/Scenes/Home/Components/SalesRail.tsx
  src/lib/Scenes/Home/Components/SmallTileRail.tsx
  src/lib/Scenes/Home/Home.tsx
  src/lib/Scenes/LotsByArtistsYouFollow/LotsByArtistsYouFollow.tsx
  src/lib/Scenes/MyProfile/MyProfile.tsx
  src/lib/Scenes/NewWorksForYou/NewWorksForYou.tsx
  src/lib/Scenes/Sale/Sale.tsx
  src/lib/Scenes/Sales/index.tsx
  src/lib/Scenes/Search/AutosuggestResults.tests.tsx
  src/lib/navigation/routes.tsx
  src/lib/store/config/features.ts
  src/lib/tests/MockRelayRenderer.tsx
  src/lib/tests/setupTestWrapper.tsx
  src/lib/utils/AboveTheFoldQueryRenderer.tsx
  src/lib/utils/experiments.ts
  src/lib/utils/queryPrefetching.ts
  tslint.json
  yarn.lock
Labels: Jira Synced

#5897 fix: bidding flow terms and conditions text invisible
  src/lib/Components/Bidding/Screens/ConfirmBid/index.tsx
  src/palette/elements/Checkbox/Checkbox.tsx
Labels: Squash On Green

#5864 feat(FX-3631): Add animation for the artwork grid filter menu header
  src/lib/Components/AnimatableHeader/AnimatableHeader.tsx
  src/lib/Components/AnimatableHeader/AnimatableHeaderContext.ts
  src/lib/Components/AnimatableHeader/AnimatableHeaderFlatList.tsx
  src/lib/Components/AnimatableHeader/AnimatableHeaderLargeTitle.tsx
  src/lib/Components/AnimatableHeader/AnimatableHeaderProvider.tsx
  src/lib/Components/AnimatableHeader/AnimatableHeaderScrollView.tsx
  src/lib/Components/AnimatableHeader/AnimatableHeaderShadow.tsx
  src/lib/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx
  src/lib/Components/ArtworkFilter/components/ArtworkFilterOptionsHeader.tests.tsx
  src/lib/Components/ArtworkFilter/components/ArtworkFilterOptionsHeader.tsx
Labels: Squash On Green

#5880 chore: update form spec in my collection add artwork
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/Components/Dimensions.tests.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/Components/Dimensions.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/Form/artworkSchema.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tests.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormAddPhotos.tests.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormAddPhotos.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormAdditionalDetails.tests.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormAdditionalDetails.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormMain.tests.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormMain.tsx
  src/lib/Scenes/MyCollection/State/MyCollectionArtworkModel.tests.tsx
  src/lib/Scenes/MyCollection/State/MyCollectionArtworkModel.tsx
  src/lib/Scenes/MyCollection/utils/cleanArtworkPayload.tests.ts
Labels: Squash On Green

#5899 Update metaphysics schema
  data/schema.graphql
  src/__generated__/myCollectionAddArtworkMutation.graphql.ts
  src/__generated__/myCollectionEditArtworkMutation.graphql.ts
Labels: Squash On Green

#5905 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#5713 feat(FX-3493): multiple size options
  src/__generated__/ArtistSeriesQuery.graphql.ts
  src/__generated__/ArtistSeriesTestsQuery.graphql.ts
  src/__generated__/ArtistSeries_artistSeries.graphql.ts
  src/__generated__/CollectionQuery.graphql.ts
  src/__generated__/CollectionTestsQuery.graphql.ts
  src/__generated__/Collection_collection.graphql.ts
  src/__generated__/FairAllFollowedArtistsQuery.graphql.ts
  src/__generated__/FairAllFollowedArtistsTestsQuery.graphql.ts
  src/__generated__/FairAllFollowedArtists_fair.graphql.ts
  src/__generated__/FairQuery.graphql.ts
  src/__generated__/FairTestsQuery.graphql.ts
  src/__generated__/Fair_fair.graphql.ts
  src/__generated__/PartnerQuery.graphql.ts
  src/__generated__/PartnerRefetchQuery.graphql.ts
  src/__generated__/Partner_partner.graphql.ts
  src/__generated__/SavedSearchAlertQuery.graphql.ts
  src/__generated__/SearchCriteriaQuery.graphql.ts
  src/__generated__/ShowQuery.graphql.ts
  src/__generated__/ShowTestsQuery.graphql.ts
  src/__generated__/Show_show.graphql.ts
  src/__generated__/VanityURLEntityQuery.graphql.ts
  src/lib/Components/ArtworkFilter/ArtworkFilterHelpers.ts
  src/lib/Components/ArtworkFilter/ArtworkFilterNavigator.tsx
  src/lib/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx
  src/lib/Components/ArtworkFilter/ArtworkFilterStore.tsx
  src/lib/Components/ArtworkFilter/ArtworkFiltersStore.tests.tsx
  src/lib/Components/ArtworkFilter/FilterArtworksHelpers.tests.tsx
  src/lib/Components/ArtworkFilter/FilterModal.tests.tsx
  src/lib/Components/ArtworkFilter/Filters/CustomSizeInputs.tests.tsx
  src/lib/Components/ArtworkFilter/Filters/CustomSizeInputs.tsx
  src/lib/Components/ArtworkFilter/Filters/MultiSelectOption.tsx
  src/lib/Components/ArtworkFilter/Filters/SizeOptions.tests.tsx
  src/lib/Components/ArtworkFilter/Filters/SizeOptions.tsx
  src/lib/Components/ArtworkFilter/Filters/SizesOptions.tests.tsx
  src/lib/Components/ArtworkFilter/Filters/SizesOptions.tsx
  src/lib/Components/ArtworkFilter/Filters/SizesOptionsScreen.tests.tsx
  src/lib/Components/ArtworkFilter/Filters/SizesOptionsScreen.tsx
  src/lib/Components/ArtworkFilter/Filters/helpers.ts
  src/lib/Components/ArtworkFilter/SavedSearch/constants.ts
  src/lib/Components/ArtworkFilter/SavedSearch/convertersToFilterParams.tests.ts
  src/lib/Components/ArtworkFilter/SavedSearch/convertersToFilterParams.ts
  src/lib/Components/ArtworkFilter/SavedSearch/searchCriteriaHelpers.tests.ts
  src/lib/Components/ArtworkFilter/SavedSearch/types.ts
  src/lib/Components/ArtworkFilter/types.ts
  src/lib/Scenes/Artist/Artist.tsx
  src/lib/Scenes/Artist/SearchCriteria.tests.tsx
  src/lib/Scenes/Artist/SearchCriteria.tsx
  src/lib/Scenes/ArtistSeries/ArtistSeries.tsx
  src/lib/Scenes/Collection/Collection.tsx
  src/lib/Scenes/Collection/Screens/CollectionArtworks.tests.tsx
  src/lib/Scenes/Fair/Fair.tsx
  src/lib/Scenes/Fair/FairAllFollowedArtists.tsx
  src/lib/Scenes/Partner/Partner.tsx
  src/lib/Scenes/SavedSearchAlert/EditSavedSearchAlert.tests.tsx
  src/lib/Scenes/SavedSearchAlert/SavedSearchAlert.tsx
  src/lib/Scenes/SavedSearchAlert/helpers.tests.ts
  src/lib/Scenes/SavedSearchAlert/helpers.ts
  src/lib/Scenes/Show/Show.tsx
Labels: Jira Synced

#5916 Update metaphysics schema
  data/schema.graphql
  src/__generated__/updateSavedSearchAlertMutation.graphql.ts
Labels: Squash On Green

#5912 fix(FX-3658): prevent crashes coming from simple-markdown
  src/lib/Components/ReadMore.tsx
  src/lib/Scenes/Show/Screens/ShowMoreInfo.tsx
  src/palette/elements/EntityHeader/EntityHeader.tsx
Labels: Jira Synced

#5919 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#5922 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#5932 fix: Remove artwork grid padding on artist artwork screen
  src/lib/Components/ArtworkGrids/ArtworksFilterHeader.tsx
  src/lib/Scenes/MyCollection/MyCollection.tsx
Labels: Jira Synced

#5935 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#5937 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#5936 feat: my collection more local filters
  src/__generated__/InfiniteScrollArtworksGrid_myCollectionConnection.graphql.ts
  src/__generated__/MyCollectionArtworkFullDetailsQuery.graphql.ts
  src/__generated__/MyCollectionArtworkFullDetailsTestsQuery.graphql.ts
  src/__generated__/MyCollectionArtworkFullDetails_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkListItemTestsQuery.graphql.ts
  src/__generated__/MyCollectionArtworkQuery.graphql.ts
  src/__generated__/MyCollectionArtwork_sharedProps.graphql.ts
  src/__generated__/MyCollectionPaginationQuery.graphql.ts
  src/__generated__/MyCollectionQuery.graphql.ts
  src/__generated__/MyCollectionTestsQuery.graphql.ts
  src/__generated__/MyCollection_me.graphql.ts
  src/__generated__/myCollectionAddArtworkMutation.graphql.ts
  src/__generated__/myCollectionEditArtworkMutation.graphql.ts
  src/lib/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx
  src/lib/Scenes/MyCollection/MyCollection.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tsx
Labels: Jira Synced, Squash On Green

#5926 feat(FX-3649): Limit Algolia search indexes exposed in app to a specific supported list
  src/__generated__/SearchQuery.graphql.ts
  src/__generated__/SearchRefetchQuery.graphql.ts
  src/__generated__/Search_system.graphql.ts
  src/lib/Scenes/Search/Search.tests.tsx
  src/lib/Scenes/Search/Search.tsx
  src/lib/Scenes/Search/SearchModel.tsx
Labels: Jira Synced

#5902 feat: unify follow buttons
  src/__generated__/ArtworkAboveTheFoldQuery.graphql.ts
  src/__generated__/ArtworkRefetchQuery.graphql.ts
  src/__generated__/ArtworkTombstone_artwork.graphql.ts
  src/__generated__/FollowArtistLinkMutation.graphql.ts
  src/__generated__/FollowArtistLinkTestsErrorQuery.graphql.ts
  src/__generated__/FollowArtistLinkTestsQuery.graphql.ts
  src/__generated__/FollowArtistLink_artist.graphql.ts
  src/lib/Components/Artist/ArtistHeader.tsx
  src/lib/Components/ArtistListItem.tsx
  src/lib/Components/Gene/Header.tsx
  src/lib/Components/Home/ArtistRails/ArtistCard.tsx
  src/lib/Scenes/Artwork/Components/ArtworkTombstone.tsx
  src/lib/Scenes/Artwork/Components/ContextCard.tsx
  src/lib/Scenes/Artwork/Components/FollowArtistLink.tests.tsx
  src/lib/Scenes/Artwork/Components/FollowArtistLink.tsx
  src/lib/Scenes/Artwork/Components/PartnerCard.tsx
  src/lib/Scenes/Onboarding/OnboardingPersonalization/OnboardingPersonalizationArtistListItem.tsx
  src/lib/Scenes/Partner/Components/PartnerFollowButton.tsx
  src/lib/utils/Wrap.tsx
  src/palette/elements/Button/Button.stories.tsx
  src/palette/elements/Button/Button.tsx
  src/palette/elements/Button/FollowButton.tsx
  src/palette/elements/Button/index.tsx
  src/storybook/storyLoader.js
Labels: Jira Synced

#5945 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#5946 Update metaphysics schema
  data/schema.graphql
  src/__generated__/myCollectionAddArtworkMutation.graphql.ts
  src/__generated__/myCollectionEditArtworkMutation.graphql.ts
Labels: Squash On Green

#5914 feat: local image handling
  src/__generated__/myCollectionAddArtworkMutation.graphql.ts
  src/__generated__/myCollectionEditArtworkMutation.graphql.ts
  src/lib/AppRegistry.tsx
  src/lib/Scenes/MyCollection/Components/MyCollectionImageView.tests.tsx
  src/lib/Scenes/MyCollection/Components/MyCollectionImageView.tsx
  src/lib/Scenes/MyCollection/MyCollection.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionArtworkHeader.tests.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionArtworkHeader.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tests.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionImageUtil.tests.ts
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionImageUtil.ts
  src/lib/Scenes/MyCollection/Screens/ArtworkImages/MyCollectionLocalArtworkImages.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkList/MyCollectionArtworkListItem.tests.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkList/MyCollectionArtworkListItem.tsx
  src/lib/Scenes/MyCollection/State/MyCollectionArtworkModel.tsx
  src/lib/Scenes/MyCollection/mutations/myCollectionAddArtwork.ts
  src/lib/Scenes/MyCollection/mutations/myCollectionEditArtwork.ts
  src/lib/Scenes/MyCollection/utils/deletedPhotoIDs.ts
  src/lib/Scenes/MyCollection/utils/deletedPhotos.tests.ts
  src/lib/Scenes/MyCollection/utils/deletedPhotos.ts
  src/lib/Scenes/MyCollection/utils/randomMyCollectionArtwork.ts
  src/lib/Scenes/MyProfile/MyCollectionAndSavedWorks.tests.tsx
  src/lib/Scenes/MyProfile/MyCollectionAndSavedWorks.tsx
  src/lib/Scenes/MyProfile/MyProfileEditFormModal.tsx
  src/lib/navigation/routes.tsx
  src/lib/store/config/features.ts
  src/lib/utils/LocalImageStore.tests.ts
  src/lib/utils/LocalImageStore.ts
  src/lib/utils/requestPhotos.ts
Labels: Jira Synced

#5921 fix: remove unnecessary lineHeight prop in MarketStats.tsx
  src/lib/Components/Artist/ArtistInsights/MarketStats.tsx
Labels: Jira Synced

#5929 fix(CX-2015): change margins (py) for action results, home and auction results screens
  src/lib/Components/Lists/AuctionResultListItem.tsx
  src/lib/Scenes/AuctionResultsForArtistsYouFollow/AuctionResultsForArtistsYouFollow.tsx
  src/lib/Scenes/Home/Components/AuctionResultsRail.tsx
Labels: Jira Synced

#5948 fix(CX-2204): replace Linking.openURL with navigation, terms of service
  src/lib/Scenes/Onboarding/OnboardingCreateAccount/TermsOfServiceCheckbox.tsx
  src/lib/Scenes/Onboarding/OnboardingSocialPick.tsx
Labels: Jira Synced

#5952 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#5951 feat: Update input 'required' indicator
  src/lib/Components/Bidding/Screens/BillingAddress.tsx
  src/lib/Components/Input/Input.tsx
  src/lib/Components/Input/InputTitle.tsx
  src/lib/Scenes/MyProfile/MyProfilePaymentNewCreditCard.tsx
  src/lib/Scenes/SavedAddresses/SavedAddressesForm.tsx
  src/palette/elements/Input/Input.stories.tsx
  src/palette/elements/Input/Input.tsx
  src/palette/elements/Input/InputTitle.tsx
  src/palette/elements/Select/Select.stories.tsx
  src/palette/elements/Select/Select.tests.tsx
  src/palette/elements/Select/Select.tsx
Labels: Jira Synced

#5956 fix: Adjust Select border color
  src/palette/elements/Select/Select.tsx
Labels: Jira Synced, Squash On Green

#5959 feat: remove artwork rails placeholder repetition
  src/lib/Scenes/Home/Home.tsx
Labels: Jira Synced

#5962 chore: Adding tooltip for Select components
  src/palette/elements/Select/Select.stories.tsx
  src/palette/elements/Select/Select.tsx
Labels: Jira Synced

#5961 chore: Adding Rarity field for My Collection Add work form
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/Components/Rarity.tests.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/Components/Rarity.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tests.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormMain.tsx
  src/lib/Scenes/MyCollection/State/MyCollectionArtworkModel.tests.tsx
  src/lib/Scenes/MyCollection/State/MyCollectionArtworkModel.tsx
  src/lib/Scenes/MyCollection/utils/cleanArtworkPayload.tests.ts
  src/lib/utils/artworkRarityClassifications.tests.ts
  src/lib/utils/artworkRarityClassifications.ts
Labels: Jira Synced

#5960 fix: Prevent Profile screen from crashing without local user profile image
  src/lib/Scenes/MyProfile/MyCollectionAndSavedWorks.tsx
Labels: Jira Synced

#5954 feat: Add prefetching to bottom navigation links
  src/lib/AppRegistry.tsx
  src/lib/Containers/Inbox/Inbox.tsx
  src/lib/Scenes/BottomTabs/BottomTabs.tsx
  src/lib/Scenes/Home/Home.tsx
  src/lib/Scenes/Search/Search.tsx
Labels: Jira Synced

#5965 feat: Allow My Collection artworks without image
  src/lib/Scenes/MyCollection/Components/MyCollectionImageView.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/Form/artworkSchema.tsx
Labels: Jira Synced

#5874 feat: Add artwork search to "My Collection" artwork form
  src/__generated__/ArtworkAutosuggestResultsContainerQuery.graphql.ts
  src/__generated__/ArtworkAutosuggestResultsQuery.graphql.ts
  src/__generated__/ArtworkAutosuggestResults_viewer.graphql.ts
  src/__generated__/AutosuggestResultsPaginationQuery.graphql.ts
  src/__generated__/AutosuggestResultsQuery.graphql.ts
  src/__generated__/AutosuggestResults_results.graphql.ts
  src/__generated__/MyCollectionArtworkFormArtworkQuery.graphql.ts
  src/__generated__/MyCollectionArtworkFullDetailsQuery.graphql.ts
  src/__generated__/MyCollectionArtworkFullDetailsTestsQuery.graphql.ts
  src/__generated__/MyCollectionArtworkFullDetails_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkListItemTestsQuery.graphql.ts
  src/__generated__/MyCollectionArtworkQuery.graphql.ts
  src/__generated__/MyCollectionArtwork_sharedProps.graphql.ts
  src/__generated__/myCollectionAddArtworkMutation.graphql.ts
  src/__generated__/myCollectionEditArtworkMutation.graphql.ts
  src/lib/Components/ArtworkGrids/ArtworkGridItem.tsx
  src/lib/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtistAutosuggest.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtistSearchResult.tests.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtistSearchResult.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtworkAutosuggest.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtworkAutosuggestResults.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/Components/Dimensions.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/Components/MediumPicker.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tests.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormArtist.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormArtwork.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormMain.tests.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormMain.tsx
  src/lib/Scenes/MyCollection/State/MyCollectionArtworkModel.tsx
  src/lib/Scenes/Search/AutosuggestResults.tsx
  src/lib/Scenes/Search/components/AutosuggestSearchResult.tsx
Labels: Jira Synced
