Repository artsy/eigen, pull requests merged in 2021-10, with the labels that each got.

#5559 Enhancement: [CX-1938] Patch react-native-credit-card-input
  patches/react-native-credit-card-input+0.4.1.patch
Labels: Jira Synced

#5551 feat(CX-2001): Add new works for you screen
  package.json
  src/__generated__/NewWorksForYouQuery.graphql.ts
  src/__generated__/NewWorksForYouRefetchQuery.graphql.ts
  src/__generated__/NewWorksForYouTestsQuery.graphql.ts
  src/__generated__/NewWorksForYou_me.graphql.ts
  src/lib/AppRegistry.tsx
  src/lib/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx
  src/lib/Containers/WorksForYou.tsx
  src/lib/Scenes/Home/Components/NewWorksForYouRail.tsx
  src/lib/Scenes/LotsByArtistsYouFollow/LotsByArtistsYouFollow.tsx
  src/lib/Scenes/NewWorksForYou/NewWorksForYou.tsx
  src/lib/Scenes/NewWorksForYou/__tests__/NewWorksForYou-tests.tsx
  src/lib/navigation/routes.tsx
  src/lib/store/config/features.ts
  yarn.lock
Labels: Jira Synced, Squash On Green

#5523 fix(PURCHASE-2833): overlapping text on lot statuses
  src/lib/Scenes/MyBids/Components/ActiveLotStanding.tsx
  src/lib/Scenes/MyBids/Components/ClosedLotStanding.tsx
  src/lib/Scenes/MyBids/Components/Lot.tsx
  src/lib/Scenes/MyBids/Components/WatchedLot.tsx
  src/lib/Scenes/Sale/Components/SaleActiveBidItem.tsx
Labels: Jira Synced

#5570 fix(FX-3414): update behaviour for search button
  src/lib/Scenes/Search2/Search2.tsx
  src/lib/Scenes/Search2/__tests__/Search2-tests.tsx
Labels: Jira Synced

#5544 feat: Artist's Articles in My Collection
  src/__generated__/ArtistArticlesQuery.graphql.ts
  src/__generated__/ArtistArticlesResultQuery.graphql.ts
  src/__generated__/ArtistArticlesTestsQuery.graphql.ts
  src/__generated__/ArtistArticles_artist.graphql.ts
  src/__generated__/MyCollectionArtworkArtistArticlesTestsQuery.graphql.ts
  src/__generated__/MyCollectionArtworkArtistArticles_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkInsightsTestsQuery.graphql.ts
  src/__generated__/MyCollectionArtworkQuery.graphql.ts
  src/lib/AppRegistry.tsx
  src/lib/Scenes/Articles/Articles.tsx
  src/lib/Scenes/Articles/ArticlesList.tsx
  src/lib/Scenes/ArtistArticles/ArtistArticles.tsx
  src/lib/Scenes/ArtistArticles/__tests__/ArtistArticles-tests.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkArtistArticles.tsx
  src/lib/navigation/routes.tsx
Labels: Jira Synced

#5573 fix(FX-3408): set collapsable to false for parent container
  src/lib/Scenes/Search2/Search2.tsx
Labels: Jira Synced, Squash On Green

#5574 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#5567 chore(FX-3414): Update tests for pills
  src/lib/Scenes/Search2/__tests__/Search2-tests.tsx
Labels: Jira Synced

#5562 Enhancement(CX-894): Fix Image view goes off screen / too tall in My Collection Artworks
  src/lib/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionArtworkHeader.tsx
Labels: Jira Synced

#5578 fix(button): fix button layout for icons and hidden text
  src/lib/Scenes/Artwork/Components/IGStoryViewShot.tsx
  src/lib/Scenes/Onboarding/OnboardingSocialPick.tsx
  src/lib/utils/MeasuredView.tsx
  src/lib/utils/useOffscreenStyle.ts
  src/palette/elements/Button/Button.stories.tsx
  src/palette/elements/Button/Button.tsx
  src/palette/svgs/LinkIcon.tsx
  src/storybook/decorators.tsx
Labels: Jira Synced

#5557 fix(FX-3278): keep the "show alerts" button disabled when the user selects the same custom price again
  src/lib/Components/ArtworkFilter/ArtworkFilterStore.tsx
  src/lib/Components/ArtworkFilter/Filters/SizeOptions.tsx
  src/lib/Components/ArtworkFilter/__tests__/ArtworkFiltersStore-tests.tsx
Labels: Jira Synced

#5581 fix: Adjust Viewing Rooms screen header
  src/lib/Scenes/ViewingRoom/ViewingRoomsList.tsx
Labels: Jira Synced

#5385 Fix: Phone number doesn't populate field on edit
  CHANGELOG.legacy.yml
  Podfile.lock
  src/__generated__/SavedAddressesFormQuery.graphql.ts
  src/__generated__/SavedAddressesFormTestsQuery.graphql.ts
  src/__generated__/SavedAddressesForm_me.graphql.ts
  src/lib/Components/PhoneInput/PhoneInput.tsx
  src/lib/Scenes/Consignments/Screens/__tests__/ConfirmContactInfo-tests.tsx
  src/lib/Scenes/SavedAddresses/SavedAddressesForm.tsx
Labels: Jira Synced

#5580 fix(FX-3324): broken analytics on artworks grid
  src/lib/Scenes/Search2/SearchArtworksGrid.tsx
Labels: Jira Synced

#5584 fix(PURCHASE-2670): Don't show the date is not present
  src/lib/Scenes/Artwork/Components/CommercialButtons/CollapsibleArtworkDetails.tsx
Labels: Jira Synced

#5587 feat: dependabot configuration for security updates
  .github/dependabot.yml
Labels: Jira Synced

#5732 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green
