Repository artsy/eigen, pull requests merged in 2021-11, with the labels that each got.

#5733 fix(CX-2122): fix broken ref handling
  src/lib/Components/SearchInput.tsx
Labels: Jira Synced

#5670 fix(CX-2087): improve logic of showing auction results
  src/__generated__/ArtistAboveTheFoldQuery.graphql.ts
  src/__generated__/AutosuggestResultsPaginationQuery.graphql.ts
  src/__generated__/AutosuggestResultsQuery.graphql.ts
  src/__generated__/AutosuggestResults_results.graphql.ts
  src/lib/Scenes/Artist/Artist.tests.tsx
  src/lib/Scenes/Artist/Artist.tsx
  src/lib/Scenes/Search/AutosuggestResults.tsx
  src/lib/Scenes/Search/AutosuggestSearchResult.tsx
  src/lib/Scenes/Search/AutosuggestedSearchResult.tests.tsx
Labels: Jira Synced, Squash On Green

#5729 feat: implement A/B testing with New works rails
  src/lib/AndroidApp.tsx
  src/lib/AppRegistry.tsx
  src/lib/Scenes/Home/Home.tsx
  src/lib/store/config/features.ts
Labels: Jira Synced

#5734 feat(FX-3507): Artworks text styling to Palette V3
  src/lib/Components/ArtworkGrids/ArtworkGridItem.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkList/MyCollectionArtworkListItem.tsx
Labels: Jira Synced

#5740 Update metaphysics schema
  data/schema.graphql
  src/__generated__/ConfirmBidUpdateUserMutation.graphql.ts
  src/__generated__/RegistrationUpdateUserMutation.graphql.ts
  src/__generated__/updateMyUserProfileMutation.graphql.ts
Labels: Merge On Green

#5739 feat: Update Android Target SDK to 30
  android/app/build.gradle
  android/build.gradle
Labels: Jira Synced

#5735 refactor(CX-1937): Change multi select filters to the right component
  src/lib/Components/ArtworkFilter/Filters/AuctionHouseOptions.tests.tsx
  src/lib/Components/ArtworkFilter/Filters/AuctionHouseOptions.tsx
  src/lib/Components/ArtworkFilter/Filters/CategoriesOptions.tests.tsx
  src/lib/Components/ArtworkFilter/Filters/CategoriesOptions.tsx
  src/lib/Components/ArtworkFilter/Filters/SizesOptions.tests.tsx
  src/lib/Components/ArtworkFilter/Filters/SizesOptions.tsx
Labels: Jira Synced

#5743 chore(FX-3523): copy change filter on searchableartworkgrid
  src/lib/Components/ArtworkGrids/FilterHeader2.tests.tsx
  src/lib/Components/ArtworkGrids/FilterHeader2.tsx
  src/lib/Scenes/Search2/SearchArtworksGrid.tsx
Labels: Jira Synced, Squash On Green

#5720 feat(FX-3503): Hide search pills with no results
  src/lib/Scenes/Search2/Search2.tests.tsx
  src/lib/Scenes/Search2/Search2.tsx
  src/lib/store/config/features.ts
  src/lib/utils/useAlgoliaIndices.ts
Labels: Jira Synced

#5737 fix(FX-3512): Search results analytics tracking issues
  src/__generated__/SearchArtworksGridTestsQuery.graphql.ts
  src/lib/Scenes/Search2/Search2.tests.tsx
  src/lib/Scenes/Search2/Search2.tsx
  src/lib/Scenes/Search2/SearchArtworksGrid.tests.tsx
  src/lib/Scenes/Search2/SearchArtworksGrid.tsx
Labels: Jira Synced

#5746 Bugfix: fix failing test
  src/lib/Scenes/Search2/SearchArtworksGrid.tests.tsx
Labels: Squash On Green

#5744 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#5747 feat(FX-3526): enable the Sort By option for the Artworks pill when feature flag is enabled
  src/lib/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx
  src/lib/Scenes/Search2/SearchArtworksGrid.tests.tsx
  src/lib/Scenes/Search2/SearchArtworksGrid.tsx
  src/lib/store/config/features.ts
Labels: Jira Synced, Squash On Green

#5754 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#5755 fix: Input with limit
  src/palette/elements/Input/Input.stories.tsx
  src/palette/elements/Input/Input.tsx
Labels: Squash On Green

#5750 feat: Put My Collection order import behind feature flag
  src/__generated__/MyCollectionPaginationQuery.graphql.ts
  src/__generated__/MyCollectionQuery.graphql.ts
  src/__generated__/MyCollectionTestsQuery.graphql.ts
  src/__generated__/MyCollection_me.graphql.ts
  src/lib/Scenes/MyCollection/MyCollection.tsx
  src/lib/Scenes/Search2/SearchArtworksGrid.tsx
  src/lib/store/config/features.ts
Labels: Jira Synced

#5748 chore(CX-2146): update prompt for review logic and add tracking
  src/lib/Components/Artist/ArtistHeader.tsx
  src/lib/NativeModules/Events.tsx
  src/lib/Scenes/Artwork/Components/ArtworkActions.tsx
  src/lib/utils/userHadMeaningfulInteraction.tsx
  src/setupJest.ts
Labels: Jira Synced

#5759 fix: Remove margin right from limit of Input components
  src/palette/elements/Input/Input.tsx
Labels: Squash On Green

#5761 fix: search2 skeleton alignment
  src/lib/Scenes/Search2/components/SearchPlaceholder.tsx
Labels: Jira Synced, Squash On Green

#5764 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#5763 Feat: add new works banner to my collection screen
  src/__generated__/MyCollectionPaginationQuery.graphql.ts
  src/__generated__/MyCollectionQuery.graphql.ts
  src/__generated__/MyCollectionTestsQuery.graphql.ts
  src/__generated__/MyCollection_me.graphql.ts
  src/lib/Scenes/MyCollection/MyCollection.tsx
  src/palette/elements/Banner/Banner.stories.tsx
  src/palette/elements/Banner/Banner.tests.tsx
  src/palette/elements/Banner/Banner.tsx
  src/palette/elements/Banner/index.tsx
  src/palette/elements/index.tsx
  src/storybook/storyLoader.js
Labels: Jira Synced

#5758 chore(CX-2148): hide description from auction results
  src/__generated__/AuctionResultQuery.graphql.ts
  src/lib/Scenes/AuctionResult/AuctionResult.tsx
Labels: Jira Synced

#5768 fix: address review comments on SplitIO
  src/lib/Components/OpaqueImageView/createGeminiUrl.tsx
  src/lib/Scenes/Home/Home.tsx
  src/lib/store/config/ExperimentsModel.ts
  src/lib/store/migration.tests.ts
  src/lib/store/migration.ts
  src/lib/utils/AdminMenu.tsx
  src/lib/utils/useExperiments.ts
Labels: Squash On Green

#5772 fix: update telemetry dep to fix mapbox rn crash
  android/app/build.gradle
Labels: Jira Synced

#5779 fix: split io env + feature flags
  .env.example
  src/lib/Scenes/Home/Components/ArtworkRail.tsx
  src/lib/Scenes/Home/Home.tsx
Labels: Squash On Green

#5773 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#5775 chore(FX-3568): Search Cleanup
  src/__generated__/SearchQuery.graphql.ts
  src/__generated__/SearchRefetchQuery.graphql.ts
  src/__generated__/Search_system.graphql.ts
  src/lib/AppRegistry.tsx
  src/lib/Scenes/BottomTabs/BottomTabsNavigator.tsx
  src/lib/Scenes/Search/AutosuggestResults.tests.tsx
  src/lib/Scenes/Search/AutosuggestResults.tsx
  src/lib/Scenes/Search/RecentSearches.tests.tsx
  src/lib/Scenes/Search/RecentSearches.tsx
  src/lib/Scenes/Search/RefetchWhenApiKeyExpired.tsx
  src/lib/Scenes/Search/Search.tests.tsx
  src/lib/Scenes/Search/Search.tsx
  src/lib/Scenes/Search/SearchArtworksContainer.tests.tsx
  src/lib/Scenes/Search/SearchArtworksContainer.tsx
  src/lib/Scenes/Search/SearchArtworksGrid.tests.tsx
  src/lib/Scenes/Search/SearchArtworksGrid.tsx
  src/lib/Scenes/Search/SearchResults.tsx
  src/lib/Scenes/Search/components/AutosuggestSearchResult.tests.tsx
  src/lib/Scenes/Search/components/AutosuggestSearchResult.tsx
  src/lib/Scenes/Search/components/CityGuideCTA.tests.tsx
  src/lib/Scenes/Search/components/CityGuideCTA.tsx
  src/lib/Scenes/Search/components/ResultWithHighlight.tsx
  src/lib/Scenes/Search/components/SearchHighlight.tsx
  src/lib/Scenes/Search/components/SearchInput.tests.tsx
  src/lib/Scenes/Search/components/SearchInput.tsx
  src/lib/Scenes/Search/components/SearchPills.tests.tsx
  src/lib/Scenes/Search/components/SearchPills.tsx
  src/lib/Scenes/Search/components/SearchResult.tests.tsx
  src/lib/Scenes/Search/components/SearchResult.tsx
  src/lib/Scenes/Search/components/SearchResultImage.tsx
  src/lib/Scenes/Search/components/SearchResultList.tsx
  src/lib/Scenes/Search/components/placeholders/AlgoliaSearchPlaceholder.tsx
  src/lib/Scenes/Search/components/placeholders/AutosuggestResultsPlaceholder.tsx
  src/lib/Scenes/Search/components/placeholders/SearchArtworksGridPlaceholder.tsx
  src/lib/Scenes/Search/components/placeholders/SearchPlaceholder.tsx
  src/lib/Scenes/Search/helpers-tests.tsx
  src/lib/Scenes/Search/helpers.ts
  src/lib/Scenes/Search/types.ts
  src/lib/Scenes/Search2/Search2.tests.tsx
  src/lib/Scenes/Search2/Search2.tsx
  src/lib/Scenes/SearchSwitchContainer/index.tsx
  src/lib/navigation/routes.tests.tsx
  src/lib/navigation/routes.tsx
  src/lib/store/config/features.ts
Labels: Jira Synced

#5780 fix: issue with image profile upload
  src/lib/Scenes/MyProfile/MyCollectionAndSavedWorks.tsx
  src/lib/Scenes/MyProfile/MyProfileEditFormModal.tsx
Labels: Squash On Green

#5781 feat(FX-3577): Remove push notifs copy from create alert screen
  src/lib/Scenes/SavedSearchAlert/CreateSavedSearchAlert.tests.tsx
  src/lib/Scenes/SavedSearchAlert/CreateSavedSearchAlert.tsx
Labels: Jira Synced

#5752 feat(FX-3521): Disable search pills
  src/lib/Scenes/SavedSearchAlert/Components/Form.tsx
  src/lib/Scenes/Search/Search.tests.tsx
  src/lib/Scenes/Search/Search.tsx
  src/lib/Scenes/Search/components/SearchPills.tests.tsx
  src/lib/Scenes/Search/components/SearchPills.tsx
  src/lib/Scenes/Search/types.ts
  src/lib/utils/useAlgoliaIndices.ts
  src/palette/elements/Pill/Pill.stories.tsx
  src/palette/elements/Pill/Pill.tsx
Labels: Jira Synced

#5784 fix(push notifs): asking for permission with new onboarding
  src/lib/Scenes/Onboarding/OnboardingPersonalization/OnboardingPersonalization.tests.tsx
  src/lib/Scenes/Onboarding/OnboardingPersonalization/OnboardingPersonalization.tsx
  src/lib/store/AuthModel.ts
  src/lib/tests/flushPromiseQueue.ts
Labels: Squash On Green

#5787 fix: prompt for push for users with no onboarding state #trivial
  src/lib/store/AuthModel.ts
Labels: Squash On Green

#5788 fix(analytics): add types and missing slug
  src/__generated__/ArtworkAboveTheFoldQuery.graphql.ts
  src/__generated__/ArtworkRefetchQuery.graphql.ts
  src/__generated__/BuyNowButton_artwork.graphql.ts
  src/__generated__/CommercialButtonsTestsMutationQuery.graphql.ts
  src/__generated__/CommercialButtonsTestsRenderQuery.graphql.ts
  src/lib/Scenes/Artwork/Components/CommercialButtons/BuyNowButton.tsx
  src/lib/Scenes/Artwork/Components/CommercialButtons/MakeOfferButton.tsx
  src/lib/utils/track/schema.ts
Labels: Jira Synced

#5794 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#5722 [SWA-43] Migrate the edition size field in Convection to a string
  src/lib/Scenes/Consignments/Submission/consignmentSetupToSubmission.ts
Labels: Jira Synced

#5795 Prep for v7.1.2
  app.json
Labels: Squash On Green

#5796 fix(FX-3587): Multi select option checkbox
  src/lib/Components/ArtworkFilter/Filters/MultiSelectOption.tsx
  src/palette/elements/Checkbox/Check.tsx
Labels: Jira Synced

#5797 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#5745 refactor(filters): remove old filter header
  src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
  src/lib/Components/ArtworkGrids/ArtworksFilterHeader.stories.tsx
  src/lib/Components/ArtworkGrids/ArtworksFilterHeader.tests.tsx
  src/lib/Components/ArtworkGrids/ArtworksFilterHeader.tsx
  src/lib/Components/ArtworkGrids/FilterHeader.tests.tsx
  src/lib/Components/ArtworkGrids/FilterHeader.tsx
  src/lib/Components/ArtworkGrids/FilterHeader2.tsx
  src/lib/Components/Gene/About.tsx
  src/lib/Components/Gene/GeneArtworks.tests.tsx
  src/lib/Components/Gene/GeneArtworks.tsx
  src/lib/Components/Photos/AddEditPhotos.tsx
  src/lib/Components/Separator.tests.tsx
  src/lib/Components/Separator.tsx
  src/lib/Components/Tag/TagArtworks.tests.tsx
  src/lib/Components/Tag/TagArtworks.tsx
  src/lib/Scenes/ArtistSeries/ArtistSeries.tests.tsx
  src/lib/Scenes/ArtistSeries/ArtistSeries.tsx
  src/lib/Scenes/ArtistSeries/ArtistSeriesFilterHeader.tests.tsx
  src/lib/Scenes/ArtistSeries/ArtistSeriesFilterHeaders.tsx
  src/lib/Scenes/Search/SearchArtworksGrid.tsx
  src/palette/elements/Tabs/Tabs.stories.tsx
  src/storybook/storyLoader.js
  src/storybook/storybook-ui.js
Labels: Jira Synced

#5803 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#5736 feat(FX-3488): Notify user that they are opting back into email
  src/__generated__/SavedSearchAlertQuery.graphql.ts
  src/__generated__/SavedSearchButtonQuery.graphql.ts
  src/__generated__/SavedSearchButtonRefetchQuery.graphql.ts
  src/__generated__/SavedSearchButtonTestsQuery.graphql.ts
  src/__generated__/SavedSearchButton_me.graphql.ts
  src/__generated__/updateEmailFrequencyMutation.graphql.ts
  src/lib/Components/Artist/ArtistArtworks/SavedSearchButton.tsx
  src/lib/Scenes/SavedSearchAlert/CreateSavedSearchAlert.tests.tsx
  src/lib/Scenes/SavedSearchAlert/CreateSavedSearchAlert.tsx
  src/lib/Scenes/SavedSearchAlert/EditSavedSearchAlert.tests.tsx
  src/lib/Scenes/SavedSearchAlert/EditSavedSearchAlert.tsx
  src/lib/Scenes/SavedSearchAlert/SavedSearchAlert.tsx
  src/lib/Scenes/SavedSearchAlert/SavedSearchAlertForm.tests.tsx
  src/lib/Scenes/SavedSearchAlert/SavedSearchAlertForm.tsx
  src/lib/Scenes/SavedSearchAlert/mutations/updateEmailFrequency.ts
Labels: Jira Synced

#5809 Update metaphysics schema
  data/schema.graphql
  src/__generated__/createConsignmentSubmissionMutation.graphql.ts
  src/__generated__/updateConsignmentSubmissionMutation.graphql.ts
Labels: Merge On Green

#5812 Update metaphysics schema
  data/schema.graphql
  src/__generated__/createConsignmentSubmissionMutation.graphql.ts
  src/__generated__/updateConsignmentSubmissionMutation.graphql.ts
Labels: Merge On Green

#5802 chore: upgrade mapbox
  Artsy/App_Resources/Artsy-Info.plist
  Gemfile.lock
  HACKS.md
  Podfile
  Podfile.lock
  android/app/build.gradle
  package.json
  patches/@react-native-mapbox-gl+maps+8.2.0-beta2.patch
  patches/@react-native-mapbox-gl+maps+8.4.0.patch
  src/lib/Components/Lists/ShowItemRow.tsx
  src/lib/Components/LocationMap/LocationMap.tests.tsx
  src/lib/Components/LocationMap/LocationMap.tsx
  src/lib/Scenes/Fair/FairMoreInfo.tests.tsx
  src/lib/Scenes/Fair/FairMoreInfo.tsx
  src/lib/Scenes/Map/Components/ShowCard.tsx
  src/lib/Scenes/Map/GlobalMap.tsx
  src/lib/Scenes/Map/exhibitionPeriodParser.ts
  src/lib/Scenes/Partner/Components/PartnerMap.tsx
  src/lib/Scenes/Show/Components/ShowLocation.tsx
  yarn.lock
Labels: Jira Synced

#5808 fix: cut off empty states on saves pages #trivial
  src/lib/Scenes/Favorites/FavoriteArtists.tsx
  src/lib/Scenes/Favorites/FavoriteCategories.tsx
  src/lib/Scenes/Favorites/FavoriteShows.tsx
Labels: Jira Synced, Squash On Green

#5811 fix(tooling): make fonts work for everyone at artsy
  .gitignore
  Podfile
  Podfile.lock
  docs/getting_started.md
  docs/troubleshooting.md
  package.json
  scripts/download-fonts
  scripts/flip-table
  scripts/install
  scripts/post-pod-install.rb
Labels: Squash On Green

#5814 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#5816 fix(FX-3599): useRawURL of images that come from articles algolia
  src/lib/Scenes/Search/components/SearchResultImage.tsx
Labels: Jira Synced

#5817 fix: My Collection Additional Details form value bug
  src/lib/Scenes/MyCollection/Screens/ArtworkFormModal/Screens/MyCollectionArtworkFormAdditionalDetails.tsx
Labels: Jira Synced

#5824 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#5818 fix: Reusing 'SaleArtworksHomeRailContainer' rail
  src/__generated__/HomeAboveTheFoldQuery.graphql.ts
  src/__generated__/HomeRefetchQuery.graphql.ts
  src/__generated__/Home_meAbove.graphql.ts
  src/__generated__/LotsByFollowedArtistsQuery.graphql.ts
  src/__generated__/LotsByFollowedArtistsRailQuery.graphql.ts
  src/__generated__/LotsByFollowedArtistsRailTestsQuery.graphql.ts
  src/__generated__/LotsByFollowedArtistsRail_me.graphql.ts
  src/__generated__/LotsByFollowedArtists_me.graphql.ts
  src/__generated__/SalesQuery.graphql.ts
  src/__generated__/SalesQueryRendererQuery.graphql.ts
  src/__generated__/Sales_me.graphql.ts
  src/lib/Components/LotsByArtistsYouFollowRail/LotsByFollowedArtistsRail.tests.tsx
  src/lib/Components/LotsByArtistsYouFollowRail/LotsByFollowedArtistsRail.tsx
  src/lib/Scenes/Home/Home.tsx
  src/lib/Scenes/Sales/Components/LotsByFollowedArtists.tests.tsx
  src/lib/Scenes/Sales/Components/LotsByFollowedArtists.tsx
  src/lib/Scenes/Sales/index.tests.tsx
  src/lib/Scenes/Sales/index.tsx
Labels: Jira Synced, Squash On Green

#5805 fix(FX-3586): Keep recent searches if log in to the same account
  .secrets.baseline
  src/lib/Scenes/Search/SearchModel.tsx
  src/lib/store/AuthModel.tests.ts
  src/lib/store/AuthModel.ts
  src/lib/store/GlobalStoreModel.tests.ts
  src/lib/store/GlobalStoreModel.ts
  src/lib/store/migration.tests.ts
  src/lib/store/migration.ts
Labels: Jira Synced

#5826 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#5829 Update metaphysics schema
  data/schema.graphql
  src/__generated__/addAssetToConsignmentMutation.graphql.ts
Labels: Merge On Green

#5831 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#5832 chore: Remove AREnableAuctionResultsKeywordFilter feature flag
  src/lib/Components/Artist/ArtistInsights/ArtistInsightsAuctionResults.tsx
  src/lib/store/config/features.ts
Labels: Jira Synced

#5836 other: marked AREnableSavedSearchToggles ready for release
  src/lib/store/config/features.ts
Labels: Jira Synced

#5800 feat(FX-3576): Create link for user to view/update email preferences
  src/__generated__/CreateSavedSearchAlertScreenRefetchQuery.graphql.ts
  src/__generated__/CreateSavedSearchAlertScreen_me.graphql.ts
  src/__generated__/CreateSavedSearchAlertTestsQuery.graphql.ts
  src/__generated__/SavedSearchButtonQuery.graphql.ts
  src/__generated__/SavedSearchButtonRefetchQuery.graphql.ts
  src/__generated__/SavedSearchButtonTestsQuery.graphql.ts
  src/__generated__/SavedSearchButton_me.graphql.ts
  src/lib/Components/Artist/ArtistArtworks/SavedSearchButton.tests.tsx
  src/lib/Components/Artist/ArtistArtworks/SavedSearchButton.tsx
  src/lib/Scenes/SavedSearchAlert/Components/Form.tsx
  src/lib/Scenes/SavedSearchAlert/CreateSavedSearchAlert.tests.tsx
  src/lib/Scenes/SavedSearchAlert/CreateSavedSearchAlert.tsx
  src/lib/Scenes/SavedSearchAlert/EditSavedSearchAlert.tsx
  src/lib/Scenes/SavedSearchAlert/SavedSearchAlertForm.tests.tsx
  src/lib/Scenes/SavedSearchAlert/SavedSearchAlertForm.tsx
  src/lib/Scenes/SavedSearchAlert/SavedSearchAlertModel.ts
  src/lib/Scenes/SavedSearchAlert/screens/CreateSavedSearchAlertScreen.tsx
  src/lib/Scenes/SavedSearchAlert/screens/EmailPreferencesScreen.tsx
  src/lib/navigation/routes.tests.tsx
  src/lib/navigation/routes.tsx
Labels: Jira Synced
