Repository artsy/eigen, pull requests merged in 2021-07, with the labels that each got.

#5069 fix: Order History: "Unable to load" page is opened (exception occurs) when artwork is deleted/unpublished from order (PX-4253)
  CHANGELOG.yml
  src/__generated__/OrderDetailsQuery.graphql.ts
  src/__generated__/OrderHistoryQuery.graphql.ts
  src/lib/Scenes/OrderHistory/OrderDetails/Components/OrderDetails.tsx
  src/lib/Scenes/OrderHistory/OrderHistory.tsx
Labels: Jira Synced

#5073 fix(CX-1658): empty search in artist field for consignment submissions
  CHANGELOG.yml
  src/lib/Scenes/Consignments/Screens/ConsignmentsArtist.tsx
Labels: Jira Synced, Squash On Green

#5070 feat: (PURCHASE-2800) Feature flag for saved addresses
  CHANGELOG.yml
  src/lib/Scenes/MyProfile/MyProfile.tsx
  src/lib/store/config/features.ts
Labels: Merge On Green

#5076 add analytics for auction results for artists you flow
  CHANGELOG.yml
  package.json
  src/lib/Scenes/AuctionResultsForYou/AuctionResultsForYou.tsx
  src/lib/Scenes/Home/Components/AuctionResultsRail.tsx
  yarn.lock
Labels: Jira Synced, Squash On Green

#5063 feat: Prevent users from submit consignments for non target supply artists
  CHANGELOG.yml
  src/__generated__/ConsignmentsArtistQuery.graphql.ts
  src/lib/Scenes/Consignments/Components/SearchResults.tsx
  src/lib/Scenes/Consignments/Screens/ConsignmentsArtist.tsx
  src/lib/Scenes/Consignments/Screens/__tests__/ConsignmentsArtist-tests.tsx
  src/lib/Scenes/Consignments/index.tsx
Labels: Jira Synced, Squash On Green

#5079 feat: Mark Order History feature as ready for release
  CHANGELOG.yml
  src/lib/store/config/features.ts
Labels: Squash On Green

#5075 feat: add context_screen_owner_slug to toggleSavedSearch analytics payload
  src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
  src/lib/Components/Artist/ArtistArtworks/SavedSearchBanner.tsx
  src/lib/Components/Artist/ArtistArtworks/__tests__/SavedSearchBanner-tests.tsx
Labels: Jira Synced, Squash On Green

#5064 fix (CX-958): refresh artwork after purchase
  CHANGELOG.yml
  src/lib/Components/ArtsyReactWebView.tsx
  src/lib/Scenes/Artwork/Artwork.tsx
Labels: Jira Synced

#5082 chore: update saved search text prompt within banner
  src/lib/Components/Artist/ArtistArtworks/SavedSearchBanner.tsx
Labels: Jira Synced, Squash On Green

#5015 feat(CX-1603): Add new onboarding feature flag
  CHANGELOG.yml
  emission/Pod/Classes/TemporaryAPI/ARTemporaryAPIModule.m
  src/lib/AppRegistry.tsx
  src/lib/Components/ArtsyReactWebView.tsx
  src/lib/ErrorReporting.ts
  src/lib/NativeModules/LegacyNativeModules.tsx
  src/lib/Scenes/Home/Home.tsx
  src/lib/Scenes/Onboarding/OnboardingCreateAccount/OnboardingCreateAccountName.tsx
  src/lib/Scenes/Onboarding/OnboardingWelcome.tsx
  src/lib/Scenes/VanityURL/VanityURLPossibleRedirect.tsx
  src/lib/store/AuthModel.ts
  src/lib/store/GlobalStore.tsx
  src/lib/store/NativeModel.ts
  src/lib/store/__tests__/migration-tests.ts
  src/lib/store/config/__tests__/UserIsDevModel-tests.tsx
  src/lib/store/config/features.ts
  src/lib/store/migration.ts
  src/lib/utils/AdminMenu.tsx
  src/setupJest.ts
Labels: Jira Synced, Squash On Green

#5074 feat: display saved search logic behind platform specific flag
  src/lib/store/config/features.ts
Labels: Jira Synced

#5081 fix: disappearing sticky header
  src/lib/Components/StickyHeaderPage.tsx
Labels: Jira Synced

#5059 fix white line below in new onboarding screen
  src/lib/Scenes/Onboarding/Onboarding.tsx
  src/lib/Scenes/Onboarding/OnboardingCreateAccount/OnboardingCreateAccount.tsx
  src/lib/Scenes/Onboarding/OnboardingLogin.tsx
  src/lib/Scenes/Onboarding/OnboardingPersonalization/OnboardingPersonalization.tsx
  src/lib/Scenes/Onboarding/OnboardingWelcome.tsx
Labels: Jira Synced

#5053 Fix(CX-1496) enable screen rotation on android tablets
  CHANGELOG.yml
  HACKS.md
  Podfile.lock
  package.json
  patches/react-native-screens+2.17.1.patch
  yarn.lock
Labels: Jira Synced, Squash On Green

#5058 enhancement: polish Auction Results for you screen
  CHANGELOG.yml
  CHANGELOG/android-changelog.md
  CHANGELOG/ios-changelog.md
  android/app/src/main/AndroidManifest.xml
  src/__generated__/ArtistBelowTheFoldQuery.graphql.ts
  src/__generated__/ArtistInsightsAuctionResultsQuery.graphql.ts
  src/__generated__/ArtistInsightsAuctionResultsTestsQuery.graphql.ts
  src/__generated__/ArtistInsightsTestsQuery.graphql.ts
  src/__generated__/AuctionResultListItemTestsQuery.graphql.ts
  src/__generated__/AuctionResultListItem_auctionResult.graphql.ts
  src/__generated__/AuctionResultsForYouContainerPaginationQuery.graphql.ts
  src/__generated__/AuctionResultsForYouContainerQuery.graphql.ts
  src/__generated__/AuctionResultsForYouTestsQuery.graphql.ts
  src/__generated__/AuctionResultsRailTestsQuery.graphql.ts
  src/__generated__/HomeQuery.graphql.ts
  src/__generated__/HomeRefetchQuery.graphql.ts
  src/__generated__/MyCollectionArtworkArtistAuctionResultsTestsQuery.graphql.ts
  src/__generated__/MyCollectionArtworkInsightsTestsQuery.graphql.ts
  src/__generated__/MyCollectionArtworkQuery.graphql.ts
  src/lib/Components/Lists/AuctionResultListItem.tsx
  src/lib/Scenes/AuctionResultsForYou/AuctionResultsForYou.tsx
  src/lib/Scenes/Home/Components/AuctionResultsRail.tsx
Labels: Jira Synced, Squash On Green

#4986 feat(CX-1559): Add Google & Apple auth
  .circleci/config.yml
  .gitignore
  Artsy.xcodeproj/project.pbxproj
  Artsy/App/ARAppDelegate.m
  Artsy/App_Resources/Artsy-Info.plist
  CHANGELOG.yml
  Podfile
  Podfile.lock
  android/app/build.gradle
  android/build.gradle
  package.json
  scripts/build-for-tests-android
  scripts/build-for-tests-ios
  scripts/changelog/changelog-types.d.ts
  scripts/download-assets
  scripts/setup-distribute-linux
  scripts/setup-distribute-macos
  scripts/setup-env-for-artsy
  src/lib/AndroidApp.tsx
  src/lib/AppRegistry.tsx
  src/lib/store/AuthModel.ts
  src/lib/store/GlobalStoreModel.ts
  src/lib/store/__tests__/AuthModel-tests.ts
  src/setupJest.ts
  yarn.lock
Labels: Jira Synced, Squash On Green

#5088 fix: hide auction results artist name on artist insights screen
  CHANGELOG.yml
  src/lib/Components/Lists/AuctionResultListItem.tsx
  src/lib/Scenes/AuctionResultsForYou/AuctionResultsForYou.tsx
  src/lib/Scenes/Home/Components/AuctionResultsRail.tsx
Labels: Jira Synced

#5089 fix(CX-1673): remove share button on BNMO flow
  CHANGELOG.yml
  Podfile.lock
  src/lib/Components/ArtsyReactWebView.tsx
Labels: Jira Synced

#5090 fix: don't show spinner when user has no auction results by followed artists
  CHANGELOG.yml
  src/lib/Components/Lists/AuctionResultListItem.tsx
  src/lib/Scenes/Home/Components/AuctionResultsRail.tsx
  src/lib/Scenes/Home/Components/__tests__/AuctionResultsRail-tests.tsx
Labels: Jira Synced, Squash On Green

#5086 feat: replace delete on disable saved search
  CHANGELOG.yml
  data/schema.graphql
  src/__generated__/SavedSearchBannerDisableSavedSearchMutation.graphql.ts
  src/lib/Components/Artist/ArtistArtworks/SavedSearchBanner.tsx
  src/lib/Components/Artist/ArtistArtworks/__tests__/SavedSearchBanner-tests.tsx
Labels: Jira Synced, Squash On Green

#5092 fix: Dont show home collections rail spinner
  CHANGELOG.yml
  src/lib/Scenes/Home/Components/CollectionsRail.tsx
Labels: Jira Synced, Squash On Green

#5096 feat: add update changelog script to CI
  .circleci/config.yml
Labels: Jira Synced

#5097 fix: fix iOS braze integration
  .circleci/config.yml
  Artsy/App/ARAppDelegate.h
  Artsy/App/ARAppDelegate.m
  Artsy/App/ARAppNotificationsDelegate.m
  Artsy/App_Resources/Artsy-Info.plist
Labels: Jira Synced, Squash On Green

#5098 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#5067 feat: Annotate home screen queries with optionalField directive
  CHANGELOG.yml
  src/__generated__/HomeQuery.graphql.ts
  src/__generated__/HomeRefetchQuery.graphql.ts
  src/lib/Scenes/Home/Components/ArticlesRail.tsx
  src/lib/Scenes/Home/Components/EmailConfirmationBanner.tsx
  src/lib/Scenes/Home/Components/HomeHero.tsx
  src/lib/Scenes/Home/Components/SalesRail.tsx
  src/lib/Scenes/Home/Home.tsx
Labels: Jira Synced

#5072 fix (CX-1576): gallery name and time overlapping
  CHANGELOG.yml
  src/lib/Scenes/ViewingRoom/Components/ViewingRoomHeader.tsx
Labels: Jira Synced, Squash On Green

#5084 Feat(cx-1635): initial android push notification setup
  .gitignore
  CHANGELOG.yml
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/mipmap-hdpi/ic_notification.png
  android/app/src/main/res/mipmap-mdpi/ic_notification.png
  android/app/src/main/res/mipmap-xhdpi/ic_notification.png
  android/app/src/main/res/mipmap-xxhdpi/ic_notification.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_notification.png
  android/app/src/main/res/values/colors.xml
  android/build.gradle
  index.android.js
  package.json
  src/lib/utils/AdminMenu.tsx
  src/lib/utils/PushNotification.ts
  src/lib/utils/__tests__/PushNotification-tests.ts
  src/setupJest.ts
  yarn.lock
Labels: Jira Synced, Squash On Green

#5100 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#5068 fix(CX-1577): featured fair show more button doesn't work
  CHANGELOG.yml
  src/lib/Scenes/Fair/Components/FairExhibitors.tsx
  src/lib/Scenes/Fair/__tests__/FairExhibitors-tests.tsx
Labels: Jira Synced, Squash On Green

#5103 fix: Adjust auction results for you tracking
  CHANGELOG.yml
  src/lib/Scenes/AuctionResultsForYou/AuctionResultsForYou.tsx
  src/lib/Scenes/Home/Components/AuctionResultsRail.tsx
Labels: Jira Synced

#5104 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#5106 chore: make home auction results available for release
  CHANGELOG.yml
  src/lib/Scenes/Home/Home.tsx
  src/lib/store/config/features.ts
Labels: Squash On Green

#5105 feat: add tracking to unable to load screen
  CHANGELOG.yml
  src/lib/Components/LoadFailureView.tsx
Labels: Jira Synced

#5102 fix: Add scrollView to auction results for you screen
  CHANGELOG.yml
  Podfile.lock
  src/lib/Scenes/AuctionResultsForYou/AuctionResultsForYou.tsx
Labels: Jira Synced, Squash On Green

#5022 fix[CX-1604] Facebook login is failing after signing up for a new account
  Artsy/View_Controllers/Login_and_Onboarding/AROnboardingViewController.m
  CHANGELOG.yml
Labels: Jira Synced

#5107 chore: update copy on iOS notifications saved search flow and profile
  src/lib/Components/Artist/ArtistArtworks/SavedSearchBanner.tsx
  src/lib/Scenes/MyProfile/MyProfilePushNotifications.tsx
Labels: Jira Synced, Squash On Green

#5110 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#5099 Update home feed titles to title case
  src/lib/Components/Home/ArtistRails/ArtistRail.tsx
  src/lib/Scenes/Home/Components/FairsRail.tsx
  src/lib/Scenes/Home/Components/__tests__/FairsRail-tests.tsx
  src/lib/Scenes/ViewingRoom/Components/ViewingRoomsHomeRail.tsx
Labels: Jira Synced

#5111 fix: push crash, disable method swizzling for firebase
  Artsy/App_Resources/Artsy-Info.plist
Labels: Jira Synced, Squash On Green

#5112 chore: remove sailthru
  .circleci/config.yml
  Artsy.xcodeproj/project.pbxproj
  Artsy/App/ARAppDelegate+Analytics.m
  Artsy/App/ARAppDelegate.m
  Artsy/App/ARAppNotificationsDelegate.m
  Artsy/App/ARSailthruIntegration.h
  Artsy/App/ARSailthruIntegration.m
  Artsy/Networking/API_Modules/ARUserManager.m
  Podfile
  Podfile.lock
Labels: Jira Synced, Squash On Green

#5114 fix(styling): Viewing Room Artwork spacing
  src/lib/Scenes/ViewingRoom/ViewingRoomArtwork.tsx
Labels: Jira Synced, Squash On Green

#5115 fix: Add auction results for you section header space
  src/lib/Scenes/AuctionResultsForYou/AuctionResultsForYou.tsx
Labels: Squash On Green

#5078 feat: User can keyword filter within artist auction results
  CHANGELOG.yml
  src/__generated__/ArtistBelowTheFoldQuery.graphql.ts
  src/__generated__/ArtistInsightsAuctionResultsQuery.graphql.ts
  src/__generated__/ArtistInsightsAuctionResultsTestsQuery.graphql.ts
  src/__generated__/ArtistInsightsAuctionResults_artist.graphql.ts
  src/__generated__/ArtistInsightsTestsQuery.graphql.ts
  src/lib/Components/Artist/ArtistInsights/ArtistInsightsAuctionResults.tsx
  src/lib/Components/ArtworkFilter/ArtworkFilterHelpers.ts
  src/lib/Components/ArtworkFilter/ArtworkFilterStore.tsx
  src/lib/Components/ArtworkFilter/Filters/KeywordFilter.tsx
  src/lib/Components/ArtworkFilter/Filters/__tests__/KeywordFilter-tests.tsx
  src/lib/Components/ArtworkFilter/__tests__/ArtworkFiltersStore-tests.tsx
  src/lib/Components/ArtworkGrids/FilteredArtworkGridZeroState.tsx
  src/lib/store/config/features.ts
Labels: Jira Synced, Squash On Green

#5118 fix(FX-3075): apply default sort for saved search
  src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
  src/lib/Components/ArtworkFilter/Filters/SortOptions.tsx
  src/lib/Scenes/Artist/Artist.tsx
  src/lib/Scenes/Artist/__tests__/ArtistSavedSearch-tests.tsx
Labels: Jira Synced

#5123 feat: add saved address list item and fetch saved addresses
  src/__generated__/SavedAddressesQuery.graphql.ts
  src/__generated__/SavedAddressesRefetchQuery.graphql.ts
  src/__generated__/SavedAddressesTestsQuery.graphql.ts
  src/__generated__/SavedAddresses_me.graphql.ts
  src/lib/Scenes/SavedAddresses/SavedAddresses.tsx
  src/lib/Scenes/SavedAddresses/__tests__/SavedAddresses-tests.tsx
Labels: Jira Synced, Squash On Green

#5129 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#5128 feat: default view of an address when multiple are saved
  src/__generated__/SavedAddressesQuery.graphql.ts
  src/__generated__/SavedAddressesRefetchQuery.graphql.ts
  src/__generated__/SavedAddressesTestsQuery.graphql.ts
  src/__generated__/SavedAddresses_me.graphql.ts
  src/lib/Scenes/SavedAddresses/SavedAddresses.tsx
Labels: Jira Synced

#5120 chore: Prepare for 6.10.1
  CHANGELOG.yml
  app.json
Labels: Squash On Green

#5131 chore: fix fastlane key
  Gemfile.lock
  fastlane/Fastfile
Labels: Squash On Green

#5130 feat: add delete address functionality
  src/__generated__/deleteSavedAddressDeleteUserAddressMutation.graphql.ts
  src/lib/Scenes/SavedAddresses/SavedAddresses.tsx
  src/lib/Scenes/SavedAddresses/mutations/deleteSavedAddress.ts
Labels: Jira Synced

#5135 fix [CX-1693]: [Auction Results for Artists You Follow] Change screen title
  src/lib/Scenes/AuctionResultsForYou/AuctionResultsForYou.tsx
  src/lib/Scenes/AuctionResultsForYou/__tests__/AuctionResultsForYou-tests.tsx
Labels: Squash On Green

#5138 fix: fix iOS side of braze integration
  Artsy/App/ARAppDelegate.h
  Artsy/App/ARAppDelegate.m
  Artsy/App/ARAppNotificationsDelegate.m
  Artsy_Tests/App_Tests/ARAppNotificationsDelegateTests.m
  Podfile
  Podfile.lock
  package.json
  patches/react-native-appboy-sdk+1.29.1.patch
  yarn.lock
Labels: Jira Synced, Squash On Green

#5139 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#5136 bring-back-feature(analytics): Added back the analytics visualizer, now in TS.
  Artsy/App/AROptions.h
  Artsy/App/AROptions.m
  Artsy/View_Controllers/Admin/ARAdminSettingsViewController.m
  src/lib/AppProviders.tsx
  src/lib/Components/ArtistListItem.tsx
  src/lib/Components/Toast/Toast.ts
  src/lib/Components/Toast/ToastComponent.tsx
  src/lib/Components/Toast/__tests__/Toast-tests.tsx
  src/lib/Components/Toast/toastHook.tsx
  src/lib/Components/Toast/types.ts
  src/lib/Scenes/Onboarding/OnboardingPersonalization/OnboardingPersonalizationArtistListItem.tsx
  src/lib/store/AuthModel.ts
  src/lib/store/GlobalStoreModel.ts
  src/lib/store/ToastModel.ts
  src/lib/store/__tests__/migration-tests.ts
  src/lib/store/config/features.ts
  src/lib/store/migration.ts
  src/lib/utils/track/SegmentTrackingProvider.ts
  src/palette/elements/Touchable/Touchable.tsx
  src/setupJest.ts
Labels: Jira Synced

#5117 fix(FX-3072): jerky popover message
  src/lib/Components/Artist/ArtistArtworks/SavedSearchBanner.tsx
  src/lib/Components/PopoverMessage/PopoverMessage.tsx
  src/lib/Components/PopoverMessage/PopoverMessageProvider.tsx
  src/lib/Components/PopoverMessage/__tests__/PopoverMessage-tests.tsx
Labels: Jira Synced, Squash On Green

#5124 feat: add address form
  CHANGELOG.yml
  src/__generated__/SavedAddressesNewFormQuery.graphql.ts
  src/__generated__/SavedAddressesNewFormTestsQuery.graphql.ts
  src/__generated__/SavedAddressesNewForm_me.graphql.ts
  src/__generated__/addNewAddressMutation.graphql.ts
  src/__generated__/setAsDefaultAddressMutation.graphql.ts
  src/lib/AppRegistry.tsx
  src/lib/Scenes/MyAccount/Components/MyAccountFieldEditScreen.tsx
  src/lib/Scenes/SavedAddresses/Components/AddAddressButton.tsx
  src/lib/Scenes/SavedAddresses/SavedAddresses.tsx
  src/lib/Scenes/SavedAddresses/SavedAddressesNewForm.tsx
  src/lib/Scenes/SavedAddresses/__tests__/SavedAddresses-tests.tsx
  src/lib/Scenes/SavedAddresses/__tests__/SavedAddressesNewForm-tests.tsx
  src/lib/Scenes/SavedAddresses/mutations/addNewAddress.ts
  src/lib/Scenes/SavedAddresses/mutations/setAsDefaultAddress.ts
  src/lib/navigation/routes.tsx
Labels: Jira Synced

#5144 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#5142 feat(FX-2789): make filter facet names title case
  Podfile.lock
  src/lib/Components/ArtworkFilter/ArtworkFilterHelpers.ts
  src/lib/Components/ArtworkFilter/Filters/__tests__/GalleriesAndInstitutionsOptions-tests.tsx
  src/lib/Components/ArtworkFilter/Filters/__tests__/LocationCitiesOptions-tests.tsx
  src/lib/Components/ArtworkFilter/Filters/__tests__/TimePeriodOptions-tests.tsx
Labels: Jira Synced

#5145 fix(scripts): better handling of .netrc
  Podfile
  Podfile.lock
Labels: Squash On Green

#5147 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#5148 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#5152 chore: enable braze verbose logging #trivial
  Artsy/App_Resources/Artsy-Info.plist
Labels: Squash On Green

#5154 fix: copy paste error braze prod api
  Artsy/App/ARAppDelegate.m
Labels: Squash On Green

#5156 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#5153 [CX-1564] Adding inEditorialFeed: true to articlesConnection for all Fair and Other Queries
  src/__generated__/FairArticlesQuery.graphql.ts
  src/__generated__/FairArticles_fair.graphql.ts
  src/__generated__/FairEditorialTestsQuery.graphql.ts
  src/__generated__/FairEditorial_fair.graphql.ts
  src/__generated__/FairQuery.graphql.ts
  src/__generated__/FairTestsQuery.graphql.ts
  src/__generated__/Fair_fair.graphql.ts
  src/__generated__/VanityURLEntityQuery.graphql.ts
  src/lib/Scenes/Fair/Components/FairEditorial.tsx
  src/lib/Scenes/Fair/Fair.tsx
  src/lib/Scenes/Fair/FairArticles.tsx
Labels: Squash On Green

#5146 feat: auto refresh for goBack event in view page [PURCHASE-2788]
  src/__generated__/SavedAddressesQuery.graphql.ts
  src/__generated__/SavedAddressesRefetchQuery.graphql.ts
  src/__generated__/SavedAddressesTestsQuery.graphql.ts
  src/__generated__/SavedAddresses_me.graphql.ts
  src/lib/Scenes/SavedAddresses/SavedAddresses.tsx
  src/lib/Scenes/SavedAddresses/__tests__/SavedAddresses-tests.tsx
  src/lib/navigation/navigate.ts
Labels: Jira Synced

#5164 chore: 6.10.2 dev prep + cleanup
  Artsy.xcodeproj/project.pbxproj
  CHANGELOG.legacy.yml
  Gemfile.lock
  app.json
  dangerfile.ts
  docs/deploy_to_app_store.md
  fastlane/Fastfile
  package.json
  yarn.lock
Labels: Squash On Green

#5158 feat(PURCHASE-2786): Edit Address
  src/__generated__/SavedAddressesFormQuery.graphql.ts
  src/__generated__/SavedAddressesFormTestsQuery.graphql.ts
  src/__generated__/SavedAddressesForm_me.graphql.ts
  src/__generated__/SavedAddressesQuery.graphql.ts
  src/__generated__/SavedAddressesRefetchQuery.graphql.ts
  src/__generated__/SavedAddressesTestsQuery.graphql.ts
  src/__generated__/SavedAddresses_me.graphql.ts
  src/__generated__/updateUserAddressMutation.graphql.ts
  src/lib/AppRegistry.tsx
  src/lib/Scenes/SavedAddresses/Components/AddAddressButton.tsx
  src/lib/Scenes/SavedAddresses/SavedAddresses.tsx
  src/lib/Scenes/SavedAddresses/SavedAddressesForm.tsx
  src/lib/Scenes/SavedAddresses/__tests__/SavedAddresses-tests.tsx
  src/lib/Scenes/SavedAddresses/__tests__/SavedAddressesForm-tests.tsx
  src/lib/Scenes/SavedAddresses/__tests__/SavedAddressesNewForm-tests.tsx
  src/lib/Scenes/SavedAddresses/mutations/updateUserAddress.ts
  src/lib/navigation/routes.tsx
Labels: Jira Synced

#5163 feat(FX-3104): ability to use ScrollView instead of FlatList
  src/lib/Components/ArtworkFilter/Filters/PriceRangeOptions.tsx
  src/lib/Components/ArtworkFilter/Filters/SingleSelectOption.tsx
  src/lib/Components/ArtworkFilter/Filters/SizeOptions.tsx
Labels: Jira Synced

#5175 chore: Add detect-secrets pre-commit hook
  .secrets.baseline
  package.json
  yarn.lock
Labels: Jira Synced

#5177 fix: braze once more
  Artsy/App/ARAppDelegate.h
  Artsy/App/ARAppDelegate.m
  Artsy/App/ARAppNotificationsDelegate.h
  Artsy/App/ARAppNotificationsDelegate.m
  emission/Pod/Classes/EigenCommunications/ARNotificationsManager.m
Labels: Jira Synced

#5167 fix(FX-3103): update size options label
  src/lib/Components/ArtworkFilter/Filters/SizeOptions.tsx
  src/lib/Components/ArtworkFilter/Filters/__tests__/SizeOptions-tests.tsx
  src/lib/Components/ArtworkFilter/SavedSearch/__tests__/convertersToFilterParams-tests.ts
Labels: Jira Synced

#5127 feat: Add storybook
  .gitignore
  Artsy/App/ARAppDelegate.m
  docs/README.md
  docs/storybook.md
  index.android.js
  index.ios.js
  index.tests.ios.js
  jest.config.js
  package.json
  scripts/set-storybook-environment.js
  scripts/start_packager.sh
  src/lib/AppRegistry.tsx
  src/lib/navigation/routes.tsx
  src/lib/utils/AdminMenu.tsx
  src/palette/elements/Button/Button.stories.tsx
  src/palette/elements/Button/Button.tsx
  src/storybook/addons.js
  src/storybook/helpers.tsx
  src/storybook/index.js
  src/storybook/package.json
  src/storybook/rn-addons.js
  src/storybook/storyLoader.js
  src/storybook/storybook-ui.js
  typings/storybook.d.ts
  yarn.lock
Labels: Jira Synced, Squash On Green

#5149 feat(FX-3089): create saved search alert button
  src/__generated__/SavedSearchButtonQuery.graphql.ts
  src/__generated__/SavedSearchButtonTestsQuery.graphql.ts
  src/__generated__/SavedSearchButton_me.graphql.ts
  src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
  src/lib/Components/Artist/ArtistArtworks/SavedSearchButton.tsx
  src/lib/Components/Artist/ArtistArtworks/__tests__/SavedSearchButton-tests.tsx
  src/lib/Scenes/Artist/__tests__/ArtistSavedSearch-tests.tsx
  src/lib/store/config/features.ts
  src/palette/elements/Button/Button.tsx
Labels: Jira Synced

#5151 fix: move auctions tracking to screen component
  src/lib/Scenes/Home/Components/SalesRail.tsx
  src/lib/Scenes/Sales/index.tsx
Labels: Jira Synced

#5186 fix(palette flag): separated the temporary palette flag
  package.json
  src/lib/Components/ArtistListItem.tsx
  src/lib/Components/__tests__/ArtistListItem-tests.tsx
  src/lib/store/config/features.ts
  src/lib/utils/AdminMenu.tsx
  src/lib/utils/track/SegmentTrackingProvider.ts
  src/palette/PaletteFlag.tsx
  src/palette/Theme.tsx
  src/palette/elements/Avatar/Avatar.tsx
  src/palette/elements/BorderBox/BorderBox.tsx
  src/palette/elements/Flex/Flex.tsx
  src/palette/elements/Message/Message.tsx
  src/palette/elements/Typography/Typography.tsx
  src/palette/hooks.ts
  src/palette/platform/primitives.ts
  yarn.lock
Labels: Squash On Green

#5140 fix(CX-1722): [unknown] sentry errors
  src/lib/relay/middlewares/__tests__/errorMiddleware-tests.ts
  src/lib/relay/middlewares/errorMiddleware.ts
Labels: Jira Synced

#5178 feature: Add loading indicator to keyword filter input
  src/lib/Components/Artist/ArtistInsights/ArtistInsightsAuctionResults.tsx
  src/lib/Components/ArtworkFilter/Filters/KeywordFilter.tsx
  src/lib/Components/Input/Input.tsx
Labels: Jira Synced

#5168 fix: change auction lots for you ending soon title to title case
  src/lib/Scenes/Home/Components/SaleArtworksHomeRail.tsx
  src/lib/Scenes/Home/Components/__tests__/SaleArtworksHomeRail-tests.tsx
Labels: Jira Synced

#5109 fix: Add www to web url
  src/lib/Components/__tests__/ArtsyReactWebView-tests.tsx
  src/lib/Scenes/Artwork/Components/__tests__/ArtworkActions-tests.tsx
  src/lib/Scenes/SaleFAQ/SaleFAQ.tsx
  src/lib/Scenes/VanityURL/__tests__/VanityURLPossibleRedirect-tests.tsx
  src/lib/Scenes/ViewingRoom/ViewingRoom.tsx
  src/lib/navigation/__tests__/routes-tests.tsx
  src/lib/navigation/routes.tsx
  src/lib/store/config/EnvironmentModel.tsx
Labels: Jira Synced, Squash On Green

#5192 fix: Adjust keyword filter loading indicator timing
  src/lib/Components/Artist/ArtistHeader.tsx
  src/lib/Components/Artist/ArtistInsights/ArtistInsightsAuctionResults.tsx
  src/lib/Components/ArtworkFilter/Filters/KeywordFilter.tsx
Labels: Jira Synced

#5134 Feat(cx-1648): android prompt for push permission if necessary
  HACKS.md
  patches/react-native-push-notification+7.4.0.patch
  src/lib/Components/Artist/ArtistArtworks/SavedSearchBanner.tsx
  src/lib/store/AuthModel.ts
Labels: Jira Synced

#5188 feat: Delete address through edit form
  src/lib/Scenes/SavedAddresses/SavedAddressesForm.tsx
  src/lib/Scenes/SavedAddresses/__tests__/SavedAddressesForm-tests.tsx
Labels: Jira Synced

#5187 Release auction results keyword filter and add echo
  src/lib/store/config/features.ts
Labels: Jira Synced, Squash On Green

#5162 feature: Add signup marketing email checkbox
  .secrets.baseline
  package.json
  src/lib/Scenes/Onboarding/OnboardingCreateAccount/EmailSubscriptionCheckbox.tsx
  src/lib/Scenes/Onboarding/OnboardingCreateAccount/OnboardingCreateAccount.tsx
  src/lib/Scenes/Onboarding/OnboardingCreateAccount/TermsOfServiceCheckbox.tsx
  src/lib/store/AuthModel.ts
  src/lib/store/__tests__/AuthModel-tests.ts
Labels: Jira Synced

#5201 fix: Decrease auctionFAQs top padding
  src/lib/Scenes/SaleFAQ/SaleFAQ.tsx
Labels: Squash On Green

#5204 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#5195 feat(FX-3109): tag page
  Podfile.lock
  src/__generated__/About_tag.graphql.ts
  src/__generated__/TagArtworksPaginationQuery.graphql.ts
  src/__generated__/TagArtworksTestsQuery.graphql.ts
  src/__generated__/TagArtworks_tag.graphql.ts
  src/__generated__/TagHeader_tag.graphql.ts
  src/__generated__/TagQuery.graphql.ts
  src/__generated__/TagTestsQuery.graphql.ts
  src/lib/AppRegistry.tsx
  src/lib/Components/ArtworkFilter/ArtworkFilterHelpers.ts
  src/lib/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx
  src/lib/Components/ArtworkFilter/ArtworkFilterStore.tsx
  src/lib/Components/ArtworkFilter/Filters/SortOptions.tsx
  src/lib/Components/Tag/About.tsx
  src/lib/Components/Tag/TagArtworks.tsx
  src/lib/Components/Tag/TagPlaceholder.tsx
  src/lib/Components/Tag/__tests__/About-tests.tsx
  src/lib/Components/Tag/__tests__/TagArtworks-tests.tsx
  src/lib/Scenes/Tag/Tag.tsx
  src/lib/Scenes/Tag/TagHeader.tsx
  src/lib/Scenes/Tag/__tests__/Tag-tests.tsx
  src/lib/Scenes/Tag/__tests__/TagHeader-tests.tsx
  src/lib/navigation/routes.tsx
  src/lib/utils/track/schema.ts
  src/setupJest.ts
Labels: Jira Synced

#5205 Revert "feat(FX-3109): tag page"
  Podfile.lock
  src/__generated__/About_tag.graphql.ts
  src/__generated__/TagArtworksPaginationQuery.graphql.ts
  src/__generated__/TagArtworksTestsQuery.graphql.ts
  src/__generated__/TagArtworks_tag.graphql.ts
  src/__generated__/TagHeader_tag.graphql.ts
  src/__generated__/TagQuery.graphql.ts
  src/__generated__/TagTestsQuery.graphql.ts
  src/lib/AppRegistry.tsx
  src/lib/Components/ArtworkFilter/ArtworkFilterHelpers.ts
  src/lib/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx
  src/lib/Components/ArtworkFilter/ArtworkFilterStore.tsx
  src/lib/Components/ArtworkFilter/Filters/SortOptions.tsx
  src/lib/Components/Tag/About.tsx
  src/lib/Components/Tag/TagArtworks.tsx
  src/lib/Components/Tag/TagPlaceholder.tsx
  src/lib/Components/Tag/__tests__/About-tests.tsx
  src/lib/Components/Tag/__tests__/TagArtworks-tests.tsx
  src/lib/Scenes/Tag/Tag.tsx
  src/lib/Scenes/Tag/TagHeader.tsx
  src/lib/Scenes/Tag/__tests__/Tag-tests.tsx
  src/lib/Scenes/Tag/__tests__/TagHeader-tests.tsx
  src/lib/navigation/routes.tsx
  src/lib/utils/track/schema.ts
  src/setupJest.ts
Labels: Jira Synced, Merge On Green

#5206 fix: remove extra notification delegate handling
  Artsy/App/ARAppDelegate.m
  Artsy/App/ARAppNotificationsDelegate.h
  Artsy/App/ARAppNotificationsDelegate.m
Labels: Squash On Green
