Repository artsy/eigen, pull requests merged in 2021-01, with the labels that each got.

#4299 feat: add support for encoded URIs
  src/lib/navigation/__tests__/routes-tests.tsx
  src/lib/navigation/routes.tsx
Labels: Squash On Green

#4300 fix(fx-2577): updates screen name
  src/lib/utils/track/schema.ts
Labels: Merge On Green

#4294 chore: Add p1 haptics for selection actions
  src/lib/Components/AnimatedBottomButton.tsx
  src/lib/Components/Artist/ArtistHeader.tsx
  src/lib/Components/Home/ArtistRails/ArtistCard.tsx
  src/lib/Scenes/ArtistSeries/ArtistSeriesMeta.tsx
  src/lib/Scenes/Artwork/Components/CommercialButtons/BidButton.tsx
  src/lib/Scenes/Artwork/Components/CommercialButtons/BuyNowButton.tsx
  src/lib/Scenes/Artwork/Components/CommercialButtons/CommercialButtons.tsx
  src/lib/Scenes/Artwork/Components/CommercialButtons/MakeOfferButton.tsx
  src/lib/Scenes/Artwork/Components/ContextCard.tsx
  src/lib/Scenes/Artwork/Components/FollowArtistButton.tsx
  src/lib/Scenes/Artwork/Components/PartnerCard.tsx
  src/lib/Scenes/Consignments/ConsignmentsHome/Components/Footer.tsx
  src/lib/Scenes/Consignments/ConsignmentsHome/Components/Header.tsx
  src/lib/Scenes/Consignments/Screens/Overview.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkFormModal/Screens/MyCollectionArtworkFormMain.tsx
  src/lib/Scenes/Partner/Components/PartnerFollowButton.tsx
  src/lib/Scenes/Sale/Components/RegisterToBidButton.tsx
  src/palette/elements/Touchable/Touchable.tsx
Labels: Jira Synced

#4284 chore: Move send email into util function and handle users with no email client setup
  CHANGELOG.yml
  src/lib/Scenes/Artwork/Components/ArtworkExtraLinks/index.tsx
  src/lib/Scenes/SaleInfo/SaleInfo.tsx
  src/lib/utils/__tests__/sendEmail-tests.ts
  src/lib/utils/renderMarkdown.tsx
  src/lib/utils/sendEmail.ts
Labels: Jira Synced

#4137 feature(share): allow instagram share
  Artsy/App_Resources/Artsy-Info.plist
  CHANGELOG.yml
  Podfile.lock
  package.json
  src/__generated__/ArtworkAboveTheFoldQuery.graphql.ts
  src/__generated__/ArtworkHeader_artwork.graphql.ts
  src/__generated__/ArtworkRefetchQuery.graphql.ts
  src/lib/Scenes/Artwork/Components/ArtworkActions.tsx
  src/lib/Scenes/Artwork/Components/ArtworkHeader.tsx
  src/lib/Scenes/Artwork/Components/ImageCarousel/ImageCarousel.tsx
  src/lib/Scenes/Artwork/Components/ImageCarousel/ImageCarouselContext.tsx
  src/setupJest.ts
  yarn.lock
Labels: Jira Synced, hackathon

#4317 chore: add lab flag in eigen to enable inquiry checkout
  Artsy/App/AROptions.h
  Artsy/App/AROptions.m
  Artsy_Tests/App_Tests/ARAppDelegateEmissionSpec.m
  CHANGELOG.yml
  src/lib/store/NativeModel.ts
  src/setupJest.ts
Labels: Squash On Green

#4329 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4335 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4336 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4326 enhancement(deps): remove prop-types, react-native-parallax-scroll-view, noop func
  CHANGELOG.yml
  index.ios.js
  package.json
  src/lib/Components/Bidding/Components/BiddingThemeProvider.tsx
  src/lib/Components/Bidding/Components/Timer.tsx
  src/lib/Components/Bidding/Context/TimeOffsetProvider.tsx
  src/lib/Components/Bidding/Context/__tests__/TimeOffsetProvider-tests.tsx
  src/lib/Components/LoadFailureView.tsx
  src/lib/Components/RetryErrorBoundary.tsx
  src/lib/Components/__tests__/RetryErrorBoundary-tests.tsx
  src/lib/Containers/Gene.tsx
  src/lib/Containers/__tests__/Gene-tests.tsx
  src/lib/Scenes/Sale/Sale.tsx
  src/lib/Scenes/ViewingRoom/ViewingRoomArtwork.tsx
  src/lib/Scenes/ViewingRoom/ViewingRoomsList.tsx
  src/lib/utils/renderWithPlaceholder.tsx
  yarn.lock
Labels: Squash On Green

#4345 Preparing for development, version 6.7.7
  Artsy Stickers/Info.plist
  Artsy/App_Resources/Artsy-Info.plist
  CHANGELOG.yml
Labels: Squash On Green

#4341 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4280 feat: Refresh inbox on visit
  CHANGELOG.yml
  src/lib/AppRegistry.tsx
  src/lib/Containers/Inbox/Inbox.tsx
  src/lib/Containers/Inbox/InboxOld.tsx
  src/lib/Containers/Inbox/index.tsx
  src/lib/Containers/__tests__/Inbox-tests.tsx
  src/lib/Containers/__tests__/InboxWrapper-tests.tsx
  src/lib/Scenes/Inbox/Components/Conversations/Conversations.tsx
  src/lib/Scenes/Inbox/Components/Conversations/__tests__/Conversations-tests.tsx
  src/lib/Scenes/MyBids/MyBids.tsx
  src/lib/Scenes/MyBids/__tests__/MyBids-tests.tsx
Labels: Squash On Green

#4354 Update metaphysics schema
  data/schema.graphql
  src/__generated__/MyCollectionArtworkArtistMarketTestsQuery.graphql.ts
  src/__generated__/MyCollectionArtworkDemandIndexTestsQuery.graphql.ts
  src/__generated__/MyCollectionArtworkInsightsTestsQuery.graphql.ts
  src/__generated__/MyCollectionArtworkPriceEstimateTestsQuery.graphql.ts
  src/__generated__/MyCollectionArtworkQuery.graphql.ts
Labels: Merge On Green

#4355 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4353 fix(Artist): Hide artist insights tab when the user has no auction results
  CHANGELOG.yml
  src/__generated__/ArtistAboveTheFoldQuery.graphql.ts
  src/lib/Components/HeaderTabGridPlaceholder.tsx
  src/lib/Scenes/Artist/Artist.tsx
  src/lib/Scenes/Artist/__tests__/Artist-tests.tsx
Labels: Jira Synced

#4358 fix: auction results list QA
  CHANGELOG.yml
  src/lib/Components/Artist/ArtistInsights/ArtistInsights.tsx
  src/lib/Components/Lists/AuctionResult.tsx
Labels: Jira Synced

#4349 fix: native auction results UI bugs
  src/lib/Components/Lists/AuctionResult.tsx
  src/lib/Scenes/AuctionResult/AuctionResult.tsx
  src/lib/Scenes/AuctionResult/__tests__/AuctionResult-tests.tsx
  src/lib/Scenes/Sale/Components/SaleArtworkListItem.tsx
Labels: Jira Synced, Squash On Green

#4359 fix: auction result screen QA fixes
  CHANGELOG.yml
  src/lib/Scenes/AuctionResult/AuctionResult.tsx
Labels: Jira Synced

#4357 CX-938: Fix empty auction
  src/__generated__/SaleBelowTheFoldQuery.graphql.ts
  src/__generated__/SaleLotsList_unfilteredSaleArtworksConnection.graphql.ts
  src/lib/Scenes/Sale/Components/SaleLotsList.tsx
  src/lib/Scenes/Sale/Sale.tsx
  src/lib/Scenes/Sale/__tests__/SaleLotsList-tests.tsx
Labels: Jira Synced, Squash On Green

#4363 chore: Add early success task to android circle job
  .circleci/config.yml
Labels: Jira Synced

#4365 chore: artist insights + auction results info modals
  CHANGELOG.yml
  src/lib/Components/Artist/ArtistInsights/ArtistInsights.tsx
  src/lib/Components/Artist/ArtistInsights/ArtistInsightsAuctionResults.tsx
  src/lib/Components/Buttons/InfoButton.tsx
  src/lib/Components/Buttons/__tests__/InfoButton-tests.tsx
  src/lib/Components/FancyModal/FancyModalHeader.tsx
  src/lib/Scenes/AuctionResult/AuctionResult.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkArtistAuctionResults.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkArtistMarket.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkDemandIndex.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkPriceEstimate.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/__tests__/MyCollectionArtworkArtistAuctionResults-tests.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/__tests__/MyCollectionArtworkArtistMarket-tests.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/__tests__/MyCollectionArtworkDemandIndex-tests.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/__tests__/MyCollectionArtworkPriceEstimate-tests.tsx
Labels: Jira Synced

#4367 feat: add tracking to auction results
  CHANGELOG.yml
  src/__generated__/AuctionResultQuery.graphql.ts
  src/lib/Components/Artist/ArtistInsights/ArtistInsights.tsx
  src/lib/Components/Artist/ArtistInsights/ArtistInsightsAuctionResults.tsx
  src/lib/Components/Buttons/InfoButton.tsx
  src/lib/Components/FilterModal/FilterModal.tsx
  src/lib/Scenes/AuctionResult/AuctionResult.tsx
  src/lib/utils/track/schema.ts
Labels: Jira Synced

#4368 fix: explicitly tag releases to fix sourcemaps for sentry errors
  Artsy/App/AROptions.m
  CHANGELOG.yml
  emission/Pod/Classes/TemporaryAPI/ARTemporaryAPIModule.m
  fastlane/Fastfile
  src/lib/ErrorReporting.ts
  src/lib/NativeModules/ArtsyNativeModules.tsx
  src/lib/Scenes/MyProfile/MyProfile.tsx
  src/lib/store/GlobalStore.tsx
  src/lib/store/NativeModel.ts
  src/setupJest.ts
  typings/emission.d.ts
Labels: Jira Synced, Squash On Green

#4372 fix: auction results end QA fixes
  CHANGELOG.yml
  src/lib/Components/Artist/ArtistInsights/ArtistInsights.tsx
Labels: Jira Synced

#4371 feat: validate changelog
  CHANGELOG.yml
  package.json
  yarn.lock
Labels: Jira Synced, Squash On Green
