Repository artsy/eigen, pull requests merged in 2021-08, with the labels that each got.

#5189 migration(palette v3 colors): here we go!
  HACKS.md
  emission/Pod/Classes/ViewControllers/ARMapComponentViewController.m
  package.json
  patches/react-native-credit-card-input+0.4.1.patch
  src/lib/Components/ArtsyReactWebView.tsx
  src/lib/Components/Bidding/Components/BidInfoRow.tsx
  src/lib/Components/Bidding/Components/BiddingThemeProvider.tsx
  src/lib/Components/Bidding/Components/Input.tsx
  src/lib/Components/Bidding/Components/PaymentInfo.tsx
  src/lib/Components/Bidding/Components/__tests__/Checkbox-tests.tsx
  src/lib/Components/Bidding/Components/__tests__/Input-tests.tsx
  src/lib/Components/Bidding/Components/__tests__/PaymentInfo-tests.tsx
  src/lib/Components/Bidding/Components/__tests__/Timer-tests.tsx
  src/lib/Components/Bidding/Components/__tests__/Title-tests.tsx
  src/lib/Components/Bidding/Context/__tests__/TimeOffsetProvider-tests.tsx
  src/lib/Components/Bidding/Elements/Grid.tsx
  src/lib/Components/Bidding/Elements/Theme.tsx
  src/lib/Components/Bidding/Screens/BidResult.tsx
  src/lib/Components/Bidding/Screens/BillingAddress.tsx
  src/lib/Components/Bidding/Screens/ConfirmBid/index.tsx
  src/lib/Components/Bidding/Screens/CreditCardForm.tsx
  src/lib/Components/Bidding/Screens/Registration.tsx
  src/lib/Components/Bidding/Screens/RegistrationResult.tsx
  src/lib/Components/Bidding/Screens/__tests__/BidResult-tests.tsx
  src/lib/Components/Bidding/Screens/__tests__/ConfirmBid-tests.tsx
  src/lib/Components/Bidding/Screens/__tests__/Registration-tests.tsx
  src/lib/Components/Bidding/Screens/__tests__/RegistrationResult-tests.tsx
  src/lib/Components/Bidding/Screens/__tests__/SelectMaxBid-tests.tsx
  src/lib/Components/Input/InputTitle.tsx
  src/lib/Components/TextArea.tsx
  src/lib/Scenes/About/About.tsx
  src/lib/Scenes/Artwork/Components/ArtworkActions.tsx
  src/lib/Scenes/Artwork/Components/CommercialButtons/InquiryModal.tsx
  src/lib/Scenes/Artwork/Components/__tests__/CommercialInformation-tests.tsx
  src/lib/Scenes/BottomTabs/BottomTabs.tsx
  src/lib/Scenes/Consignments/Components/ImageSelection.tsx
  src/lib/Scenes/Inbox/Components/Conversations/Composer.tsx
  src/lib/Scenes/Inbox/Components/Conversations/Message.tsx
  src/lib/Scenes/Map/Components/UserPositionButton.tsx
  src/lib/Scenes/MyBids/Components/SaleInfo.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkDemandIndex.tsx
  src/lib/utils/QAInfo.tsx
  src/palette/Theme.tsx
  src/palette/colors.stories.tsx
  src/palette/colorsV2.stories.tsx
  src/palette/helpers/__tests__/color.tests.tsx
  src/palette/helpers/__tests__/space.tests.tsx
  src/palette/svgs/sf/BoltCircleFill.tsx
  src/storybook/decorators.tsx
  src/storybook/helpers.tsx
  src/storybook/storyLoader.js
  src/storybook/storybook-ui.js
Labels: Jira Synced

#5194 migration(palette v3): space 🛰
  src/palette/Theme.tsx
  src/palette/colorsV2.stories.tsx
  src/palette/helpers/__tests__/space.tests.tsx
  src/palette/space.stories.tsx
  src/palette/spaceV2.stories.tsx
  src/storybook/storyLoader.js
Labels: Jira Synced

#5211 fix(button spinner): cherry-pick some work from ole's button PR
  src/lib/tests/__tests__/MockRelayRenderer-tests.tsx
  src/palette/elements/Spinner/Spinner.tsx
Labels: Squash On Green

#5182 feat: show notifs when saved addresses added, updated, or deleted
  src/lib/Scenes/SavedAddresses/SavedAddressNotification.tsx
  src/lib/Scenes/SavedAddresses/SavedAddresses.tsx
  src/lib/Scenes/SavedAddresses/SavedAddressesForm.tsx
  src/lib/Scenes/SavedAddresses/__tests__/SavedAddresses-tests.tsx
  src/lib/navigation/navigate.ts
Labels: Jira Synced

#5159 feat(FX-3100): create saved search alert form
  src/lib/Scenes/SavedSearchAlert/Components/Form.tsx
  src/lib/Scenes/SavedSearchAlert/Components/__tests__/Form-tests.tsx
  src/lib/Scenes/SavedSearchAlert/CreateSavedSearchAlert.tsx
  src/lib/Scenes/SavedSearchAlert/SavedSearchAlertForm.tsx
  src/lib/Scenes/SavedSearchAlert/SavedSearchAlertModel.ts
  src/palette/elements/Pill/Pill.tsx
  src/palette/elements/Pill/index.ts
  src/palette/elements/index.tsx
Labels: Jira Synced

#5218 Update metaphysics schema
  data/schema.graphql
  src/__generated__/SavedSearchBannerCreateSavedSearchMutation.graphql.ts
Labels: Merge On Green

#5221 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#5222 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#5223 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#5220 feat(FX-3110): list of saved search alerts
  src/__generated__/SavedSearchAlertsListQuery.graphql.ts
  src/__generated__/SavedSearchAlertsList_me.graphql.ts
  src/__generated__/SavedSearchesListQuery.graphql.ts
  src/__generated__/SavedSearchesListTestsQuery.graphql.ts
  src/__generated__/SavedSearchesList_me.graphql.ts
  src/lib/AppRegistry.tsx
  src/lib/Scenes/MyProfile/MyProfile.tsx
  src/lib/Scenes/MyProfile/__tests__/MyProfile-tests.tsx
  src/lib/Scenes/SavedSearchAlertsList/Components/EmptyMessage.tsx
  src/lib/Scenes/SavedSearchAlertsList/Components/SavedSearchAlertsListPlaceholder.tsx
  src/lib/Scenes/SavedSearchAlertsList/Components/SavedSearchListItem.tsx
  src/lib/Scenes/SavedSearchAlertsList/Components/SavedSearchesList.tsx
  src/lib/Scenes/SavedSearchAlertsList/Components/__tests__/SavedSearchesList-tests.tsx
  src/lib/Scenes/SavedSearchAlertsList/SavedSearchAlertsList.tsx
  src/lib/data/constants.ts
  src/lib/navigation/routes.tsx
Labels: Jira Synced

#5208 Feat (CX-1768): handle data in notification
  src/lib/AndroidApp.tsx
  src/lib/store/GlobalStore.tsx
  src/lib/store/GlobalStoreModel.ts
  src/lib/store/PendingPushNotificationModel.ts
  src/lib/store/__tests__/migration-tests.ts
  src/lib/store/migration.ts
  src/lib/utils/PushNotification.ts
  src/lib/utils/__tests__/PushNotification-tests.ts
  src/setupJest.ts
Labels: Jira Synced

#5202 feat(FX-3143): dynamic state for saved search v2
  src/__generated__/ArtistAboveTheFoldQuery.graphql.ts
  src/__generated__/ArtistArtworksQuery.graphql.ts
  src/__generated__/ArtistArtworks_artist.graphql.ts
  src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
  src/lib/Components/Artist/ArtistArtworks/SavedSearchBanner.tsx
  src/lib/Components/Artist/ArtistArtworks/SavedSearchButton.tsx
  src/lib/Components/Artist/ArtistArtworks/__tests__/SavedSearchButton-tests.tsx
  src/lib/Components/ArtworkFilter/ArtworkFilterHelpers.ts
  src/lib/Components/ArtworkFilter/SavedSearch/__tests__/searchCriteriaHelpers-tests.ts
  src/lib/Components/ArtworkFilter/SavedSearch/constants.ts
  src/lib/Components/ArtworkFilter/SavedSearch/convertersToFilterParams.ts
  src/lib/Components/ArtworkFilter/SavedSearch/searchCriteriaHelpers.ts
  src/lib/Components/ArtworkFilter/__tests__/FilterArtworksHelpers-tests.tsx
  src/lib/Scenes/SavedSearchAlert/Components/Form.tsx
  src/lib/Scenes/SavedSearchAlert/Components/__tests__/Form-tests.tsx
  src/lib/Scenes/SavedSearchAlert/CreateSavedSearchAlert.tsx
  src/lib/Scenes/SavedSearchAlert/SavedSearchAlertForm.tsx
  src/lib/Scenes/SavedSearchAlert/SavedSearchAlertModel.ts
  src/lib/Scenes/SavedSearchAlert/__tests__/SavedSearchAlertForm-tests.tsx
  src/lib/Scenes/SavedSearchAlert/__tests__/helpers-tests.ts
  src/lib/Scenes/SavedSearchAlert/helpers.ts
Labels: Jira Synced

#5207 feat(FX-3109): tag page
  Podfile.lock
  src/__generated__/About_tag.graphql.ts
  src/__generated__/TagArtworksPaginationQuery.graphql.ts
  src/__generated__/TagArtworksTestsQuery.graphql.ts
  src/__generated__/TagArtworks_tag.graphql.ts
  src/__generated__/TagHeader_tag.graphql.ts
  src/__generated__/TagQuery.graphql.ts
  src/__generated__/TagTestsQuery.graphql.ts
  src/lib/AppRegistry.tsx
  src/lib/Components/ArtworkFilter/ArtworkFilterHelpers.ts
  src/lib/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx
  src/lib/Components/ArtworkFilter/ArtworkFilterStore.tsx
  src/lib/Components/ArtworkFilter/Filters/SortOptions.tsx
  src/lib/Components/Tag/About.tsx
  src/lib/Components/Tag/TagArtworks.tsx
  src/lib/Components/Tag/TagPlaceholder.tsx
  src/lib/Components/Tag/__tests__/About-tests.tsx
  src/lib/Components/Tag/__tests__/TagArtworks-tests.tsx
  src/lib/Scenes/Tag/Tag.tsx
  src/lib/Scenes/Tag/TagHeader.tsx
  src/lib/Scenes/Tag/__tests__/Tag-tests.tsx
  src/lib/Scenes/Tag/__tests__/TagHeader-tests.tsx
  src/lib/navigation/routes.tsx
  src/lib/utils/track/schema.ts
  src/setupJest.ts
Labels: Jira Synced

#5210 fix(CX-1776): Dont show broken image when auction result screen loads
  src/lib/Scenes/AuctionResult/AuctionResult.tsx
Labels: Jira Synced

#5235 fix: Remove deprecated object-form attrs({}) keys
  src/lib/Components/ArtworkTileRail/ArtworkTileRailCard.tsx
  src/lib/Components/Home/CardRailCard.tsx
  src/lib/Components/SaleArtworkTileRailCard/SaleArtworkTileRailCard.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkList/MyCollectionArtworkListItem.tsx
  src/lib/Scenes/Search/Search.tsx
Labels: Squash On Green

#5232 feat(cx-1768): fix concerns raised in handling of push notifications
  src/lib/AndroidApp.tsx
  src/lib/store/PendingPushNotificationModel.ts
  src/lib/store/__tests__/migration-tests.ts
  src/lib/store/migration.ts
  src/lib/utils/PushNotification.ts
  src/lib/utils/__tests__/PushNotification-tests.ts
  src/lib/utils/useInitialNotification.ts
  src/setupJest.ts
Labels: Jira Synced

#5233 chore: Refine detect-secrets hook and add it to CircleCI workflow
  .circleci/config.yml
  .secrets.baseline
  package.json
  scripts/detect-secrets
  yarn.lock
Labels: Jira Synced

#5165 feat: use liveArtwork to determine isOfferableFromInquiry
  src/__generated__/ComposerTestsQuery.graphql.ts
  src/__generated__/ConversationCTATestsQuery.graphql.ts
  src/__generated__/ConversationCTA_conversation.graphql.ts
  src/__generated__/ConversationQuery.graphql.ts
  src/__generated__/ConversationRefetchQuery.graphql.ts
  src/__generated__/ConversationTestsQuery.graphql.ts
  src/__generated__/OpenInquiryModalButtonQuery.graphql.ts
  src/__generated__/OpenInquiryModalButtonTestsQuery.graphql.ts
  src/lib/Scenes/Inbox/Components/Conversations/ConversationCTA.tsx
  src/lib/Scenes/Inbox/Components/Conversations/OpenInquiryModalButton.tsx
  src/lib/Scenes/Inbox/Components/Conversations/__tests__/Composer-tests.tsx
  src/lib/Scenes/Inbox/Components/Conversations/__tests__/ConversationCTA-tests.tsx
  src/lib/Scenes/Inbox/Components/Conversations/__tests__/OpenInquiryModalButton-tests.tsx
Labels: Jira Synced

#5143 feat(cx-1636): send token to gravity
  CHANGELOG.legacy.yml
  src/lib/AndroidApp.tsx
  src/lib/Components/Artist/ArtistArtworks/SavedSearchBanner.tsx
  src/lib/Components/Artist/ArtistArtworks/SavedSearchButton.tsx
  src/lib/Components/Artist/ArtistArtworks/__tests__/SavedSearchButton-tests.tsx
  src/lib/Components/PopoverMessage/__tests__/PopoverMessage-tests.tsx
  src/lib/Scenes/SavedSearchAlert/CreateSavedSearchAlert.tsx
  src/lib/Scenes/SavedSearchAlertsList/Components/SavedSearchListItem.tsx
  src/lib/Scenes/SavedSearchAlertsList/Components/__tests__/SavedSearchesList-tests.tsx
  src/lib/Scenes/SavedSearchAlertsList/SavedSearchAlertsList.tsx
  src/lib/utils/PushNotification.ts
  src/lib/utils/__tests__/PushNotification-tests.ts
  src/palette/elements/Pill/Pill.tsx
Labels: Jira Synced

#5193 Enhancement(CX-1637): Reenable push notifications in user profile setting
  .secrets.baseline
  src/lib/Scenes/MyProfile/MyProfile.tsx
  src/lib/Scenes/MyProfile/MyProfilePushNotifications.tsx
  src/lib/Scenes/MyProfile/__tests__/MyProfile-tests.tsx
  src/lib/Scenes/MyProfile/__tests__/MyProfilePushNotifications-tests.tsx
Labels: Jira Synced

#5239 feat: reorder artwork filters on artist series screen
  src/lib/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx
Labels: Jira Synced

#5241 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#5226 feat(FX-3112): edit saved search alert
  src/__generated__/EditSavedSearchAlertQuery.graphql.ts
  src/__generated__/EditSavedSearchAlert_artist.graphql.ts
  src/__generated__/EditSavedSearchAlert_artworksConnection.graphql.ts
  src/__generated__/SavedSearchAlertQuery.graphql.ts
  src/__generated__/SavedSearchAlertsListQuery.graphql.ts
  src/__generated__/SavedSearchesListQuery.graphql.ts
  src/__generated__/SavedSearchesListTestsQuery.graphql.ts
  src/__generated__/SavedSearchesList_me.graphql.ts
  src/__generated__/updateSavedSearchAlertMutation.graphql.ts
  src/lib/AppRegistry.tsx
  src/lib/Scenes/MyProfile/MyProfile.tsx
  src/lib/Scenes/SavedSearchAlert/Components/EditSavedSearchAlertPlaceholder.tsx
  src/lib/Scenes/SavedSearchAlert/Components/Form.tsx
  src/lib/Scenes/SavedSearchAlert/CreateSavedSearchAlert.tsx
  src/lib/Scenes/SavedSearchAlert/EditSavedSearchAlert.tsx
  src/lib/Scenes/SavedSearchAlert/SavedSearchAlert.tsx
  src/lib/Scenes/SavedSearchAlert/SavedSearchAlertForm.tsx
  src/lib/Scenes/SavedSearchAlert/__tests__/EditSavedSearchAlert-tests.tsx
  src/lib/Scenes/SavedSearchAlert/__tests__/SavedSearchAlertForm-tests.tsx
  src/lib/Scenes/SavedSearchAlert/mutations/updateSavedSearchAlert.ts
  src/lib/Scenes/SavedSearchAlertsList/Components/SavedSearchesList.tsx
  src/lib/navigation/routes.tsx
Labels: Jira Synced

#5246 chore(testing): add hooks testing library too
  .secrets.baseline
  HACKS.md
  package.json
  patches/@testing-library+react-native+7.2.0.patch
  src/lib/tests/extractText.ts
  src/lib/utils/__tests__/useEventTiming-tests.ts
  src/lib/utils/__tests__/useGlobalState-tests.tsx
  src/lib/utils/useEventTiming.tsx
  yarn.lock
Labels: Squash On Green

#5243 feat: reorder artwork filters on fair screen
  src/lib/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx
Labels: Jira Synced

#5231 feat(FX-3115): delete saved search alert
  src/__generated__/deleteSavedSearchAlertMutation.graphql.ts
  src/lib/Scenes/MyProfile/MyProfile.tsx
  src/lib/Scenes/SavedSearchAlert/EditSavedSearchAlert.tsx
  src/lib/Scenes/SavedSearchAlert/SavedSearchAlertForm.tsx
  src/lib/Scenes/SavedSearchAlert/__tests__/SavedSearchAlertForm-tests.tsx
  src/lib/Scenes/SavedSearchAlert/mutations/deleteSavedSearchAlert.ts
Labels: Jira Synced

#5250 chore: align artworks filters on gallery screen
  src/__generated__/PartnerArtworkInfiniteScrollGridQuery.graphql.ts
  src/__generated__/PartnerArtworkTestsQuery.graphql.ts
  src/__generated__/PartnerArtwork_partner.graphql.ts
  src/__generated__/PartnerQuery.graphql.ts
  src/__generated__/PartnerRefetchQuery.graphql.ts
  src/__generated__/VanityURLEntityQuery.graphql.ts
  src/lib/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx
  src/lib/Scenes/Partner/Components/PartnerArtwork.tsx
Labels: Jira Synced

#5257 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#5256 enhancement: improve tracking for "unable to load"
  src/lib/Components/LoadFailureView.tsx
  src/lib/relay/middlewares/errorMiddleware.ts
Labels: Jira Synced, Squash On Green

#5237 feat(FX-3113): Admin can submit "create alert" form
  src/__generated__/SavedSearchButtonRefetchQuery.graphql.ts
  src/__generated__/createSavedSearchAlertMutation.graphql.ts
  src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
  src/lib/Components/Artist/ArtistArtworks/SavedSearchButton.tsx
  src/lib/Components/Artist/ArtistArtworks/__tests__/SavedSearchButton-tests.tsx
  src/lib/Components/ArtworkFilter/SavedSearch/__tests__/searchCriteriaHelpers-tests.ts
  src/lib/Components/ArtworkFilter/SavedSearch/searchCriteriaHelpers.ts
  src/lib/Components/FancyModal/FancyModalHeader.tsx
  src/lib/Scenes/SavedSearchAlert/Components/Form.tsx
  src/lib/Scenes/SavedSearchAlert/CreateSavedSearchAlert.tsx
  src/lib/Scenes/SavedSearchAlert/SavedSearchAlertForm.tsx
  src/lib/Scenes/SavedSearchAlert/SavedSearchAlertModel.ts
  src/lib/Scenes/SavedSearchAlert/__tests__/CreateSavedSearchAlert-tests.tsx
  src/lib/Scenes/SavedSearchAlert/__tests__/SavedSearchAlertForm-tests.tsx
  src/lib/Scenes/SavedSearchAlert/__tests__/helpers-tests.ts
  src/lib/Scenes/SavedSearchAlert/helpers.ts
  src/lib/Scenes/SavedSearchAlert/mutations/createSavedSearchAlert.ts
Labels: Jira Synced

#5255 feat(FX-3144): saved search name input is limited to 75 characters
  src/lib/Scenes/SavedSearchAlert/Components/Form.tsx
  src/lib/Scenes/SavedSearchAlert/SavedSearchAlertForm.tsx
  src/lib/Scenes/SavedSearchAlert/__tests__/SavedSearchAlertForm-tests.tsx
  src/lib/Scenes/SavedSearchAlert/mutations/updateSavedSearchAlert.ts
  src/lib/Scenes/SavedSearchAlertsList/Components/EmptyMessage.tsx
Labels: Jira Synced

#5252 feat: reorder artwork for sale filters on artist screen
  src/lib/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx
  src/lib/Components/ArtworkFilter/Filters/__tests__/AdditionalGeneIDsOptions-tests.tsx
  src/lib/Components/ArtworkFilter/__tests__/FilterModal-tests.tsx
Labels: Jira Synced

#5266 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#5244 fix: iOS 15 photo picker thread
  Artsy/Views/Styled_Subclasses/Buttons/ARNavigationButton.m
  emission/Pod/Classes/EigenCommunications/ARPHPhotoPickerModule.m
Labels: Jira Synced

#5258 fix(make help, detect-secrets): adding detect-secrets with python, `make help`
  .circleci/config.yml
  .husky/post-merge
  .husky/pre-commit
  .husky/pre-push
  .nvmrc
  .tool-versions
  Makefile
  Podfile
  Podfile.lock
  docs/getting_started.md
  package.json
  requirements.txt
  scripts/detect-secrets
  scripts/diagnose.js
  scripts/help.js
  scripts/install
  yarn.lock
Labels: Jira Synced, Squash On Green

#5272 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#5276 Revert "feat: show notifs when saved addresses added, updated, or deleted"
  src/lib/Scenes/SavedAddresses/SavedAddressNotification.tsx
  src/lib/Scenes/SavedAddresses/SavedAddresses.tsx
  src/lib/Scenes/SavedAddresses/SavedAddressesForm.tsx
  src/lib/Scenes/SavedAddresses/__tests__/SavedAddresses-tests.tsx
  src/lib/navigation/navigate.ts
Labels: Merge On Green

#5268 feat(FX-3190): use saved search banner M2 design for M1
  src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
  src/lib/Components/Artist/ArtistArtworks/SavedSearchBanner.tsx
  src/lib/Components/Artist/ArtistArtworks/__tests__/SavedSearchBanner-tests.tsx
  src/lib/Scenes/Artist/__tests__/ArtistSavedSearch-tests.tsx
Labels: Jira Synced

#5281 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#5282 chore: adds feat flag to phone validation error msg
  src/lib/Components/PhoneInput/PhoneInput.tsx
  src/lib/store/config/features.ts
Labels: Jira Synced, Squash On Green

#5278 feat(FX-3191): add “View artworks” button for edit saved search alert screen
  src/__generated__/ArtistAboveTheFoldQuery.graphql.ts
  src/__generated__/ArtistArtworksQuery.graphql.ts
  src/__generated__/ArtistArtworks_artist.graphql.ts
  src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
  src/lib/Scenes/Artist/SearchCriteria.tsx
  src/lib/Scenes/SavedSearchAlert/Components/EditSavedSearchAlertPlaceholder.tsx
  src/lib/Scenes/SavedSearchAlert/Components/Form.tsx
  src/lib/Scenes/SavedSearchAlert/SavedSearchAlertForm.tsx
  src/lib/Scenes/SavedSearchAlert/__tests__/EditSavedSearchAlert-tests.tsx
Labels: Jira Synced

#5279 feat(FX-3192): ask notification permissions
  .secrets.baseline
  Podfile.lock
  src/lib/Components/Artist/ArtistArtworks/SavedSearchBanner.tsx
  src/lib/Components/Artist/ArtistArtworks/__tests__/SavedSearchBanner-tests.tsx
  src/lib/NativeModules/LegacyNativeModules.tsx
  src/lib/Scenes/MyProfile/MyProfilePushNotifications.tsx
  src/lib/Scenes/MyProfile/__tests__/MyProfilePushNotifications-tests.tsx
  src/lib/Scenes/SavedSearchAlert/Components/Form.tsx
  src/lib/Scenes/SavedSearchAlert/SavedSearchAlertForm.tsx
  src/lib/Scenes/SavedSearchAlert/__tests__/CreateSavedSearchAlert-tests.tsx
  src/lib/Scenes/SavedSearchAlert/__tests__/EditSavedSearchAlert-tests.tsx
  src/lib/Scenes/SavedSearchAlert/__tests__/SavedSearchAlertForm-tests.tsx
  src/lib/tests/mockFetchNotificationPermissions.ts
  src/lib/utils/PushNotification.ts
  src/lib/utils/__tests__/PushNotification-tests.ts
Labels: Jira Synced

#5287 chore: Tag and Gene filter Alignment
  src/__generated__/GeneArtworksPaginationQuery.graphql.ts
  src/__generated__/GeneArtworksTestsQuery.graphql.ts
  src/__generated__/GeneArtworks_gene.graphql.ts
  src/__generated__/GeneQuery.graphql.ts
  src/__generated__/GeneTestsQuery.graphql.ts
  src/__generated__/TagArtworksPaginationQuery.graphql.ts
  src/__generated__/TagArtworksTestsQuery.graphql.ts
  src/__generated__/TagArtworks_tag.graphql.ts
  src/__generated__/TagQuery.graphql.ts
  src/__generated__/TagTestsQuery.graphql.ts
  src/lib/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx
  src/lib/Components/Gene/GeneArtworks.tsx
  src/lib/Components/Tag/TagArtworks.tsx
Labels: Jira Synced

#5289 chore: standardize ampersands in filter titles
  src/lib/Components/ArtworkFilter/ArtworkFilterHelpers.ts
  src/lib/Components/ArtworkFilter/Filters/__tests__/GalleriesAndInstitutionsOptions-tests.tsx
Labels: Jira Synced, Squash On Green

#5288 feat: show relevant error messages on the onboarding
  src/lib/Scenes/Onboarding/OnboardingCreateAccount/OnboardingCreateAccount.tsx
  src/lib/Scenes/Onboarding/OnboardingSocialPick.tsx
  src/lib/Scenes/Onboarding/OnboardingWelcome.tsx
  src/lib/Scenes/Onboarding/__tests__/OnboardingWelcome-tests.tsx
  src/lib/store/AuthModel.ts
  src/lib/store/__tests__/AuthModel-tests.ts
  src/lib/store/config/features.ts
Labels: Jira Synced

#5291 chore: update aggregations for show artworks
  src/__generated__/ShowArtworksInfiniteScrollGridQuery.graphql.ts
  src/__generated__/ShowArtworksTestsQuery.graphql.ts
  src/__generated__/ShowArtworks_show.graphql.ts
  src/__generated__/ShowQuery.graphql.ts
  src/__generated__/ShowTestsQuery.graphql.ts
  src/lib/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx
  src/lib/Scenes/Show/Components/ShowArtworks.tsx
Labels: Jira Synced

#5227 feature: Checkbox V3
  src/lib/Components/Bidding/Components/__tests__/Checkbox-tests.tsx
  src/lib/Components/Bidding/Screens/ConfirmBid/index.tsx
  src/lib/Components/Bidding/Screens/Registration.tsx
  src/lib/Components/Bidding/Screens/__tests__/ConfirmBid-tests.tsx
  src/lib/Components/Bidding/Screens/__tests__/Registration-tests.tsx
  src/lib/Components/Bidding/__tests__/BidFlow-tests.tsx
  src/lib/Scenes/Artwork/Components/CommercialButtons/InquiryModal.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkFormModal/Screens/MyCollectionArtworkFormAdditionalDetails.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkFormModal/Screens/__tests__/MyCollectionArtworkFormAdditionalDetails-tests.tsx
  src/lib/Scenes/Onboarding/OnboardingCreateAccount/EmailSubscriptionCheckbox.tsx
  src/lib/Scenes/Onboarding/OnboardingCreateAccount/TermsOfServiceCheckbox.tsx
  src/lib/Scenes/Onboarding/OnboardingCreateAccount/__tests__/OnboardingCreateAccount-tests.tsx
  src/lib/Scenes/Onboarding/__tests__/OnboardingLogin-tests.tsx
  src/lib/Scenes/Onboarding/__tests__/OnboardingWelcome-tests.tsx
  src/lib/Scenes/SavedAddresses/SavedAddressesForm.tsx
  src/lib/Scenes/SavedAddresses/__tests__/SavedAddressesForm-tests.tsx
  src/palette/elements/Checkbox/Checkbox.stories.tsx
  src/palette/elements/Checkbox/Checkbox.tsx
  src/palette/elements/Checkbox/CheckboxV2.stories.tsx
  src/palette/elements/Checkbox/CheckboxV2.tsx
  src/palette/elements/Checkbox/__tests__/Checkbox-tests.tsx
  src/palette/elements/Checkbox/index.ts
  src/palette/elements/Checkbox/index.tsx
  src/storybook/helpers.tsx
  src/storybook/storyLoader.js
Labels: Jira Synced, Squash On Green

#5296 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#5293 fix(viewing room): dont show artwork rail if 0 artworks
  src/__generated__/ViewingRoomQuery.graphql.ts
  src/__generated__/ViewingRoomTestsQuery.graphql.ts
  src/__generated__/ViewingRoom_viewingRoom.graphql.ts
  src/lib/Scenes/ViewingRoom/ViewingRoom.tsx
  src/lib/Scenes/ViewingRoom/__tests__/ViewingRoom-tests.tsx
Labels: Squash On Green

#5298 chore: Update release notes
  fastlane/metadata/android/en-US/changelogs/default.txt
  fastlane/metadata/en-US/release_notes.txt
Labels: Squash On Green

#5299 fix: typo to call function
  scripts/changelog/commitChangelog.js
Labels: Squash On Green

#5302 Enhancement: Track Link Tap in Auction Results For You
  src/lib/Scenes/AuctionResultsForYou/AuctionResultsForYou.tsx
Labels: Jira Synced

#5301 Update Changelog ✍️
  CHANGELOG/android-changelog.md
  CHANGELOG/ios-changelog.md
Labels: Squash On Green

#5307 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#5230 feature(CX-1796): Introduce AboveTheFoldQueryRenderer to Home screen
  Podfile.lock
  src/__generated__/HomeAboveTheFoldQuery.graphql.ts
  src/__generated__/HomeBelowTheFoldQuery.graphql.ts
  src/__generated__/HomeRefetchQuery.graphql.ts
  src/__generated__/Home_homePageAbove.graphql.ts
  src/__generated__/Home_homePageBelow.graphql.ts
  src/__generated__/Home_meAbove.graphql.ts
  src/__generated__/Home_meBelow.graphql.ts
  src/lib/Scenes/Home/Components/FairsRail.tsx
  src/lib/Scenes/Home/Home.tsx
  src/lib/Scenes/Home/__tests__/Home-tests.tsx
  src/lib/utils/AboveTheFoldQueryRenderer.tsx
Labels: Jira Synced

#5305 feat(FX-3202): add analytic events for saved search M2
  src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
  src/lib/Components/Artist/ArtistArtworks/SavedSearchButton.tsx
  src/lib/Components/Artist/ArtistArtworks/__tests__/SavedSearchButton-tests.tsx
  src/lib/Scenes/SavedSearchAlert/Components/Form.tsx
  src/lib/Scenes/SavedSearchAlert/EditSavedSearchAlert.tsx
  src/lib/Scenes/SavedSearchAlert/SavedSearchAlertForm.tsx
  src/lib/Scenes/SavedSearchAlert/SavedSearchAlertModel.ts
  src/lib/Scenes/SavedSearchAlert/__tests__/CreateSavedSearchAlert-tests.tsx
  src/lib/Scenes/SavedSearchAlert/__tests__/SavedSearchAlertForm-tests.tsx
  src/lib/Scenes/SavedSearchAlertsList/Components/SavedSearchesList.tsx
  src/lib/utils/track/schema.ts
Labels: Jira Synced

#5310 fix: artwork filter helpers increment and "All" issue
  src/lib/Components/ArtworkFilter/ArtworkFilterHelpers.ts
Labels: Jira Synced

#5315 fix: remove brew update distribute-macos script
  .circleci/config.yml
  scripts/setup-distribute-macos
Labels: Squash On Green

#5309 feature(CX-1697): V3 Select
  src/lib/Components/Artist/ArtistInsights/MarketStats.tsx
  src/lib/Components/Bidding/Screens/SelectMaxBid.tsx
  src/lib/Components/Bidding/Screens/__tests__/BillingAddress-tests.tsx
  src/lib/Components/Bidding/__tests__/BidFlow-tests.tsx
  src/lib/Components/CountrySelect.tsx
  src/lib/Components/PhoneInput/PhoneInput.tsx
  src/lib/Components/PhoneInput/__tests__/PhoneInput-tests.tsx
  src/lib/Scenes/Consignments/Screens/Metadata.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkFormModal/Components/Dimensions.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkFormModal/Components/MediumPicker.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkFormModal/Components/__tests__/MediumPicker-tests.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkFormModal/Screens/MyCollectionArtworkFormAdditionalDetails.tsx
  src/lib/Scenes/MyProfile/MyProfilePaymentNewCreditCard.tsx
  src/palette/elements/Select/Select.stories.tsx
  src/palette/elements/Select/Select.tsx
  src/palette/elements/Select/SelectV2.stories.tsx
  src/palette/elements/Select/SelectV2.tsx
  src/palette/elements/Select/__tests__/Select-tests.tsx
  src/palette/elements/Select/index.tsx
  src/storybook/helpers.tsx
  src/storybook/storyLoader.js
Labels: Jira Synced, Squash On Green

#5297 feat(FX-3195): dialog component
  src/palette/elements/Dialog/Dialog.stories.tsx
  src/palette/elements/Dialog/Dialog.tsx
  src/palette/elements/Dialog/__tests__/Dialog-tests.tsx
  src/palette/elements/Dialog/index.ts
  src/palette/elements/index.tsx
  src/storybook/storyLoader.js
Labels: Jira Synced

#5317 feat(FX-3214): apply custom Dialog for confirm saved search delete
  src/lib/Scenes/SavedSearchAlert/SavedSearchAlertForm.tsx
  src/lib/Scenes/SavedSearchAlert/__tests__/SavedSearchAlertForm-tests.tsx
Labels: Jira Synced

#5269 chore: adjust SDK integration
  .circleci/config.yml
  Artsy.xcodeproj/project.pbxproj
  Artsy/App/ARAppDelegate.m
  Artsy_Tests/Supporting_Files/ARTestHelper.m
  Podfile
  Podfile.lock
  package.json
  scripts/source-for-bash-env
  src/lib/utils/track/SegmentTrackingProvider.ts
  yarn.lock
Labels: Squash On Green

#5320 feat: add saved addresses notifs using toast hook
  src/lib/Scenes/SavedAddresses/SavedAddresses.tsx
  src/lib/Scenes/SavedAddresses/SavedAddressesForm.tsx
Labels: Merge On Green, Jira Synced

#5321 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#5323 fix(FX-3218): update copies saved search
  src/lib/Scenes/SavedSearchAlert/CreateSavedSearchAlert.tsx
Labels: Jira Synced

#5327 fix: Dont restrict number of artwork rails in home screen above-the-fold query
  src/__generated__/HomeAboveTheFoldQuery.graphql.ts
  src/__generated__/HomeRefetchQuery.graphql.ts
  src/__generated__/Home_homePageAbove.graphql.ts
  src/lib/Scenes/Home/Home.tsx
Labels: Squash On Green

#5322 fix: place saved alerts under my collection
  src/lib/Scenes/MyProfile/MyProfile.tsx
Labels: Jira Synced

#5330 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#5318 feat(FX-3210): show SS only when applied filters
  src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
  src/lib/Components/Artist/ArtistArtworks/SavedSearchBanner.tsx
  src/lib/Components/Artist/ArtistArtworks/SavedSearchButton.tsx
  src/lib/Scenes/Artist/__tests__/ArtistSavedSearch-tests.tsx
Labels: Jira Synced

#5308 feat(FX-3146): Filter menu displays number of active filters per facet
  src/lib/Components/ArtworkFilter/ArtworkFilterHelpers.ts
  src/lib/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx
  src/lib/Components/ArtworkFilter/ArtworkFilterStore.tsx
  src/lib/Components/ArtworkFilter/__tests__/FilterArtworksHelpers-tests.tsx
Labels: Jira Synced

#5265 feat(FX-3188): update popover message to v3 design system
  src/lib/Components/PopoverMessage/PopoverMessage.tsx
  src/lib/Components/PopoverMessage/__tests__/PopoverMessage-tests.tsx
Labels: Jira Synced

#5345 fix(FX-3235): track toggle saved search event
  src/lib/Components/Artist/ArtistArtworks/SavedSearchButton.tsx
  src/lib/Components/Artist/ArtistArtworks/__tests__/SavedSearchButton-tests.tsx
  src/lib/Scenes/SavedSearchAlert/CreateSavedSearchAlert.tsx
  src/lib/Scenes/SavedSearchAlert/SavedSearchAlertForm.tsx
  src/lib/Scenes/SavedSearchAlert/SavedSearchAlertModel.ts
  src/lib/Scenes/SavedSearchAlert/__tests__/CreateSavedSearchAlert-tests.tsx
  src/lib/Scenes/SavedSearchAlert/mutations/createSavedSearchAlert.ts
  src/lib/Scenes/SavedSearchAlert/mutations/updateSavedSearchAlert.ts
Labels: Jira Synced

#5343 feature: RadioButton V3
  Podfile.lock
  src/lib/Scenes/Inbox/Components/Conversations/EditionSelectBox.tsx
  src/palette/elements/Radio/RadioButton.stories.tsx
  src/palette/elements/Radio/RadioButton.tsx
  src/palette/elements/Radio/__tests__/RadioButton-tests.tsx
  src/palette/elements/Radio/index.tsx
  src/storybook/storyLoader.js
Labels: Jira Synced, Squash On Green

#5350 feat(FX-3228): global combined search results by default
  src/lib/Scenes/Search2/Search2.tsx
  src/lib/Scenes/Search2/__tests__/Search2-tests.tsx
Labels: Jira Synced

#5352 fix: Scrollview in make offer modal
  src/lib/Scenes/Inbox/Components/Conversations/MakeOfferModal.tsx
Labels: Jira Synced, Squash On Green

#5353 chore: remove extra info from description #trivial
  fastlane/metadata/android/en-US/full_description.txt
Labels: Squash On Green

#5348 feat:navigate back in BNMO [PURCHASE-840]
  src/lib/Components/ArtsyReactWebView.tsx
  src/lib/Components/FancyModal/FancyModalHeader.tsx
  src/lib/navigation/routes.tsx
Labels: Jira Synced

#5357 Update metaphysics schema
  data/schema.graphql
  src/__generated__/Search2Query.graphql.ts
Labels: Merge On Green

#5356 fix: Set Palette V3 toggle title correctly
  src/lib/AppProviders.tsx
Labels: Squash On Green

#5360 feat(FX-3239): Pill component enhancement and stories
  src/lib/Scenes/Search2/Search2.tsx
  src/palette/elements/Pill/Pill.stories.tsx
  src/palette/elements/Pill/Pill.tsx
  src/storybook/storyLoader.js
Labels: Jira Synced

#5361 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#5362 feat(FX-3226): add dynamic rendering of indices
  src/__generated__/Search2Query.graphql.ts
  src/lib/Scenes/Search2/Search2.tsx
  src/lib/Scenes/Search2/__tests__/Search2-tests.tsx
Labels: Jira Synced, Squash On Green

#5355 chore: firebase app distribution
  .gitignore
  Gemfile.lock
  fastlane/Fastfile
  fastlane/Pluginfile
  scripts/setup-distribute-linux
Labels: Jira Synced

#5354 fix(FX-3223): correct logic for displaying the selected insight filters
  src/lib/Components/ArtworkFilter/Filters/AuctionHouseOptions.tsx
  src/lib/Components/ArtworkFilter/Filters/CategoriesOptions.tsx
  src/lib/Components/ArtworkFilter/Filters/MultiSelectCheckOption.tsx
  src/lib/Components/ArtworkFilter/Filters/SizesOptions.tsx
Labels: Jira Synced

#5363 Enhancement(CX-1641): remove push notification asyncstorage flag
  .secrets.baseline
  src/lib/Scenes/MyProfile/MyProfile.tsx
  src/lib/Scenes/MyProfile/__tests__/MyProfile-tests.tsx
  src/lib/utils/AdminMenu.tsx
  src/lib/utils/PushNotification.ts
  src/lib/utils/__tests__/PushNotification-tests.ts
Labels: Jira Synced

#5359 fix:refetch data after deleting [PURCHASE-2899]
  src/lib/Scenes/SavedAddresses/SavedAddresses.tsx
Labels: Jira Synced

#5367 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green
