Repository artsy/eigen, pull requests merged in 2021-06, with the labels that each got.

#4903 Feat(fx-2960) saved search feature flag
  CHANGELOG.yml
  src/lib/store/config/features.ts
Labels: Jira Synced

#4897 fix: apply "cancel all" instantly
  CHANGELOG.yml
  src/lib/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx
  src/lib/Components/ArtworkFilter/ArtworkFilterStore.tsx
  src/lib/Components/ArtworkFilter/__tests__/ArtworkFiltersStore-tests.tsx
  src/lib/Components/ArtworkFilter/__tests__/FilterModal-tests.tsx
Labels: Jira Synced

#4907 chore: Prepare for development, 6.9.4
  CHANGELOG.yml
  app.json
Labels: Squash On Green

#4888 chore: remove ARUseImprovedArtworkFilters feature flag
  CHANGELOG.yml
  src/lib/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx
  src/lib/Components/ArtworkFilter/Filters/PriceRangeOptions.tsx
  src/lib/Components/ArtworkFilter/Filters/PriceRangeOptionsNew.tsx
  src/lib/Components/ArtworkFilter/Filters/PriceRangeOptionsOld.tsx
  src/lib/Components/ArtworkFilter/Filters/SizeOptions.tsx
  src/lib/Components/ArtworkFilter/Filters/SizeOptionsNew.tsx
  src/lib/Components/ArtworkFilter/Filters/SizeOptionsOld.tsx
  src/lib/Components/ArtworkFilter/Filters/__tests__/PriceRangeOptions-tests.tsx
  src/lib/Components/ArtworkFilter/Filters/__tests__/PriceRangeOptionsNew-tests.tsx
  src/lib/Components/ArtworkFilter/Filters/__tests__/SizeOptions-tests.tsx
  src/lib/store/config/features.ts
Labels: Jira Synced

#4906 fix: Reduce padding between titles and the artwork grids
  CHANGELOG.yml
  src/lib/Scenes/Artwork/Components/OtherWorks/OtherWorks.tsx
Labels: Squash On Green

#4909 feature(analytics): adding braze on android
  HACKS.md
  android/build.gradle
  package.json
  patches/@segment+analytics-react-native-appboy+1.4.8.patch
  src/lib/utils/track/SegmentTrackingProvider.ts
  yarn.lock
Labels: Jira Synced, Squash On Green

#4910 feat: admin sees saved search banner
  CHANGELOG.yml
  src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
  src/lib/Components/Artist/ArtistArtworks/SavedSearchBanner.tsx
  src/lib/Components/Artist/ArtistArtworks/__tests__/SavedSearchBanner-tests.tsx
Labels: Jira Synced, Squash On Green

#4896 feat: User sees skeleton loading screen (PX-4120)
  CHANGELOG.yml
  src/lib/Scenes/OrderHistory/OrderDetails/OrderDetails.tsx
Labels: Jira Synced

#4911 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4889 fix: User can see order info on each row PX-4065
  src/__generated__/OrderHistoryPaginationQuery.graphql.ts
  src/__generated__/OrderHistoryQuery.graphql.ts
  src/__generated__/OrderHistoryRow_order.graphql.ts
  src/__generated__/OrderHistoryTestsQuery.graphql.ts
  src/__generated__/OrderHistory_me.graphql.ts
  src/lib/Scenes/OrderHistory/OrderHistory.tsx
  src/lib/Scenes/OrderHistory/OrderHistoryRow.tsx
  src/lib/Scenes/OrderHistory/__tests__/OrderHistoryRow-tests.tsx
Labels: Jira Synced, Squash On Green

#4913 fix: send only changed filter params in the analytics event
  CHANGELOG.yml
  src/lib/Components/ArtworkFilter/ArtworkFilterHelpers.ts
  src/lib/Components/ArtworkFilter/__tests__/FilterArtworksHelpers-tests.tsx
Labels: Jira Synced

#4808 feat: implement UI AuctionResults section with mock data for home screen and create AuctionResultForYou screen
  CHANGELOG.yml
  src/__generated__/AuctionResultForYouQuery.graphql.ts
  src/__generated__/AuctionResultForYou_collection.graphql.ts
  src/__generated__/AuctionResultsRail_collectionsModule.graphql.ts
  src/lib/AppRegistry.tsx
  src/lib/Scenes/AuctionResultForYou/AuctionResultForYou.tsx
  src/lib/Scenes/AuctionResultForYou/AuctionResultForYouListItem.tsx
  src/lib/Scenes/AuctionResultForYou/__tests__/AuctionResultForYouListItem-tests.tsx
  src/lib/Scenes/Favorites/Favorites.tsx
  src/lib/Scenes/Home/Components/AuctionResultsRail.tsx
  src/lib/Scenes/Home/Home.tsx
  src/lib/navigation/routes.tsx
  src/lib/store/config/features.ts
Labels: Jira Synced

#4920 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4886 fix(CX-1534): double tapping 'log in' opens a blank page
  CHANGELOG.yml
  src/lib/Scenes/Onboarding/OnboardingLogin.tsx
Labels: Jira Synced, Squash On Green

#4915 fix: Vertically aligned 'Follow/Following' artist button text
  CHANGELOG.yml
  src/lib/Scenes/Artwork/Components/FollowArtistButton.tsx
Labels: Squash On Green

#4882 feat(CX-1465): user can enter auction results tab from search
  CHANGELOG.yml
  src/__generated__/AutosuggestResultsPaginationQuery.graphql.ts
  src/__generated__/AutosuggestResultsQuery.graphql.ts
  src/__generated__/AutosuggestResults_results.graphql.ts
  src/lib/Scenes/Search/AutosuggestResults.tsx
  src/lib/Scenes/Search/SearchResult.tsx
  src/lib/Scenes/Search/__tests__/RecentSearches-tests.tsx
  src/lib/Scenes/Search/__tests__/Search-tests.tsx
  src/lib/Scenes/Search/__tests__/SearchModel-tests.tsx
  src/lib/Scenes/Search/__tests__/SearchResult-tests.tsx
Labels: Jira Synced, Squash On Green

#4917 feat(PX-4073): order details payment section
  CHANGELOG.yml
  src/__generated__/OrderDetailsPaymentTestsQuery.graphql.ts
  src/__generated__/OrderDetailsPayment_order.graphql.ts
  src/__generated__/OrderDetailsQuery.graphql.ts
  src/__generated__/OrderDetailsTestsQuery.graphql.ts
  src/__generated__/OrderDetails_order.graphql.ts
  src/lib/Scenes/OrderHistory/OrderDetails/OrderDetails.tsx
  src/lib/Scenes/OrderHistory/OrderDetails/OrderDetailsPayment.tsx
  src/lib/Scenes/OrderHistory/__tests__/OrderDetailsPayment-tests.tsx
Labels: Jira Synced

#4922 fix: wrong displaying in Order History when fields are too long (PX-4065)
  CHANGELOG.yml
  src/lib/Scenes/OrderHistory/OrderHistoryRow.tsx
Labels: Jira Synced

#4919 fix android native go back from sale tab to search
  CHANGELOG.yml
  src/lib/Components/Artist/ArtistConsignButton.tsx
  src/lib/Components/Artist/__tests__/ArtistConsignButton-tests.tsx
  src/lib/Scenes/Consignments/index.tsx
  src/lib/navigation/navigate.ts
Labels: Jira Synced

#4921 fix: prevent home screen placeholders from rerendering
  CHANGELOG.yml
  src/lib/Scenes/Home/Home.tsx
  src/lib/utils/placeholders.tsx
Labels: Jira Synced, Squash On Green

#4928 chore: update pr template jira reference
  CHANGELOG.yml
  docs/pull_request_template.md
Labels: Jira Synced

#4929 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4901 feat: Add latest articles rail to home screen
  CHANGELOG.yml
  package.json
  src/__generated__/ArticleCard_article.graphql.ts
  src/__generated__/ArticlesRail_articlesConnection.graphql.ts
  src/__generated__/Articles_articles.graphql.ts
  src/__generated__/ArtistAboutTestsQuery.graphql.ts
  src/__generated__/ArtistBelowTheFoldQuery.graphql.ts
  src/__generated__/HomeQuery.graphql.ts
  src/__generated__/HomeRefetchQuery.graphql.ts
  src/__generated__/Home_articlesConnection.graphql.ts
  src/lib/Components/ArticleCard.tsx
  src/lib/Components/Artist/Articles/Article.tsx
  src/lib/Components/Artist/Articles/Articles.tsx
  src/lib/Components/Artist/Articles/__tests__/Article-tests.tsx
  src/lib/Components/Artist/ArtistAbout/ArtistAbout.tsx
  src/lib/Components/__tests__/ArticleCard-tests.tsx
  src/lib/Scenes/Home/Components/ArticlesRail.tsx
  src/lib/Scenes/Home/Home.tsx
  src/lib/Scenes/Home/__tests__/homeAnalytics-tests.ts
  src/lib/Scenes/Home/homeAnalytics.ts
  yarn.lock
Labels: Jira Synced

#4918 feat: User can see Order Summary section PX-4071
  CHANGELOG.yml
  src/__generated__/OrderDetailsQuery.graphql.ts
  src/__generated__/OrderDetailsTestsQuery.graphql.ts
  src/__generated__/OrderDetails_order.graphql.ts
  src/__generated__/SummarySectionTestsQuery.graphql.ts
  src/__generated__/SummarySection_section.graphql.ts
  src/lib/Scenes/OrderHistory/OrderDetails/ArtworkInfoSection.tsx
  src/lib/Scenes/OrderHistory/OrderDetails/OrderDetails.tsx
  src/lib/Scenes/OrderHistory/OrderDetails/ShipsToSection.tsx
  src/lib/Scenes/OrderHistory/OrderDetails/SummarySection.tsx
  src/lib/Scenes/OrderHistory/__tests__/OrderDetails-tests.tsx
  src/lib/Scenes/OrderHistory/__tests__/SummarySection-tests.tsx
Labels: Jira Synced

#4930 chore: remove duplicate changelog entries #trivial
  CHANGELOG.yml
Labels: Squash On Green

#4926 feat: create save search mutation
  CHANGELOG.yml
  src/__generated__/ArtistArtworksContainerCreateSavedSearchMutation.graphql.ts
  src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
  src/lib/Components/ArtworkFilter/ArtworkFilterHelpers.ts
  src/lib/Components/ArtworkFilter/__tests__/FilterArtworksHelpers-tests.tsx
Labels: Jira Synced, Squash On Green

#4931 fix: Rename home articles section to market news
  src/lib/Scenes/Home/Components/ArticlesRail.tsx
Labels: Jira Synced

#4908 fix(CX-1529): unable to edit credit card
  CHANGELOG.yml
  HACKS.md
  patches/react-native-credit-card-input+0.4.1.patch
Labels: Jira Synced, Squash On Green

#4936 Update metaphysics schema
  data/schema.graphql
  src/__generated__/ArtistArtworksContainerCreateSavedSearchMutation.graphql.ts
Labels: Merge On Green

#4934 feat: delete saved search mutation
  CHANGELOG.yml
  src/__generated__/ArtistArtworksContainerDeleteSavedSearchMutation.graphql.ts
  src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
Labels: Jira Synced

#4938 fix: Remove artsy react web view top padding
  CHANGELOG.yml
  src/lib/Components/ArtsyReactWebView.tsx
Labels: Jira Synced

#4941 chore: 6.9.4 release prep
  fastlane/metadata/android/en-US/changelogs/default.txt
  fastlane/metadata/en-US/name.txt
  fastlane/metadata/en-US/release_notes.txt
  fastlane/metadata/en-US/subtitle.txt
Labels: Squash On Green

#4933 fix inaccurate validators for artwork submission
  CHANGELOG.yml
  src/lib/Scenes/Consignments/Screens/Metadata.tsx
Labels: Jira Synced

#4932 Feat: (FX-2910) - filter art in collection screen
  CHANGELOG.yml
  src/__generated__/CollectionArtworksFilter_collection.graphql.ts
  src/__generated__/CollectionQuery.graphql.ts
  src/__generated__/CollectionTestsQuery.graphql.ts
  src/__generated__/Collection_collection.graphql.ts
  src/lib/Scenes/Collection/Collection.tsx
  src/lib/Scenes/Collection/Components/CollectionArtworksFilter.tsx
  src/lib/Scenes/Collection/Screens/CollectionArtworks.tsx
Labels: Jira Synced

#4946 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4937 feat: check savedSearch query field
  CHANGELOG.yml
  src/__generated__/SavedSearchBannerCreateSavedSearchMutation.graphql.ts
  src/__generated__/SavedSearchBannerDeleteSavedSearchMutation.graphql.ts
  src/__generated__/SavedSearchBannerQuery.graphql.ts
  src/__generated__/SavedSearchBannerTestsQuery.graphql.ts
  src/__generated__/SavedSearchBanner_me.graphql.ts
  src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
  src/lib/Components/Artist/ArtistArtworks/SavedSearchBanner.tsx
  src/lib/Components/Artist/ArtistArtworks/__tests__/SavedSearchBanner-tests.tsx
  src/lib/Components/ArtworkFilter/ArtworkFilterHelpers.ts
Labels: Jira Synced

#4944 feat: size filter for saved search
  CHANGELOG.yml
  src/lib/Components/ArtworkFilter/ArtworkFilterHelpers.ts
  src/lib/Components/ArtworkFilter/Filters/__tests__/helpers-tests.tsx
  src/lib/Components/ArtworkFilter/Filters/helpers.ts
  src/lib/Components/ArtworkFilter/__tests__/FilterArtworksHelpers-tests.tsx
Labels: Jira Synced

#4927 fix: show approved cta when fulfilled
  CHANGELOG.yml
  Podfile.lock
  src/lib/Scenes/Inbox/Components/Conversations/ConversationCTA.tsx
  src/lib/Scenes/Inbox/Components/Conversations/__tests__/ConversationCTA-tests.tsx
Labels: Jira Synced

#4945 feat: don’t close modal when “clear all” tapped
  CHANGELOG.yml
  src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
  src/lib/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx
  src/lib/Components/ArtworkFilter/__tests__/FilterModal-tests.tsx
Labels: Jira Synced, Squash On Green

#4912 enhancement(CX-1418): add link to Conditions of Sale in sign up
  Artsy/View_Controllers/Login_and_Onboarding/AROnboardingViewController.h
  Artsy/View_Controllers/Login_and_Onboarding/AROnboardingViewController.m
  Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/2_-_Calls_to_Action/ARSignUpSplashViewController.m
  Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/2_-_Calls_to_Action/Views/ARTermsAndConditionsView.m
  Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/5-_Onboarding_Personalization/ARPersonalizeViewController.m
  Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/Views/ARAcceptConditionsView.m
  CHANGELOG.yml
  src/lib/Scenes/About/About.tsx
  src/lib/Scenes/About/__tests__/About-tests.tsx
  src/lib/Scenes/Onboarding/OnboardingCreateAccount/OnboardingCreateAccount.tsx
Labels: Jira Synced, Squash On Green

#4949 fix: move artsy web view padding to correct place
  src/lib/Components/ArtsyReactWebView.tsx
Labels: Jira Synced

#4943 feat:order details sold by section
  CHANGELOG.yml
  src/__generated__/OrderDetailsQuery.graphql.ts
  src/__generated__/OrderDetailsTestsQuery.graphql.ts
  src/__generated__/OrderDetails_order.graphql.ts
  src/__generated__/SoldBySectionTestsQuery.graphql.ts
  src/__generated__/SoldBySection_soldBy.graphql.ts
  src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
  src/lib/Components/Artist/ArtistArtworks/__tests__/SavedSearchBanner-tests.tsx
  src/lib/Components/ArtworkFilter/__tests__/FilterArtworksHelpers-tests.tsx
  src/lib/Scenes/OrderHistory/OrderDetails/Components/OrderDetails.tsx
  src/lib/Scenes/OrderHistory/OrderDetails/Components/ShipsToSection.tsx
  src/lib/Scenes/OrderHistory/OrderDetails/Components/SoldBySection.tsx
  src/lib/Scenes/OrderHistory/OrderDetails/__tests__/ShipsToSection-tests.tsx
  src/lib/Scenes/OrderHistory/OrderDetails/__tests__/SoldBySection-tests.tsx
Labels: Jira Synced

#4948 feat: add feedback for sort and filter button
  CHANGELOG.yml
  src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
  src/lib/Scenes/Collection/Components/CollectionArtworksFilter.tsx
  src/palette/elements/Touchable/TouchableHighlightColor.tsx
  src/palette/elements/Touchable/index.tsx
Labels: Jira Synced

#4953 feat: don't show saved search for only sort filter
  CHANGELOG.yml
  src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
Labels: Jira Synced, Squash On Green

#4935 feat: articles screen
  CHANGELOG.yml
  android/app/src/main/AndroidManifest.xml
  package.json
  src/__generated__/ArticleCard_article.graphql.ts
  src/__generated__/ArticlesQuery.graphql.ts
  src/__generated__/Articles_articlesConnection.graphql.ts
  src/__generated__/ArtistAboutTestsQuery.graphql.ts
  src/__generated__/ArtistBelowTheFoldQuery.graphql.ts
  src/__generated__/HomeQuery.graphql.ts
  src/__generated__/HomeRefetchQuery.graphql.ts
  src/lib/AppRegistry.tsx
  src/lib/Components/ArticleCard.tsx
  src/lib/Scenes/Articles/Articles.tsx
  src/lib/Scenes/Articles/ArticlesList.tsx
  src/lib/Scenes/Articles/__tests__/Articles-tests.tsx
  src/lib/Scenes/Home/Components/ArticlesRail.tsx
  src/lib/Scenes/Home/homeAnalytics.ts
  src/lib/navigation/routes.tsx
  yarn.lock
Labels: Jira Synced, Squash On Green

#4955 chore: Preparing for development version 6.9.5
  CHANGELOG.yml
  app.json
Labels: Squash On Green

#4954 feat(fx-2968): saved search banner update on off automatically
  CHANGELOG.yml
  Podfile.lock
  src/__generated__/SavedSearchBannerRefetchQuery.graphql.ts
  src/lib/Components/Artist/ArtistArtworks/SavedSearchBanner.tsx
  src/lib/Components/Artist/ArtistArtworks/__tests__/SavedSearchBanner-tests.tsx
  src/lib/Components/ArtworkFilter/Filters/__tests__/helpers-tests.tsx
  src/lib/Components/ArtworkFilter/__tests__/FilterArtworksHelpers-tests.tsx
  src/lib/Scenes/Artist/Artist.tsx
Labels: Jira Synced

#4957 Enhancement(fx 2981)/saved search user is prompted to enable push notifications
  CHANGELOG.yml
  src/lib/Components/Artist/ArtistArtworks/SavedSearchBanner.tsx
Labels: Jira Synced, Squash On Green

#4899 Enhancement(cx 1462): android enable infinite scroll
  CHANGELOG.yml
  src/lib/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx
  src/lib/Components/ParentAwareScrollView.tsx
  src/lib/Components/__tests__/ParentAwareScrollView-tests.tsx
Labels: Jira Synced

#4961 remove horizontal scrolling indicator
  src/lib/Scenes/Home/Components/ArticlesRail.tsx
Labels: Jira Synced

#4963 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4965 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4966 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4958 feat: show toast for saved search
  CHANGELOG.yml
  src/lib/AppProviders.tsx
  src/lib/Components/Artist/ArtistArtworks/SavedSearchBanner.tsx
  src/lib/Components/PopoverMessage/PopoverMessage.tsx
  src/lib/Components/PopoverMessage/PopoverMessageProvider.tsx
  src/lib/Components/PopoverMessage/__tests__/PopoverMessage-tests.tsx
  src/lib/Components/PopoverMessage/popoverMessageHooks.tsx
  src/lib/Scenes/Artwork/Components/CommercialButtons/InquirySuccessNotification.tsx
  src/lib/tests/renderWithWrappers.tsx
Labels: Jira Synced

#4973 fix: User can see the way of delivery (PX-4211)
  CHANGELOG.yml
  src/__generated__/OrderDetailsHeaderTestsQuery.graphql.ts
  src/__generated__/OrderDetailsHeader_info.graphql.ts
  src/__generated__/OrderDetailsQuery.graphql.ts
  src/__generated__/OrderDetailsTestsQuery.graphql.ts
  src/__generated__/OrderDetails_order.graphql.ts
  src/lib/Scenes/OrderHistory/OrderDetails/Components/OrderDetailsHeader.tsx
  src/lib/Scenes/OrderHistory/OrderDetails/__tests__/OrderDetailsHeader-tests.tsx
Labels: Jira Synced

#4975 fix: align InfoCircleIcon inside InfoButton
  CHANGELOG.yml
  src/lib/Components/Buttons/InfoButton.tsx
Labels: Jira Synced

#4923 feat(CX-1552): Support Facebook login in react native onboarding
  Artsy.xcodeproj/project.pbxproj
  CHANGELOG.yml
  Podfile
  Podfile.lock
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/values/strings.xml
  package.json
  src/lib/store/AuthModel.ts
  src/lib/store/GlobalStoreModel.ts
  src/lib/store/__tests__/AuthModel-tests.ts
  src/setupJest.ts
  yarn.lock
Labels: Jira Synced, Squash On Green

#4968 fix: add roundedButtonStyle to floating button
  src/lib/Scenes/ViewingRoom/Components/ViewingRoomViewWorksButton.tsx
Labels: Jira Synced

#4970 enhancement(CX-1437): remove old spinner component
  CHANGELOG.yml
  emission/Pod/Classes/SpinnerComponent/ARSpinnerManager.h
  emission/Pod/Classes/SpinnerComponent/ARSpinnerManager.m
  src/lib/Components/Spinner.tsx
  src/lib/Scenes/Map/Components/CitySwitcherButton.tsx
  src/lib/utils/__tests__/renderWithLoadProgress-tests.tsx
  src/palette/elements/Spinner/Spinner.tsx
  src/setupJest.ts
Labels: Jira Synced

#4984 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4987 fix(CX-1536): align the button to center in the 'sell work' menu
  CHANGELOG.yml
  src/lib/Scenes/Consignments/Screens/Overview.tsx
Labels: Jira Synced

#4990 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4985 fix: Invalid user name + acronym for country name (PX-4241) and OrderSummary fixes (PX-4212)
  CHANGELOG.yml
  src/__generated__/OrderDetailsQuery.graphql.ts
  src/__generated__/OrderDetailsTestsQuery.graphql.ts
  src/__generated__/OrderDetails_order.graphql.ts
  src/lib/Scenes/OrderHistory/OrderDetails/Components/OrderDetails.tsx
  src/lib/Scenes/OrderHistory/OrderDetails/Components/ShipsToSection.tsx
  src/lib/Scenes/OrderHistory/OrderDetails/Components/SummarySection.tsx
  src/lib/Scenes/OrderHistory/OrderDetails/__tests__/OrderDetails-tests.tsx
  src/lib/Scenes/OrderHistory/OrderDetails/__tests__/ShipsToSection-tests.tsx
Labels: Jira Synced

#4991 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#4989 fix (CX-1549): hide spinner when there is no more data to load
  CHANGELOG.yml
  src/lib/Components/ArtworkGrids/GenericGrid.tsx
  src/lib/Components/ArtworkGrids/__tests__/GenericGrid-tests.tsx
Labels: Jira Synced

#4962 fix: Normalize market news rail spacing
  CHANGELOG.yml
  src/lib/Components/ArticleCard.tsx
  src/lib/Components/Artist/Articles/Articles.tsx
  src/lib/Scenes/Home/Components/ArticlesRail.tsx
Labels: Jira Synced, Squash On Green

#4996 Update metaphysics schema
  data/schema.graphql
  src/__generated__/SavedSearchBannerCreateSavedSearchMutation.graphql.ts
  src/__generated__/SavedSearchBannerQuery.graphql.ts
  src/__generated__/SavedSearchBannerRefetchQuery.graphql.ts
  src/__generated__/SavedSearchBannerTestsQuery.graphql.ts
Labels: Merge On Green

#4994 fix: Order History. Sold by: "Ships from" is displayed for "Pickup" fulfillment (PX-4257)
  CHANGELOG.yml
  src/__generated__/OrderDetailsQuery.graphql.ts
  src/__generated__/OrderDetailsTestsQuery.graphql.ts
  src/__generated__/SoldBySectionTestsQuery.graphql.ts
  src/__generated__/SoldBySection_soldBy.graphql.ts
  src/lib/Scenes/OrderHistory/OrderDetails/Components/SoldBySection.tsx
  src/lib/Scenes/OrderHistory/OrderDetails/__tests__/SoldBySection-tests.tsx
Labels: Jira Synced

#5001 enhancement(dev tools): show redux in flipper
  Podfile.lock
  package.json
  src/lib/store/GlobalStore.tsx
  yarn.lock
Labels: Squash On Green

#5002 Update metaphysics schema
  data/schema.graphql
  src/__generated__/SavedSearchBannerCreateSavedSearchMutation.graphql.ts
  src/__generated__/SavedSearchBannerQuery.graphql.ts
  src/__generated__/SavedSearchBannerRefetchQuery.graphql.ts
  src/__generated__/SavedSearchBannerTestsQuery.graphql.ts
Labels: Merge On Green

#4997 feat: sync search attributes
  CHANGELOG.yml
  src/lib/Components/ArtworkFilter/ArtworkFilterHelpers.ts
  src/lib/Components/ArtworkFilter/Filters/__tests__/helpers-tests.tsx
  src/lib/Components/ArtworkFilter/Filters/helpers.ts
  src/lib/Components/ArtworkFilter/__tests__/FilterArtworksHelpers-tests.tsx
Labels: Jira Synced

#5007 Update metaphysics schema
  data/schema.graphql
  src/__generated__/createConsignmentSubmissionMutation.graphql.ts
  src/__generated__/updateConsignmentSubmissionMutation.graphql.ts
Labels: Merge On Green

#5005 fix: Order History: "Unable to load" page is opened (exception occurs) when artwork is deleted/unpublished from order (PX-4253)
  CHANGELOG.yml
  src/__generated__/OrderHistoryQuery.graphql.ts
  src/lib/Scenes/OrderHistory/OrderHistory.tsx
  src/lib/Scenes/OrderHistory/OrderHistoryRow.tsx
Labels: Jira Synced

#5006 feat: Adds flag for order history feature
  CHANGELOG.yml
  src/lib/store/config/features.ts
Labels: Squash On Green

#5008 fix: adjust market news rail spacing
  src/lib/Scenes/Home/Components/ArticlesRail.tsx
Labels: Jira Synced, Squash On Green

#4988 feat: convert saved search criteria to filter params
  CHANGELOG.yml
  src/lib/Components/ArtworkFilter/Filters/ColorsOptions.tsx
  src/lib/Components/ArtworkFilter/Filters/PriceRangeOptions.tsx
  src/lib/Components/ArtworkFilter/Filters/SizeOptions.tsx
  src/lib/Components/ArtworkFilter/Filters/WaysToBuyOptions.tsx
  src/lib/Components/ArtworkFilter/Filters/helpers.ts
  src/lib/Components/ArtworkFilter/SavedSearch/__tests__/convertersToFilterParams-tests.ts
  src/lib/Components/ArtworkFilter/SavedSearch/convertersToFilterParams.ts
Labels: Jira Synced

#5010 fix: Unrelease order history feature for now
  src/lib/store/config/features.ts
Labels: Squash On Green

#4869 feat: show currency for realized price in auction result list item
  CHANGELOG.yml
  src/lib/Components/Lists/AuctionResultListItem.tsx
Labels: Jira Synced, Squash On Green

#4980 feat: set web view deceleration rate to normal
  CHANGELOG.yml
  src/lib/Components/ArtsyReactWebView.tsx
  src/lib/Components/StyledWebView.tsx
Labels: Jira Synced, Squash On Green

#4998 feat: User on app can filter auction results by auction house
  CHANGELOG.yml
  src/__generated__/ArtistBelowTheFoldQuery.graphql.ts
  src/__generated__/ArtistInsightsAuctionResultsQuery.graphql.ts
  src/__generated__/ArtistInsightsAuctionResultsTestsQuery.graphql.ts
  src/__generated__/ArtistInsightsAuctionResults_artist.graphql.ts
  src/__generated__/ArtistInsightsTestsQuery.graphql.ts
  src/lib/Components/Artist/ArtistInsights/ArtistInsightsAuctionResults.tsx
  src/lib/Components/ArtworkFilter/ArtworkFilter.tsx
  src/lib/Components/ArtworkFilter/ArtworkFilterHelpers.ts
  src/lib/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx
  src/lib/Components/ArtworkFilter/ArtworkFilterStore.tsx
  src/lib/Components/ArtworkFilter/Filters/AuctionHouseOptions.tsx
  src/lib/Components/ArtworkFilter/Filters/__tests__/AuctionHouseOptions-tests.tsx
  src/lib/Components/ArtworkFilter/__tests__/ArtworkFiltersStore-tests.tsx
Labels: Jira Synced, Squash On Green

#5014 Update metaphysics schema
  data/schema.graphql
  src/__generated__/createConsignmentSubmissionMutation.graphql.ts
Labels: Merge On Green

#5016 docs: update release notes
  app.json
  docs/deploy_to_play_store.md
  fastlane/metadata/android/en-US/changelogs/default.txt
  fastlane/metadata/en-US/release_notes.txt
Labels: Squash On Green

#5004 chore: add specs for deleteSavedSearch and createSavedSearch mutations
  CHANGELOG.yml
  src/lib/Components/Artist/ArtistArtworks/__tests__/SavedSearchBanner-tests.tsx
Labels: Jira Synced

#5017 feat: Message on mutation fail
  src/lib/Components/Artist/ArtistArtworks/SavedSearchBanner.tsx
  src/lib/Components/PopoverMessage/PopoverMessage.tsx
  src/lib/Components/PopoverMessage/__tests__/PopoverMessage-tests.tsx
Labels: Jira Synced

#4995 feat: Sticky header on show screen
  Podfile.lock
  src/lib/Components/HeaderArtworksFilter.tsx
  src/lib/Components/__tests__/HeaderArtworksFilter-tests.tsx
  src/lib/Scenes/Collection/Components/CollectionArtworksFilter.tsx
  src/lib/Scenes/Collection/Screens/CollectionArtworks.tsx
  src/lib/Scenes/Show/Components/ShowArtworks.tsx
  src/lib/Scenes/Show/Components/ShowArtworksFilter.tsx
  src/lib/Scenes/Show/Show.tsx
  src/lib/Scenes/Show/__tests__/Show-tests.tsx
  src/lib/Scenes/Show/__tests__/ShowArtworksFilter-tests.tsx
Labels: Jira Synced

#5020 fix (CX-1532): user can't unfollow category
  CHANGELOG.yml
  src/lib/Components/Gene/Header.tsx
Labels: Jira Synced

#4924 feat: parse prs
  CHANGELOG/android-changelog.md
  CHANGELOG/ios-changelog.md
  docs/pull_request_template.md
  fastlane/Fastfile
  package.json
  scripts/changelog/changelog-types.d.ts
  scripts/changelog/generatePlatformChangelog-tests.ts
  scripts/changelog/generatePlatformChangelog.js
  scripts/changelog/parsePRDescription-tests.ts
  scripts/changelog/parsePRDescription.js
  yarn.lock
Labels: Jira Synced

#4999 fix: iOS artwork preview misalignment
  src/lib/Scenes/Inbox/Components/Conversations/Preview/ArtworkPreview.tsx
Labels: Jira Synced

#5028 fix: ask notification permissions only for create saved search
  CHANGELOG.yml
  src/lib/Components/Artist/ArtistArtworks/SavedSearchBanner.tsx
Labels: Jira Synced

#5030 fix: toggle saved search banner label by enable/disable state
  src/lib/Components/Artist/ArtistArtworks/SavedSearchBanner.tsx
Labels: Jira Synced

#5029 fix: update popover message markup
  src/lib/Components/PopoverMessage/PopoverMessage.tsx
Labels: Jira Synced

#5037 chore: update Podfile.lock #trivial
  Podfile.lock
Labels: Squash On Green

#5032 feat: allow component props to be passed from push notification payload
  Artsy/App/ARAppNotificationsDelegate.m
  Artsy_Tests/App_Tests/ARAppNotificationsDelegateTests.m
  CHANGELOG.yml
  emission/Pod/Classes/Core/AREmission.h
  emission/Pod/Classes/Core/AREmission.m
  emission/Pod/Classes/EigenCommunications/ARNotificationsManager.h
  emission/Pod/Classes/EigenCommunications/ARNotificationsManager.m
  src/lib/Scenes/Artist/Artist.tsx
  src/lib/store/NativeModel.ts
Labels: Jira Synced

#5043 chore: Prepare for development, 6.10.0 #trivial
  CHANGELOG.yml
  app.json
Labels: Squash On Green

#4971 feat (CX-1590): implement share button for articles
  CHANGELOG.yml
  src/lib/Components/ArtsyReactWebView.tsx
  src/lib/Components/FancyModal/FancyModalHeader.tsx
  src/lib/Components/__tests__/ArtsyReactWebView-tests.tsx
  src/lib/navigation/__tests__/routes-tests.tsx
  src/lib/navigation/routes.tsx
Labels: Jira Synced, Squash On Green

#5036 feat: Add sticky header on fair screen
  src/lib/Components/HeaderArtworksFilter/HeaderArtworksFilter.tsx
  src/lib/Components/HeaderArtworksFilter/HeaderArtworksFilterWithTotalArtworks.tsx
  src/lib/Components/HeaderArtworksFilter/__tests__/HeaderArtworksFilter-tests.tsx
  src/lib/Components/HeaderArtworksFilter/__tests__/HeaderArtworksFilterWithTotalArtworks-tests.tsx
  src/lib/Scenes/Collection/Components/CollectionArtworksFilter.tsx
  src/lib/Scenes/Fair/Components/FairArtworks.tsx
  src/lib/Scenes/Fair/Fair.tsx
  src/lib/Scenes/Show/Show.tsx
  src/lib/Scenes/Show/__tests__/Show-tests.tsx
Labels: Jira Synced

#5047 chore: update saved search tests
  src/lib/Components/Artist/ArtistArtworks/__tests__/SavedSearchBanner-tests.tsx
Labels: Squash On Green

#5048 chore: update convert to filter params tests
  src/lib/Components/ArtworkFilter/SavedSearch/__tests__/convertersToFilterParams-tests.ts
Labels: Squash On Green

#5046 Update metaphysics schema
  data/schema.graphql
  src/__generated__/SavedSearchBannerCreateSavedSearchMutation.graphql.ts
  src/__generated__/SavedSearchBannerQuery.graphql.ts
  src/__generated__/SavedSearchBannerRefetchQuery.graphql.ts
  src/__generated__/SavedSearchBannerTestsQuery.graphql.ts
Labels: Merge On Green

#5050 fix (CX-1621): locations menu does not redirect correctly
  CHANGELOG.yml
  src/lib/Components/LocationMap/index.tsx
Labels: Jira Synced

#5045 feat: add diagnose script
  .gitignore
  CHANGELOG.yml
  package.json
  scripts/diagnose.js
  yarn.lock
Labels: Squash On Green

#5044 fix(CX-1650): tapping artist opens its page after passing new onboarding on ios
  CHANGELOG.yml
  src/lib/Components/ArtistListItem.tsx
  src/lib/Scenes/Onboarding/OnboardingPersonalization/OnboardingPersonalization.tsx
  src/lib/Scenes/Onboarding/OnboardingPersonalization/OnboardingPersonalizationArtistListItem.tsx
  src/lib/Scenes/Onboarding/OnboardingPersonalization/OnboardingPersonalizationModal.tsx
Labels: Jira Synced, Squash On Green

#5038 feat: show refine button only for iOS
  src/lib/Containers/Gene.tsx
Labels: Jira Synced

#5055 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#5056 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#5051 fix(CX-1656): Prevent facebook auth for users without email
  CHANGELOG.yml
  src/lib/store/AuthModel.ts
  src/lib/store/__tests__/AuthModel-tests.ts
Labels: Jira Synced, Squash On Green

#5033 fix(CX-1626, CX-1630): unable to press 'following' button
  CHANGELOG.yml
  src/lib/Components/ArtistListItem.tsx
  src/lib/Scenes/Onboarding/OnboardingPersonalization/OnboardingPersonalizationArtistListItem.tsx
  src/palette/elements/Touchable/Touchable.tsx
Labels: Jira Synced, Squash On Green

#4992 feat(CX-1554): Add apple auth (review google auth first)
  .gitignore
  CHANGELOG.yml
  GoogleService-Info.plist
  Podfile.lock
  package.json
  scripts/setup-distribute-linux
  src/lib/store/AuthModel.ts
  src/lib/store/__tests__/AuthModel-tests.ts
  src/setupJest.ts
  yarn.lock
Labels: Jira Synced

#5034 feat: saved search notification
  src/__generated__/ArtistAboveTheFoldQuery.graphql.ts
  src/__generated__/SearchCriteriaQuery.graphql.ts
  src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
  src/lib/Components/Artist/ArtistArtworks/SavedSearchBanner.tsx
  src/lib/Components/ArtworkFilter/ArtworkFilterHelpers.ts
  src/lib/Components/ArtworkFilter/SavedSearch/__tests__/convertersToFilterParams-tests.ts
  src/lib/Components/ArtworkFilter/SavedSearch/__tests__/searchCriteriaHelpers-tests.ts
  src/lib/Components/ArtworkFilter/SavedSearch/convertersToFilterParams.ts
  src/lib/Components/ArtworkFilter/SavedSearch/searchCriteriaHelpers.ts
  src/lib/Components/ArtworkFilter/SavedSearch/types.ts
  src/lib/Scenes/Artist/Artist.tsx
  src/lib/Scenes/Artist/SearchCriteria.tsx
  src/lib/Scenes/Artist/__tests__/Artist-tests.tsx
  src/lib/Scenes/Artist/__tests__/ArtistSavedSearch-tests.tsx
  src/lib/Scenes/Artist/__tests__/SearchCriteria-tests.tsx
  src/lib/navigation/__tests__/navigate-tests.tsx
  src/lib/store/__tests__/NativeModel-tests.ts
Labels: Jira Synced

#5023 feat: Add optionalField directive
  CHANGELOG.yml
  src/__generated__/HomeQuery.graphql.ts
  src/__generated__/HomeRefetchQuery.graphql.ts
  src/lib/Scenes/Home/Home.tsx
  src/lib/relay/createEnvironment.ts
  src/lib/relay/middlewares/__tests__/errorMiddleware-tests.ts
  src/lib/relay/middlewares/errorMiddleware.ts
  src/lib/relay/middlewares/metaphysicsMiddleware.ts
Labels: Jira Synced

#5057 fix: use palette touchable /w underlayColor & consistency style changes in ArtistSeriesListItem
  src/lib/Scenes/ArtistSeries/ArtistSeriesListItem.tsx
  src/lib/Scenes/ArtistSeries/__tests__/ArtistSeries-tests.tsx
  src/lib/Scenes/ArtistSeries/__tests__/ArtistSeriesFullArtistSeriesList-tests.tsx
  src/lib/Scenes/ArtistSeries/__tests__/ArtistSeriesListItem-tests.tsx
  src/lib/Scenes/ArtistSeries/__tests__/ArtistSeriesMoreSeries-tests.tsx
  src/lib/Scenes/Artwork/__tests__/Artwork-tests.tsx
Labels: Jira Synced, Squash On Green

#5062 fix: android rn screen crash
  CHANGELOG.yml
  HACKS.md
  android/app/src/main/java/net/artsy/app/MainActivity.java
Labels: Jira Synced

#5027 fix (CX-1572): social icons overlap
  Artsy/View_Controllers/Login_and_Onboarding/Onboarding_stages/5-_Onboarding_Personalization/ARPersonalizeViewController.m
  CHANGELOG.yml
Labels: Jira Synced, Squash On Green
