Repository artsy/eigen, pull requests merged in 2022-05, with the labels that each got.

#6693 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6694 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6696 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6676 fix(CX-2543): Fix performance with my collection search
  HACKS.md
  src/app/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tests.tsx
  src/app/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx
  src/app/Components/StickyTabPage/StickyTabPage.tsx
  src/app/Components/StickyTabPage/StickyTabPageContext.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionArtworkList.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionSearchBar.tests.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionSearchBar.tsx
  src/app/Scenes/MyCollection/MyCollection.tests.tsx
  src/app/Scenes/MyCollection/MyCollection.tsx
  src/app/Scenes/MyCollection/MyCollectionArtworks.tsx
Labels: Jira Synced

#6697 fix: add back manual token registration and new keys #trivial
  android/app/src/main/java/net/artsy/app/MainApplication.java
  android/app/src/main/res/values/braze.xml
Labels: Squash On Green

#6699 fix: collector profile message typo
  src/app/Scenes/MyProfile/MyProfileHeader.tsx
  src/app/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tests.tsx
Labels: Squash On Green

#6702 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6703 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6559 feat(CX-2528): My Collection artwork upload with custom artist
  .secrets.baseline
  src/app/Components/FancyModal/FancyModalHeader.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtistAutosuggest.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Form/artworkSchema.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tests.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormArtist.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormArtwork.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormMain.tsx
  src/app/Scenes/MyCollection/State/MyCollectionArtworkModel.tsx
  src/app/Scenes/Search/AutosuggestResults.tsx
  src/app/store/config/features.ts
Labels: Jira Synced

#6704 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6708 fix(CX-2554): Fix alignment of the "View all" link of the <SectionTitle/> component
  src/app/Components/SectionTitle.tsx
Labels: Jira Synced, Squash On Green

#6714 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6717 fix: artworkrail truncated price
  src/app/Components/ArtworkRail/ArtworkRailCard.tsx
Labels: Jira Synced

#6713 feat(CX-2511): add last 3 recent auction results based on artists you collect
  src/app/Scenes/MyCollection/Screens/Insights/AuctionResultsBasedOnArtistsYouCollect.tsx
  src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsights.tests.tsx
  src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsights.tsx
  src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsightsOverview.tsx
  src/app/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx
Labels: Jira Synced

#6716 Enhancement(CX-2556): Standardize Toast Duration and Make RequestPriceEstimate Toast duration long
  src/app/Components/Toast/Toast.tests.tsx
  src/app/Components/Toast/ToastComponent.tsx
  src/app/Components/Toast/types.ts
  src/app/Scenes/Inbox/Components/Conversations/Messages.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/RequestForPriceEstimate/RequestForPriceEstimateScreen.tsx
Labels: Jira Synced

#6700 feat: Introduce NotFoundFailureView
  src/app/Components/NotFoundFailureView.tsx
  src/app/Components/RetryErrorBoundary.tests.tsx
  src/app/Components/RetryErrorBoundary.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tsx
  src/app/relay/middlewares/errorMiddleware.tests.ts
  src/app/store/config/features.ts
Labels: Jira Synced

#6690 feat(FX-3928): upload file using GraphQL query/mutation
  HACKS.md
  package.json
  patches/@types+extract-files+8.1.1.patch
  patches/react-relay-network-modern+6.2.1.patch
  src/app/Scenes/Fair/Fair.tsx
  src/app/relay/createEnvironment.ts
  yarn.lock
Labels: Jira Synced

#6722 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6723 fix: (SWA-357): Display multiple photos when uploaded in Submission flow
  src/app/Scenes/SellWithArtsy/SubmitArtwork/UploadPhotos/UploadPhotosForm.tsx
Labels: Jira Synced

#6542 chore(GRO-764): Match saved search updates with new user email preferences
  src/app/Scenes/SavedSearchAlert/CreateSavedSearchAlert.tests.tsx
  src/app/Scenes/SavedSearchAlert/SavedSearchAlertForm.tests.tsx
  src/app/Scenes/SavedSearchAlert/SavedSearchAlertForm.tsx
  src/app/Scenes/SavedSearchAlert/containers/CreateSavedSearchContentContainer.tsx
  src/app/Scenes/SavedSearchAlert/mutations/updateEmailFrequency.ts
  src/app/Scenes/SavedSearchAlert/mutations/updateNotificationPreferences.ts
Labels: Jira Synced

#6726 refactor: small refactor on artwork scene
  src/app/Scenes/Artwork/Artwork.tsx
  src/app/Scenes/Artwork/Components/AboveTheFoldArtworkPlaceholder.tsx
  src/app/Scenes/Artwork/Components/BelowTheFoldPlaceholder.tsx
  src/app/Scenes/Artwork/helpers.ts
Labels: Jira Synced

#6719 fix: Show Not Found screen for missing artworks
  src/app/Components/NotFoundFailureView.tsx
  src/app/Components/RetryErrorBoundary.tsx
  src/app/utils/renderWithPlaceholder.tsx
Labels: Jira Synced

#6731 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6733 prep for next release
  app.json
  fastlane/metadata/android/en-US/changelogs/default.txt
  fastlane/metadata/en-US/release_notes.txt
Labels: Squash On Green

#6729 feat(FX-3928): upload middleware for Relay
  package.json
  patches/react-relay-network-modern+6.2.1.patch
  src/app/relay/createEnvironment.ts
  src/app/relay/middlewares/uploadMiddleware.tests.ts
  src/app/relay/middlewares/uploadMiddleware.ts
  yarn.lock
Labels: Jira Synced

#6738 feat(MOPLAT-261): Sentence case on placeholder
  src/app/Components/ArtistAutosuggest/ArtistAutosuggest.tsx
  src/app/Components/LocationAutocomplete/LocationAutocomplete.tests.tsx
  src/app/Components/LocationAutocomplete/LocationAutocomplete.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/RequestForPriceEstimate/RequestForPriceEstimateForm.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtistAutosuggest.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tests.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormMain.tsx
  src/app/Scenes/MyProfile/MyProfileEditForm.tsx
  src/app/Scenes/MyProfile/MyProfilePaymentNewCreditCard.tsx
  src/app/Scenes/Onboarding/OnboardingCreateAccount/OnboardingCreateAccount.tests.tsx
  src/app/Scenes/Onboarding/OnboardingCreateAccount/OnboardingCreateAccountName.tsx
  src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkDetails/ArtworkDetailsForm.tsx
  src/app/Scenes/SellWithArtsy/SubmitArtwork/ContactInformation/ContactInformation.tests.tsx
  src/app/Scenes/SellWithArtsy/SubmitArtwork/ContactInformation/ContactInformation.tsx
Labels: Jira Synced

#6740 feat: resize image for TinEye search
  src/app/Scenes/Fair/Fair.tsx
Labels: Squash On Green

#6742 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6744 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6745 fix(CX-2558): Change subtitle copy
  src/app/Scenes/MyCollection/Screens/Insights/AuctionResultsForArtistsYouCollectRail.tsx
Labels: Jira Synced

#6748 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6747 fix: Align My Collection failure view
  src/app/Components/LoadFailureView.tsx
  src/app/Scenes/MyCollection/MyCollection.tsx
Labels: Jira Synced

#6752 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6741 feat(FX-3953): Create alert on an artwork page
  src/app/Scenes/Artwork/Artwork.tsx
  src/app/Scenes/Artwork/Components/ArtworkExtraLinks/FaqAndSpecialistSection.tsx
  src/app/Scenes/Artwork/Components/ArtworkExtraLinks/index.tests.tsx
  src/app/Scenes/Artwork/Components/ArtworkExtraLinks/index.tsx
  src/app/Scenes/Artwork/Components/CommercialInformation.tests.tsx
  src/app/Scenes/Artwork/Components/CommercialPartnerInformation.tsx
  src/app/Scenes/Artwork/Components/CreateArtworkAlertSection.tsx
  src/app/store/config/features.ts
  src/app/utils/track/schema.ts
Labels: Jira Synced

#6753 fix(CX-2562): fix share icon positioning
  src/app/Scenes/Sale/Components/SaleHeader.tsx
Labels: Jira Synced

#6735 refactor: prepare SavedSearchStore for FX-3954
  src/app/Components/Artist/ArtistArtworks/CreateSavedSearchModal.tests.tsx
  src/app/Components/Artist/ArtistArtworks/CreateSavedSearchModal.tsx
  src/app/Components/ArtworkFilter/ArtworkFilterNavigator.tsx
  src/app/Components/ArtworkFilter/SavedSearch/searchCriteriaHelpers.tests.ts
  src/app/Components/ArtworkFilter/SavedSearch/searchCriteriaHelpers.ts
  src/app/Components/ArtworkFilter/SavedSearch/types.ts
  src/app/Scenes/SavedSearchAlert/CreateSavedSearchAlert.tests.tsx
  src/app/Scenes/SavedSearchAlert/EditSavedSearchAlert.tests.tsx
  src/app/Scenes/SavedSearchAlert/EditSavedSearchAlert.tsx
  src/app/Scenes/SavedSearchAlert/SavedSearchAlertForm.tests.tsx
  src/app/Scenes/SavedSearchAlert/SavedSearchAlertForm.tsx
  src/app/Scenes/SavedSearchAlert/SavedSearchAlertModel.ts
  src/app/Scenes/SavedSearchAlert/SavedSearchStore.tsx
  src/app/Scenes/SavedSearchAlert/pillExtractors.tests.ts
  src/app/Scenes/SavedSearchAlert/pillExtractors.ts
  src/app/Scenes/SavedSearchAlert/screens/CreateSavedSearchAlertScreen.tsx
  src/app/Scenes/SavedSearchAlert/useSavedSearchPills.ts
Labels: Jira Synced

#6755 refactor: prepare SavedSearchStore for FX-3954 (second stage)
  src/app/Components/Artist/ArtistArtworks/CreateSavedSearchModal.tests.tsx
  src/app/Components/Artist/ArtistArtworks/CreateSavedSearchModal.tsx
  src/app/Components/ArtworkFilter/ArtworkFilterNavigator.tsx
  src/app/Components/ArtworkFilter/SavedSearch/searchCriteriaHelpers.tests.ts
  src/app/Components/ArtworkFilter/SavedSearch/types.ts
  src/app/Scenes/SavedSearchAlert/Components/EditSavedSearchAlertPlaceholder.tsx
  src/app/Scenes/SavedSearchAlert/Components/Form.tsx
  src/app/Scenes/SavedSearchAlert/CreateSavedSearchAlert.tests.tsx
  src/app/Scenes/SavedSearchAlert/EditSavedSearchAlert.tests.tsx
  src/app/Scenes/SavedSearchAlert/EditSavedSearchAlert.tsx
  src/app/Scenes/SavedSearchAlert/SavedSearchAlertForm.tests.tsx
  src/app/Scenes/SavedSearchAlert/SavedSearchAlertForm.tsx
  src/app/Scenes/SavedSearchAlert/SavedSearchAlertModel.ts
  src/app/Scenes/SavedSearchAlert/SavedSearchStore.tsx
  src/app/Scenes/SavedSearchAlert/containers/CreateSavedSearchContentContainer.tsx
  src/app/Scenes/SavedSearchAlert/helpers.tests.ts
  src/app/Scenes/SavedSearchAlert/helpers.ts
  src/app/Scenes/SavedSearchAlert/pillExtractors.tests.ts
Labels: Squash On Green

#6756 feat(BID-368): Auctions Countdown Progress Bar
  src/app/Components/Bidding/Components/ArtworkAuctionProgressBar.tests.tsx
  src/app/Components/Bidding/Components/ArtworkAuctionProgressBar.tsx
  src/app/Components/Bidding/Components/Timer.tsx
  src/app/Scenes/Artwork/Components/CommercialInformation.tsx
  src/palette/elements/PhotoRow/PhotoRow.tsx
  src/palette/elements/ProgressBar/ProgressBar.stories.tsx
  src/palette/elements/ProgressBar/ProgressBar.tests.tsx
  src/palette/elements/ProgressBar/ProgressBar.tsx
Labels: Jira Synced

#6764 feat(CX-2572): add market signal info modal
  src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsights.tsx
Labels: Jira Synced

#6760 Feat(BID-369): Prefix Extended to Bid label when popcorn has been activated
  src/app/Components/ArtworkGrids/LotCloseInfo.tsx
  src/app/Components/Bidding/Components/Timer.tsx
  src/app/Components/Countdown/Ticker.tests.tsx
  src/app/Components/Countdown/Ticker.tsx
  src/app/utils/saleTime.ts
Labels: Jira Synced

#6765 feat(FX-3978): Separate Faq Section from Auction Faq and add it to artwork screen
  src/app/Scenes/Artwork/Artwork.tsx
  src/app/Scenes/Artwork/Components/ArtworkExtraLinks/AuctionFaqSection.tsx
  src/app/Scenes/Artwork/Components/ArtworkExtraLinks/FaqAndSpecialistSection.tsx
  src/app/Scenes/Artwork/Components/ArtworkExtraLinks/index.tests.tsx
  src/app/Scenes/Artwork/Components/ArtworkExtraLinks/index.tsx
Labels: Jira Synced

#6757 feat(FX-3954): Create Alert button opens up modal pre-filled with relevant filters on artwork screen
  src/app/Components/Artist/ArtistArtworks/CreateSavedSearchModal.tests.tsx
  src/app/Components/Artist/ArtistArtworks/CreateSavedSearchModal.tsx
  src/app/Components/ArtworkFilter/ArtworkFilterNavigator.tsx
  src/app/Scenes/Artwork/Artwork.tsx
  src/app/Scenes/Artwork/Components/CreateArtworkAlertSection.tests.tsx
  src/app/Scenes/Artwork/Components/CreateArtworkAlertSection.tsx
Labels: Jira Synced, Squash On Green

#6771 feat(CX-2589): add the third tab to the MyC placeholder
  src/app/Scenes/MyCollection/MyCollection.tsx
Labels: Jira Synced

#6773 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#6777 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#6770 feat(CX-2575): add open more market insights banner
  images/MCInsights_banner_backgound_image.webp
  images/MCInsights_banner_backgound_image@2x.webp
  images/MCInsights_banner_backgound_image@3x.webp
  src/app/Scenes/MyCollection/Screens/Insights/ActivateMoreMarketInsightsBanner.tests.tsx
  src/app/Scenes/MyCollection/Screens/Insights/ActivateMoreMarketInsightsBanner.tsx
  src/app/Scenes/MyCollection/Screens/Insights/AuctionResultsForArtistsYouCollectRail.tsx
  src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsights.tsx
Labels: Jira Synced

#6775 feat(BID-379): Enhance Cascading banner to feature popcorn message
  src/app/Scenes/Artwork/Components/ArtworkTombstone.tests.tsx
  src/app/Scenes/Artwork/Components/ArtworkTombstone.tsx
  src/app/Scenes/Artwork/Components/CascadingEndTimesBanner.tsx
  src/app/Scenes/Sale/Components/SaleHeader.tsx
  src/app/Scenes/Sale/Sale.tsx
Labels: Jira Synced

#6774 feat(BID-213): Sale Listings on Eigen show correct subtitle
  src/app/Scenes/Home/Components/SalesRail.tests.tsx
  src/app/Scenes/Home/Components/SalesRail.tsx
  src/app/Scenes/Sales/Components/SaleListItem.tests.tsx
  src/app/Scenes/Sales/Components/SaleListItem.tsx
  src/app/store/config/features.ts
Labels: Jira Synced

#6768 feat(CX-2565): add my collection insights empty state
  Artsy.xcodeproj/project.pbxproj
  Podfile.lock
  images/my-collection-empty-state.webp
  images/my-collection-empty-state@2x.webp
  images/my-collection-empty-state@3x.webp
  src/app/Components/StickyTabPage/testHelpers.tsx
  src/app/Scenes/MyCollection/Screens/Insights/AuctionResultsForArtistsYouCollectRail.tsx
  src/app/Scenes/MyCollection/Screens/Insights/MarketSignalsSectionHeader.tsx
  src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsights.tests.tsx
  src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsights.tsx
  src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsightsEmptyState.tests.tsx
  src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsightsEmptyState.tsx
  src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsightsOverview.tsx
  src/app/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx
Labels: Jira Synced

#6780 fix(SWA-358): Bug fixes for SWA flow
  src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkDetails/ArtworkDetails.tests.tsx
  src/palette/elements/Collapse/Collapse.tsx
Labels: Jira Synced

#6785 fix(CX-2565): my collection insights empty state - ui fix
  src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsightsEmptyState.tsx
Labels: Jira Synced

#6778 feat(CX-2594): add my collection insights phases steps
  src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsights.tests.tsx
  src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsights.tsx
  src/app/store/config/features.ts
Labels: Jira Synced

#6791 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#6796 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#6792 fix(Bid Timers): Fix Timer sync issues
  src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
  src/app/Components/ArtworkGrids/LotCloseInfo.tests.tsx
  src/app/Components/ArtworkGrids/LotCloseInfo.tsx
  src/app/Components/Bidding/Components/Timer.tsx
  src/app/Components/Bidding/Screens/BidResult.tsx
  src/app/Components/Bidding/Screens/ConfirmBid/index.tsx
  src/app/Components/Countdown/CountdownTimer.tsx
  src/app/Components/Countdown/DurationProvider.tsx
  src/app/Components/Countdown/StateManager.tsx
  src/app/Components/Countdown/Ticker.tsx
  src/app/Scenes/Artwork/Components/CommercialInformation.tsx
  src/app/Scenes/Artwork/Components/CreateArtworkAlertButtonsSection.tsx
  src/app/Scenes/ViewingRoom/Components/ViewingRoomHeader.tsx
Labels: Jira Synced

#6799 chore: update Algolia index key for collection pill
  src/app/Scenes/Search/Search.tests.tsx
  src/app/Scenes/Search/types.ts
Labels: Squash On Green

#6790 feat(FX-3926): display Sort & filter bar when artist has no artworks
  src/app/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
  src/app/Scenes/Artist/Artist.tests.tsx
  src/app/Scenes/Artist/Artist.tsx
  src/app/Scenes/Artist/ArtistSavedSearch.tests.tsx
  src/setupJest.ts
Labels: Jira Synced

#6794 feat(Bid-371): Add Progress bar on Sale Grid Item
  src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
  src/app/Components/ArtworkGrids/LotCloseInfo.tests.tsx
  src/app/Components/ArtworkGrids/LotProgressBar.tests.tsx
  src/app/Components/ArtworkGrids/LotProgressBar.tsx
Labels: Jira Synced

#6727 feat: My Collection Search Bar Rework 2
  HACKS.md
  src/app/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tests.tsx
  src/app/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionArtworkList.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionSearchBar.tests.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionSearchBar.tsx
  src/app/Scenes/MyCollection/MyCollectionArtworks.tsx
Labels: Jira Synced

#6787 feat(CX2587): add no insights message (artwork added from my collection tab)
  .secrets.baseline
  Artsy.xcodeproj/project.pbxproj
  Podfile.lock
  src/app/Scenes/MyCollection/MyCollection.tests.tsx
  src/app/Scenes/MyCollection/MyCollection.tsx
  src/app/Scenes/MyCollection/MyCollectionArtworks.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tests.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx
  src/app/Scenes/MyCollection/Screens/Insights/ActivateMoreMarketInsightsBanner.tests.tsx
  src/app/Scenes/MyCollection/Screens/Insights/ActivateMoreMarketInsightsBanner.tsx
  src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsightsEmptyState.tests.tsx
  src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsightsEmptyState.tsx
  src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsightsMessages.tsx
  src/app/store/config/visualClues.ts
Labels: Jira Synced, Squash On Green

#6805 feat: Add RefreshControl to MyCollection Insights
  src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsights.tsx
Labels: Jira Synced

#6813 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#6772 feat [CX-2566]: Add new Generating Market Data loader for My Collection Insights
  .secrets.baseline
  images/InsightsLoadingImage.webp
  images/InsightsLoadingImage@2x.webp
  images/InsightsLoadingImage@3x.webp
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/SavingArtworkModal.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tests.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx
  src/palette/elements/Spinner/CircularSpinner.tsx
  src/palette/elements/Spinner/index.tsx
Labels: Jira Synced

#6816 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#6815 fix(FX-3988): partners section for auctions should not be pressable
  src/app/Scenes/Artwork/Artwork.tests.tsx
  src/app/Scenes/Artwork/Artwork.tsx
Labels: Jira Synced, Squash On Green

#6820 feat: add nav visualizer, make visualizer shared util
  src/app/navigation/navigate.ts
  src/app/store/config/features.ts
  src/app/utils/track/SegmentTrackingProvider.ts
  src/app/utils/visualizer.ts
Labels: Squash On Green

#6823 fix: hide "Contact Gallery" button when auction is in closed state
  src/app/Scenes/Artwork/Components/CreateArtworkAlertButtonsSection.tsx
Labels: Squash On Green

#6818 chore(FX-3989): copy update
  src/app/Scenes/Artwork/Components/CreateArtworkAlertButtonsSection.tsx
  src/app/Scenes/Artwork/Components/CreateArtworkAlertSection.tsx
Labels: Jira Synced

#6826 chore(FX-3985): mark AREnableCreateArtworkAlert as ready for release
  src/app/store/config/features.ts
Labels: Jira Synced, Squash On Green

#6828 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#6822 refactor(PLATFORM-4107): notify user to verify email after update
  src/app/Scenes/MyAccount/MyAccountEditEmail.tsx
Labels: Jira Synced

#6843 chore(FX-3993): decrease debounce value to 200ms
  src/app/Components/ArtworkFilter/Filters/PriceRangeOptions.tsx
Labels: Jira Synced, Squash On Green

#6845 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green
