Repository artsy/eigen, pull requests merged in 2022-04, with the labels that each got.

#6546 chore: Remove SplitIO Integration
  .env.example
  Podfile.lock
  src/app/AndroidApp.tsx
  src/app/AppRegistry.tsx
  src/app/store/config/features.ts
  src/app/utils/experiments.ts
  src/app/utils/useExperiments.ts
  typings/react-native-config.d.ts
Labels: Jira Synced

#6543 refactor: Search results container
  src/app/Scenes/Search/Search.tsx
  src/app/Scenes/Search/SearchResults.tsx
  src/app/Scenes/Search/components/AlgoliaSearchResults.tsx
  src/app/Scenes/Search/constants.ts
Labels: Squash On Green

#6551 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6553 fix: Adjust My Collection artwork high demand logic
  src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkDemandIndex.tsx
Labels: Jira Synced

#6554 feat: Hide Estimate Range section on MC artwork screen
  src/app/store/config/features.ts
Labels: Jira Synced

#6555 fix: Change My Collection artwork image pagination indicator to dots
  src/app/Scenes/Artwork/Components/ImageCarousel/ImageCarousel.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/NewComponents/NewMyCollectionArtworkHeader.tsx
Labels: Jira Synced

#6533 feat(NX-3052): Modify the UI of the edition selection modal
  src/app/Scenes/Inbox/Components/Conversations/MakeOfferModal.tests.tsx
  src/app/Scenes/Inbox/Components/Conversations/MakeOfferModal.tsx
Labels: Jira Synced

#6564 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6565 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6571 feat(FX-3836): add histogram on Artist Series price filter screen
  src/app/Scenes/ArtistSeries/ArtistSeriesArtworks.tsx
Labels: Jira Synced, Squash On Green

#6498 feat(FX-3739): Size Filter Metric
  src/app/Components/Artist/ArtistArtworks/CreateSavedSearchModal.tests.tsx
  src/app/Components/Artist/ArtistInsights/ArtistInsightsAuctionResults.tests.tsx
  src/app/Components/ArtworkFilter/ArtworkFilterNavigator.tsx
  src/app/Components/ArtworkFilter/ArtworkFilterStore.tsx
  src/app/Components/ArtworkFilter/ArtworkFiltersStore.tests.tsx
  src/app/Components/ArtworkFilter/FilterModal.tests.tsx
  src/app/Components/ArtworkFilter/Filters/AdditionalGeneIDsOptions.tests.tsx
  src/app/Components/ArtworkFilter/Filters/AggregationOptionCommonValidation.tsx
  src/app/Components/ArtworkFilter/Filters/ArtistIDsArtworksOptions.tests.tsx
  src/app/Components/ArtworkFilter/Filters/ArtistNationalitiesOptions.tests.tsx
  src/app/Components/ArtworkFilter/Filters/AttributionClassOptions.tests.tsx
  src/app/Components/ArtworkFilter/Filters/AuctionHouseOptions.tests.tsx
  src/app/Components/ArtworkFilter/Filters/CategoriesOptions.tests.tsx
  src/app/Components/ArtworkFilter/Filters/ColorsOptions.tests.tsx
  src/app/Components/ArtworkFilter/Filters/CustomSizeInputs.tests.tsx
  src/app/Components/ArtworkFilter/Filters/CustomSizeInputs.tsx
  src/app/Components/ArtworkFilter/Filters/GalleriesAndInstitutionsOptions.tests.tsx
  src/app/Components/ArtworkFilter/Filters/KeywordFilter.tests.tsx
  src/app/Components/ArtworkFilter/Filters/LocationCitiesOptions.tests.tsx
  src/app/Components/ArtworkFilter/Filters/MaterialsTermsOptions.tests.tsx
  src/app/Components/ArtworkFilter/Filters/PriceRangeOptions.tests.tsx
  src/app/Components/ArtworkFilter/Filters/SizesOptionsScreen.tests.tsx
  src/app/Components/ArtworkFilter/Filters/SizesOptionsScreen.tsx
  src/app/Components/ArtworkFilter/Filters/SortOptions.tests.tsx
  src/app/Components/ArtworkFilter/Filters/TimePeriodOptions.tests.tsx
  src/app/Components/ArtworkFilter/Filters/WaysToBuyOptions.tests.tsx
  src/app/Components/ArtworkFilter/Filters/YearOptions.tests.tsx
  src/app/Components/ArtworkFilter/Filters/helpers.ts
  src/app/Components/ArtworkFilter/Filters/useMultiSelect.tests.tsx
  src/app/Components/ArtworkFilter/SavedSearch/convertersToFilterParams.ts
  src/app/Components/HeaderArtworksFilter/HeaderArtworksFilterWithTotalArtworks.tests.tsx
  src/app/Scenes/Sale/SaleLotsList.tests.tsx
  src/app/Scenes/SavedSearchAlert/CreateSavedSearchAlert.tests.tsx
  src/app/Scenes/SavedSearchAlert/SavedSearchAlertForm.tsx
  src/app/Scenes/SavedSearchAlert/SavedSearchStore.tsx
  src/app/Scenes/SavedSearchAlert/pillExtractors.tests.ts
  src/app/Scenes/SavedSearchAlert/pillExtractors.ts
  src/app/Scenes/SavedSearchAlert/useSavedSearchPills.ts
  src/app/store/GlobalStore.tsx
  src/app/utils/useLocalizedUnit.ts
  src/palette/elements/Radio/RadioButton.tsx
Labels: Jira Synced

#6574 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6578 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6583 fix(RequestPriceEstimate Button): padding issue on iphone minis
  src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/RequestForPriceEstimate/RequestForPriceEstimateForm.tsx
Labels: Squash On Green

#6584 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6566 feat[SWA-291]: zip code field
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/ArtworkDetailsForm.tests.tsx
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/ArtworkDetailsForm.tsx
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/Components/LocationAutocomplete.tests.tsx
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/Components/LocationAutocomplete.tsx
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/utils/createOrUpdateSubmission.ts
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/utils/testUtils.ts
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/validation.ts
  src/app/store/migration.tests.ts
  src/app/store/migration.ts
  src/app/utils/googleMaps.ts
Labels: Jira Synced

#6591 feat: Adjust demand rank text
  src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkDemandIndex.tsx
Labels: Jira Synced

#6595 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6577 feat(NX-3118): Display edition set selection modal only when the artwork is non-unique
  src/app/Scenes/Inbox/Components/Conversations/ConversationCTA.tsx
  src/app/Scenes/Inbox/Components/Conversations/InquiryMakeOfferButton.tsx
  src/app/Scenes/Inbox/Components/Conversations/OpenInquiryModalButton.tests.tsx
  src/app/Scenes/Inbox/Components/Conversations/OpenInquiryModalButton.tsx
Labels: Jira Synced, Squash On Green

#6596 fix(NX-3119): broken conversations for Collectors without a name
  src/app/Scenes/Inbox/Components/Conversations/Message.tsx
  src/app/Scenes/Inbox/Components/Conversations/Messages.tsx
Labels: Jira Synced

#6600 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6599 fix(CX-2342): fixed appearance o MyCollection placeholder
  src/app/Scenes/MyCollection/MyCollection.tsx
  src/app/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx
Labels: Jira Synced

#6592 feat: Change copy of my collection when no artwork
  images/lock.webp
  images/lock@2x.webp
  images/lock@3x.webp
  src/app/Components/States/ZeroState.tsx
  src/app/Scenes/MyCollection/MyCollection.tests.tsx
  src/app/Scenes/MyCollection/MyCollectionArtworks.tsx
Labels: Jira Synced

#6602 fix(MOPLAT-213): partial revert of #6386, add back auction web view
  Artsy.xcodeproj/project.pbxproj
  Artsy/App/ARScreenPresenterModule.m
  Artsy/Constants/ARAppConstants.h
  Artsy/Constants/ARAppConstants.m
  Artsy/View_Controllers/Auction_Results/ARAuctionWebViewController.h
  Artsy/View_Controllers/Auction_Results/ARAuctionWebViewController.m
  Artsy_Tests/View_Controller_Tests/Web_Browsing/ARAuctionWebViewControllerTests.m
  Podfile.lock
Labels: Jira Synced, Squash On Green

#6604 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6611 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6582 feat: add share auction button
  src/app/Components/FancyModal/FancyModal.tsx
  src/app/Scenes/Sale/Components/SaleHeader.tsx
  src/app/store/config/features.ts
Labels: hackathon

#6605 feat(FX-3888): Price filter design refinements
  src/app/Components/ArtworkFilter/Filters/PriceRangeOptions.tsx
  src/palette/elements/Input/Input.stories.tsx
  src/palette/elements/Input/Input.tests.tsx
  src/palette/elements/Input/Input.tsx
Labels: Jira Synced

#6613 fix(FX-3895): handle special characters on pricerangeoptions screen
  src/app/Components/ArtworkFilter/Filters/PriceRangeOptions.tests.tsx
  src/app/Components/ArtworkFilter/Filters/PriceRangeOptions.tsx
Labels: Jira Synced

#6619 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6618 chore(FX-3887): size filter design refinements
  src/app/Components/ArtworkFilter/Filters/CustomSizeInputs.tsx
Labels: Jira Synced

#6622 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6620 fix(FX-3896): problem when need to click "Save Alert" button twice
  src/app/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
Labels: Jira Synced

#6621 fix(FX-3816): Share link for Viewing Rooms
  src/app/Scenes/ViewingRoom/ViewingRoom.tsx
Labels: Jira Synced, Squash On Green

#6626 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6627 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6629 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6630 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6631 fix: revert "chore: disable build-test-js on beta builds (#6598)" #trivial
  .circleci/config.yml
Labels: Squash On Green

#6624 fix(FX-3814): problem when need to click "Show Results" button twice
  src/app/Components/StickyHeaderPage.tsx
  src/app/Components/Tag/TagArtworks.tsx
  src/app/Scenes/ArtistSeries/ArtistSeries.tsx
  src/app/Scenes/Collection/Collection.tsx
  src/app/Scenes/Fair/Fair.tsx
  src/app/Scenes/Show/Show.tsx
Labels: Jira Synced

#6634 fix: add decorator to phone input story
  src/palette/elements/Input/Input.stories.tsx
Labels: Squash On Green

#6638 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6639 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6640 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6641 chore: Remove AREnableShowOnlySubmittedMyCollectionArtworkFilter feature flag
  src/app/Scenes/MyCollection/utils/localArtworkSortAndFilter.ts
  src/app/store/config/features.ts
Labels: Jira Synced

#6628 fix(FX-3892): App freezes on Sale page when filters are changed
  src/app/Scenes/Sale/Components/SaleActiveBids.tsx
Labels: Jira Synced

#6633 fix(FX-3902): Contact email is not hyperlinked in Request condition report modal
  src/app/Components/Bidding/Screens/ConfirmBid.tests.tsx
  src/app/Components/Bidding/Screens/Registration.tests.tsx
  src/app/Components/Modal.tests.tsx
  src/app/Components/Modal.tsx
  src/app/Scenes/Artwork/Components/RequestConditionReport.tsx
  src/app/utils/renderMarkdown.tsx
Labels: Jira Synced

#6644 feat(NX-3127): add AREnableConversationalBuyNow
  src/app/store/config/features.ts
Labels: Jira Synced

#6645 fix(cx-2501): Fix sort by price my collection filter
  src/app/Scenes/MyCollection/utils/localArtworkSortAndFilter.ts
Labels: Jira Synced

#6646 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6643 chore(SWA-343): Remove ff AREnableAccordionNavigationOnSubmitArtwork
  src/app/store/config/features.ts
Labels: Jira Synced

#6636 (BID-294): Add timers sale artwork grid
  src/app/Components/ArtworkGrids/ArtworkGridItem.tests.tsx
  src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
  src/app/Components/ArtworkGrids/LotCloseInfo.tests.tsx
  src/app/Components/ArtworkGrids/LotCloseInfo.tsx
  src/app/Components/SaleArtworkTileRailCard/SaleArtworkTileRailCard.tsx
  src/app/store/config/features.ts
  src/app/utils/useTimer.tsx
Labels: Squash On Green

#6648 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6568 feat: Explanatory banner for empty Collector Profile
  src/app/Scenes/MyCollection/MyCollection.tsx
  src/app/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tests.tsx
  src/app/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx
  src/app/Scenes/SellWithArtsy/SubmitArtwork/ContactInformation/ContactInformation.tsx
  src/app/store/config/features.ts
  src/app/store/config/visualClues.ts
Labels: Jira Synced

#6649 fix(CX-2496): Materials and Medium interchanged
  src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkAbout/MyCollectionArtworkAboutWork.tsx
Labels: Jira Synced

#6654 fix: adjust margins in price filter
  src/app/Components/ArtworkFilter/Filters/PriceRangeOptions.tsx
Labels: Jira Synced, Squash On Green

#6655 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6625 fix(FX-3904): `CVC` text in Card Information is poorly wrapped and truncated
  patches/react-native-credit-card-input+0.4.1.patch
Labels: Jira Synced

#6653 Fix (BX-201): Fix padding on cascading end times banner on lot page
  src/app/Scenes/Artwork/Components/CascadingEndTimesBanner.tsx
Labels: Squash On Green

#6658 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6650 chore: Remove the old My Collection artwork screen
  .secrets.baseline
  src/app/AppRegistry.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/OldMyCollectionArtworkArtistAuctionResults.tests.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/OldMyCollectionArtworkArtistAuctionResults.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/OldMyCollectionArtworkArtistMarket.tests.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/OldMyCollectionArtworkArtistMarket.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/OldMyCollectionArtworkDemandIndex.tests.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/OldMyCollectionArtworkDemandIndex.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/OldMyCollectionArtworkInsights.tests.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/OldMyCollectionArtworkInsights.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/Field.tests.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionArtworkHeader.tests.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionArtworkHeader.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionArtworkMeta.tests.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionArtworkMeta.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/OldField.tests.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/OldField.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/OldWhySell.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tests.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/NewComponents/NewMyCollectionArtworkHeader.tests.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/NewComponents/NewMyCollectionArtworkHeader.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/OldMyCollectionArtwork.tests.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/OldMyCollectionArtwork.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tests.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkFullDetails/MyCollectionArtworkFullDetails.tests.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkFullDetails/MyCollectionArtworkFullDetails.tsx
  src/app/Scenes/MyCollection/State/MyCollectionArtworkModel.tsx
  src/app/Scenes/MyCollection/mutations/myCollectionCreateArtwork.ts
  src/app/Scenes/MyCollection/mutations/myCollectionUpdateArtwork.ts
  src/app/navigation/routes.tests.tsx
  src/app/navigation/routes.tsx
  src/app/store/config/features.ts
Labels: Jira Synced

#6660 feat: add my collection insights feature flag
  Podfile.lock
  src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsights.tsx
  src/app/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx
  src/app/store/config/features.ts
Labels: Jira Synced, Squash On Green

#6562 feat: android braze push
  Gemfile.lock
  Podfile
  Podfile.lock
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/net/artsy/app/BrazePushListenerService.java
  android/app/src/main/java/net/artsy/app/MainActivity.java
  android/app/src/main/java/net/artsy/app/MainApplication.java
  android/app/src/main/res/values/braze.xml
  package.json
  src/app/navigation/navigate.ts
  src/app/utils/PushNotification.tests.ts
  src/app/utils/PushNotification.ts
  src/app/utils/track/SegmentTrackingProvider.ts
  src/app/utils/useIdentifyUser.ts
  src/setupJest.ts
  yarn.lock
Labels: Jira Synced, Squash On Green

#6665 fix: hide filter menu item when aggregation counts are empty
  src/app/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx
  src/app/Components/ArtworkFilter/FilterModal.tests.tsx
Labels: Squash On Green

#6664 chore(CX-2520): clean up feature flag AREnableMyCollectionComparableWorks
  src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtworkInsights.tests.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtworkInsights.tsx
  src/app/store/config/features.ts
Labels: Jira Synced

#6663 chore(CX-2524): clean up feature flag AREnableCollectorProfile
  src/app/Scenes/MyProfile/MyProfileEditForm.tsx
  src/app/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tests.tsx
  src/app/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx
  src/app/Scenes/MyProfile/__tests__/MyProfileEditForm.tests.tsx
  src/app/store/config/features.ts
Labels: Jira Synced

#6666 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6661 feat(CX-2509): added MyCollectionInsightsOverview, UI only
  src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsights.tsx
  src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsightsOverview.tests.tsx
  src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsightsOverview.tsx
Labels: Jira Synced

#6667 feat(SWA-325): remove maxwidth from cta button
  src/palette/elements/Button/CTAButton.tsx
Labels: Jira Synced

#6669 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6670 feat(cx-2438): sort and filter for high demand index
  src/app/Scenes/MyCollection/MyCollectionArtworks.tsx
  src/app/Scenes/MyCollection/utils/localArtworkSortAndFilter.ts
Labels: Jira Synced

#6671 fix: Let Profile header update on Relay data change
  src/app/Scenes/MyProfile/MyProfileHeader.tsx
  src/app/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx
Labels: Jira Synced

#6672 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6673 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6675 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6674 fix(CX-2499): fixed rarity filter in MyCollection
  src/app/Scenes/MyCollection/MyCollectionArtworks.tsx
  src/app/Scenes/MyCollection/utils/localArtworkSortAndFilter.ts
Labels: Jira Synced

#6545 feat: add a toggle for order update pushes
  src/app/Scenes/MyProfile/MyProfilePushNotifications.tests.tsx
  src/app/Scenes/MyProfile/MyProfilePushNotifications.tsx
Labels: Squash On Green, hackathon

#6679 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6678 feat(NX-3131): add contact gallery small cta for buy now artworks
  src/app/Scenes/Artwork/Artwork.tests.tsx
  src/app/Scenes/Artwork/Artwork.tsx
  src/app/Scenes/Artwork/Components/CommercialButtons/CommercialButtons.tsx
  src/app/Scenes/Artwork/Components/CommercialButtons/InquiryButtons.tsx
  src/app/Scenes/Artwork/Components/Questions.tests.tsx
  src/app/Scenes/Artwork/Components/Questions.tsx
Labels: Jira Synced

#6683 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6692 chore: update keywords #trivial
  fastlane/metadata/en-US/keywords.txt
Labels: Squash On Green
