Repository artsy/eigen, pull requests merged in 2022-02, with the labels that each got.

#6133 chore(FX-3664): replace deprecated artistID with artistIDs[]
  src/__generated__/SavedSearchAlertQuery.graphql.ts
  src/__generated__/SavedSearchAlertsListQuery.graphql.ts
  src/__generated__/SavedSearchesListQuery.graphql.ts
  src/__generated__/SavedSearchesListTestsQuery.graphql.ts
  src/__generated__/SavedSearchesList_me.graphql.ts
  src/__generated__/SearchCriteriaQuery.graphql.ts
  src/lib/Components/ArtworkFilter/SavedSearch/constants.ts
  src/lib/Components/ArtworkFilter/SavedSearch/searchCriteriaHelpers.tests.ts
  src/lib/Components/ArtworkFilter/SavedSearch/searchCriteriaHelpers.ts
  src/lib/Components/ArtworkFilter/SavedSearch/types.ts
  src/lib/Scenes/Artist/SearchCriteria.tests.tsx
  src/lib/Scenes/Artist/SearchCriteria.tsx
  src/lib/Scenes/SavedSearchAlert/EditSavedSearchAlert.tests.tsx
  src/lib/Scenes/SavedSearchAlert/EditSavedSearchAlert.tsx
  src/lib/Scenes/SavedSearchAlert/SavedSearchAlert.tsx
  src/lib/Scenes/SavedSearchAlert/SavedSearchAlertForm.tests.tsx
  src/lib/Scenes/SavedSearchAlert/SavedSearchAlertForm.tsx
  src/lib/Scenes/SavedSearchAlert/helpers.tests.ts
  src/lib/Scenes/SavedSearchAlertsList/Components/SavedSearchesList.tsx
Labels: Jira Synced

#6097 fix: fix sentry traces
  Gemfile.lock
  HACKS.md
  Podfile.lock
  app.json
  fastlane/Fastfile
  package.json
  patches/@sentry+react-native+3.1.1.patch
  src/lib/ErrorReporting.ts
  src/lib/Scenes/Artwork/Components/ArtworksInSeriesRail.tsx
  src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/Components/ArtistAutosuggestResults.tsx
  src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/Components/ErrorView.tsx
  src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/Components/InfoModal.tests.tsx
  src/lib/store/config/EchoModel.tests.tsx
  src/lib/utils/AdminMenu.tsx
  yarn.lock
Labels: Jira Synced, Squash On Green

#6130 fix(CX-2291): Can't save location when editing artwork in My Collection
  src/__generated__/MyCollectionArtworkFullDetailsQuery.graphql.ts
  src/__generated__/MyCollectionArtworkFullDetailsTestsQuery.graphql.ts
  src/__generated__/MyCollectionArtworkFullDetails_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkListItemTestsQuery.graphql.ts
  src/__generated__/MyCollectionArtworkQuery.graphql.ts
  src/__generated__/MyCollectionArtwork_sharedProps.graphql.ts
  src/__generated__/myCollectionAddArtworkMutation.graphql.ts
  src/__generated__/myCollectionEditArtworkMutation.graphql.ts
  src/lib/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tests.tsx
  src/lib/Scenes/MyCollection/State/MyCollectionArtworkModel.tsx
Labels: Jira Synced

#6142 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6055 feat: Add profession, location and otherRelevantPosition to profile form
  src/__generated__/MyCollectionAndSavedWorksQuery.graphql.ts
  src/__generated__/MyCollectionAndSavedWorksTestsQuery.graphql.ts
  src/__generated__/MyProfileEditFormModal_me.graphql.ts
  src/__generated__/updateMyUserProfileMutation.graphql.ts
  src/lib/Components/DetailedLocationAutocomplete.tests.tsx
  src/lib/Components/DetailedLocationAutocomplete.tsx
  src/lib/Scenes/MyAccount/updateMyUserProfile.ts
  src/lib/Scenes/MyProfile/MyCollectionAndSavedWorks.tsx
  src/lib/Scenes/MyProfile/MyProfileEditFormModal.tsx
Labels: Jira Synced

#6146 fix: Artwork placeholder stuck bug given dismissed modal event
  src/lib/Scenes/Artwork/Artwork.tests.tsx
  src/lib/Scenes/Artwork/Artwork.tsx
Labels: Jira Synced

#6148 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6152 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6138 ci(tests): update ios version for tests
  .circleci/config.yml
  .yarnrc
  Artsy_Tests/Supporting_Files/ARTestHelper.m
  scripts/source-for-bash-env
Labels: Squash On Green

#6109 fix(detect-secrets): improve how secret detection works
  .circleci/config.yml
  .husky/pre-commit
  .secrets.baseline
  docs/troubleshooting.md
  package.json
  requirements.txt
  scripts/detect-secrets-all
  scripts/detect-secrets-generate-baseline
  scripts/detect-secrets-staged
  scripts/install
  scripts/secrets-add-all
  scripts/secrets-add-staged
  scripts/secrets-check-all
  scripts/secrets-check-staged
  scripts/secrets-generate-baseline
  yarn.lock
Labels: Squash On Green

#6154 fix(CX-2048): Cover picture on My Collection and Picture on Artwork details are formatted differently after initial upload
  src/lib/Scenes/MyCollection/Components/MyCollectionImageView.tsx
Labels: Jira Synced

#6153 fix: Deactivate placeholder layout animation for android
  src/lib/store/config/features.ts
  src/lib/tests/MockRelayRenderer.tests.tsx
  src/lib/utils/placeholders.tsx
Labels: Squash On Green

#6160 chore(CX-2304): Create ARShowConsignmentsInMyCollection feature flag
  src/lib/store/config/features.ts
Labels: Jira Synced

#6124 feat: ContactInformation
  src/__generated__/ContactInformationQueryRendererQuery.graphql.ts
  src/__generated__/ContactInformation_me.graphql.ts
  src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/ArtworkDetails.tests.tsx
  src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/ArtworkDetails.tsx
  src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/ArtworkDetailsForm.tests.tsx
  src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/ArtworkDetailsForm.tsx
  src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/Components/ArtistAutosuggest.tsx
  src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/Components/ArtistAutosuggestResults.tsx
  src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/Components/LocationAutocomplete.tsx
  src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/utils/createOrUpdateSubmission.ts
  src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/utils/rarityOptions.ts
  src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/validation.ts
  src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/Components/ErrorView.tests.tsx
  src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/Components/ErrorView.tsx
  src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/ContactInformation/ContactInformation.tests.tsx
  src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/ContactInformation/ContactInformation.tsx
  src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/ContactInformation/validation.ts
  src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/State/SubmissionModel.tsx
  src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/SubmitArtworkOverview.tsx
  src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/utils/rarityOptions.ts
  src/lib/Scenes/ViewingRoom/ViewingRoomArtwork.tsx
  src/lib/store/migration.tests.ts
  src/lib/store/migration.ts
Labels: Jira Synced

#6157 chore(CX-2323): add my collection artwork screen feature flag
  src/__generated__/MyCollectionArtworkFullDetails_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkListItemTestsQuery.graphql.ts
  src/__generated__/OldMyCollectionArtworkQuery.graphql.ts
  src/__generated__/OldMyCollectionArtwork_sharedProps.graphql.ts
  src/__generated__/myCollectionAddArtworkMutation.graphql.ts
  src/__generated__/myCollectionEditArtworkMutation.graphql.ts
  src/lib/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tests.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/OldMyCollectionArtwork.tests.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/OldMyCollectionArtwork.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkFullDetails/MyCollectionArtworkFullDetails.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkList/MyCollectionArtworkListItem.tests.tsx
  src/lib/Scenes/MyCollection/State/MyCollectionArtworkModel.tsx
  src/lib/Scenes/MyCollection/mutations/myCollectionAddArtwork.ts
  src/lib/Scenes/MyCollection/mutations/myCollectionEditArtwork.ts
  src/lib/store/config/features.ts
Labels: Jira Synced

#6168 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6170 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6171 [CX-2331]: Remove AROptionsArtistSeries feature flag
  src/lib/Components/Artist/ArtistAbout/ArtistAbout.tsx
  src/lib/Scenes/Artwork/Artwork.tests.tsx
  src/lib/Scenes/Artwork/Artwork.tsx
  src/lib/store/config/features.ts
Labels: Jira Synced, Squash On Green

#6173 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6115 feat: My Collection search bar
  src/__generated__/InfiniteScrollArtworksGrid_myCollectionConnection.graphql.ts
  src/__generated__/MyCollectionPaginationQuery.graphql.ts
  src/__generated__/MyCollectionQuery.graphql.ts
  src/__generated__/MyCollectionTestsQuery.graphql.ts
  src/__generated__/MyCollection_me.graphql.ts
  src/lib/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx
  src/lib/Components/StickyTabPage/SitckyTabPageContext.tsx
  src/lib/Components/StickyTabPage/StickyTabPage.tsx
  src/lib/Scenes/MyCollection/Components/MyCollectionSearchBar.tsx
  src/lib/Scenes/MyCollection/MyCollection.tsx
  src/lib/Scenes/MyCollection/utils/localArtworkSortAndFilter.ts
  src/lib/store/config/features.ts
Labels: Jira Synced

#6162 fix: Prevent new lines in My Profile bio
  src/lib/Scenes/MyProfile/MyCollectionAndSavedWorks.tsx
  src/lib/Scenes/MyProfile/MyProfileEditFormModal.tsx
  src/lib/Scenes/MyProfile/utils.ts
Labels: Jira Synced

#6179 chore: fix failing tests due to ff release
  src/lib/Components/Artist/ArtistArtworks/SavedSearchButton.tests.tsx
  src/lib/Components/ArtworkFilter/FilterModal.tests.tsx
  src/lib/Components/ArtworkFilter/Filters/ArtistNationalitiesOptions.tests.tsx
  src/lib/Components/ArtworkFilter/components/ArtworkFilterApplyButton.tests.tsx
  src/lib/Components/ArtworkFilter/components/ArtworkFilterOptionsHeader.tests.tsx
  src/lib/Components/Gene/GeneArtworks.tests.tsx
  src/lib/Components/Tag/TagArtworks.tests.tsx
  src/lib/Scenes/MyCollection/MyCollection.tests.tsx
  src/lib/Scenes/Sale/Sale.tests.tsx
  src/lib/Scenes/SavedSearchAlert/Components/CreateSavedSearchContent.tests.tsx
  src/lib/Scenes/SavedSearchAlert/CreateSavedSearchAlert.tests.tsx
  src/lib/Scenes/SavedSearchAlert/EditSavedSearchAlert.tests.tsx
  src/lib/Scenes/SavedSearchAlert/SavedSearchAlertForm.tests.tsx
Labels: Squash On Green

#6177 feat: Add no results for filter message to My Collection
  src/lib/Scenes/MyCollection/MyCollection.tsx
  src/lib/Scenes/MyCollection/MyCollectionArtworks.tsx
Labels: Jira Synced, Squash On Green

#6163 fix(SWA-198): submissions without photos
  src/lib/Scenes/Consignments/Screens/Overview-uploading.tests.tsx
  src/lib/Scenes/Consignments/Screens/Overview.tests.tsx
  src/lib/Scenes/Consignments/Screens/Overview.tsx
Labels: Jira Synced

#6181 feat [SWA-205] CollapsibleView component
  src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/ArtworkDetails.tsx
  src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/ArtworkDetailsForm.tsx
  src/palette/elements/Collapse/CollapseView.tsx
  src/palette/elements/Collapse/index.tsx
  src/palette/elements/CollapsibleMenuItem/CollapsibleMenuItem.tsx
Labels: Jira Synced, Squash On Green

#6174 Update metaphysics schema
  data/schema.graphql
  src/__generated__/myCollectionAddArtworkMutation.graphql.ts
Labels: Squash On Green

#6184 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6185 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6186 feat(tracking): moving the top-level tracking to the AppProviders
  patches/@types+react-relay+11.0.3.patch
  src/lib/AndroidApp.tsx
  src/lib/AppProviders.tsx
  src/lib/AppRegistry.tsx
  src/lib/Components/RetryErrorBoundary.tsx
  src/lib/utils/combineProviders.tests.tsx
  src/lib/utils/combineProviders.tsx
Labels: Squash On Green

#6158 feat: Convert My Profile Edit Modal into navigation container
  .secrets.baseline
  src/__generated__/MyProfileEditFormQuery.graphql.ts
  src/__generated__/MyProfileEditForm_me.graphql.ts
  src/__generated__/MyProfileHeaderMyCollectionAndSavedWorksQuery.graphql.ts
  src/__generated__/MyProfileHeaderMyCollectionAndSavedWorksRefetchQuery.graphql.ts
  src/__generated__/MyProfileHeaderMyCollectionAndSavedWorksTestsQuery.graphql.ts
  src/__generated__/MyProfileHeaderMyCollectionAndSavedWorks_me.graphql.ts
  src/lib/AppRegistry.tsx
  src/lib/Scenes/MyProfile/MyProfile.tsx
  src/lib/Scenes/MyProfile/MyProfileEditForm.tsx
  src/lib/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tests.tsx
  src/lib/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx
  src/lib/Scenes/MyProfile/MyProfileProvider.tsx
Labels: Jira Synced

#6190 feat: my collection artwork details page header
  src/__generated__/MyCollectionArtworkQuery.graphql.ts
  src/__generated__/NewMyCollectionArtworkHeaderTestQuery.graphql.ts
  src/__generated__/NewMyCollectionArtworkHeader_artwork.graphql.ts
  src/lib/AppRegistry.tsx
  src/lib/Scenes/Artwork/Components/ImageCarousel/ImageWithLoadingState.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tests.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/NewComponents/NewMyCollectionArtworkHeader.tests.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/NewComponents/NewMyCollectionArtworkHeader.tsx
  src/lib/tests/renderWithWrappers.tsx
Labels: Jira Synced

#6139 feat(NX-3071): Add see details link on initial offer message (inbox)
  src/lib/AppRegistry.tsx
  src/lib/Scenes/Inbox/Components/Conversations/MessageGroup.tsx
  src/lib/Scenes/Inbox/Components/Conversations/OrderUpdate.tests.tsx
  src/lib/Scenes/Inbox/Components/Conversations/OrderUpdate.tsx
  src/lib/navigation/routes.tsx
Labels: Jira Synced

#6192 fix: Merge MyProfileEditForm and MyProfileEditFormModal
  src/__generated__/MyProfileEditFormModal_me.graphql.ts
  src/__generated__/MyProfileEditFormQuery.graphql.ts
  src/__generated__/MyProfileEditFormTestsQuery.graphql.ts
  src/__generated__/MyProfileEditForm_me.graphql.ts
  src/__generated__/MyProfileEditForm_meRefetch.graphql.ts
  src/__generated__/MyProfileHeaderMyCollectionAndSavedWorksQuery.graphql.ts
  src/__generated__/MyProfileHeaderMyCollectionAndSavedWorksRefetchQuery.graphql.ts
  src/__generated__/MyProfileHeaderMyCollectionAndSavedWorksTestsQuery.graphql.ts
  src/__generated__/MyProfileHeaderMyCollectionAndSavedWorks_me.graphql.ts
  src/__generated__/updateMyUserProfileMutation.graphql.ts
  src/lib/AppRegistry.tsx
  src/lib/Components/DetailedLocationAutocomplete.tsx
  src/lib/Scenes/MyAccount/updateMyUserProfile.ts
  src/lib/Scenes/MyProfile/MyProfile.tsx
  src/lib/Scenes/MyProfile/MyProfileEditForm.tsx
  src/lib/Scenes/MyProfile/MyProfileEditFormModal.tsx
  src/lib/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx
  src/lib/Scenes/MyProfile/__tests__/MyProfileEditForm.tests.tsx
Labels: Squash On Green

#6194 chore: Remove unnecessary exports
  src/lib/Scenes/MyProfile/MyProfileEditForm.tsx
Labels: Squash On Green

#6195 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6175 fix: broken artist screen animation
  src/lib/utils/useAutoCollapsingMeasuredView.tsx
Labels: Squash On Green

#6199 fix: Remove selectTextOnFocus from My Collection search bar
  src/lib/Scenes/MyCollection/Components/MyCollectionSearchBar.tsx
Labels: Squash On Green

#6200 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6202 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6191 chore: Await findByText in all tests
  src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/Components/InfoModal.tests.tsx
  src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/Components/ErrorView.tests.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtistSearchResult.tests.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/Components/Rarity.tests.tsx
  src/lib/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tests.tsx
Labels: Squash On Green

#6207 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6206 fix: add padding to profile verifications
  src/lib/Scenes/MyProfile/MyProfileEditForm.tsx
Labels: Jira Synced

#6211 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6215 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6193 chore(FX-3731): Saved Alerts copy updates
  src/lib/Components/Artist/ArtistArtworks/CreateSavedSearchModal.tsx
  src/lib/Components/ArtworkFilter/FilterModal.tests.tsx
  src/lib/Components/ArtworkFilter/components/ArtworkFilterApplyButton.tests.tsx
  src/lib/Components/ArtworkFilter/components/ArtworkFilterApplyButton.tsx
  src/lib/Components/Gene/GeneArtworks.tests.tsx
  src/lib/Components/Tag/TagArtworks.tests.tsx
  src/lib/Scenes/MyCollection/MyCollection.tests.tsx
  src/lib/Scenes/Sale/Sale.tests.tsx
  src/lib/Scenes/SavedSearchAlert/Components/Form.tsx
  src/lib/Scenes/SavedSearchAlert/SavedSearchAlertForm.tests.tsx
  src/lib/Scenes/SavedSearchAlert/SavedSearchAlertForm.tsx
  src/lib/Scenes/SavedSearchAlert/helpers.ts
  src/lib/Scenes/SavedSearchAlertsList/Components/EmptyMessage.tsx
  src/lib/Scenes/SavedSearchAlertsList/Components/SavedSearchesList.tests.tsx
Labels: Jira Synced

#6225 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6213 Feat(SWA 223): Test ContactInformation
  docs/testing.md
  src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/ContactInformation/ContactInformation.tests.tsx
  src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/ContactInformation/ContactInformation.tsx
Labels: Jira Synced

#6229 fix(CX-2345): ReadMore line height changes after expansion
  src/lib/Scenes/Show/Screens/ShowMoreInfo.tsx
Labels: Jira Synced

#6234 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6235 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6236 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6237 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6003 feature(auth): link multiple social/email accounts
  .secrets.baseline
  Artsy/Networking/ARNetworkConstants.h
  Artsy/Networking/ARNetworkConstants.m
  package.json
  src/__generated__/MyAccountQuery.graphql.ts
  src/__generated__/MyAccountTestsQuery.graphql.ts
  src/__generated__/MyAccount_me.graphql.ts
  src/__generated__/apple_LinkAccountMutation.graphql.ts
  src/__generated__/apple_UnlinkAccountMutation.graphql.ts
  src/__generated__/facebook_LinkAccountMutation.graphql.ts
  src/__generated__/facebook_UnlinkAccountMutation.graphql.ts
  src/__generated__/google_LinkAccountMutation.graphql.ts
  src/__generated__/google_UnlinkAccountMutation.graphql.ts
  src/lib/Components/MenuItem.tsx
  src/lib/Scenes/MyAccount/MyAccount.tests.tsx
  src/lib/Scenes/MyAccount/MyAccount.tsx
  src/lib/Scenes/Onboarding/Onboarding.tsx
  src/lib/Scenes/Onboarding/OnboardingCreateAccount/OnboardingCreateAccount.tsx
  src/lib/Scenes/Onboarding/OnboardingCreateAccount/OnboardingSocialPick.tests.tsx
  src/lib/Scenes/Onboarding/OnboardingLogin.tests.tsx
  src/lib/Scenes/Onboarding/OnboardingLoginWithOTP.tests.tsx
  src/lib/Scenes/Onboarding/OnboardingLoginWithOTP.tsx
  src/lib/Scenes/Onboarding/OnboardingSocialLink.tests.tsx
  src/lib/Scenes/Onboarding/OnboardingSocialLink.tsx
  src/lib/Scenes/Onboarding/OnboardingSocialPick.tsx
  src/lib/store/AuthError.ts
  src/lib/store/AuthModel.tests.ts
  src/lib/store/AuthModel.ts
  src/lib/store/GlobalStore.tsx
  src/lib/store/config/features.ts
  src/lib/utils/LinkedAccounts/apple.ts
  src/lib/utils/LinkedAccounts/facebook.ts
  src/lib/utils/LinkedAccounts/google.ts
  yarn.lock
Labels: Jira Synced, Squash On Green

#6240 Update metaphysics schema
  data/schema.graphql
  src/__generated__/ConfirmBidUpdateUserMutation.graphql.ts
  src/__generated__/RegistrationUpdateUserMutation.graphql.ts
  src/__generated__/updateEmailFrequencyMutation.graphql.ts
  src/__generated__/updateMyUserProfileMutation.graphql.ts
Labels: Squash On Green

#6209 feat(TX-168): add Avalara phase 2 feature flag and new tax message
  src/lib/Scenes/Artwork/Components/CommercialPartnerInformation.tests.tsx
  src/lib/Scenes/Artwork/Components/CommercialPartnerInformation.tsx
  src/lib/store/config/features.ts
Labels: Jira Synced

#6221 feat(CX-2297): Artwork Detail Page | Status Explanatory Page (what's this)
  src/lib/AppRegistry.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/ArtworkSubmissionStatusFAQ.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionArtworkSubmissionStatus.tsx
  src/lib/navigation/routes.tsx
Labels: Jira Synced, Squash On Green

#6232 docs: update folder capitalisation preferred practices
  docs/preferred_practices.md
Labels: Squash On Green

#6239 chore: Add migration test for view options
  src/lib/store/migration.tests.ts
Labels: Jira Synced

#6246 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6247 fix: android deeplinks, watch login state in deeplink setup
  src/lib/utils/useDeepLinks.ts
Labels: Jira Synced

#6222 [CX-2326]: Hide Artwork Edit Button when the submission is in progress
  .secrets.baseline
  src/__generated__/MyCollectionArtworkFullDetailsQuery.graphql.ts
  src/__generated__/MyCollectionArtworkFullDetailsTestsQuery.graphql.ts
  src/__generated__/MyCollectionArtworkFullDetails_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkGridItemTestsQuery.graphql.ts
  src/__generated__/MyCollectionArtworkQuery.graphql.ts
  src/__generated__/OldMyCollectionArtworkQuery.graphql.ts
  src/__generated__/OldMyCollectionArtwork_sharedProps.graphql.ts
  src/__generated__/myCollectionAddArtworkMutation.graphql.ts
  src/__generated__/myCollectionEditArtworkMutation.graphql.ts
  src/lib/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tests.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/OldMyCollectionArtwork.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tests.tsx
Labels: Jira Synced, Squash On Green

#6249 chore(FX-3753): Restore listing of articles not in the editorial feed to fair screen
  src/__generated__/FairArticlesQuery.graphql.ts
  src/__generated__/FairArticles_fair.graphql.ts
  src/__generated__/FairEditorialTestsQuery.graphql.ts
  src/__generated__/FairEditorial_fair.graphql.ts
  src/__generated__/FairQuery.graphql.ts
  src/__generated__/FairTestsQuery.graphql.ts
  src/__generated__/Fair_fair.graphql.ts
  src/__generated__/VanityURLEntityQuery.graphql.ts
  src/lib/Scenes/Fair/Components/FairEditorial.tsx
  src/lib/Scenes/Fair/Fair.tsx
  src/lib/Scenes/Fair/FairArticles.tsx
Labels: Jira Synced

#6253 fix(.env): .env files formatting
  .editorconfig
  .env.example
  package.json
  scripts/update-env-for-artsy
  src/setupJest.ts
  typings/react-native-config.d.ts
Labels: Squash On Green

#6256 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6258 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6264 chore: remove AREnableSortFilterForArtworksPill feature flag
  src/lib/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx
  src/lib/store/config/features.ts
Labels: Jira Synced

#6270 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6271 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6266 feat(flag): just adding a flag for now, for dark mode
  src/lib/AndroidApp.tsx
  src/lib/AppProviders.tsx
  src/lib/AppRegistry.tsx
  src/lib/Components/SwitchMenu.tsx
  src/lib/Scenes/About/About.tsx
  src/lib/Scenes/BottomTabs/BottomTabsIcon.tsx
  src/lib/Scenes/BottomTabs/BottomTabsNavigator.tsx
  src/lib/Scenes/MyCollection/Components/MyCollectionSearchBar.tsx
  src/lib/Scenes/MyCollection/MyCollection.tsx
  src/lib/Scenes/MyCollection/MyCollectionArtworks.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/Components/Dimensions.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormArtwork.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormMain.tsx
  src/lib/Scenes/MyCollection/State/MyCollectionArtworkModel.tsx
  src/lib/Scenes/MyProfile/DarkModeSettings.tsx
  src/lib/Scenes/MyProfile/DevicePrefsModel.ts
  src/lib/Scenes/MyProfile/MyProfileSettings.tsx
  src/lib/Scenes/Search/UserPrefsModel.tsx
  src/lib/errorReporting/hooks.ts
  src/lib/navigation/routes.tests.tsx
  src/lib/navigation/routes.tsx
  src/lib/store/ArtsyPrefsModel.ts
  src/lib/store/AuthModel.ts
  src/lib/store/GlobalStore.tsx
  src/lib/store/GlobalStoreModel.ts
  src/lib/store/config/EchoModel.tests.tsx
  src/lib/store/config/EchoModel.tsx
  src/lib/store/config/FeaturesModel.tests.tsx
  src/lib/store/config/FeaturesModel.tsx
  src/lib/store/config/UserIsDevModel.tests.tsx
  src/lib/store/config/UserIsDevModel.tsx
  src/lib/store/config/features.ts
  src/lib/store/migration.tests.ts
  src/lib/store/migration.ts
  src/lib/utils/AdminMenu.tsx
  src/lib/utils/AdminMenuWrapper.tsx
  src/lib/utils/queryPrefetching.ts
  src/lib/utils/useExperiments.ts
  src/palette/Theme.tsx
Labels: FF

#6267 feat(metaflags): changing storybook.json into metaflags.json
  .gitignore
  .tool-versions
  docs/metaflags.md
  index.android.js
  index.ios.js
  metaflags.example.json
  package.json
  scripts/download-assets
  scripts/set-storybook-environment.js
  scripts/setup-env-for-artsy
  scripts/setup-env-for-oss
  scripts/start_packager.sh
Labels: FF

#6250 feat (SWA-243) stop back button from floating
  src/lib/AppRegistry.tsx
  src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/SubmitArtworkOverview.tsx
  src/lib/navigation/BackButton.tsx
  src/palette/elements/CollapsibleMenuItem/CollapsibleMenuItem.tsx
Labels: Jira Synced

#6272 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6280 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6275 fix: Improve performance of artwork form metric change
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/Components/Dimensions.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormMain.tsx
  src/palette/elements/Radio/RadioButton.tsx
Labels: Jira Synced

#6284 fix(CX-2373): Update copy on link accounts flow
  src/lib/Scenes/Onboarding/OnboardingSocialLink.tsx
  src/lib/store/AuthModel.ts
Labels: Jira Synced, Squash On Green

#6286 fix: Adjust collector profile verification icon alignment
  src/lib/Scenes/MyProfile/MyProfileEditForm.tsx
  src/lib/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx
Labels: Jira Synced

#6282 [enhancement]: Preserve photos on GS as soon as upload on backend
  src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/UploadPhotos/UploadPhotos.tsx
  src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/UploadPhotos/UploadPhotosForm.tsx
Labels: Squash On Green

#6289 fix: improve next behaviour on collector profile edit
  src/lib/Components/DetailedLocationAutocomplete.tsx
  src/lib/Scenes/MyProfile/MyProfileEditForm.tsx
Labels: Jira Synced

#6294 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6297 fix: keyboard issues on my collection edit profile screen
  src/app/Scenes/MyProfile/MyProfileEditForm.tsx
Labels: Jira Synced, Squash On Green

#6300 chore: remove shows for you rail ff
  src/app/Scenes/Home/Home.tsx
  src/app/store/config/features.ts
Labels: Jira Synced, Squash On Green

#6299 chore: remove enable trove ff
  src/app/Scenes/Home/Home.tsx
  src/app/store/config/features.ts
Labels: Jira Synced

#6298 fix: bio line breaks issues on the collector profile
  src/app/Scenes/MyProfile/MyProfileEditForm.tsx
  src/app/Scenes/MyProfile/utils.tests.ts
  src/app/Scenes/MyProfile/utils.ts
Labels: Jira Synced

#6296 chore: add ARShowDemandIndexHints and ARShowwRequestPriceEstimateBanner feature flags
  src/app/store/config/features.ts
Labels: Jira Synced

#6301 chore: refactor some thunks inside the AuthModel
  src/app/Scenes/Onboarding/OnboardingPersonalization/OnboardingPersonalization.tsx
  src/app/store/AuthModel.ts
  src/app/utils/PushNotification.ts
Labels: Squash On Green

#6307 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6309 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6311 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6312 feat(NX-3082): Change artwork and CTAs copies
  src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
  src/app/Scenes/Artwork/Components/CommercialButtons/BuyNowButton.tsx
  src/app/Scenes/Artwork/Components/CommercialButtons/CommercialButtons.tests.tsx
  src/app/Scenes/Artwork/Components/CommercialButtons/MakeOfferButton.tsx
  src/app/Scenes/Artwork/Components/CommercialInformation.tsx
  src/app/Scenes/Inbox/Components/Conversations/EditionSelectBox.tsx
  src/app/Scenes/Inbox/Components/Conversations/InquiryMakeOfferButton.tsx
  src/app/Scenes/Inbox/Components/Conversations/ItemArtwork.tests.tsx
  src/app/Scenes/Inbox/Components/Conversations/ItemArtwork.tsx
  src/app/Scenes/Inbox/Components/Conversations/OpenInquiryModalButton.tsx
  src/app/utils/ArtworkInquiry/ArtworkInquiryStore.tests.tsx
  src/app/utils/ArtworkInquiry/ArtworkInquiryTypes.ts
Labels: Jira Synced

#6303 feat(swa 253) display email error messages
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ContactInformation/ContactInformation.tests.tsx
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ContactInformation/ContactInformation.tsx
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ContactInformation/validation.ts
  src/app/utils/isValidPhoneNumber.tests.ts
  src/app/utils/isValidPhoneNumber.ts
Labels: Jira Synced

#6291 feat [CX-2287]: My Collection Artwork details about tab
  src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkAbout/MyCollectionArtworkAboutWork.tests.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkAbout/MyCollectionArtworkAboutWork.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkAbout/MyCollectionArtworkArticles.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkAbout/MyCollectionArtworkPurchaseDetails.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/Field.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtworkAbout.tests.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtworkAbout.tsx
Labels: Jira Synced

#6285 feat: Sending ID verification email
  src/app/Scenes/MyProfile/MyProfileEditForm.tsx
  src/app/Scenes/MyProfile/__tests__/MyProfileEditForm.tests.tsx
  src/app/Scenes/MyProfile/useHandleVerification.tsx
  src/app/utils/verifyID.ts
Labels: Jira Synced, Squash On Green

#6315 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6320 chore: Update copy on Collector profile
  src/app/Scenes/MyProfile/MyProfileEditForm.tsx
Labels: Jira Synced

#6319 feature: Scale all icons based on font scale
  src/app/Scenes/MyProfile/MyProfileEditForm.tsx
  src/app/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx
  src/palette/svgs/Icon.tsx
Labels: Squash On Green

#6324 chore: Remove AREnableCustomSharesheet feature flag
  src/app/Scenes/Artwork/Components/ArtworkHeader.tsx
  src/app/store/config/features.ts
Labels: Jira Synced

#6318 feat(cx-2353): add request for price estimate CTA
  src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/RequestForPriceEstimate.tests.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/RequestForPriceEstimate.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtworkInsights.tsx
  src/app/store/config/features.ts
Labels: Jira Synced

#6172 feat(flags): adding Unleash
  .secrets.baseline
  docs/add_an_experiment.md
  docs/screenshots/create-split.png
  docs/screenshots/kill-treatment.png
  docs/screenshots/split-rules.png
  package.json
  src/app/AndroidApp.tsx
  src/app/AppProviders.tsx
  src/app/AppRegistry.tsx
  src/app/Scenes/MyAccount/MyAccount.tsx
  src/app/Scenes/Search/Search.tsx
  src/app/store/config/features.ts
  src/app/utils/experiments.ts
  src/app/utils/experiments/UnleashProvider.tsx
  src/app/utils/experiments/helpers.ts
  src/app/utils/experiments/hooks.ts
  src/app/utils/experiments/reporter.ts
  src/app/utils/experiments/unleashClient.ts
  src/app/utils/nullAndUndef.ts
  src/app/utils/useDebugging.ts
  src/app/utils/useExperiments.ts
  src/app/utils/useIdentifyUser.ts
  src/setupJest.ts
  yarn.lock
Labels: Jira Synced

#6328 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6323 chore: Remove AREnableWebPImages feature flag
  src/app/Components/OpaqueImageView/createGeminiUrl.tsx
  src/app/store/config/features.ts
Labels: Jira Synced

#6321 feat(FX-3758): Price filter slider
  src/app/Components/ArtworkFilter/ArtworkFilterNavigator.tsx
  src/app/Components/ArtworkFilter/Filters/PriceRangeOptions.tests.tsx
  src/app/Components/ArtworkFilter/Filters/PriceRangeOptions.tsx
  src/app/Components/ArtworkFilter/Filters/YearOptions.tsx
  src/app/Components/CircleWithBorder/CircleWithBorder.tsx
  src/palette/elements/Input/Input.tsx
Labels: Jira Synced, Squash On Green

#6325 bug(SWA-228): use consistent error message format
  src/app/Components/PhoneInput/PhoneInput.tests.tsx
  src/app/Components/PhoneInput/PhoneInput.tsx
  src/palette/elements/Input/Input.tests.tsx
  src/palette/elements/Input/Input.tsx
Labels: Jira Synced

#6219 chore: add autofocus to onboarding OTP
  src/app/Scenes/Onboarding/OnboardingLoginWithOTP.tsx
Labels: Squash On Green

#6327 fix: fix old consignments nav
  .secrets.baseline
  src/app/Scenes/Consignments/Screens/ConfirmContactInfo.tsx
  src/app/Scenes/Consignments/Screens/Confirmation.tests.tsx
  src/app/Scenes/Consignments/Screens/Confirmation.tsx
  src/app/Scenes/Consignments/Screens/Overview.tsx
  src/app/Scenes/MyCollection/MyCollection.tests.tsx
  src/setupJest.ts
Labels: Jira Synced

#6335 bug[SWA-248] remove the country code bug
  src/app/Components/PhoneInput/PhoneInput.tsx
Labels: Jira Synced, Squash On Green

#6339 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6333 fix(SWA): submission flow updates
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/ArtworkDetails.tsx
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkSubmitted.tsx
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ContactInformation/ContactInformation.tsx
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/SubmitArtworkOverview.tsx
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/UploadPhotos/UploadPhotos.tsx
  src/palette/elements/CollapsibleMenuItem/CollapsibleMenuItem.tsx
Labels: Squash On Green

#6341 fix: fix issue with back navigation on swa flow
  .secrets.baseline
  src/app/Scenes/Consignments/Screens/ConfirmContactInfo.tsx
  src/app/Scenes/Consignments/Screens/Confirmation.tests.tsx
  src/app/Scenes/Consignments/Screens/Confirmation.tsx
  src/app/Scenes/Consignments/Screens/Overview.tsx
  src/app/Scenes/MyCollection/MyCollection.tests.tsx
  src/setupJest.ts
Labels: Squash On Green

#6313 feat(SWA-90): event tracking for submission flow
  src/app/Scenes/Consignments/ConsignmentsHome/ConsignmentsHome.tsx
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/ArtworkDetails.tests.tsx
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/ArtworkDetails.tsx
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkSubmitted.tsx
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ContactInformation/ContactInformation.tests.tsx
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ContactInformation/ContactInformation.tsx
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/SubmitArtworkOverview.tsx
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/UploadPhotos/UploadPhotos.tests.tsx
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/UploadPhotos/UploadPhotos.tsx
  src/app/Scenes/Consignments/Utils/TrackingEvent.ts
  src/palette/elements/CollapsibleMenuItem/CollapsibleMenuItem.tsx
Labels: Jira Synced, Squash On Green
