Repository artsy/eigen, pull requests merged in 2022-01, with the labels that each got.

#5970 fix sale active bid item failing test
  src/lib/Scenes/Sale/SaleActiveBidItem.tests.tsx
Labels: Squash On Green

#5971 Update metaphysics schema
  data/schema.graphql
  src/__generated__/myCollectionAddArtworkMutation.graphql.ts
  src/__generated__/myCollectionEditArtworkMutation.graphql.ts
Labels: Squash On Green

#5930 chore(FX-3666): Code cleanup after the release of the AREnableSavedSearchToggles flag
  src/lib/Scenes/SavedSearchAlert/Components/CreateSavedSearchContent.tests.tsx
  src/lib/Scenes/SavedSearchAlert/Components/Form.tsx
  src/lib/Scenes/SavedSearchAlert/CreateSavedSearchAlert.tests.tsx
  src/lib/Scenes/SavedSearchAlert/EditSavedSearchAlert.tests.tsx
  src/lib/Scenes/SavedSearchAlert/SavedSearchAlertForm.tests.tsx
  src/lib/Scenes/SavedSearchAlert/SavedSearchAlertForm.tsx
  src/lib/Scenes/SavedSearchAlert/SavedSearchAlertModel.ts
  src/lib/Scenes/SavedSearchAlert/containers/CreateSavedSearchContentContainerV1.tsx
  src/lib/Scenes/SavedSearchAlert/containers/CreateSavedSearchContentContainerV2.tsx
  src/lib/Scenes/SavedSearchAlert/mutations/createSavedSearchAlert.ts
  src/lib/Scenes/SavedSearchAlert/mutations/updateSavedSearchAlert.ts
  src/lib/store/config/features.ts
Labels: Jira Synced

#5966 feat: Rarity classification type explanation modal
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/Components/Rarity.tests.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/Components/Rarity.tsx
  src/lib/utils/artworkRarityClassifications.ts
Labels: Jira Synced, Squash On Green

#5972 fix: Add keyboard avoiding view to artwork form
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormMain.tsx
Labels: Jira Synced

#5944 fix(CX-1060): change description textStyle
  src/lib/Scenes/ArtistSeries/ArtistSeriesMeta.tsx
Labels: Jira Synced

#5973 fix: saving spinner not visible on android in my collection
  src/lib/Components/Modals/LoadingModal.tsx
Labels: Jira Synced, Squash On Green

#5974 Update metaphysics schema
  data/schema.graphql
  src/__generated__/ConfirmBidUpdateUserMutation.graphql.ts
  src/__generated__/RegistrationUpdateUserMutation.graphql.ts
  src/__generated__/updateEmailFrequencyMutation.graphql.ts
  src/__generated__/updateMyUserProfileMutation.graphql.ts
Labels: Squash On Green

#5950 feat(FX-3670): Enable the "save alert" button whenever the "Create Alert" screen has pending updates
  src/lib/Scenes/SavedSearchAlert/Components/Form.tsx
  src/lib/Scenes/SavedSearchAlert/SavedSearchAlertForm.tests.tsx
  src/lib/Scenes/SavedSearchAlert/SavedSearchAlertForm.tsx
Labels: Jira Synced, Squash On Green

#5977 chore: rename select artist to select artwork
  package.json
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tests.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormArtist.tsx
  yarn.lock
Labels: Jira Synced, Squash On Green

#5978 fix[CX-2254]: back button issue in Add Photos when editing artwork
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx
Labels: Jira Synced

#5979 chore: different approach for navigating back on editing photos
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormAddPhotos.tests.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormAddPhotos.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormMain.tsx
Labels: Jira Synced

#5964 fix(CX-2248): broken onboarding webview links on android
  src/lib/Components/ArtsyReactWebViewPolicy.tsx
  src/lib/Scenes/Onboarding/Onboarding.tsx
  src/lib/Scenes/Onboarding/OnboardingCreateAccount/OnboardingCreateAccount.tsx
  src/lib/Scenes/Onboarding/OnboardingCreateAccount/OnboardingCreateAccountName.tsx
  src/lib/Scenes/Onboarding/OnboardingCreateAccount/OnboardingSocialPick.tests.tsx
  src/lib/Scenes/Onboarding/OnboardingCreateAccount/TermsOfServiceCheckbox.tsx
  src/lib/Scenes/Onboarding/OnboardingSocialPick.tsx
Labels: Jira Synced, Squash On Green

#5985 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#5986 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#5987 fix: get previousToken before updating the token
  Artsy/App/ARAppNotificationsDelegate.m
Labels: Jira Synced, Squash On Green

#5988 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#5989 fix: (CX-2253) fix skip bug in my collection artwork forms
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormArtwork.tsx
Labels: Jira Synced

#5856 feat(SWA-89): Accordion navigation
  docs/storybook.md
  src/lib/AppRegistry.tsx
  src/lib/Scenes/Consignments/ConsignmentsHome/ConsignmentsSubmissionForm.tsx
  src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkSubmitted.tsx
  src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/SubmitArtworkOverview.tsx
  src/lib/store/config/features.ts
  src/palette/elements/CollapsibleMenuItem/CollapsibleMenuItem.stories.tsx
  src/palette/elements/CollapsibleMenuItem/CollapsibleMenuItem.tsx
  src/palette/elements/CollapsibleMenuItem/index.ts
  src/palette/elements/Header/ArtsyLogoHeader.tsx
  src/palette/elements/Header/Header.stories.tsx
  src/palette/elements/Header/index.tsx
  src/palette/elements/Text/index.tsx
  src/palette/elements/index.tsx
  src/storybook/storyLoader.js
Labels: Jira Synced

#5992 feat: Adjust My Collection import banner copy
  src/lib/Scenes/MyCollection/MyCollection.tsx
Labels: Jira Synced

#5997 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#5998 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#5996 fix(CX-1759): change all titles and subtitles from Sentence Case to Title Case in Eigen
  src/lib/Components/SectionTitle.tests.tsx
  src/lib/Components/SectionTitle.tsx
  src/lib/Scenes/Search/Search.tests.tsx
  src/lib/Scenes/Search/components/CityGuideCTA.tests.tsx
Labels: Jira Synced

#5933 refactor(FX-3669): pill extractors for saved search
  src/lib/Components/ArtworkFilter/Filters/WaysToBuyOptions.tsx
  src/lib/Components/ArtworkFilter/SavedSearch/convertersToFilterParams.ts
  src/lib/Scenes/SavedSearchAlert/SavedSearchAlertForm.tsx
  src/lib/Scenes/SavedSearchAlert/helpers.tests.ts
  src/lib/Scenes/SavedSearchAlert/helpers.ts
  src/lib/Scenes/SavedSearchAlert/pillExtractors.tests.ts
  src/lib/Scenes/SavedSearchAlert/pillExtractors.ts
Labels: Jira Synced, Squash On Green

#5949 refactor: Use key instead of name for search pills
  src/lib/Scenes/Search/Search.tsx
  src/lib/Scenes/Search/SearchModel.tsx
  src/lib/Scenes/Search/SearchResults.tsx
  src/lib/Scenes/Search/components/SearchPills.tests.tsx
  src/lib/Scenes/Search/components/SearchPills.tsx
  src/lib/Scenes/Search/components/SearchResult.tests.tsx
  src/lib/Scenes/Search/components/SearchResult.tsx
  src/lib/Scenes/Search/constants.ts
  src/lib/Scenes/Search/types.ts
Labels: Squash On Green

#6002 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#5967 feat: Preload artwork placeholder image size
  src/__generated__/ArtworkBelowTheFoldQuery.graphql.ts
  src/__generated__/ArtworkRefetchQuery.graphql.ts
  src/__generated__/FavoriteArtworksPaginationQuery.graphql.ts
  src/__generated__/FavoriteArtworksQuery.graphql.ts
  src/__generated__/FeatureQuery.graphql.ts
  src/__generated__/GenericGrid_artworks.graphql.ts
  src/__generated__/HomeAboveTheFoldQuery.graphql.ts
  src/__generated__/HomeBelowTheFoldQuery.graphql.ts
  src/__generated__/HomeRefetchQuery.graphql.ts
  src/__generated__/MyProfileQuery.graphql.ts
  src/__generated__/MyProfileRefetchQuery.graphql.ts
  src/__generated__/NewWorksForYouRailQuery.graphql.ts
  src/__generated__/ShowArtworksPreviewTestsQuery.graphql.ts
  src/__generated__/SmallTileRail_artworks.graphql.ts
  src/__generated__/WorksForYouPaginationQuery.graphql.ts
  src/__generated__/WorksForYouQuery.graphql.ts
  src/lib/Components/ArtworkGrids/GenericGrid.tsx
  src/lib/Scenes/Artwork/Artwork.tsx
  src/lib/Scenes/Home/Components/SmallTileRail.tsx
  src/lib/utils/relayHelpers.ts
Labels: Squash On Green

#6001 fix: Avoid My Collection price filter crash
  .secrets.baseline
  src/lib/Components/ArtworkFilter/components/ArtworkFilterApplyButton.tsx
  src/lib/Components/ArtworkGrids/ArtworksFilterHeader.tsx
  src/lib/Scenes/MyCollection/MyCollection.tests.tsx
  src/lib/Scenes/MyCollection/MyCollection.tsx
  src/setupJest.ts
Labels: Jira Synced, Squash On Green

#6004 Revert "fix: (CX-2253) fix skip bug in my collection artwork forms"
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormArtwork.tsx
Labels: Jira Synced

#5958 Bugfix(cx-2091): fix broken sharing to instagram stories
  src/lib/Scenes/Artwork/Components/ArtworkHeader.tsx
Labels: Jira Synced

#5876 Feat(cx-2166): my collection image carousel
  ArtsyWidget/Assets.xcassets/PrimaryArticleImage.imageset/Contents.json
  ArtsyWidget/Assets.xcassets/QuaternaryArticleImage.imageset/Contents.json
  ArtsyWidget/Assets.xcassets/SecondaryArticleImage.imageset/Contents.json
  ArtsyWidget/Assets.xcassets/TertiaryArticleImage.imageset/Contents.json
  src/__generated__/MyCollectionArtworkHeaderRefetchQuery.graphql.ts
  src/__generated__/MyCollectionArtworkHeaderTestsQuery.graphql.ts
  src/__generated__/MyCollectionArtworkHeader_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkImagesQuery.graphql.ts
  src/__generated__/MyCollectionArtworkImages_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkQuery.graphql.ts
  src/lib/AppRegistry.tsx
  src/lib/Components/OpaqueImageView/OpaqueImageView.tsx
  src/lib/Scenes/Artwork/Components/ImageCarousel/ImageCarousel.tests.tsx
  src/lib/Scenes/Artwork/Components/ImageCarousel/ImageCarousel.tsx
  src/lib/Scenes/Artwork/Components/ImageCarousel/ImageCarouselContext.tsx
  src/lib/Scenes/Artwork/Components/ImageCarousel/ImageCarouselEmbedded.tests.tsx
  src/lib/Scenes/Artwork/Components/ImageCarousel/ImageCarouselEmbedded.tsx
  src/lib/Scenes/Artwork/Components/ImageCarousel/ImageCarouselPaginationIndicator.tsx
  src/lib/Scenes/MyCollection/Components/MyCollectionImageView.tests.tsx
  src/lib/Scenes/MyCollection/Components/MyCollectionImageView.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionArtworkHeader.tests.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionArtworkHeader.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tests.tsx
  src/lib/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionImageUtil.ts
  src/lib/Scenes/MyCollection/Screens/ArtworkImages/MyCollectionArtworkImages.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkImages/MyCollectionLocalArtworkImages.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkList/MyCollectionArtworkListItem.tsx
  src/lib/navigation/routes.tsx
  src/lib/store/config/features.ts
Labels: Jira Synced

#6005 fix(cx-2253): fix skip bug present in my collection artwork forms
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormMain.tests.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormMain.tsx
Labels: Jira Synced

#6009 chore(FX-3610): Pass correct owner type to analytics for saved search alerts screen
  src/lib/Scenes/SavedSearchAlertsList/Components/SavedSearchesList.tests.tsx
  src/lib/Scenes/SavedSearchAlertsList/Components/SavedSearchesList.tsx
Labels: Jira Synced, Squash On Green

#6015 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6020 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#5990 feat(FX-3675): update analytics tracking for saved search
  src/lib/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
  src/lib/Components/Artist/ArtistArtworks/SavedSearchButtonV2.tests.tsx
  src/lib/Components/Artist/ArtistArtworks/SavedSearchButtonV2.tsx
  src/lib/Components/ArtworkFilter/ArtworkFilterNavigator.tsx
Labels: Jira Synced

#6014 feat(search): reverse image search
  src/lib/Scenes/Search/components/ImageSearchModal.tsx
  src/lib/Scenes/Search/components/SearchInput.tsx
  src/lib/store/config/features.ts
  src/lib/utils/useImageSearch.tsx
  src/palette/elements/Input/Input.tsx
  src/palette/svgs/CameraIcon.tsx
  src/palette/svgs/index.tsx
Labels: hackathon

#6030 fix: change master to main
  scripts/update-metaphysics.js
Labels: Squash On Green

#6025 fix: Set rarity when editing artworks in My Collection
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/Components/Rarity.tests.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormMain.tsx
  src/lib/Scenes/MyCollection/State/MyCollectionArtworkModel.tsx
  src/lib/utils/artworkRarityClassifications.tests.ts
  src/lib/utils/artworkRarityClassifications.ts
Labels: Jira Synced, Squash On Green

#6031 feat: use both artworkHref/href
  src/lib/utils/useImageSearch.tsx
Labels: Squash On Green, hackathon

#6010 chore(FX-3677): update the filter counting logic for name input
  src/lib/Scenes/SavedSearchAlert/SavedSearchAlertForm.tests.tsx
  src/lib/Scenes/SavedSearchAlert/helpers.tests.ts
  src/lib/Scenes/SavedSearchAlert/helpers.ts
Labels: Jira Synced

#6037 chore: Remove AREnableNewWorksForYou feature flag
  src/lib/Scenes/Home/Home.tsx
  src/lib/store/config/features.ts
Labels: Jira Synced, Squash On Green

#5934 refactor(FX-3669): saved search alert logic
  src/lib/Components/Artist/ArtistArtworks/CreateSavedSearchModal.tsx
  src/lib/Components/Artist/ArtistArtworks/SavedSearchButton.tsx
  src/lib/Components/ArtworkFilter/SavedSearch/constants.ts
  src/lib/Components/ArtworkFilter/SavedSearch/convertersToFilterParams.ts
  src/lib/Components/ArtworkFilter/SavedSearch/searchCriteriaHelpers.tests.ts
  src/lib/Components/ArtworkFilter/SavedSearch/searchCriteriaHelpers.ts
  src/lib/Components/ArtworkFilter/SavedSearch/types.ts
  src/lib/Scenes/SavedSearchAlert/Components/CreateSavedSearchContent.tests.tsx
  src/lib/Scenes/SavedSearchAlert/Components/Form.tsx
  src/lib/Scenes/SavedSearchAlert/EditSavedSearchAlert.tsx
  src/lib/Scenes/SavedSearchAlert/SavedSearchAlertForm.tests.tsx
  src/lib/Scenes/SavedSearchAlert/SavedSearchAlertForm.tsx
  src/lib/Scenes/SavedSearchAlert/SavedSearchAlertModel.ts
  src/lib/Scenes/SavedSearchAlert/SavedSearchStore.tsx
  src/lib/Scenes/SavedSearchAlert/containers/CreateSavedSearchContentContainerV2.tsx
  src/lib/Scenes/SavedSearchAlert/helpers.tests.ts
  src/lib/Scenes/SavedSearchAlert/helpers.ts
  src/lib/Scenes/SavedSearchAlert/pillExtractors.tests.ts
  src/lib/Scenes/SavedSearchAlert/pillExtractors.ts
  src/lib/Scenes/SavedSearchAlert/screens/CreateSavedSearchAlertScreen.tsx
Labels: Jira Synced, Squash On Green

#6036 chore: Remove AREnableMyCollectionOrderImport feature flag
  src/__generated__/MyCollectionPaginationQuery.graphql.ts
  src/__generated__/MyCollectionQuery.graphql.ts
  src/__generated__/MyCollectionTestsQuery.graphql.ts
  src/__generated__/MyCollection_me.graphql.ts
  src/lib/Scenes/MyCollection/MyCollection.tsx
  src/lib/store/config/features.ts
Labels: Jira Synced

#6042 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#5957 feat: Save currency user preference
  .secrets.baseline
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/Components/Dimensions.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormArtwork.tsx
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormMain.tsx
  src/lib/Scenes/Search/UserPreferencesModel.tsx
  src/lib/store/GlobalStoreModel.ts
  src/lib/store/migration.tests.ts
  src/lib/store/migration.ts
  src/setupJest.ts
Labels: Jira Synced

#6044 feat: support braze rich push notifications
  Artsy.xcodeproj/project.pbxproj
  BrazePushServiceExtension/Info.plist
  BrazePushServiceExtension/NotificationService.swift
Labels: Jira Synced

#6045 feat: Palette V3 artwork rail
  src/__generated__/ArtworkModuleRail_rail.graphql.ts
  src/__generated__/ArtworkRailCard_artwork.graphql.ts
  src/__generated__/HomeAboveTheFoldQuery.graphql.ts
  src/__generated__/HomeBelowTheFoldQuery.graphql.ts
  src/__generated__/HomeRefetchQuery.graphql.ts
  src/__generated__/Home_homePageAbove.graphql.ts
  src/__generated__/Home_homePageBelow.graphql.ts
  src/__generated__/LargeArtworkRail_artworks.graphql.ts
  src/__generated__/SmallArtworkRail_artworks.graphql.ts
  src/lib/Components/ArtworkRail/ArtworkRail.tsx
  src/lib/Components/ArtworkRail/ArtworkRailCard.tsx
  src/lib/Components/ArtworkRail/LargeArtworkRail.tsx
  src/lib/Components/ArtworkRail/SmallArtworkRail.tsx
  src/lib/Components/OpaqueImageView/OpaqueImageView.tsx
  src/lib/Scenes/Home/Components/ArtworkModuleRail.tsx
  src/lib/Scenes/Home/Home.tests.tsx
  src/lib/Scenes/Home/Home.tsx
  src/lib/Scenes/Home/homeAnalytics.tests.ts
  src/lib/Scenes/Home/homeAnalytics.ts
Labels: Jira Synced

#6048 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6019 feat: base for swa 85 86 133
  src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/ArtworkDetails.tests.tsx
  src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/ArtworkDetails.tsx
  src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkSubmitted.tsx
  src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/ContactInformation/ContactInformation.tests.tsx
  src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/ContactInformation/ContactInformation.tsx
  src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/SubmitArtworkOverview.tsx
  src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/UploadPhotos/UploadPhotos.tests.tsx
  src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/UploadPhotos/UploadPhotos.tsx
Labels: Jira Synced

#5953 feat: Introduce visual clue
  docs/add_a_visual_clue.md
  src/lib/Scenes/BottomTabs/BottomTabsButton.tsx
  src/lib/store/GlobalStore.tsx
  src/lib/store/GlobalStoreModel.ts
  src/lib/store/VisualClueModel.ts
  src/lib/store/config/visualClues.ts
  src/lib/store/migration.ts
  src/palette/elements/VisualClue/VisualClue.stories.tsx
  src/palette/elements/VisualClue/VisualClueDot.tsx
  src/palette/elements/VisualClue/VisualClueText.tsx
  src/palette/elements/VisualClue/index.tsx
  src/storybook/storyLoader.js
Labels: Jira Synced

#6052 chore: add collector profile feature flag
  src/lib/store/config/features.ts
Labels: Jira Synced

#6050 feat: Convert viewing rooms artwork rail to V3
  src/__generated__/ViewingRoomArtworkRailTestsQuery.graphql.ts
  src/__generated__/ViewingRoomArtworkRail_viewingRoom.graphql.ts
  src/__generated__/ViewingRoomQuery.graphql.ts
  src/__generated__/ViewingRoomTestsQuery.graphql.ts
  src/lib/Scenes/ViewingRoom/Components/ViewingRoomArtworkRail.tests.tsx
  src/lib/Scenes/ViewingRoom/Components/ViewingRoomArtworkRail.tsx
Labels: Jira Synced

#6054 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6058 Update metaphysics schema
  data/schema.graphql
  src/__generated__/ConfirmBidUpdateUserMutation.graphql.ts
  src/__generated__/RegistrationUpdateUserMutation.graphql.ts
  src/__generated__/updateEmailFrequencyMutation.graphql.ts
  src/__generated__/updateMyUserProfileMutation.graphql.ts
Labels: Squash On Green

#6017 feat: add share button on artist page
  src/__generated__/ArtistAboveTheFoldQuery.graphql.ts
  src/__generated__/ArtistHeaderFloatingButtons_artist.graphql.ts
  src/lib/AppRegistry.tsx
  src/lib/Components/Artist/ArtistHeaderButton.tsx
  src/lib/Components/Artist/ArtistHeaderFloatingButtons.tsx
  src/lib/Components/ShareSheet/ShareSheet.tests.tsx
  src/lib/Components/ShareSheet/ShareSheet.tsx
  src/lib/Components/ShareSheet/helpers.tests.ts
  src/lib/Components/ShareSheet/helpers.ts
  src/lib/Components/StickyTabPage/StickyTabPage.tsx
  src/lib/Components/Toast/ToastComponent.tsx
  src/lib/Scenes/Artist/Artist.tsx
  src/lib/Scenes/Artwork/Components/InstagramStoryViewShot.tsx
  src/lib/navigation/navigate.tests.tsx
Labels: hackathon

#5918 feat(FX-3634): Allow to update search criteria attributes from saved alerts screen
  src/lib/Scenes/SavedSearchAlert/Components/Form.tsx
  src/lib/Scenes/SavedSearchAlert/EditSavedSearchAlert.tests.tsx
  src/lib/Scenes/SavedSearchAlert/SavedSearchAlertForm.tests.tsx
  src/lib/Scenes/SavedSearchAlert/SavedSearchAlertForm.tsx
  src/lib/Scenes/SavedSearchAlert/mutations/updateSavedSearchAlert.ts
Labels: Jira Synced, Squash On Green

#6047 bring button stories back
  src/lib/Components/PopoverMessage/PopoverMessage.stories.tsx
  src/lib/utils/Wrap.tsx
  src/palette/elements/Button/Button.stories.tsx
  src/palette/elements/Input/Input.stories.tsx
  src/palette/elements/Text/Text.stories.tsx
  src/storybook/helpers.tsx
Labels: Jira Synced, Squash On Green

#6051 feat: Convert artist notable works rail to V3
  src/__generated__/ArtistAboutTestsQuery.graphql.ts
  src/__generated__/ArtistBelowTheFoldQuery.graphql.ts
  src/__generated__/ArtistNotableWorksRailTestsQuery.graphql.ts
  src/__generated__/ArtistNotableWorksRail_artist.graphql.ts
  src/lib/Components/Artist/ArtistArtworks/ArtistNotableWorksRail.tests.tsx
  src/lib/Components/Artist/ArtistArtworks/ArtistNotableWorksRail.tsx
  src/lib/Components/ArtworkRail/ArtworkRail.tsx
  src/lib/Components/ArtworkRail/ArtworkRailCard.tsx
Labels: Jira Synced

#6063 feat: Convert New Works For You rail to V3
  src/__generated__/HomeAboveTheFoldQuery.graphql.ts
  src/__generated__/HomeRefetchQuery.graphql.ts
  src/__generated__/NewWorksForYouRailQuery.graphql.ts
  src/__generated__/NewWorksForYouRail_me.graphql.ts
  src/lib/Scenes/Home/Components/NewWorksForYouRail.tsx
  src/lib/Scenes/Home/Home.tsx
Labels: Jira Synced

#6068 fix: rich push signing
  Gemfile.lock
  fastlane/Fastfile
Labels: Squash On Green

#6053 chore(CX-1947): Save user preferences follow-up
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/Components/Dimensions.tsx
  src/lib/Scenes/MyCollection/State/MyCollectionArtworkModel.tsx
  src/lib/Scenes/Search/UserPreferencesModel.tsx
Labels: Jira Synced

#6023 feat: support 2fa
  .secrets.baseline
  src/lib/Scenes/Onboarding/Onboarding.tsx
  src/lib/Scenes/Onboarding/OnboardingLogin.tests.tsx
  src/lib/Scenes/Onboarding/OnboardingLogin.tsx
  src/lib/Scenes/Onboarding/OnboardingLoginWithOTP.tests.tsx
  src/lib/Scenes/Onboarding/OnboardingLoginWithOTP.tsx
  src/lib/store/AuthModel.tests.ts
  src/lib/store/AuthModel.ts
Labels: Jira Synced, hackathon

#6059 Feat[CX-2183]: Displaying new Collector Profile info
  src/__generated__/MyCollectionAndSavedWorksQuery.graphql.ts
  src/__generated__/MyCollectionAndSavedWorksTestsQuery.graphql.ts
  src/__generated__/MyCollectionAndSavedWorks_me.graphql.ts
  src/lib/Scenes/MyProfile/MyCollectionAndSavedWorks.tests.tsx
  src/lib/Scenes/MyProfile/MyCollectionAndSavedWorks.tsx
  src/palette/svgs/BriefcaseIcon.tsx
  src/palette/svgs/PageIcon.tsx
Labels: Jira Synced

#6077 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6070 feat(FX-3699): Show a warning message on edit alert screen if a user has set email frequency to None
  src/__generated__/EditSavedSearchAlertQuery.graphql.ts
  src/__generated__/EditSavedSearchAlertRefetchQuery.graphql.ts
  src/__generated__/EditSavedSearchAlert_user.graphql.ts
  src/__generated__/SavedSearchAlertQuery.graphql.ts
  src/lib/Scenes/SavedSearchAlert/Components/Form.tsx
  src/lib/Scenes/SavedSearchAlert/EditSavedSearchAlert.tests.tsx
  src/lib/Scenes/SavedSearchAlert/EditSavedSearchAlert.tsx
  src/lib/Scenes/SavedSearchAlert/SavedSearchAlert.tsx
  src/lib/Scenes/SavedSearchAlert/SavedSearchAlertForm.tests.tsx
  src/lib/Scenes/SavedSearchAlert/SavedSearchAlertForm.tsx
  src/palette/Theme.tsx
Labels: Jira Synced

#6081 chore: Remove AREnableVisualProfileIconAndBio feature flag
  src/lib/Scenes/MyProfile/MyCollectionAndSavedWorks.tests.tsx
  src/lib/Scenes/MyProfile/MyCollectionAndSavedWorks.tsx
  src/lib/store/config/features.ts
Labels: Jira Synced, Squash On Green

#6083 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6084 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6085 feat: Update Artsy Address GRO-744
  src/lib/Scenes/SavedAddresses/SavedAddresses.tests.tsx
  src/lib/Scenes/SavedAddresses/SavedAddressesForm.tests.tsx
Labels: Merge On Green

#6062 feat: Convert fair exhibitor rail to V3
  src/__generated__/FairExhibitorRailTestsQuery.graphql.ts
  src/__generated__/FairExhibitorRail_show.graphql.ts
  src/__generated__/FairExhibitorsQuery.graphql.ts
  src/__generated__/FairExhibitorsTestsQuery.graphql.ts
  src/__generated__/FairQuery.graphql.ts
  src/__generated__/FairTestsQuery.graphql.ts
  src/__generated__/VanityURLEntityQuery.graphql.ts
  src/lib/Scenes/Fair/Components/FairExhibitorRail.tsx
  src/lib/Scenes/Fair/FairExhibitorRail.tests.tsx
Labels: Jira Synced

#6072 feat: pass go back props
  src/lib/Components/ArtsyReactWebView.tests.tsx
  src/lib/Components/ArtsyReactWebView.tsx
  src/lib/Scenes/ArtworkAttributionClassFAQ/ArtworkAttributionClassFAQ.tsx
  src/lib/Scenes/ArtworkMedium/ArtworkMedium.tsx
  src/lib/Scenes/MyAccount/Components/MyAccountFieldEditScreen.tsx
  src/lib/Scenes/SavedSearchAlert/Components/Form.tsx
  src/lib/Scenes/SavedSearchAlert/EditSavedSearchAlert.tsx
  src/lib/Scenes/SavedSearchAlert/SavedSearchAlertForm.tests.tsx
  src/lib/Scenes/SavedSearchAlertsList/Components/SavedSearchesList.tsx
  src/lib/navigation/BackButton.tsx
  src/lib/navigation/navigate.ts
Labels: Squash On Green

#6089 fix: fix how error message appears
  src/lib/Components/PhoneInput/PhoneInput.tsx
Labels: Squash On Green

#6092 Update metaphysics schema
  data/schema.graphql
  src/__generated__/ConfirmBidUpdateUserMutation.graphql.ts
  src/__generated__/RegistrationUpdateUserMutation.graphql.ts
  src/__generated__/updateEmailFrequencyMutation.graphql.ts
  src/__generated__/updateMyUserProfileMutation.graphql.ts
Labels: Squash On Green

#6098 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6082 chore: consolidate env for ci
  .circleci/config.yml
  .env.example
  scripts/build-for-tests-android
  scripts/build-for-tests-ios
  scripts/distribute-android
  scripts/distribute-ios
  scripts/download-assets
  scripts/generate-env.js
  scripts/setup-awscli
  scripts/setup-distribute
  scripts/setup-distribute-linux
  scripts/setup-distribute-macos
  scripts/setup-env-for-ci
Labels: Jira Synced

#6093 fix(FX-3705): Add small changes to the header for the "Sort & Filter" screen
  src/lib/Components/AnimatableHeader/AnimatableHeader.tsx
Labels: Jira Synced

#6088 Fix[CX-2265]: unable to save an artwork after adding image in My Collection
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/Form/artworkSchema.tsx
Labels: Jira Synced, Squash On Green

#6096 chore(CX-2266): clean up feature flag ARMyCollectionLocalSortAndFilter
  src/lib/Scenes/MyCollection/MyCollection.tsx
  src/lib/store/config/features.ts
Labels: Jira Synced

#6102 Chore[CX-2183]: collector profile new info update
  src/__generated__/MyCollectionAndSavedWorksQuery.graphql.ts
  src/__generated__/MyCollectionAndSavedWorksTestsQuery.graphql.ts
  src/__generated__/MyCollectionAndSavedWorks_me.graphql.ts
  src/lib/Scenes/MyProfile/MyCollectionAndSavedWorks.tests.tsx
  src/lib/Scenes/MyProfile/MyCollectionAndSavedWorks.tsx
Labels: Jira Synced, Squash On Green

#6101 feat: Convert fair followed artist rail to V3
  src/__generated__/FairFollowedArtistsRailTestsQuery.graphql.ts
  src/__generated__/FairFollowedArtistsRail_fair.graphql.ts
  src/__generated__/FairQuery.graphql.ts
  src/__generated__/FairTestsQuery.graphql.ts
  src/__generated__/VanityURLEntityQuery.graphql.ts
  src/lib/Scenes/Fair/Components/FairFollowedArtistsRail.tsx
  src/lib/Scenes/Fair/Fair.tests.tsx
  src/lib/Scenes/Fair/FairFollowedArtistsRail.tests.tsx
Labels: Jira Synced, Squash On Green

#6105 feat: Update section title right button text
  src/lib/Components/SectionTitle.tsx
  src/lib/Scenes/Home/SectionTitle.tests.tsx
Labels: Jira Synced

#6108 chore: prevent adding empty title for artworks in my collection
  scripts/setup-distribute
  src/lib/Scenes/MyCollection/Screens/ArtworkForm/Form/artworkSchema.tsx
Labels: Jira Synced

#6064 feat: Convert Artworks In Series rail to V3
  src/__generated__/ArtworkBelowTheFoldQuery.graphql.ts
  src/__generated__/ArtworkRefetchQuery.graphql.ts
  src/__generated__/ArtworksInSeriesRailTestsQuery.graphql.ts
  src/__generated__/ArtworksInSeriesRail_artwork.graphql.ts
  src/lib/Scenes/Artwork/Artwork.tsx
  src/lib/Scenes/Artwork/Components/ArtworksInSeriesRail.tests.tsx
  src/lib/Scenes/Artwork/Components/ArtworksInSeriesRail.tsx
Labels: Jira Synced

#6103 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6095 chore(CX-2267): Clean up feature flag AREnableAuctionResultComparableWorks
  src/lib/Components/ArtworkFilter/FilterModal.tests.tsx
  src/lib/Components/Countdown/Ticker.tests.tsx
  src/lib/Scenes/AuctionResult/AuctionResult.tests.tsx
  src/lib/Scenes/AuctionResult/AuctionResult.tsx
  src/lib/Scenes/Fair/Components/FairExhibitorRail.tsx
  src/lib/store/config/features.ts
  src/palette/elements/List/List.stories.tsx
Labels: Jira Synced

#6094 chore(CX-2268): clean up feature flags AREnableMyCollectionAndroid and AREnableMyCollectionIOS
  src/__generated__/MyProfileQuery.graphql.ts
  src/__generated__/MyProfileRefetchQuery.graphql.ts
  src/__generated__/MyProfile_me.graphql.ts
  src/lib/AppRegistry.tsx
  src/lib/Components/Artist/ArtistArtworks/CreateSavedSearchModal.tests.tsx
  src/lib/Components/Artist/ArtistArtworks/CreateSavedSearchModal.tsx
  src/lib/Components/Artist/ArtistArtworks/SavedSearchButton.tests.tsx
  src/lib/Components/Artist/ArtistArtworks/SavedSearchButton.tsx
  src/lib/Scenes/Favorites/FavoriteArtworks.tsx
  src/lib/Scenes/Favorites/Favorites.tsx
  src/lib/Scenes/MyCollection/MyCollection.tsx
  src/lib/Scenes/MyProfile/MyCollectionAndSavedWorks.tsx
  src/lib/Scenes/MyProfile/MyProfile.tests.tsx
  src/lib/Scenes/MyProfile/MyProfile.tsx
  src/lib/store/config/features.ts
Labels: Jira Synced

#6110 fix: Adjust ArtworkRail onPress type
  src/lib/Components/ArtworkRail/ArtworkRail.tsx
Labels: Squash On Green

#6111 chore(FX-3706): mark AREnableImprovedAlertsFlow to readyForRelease
  src/lib/Scenes/MyCollection/MyCollection.tsx
  src/lib/store/config/features.ts
Labels: Jira Synced, Squash On Green

#6043 [feat]: AlicanAkyuz/swa-85/consignment artwork 1st step
  images/powered_by_google.webp
  src/__generated__/ArtistAutosuggestResultsPaginationQuery.graphql.ts
  src/__generated__/ArtistAutosuggestResultsQuery.graphql.ts
  src/__generated__/ArtistAutosuggestResults_results.graphql.ts
  src/__generated__/createConsignSubmissionMutation.graphql.ts
  src/__generated__/updateConsignSubmissionMutation.graphql.ts
  src/lib/Scenes/Consignments/ConsignmentsHome/ConsignmentsHome.tsx
  src/lib/Scenes/Consignments/ConsignmentsHome/ConsignmentsSubmissionForm.tsx
  src/lib/Scenes/Consignments/Screens/Overview.tsx
  src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/ArtworkDetails.tests.tsx
  src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/ArtworkDetails.tsx
  src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/ArtworkDetailsForm.tests.tsx
  src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/ArtworkDetailsForm.tsx
  src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/Components/ArtistAutosuggest.tests.tsx
  src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/Components/ArtistAutosuggest.tsx
  src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/Components/ArtistAutosuggestResults.tsx
  src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/Components/ArtistAutosuggestRow.tests.tsx
  src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/Components/ArtistAutosuggestRow.tsx
  src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/Components/ErrorView.tests.tsx
  src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/Components/ErrorView.tsx
  src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/Components/InfoModal.tests.tsx
  src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/Components/InfoModal.tsx
  src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/Components/LocationAutocomplete.tests.tsx
  src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/Components/LocationAutocomplete.tsx
  src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/Mutations/createConsignSubmissionMutation.ts
  src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/Mutations/index.ts
  src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/Mutations/updateConsignSubmissionMutation.ts
  src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/State/SubmissionModel.tsx
  src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/utils/createOrUpdateSubmission.ts
  src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/utils/rarityOptions.ts
  src/lib/Scenes/Consignments/Screens/SubmitArtworkOverview/utils/validation.ts
  src/lib/store/GlobalStoreModel.ts
  src/lib/store/migration.tests.ts
  src/lib/store/migration.ts
  src/lib/utils/googleMaps.ts
  src/palette/elements/List/BulletedItem.tsx
Labels: Jira Synced

#6113 fix: crash for alerts flow on android
  src/lib/Scenes/SavedSearchAlert/EditSavedSearchAlert.tsx
  src/lib/Scenes/SavedSearchAlertsList/Components/SavedSearchesList.tsx
Labels: Squash On Green

#6112 feat(FX-3707): show a warning message for a duplicate alert
  src/__generated__/CreateSavedSearchContentContainerV2Query.graphql.ts
  src/__generated__/CreateSavedSearchContentContainerV2RefetchQuery.graphql.ts
  src/__generated__/CreateSavedSearchContentContainerV2_me.graphql.ts
  src/__generated__/getSavedSearchIdByCriteriaQuery.graphql.ts
  src/lib/Scenes/SavedSearchAlert/Components/CreateSavedSearchContent.tsx
  src/lib/Scenes/SavedSearchAlert/Components/Form.tsx
  src/lib/Scenes/SavedSearchAlert/CreateSavedSearchAlert.tests.tsx
  src/lib/Scenes/SavedSearchAlert/EditSavedSearchAlert.tests.tsx
  src/lib/Scenes/SavedSearchAlert/SavedSearchAlertForm.tests.tsx
  src/lib/Scenes/SavedSearchAlert/SavedSearchAlertForm.tsx
  src/lib/Scenes/SavedSearchAlert/SavedSearchAlertModel.ts
  src/lib/Scenes/SavedSearchAlert/containers/CreateSavedSearchContentContainerV2.tsx
  src/lib/Scenes/SavedSearchAlert/helpers.ts
  src/lib/Scenes/SavedSearchAlert/queries/getSavedSearchIdByCriteria.ts
Labels: Jira Synced, Squash On Green

#6117 fix: Broken back navigation
  src/lib/AppRegistry.tsx
Labels: Jira Synced

#6120 Update metaphysics schema
  data/schema.graphql
  src/__generated__/SavedSearchButtonQuery.graphql.ts
  src/__generated__/SavedSearchButtonRefetchQuery.graphql.ts
  src/__generated__/SavedSearchButtonTestsQuery.graphql.ts
  src/__generated__/createSavedSearchAlertMutation.graphql.ts
  src/__generated__/getSavedSearchIdByCriteriaQuery.graphql.ts
  src/__generated__/updateSavedSearchAlertMutation.graphql.ts
Labels: Squash On Green

#6114 feat: Convert Buy now artwork rail in series rail to V3
  src/__generated__/BuyNowArtworksRailQuery.graphql.ts
  src/__generated__/BuyNowArtworksRailTestsQuery.graphql.ts
  src/__generated__/BuyNowArtworksRail_sale.graphql.ts
  src/__generated__/SaleAboveTheFoldQuery.graphql.ts
  src/__generated__/SaleRefetchQuery.graphql.ts
  src/lib/Scenes/Sale/BuyNowArtworksRail.tests.tsx
  src/lib/Scenes/Sale/Components/BuyNowArtworksRail.tsx
Labels: Jira Synced

#6121 Update metaphysics schema
  yarn.lock
Labels: Squash On Green

#6126 chore: Remove old inbox and AROptionsBidManagement feature flag
  src/__generated__/InboxOldQuery.graphql.ts
  src/__generated__/InboxOldRefetchQuery.graphql.ts
  src/__generated__/InboxOld_me.graphql.ts
  src/lib/AppRegistry.tsx
  src/lib/Components/ArtworkGrids/InfiniteScrollArtworksList.tsx
  src/lib/Containers/Inbox.tests.tsx
  src/lib/Containers/Inbox.tsx
  src/lib/Containers/Inbox/InboxOld.tsx
  src/lib/Containers/Inbox/index.tsx
  src/lib/Containers/InboxOld.tests.tsx
  src/lib/Containers/InboxWrapper.tests.tsx
  src/lib/Scenes/Inbox/Components/Conversations/Conversations.tsx
  src/lib/store/config/features.ts
Labels: Jira Synced, Squash On Green
