Repository artsy/eigen, pull requests merged in 2022-03, with the labels that each got.

#6334 feat: update copy in artwork details step
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/ArtworkDetails.tests.tsx
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/ArtworkDetails.tsx
Labels: Jira Synced

#6348 fix: use weak self in city guide, fix memory leak
  Artsy/App/ARAppDelegate+Emission.m
  Artsy/View_Controllers/Util/ARNavigationController.m
  HACKS.md
  emission/Pod/Classes/ViewControllers/ARMapContainerViewController.m
  src/app/AppRegistry.tsx
Labels: Jira Synced

#6351 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6350 feat[swa 252]underline "what is this?" text
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/ArtworkDetailsForm.tests.tsx
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/ArtworkDetailsForm.tsx
  src/palette/elements/Button/Button.stories.tsx
  src/palette/elements/Button/LinkButton.tsx
  src/palette/elements/Button/index.tsx
  src/palette/elements/Select/Select.tsx
  src/palette/elements/Text/Text.stories.tsx
  src/palette/elements/Text/Text.tsx
Labels: Jira Synced

#6317 feat(colors): support new color filtering options
  src/app/Components/ArtworkFilter/Filters/ColorsOptions.tests.tsx
  src/app/Components/ArtworkFilter/Filters/ColorsOptions.tsx
  src/app/Components/ArtworkFilter/Filters/ColorsSwatch.tests.tsx
  src/app/Components/ArtworkFilter/SavedSearch/convertersToFilterParams.tests.ts
  src/app/Scenes/SavedSearchAlert/pillExtractors.tests.ts
Labels: Jira Synced

#6362 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6347 refactor: commercial buttons
  src/app/Scenes/Artwork/Components/CommercialButtons/CommercialButtons.tests.tsx
  src/app/Scenes/Artwork/Components/CommercialButtons/CommercialButtons.tsx
Labels: Jira Synced

#6363 feat [SWA-276] update user email error
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ContactInformation/ContactInformation.tsx
Labels: Jira Synced

#6366 [Enhancement]: add HEIC to supported files list
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/UploadPhotos/UploadPhotosForm.tests.tsx
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/UploadPhotos/UploadPhotosForm.tsx
Labels: Jira Synced

#6369 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6370 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6364 [fix]: swa 277/numeric keyboard for inputs in submission flow
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/ArtworkDetails.tests.tsx
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/ArtworkDetailsForm.tsx
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ContactInformation/ContactInformation.tsx
Labels: Jira Synced

#6379 bug[swa-278] location autofill result needs two clicks & styling
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/Components/LocationAutocomplete.tsx
Labels: Jira Synced

#6381 feat(FX-3737): clean up feature flag AREnableImprovedAlertsFlow
  src/app/Components/AnimatableHeader/AnimatableHeader.tests.tsx
  src/app/Components/AnimatableHeader/AnimatableHeader.tsx
  src/app/Components/AnimatableHeader/AnimatableHeaderLargeTitle.tsx
  src/app/Components/AnimatableHeader/AnimatableHeaderShadow.tsx
  src/app/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
  src/app/Components/Artist/ArtistArtworks/CreateSavedSearchModal.tests.tsx
  src/app/Components/Artist/ArtistArtworks/SavedSearchButton.tests.tsx
  src/app/Components/Artist/ArtistArtworks/SavedSearchButton.tsx
  src/app/Components/ArtworkFilter/ArtworkFilterNavigator.tsx
  src/app/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx
  src/app/Components/ArtworkFilter/Filters/ArtistNationalitiesOptions.tests.tsx
  src/app/Components/ArtworkFilter/Filters/ColorsOptions.tsx
  src/app/Components/ArtworkFilter/Filters/MultiSelectCheckOption.tsx
  src/app/Components/ArtworkFilter/Filters/MultiSelectOption.tsx
  src/app/Components/ArtworkFilter/Filters/SingleSelectOption.tsx
  src/app/Components/ArtworkFilter/Filters/YearOptions.tsx
  src/app/Components/ArtworkFilter/components/ArtworkFilterApplyButton.tsx
  src/app/Components/ArtworkFilter/components/ArtworkFilterOptionCheckboxItem.tests.tsx
  src/app/Components/ArtworkFilter/components/ArtworkFilterOptionCheckboxItem.tsx
  src/app/Components/ArtworkFilter/components/ArtworkFilterOptionItem.tests.tsx
  src/app/Components/ArtworkFilter/components/ArtworkFilterOptionItem.tsx
  src/app/Components/ArtworkFilter/components/ArtworkFilterOptionsHeader.tsx
  src/app/Scenes/SavedSearchAlert/Components/CreateSavedSearchContent.tests.tsx
  src/app/Scenes/SavedSearchAlert/Components/CreateSavedSearchContent.tsx
  src/app/Scenes/SavedSearchAlert/Components/Form.tsx
  src/app/Scenes/SavedSearchAlert/CreateSavedSearchAlert.tests.tsx
  src/app/Scenes/SavedSearchAlert/EditSavedSearchAlert.tests.tsx
  src/app/Scenes/SavedSearchAlert/EditSavedSearchAlert.tsx
  src/app/Scenes/SavedSearchAlert/SavedSearchAlertForm.tests.tsx
  src/app/Scenes/SavedSearchAlert/SavedSearchAlertForm.tsx
  src/app/Scenes/SavedSearchAlert/SavedSearchAlertModel.ts
  src/app/Scenes/SavedSearchAlert/containers/CreateSavedSearchContentContainer.tsx
  src/app/Scenes/SavedSearchAlert/containers/CreateSavedSearchContentContainerV1.tsx
  src/app/Scenes/SavedSearchAlert/helpers.tests.ts
  src/app/Scenes/SavedSearchAlert/mutations/updateSavedSearchAlert.ts
  src/app/Scenes/SavedSearchAlert/screens/CreateSavedSearchAlertScreen.tsx
Labels: Jira Synced

#6378 fix: enable save & continue button after photo deletion
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/UploadPhotos/UploadPhotosForm.tsx
Labels: Jira Synced

#6375 feat: Add trending icon to My Collection artwork detail screen
  src/app/Icons/HighDemandIcon.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkDemandIndex.tsx
Labels: Jira Synced

#6380 fix: preserve artwork details in the flow
  src/app/Scenes/Consignments/ConsignmentsHome/ConsignmentsHome.tsx
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkSubmitted.tsx
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/State/SubmissionModel.tsx
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/UploadPhotos/UploadPhotosForm.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionImageView.tsx
  src/app/store/migration.ts
Labels: Jira Synced, Squash On Green

#6367 fix(city guide): selector staying visible
  src/app/Scenes/Map/GlobalMap.tsx
Labels: Jira Synced

#6387 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6326 chore: Remove AROptionsNewSalePage feature flag
  src/app/AppRegistry.tsx
  src/app/navigation/routes.tests.tsx
  src/app/navigation/routes.tsx
Labels: Jira Synced

#6377 chore: hide loggers using metaflags
  docs/README.md
  docs/adding_new_keys.md
  docs/metaflags.md
  metaflags.example.json
  metaphysics-queries-freshness-tests/test-freshness.ts
  scripts/setup-env-for-ci
  src/app/relay/middlewares/metaphysicsMiddleware.ts
  src/app/relay/middlewares/rateLimitMiddleware.ts
  src/app/relay/middlewares/simpleLoggerMiddleware.ts
  src/app/store/GlobalStore.tsx
  src/app/utils/PushNotification.ts
  src/app/utils/loggers.ts
  src/app/utils/queryPrefetching.ts
  src/app/utils/track/ConsoleTrackingProvider.ts
  src/app/utils/volleyClient.ts
Labels: Squash On Green

#6374 feat: Update currency and metrics
  src/app/Scenes/MyAccount/updateMyUserProfile.ts
  src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx
  src/app/Scenes/Search/UserPrefsModel.tsx
  src/app/store/AuthModel.ts
  src/app/store/migration.tests.ts
  src/app/store/migration.ts
Labels: Jira Synced

#6391 feat: Stick Save/Complete button on My collection artwork form
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormMain.tsx
Labels: Jira Synced

#6384 fix: swa289/92/93 - Contact Information step validations
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ContactInformation/ContactInformation.tests.tsx
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ContactInformation/ContactInformation.tsx
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ContactInformation/validation.ts
  src/palette/elements/Input/PhoneInput/PhoneInput.tests.tsx
  src/palette/elements/Input/PhoneInput/PhoneInput.tsx
Labels: Jira Synced

#6394 Fix[SWA-294]:reposition onPress
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/ArtworkDetailsForm.tests.tsx
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/ArtworkDetailsForm.tsx
Labels: Jira Synced, Squash On Green

#6396 fix: Button behind keyboard
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormMain.tsx
Labels: Squash On Green

#6403 fix: Limit shows per gallery for Shows for You rail
  src/app/Scenes/Home/Components/ShowsRail.tsx
  src/app/Scenes/Home/Home.tsx
Labels: Squash On Green

#6406 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6408 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6393 fix: conversation messages and event order
  src/app/Scenes/Inbox/Components/Conversations/ConversationCTA.tsx
  src/app/Scenes/Inbox/Components/Conversations/MessageGroup.tsx
  src/app/Scenes/Inbox/Components/Conversations/Messages.tests.tsx
  src/app/Scenes/Inbox/Components/Conversations/Messages.tsx
  src/app/Scenes/Inbox/Components/Conversations/utils/groupConversationItems.ts
Labels: Jira Synced

#6410 fix: Update artwork form skip button copy
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtworkAutosuggestResults.tsx
Labels: Jira Synced

#6412 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6413 feat(SWA-234): add submission source for the app.
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/Mutations/createConsignSubmissionMutation.ts
Labels: Jira Synced, Squash On Green

#6414 feat: wrap my collection mentions with feature flag in submitted screen
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkSubmitted.tsx
Labels: Jira Synced, Squash On Green

#6411 fix(CX-2138): login and signup screen, bottom buttons dont obey SafeArea
  .secrets.baseline
  src/app/Scenes/Onboarding/ForgotPassword.tsx
  src/app/Scenes/Onboarding/Onboarding.tsx
  src/app/Scenes/Onboarding/OnboardingCreateAccount/OnboardingCreateAccount.tsx
  src/app/Scenes/Onboarding/OnboardingLogin.tsx
  src/app/Scenes/Onboarding/OnboardingLoginWithOTP.tsx
Labels: Jira Synced

#6417 feat: fraud prevention messages in Conversations
  src/app/Components/Toast/ToastComponent.tsx
  src/app/Components/Toast/types.ts
  src/app/Scenes/Inbox/Components/Conversations/MessageGroup.tsx
  src/app/Scenes/Inbox/Components/Conversations/Messages.tests.tsx
  src/app/Scenes/Inbox/Components/Conversations/Messages.tsx
  src/app/Scenes/Inbox/Components/Conversations/OpenInquiryModalButton.tests.tsx
  src/app/Scenes/Inbox/Components/Conversations/OpenInquiryModalButton.tsx
  src/palette/svgs/ShieldIcon.tsx
  src/palette/svgs/index.tsx
Labels: Jira Synced

#6422 feat(CX-2362): Visual Update of Demand Index section
  src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkDemandIndex.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtworkInsights.tests.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtworkInsights.tsx
Labels: Jira Synced

#6429 feat: Make medium required in artwork form
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/MediumPicker.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Form/artworkSchema.tsx
Labels: Jira Synced

#6419 Chore: Remove NewFirstInquiry feature flag
  scripts/check-flags/check-flags.tests.ts
  src/app/Scenes/Artwork/Components/CommercialButtons/CommercialButtons.tests.tsx
  src/app/Scenes/Artwork/Components/CommercialButtons/CommercialButtons.tsx
  src/app/store/config/features.ts
Labels: Jira Synced

#6432 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6398 feat(CX-2354): Add sell with Artsy banner | Eigen
  .secrets.baseline
  src/app/AppRegistry.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/OldMyCollectionArtworkArtistAuctionResults.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/OldMyCollectionArtworkInsights.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/RequestForPriceEstimate.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionArtworkSubmissionStatus.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionWhySell.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/OldWhySell.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtworkAbout.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtworkInsights.tests.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtworkInsights.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionSellingWithartsyFAQ.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/OldMyCollectionArtwork.tests.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/OldMyCollectionArtwork.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tests.tsx
  src/app/navigation/routes.tsx
Labels: Jira Synced

#6433 fix: use isSold instead of inProgress for My Collection artworks
  src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionWhySell.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/OldMyCollectionArtwork.tsx
Labels: Jira Synced, Squash On Green

#6402 feat: Add skip ahead link
  package.json
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtworkAutosuggest.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtworkAutosuggestResults.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormArtwork.tsx
  yarn.lock
Labels: Jira Synced, Squash On Green

#6436 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6438 chore(CX-2441): add tests to MyCollectionWhySell component
  src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionWhySell.tests.tsx
Labels: Jira Synced

#6439 feat: Put price estimate range behind feature flag
  src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkAbout/MyCollectionArtworkAboutWork.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtworkAbout.tests.tsx
  src/app/store/config/features.ts
Labels: Jira Synced, Squash On Green

#6431 create a ProgressBar
  src/palette/elements/ProgressBar/ProgressBar.stories.tsx
  src/palette/elements/ProgressBar/ProgressBar.tsx
  src/palette/elements/ProgressBar/index.ts
  src/palette/elements/index.tsx
  src/storybook/storyLoader.js
Labels: Jira Synced, Squash On Green

#6345 feat(CX-2293): explanatory Banner Appears in My Collection after Artwork Submission
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ContactInformation/ContactInformation.tsx
  src/app/Scenes/MyCollection/MyCollection.tsx
  src/app/store/GlobalStore.tsx
  src/app/store/VisualClueModel.ts
  src/app/store/config/visualClues.ts
Labels: Jira Synced

#6452 fix: remove changelog validation
  dangerRules/validateChangelogYMLFile.tests.ts
  dangerfile.ts
Labels: Squash On Green

#6451 Disable edit artwork coming from SWA
  src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tests.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/OldMyCollectionArtwork.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkFullDetails/MyCollectionArtworkFullDetails.tests.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkFullDetails/MyCollectionArtworkFullDetails.tsx
Labels: Jira Synced

#6455 fix: point to fixed version of scrollable tab library
  HACKS.md
  package.json
  yarn.lock
Labels: Squash On Green

#6456 fix: remove rimraf storybook
  scripts/setup-env-for-artsy
  scripts/setup-env-for-oss
Labels: Squash On Green

#6442 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6460 fix(CX-2448): fix skip ahead link
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtworkAutosuggest.tsx
Labels: Jira Synced, Squash On Green

#6418 feat: Populate submission form when submitting an artwork from My Collection
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/ArtworkDetailsForm.tsx
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/utils/createOrUpdateSubmission.ts
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/utils/testUtils.ts
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/validation.ts
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/State/SubmissionModel.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionWhySell.tests.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionWhySell.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/Rarity.tsx
  src/app/Scenes/MyCollection/utils/initializeSubmissionArtworkForm.ts
  src/app/store/migration.tests.ts
  src/app/store/migration.ts
  src/app/utils/artworkRarityClassifications.ts
Labels: Jira Synced, Squash On Green

#6461 fix: virtualization issues inside my collection
  Podfile.lock
  src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/OldMyCollectionArtworkArtistAuctionResults.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormArtist.tsx
Labels: Jira Synced, Squash On Green

#6462 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6397 docs: docs on how to generate a release build for local testing
  .secrets.baseline
  Artsy.xcodeproj/xcshareddata/xcschemes/Artsy (Release build).xcscheme
  docs/README.md
  docs/generate_a_release_build_for_local_testing.md
Labels: Squash On Green

#6464 feat: Update price estimate CTA copy
  src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/RequestForPriceEstimate.tsx
Labels: Jira Synced

#6465 feat(NX-3091): Make Price on Request sentence case
  src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
  src/app/Scenes/Artwork/Components/CommercialInformation.tsx
  src/app/Scenes/Inbox/Components/Conversations/EditionSelectBox.tsx
  src/app/Scenes/Inbox/Components/Conversations/ItemArtwork.tests.tsx
  src/app/Scenes/Inbox/Components/Conversations/ItemArtwork.tsx
Labels: Jira Synced

#6459 [WIP] feat: SWA-267 photo row placeholder
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/State/SubmissionModel.tsx
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/UploadPhotos/PhotoRow.tsx
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/UploadPhotos/UploadPhotos.tsx
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/UploadPhotos/UploadPhotosForm.tsx
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/UploadPhotos/utils/addPhotoToConsignment.ts
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/UploadPhotos/utils/calculatePhotoSize.ts
  src/palette/elements/PhotoRow/PhotoRow.tests.tsx
  src/palette/elements/PhotoRow/PhotoRow.tsx
Labels: Jira Synced

#6449 feat(react 17): LETS GO
  babel.config.js
  docs/adding_new_components.md
  metro.config.js
  package.json
  src/app/Components/ArticleCard.tests.tsx
  src/app/Components/ArticleCard.tsx
  src/app/Components/Artist/ArtistHeader.tsx
  src/app/Scenes/Artwork/Components/RequestConditionReport.tsx
  src/app/Scenes/Home/Home.tsx
  src/app/Scenes/Search/Search.tests.tsx
  src/app/Scenes/Search/Search.tsx
  src/palette/elements/Button/Button.stories.tsx
  src/palette/elements/Button/Button.tests.tsx
  src/palette/elements/Button/Button.tsx
  yarn.lock
Labels: Squash On Green

#6473 chore: remove scrollview from price filter
  src/app/Components/ArtworkFilter/Filters/PriceRangeOptions.tsx
Labels: Jira Synced

#6478 feat: Set import source when creating My Collection artworks + refactoring
  .secrets.baseline
  src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tests.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormArtist.tsx
  src/app/Scenes/MyCollection/mutations/myCollectionCreateArtwork.ts
  src/app/Scenes/MyCollection/mutations/myCollectionUpdateArtwork.ts
  src/app/Scenes/MyCollection/utils/randomMyCollectionArtwork.ts
  src/app/utils/artworkRarityClassifications.ts
Labels: Jira Synced, Squash On Green

#6481 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6480 feat(cx-2439): Restrict showing request price estimate banner for D-Index less than nine
  src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtworkInsights.tests.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtworkInsights.tsx
Labels: Jira Synced

#6484 feat(CX-2457): added correct events to the SWA banner on MC Artwork page
  package.json
  src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionWhySell.tests.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionWhySell.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtworkAbout.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtworkInsights.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/OldMyCollectionArtwork.tsx
  yarn.lock
Labels: Jira Synced, Squash On Green

#6483 chore: Remove SplitIO QueryPrefetching experiment
  src/app/utils/experiments.ts
  src/app/utils/queryPrefetching.ts
Labels: Squash On Green

#6463 feat: Initialize images when submitting My Collection artworks
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/State/SubmissionModel.tsx
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/UploadPhotos/UploadPhotosForm.tsx
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/UploadPhotos/utils/calculatePhotoSize.tests.ts
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/UploadPhotos/utils/calculatePhotoSize.ts
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/UploadPhotos/validation.ts
  src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionWhySell.tsx
  src/app/Scenes/MyCollection/utils/initializeSubmissionArtworkForm.ts
  src/app/store/migration.tests.ts
  src/app/store/migration.ts
  src/palette/elements/PhotoRow/PhotoRow.tsx
Labels: Jira Synced

#6392 Update best_practices.md
  docs/best_practices.md
Labels: Jira Synced

#6468 refactor(FX-3750): Improved search pills
  src/app/Scenes/Search/RefetchWhenApiKeyExpired.tsx
  src/app/Scenes/Search/Search.tests.tsx
  src/app/Scenes/Search/Search.tsx
  src/app/Scenes/Search/components/SearchInput.tsx
  src/app/store/config/features.ts
  src/app/utils/useAlgoliaIndices.ts
  src/palette/elements/Pill/Pill.tsx
Labels: Jira Synced

#6489 fix: location auto complete dropdown logic
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/Components/LocationAutocomplete.tests.tsx
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/Components/LocationAutocomplete.tsx
Labels: Jira Synced

#6491 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6485 feat(FX-3760): price histogram on artist artwork page
  src/app/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
  src/app/Components/ArtworkFilter/ArtworkFilterHelpers.ts
  src/app/Components/ArtworkFilter/Filters/PriceRangeOptions.tsx
  src/palette/elements/Histogram/Histogram.stories.tsx
  src/palette/elements/Histogram/Histogram.tsx
  src/palette/elements/Histogram/index.tsx
  src/palette/elements/index.tsx
  src/storybook/storyLoader.js
Labels: Jira Synced

#6494 chore: patch React Native find-node.sh
  patches/react-native+0.66.4.patch
Labels: Squash On Green

#6476 feat: react 17 FC types
  docs/adding_new_components.md
  src/app/AppProviders.tsx
  src/app/Components/ArticleCard.tsx
  src/app/Components/Artist/ArtistHeader.tsx
  src/app/Components/ArtsyKeyboardAvoidingView.tsx
  src/app/Components/ArtworkFilter/components/ArtworkFilterApplyButton.tsx
  src/app/Components/RetryErrorBoundary.tsx
  src/app/Scenes/Artwork/Components/RequestConditionReport.tsx
  src/app/Scenes/Home/Components/EmailConfirmationBanner.tsx
  src/app/Scenes/Home/Home.tsx
  src/app/Scenes/OrderHistory/OrderDetails/Components/OrderDetails.tsx
  src/app/Scenes/OrderHistory/OrderDetails/Components/TrackOrderSection.tsx
  src/app/Scenes/Search/Search.tsx
  src/app/Scenes/ViewingRoom/ViewingRoomsList.tsx
  src/app/utils/Wrap.tsx
  src/app/utils/combineProviders.tests.tsx
  src/app/utils/combineProviders.tsx
  src/app/utils/experiments/UnleashProvider.tsx
  src/palette/elements/Button/Button.tsx
  src/palette/elements/Pill/Pill.tsx
  src/palette/elements/Text/Text.tsx
  src/palette/svgs/DecreaseIcon.tsx
  src/palette/svgs/IncreaseIcon.tsx
  src/storybook/decorators.tsx
Labels: Squash On Green

#6493 fix(CX-2460): Fix Show Only Submitted Artwork Filter Bug
  src/app/Scenes/MyCollection/MyCollectionArtworks.tsx
Labels: Jira Synced

#6488 fix(CX-2433): Fix Newly added MyCollection Artwork's artist not showing in Filters
  src/app/Scenes/MyCollection/MyCollection.tsx
  src/app/Scenes/MyCollection/utils/localArtworkSortAndFilter.ts
Labels: Jira Synced

#6499 fix: text underlines
  src/palette/elements/Text/Text.tsx
Labels: Squash On Green

#6500 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6503 fix: artwork dimensions not updated after mutation
  .secrets.baseline
  src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tests.tsx
Labels: Jira Synced

#6505 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6487 feat(SWA-267) Animated Progress Bar
  .secrets.baseline
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/UploadPhotos/UploadPhotos.tests.tsx
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/UploadPhotos/UploadPhotosForm.tsx
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/UploadPhotos/utils/addPhotoToConsignment.ts
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/UploadPhotos/utils/calculatePhotoSize.tests.ts
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/UploadPhotos/validation.ts
  src/app/Scenes/Consignments/Submission/uploadFileToS3.ts
  src/app/Scenes/Consignments/Submission/uploadPhotoToGemini.ts
  src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tests.tsx
  src/app/Scenes/MyCollection/utils/initializeSubmissionArtworkForm.ts
  src/app/utils/getConvertedImageUrlFromS3.tsx
  src/app/utils/useImageSearch.tsx
  src/palette/elements/PhotoRow/PhotoRow.tests.tsx
  src/palette/elements/PhotoRow/PhotoRow.tsx
Labels: Jira Synced, Squash On Green

#6506 fix: unleash working right on beta and release
  src/app/utils/experiments/UnleashProvider.tsx
Labels: Squash On Green

#6437 fix: sync native auth state more frequently for deeplinks
  src/app/AppRegistry.tsx
  src/app/store/AuthModel.ts
  src/app/utils/useSyncAuthState.ts
Labels: Jira Synced

#6509 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6511 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6515 chore: Remove old recommendations from home feed
  src/app/Scenes/Home/Home.tests.tsx
  src/app/Scenes/Home/Home.tsx
  src/app/utils/experiments.ts
Labels: Jira Synced, Squash On Green

#6510 fix: erase bug and virtualised list err
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/Components/ArtistAutosuggest.tsx
  src/app/Scenes/Consignments/Screens/SubmitArtworkOverview/ArtworkDetails/Components/ArtistAutosuggestResults.tsx
Labels: Jira Synced

#6513 feat: Artwork recommendations home screen rail
  package.json
  src/app/Scenes/Home/Components/ArtworkRecommendationsRail.tests.tsx
  src/app/Scenes/Home/Components/ArtworkRecommendationsRail.tsx
  src/app/Scenes/Home/Home.tsx
  src/app/store/config/features.ts
  yarn.lock
Labels: Jira Synced, Squash On Green

#6518 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6517 feat: Move Artist Recommendations home screen rail below Market News
  src/app/Scenes/Home/Home.tsx
Labels: Jira Synced

#6520 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6535 feat(hack10): city guide remake / explore page
  images/city-guide.webp
  src/app/Scenes/City/CityBMWSponsorship.tsx
  src/app/Scenes/Search/Search.tests.tsx
  src/app/Scenes/Search/Search.tsx
  src/app/Scenes/Search/components/CityGuideCTANew.tests.tsx
  src/app/Scenes/Search/components/CityGuideCTANew.tsx
  src/palette/elements/Message/Message.tsx
Labels: hackathon

#6540 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#6539 chore: add script to execute example algolia location-based queries
  package.json
  scripts/algolia-example-galleries-near-me.ts
  yarn.lock
Labels: hackathon
