Repository artsy/eigen, pull requests merged in 2022-08, with the labels that each got.

#7117 feat(GRO-1113): User sees app path for `Follow artists I’m interested in`
  src/app/Components/ArtistListItem.tsx
  src/app/Scenes/Onboarding/OnboardingPersonalization2/ArtistListItem.tsx
  src/app/Scenes/Onboarding/OnboardingPersonalization2/OnboardingFollowArtists.tsx
  src/app/Scenes/Onboarding/OnboardingPersonalization2/OnboardingFollows.tests.tsx
  src/app/Scenes/Onboarding/OnboardingPersonalization2/OnboardingFollows.tsx
  src/app/Scenes/Onboarding/OnboardingPersonalization2/OnboardingOrderedSet.tests.tsx
  src/app/Scenes/Onboarding/OnboardingPersonalization2/OnboardingOrderedSet.tsx
  src/app/Scenes/Onboarding/OnboardingPersonalization2/OnboardingPersonalization2.tsx
  src/app/Scenes/Onboarding/OnboardingPersonalization2/OnboardingSearchResults.tsx
  src/shared/hooks/useDebouncedValue.ts
Labels: Jira Synced

#7123 feat(GRO-1117): Add follow galleries I love screen
  src/app/Scenes/Onboarding/OnboardingPersonalization2/OnboardingFollowGalleries.tsx
  src/app/Scenes/Onboarding/OnboardingPersonalization2/OnboardingOrderedSet.tsx
  src/app/Scenes/Onboarding/OnboardingPersonalization2/OnboardingPersonalization2.tsx
  src/app/Scenes/Onboarding/OnboardingPersonalization2/OnboardingSearchResults.tsx
  src/app/Scenes/Onboarding/OnboardingPersonalization2/PartnerListItem.tsx
Labels: Jira Synced

#7130 feat: add onboarding loadingscreen
  src/app/Components/FullScreenLoadingImage.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/SavingArtworkModal.tsx
  src/app/Scenes/Onboarding/OnboardingPersonalization2/OnboardingPersonalization2.tsx
  src/app/Scenes/Onboarding/OnboardingPersonalization2/OnboardingPostFollowLoadingScreen.tsx
Labels: Squash On Green

#7136 fix: Add border to promotional card
  src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightCard.tsx
Labels: Jira Synced

#7120 feature(GRO-1109, GRO-1111, GRO-1112): add questionnaire to onboarding flow
  src/app/Scenes/Onboarding/OnboardingPersonalization2/Hooks/useOnboardingContext.tsx
  src/app/Scenes/Onboarding/OnboardingPersonalization2/OnboardingPersonalization2.tsx
  src/app/Scenes/Onboarding/OnboardingPersonalization2/OnboardingPersonalizationWelcome.tsx
  src/app/Scenes/Onboarding/OnboardingPersonalization2/Questions/OnboardingQuestionOne.tsx
  src/app/Scenes/Onboarding/OnboardingPersonalization2/Questions/OnboardingQuestionTemplate.tsx
  src/app/Scenes/Onboarding/OnboardingPersonalization2/Questions/OnboardingQuestionThree.tsx
  src/app/Scenes/Onboarding/OnboardingPersonalization2/Questions/OnboardingQuestionTwo.tsx
  src/app/Scenes/Onboarding/OnboardingPersonalization2/Questions/__tests__/OnboardingQuestionTemplate.tests.tsx
  src/app/Scenes/Onboarding/OnboardingPersonalization2/Questions/index.ts
  src/app/Scenes/Onboarding/OnboardingPersonalization2/config.ts
  src/app/Scenes/SavedSearchAlert/Components/Form.tsx
  src/app/Scenes/Search/components/AutosuggestSearchResult.tsx
  src/app/Scenes/Search/components/SearchPills.tsx
  src/palette/elements/Pill/Pill.tsx
  src/palette/organisms/screenStructure/Screen.tsx
Labels: Jira Synced, Squash On Green

#7113 feat(FX-4107): Replace `saleArtworksConnection` with `artworksConnection` for "Artworks Available to Buy Now" rail on the sale page
  src/app/Scenes/Sale/Components/NewBuyNowArtworksRail.tests.tsx
  src/app/Scenes/Sale/Components/NewBuyNowArtworksRail.tsx
  src/app/Scenes/Sale/Sale.tsx
Labels: Jira Synced, Squash On Green

#7141 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7139 chore: update copy per spec
  src/app/Scenes/Inbox/Components/Conversations/OrderUpdate.tests.tsx
  src/app/Scenes/Inbox/Components/Conversations/OrderUpdate.tsx
Labels: Jira Synced

#7140 fix: Artwork grid tablet layout
  src/app/Components/ArtworkGrids/GenericGrid.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkList/MyCollectionArtworkGridItem.tsx
Labels: Jira Synced

#7144 docs: test docs + start using `screen.` from rntl
  docs/best_practices.md
  src/app/Components/ArtworkFilter/Filters/CustomSizeInputs.tests.tsx
  src/app/Components/ArtworkFilter/Filters/SizesOptionsScreen.tests.tsx
  src/app/Scenes/Artist/ArtistSavedSearch.tests.tsx
  src/app/Scenes/Search/Search.tests.tsx
Labels: Squash On Green

#7142 feat(GRO-1180): Add nav bar and progress bar to follows onboarding screen
  src/app/Scenes/Onboarding/OnboardingPersonalization2/OnboardingFollows.tsx
  src/app/Scenes/Onboarding/OnboardingPersonalization2/OnboardingOrderedSet.tsx
  src/app/Scenes/Onboarding/OnboardingPersonalization2/OnboardingSearchResults.tsx
Labels: Jira Synced

#7147 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7149 fix: Correct Sticky Tab Page offset when rotating the device
  src/app/Components/StickyTabPage/StickyTabPage.tsx
  src/app/Components/StickyTabPage/StickyTabPageContext.tsx
  src/app/Components/StickyTabPage/StickyTabPageTabBar.tsx
  src/app/Scenes/MyProfile/__tests__/MyProfileHeaderMyCollectionAndSavedWorks.tests.tsx
Labels: Jira Synced

#7138 feat(GRO-1114, GRO-1115, GRO-1116): add app path for gene
  src/app/Scenes/Onboarding/OnboardingPersonalization2/ArtworkScreen.tsx
  src/app/Scenes/Onboarding/OnboardingPersonalization2/Components/AnimatedTooltip.tsx
  src/app/Scenes/Onboarding/OnboardingPersonalization2/Components/ArtistListItem.tsx
  src/app/Scenes/Onboarding/OnboardingPersonalization2/Components/PartnerListItem.tsx
  src/app/Scenes/Onboarding/OnboardingPersonalization2/OnboardingArtistsOnTheRise.tsx
  src/app/Scenes/Onboarding/OnboardingPersonalization2/OnboardingCuratedArtworks.tsx
  src/app/Scenes/Onboarding/OnboardingPersonalization2/OnboardingGene.tests.tsx
  src/app/Scenes/Onboarding/OnboardingPersonalization2/OnboardingGene.tsx
  src/app/Scenes/Onboarding/OnboardingPersonalization2/OnboardingOrderedSet.tsx
  src/app/Scenes/Onboarding/OnboardingPersonalization2/OnboardingPersonalization2.tsx
  src/app/Scenes/Onboarding/OnboardingPersonalization2/OnboardingSearchResults.tsx
  src/app/Scenes/Onboarding/OnboardingPersonalization2/OnboardingTopAuctionLots.tsx
Labels: Jira Synced

#7153 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7164 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7165 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7157 feat(GRO-1182): minor fixes and screen navigation logic
  src/app/Scenes/Onboarding/OnboardingPersonalization2/Components/GeneHeader.tsx
  src/app/Scenes/Onboarding/OnboardingPersonalization2/Hooks/useNextOnboardingScreen.tsx
  src/app/Scenes/Onboarding/OnboardingPersonalization2/OnboardingFollows.tsx
  src/app/Scenes/Onboarding/OnboardingPersonalization2/OnboardingGene.tests.tsx
  src/app/Scenes/Onboarding/OnboardingPersonalization2/OnboardingGene.tsx
  src/app/Scenes/Onboarding/OnboardingPersonalization2/OnboardingPostFollowLoadingScreen.tsx
  src/app/Scenes/Onboarding/OnboardingPersonalization2/Questions/OnboardingQuestionTemplate.tsx
  src/app/Scenes/Onboarding/OnboardingPersonalization2/Questions/OnboardingQuestionThree.tsx
Labels: Jira Synced

#7169 feat(GRO-1183): animated removal of unselected answers
  src/app/Scenes/Onboarding/OnboardingPersonalization2/Components/AnimatedFadingPill.tsx
  src/app/Scenes/Onboarding/OnboardingPersonalization2/Questions/OnboardingQuestionTemplate.tsx
Labels: Jira Synced

#7172 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7173 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7125 feat(FX-4142): reverse image stage 2
  android/app/src/main/AndroidManifest.xml
  android/build.gradle
  ios/Podfile.lock
  package.json
  src/app/AppRegistry.tsx
  src/app/Components/SearchImageHeaderButton/SearchImageHeaderButton.tsx
  src/app/Scenes/Fair/Fair.tests.tsx
  src/app/Scenes/ReverseImage/Components/Background.tsx
  src/app/Scenes/ReverseImage/Components/CameraFramesContainer.tsx
  src/app/Scenes/ReverseImage/Components/FrameIndicator.tsx
  src/app/Scenes/ReverseImage/Components/FrameIndicators.tsx
  src/app/Scenes/ReverseImage/Components/HeaderContainer.tsx
  src/app/Scenes/ReverseImage/Components/HeaderTitle.tsx
  src/app/Scenes/ReverseImage/ReverseImage.tsx
  src/app/Scenes/ReverseImage/Screens/ArtworkNotFound/ReverseImageArtworkNotFoundScreen.tsx
  src/app/Scenes/ReverseImage/Screens/Camera/Components/CameraButtons.tsx
  src/app/Scenes/ReverseImage/Screens/Camera/Components/CameraErrorState.tsx
  src/app/Scenes/ReverseImage/Screens/Camera/Components/CameraGrantPermissions.tsx
  src/app/Scenes/ReverseImage/Screens/Camera/Components/CapturePhotoButton.tsx
  src/app/Scenes/ReverseImage/Screens/Camera/Components/FocusIndicator.tsx
  src/app/Scenes/ReverseImage/Screens/Camera/ReverseImageCamera.tsx
  src/app/Scenes/ReverseImage/Screens/MultipleResults/ReverseImageArtworksRail.tsx
  src/app/Scenes/ReverseImage/Screens/MultipleResults/ReverseImageMultipleResults.tsx
  src/app/Scenes/ReverseImage/Screens/Preview/ReverseImagePreview.tsx
  src/app/Scenes/ReverseImage/types.ts
  src/app/Scenes/Show/Show.tests.tsx
  src/app/navigation/routes.ts
  src/app/utils/useImageSearch.ts
  src/app/utils/useIsForeground.ts
  src/palette/atoms/BackButton/BackButton.tsx
  yarn.lock
Labels: Jira Synced

#7177 feat: Add AREnableMyCollectionInsightsMedianPrice feature flag
  src/app/store/config/features.ts
Labels: Jira Synced, Squash On Green

#7176 fix: change My Collection Insights Average Price copy to Median Price
  .secrets.baseline
  src/app/AppRegistry.tsx
  src/app/Scenes/MyCollection/Screens/Insights/MedianAuctionPriceListItem.tsx
  src/app/Scenes/MyCollection/Screens/Insights/MedianAuctionPriceRail.tsx
  src/app/Scenes/MyCollection/Screens/Insights/MedianSalePriceAtAuction.tests.tsx
  src/app/Scenes/MyCollection/Screens/Insights/MedianSalePriceAtAuction.tsx
  src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsights.tsx
  src/app/Scenes/MyCollection/Screens/Insights/SelectArtist.tests.tsx
  src/app/Scenes/MyCollection/Screens/Insights/SelectArtistModal.tsx
  src/app/navigation/routes.ts
Labels: Jira Synced

#7174 fix(CX-2724): Update copy for sale price in the last 3 years
  src/app/Scenes/MyCollection/Screens/Insights/MedianAuctionPriceRail.tsx
Labels: Jira Synced

#7178 feat(CX-2723): Update empty state image on the insights page
  images/my-collection-empty-state-median.webp
  images/my-collection-empty-state-median@2x.webp
  images/my-collection-empty-state-median@3x.webp
  src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsightsEmptyState.tsx
Labels: Jira Synced

#7186 feat(CX-2734): remove the new tag from the career highlights cards
  src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightCard.tsx
  src/app/store/GlobalStore.tsx
  src/app/store/GlobalStoreModel.ts
  src/app/store/MyCollectionCareerHighlightsModel.ts
  src/app/store/migration.ts
Labels: Jira Synced

#7099 feat: add onboarding animation (not connected yet)
  src/app/Components/ArtworkFilter/Filters/AdditionalGeneIDsOptions.tests.tsx
  src/app/Components/ArtworkFilter/Filters/WaysToBuyOptions.tests.tsx
  src/app/Scenes/Onboarding/OnboardingPersonalization/OnboardingAnimation.tsx
  src/app/utils/placeholders.tests.tsx
  tsconfig.json
Labels: Jira Synced, Squash On Green

#7148 feat(GRO-1184): implement onboarding backward navigation
  src/app/Scenes/Onboarding/OnboardingPersonalization2/Hooks/useOnboardingContext.tsx
  src/app/Scenes/Onboarding/OnboardingPersonalization2/Questions/OnboardingQuestionOne.tsx
  src/app/Scenes/Onboarding/OnboardingPersonalization2/Questions/OnboardingQuestionTemplate.tsx
  src/app/Scenes/Onboarding/OnboardingPersonalization2/Questions/OnboardingQuestionThree.tsx
  src/app/Scenes/Onboarding/OnboardingPersonalization2/Questions/OnboardingQuestionTwo.tsx
  src/app/Scenes/Onboarding/OnboardingPersonalization2/config.tests.ts
  src/app/Scenes/Onboarding/OnboardingPersonalization2/config.ts
  src/app/utils/WorkflowEngine/WorkflowEngine.tsx
Labels: Jira Synced

#7189 fix(NX-3251): attachment open inside conversation android
  src/app/Scenes/Inbox/Components/Conversations/Message.tsx
Labels: Jira Synced

#7192 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7193 feat: Fetch median instead of average for My Collection Insights
  src/app/Scenes/MyCollection/Screens/Insights/MedianAuctionPriceListItem.tsx
  src/app/Scenes/MyCollection/Screens/Insights/MedianAuctionPriceRail.tsx
Labels: Jira Synced

#7156 feat(CX-2645): add career highlight modal carousel (big cards)
  images/careerHighlightsPromotionalCardImage.webp
  images/careerHighlightsPromotionalCardImage@2x.webp
  images/careerHighlightsPromotionalCardImage@3x.webp
  src/app/AppRegistry.tsx
  src/app/Components/FancyModal/FancyModalHeader.tsx
  src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightBigCard.tsx
  src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightCard.tsx
  src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightsBigCardsSwiper.tests.tsx
  src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightsBigCardsSwiper.tsx
  src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightsPromotionalCard.tsx
  src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightsRail.tests.tsx
  src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightsRail.tsx
  src/app/navigation/routes.ts
Labels: Jira Synced, Squash On Green

#7194 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7195 feat: Show orders while processing approval
  src/app/Scenes/OrderHistory/OrderHistory.tsx
  src/app/Scenes/OrderHistory/OrderHistoryRow.tests.tsx
  src/app/utils/getOrderStatus.ts
Labels: Jira Synced

#7201 fix(CX2750): add top padding to career highlights full modal carousel
  src/app/AppRegistry.tsx
Labels: Jira Synced

#7203 fix(CX-2751): dismiss career highlights modal after adding a new artwork
  src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightsPromotionalCard.tsx
Labels: Jira Synced, Squash On Green

#7204 chore: hide median price screen under different ff
  src/app/Scenes/MyCollection/Screens/Insights/MedianAuctionPriceRail.tsx
  src/app/store/config/features.ts
Labels: Jira Synced, Squash On Green

#7206 fix(CX-2752): Refresh career highlights after adding an artist
  src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx
  src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightsBigCardsSwiper.tsx
Labels: Jira Synced, Squash On Green

#7208 fix(CX-2749): fix small promo card and grammar
  src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightCard.tsx
  src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightsBigCardsSwiper.tsx
  src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightsRail.tests.tsx
  src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightsRail.tsx
Labels: Squash On Green

#7209 fix(CX-2754): MyC / Insights / Saved empty states are not aligned [Android]
  src/app/Scenes/Favorites/FavoriteArtworks.tsx
  src/app/Scenes/MyCollection/MyCollection.tsx
  src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsights.tsx
Labels: Jira Synced

#7214 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7213 fix(NX-3269): conversations list all shown on the list
  src/app/Containers/Inbox.tsx
  src/app/Scenes/Inbox/Components/Conversations/Conversations.tsx
Labels: Jira Synced

#7211 feat(GRO-1187): onboarding analytics
  src/app/Scenes/Onboarding/Onboarding.tsx
  src/app/Scenes/Onboarding/OnboardingPersonalization2/Questions/index.ts
  src/app/Scenes/Onboarding/OnboardingV2/ArtworkScreen.tsx
  src/app/Scenes/Onboarding/OnboardingV2/Components/AnimatedFadingPill.tsx
  src/app/Scenes/Onboarding/OnboardingV2/Components/AnimatedTooltip.tsx
  src/app/Scenes/Onboarding/OnboardingV2/Components/ArtistListItem.tsx
  src/app/Scenes/Onboarding/OnboardingV2/Components/GeneHeader.tsx
  src/app/Scenes/Onboarding/OnboardingV2/Components/OnboardingQuestionTemplate.tsx
  src/app/Scenes/Onboarding/OnboardingV2/Components/PartnerListItem.tsx
  src/app/Scenes/Onboarding/OnboardingV2/Hooks/__mocks__/useOnboardingTracking.ts
  src/app/Scenes/Onboarding/OnboardingV2/Hooks/useNextOnboardingScreen.tsx
  src/app/Scenes/Onboarding/OnboardingV2/Hooks/useOnboardingContext.tsx
  src/app/Scenes/Onboarding/OnboardingV2/Hooks/useOnboardingTracking.ts
  src/app/Scenes/Onboarding/OnboardingV2/Hooks/useUpdateUserProfile.tsx
  src/app/Scenes/Onboarding/OnboardingV2/OnboardingArtistsOnTheRise.tsx
  src/app/Scenes/Onboarding/OnboardingV2/OnboardingCuratedArtworks.tsx
  src/app/Scenes/Onboarding/OnboardingV2/OnboardingFollowArtists.tsx
  src/app/Scenes/Onboarding/OnboardingV2/OnboardingFollowGalleries.tsx
  src/app/Scenes/Onboarding/OnboardingV2/OnboardingFollows.tsx
  src/app/Scenes/Onboarding/OnboardingV2/OnboardingGene.tsx
  src/app/Scenes/Onboarding/OnboardingV2/OnboardingOrderedSet.tsx
  src/app/Scenes/Onboarding/OnboardingV2/OnboardingPersonalizationWelcome.tsx
  src/app/Scenes/Onboarding/OnboardingV2/OnboardingPostFollowLoadingScreen.tsx
  src/app/Scenes/Onboarding/OnboardingV2/OnboardingQuestionOne.tsx
  src/app/Scenes/Onboarding/OnboardingV2/OnboardingQuestionThree.tsx
  src/app/Scenes/Onboarding/OnboardingV2/OnboardingQuestionTwo.tsx
  src/app/Scenes/Onboarding/OnboardingV2/OnboardingSearchResults.tsx
  src/app/Scenes/Onboarding/OnboardingV2/OnboardingTopAuctionLots.tsx
  src/app/Scenes/Onboarding/OnboardingV2/OnboardingV2.tsx
  src/app/Scenes/Onboarding/OnboardingV2/__tests__/OnboardingFollows.tests.tsx
  src/app/Scenes/Onboarding/OnboardingV2/__tests__/OnboardingGene.tests.tsx
  src/app/Scenes/Onboarding/OnboardingV2/__tests__/OnboardingOrderedSet.tests.tsx
  src/app/Scenes/Onboarding/OnboardingV2/__tests__/OnboardingPersonalizationWelcome.tests.tsx
  src/app/Scenes/Onboarding/OnboardingV2/__tests__/OnboardingQuestionTemplate.tests.tsx
  src/app/Scenes/Onboarding/OnboardingV2/__tests__/config.tests.ts
  src/app/Scenes/Onboarding/OnboardingV2/__tests__/useOnboardingTracking.tests.ts
  src/app/Scenes/Onboarding/OnboardingV2/config.ts
Labels: Jira Synced

#7218 chore(GRO-1220): update copy
  src/app/Scenes/Onboarding/OnboardingV2/Hooks/useNextOnboardingScreen.tsx
  src/app/Scenes/Onboarding/OnboardingV2/OnboardingQuestionOne.tsx
  src/app/Scenes/Onboarding/OnboardingV2/OnboardingQuestionThree.tsx
  src/app/Scenes/Onboarding/OnboardingV2/__tests__/config.tests.ts
  src/app/Scenes/Onboarding/OnboardingV2/config.ts
Labels: Jira Synced

#7219 bug(GRO-1227): fix tracking hook
  src/app/Scenes/Onboarding/OnboardingV2/Components/GeneHeader.tsx
  src/app/Scenes/Onboarding/OnboardingV2/Hooks/useOnboardingTracking.ts
  src/app/Scenes/Onboarding/OnboardingV2/OnboardingOrderedSet.tsx
  src/app/Scenes/Onboarding/OnboardingV2/OnboardingSearchResults.tsx
  src/app/Scenes/Onboarding/OnboardingV2/OnboardingV2.tsx
  src/app/Scenes/Onboarding/OnboardingV2/OnboardingWelcome.tsx
  src/app/Scenes/Onboarding/OnboardingV2/__tests__/OnboardingGene.tests.tsx
  src/app/Scenes/Onboarding/OnboardingV2/__tests__/OnboardingWelcome.tests.tsx
  src/app/Scenes/Onboarding/OnboardingV2/__tests__/useOnboardingTracking.tests.ts
Labels: Jira Synced

#7220 bug(GRO-1083): fix follow button appearance
  src/app/Scenes/Onboarding/OnboardingV2/Components/GeneHeader.tsx
  src/palette/elements/Button/FollowButton.tsx
Labels: Jira Synced

#7223 fix(GRO-1217): back button is difficult to interact with
  src/palette/organisms/screenStructure/Screen.tsx
Labels: Jira Synced

#7222 fix(GRO-1218): progress bar doesn't reflect progress
  src/palette/elements/ProgressBar/ProgressBar.tsx
Labels: Jira Synced

#7224 feat(GRO-1205):replace button animations and smooth out page transitions
  src/app/Scenes/Onboarding/OnboardingV2/Components/AnimatedFadingPill.tsx
  src/app/Scenes/Onboarding/OnboardingV2/Components/OnboardingQuestionTemplate.tsx
  src/app/Scenes/Onboarding/OnboardingV2/__tests__/OnboardingQuestionTemplate.tests.tsx
Labels: Merge On Green, Jira Synced

#7225 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7221 feat: connect welcome animations
  images/OnboardingImage4AndyWarholCow.webp
  images/OnboardingImage4AndyWarholCow@2x.webp
  images/OnboardingImage4AndyWarholCow@3x.webp
  src/app/Scenes/Onboarding/OnboardingPersonalization/OnboardingAnimation.tsx
  src/app/Scenes/Onboarding/OnboardingV2/OnboardingV2.tsx
  src/app/Scenes/Onboarding/OnboardingV2/OnboardingWelcome.tsx
  src/app/Scenes/Onboarding/OnboardingV2/__tests__/OnboardingWelcome.tests.tsx
Labels: Jira Synced

#7226 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7232 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7237 chore: revert m1 ios
  ios/Artsy.xcodeproj/project.pbxproj
  ios/Podfile
  ios/Podfile.lock
Labels: Squash On Green

#7236 feat(GRO-1232): mark onboarding as readyforrelease and connect with echo
  src/app/store/config/features.ts
Labels: Jira Synced, Squash On Green

#7240 chore: get main up to date
  src/app/Scenes/Favorites/FavoriteArtworks.tsx
  src/app/Scenes/MyCollection/MyCollection.tsx
  src/app/Scenes/MyCollection/MyCollectionArtworks.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx
  src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightCard.tsx
  src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightsBigCardsSwiper.tsx
  src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightsPromotionalCard.tsx
  src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightsRail.tests.tsx
  src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightsRail.tsx
  src/app/Scenes/MyCollection/Screens/Insights/MedianAuctionPriceRail.tsx
  src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsights.tsx
  src/app/store/config/features.ts
Labels: Jira Synced

#7241 fix fix: Remove artist insights modal height restriction
  src/app/Components/Artist/ArtistInsights/ArtistInsightsAuctionResults.tsx
Labels: Jira Synced

#7242 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7243 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7244 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7245 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7246 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7085 feat(CX-2577): add median sale price graph
  .secrets.baseline
  docs/storybook.md
  package.json
  src/app/Scenes/MyCollection/Screens/Insights/MedianAuctionPriceRail.tsx
  src/app/Scenes/MyCollection/Screens/Insights/MedianSalePriceAtAuction.tests.tsx
  src/app/Scenes/MyCollection/Screens/Insights/MedianSalePriceAtAuction.tsx
  src/app/Scenes/MyCollection/Screens/Insights/MedianSalePriceChart.tsx
  src/app/Scenes/MyCollection/Screens/Insights/SelectArtist.tests.tsx
  src/app/utils/marketPriceInsightHelpers.tsx
  src/palette/elements/LineGraph/Axes.tsx
  src/palette/elements/LineGraph/ColoredDot.tests.tsx
  src/palette/elements/LineGraph/ColoredDot.tsx
  src/palette/elements/LineGraph/LineGraph.stories.tsx
  src/palette/elements/LineGraph/LineGraph.tests.tsx
  src/palette/elements/LineGraph/LineGraph.tsx
  src/palette/elements/LineGraph/LineGraphBands.tests.tsx
  src/palette/elements/LineGraph/LineGraphBands.tsx
  src/palette/elements/LineGraph/LineGraphCategoryPicker.tests.tsx
  src/palette/elements/LineGraph/LineGraphCategoryPicker.tsx
  src/palette/elements/LineGraph/LineGraphChart.tsx
  src/palette/elements/LineGraph/LineGraphHeader.tsx
  src/palette/elements/LineGraph/ScatterPointsContainers.tsx
  src/palette/elements/LineGraph/helpers.tests.ts
  src/palette/elements/LineGraph/helpers.ts
  src/palette/elements/LineGraph/index.tsx
  src/palette/elements/LineGraph/testHelpers.tsx
  src/palette/elements/LineGraph/types.ts
  src/palette/elements/index.tsx
  src/palette/svgs/StarCircleIcon.tsx
  src/storybook/storybook.requires.js
  tsconfig.json
  yarn.lock
Labels: Jira Synced

#7248 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7251 fix: auction results launch blocking bugs
  src/app/Components/ArtworkFilter/Filters/KeywordFilter.tsx
Labels: Jira Synced

#7252 fix(CX-2815): fix space between chart duration and chart too big
  src/palette/elements/LineGraph/LineGraphChart.tsx
Labels: Jira Synced, Squash On Green

#7249 fix(cx-2812): unable to scroll to medium pills
  src/app/Scenes/MyCollection/Screens/Insights/MedianSalePriceAtAuction.tsx
Labels: Jira Synced, Squash On Green

#7255 chore: improve performance of interactions in the graph
  src/palette/elements/LineGraph/LineGraphChart.tsx
Labels: Jira Synced

#7256 chore: increase medium pills hitslop
  src/palette/elements/LineGraph/LineGraphCategoryPicker.tsx
  src/palette/elements/Pill/Pill.tsx
Labels: Jira Synced

#7254 fix: graph content pushed down when the text is too long
  src/palette/elements/LineGraph/LineGraph.tsx
  src/palette/elements/LineGraph/LineGraphChart.tsx
  src/palette/elements/LineGraph/LineGraphHeader.tsx
Labels: Jira Synced, Squash On Green

#7253 fix: improve copy when no auction results or little are available
  src/app/Scenes/MyCollection/Screens/Insights/MedianSalePriceChart.tsx
Labels: Jira Synced

#7259 feat: bump `react-native-vision-camera` to `2.14.1`
  ios/Artsy.xcodeproj/project.pbxproj
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: Squash On Green

#7260 chore: display debug info for reverse image screen
  src/app/Scenes/ReverseImage/Screens/Camera/ReverseImageCamera.tsx
  src/app/store/config/features.ts
Labels: Squash On Green

#7264 chore: remove complete profile message
  src/app/Scenes/MyProfile/MyProfileHeader.tsx
  src/app/Scenes/MyProfile/__tests__/MyProfileHeaderMyCollectionAndSavedWorks.tests.tsx
  src/app/store/config/features.ts
  src/app/store/config/visualClues.ts
Labels: Jira Synced, Squash On Green

#7268 fix: can't save update profile fields
  src/app/Scenes/MyAccount/updateMyUserProfile.ts
  src/app/Scenes/MyProfile/MyProfileEditForm.tsx
Labels: Jira Synced, Squash On Green

#7269 chore: make comparable works menu not clickable
  src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkComparableWorks.tsx
Labels: Jira Synced, Squash On Green

#7267 chore(GRO-1246): change NAVIGATE_TO_NEXT_SCREEN_DELAY on postfollow screen
  src/app/Scenes/Onboarding/OnboardingV2/OnboardingPostFollowLoadingScreen.tsx
Labels: Jira Synced

#7266 feat: remove back button from follow artists/galleries onboarding page
  src/app/Scenes/Onboarding/OnboardingV2/OnboardingFollows.tsx
  src/palette/organisms/screenStructure/Screen.tsx
Labels: Jira Synced

#7270 feat(GRO-1235): create a custom onboarding results grid
  src/app/Components/ArtworkGrids/utils/index.ts
  src/app/Components/ArtworkGrids/utils/layout.ts
  src/app/Components/ArtworkGrids/utils/sections.ts
  src/app/Scenes/Onboarding/OnboardingV2/Components/GeneHeader.tsx
  src/app/Scenes/Onboarding/OnboardingV2/Components/OnboardingResultsGrid.tsx
  src/app/Scenes/Onboarding/OnboardingV2/OnboardingArtistsOnTheRise.tsx
  src/app/Scenes/Onboarding/OnboardingV2/OnboardingCuratedArtworks.tsx
  src/app/Scenes/Onboarding/OnboardingV2/OnboardingGene.tsx
  src/app/Scenes/Onboarding/OnboardingV2/OnboardingTopAuctionLots.tsx
  src/app/Scenes/Onboarding/OnboardingV2/__tests__/OnboardingGene.tests.tsx
Labels: Jira Synced, Squash On Green

#7271 refactor: cleanup onboarding
  src/app/Scenes/Onboarding/OnboardingV2/ArtworkScreen.tsx
  src/app/Scenes/Onboarding/OnboardingV2/OnboardingV2.tsx
Labels: Squash On Green

#7274 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7279 feat: allow editing and deleting submitted artworks inside my collection
  .secrets.baseline
  src/app/Scenes/MyCollection/Components/MyCollectionSearchBar.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tests.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tests.tsx
Labels: Jira Synced

#7280 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7283 fix(GRO-1274): Prevent users from using the hardware android button onboarding
  src/app/Scenes/Onboarding/OnboardingV2/OnboardingFollows.tsx
  src/app/Scenes/Onboarding/OnboardingV2/OnboardingGene.tsx
  src/app/Scenes/Onboarding/OnboardingV2/OnboardingPostFollowLoadingScreen.tsx
  src/shared/hooks/useBackHandler.tests.ts
  src/shared/hooks/useBackHandler.ts
Labels: Jira Synced

#7281 feat(FX-4189): Add the ability to select an image from the library for reverse image search
  src/app/Scenes/ReverseImage/Screens/Camera/Components/CameraButtons.tsx
  src/app/Scenes/ReverseImage/Screens/Camera/ReverseImageCamera.tsx
  src/app/Scenes/ReverseImage/Screens/Preview/ReverseImagePreview.tsx
  src/app/Scenes/ReverseImage/types.ts
Labels: Jira Synced

#7290 fix: hide apple sign in on iOS <13
  src/app/Scenes/Onboarding/OnboardingCreateAccount/OnboardingSocialPick.tests.tsx
  src/app/Scenes/Onboarding/OnboardingSocialLink.tests.tsx
  src/app/Scenes/Onboarding/OnboardingSocialLink.tsx
  src/app/Scenes/Onboarding/OnboardingSocialPick.tsx
Labels: Squash On Green

#7292 fix: android cut off welcome screen when having notches
  src/app/Scenes/Onboarding/OnboardingV2/OnboardingWelcome.tsx
Labels: Jira Synced

#7284 feat: allow releasing specific versions of apps
  .circleci/config.yml
  .github/workflows/promote-android.yml
  .github/workflows/promote-ios.yml
  Gemfile.lock
  fastlane/Fastfile
  package.json
  scripts/promote-beta-to-submission-android
  scripts/promote-beta-to-submission-ios
  scripts/promote-if-appstore-submission-branch
  scripts/promote-if-playstore-submission-branch
  scripts/setup-distribute-macos
Labels: Jira Synced

#7294 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green
