Repository artsy/eigen, pull requests merged in 2022-09, with the labels that each got.

#7305 fix: broken main build after onboarding release
  src/app/Scenes/Onboarding/OnboardingCreateAccount/Onboarding.tests.tsx
Labels: Squash On Green

#7303 fix: Adjust MyC insights sell-through rate formatting
  src/app/Components/Artist/ArtistInsights/MarketStats.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkArtistMarket.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtworkInsights.tests.tsx
  src/app/utils/marketPriceInsightHelpers.tsx
Labels: Squash On Green

#7299 feat(CX-2834): median graph visual improvements
  src/app/utils/renderMarkdown.tests.tsx
  src/palette/elements/LineGraph/ColoredDot.tests.tsx
  src/palette/elements/LineGraph/ColoredDot.tsx
  src/palette/elements/LineGraph/LineGraphBands.tsx
  src/palette/elements/LineGraph/LineGraphCategoryPicker.tsx
  src/palette/elements/LineGraph/LineGraphChart.tsx
  src/palette/elements/Pill/Pill.tsx
Labels: Jira Synced

#7291 feat(CX-2646): add career highlights to graph
  package.json
  src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightBottomSheet.tests.tsx
  src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightBottomSheet.tsx
  src/app/Scenes/MyCollection/Screens/Insights/Components/CareerHighlightBottomSheetItem.tests.tsx
  src/app/Scenes/MyCollection/Screens/Insights/Components/CareerHighlightBottomSheetItem.tsx
  src/app/Scenes/MyCollection/Screens/Insights/MedianSalePriceAtAuction.tsx
  src/app/Scenes/MyCollection/Screens/Insights/MedianSalePriceChart.tsx
  src/app/Scenes/MyCollection/Screens/Insights/providers/MedianSalePriceChartDataContext.tsx
  src/palette/elements/LineGraph/ScatterPointsContainers.tsx
  src/setupJest.ts
  yarn.lock
Labels: Jira Synced

#7309 feat(CX-2818): Remove support for floating label in LineChart
  package.json
  src/palette/elements/LineGraph/LineGraphChart.tsx
  src/palette/elements/LineGraph/ScatterPointsContainers.tsx
  yarn.lock
Labels: Jira Synced

#7310 feat(CX-2828): change empty graph copy
  src/app/Scenes/MyCollection/Screens/Insights/MedianSalePriceChart.tsx
  src/palette/elements/LineGraph/LineGraphHeader.tsx
Labels: Jira Synced

#7300 feat: support fullscreen mode for modal screens
  src/app/AppRegistry.tsx
  src/app/navigation/ModalStack.tsx
Labels: Squash On Green

#7301 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7312 fix(CX-2900): fix label space in chart
  src/palette/elements/LineGraph/LineGraphChart.tsx
Labels: Jira Synced

#7313 fix(CX-2898): center graph no data text
  src/app/Scenes/MyCollection/Screens/Insights/MedianSalePriceChart.tsx
Labels: Jira Synced

#7315 fix(CX-2908): Exclude Categories without data from MedianSaleChart
  src/app/Scenes/MyCollection/Screens/Insights/MedianSalePriceChart.tsx
  src/app/Scenes/MyCollection/Screens/Insights/providers/MedianSalePriceChartDataContext.tsx
  src/palette/elements/LineGraph/LineGraphHeader.tsx
Labels: Jira Synced

#7316 chore: make camera always active when dev toggle is enabled
  src/app/Scenes/ReverseImage/Screens/Camera/ReverseImageCamera.tsx
Labels: Squash On Green

#7318 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7319 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7320 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7321 fix: Fix Career Highlight UI issues
  src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightBottomSheet.tsx
  src/app/Scenes/MyCollection/Screens/Insights/Components/CareerHighlightBottomSheetItem.tests.tsx
  src/app/Scenes/MyCollection/Screens/Insights/Components/CareerHighlightBottomSheetItem.tsx
Labels: Jira Synced

#7322 feat(CX-2894): Change Highlight Icon Color
  src/app/Scenes/MyCollection/Screens/Insights/MedianSalePriceChart.tsx
  src/app/utils/marketPriceInsightHelpers.tsx
  src/palette/elements/LineGraph/LineGraph.tsx
  src/palette/elements/LineGraph/LineGraphChart.tsx
Labels: Jira Synced

#7317 fix(CX-2867): fix tappable area and spacing in MedianAuctionRailsItem
  src/app/Scenes/MyCollection/Screens/Insights/MedianAuctionPriceListItem.tsx
Labels: Jira Synced

#7326 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7331 fix(CX-2892): make unit change experience better at add works flow
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/Dimensions.tsx
  src/palette/elements/Radio/RadioButton.tsx
Labels: Jira Synced

#7334 feat: set dark navigation bar color for reverse image screens
  src/app/App.tsx
  src/app/NativeModules/ArtsyNativeModule.tsx
  src/app/Scenes/Onboarding/OnboardingWelcome.tsx
  src/app/Scenes/ReverseImage/ReverseImage.tsx
Labels: Squash On Green

#7337 feat(2920): Feature flags for Median Auction Screen and Chart
  src/app/Scenes/MyCollection/Screens/Insights/MedianSalePriceChart.tsx
  src/app/store/config/features.ts
Labels: Jira Synced

#7335 feat(CX-2919): Track Median Auction Screen and Chart Interactions
  package.json
  src/app/Scenes/MyCollection/Screens/Insights/Components/MedianSalePriceChartTracking.tsx
  src/app/Scenes/MyCollection/Screens/Insights/MedianAuctionPriceRail.tsx
  src/app/Scenes/MyCollection/Screens/Insights/MedianSalePriceAtAuction.tsx
  yarn.lock
Labels: Jira Synced

#7323 feat(FX-4209): setup analytics for reverse image
  src/app/Components/SearchImageHeaderButton/SearchImageHeaderButton.tests.tsx
  src/app/Components/SearchImageHeaderButton/SearchImageHeaderButton.tsx
  src/app/Scenes/Fair/Fair.tsx
  src/app/Scenes/ReverseImage/ReverseImage.tsx
  src/app/Scenes/ReverseImage/Screens/Camera/ReverseImageCamera.tsx
  src/app/Scenes/ReverseImage/Screens/MultipleResults/ReverseImageArtworksRail.tsx
  src/app/Scenes/ReverseImage/Screens/MultipleResults/ReverseImageMultipleResults.tsx
  src/app/Scenes/ReverseImage/Screens/Preview/ReverseImagePreview.tsx
  src/app/Scenes/ReverseImage/types.ts
  src/app/Scenes/Show/Show.tsx
Labels: Jira Synced, Squash On Green

#7341 chore: update navigation color on focus for reverse image screen
  src/app/Scenes/ReverseImage/ReverseImage.tsx
Labels: Squash On Green

#7342 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7343 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7332 fix(NX-3280): Adds loading state to fix multiple inquiry sends
  src/app/Scenes/Artwork/Components/CommercialButtons/InquiryModal.tsx
Labels: Jira Synced

#7347 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7349 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7352 fix: don't upload changelogs in supply #trivial
  fastlane/Fastfile
Labels: Squash On Green

#7353 fix: don't retain old android versions for now #trivial
  fastlane/Fastfile
Labels: Squash On Green

#7354 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7351 feat(CX-2923): add recently sold artworks rail to SWA landing page
  src/app/Components/ArtworkRail/ArtworkRail.tsx
  src/app/Components/ArtworkRail/ArtworkRailCard.tsx
  src/app/Scenes/SellWithArtsy/Components/SellWithArtsyCustomRecentlySold.tsx
  src/app/Scenes/SellWithArtsy/SellWithArtsyHome.tsx
  src/app/Scenes/SellWithArtsy/index.tests.tsx
  src/app/store/config/features.ts
Labels: Jira Synced

#7356 feat(FX-4221): "Show results" does not work after applying filters in Insights
  src/app/Components/ArtworkFilter/Filters/KeywordFilter.tsx
Labels: Jira Synced

#7360 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7359 fix: remove spotlight indexing code interfering with scrolling
  ios/Artsy/View_Controllers/Auction/AuctionInformationViewController.swift
Labels: Jira Synced

#7363 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7368 fix: lock orientation to "portrait"
  src/app/navigation/NavStack.tsx
Labels: Squash On Green

#7377 fix: Only show size in selected metric on My Collection artwork screen
  src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkAbout/MyCollectionArtworkAboutWork.tests.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkAbout/MyCollectionArtworkAboutWork.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtworkAbout.tests.tsx
Labels: Jira Synced

#7379 feat: Change add artwork button copy
  src/app/Scenes/MyCollection/MyCollection.tsx
Labels: Jira Synced

#7381 fix(NX-3277): change copy on fraud prevention banner
  src/app/Scenes/Inbox/Components/Conversations/Messages.tests.tsx
  src/app/Scenes/Inbox/Components/Conversations/Messages.tsx
Labels: Jira Synced

#7387 chore: ignore search results when component was unmounted
  src/app/Scenes/ReverseImage/Screens/Preview/ReverseImagePreview.tsx
Labels: Squash On Green

#7386 feat(DO-461): add bonhams to filter list
  src/app/Components/ArtworkFilter/Filters/AuctionHouseOptions.tests.tsx
  src/app/Components/ArtworkFilter/Filters/AuctionHouseOptions.tsx
Labels: Jira Synced

#7390 fix(NX-3299): Hyphenate 'last-minute'
  src/app/Components/Bidding/Components/Timer.tests.tsx
  src/app/Components/Bidding/Components/Timer.tsx
  src/app/Scenes/Artwork/Components/ArtworkTombstone.tests.tsx
  src/app/Scenes/Artwork/Components/CascadingEndTimesBanner.tsx
Labels: Jira Synced, Squash On Green

#7391 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7395 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7397 chore: increase touchable area for the back button
  src/app/Scenes/ReverseImage/Components/HeaderBackButton.tsx
  src/app/Scenes/ReverseImage/Screens/ArtworkNotFound/ReverseImageArtworkNotFoundScreen.tsx
  src/app/Scenes/ReverseImage/Screens/Camera/Components/CameraGrantPermissions.tsx
  src/app/Scenes/ReverseImage/Screens/Camera/ReverseImageCamera.tsx
  src/app/Scenes/ReverseImage/Screens/MultipleResults/ReverseImageMultipleResults.tsx
  src/app/Scenes/ReverseImage/Screens/Preview/ReverseImagePreview.tsx
Labels: Squash On Green

#7394 feat(FX-4248): add Activity screen
  android/app/src/main/AndroidManifest.xml
  src/app/AppRegistry.tsx
  src/app/Scenes/Activity/Activity.tests.tsx
  src/app/Scenes/Activity/Activity.tsx
  src/app/Scenes/Activity/ActivityList.tsx
  src/app/Scenes/Home/ActivityIndicator.tsx
  src/app/Scenes/Home/Home.tests.tsx
  src/app/Scenes/Home/Home.tsx
  src/app/navigation/routes.ts
  src/app/store/config/features.ts
  src/palette/elements/VisualClue/VisualClueDot.tsx
Labels: Jira Synced, Squash On Green

#7400 feat: Hide Get Price Estimate CTA when artwork is submitted
  src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtworkInsights.tests.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtworkInsights.tsx
Labels: Jira Synced

#7402 fix: Adjust SWA header subtitle copy
  src/app/Scenes/SellWithArtsy/Components/Header.tsx
Labels: Squash On Green

#7403 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7396 feat[FX-4251]: replace genes with collections in onboarding
  src/app/Scenes/Onboarding/OnboardingV2/Components/GeneHeader.tsx
  src/app/Scenes/Onboarding/OnboardingV2/Components/MarketingCollectionHeader.tsx
  src/app/Scenes/Onboarding/OnboardingV2/Components/OnboardingResultsGrid.tsx
  src/app/Scenes/Onboarding/OnboardingV2/Hooks/useNextOnboardingScreen.tsx
  src/app/Scenes/Onboarding/OnboardingV2/OnboardingArtistsOnTheRiseCollection.tsx
  src/app/Scenes/Onboarding/OnboardingV2/OnboardingCuratedArtworksCollection.tsx
  src/app/Scenes/Onboarding/OnboardingV2/OnboardingGene.tsx
  src/app/Scenes/Onboarding/OnboardingV2/OnboardingMarketingCollection.tsx
  src/app/Scenes/Onboarding/OnboardingV2/OnboardingTopAuctionLotsCollection.tsx
  src/app/Scenes/Onboarding/OnboardingV2/OnboardingV2.tsx
  src/app/Scenes/Onboarding/OnboardingV2/__tests__/OnboardingMarketingCollection.tests.tsx
  src/app/store/config/features.ts
Labels: Jira Synced

#7405 fix: SWA landing page margin issue in Android
  src/app/Scenes/SellWithArtsy/SellWithArtsyHome.tsx
Labels: Squash On Green

#7408 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7414 fix: Change fetch policy to store-and-network on MyC screens
  src/app/Scenes/MyCollection/Screens/Insights/AuctionResultsForArtistsYouCollect.tsx
  src/app/Scenes/MyCollection/Screens/Insights/MedianSalePriceAtAuction.tsx
  src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsights.tsx
Labels: Jira Synced, Squash On Green

#7406 feat(FX-4299): add activity item
  src/app/Scenes/Activity/ActivityItem.tests.tsx
  src/app/Scenes/Activity/ActivityItem.tsx
  src/app/Scenes/Activity/ActivityList.tsx
  src/app/Scenes/Activity/util/getDateLabel.tests.ts
  src/app/Scenes/Activity/util/getDateLabel.ts
Labels: Jira Synced

#7417 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7416 feat(FX-4306): Display the blue dot on Activity icon only when user has unread notifications
  src/app/Scenes/Home/Components/ActivityIndicator.tsx
  src/app/Scenes/Home/Components/HomeHeader.tests.tsx
  src/app/Scenes/Home/Components/HomeHeader.tsx
  src/app/Scenes/Home/Home.tsx
Labels: Jira Synced

#7419 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7420 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7412 feat(FX-4304): add activity panel tabs
  src/app/AppRegistry.tsx
  src/app/Scenes/Activity/Activity.tests.tsx
  src/app/Scenes/Activity/Activity.tsx
  src/app/Scenes/Activity/ActivityItem.tsx
  src/app/Scenes/Activity/ActivityList.tsx
  src/app/Scenes/Activity/ActivityTabSubheader.tsx
  src/app/Scenes/Activity/types.ts
Labels: Jira Synced

#7427 fix(CX-2842): Update onSuccess behavior when editing a MyC artwork
  src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tsx
Labels: Jira Synced
