Repository artsy/eigen, pull requests merged in 2022-12, with the labels that each got.

#7764 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7754 feat: update order details: add payment info and payment method
  src/app/Scenes/OrderHistory/OrderDetails/Components/OrderDetails.tsx
  src/app/Scenes/OrderHistory/OrderDetails/Components/OrderDetailsPayment.tsx
  src/app/Scenes/OrderHistory/OrderDetails/Components/WirePaymentSection.tsx
  src/app/Scenes/OrderHistory/OrderDetails/OrderDetails.tests.tsx
  src/app/Scenes/OrderHistory/OrderDetails/OrderDetailsPayment.tests.tsx
  src/app/Scenes/OrderHistory/OrderDetails/WirePaymentSection.tests.tsx
Labels: Jira Synced

#7758 feat: remove extraneous webview
  src/app/Components/Bidding/Screens/RegistrationResult.tsx
  src/app/Components/StyledWebView.tsx
  src/app/Scenes/SaleInfo/SaleInfo.tsx
  src/app/navigation/navigate.ts
  src/app/utils/AdminMenu.tsx
Labels: Jira Synced

#7759 fix: webview should move us to native screens if we have them
  index-common.js
  package.json
  src/app/Components/ArtsyWebView.tests.tsx
  src/app/Components/ArtsyWebView.tsx
  src/app/navigation/routes.tests.ts
  src/app/navigation/routes.ts
  src/setupJest.ts
  yarn.lock
Labels: Jira Synced, Squash On Green

#7771 fix: flaky tests on artwork page
  src/app/Scenes/Artwork/Artwork.tests.tsx
Labels: Jira Synced, Squash On Green

#7777 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7775 feat(FX-4486): add sale message for not for sale artworks
  src/app/Scenes/Artwork/Components/ArtworkTombstone.tests.tsx
  src/app/Scenes/Artwork/Components/ArtworkTombstone.tsx
Labels: Jira Synced

#7760 feat(FX-4305): add ability to hide bottom tabs on specific screen
  src/app/Scenes/Artwork/Artwork.tsx
  src/app/Scenes/BottomTabs/BottomTabs.tests.tsx
  src/app/Scenes/BottomTabs/BottomTabs.tsx
  src/app/Scenes/BottomTabs/BottomTabsNavigator.tsx
  src/app/Scenes/BottomTabs/setBottomTabVisibilityForCurrentScreen.ts
  src/app/Scenes/BottomTabs/useBottomTabBarHeight.ts
  src/app/navigation/NavStack.tsx
Labels: Jira Synced, Squash On Green

#7577 feat(FX-4419): Auctions progressbar/timer move to header
  src/app/Components/Bidding/Components/ArtworkAuctionProgressBar.tsx
  src/app/Components/Bidding/Components/Timer.tsx
  src/app/Components/Countdown/Ticker.tsx
  src/app/Scenes/Artwork/Artwork.tsx
  src/app/Scenes/Artwork/Components/ArtworkHeader.tests.tsx
  src/app/Scenes/Artwork/Components/ArtworkHeader.tsx
  src/app/Scenes/Artwork/Components/ArtworkLotTimer.tests.tsx
  src/app/Scenes/Artwork/Components/ArtworkLotTimer.tsx
  src/app/Scenes/Artwork/Components/ArtworkScreenHeaderCreateAlert.tsx
  src/app/Scenes/Artwork/Components/ArtworkTombstone.tests.tsx
  src/app/Scenes/Artwork/Components/ArtworkTombstone.tsx
  src/app/Scenes/Artwork/Components/CommercialInformation.tsx
Labels: Jira Synced

#7765 fix: notification is not appear if app in foreground
  package.json
  yarn.lock
Labels: Jira Synced

#7781 fix: small podfile.lock fix
  ios/Podfile.lock
Labels: Squash On Green

#7784 refactor: remove bottom offset for modal screens
  src/app/Scenes/BottomTabs/BottomTabsNavigator.tsx
  src/app/navigation/NavStack.tsx
Labels: Squash On Green

#7697 fix: placeholder for recovery codes
  src/app/Scenes/Onboarding/OnboardingLoginWithOTP.tsx
Labels: Jira Synced, Squash On Green

#7774 feat: add copy buttons for payment info
  src/app/Scenes/OrderHistory/OrderDetails/Components/WirePaymentSection.tsx
  src/app/Scenes/OrderHistory/OrderDetails/WirePaymentSection.tests.tsx
Labels: Jira Synced

#7790 fix: import
  src/app/Scenes/OrderHistory/OrderDetails/Components/WirePaymentSection.tsx
Labels: Squash On Green

#7791 fix: bad function call
  src/app/Components/Bidding/Screens/BidResult.tsx
  src/app/Components/Bidding/Screens/Registration.tsx
  src/app/Components/Bidding/Screens/RegistrationResult.tsx
  src/app/Components/Bidding/Screens/SelectMaxBid.tsx
  src/app/utils/AdminMenu.tsx
Labels: Squash On Green

#7782 feat(FX-4477): add counts to activity panel items
  src/app/Scenes/Activity/ActivityItem.tests.tsx
  src/app/Scenes/Activity/ActivityItem.tsx
Labels: Jira Synced

#7792 chore: change order for consignments section
  src/app/Scenes/Artwork/Artwork.tests.tsx
  src/app/Scenes/Artwork/Artwork.tsx
Labels: Squash On Green

#7794 feat(FX-4489): add loading placeholders for redesigned artwork screen
  src/app/Scenes/Artwork/Components/AboveTheFoldArtworkPlaceholder.tsx
  src/app/Scenes/Artwork/Components/BelowTheFoldPlaceholder.tsx
Labels: Jira Synced, Squash On Green

#7798 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7763 feat(FX-4475): Blue dot on Home icon when there are unread notifications
  src/app/Scenes/Activity/Activity.tsx
  src/app/Scenes/BottomTabs/BottomTabs.tests.tsx
  src/app/Scenes/BottomTabs/BottomTabs.tsx
  src/app/Scenes/BottomTabs/BottomTabsButton.tsx
  src/app/Scenes/BottomTabs/BottomTabsModel.ts
  src/app/Scenes/Home/Components/HomeHeader.tests.tsx
  src/app/Scenes/Home/Components/HomeHeader.tsx
  src/app/Scenes/Home/Home.tsx
  src/app/store/migration.tests.ts
  src/app/store/persistence.tests.ts
Labels: Jira Synced

#7801 chore: return correct data for optimistic response for save button
  src/app/Scenes/Artwork/Components/ArtworkScreenHeader.tsx
Labels: Squash On Green

#7803 fix: Adjust home screen placeholder for large rail
  src/app/Scenes/Home/Home.tsx
Labels: Squash On Green

#7805 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7808 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7806 fix: save user's coordinates
  src/app/Scenes/MyProfile/MyProfileEditForm.tsx
  src/app/utils/googleMaps.ts
Labels: Jira Synced

#7811 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7810 fix: request condition report copy change
  src/app/Scenes/Artwork/Components/RequestConditionReport.tests.tsx
  src/app/Scenes/Artwork/Components/RequestConditionReport.tsx
Labels: Squash On Green

#7815 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7814 fix: artwork title should be italic
  src/app/Scenes/Artwork/Components/ArtworkTombstone.tsx
Labels: Squash On Green

#7819 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7802 chore: artwork header buttons improvements
  src/app/Scenes/Artwork/Components/ArtworkScreenHeader.tsx
  src/app/Scenes/Artwork/Components/ArtworkScreenHeaderCreateAlert.tsx
  src/palette/elements/Button/Button.tsx
Labels: Squash On Green

#7822 fix: lot label trim
  src/app/Scenes/Artwork/Components/ArtworkLotTimer.tsx
  src/app/Scenes/Artwork/Components/ArtworkTombstone.tsx
Labels: Squash On Green

#7824 fix: display save button for bidding closed lots
  src/app/Scenes/Artwork/Components/ArtworkScreenHeader.tests.tsx
  src/app/Scenes/Artwork/Components/ArtworkScreenHeader.tsx
Labels: Squash On Green

#7820 fix: Always use local image for My Collection images when available
  src/app/Scenes/MyCollection/Components/MyCollectionImageView.tsx
Labels: Squash On Green

#7825 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7823 refactor: another approach for hiding the bottom tabs
  src/app/Scenes/Artwork/Artwork.tsx
  src/app/Scenes/Artwork/Components/ArtworkStickyBottomContent.tsx
  src/app/Scenes/BottomTabs/BottomTabsNavigator.tsx
  src/app/navigation/NavStack.tsx
Labels: Squash On Green

#7828 fix: type
  src/app/store/config/features.ts
Labels: Squash On Green

#7816 fix: Add artwork rail save icon tracking
  src/app/Components/ArtworkRail/ArtworkRailCard.tsx
Labels: Jira Synced

#7831 fix: environment swap
  src/app/Components/Toast/ToastComponent.tsx
  src/app/store/GlobalStoreModel.ts
  src/app/store/persistence.tests.ts
  src/app/store/persistence.ts
  src/app/utils/DevMenu.tsx
Labels: Squash On Green

#7821 fix: Deep zoom issues
  src/app/Scenes/Artwork/Artwork.tsx
  src/app/Scenes/Artwork/Components/ImageCarousel/FullScreen/ImageCarouselFullScreenAndroid.tsx
  src/app/Scenes/Artwork/Components/ImageCarousel/FullScreen/ImageZoomViewAndroid.tsx
  src/app/Scenes/Artwork/Components/ImageCarousel/ImageCarouselEmbedded.tsx
  src/app/Scenes/MyProfile/DevicePrefsModel.ts
  src/app/utils/DevMenuWrapper.tsx
Labels: Jira Synced

#7807 feat(FX-4472): iOS: unread notifications count on the app icon
  src/app/Scenes/Activity/ActivityMarkAllAsReadSection.tsx
  src/app/Scenes/BottomTabs/BottomTabs.tests.tsx
  src/app/Scenes/BottomTabs/BottomTabsModel.ts
Labels: Jira Synced

#7834 fix: Reset My Collection form after skipping artist selection
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormArtist.tsx
Labels: Jira Synced, Squash On Green

#7835 feat: add staging indicator on artwork page header #ff
  src/app/Scenes/Artwork/Components/ArtworkScreenHeader.tsx
Labels: FF

#7838 fix: off by one for webp check #trivial
  src/app/Components/OpaqueImageView/createGeminiUrl.tsx
Labels: Squash On Green

#7840 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7841 chore: small improvements for redesigned artwork loading placeholder
  src/app/Scenes/Artwork/Components/AboveTheFoldArtworkPlaceholder.tsx
Labels: Squash On Green

#7772 feat(CX-2938): SWA Inquiry Flow
  src/app/AppRegistry.tsx
  src/app/Scenes/SellWithArtsy/Components/Header.tsx
  src/app/Scenes/SellWithArtsy/ConsignmentInquiry/ConsignmentInquiryConfirmation.tests.tsx
  src/app/Scenes/SellWithArtsy/ConsignmentInquiry/ConsignmentInquiryConfirmation.tsx
  src/app/Scenes/SellWithArtsy/ConsignmentInquiry/ConsignmentInquiryForm.tests.tsx
  src/app/Scenes/SellWithArtsy/ConsignmentInquiry/ConsignmentInquiryForm.tsx
  src/app/Scenes/SellWithArtsy/ConsignmentInquiry/ConsignmentInquiryFormAbandonEdit.tsx
  src/app/Scenes/SellWithArtsy/ConsignmentInquiry/ConsignmentInquiryScreen.tests.tsx
  src/app/Scenes/SellWithArtsy/ConsignmentInquiry/ConsignmentInquiryScreen.tsx
  src/app/Scenes/SellWithArtsy/SellWithArtsyHome.tsx
  src/app/navigation/routes.ts
  src/app/store/config/features.ts
Labels: Jira Synced

#7844 Change showInAdminMenu to showInDevMenu for AREnableConsignmentInquiryFlow
  src/app/store/config/features.ts
Labels: Squash On Green

#7845 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7846 chore: small improvement for saved search alert flow
  src/app/Scenes/SavedSearchAlert/SavedSearchAlertForm.tsx
Labels: Squash On Green

#7847 refactor(FX-4498): remove AREnableActivity feature flag
  src/app/Scenes/Home/Components/ActivityIndicator.tests.tsx
  src/app/Scenes/Home/Components/ActivityIndicator.tsx
  src/app/Scenes/Home/Components/HomeHeader.tests.tsx
  src/app/store/config/features.ts
Labels: Jira Synced, Squash On Green

#7849 chore(FX-4211): sort artists by name in "Artists" filter when artwork is in auction
  src/app/Components/ArtworkFilter/Filters/ArtistIDsSaleArtworksOptionsScreen.tests.tsx
  src/app/Components/ArtworkFilter/Filters/ArtistIDsSaleArtworksOptionsScreen.tsx
  src/app/Components/ArtworkFilter/Filters/MultiSelectCheckOption.tsx
Labels: Jira Synced, Squash On Green

#7850 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7851 feat: update test wrapper to match force/volt and support preloaded q…
  src/app/tests/setupTestWrapper.tsx
Labels: Squash On Green

#7853 chore: clean up enableImprovedSearchPills flag
  src/app/Scenes/Search/Search.tests.tsx
  src/app/Scenes/Search/Search.tsx
Labels: Squash On Green

#7855 test: setupTestWrapper improvements
  src/app/Components/PartnerEntityHeader.tests.tsx
  src/app/tests/setupTestWrapper.tsx
Labels: Squash On Green

#7832 chore: update changelog for 8.4.0
  CHANGELOG/android-changelog.md
  CHANGELOG/ios-changelog.md
Labels: Squash On Green

#7858 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7796 feat: add show only upcoming auction results filter
  src/app/Components/Artist/ArtistInsights/ArtistInsightsAuctionResults.tsx
  src/app/Components/ArtworkFilter/ArtworkFilterHelpers.ts
  src/app/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx
  src/app/Components/ArtworkFilter/ArtworkFilterStore.tsx
  src/app/Components/ArtworkFilter/ArtworkFiltersStore.tests.tsx
  src/app/Components/ArtworkFilter/components/ArtworkFilterOptionCheckboxItem.tsx
  src/app/Components/ArtworkFilter/types.ts
Labels: Jira Synced

#7860 chore(FX-4399): display the empty state for the partner artworks tab if there are no artworks
  src/app/Scenes/Partner/Components/PartnerArtwork.tests.tsx
  src/app/Scenes/Partner/Components/PartnerArtwork.tsx
Labels: Jira Synced, Squash On Green

#7864 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7863 fix: My Collection form artist screen bottom spacing
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtistAutosuggest.tsx
Labels: Jira Synced

#7869 fix: failed tests
  src/app/Scenes/Artwork/Components/ArtworkActions.tests.tsx
  src/app/Scenes/Artwork/Components/CommercialButtons/BidButton.tests.tsx
Labels: Squash On Green

#7859 test: refactor some tests to use setupTestWrapper
  src/app/Components/Artist/ArtistAbout/ArtistAbout.tests.tsx
  src/app/Components/Artist/ArtistHeader.tests.tsx
  src/app/Scenes/Search/SearchArtworksGrid.tests.tsx
  src/app/Scenes/ViewingRoom/Components/ViewingRoomArtworkRail.tests.tsx
  src/app/Scenes/ViewingRoom/Components/ViewingRoomViewWorksButton.tests.tsx
Labels: Squash On Green

#7868 chore: set app version to 8.5.0
  app.json
Labels: Squash On Green

#7866 chore: remove extra padding from artwork page when no sale message
  src/app/Scenes/Artwork/Components/ArtworkTombstone.tsx
Labels: Jira Synced, Squash On Green

#7871 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7867 Revert "feat: add show only upcoming auction results filter"
  src/app/Components/Artist/ArtistInsights/ArtistInsightsAuctionResults.tsx
  src/app/Components/ArtworkFilter/ArtworkFilterHelpers.ts
  src/app/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx
  src/app/Components/ArtworkFilter/ArtworkFilterStore.tsx
  src/app/Components/ArtworkFilter/ArtworkFiltersStore.tests.tsx
  src/app/Components/ArtworkFilter/components/ArtworkFilterOptionCheckboxItem.tsx
  src/app/Components/ArtworkFilter/types.ts
Labels: Squash On Green

#7873 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7875 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7876 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7878 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7874 chore: update auction result list item component
  src/app/Components/AuctionResult/AuctionResultMidEstimate.tests.tsx
  src/app/Components/AuctionResult/AuctionResultMidEstimate.tsx
  src/app/Components/Lists/AuctionResultListItem.tests.tsx
  src/app/Components/Lists/AuctionResultListItem.tsx
Labels: Jira Synced

#7865 feat(FX-4076): improvements for live auction modal
  ios/Artsy/View_Controllers/ARSerifNavigationViewController.m
  ios/Artsy/View_Controllers/Live_Auctions/LiveAuctionViewController.swift
Labels: Jira Synced

#7881 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7882 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7886 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7883 feat(CX-3255): Add edit profile tracking event
  src/app/Scenes/MyProfile/MyProfileEditForm.tsx
Labels: Jira Synced, Squash On Green

#7887 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7888 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7885 fix: revert mid estimate strings
  src/app/Components/AuctionResult/AuctionResultMidEstimate.tests.tsx
  src/app/Components/AuctionResult/AuctionResultMidEstimate.tsx
  src/app/Components/Lists/AuctionResultListItem.tests.tsx
  src/app/Components/Lists/AuctionResultListItem.tsx
Labels: Squash On Green

#7890 feat: add upcoming auctions rails to the home page
  src/app/Components/Lists/AuctionResultListItem.tsx
  src/app/Scenes/Home/Components/HomeUpcomingAuctionsRail.tsx
  src/app/Scenes/Home/Home.tsx
  src/app/store/config/features.ts
Labels: Jira Synced

#7891 feat: add upcoming auction results screen
  android/app/src/main/AndroidManifest.xml
  src/app/AppRegistry.tsx
  src/app/Scenes/AuctionResults/AuctionResultsForArtistsYouFollow.tsx
  src/app/Scenes/AuctionResults/AuctionResultsScreenWrapper.tests.tsx
  src/app/Scenes/AuctionResults/AuctionResultsScreenWrapper.tsx
  src/app/Scenes/AuctionResults/AuctionResultsUpcoming.tsx
  src/app/Scenes/Home/Components/HomeUpcomingAuctionsRail.tsx
  src/app/navigation/routes.ts
Labels: Jira Synced

#7892 feat(CX-3229): separate between past and future auction results
  src/app/Components/Artist/ArtistInsights/ArtistInsightsAuctionResults.tests.tsx
  src/app/Components/Artist/ArtistInsights/ArtistInsightsAuctionResults.tsx
Labels: Jira Synced

#7879 refactor(FX-4396): Optimization for "Artists" filter screen
  src/app/Components/ArtworkFilter/Filters/ArtistIDsArtworksOptions.tsx
  src/app/Components/ArtworkFilter/Filters/MultiSelectOption.tsx
  src/app/Components/ArtworkFilter/Filters/MultiSelectOptionItem.tsx
  src/app/Components/ArtworkFilter/Filters/useMultiSelect.ts
Labels: Jira Synced

#7893 fix: Adjust New Works rail artwork rail save icon tracking
  src/app/Components/ArtworkRail/ArtworkRail.tsx
  src/app/Components/ArtworkRail/ArtworkRailCard.tsx
  src/app/Scenes/Home/Components/NewWorksForYouRail.tsx
Labels: Jira Synced, Squash On Green

#7895 feat: allow filtering auction results by state
  src/app/Components/Artist/ArtistInsights/ArtistInsightsAuctionResults.tsx
  src/app/Components/ArtworkFilter/ArtworkFilterHelpers.ts
  src/app/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx
  src/app/Components/ArtworkFilter/ArtworkFilterStore.tsx
  src/app/Components/ArtworkFilter/ArtworkFiltersStore.tests.tsx
  src/app/Components/ArtworkFilter/components/ArtworkFilterOptionCheckboxItem.tsx
  src/app/Components/ArtworkFilter/types.ts
Labels: Jira Synced

#7889 feat(CX-3157): Eigen Add Medium to SWA Form
  src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionWhySell.tests.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionWhySell.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/CategoryPicker.tests.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/CategoryPicker.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormMain.tsx
  src/app/Scenes/MyCollection/utils/initializeSubmissionArtworkForm.ts
  src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkDetails/ArtworkDetailsForm.tsx
  src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkDetails/utils/acceptableCategoriesForSubmission.ts
  src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkDetails/utils/testUtils.ts
  src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkDetails/validation.ts
  src/app/store/migration.ts
Labels: Jira Synced

#7897 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7898 fix: Address QA comments on auction results
  src/app/Components/AuctionResult/AuctionResultMidEstimate.tests.tsx
  src/app/Components/AuctionResult/AuctionResultMidEstimate.tsx
  src/app/Scenes/AuctionResults/AuctionResultsForArtistsYouFollow.tsx
  src/app/Scenes/AuctionResults/AuctionResultsScreenWrapper.tsx
  src/app/Scenes/Home/Components/AuctionResultsRail.tsx
  src/app/Scenes/Home/Components/HomeUpcomingAuctionsRail.tsx
  src/app/store/config/features.ts
Labels: Squash On Green

#7899 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7902 fix: padding on mid estimate comp
  src/app/Components/Artist/ArtistInsights/ArtistInsightsAuctionResults.tsx
  src/app/Components/AuctionResult/AuctionResultMidEstimate.tests.tsx
  src/app/Components/AuctionResult/AuctionResultMidEstimate.tsx
  src/app/Components/AuctionResultsList.tsx
  src/app/Components/Lists/AuctionResultListItem.tsx
Labels: Squash On Green

#7905 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7906 feat(CX-3272): Remove Zipcode in SWA artwork details form
  src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkDetails/ArtworkDetailsForm.tsx
  src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkDetails/validation.ts
Labels: Jira Synced

#7904 feat: Add includePersonalArtists param to collection artist query
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtistAutosuggest.tsx
Labels: Jira Synced

#7907 feat(CX-3273): Remove Phone validation in SWA form
  src/app/Scenes/SellWithArtsy/SubmitArtwork/ContactInformation/ContactInformation.tests.tsx
  src/app/Scenes/SellWithArtsy/SubmitArtwork/ContactInformation/ContactInformation.tsx
  src/app/Scenes/SellWithArtsy/SubmitArtwork/ContactInformation/validation.ts
Labels: Jira Synced

#7909 fix: Mark depth as optional in SWA flow
  src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkDetails/ArtworkDetailsForm.tsx
Labels: Squash On Green

#7910 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7912 fix(CX-3295): Update upcoming auction results rail title
  src/app/Scenes/Home/Home.tsx
Labels: Jira Synced, Squash On Green
