Repository artsy/eigen, pull requests merged in 2022-11, with the labels that each got.

#7560 chore: Remove My Collection phase feature flags
  src/app/Scenes/MyCollection/Screens/Insights/MedianAuctionPriceRail.tsx
  src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsights.tests.tsx
  src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsights.tsx
  src/app/store/config/features.ts
Labels: Jira Synced, Squash On Green

#7564 style: minor visual glitches in Fair app
  src/app/Scenes/Artwork/Components/Questions.tsx
  src/app/Scenes/Fair/Components/FairHeader.tsx
Labels: Jira Synced

#7558 fix(CX-3096): Go back to artwork not MyCollection after sending request price estimate
  src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/RequestForPriceEstimate/RequestForPriceEstimateConfirmationScreen.tests.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/RequestForPriceEstimate/RequestForPriceEstimateConfirmationScreen.tsx
Labels: Jira Synced

#7565 fix: Always show message when a price estimate has been sent
  src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/RequestForPriceEstimate/RequestForPriceEstimateBanner.tests.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/RequestForPriceEstimate/RequestForPriceEstimateBanner.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtworkInsights.tsx
Labels: Jira Synced

#7569 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7567 feat(FX-4421): add "Mark all as read" button for activity screen
  src/app/Scenes/Activity/Activity.tsx
  src/app/Scenes/Activity/ActivityList.tsx
  src/app/Scenes/Activity/ActivityMarkAllAsReadSection.tests.tsx
  src/app/Scenes/Activity/ActivityMarkAllAsReadSection.tsx
  src/app/Scenes/Activity/ActivityTabPlaceholder.tsx
  src/app/Scenes/Activity/ActivityTabSubheader.tsx
Labels: Jira Synced, Squash On Green

#7571 chore: small improvements for "mark all as read" button
  src/app/Scenes/Activity/Activity.tsx
  src/app/Scenes/Activity/ActivityList.tsx
  src/app/Scenes/Activity/ActivityMarkAllAsReadSection.tsx
  src/app/Scenes/Activity/types.ts
  src/app/Scenes/Activity/utils/getNotificationTypes.ts
Labels: Squash On Green

#7551 refactor(FX-4392): auction artwork screen
  src/app/Scenes/Artwork/Artwork.tests.tsx
  src/app/Scenes/Artwork/Components/ArtworkDetails.tsx
  src/app/Scenes/Artwork/Components/ArtworkDetailsRow.tsx
  src/app/Scenes/Artwork/Components/ArtworkTombstone.tsx
  src/app/Scenes/Artwork/Components/RequestConditionReport.tsx
Labels: Jira Synced, Squash On Green

#7578 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7573 feat(FX-4374): new preference to allow opting out of partner show notifications
  src/app/Scenes/MyProfile/MyProfilePushNotifications.tests.tsx
  src/app/Scenes/MyProfile/MyProfilePushNotifications.tsx
Labels: Jira Synced

#7575 feat: Move all required fields to top in artwork form
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormMain.tsx
Labels: Jira Synced

#7134 feat: Allow users to create artists for My Collection
  .secrets.baseline
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtistAutosuggest.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtistSearchResult.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tests.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormArtist.tsx
  src/app/Scenes/Search/AutosuggestResults.tsx
  src/app/Scenes/Search/components/AutosuggestSearchResult.tsx
  src/app/Scenes/Search/components/SearchResultImage.tsx
  src/palette/elements/Avatar/Avatar.tsx
Labels: Jira Synced

#7581 feat: Initialize artist name input field in MyC upload flow
  .secrets.baseline
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtistAutosuggest.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tests.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormArtist.tsx
Labels: Jira Synced

#7587 fix(FX-4426): activity icon and copy changes
  src/app/Scenes/Activity/ActivityEmptyView.tsx
  src/app/Scenes/Home/Components/ActivityIndicator.tsx
  src/palette/helpers/text.ts
Labels: Squash On Green

#7586 chore: mark `AREnableActivity` as ready for release
  src/app/store/config/features.ts
Labels: Squash On Green

#7495 feat(FX-4280): add shipping and taxes section on artwork page
  .secrets.baseline
  src/app/Scenes/Artwork/Artwork.tests.tsx
  src/app/Scenes/Artwork/Artwork.tsx
  src/app/Scenes/Artwork/Components/CommercialInformation.tests.tsx
  src/app/Scenes/Artwork/Components/CommercialInformation.tsx
  src/app/Scenes/Artwork/Components/CommercialPartnerInformation.tests.tsx
  src/app/Scenes/Artwork/Components/CommercialPartnerInformation.tsx
  src/app/Scenes/Artwork/Components/ShippingAndTaxes.tests.tsx
  src/app/Scenes/Artwork/Components/ShippingAndTaxes.tsx
  src/app/store/config/features.ts
Labels: Jira Synced, Squash On Green

#7590 feat: add ability to refetch notifications for empty state
  src/app/Scenes/Activity/ActivityEmptyView.tsx
  src/app/Scenes/Activity/ActivityList.tsx
Labels: Squash On Green

#7579 refactor(FX-4424): cleanup cascading auction flags
  .secrets.baseline
  src/app/Components/ArtworkGrids/ArtworkGridItem.tests.tsx
  src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
  src/app/Components/Bidding/Components/Timer.tests.tsx
  src/app/Components/Bidding/Components/Timer.tsx
  src/app/Components/Bidding/Screens/ConfirmBid.tests.tsx
  src/app/Components/Bidding/Screens/ConfirmBid/index.tsx
  src/app/Components/RetryErrorBoundary.tests.tsx
  src/app/Scenes/Artwork/Components/CommercialInformation.tests.tsx
  src/app/Scenes/Artwork/Components/CommercialInformation.tsx
  src/app/Scenes/Home/Components/SalesRail.tests.tsx
  src/app/Scenes/Home/Components/SalesRail.tsx
  src/app/Scenes/Sale/Components/SaleHeader.tsx
  src/app/Scenes/Sale/SaleHeader.tests.tsx
  src/app/Scenes/Sale/helpers.ts
  src/app/Scenes/Sales/Components/SaleListItem.tests.tsx
  src/app/Scenes/Sales/Components/SaleListItem.tsx
  src/app/store/config/features.ts
Labels: Squash On Green

#7595 chore: hide shipping and taxes section if artwork is in auction
  src/app/Scenes/Artwork/Artwork.tests.tsx
  src/app/Scenes/Artwork/Artwork.tsx
Labels: Jira Synced

#7603 fix: Reset artist when discarding changes in My Collection form
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormMain.tsx
Labels: Jira Synced, Squash On Green

#7599 fix: My Collection artist select loading screen
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormArtist.tsx
Labels: Jira Synced

#7601 fix: Adjust Submission My Collection artwork image logic
  src/app/Scenes/MyCollection/Components/MyCollectionImageView.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkList/MyCollectionArtworkGridItem.tsx
  src/app/Scenes/SellWithArtsy/SellWithArtsyHome.tsx
  src/app/Scenes/SellWithArtsy/SubmitArtwork/UploadPhotos/UploadPhotosForm.tsx
  src/app/Scenes/SellWithArtsy/utils/submissionModelState.tsx
  src/app/store/migration.tests.ts
  src/app/store/migration.ts
Labels: Jira Synced, Squash On Green

#7584 feat: Initialize artwork title input when skipping artwork selection
  .secrets.baseline
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtistAutosuggest.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtworkAutosuggest.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtworkAutosuggestResults.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tests.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormArtwork.tsx
Labels: Jira Synced

#7604 fix: don't use webp on unsupported os versions
  src/app/Components/OpaqueImageView/createGeminiUrl.tsx
Labels: Squash On Green

#7605 fix: Revert "chore: only use metaphysicsExtensionsLoggerMiddleware on dev" #trivial
  src/app/relay/createEnvironment.ts
Labels: Squash On Green

#7607 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7608 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7609 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7610 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7606 fix(MOPLAT-490): Fix android unable to build issue
  ios/Podfile.lock
  package.json
  patches/react-native+0.66.5.patch
  yarn.lock
Labels: Jira Synced

#7613 feat: Update price estimate form copy
  src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/RequestForPriceEstimate/RequestForPriceEstimateForm.tsx
Labels: Jira Synced

#7602 feat(CX-2987): Reorder SWA submission flow
  src/app/Components/ArtistAutosuggest/ArtistAutosuggest.tests.tsx
  src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkDetails/ArtworkDetails.tests.tsx
  src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkDetails/ArtworkDetails.tsx
  src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkDetails/utils/createOrUpdateSubmission.ts
  src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkDetails/validation.ts
  src/app/Scenes/SellWithArtsy/SubmitArtwork/ContactInformation/ContactInformation.tests.tsx
  src/app/Scenes/SellWithArtsy/SubmitArtwork/ContactInformation/ContactInformation.tsx
  src/app/Scenes/SellWithArtsy/SubmitArtwork/SubmitArtwork.tests.tsx
  src/app/Scenes/SellWithArtsy/SubmitArtwork/SubmitArtwork.tsx
  src/app/Scenes/SellWithArtsy/SubmitArtwork/UploadPhotos/UploadPhotos.tests.tsx
  src/app/Scenes/SellWithArtsy/SubmitArtwork/UploadPhotos/UploadPhotos.tsx
  src/app/store/config/features.ts
Labels: Jira Synced

#7618 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7619 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7625 fix(setup): Invoke prettier via npx to avoid error during repo setup
  scripts/update-echo
Labels: Squash On Green

#7600 build(deps): bump @testing-library/jest-native from 5.0.0 to 5.1.2
  package.json
  yarn.lock
Labels: Squash On Green

#7632 fix(TX-877): remove modal navigation for bidding conditions of sale
  src/app/Components/Bidding/Screens/ConfirmBid/index.tsx
Labels: Jira Synced

#7629 feat: Adjust settings screen
  src/app/AppRegistry.tsx
  src/app/Scenes/MyProfile/MyProfileSettings.tsx
  src/app/navigation/routes.ts
Labels: Jira Synced

#7580 feat(CX-3052): Create Embedded Carousel
  images/homefeed-my-collection-inboarding-0.webp
  images/homefeed-my-collection-inboarding-0@2x.webp
  images/homefeed-my-collection-inboarding-0@3x.webp
  images/homefeed-my-collection-inboarding-1.webp
  images/homefeed-my-collection-inboarding-1@2x.webp
  images/homefeed-my-collection-inboarding-1@3x.webp
  src/app/Components/EmbeddedCarousel.tsx
  src/app/Scenes/Home/Components/HomeFeedOnboardingCard.tests.tsx
  src/app/Scenes/Home/Components/HomeFeedOnboardingCard.tsx
  src/app/Scenes/Home/Components/HomeFeedOnboardingRail.tests.tsx
  src/app/Scenes/Home/Components/HomeFeedOnboardingRail.tsx
  src/app/Scenes/Home/Components/SalesRail.tsx
  src/app/Scenes/Home/Home.tsx
  src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightsRail.tsx
  src/app/store/config/features.ts
Labels: Jira Synced, Squash On Green

#7576 feat(FX-4393): lot Details Section
  src/app/AppRegistry.tsx
  src/app/Components/Bidding/Components/Timer.tests.tsx
  src/app/Components/Bidding/Components/Timer.tsx
  src/app/Scenes/Artwork/Artwork.tsx
  src/app/Scenes/Artwork/Components/ArtworkExtraLinks/index.tests.tsx
  src/app/Scenes/Artwork/Components/ArtworkExtraLinks/index.tsx
  src/app/Scenes/Artwork/Components/ArtworkExtraLinks/partnerName.tsx
  src/app/Scenes/Artwork/Components/ArtworkLotDetails/ArtworkLotDetails.tests.tsx
  src/app/Scenes/Artwork/Components/ArtworkLotDetails/ArtworkLotDetails.tsx
  src/app/Scenes/Artwork/Components/ArtworkLotDetails/ArtworkLotDetailsRow.tsx
  src/app/Scenes/Artwork/Components/ArtworkLotDetails/LotCascadingEndTimesBanner.tsx
  src/app/Scenes/Artwork/Components/ArtworkLotDetails/LotCurrentBidInfo.tests.tsx
  src/app/Scenes/Artwork/Components/ArtworkLotDetails/LotCurrentBidInfo.tsx
  src/app/Scenes/Artwork/Components/ArtworkLotDetails/LotEndDateTime.tsx
  src/app/Scenes/Artwork/Components/ArtworkLotDetails/LotUpcomingLiveDateTime.tsx
  src/app/Scenes/Artwork/Components/ArtworkLotDetails/utils/formatLotDateTime.ts
  src/app/Scenes/Artwork/Components/ArtworkTombstone.tests.tsx
  src/app/Scenes/Artwork/Components/ArtworkTombstone.tsx
  src/app/Scenes/Artwork/Components/CommercialInformation.tsx
  src/app/Scenes/SaleFAQ/SaleFAQ.tests.tsx
  src/app/Scenes/SaleFAQ/SaleFAQ.tsx
  src/app/__fixtures__/ArtworkBidInfo.ts
  src/app/navigation/routes.ts
  src/app/store/config/features.ts
  src/palette/svgs/CloseCircleFillIcon.tsx
Labels: Jira Synced

#7641 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7640 chore: export recently added icon
  src/app/Scenes/Artwork/Components/ArtworkLotDetails/LotCurrentBidInfo.tsx
  src/palette/svgs/CloseCircleFillIcon.tsx
  src/palette/svgs/index.tsx
Labels: Squash On Green

#7637 build: simplify ci setup scripts
  .circleci/config.yml
  .nvmrc
Labels: Jira Synced, Squash On Green

#7642 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7644 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7634 ARReorderSWAArtworkSubmissionFlow
  src/app/store/config/features.ts
Labels: Jira Synced

#7633 feat(CX-3106): Track ContactInformation in SWA Flow
  src/app/Scenes/SellWithArtsy/SubmitArtwork/ContactInformation/ContactInformation.tests.tsx
  src/app/Scenes/SellWithArtsy/SubmitArtwork/SubmitArtwork.tsx
  src/app/Scenes/SellWithArtsy/utils/TrackingEvent.ts
Labels: Jira Synced

#7639 build: remove .env.ci
  HACKS.md
  android/app/build.gradle
  fastlane/Fastfile
  ios/Artsy.xcodeproj/project.pbxproj
  ios/Podfile.lock
  package.json
  patches/react-native-config+1.5.0.patch
  scripts/setup-env-for-artsy
  scripts/setup-env-for-ci
  scripts/setup-env-for-oss
  yarn.lock
Labels: Jira Synced

#7651 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7645 fix: Adjust artwork form submit logic
  .secrets.baseline
  src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tests.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx
Labels: Jira Synced

#7655 fix(MOPLAT-514): deeplinking for new-for-you
  android/app/src/main/AndroidManifest.xml
  src/app/Scenes/Home/Components/NewWorksForYouRail.tsx
  src/app/Scenes/Home/Home.tsx
  src/app/navigation/routes.ts
Labels: Jira Synced, Squash On Green

#7654 fix(MOPLAT-485): Layout issues when navigating to works-for-you from notification
  src/app/Components/ArticleCard.tsx
  src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
  src/app/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx
  src/app/Components/Home/ArtistRails/ArtistCard.tsx
  src/app/Scenes/NewWorksForYou/NewWorksForYou.tsx
  src/app/Scenes/ViewingRoom/ViewingRoomArtworks.tsx
  src/app/store/config/features.ts
  src/palette/elements/Cards/MediumCard.tsx
Labels: Jira Synced

#7649 feat(FX-44390: Display recent price ranges
  .secrets.baseline
  src/app/Components/ArtworkFilter/ArtworkFilterNavigator.tsx
  src/app/Components/ArtworkFilter/Filters/PriceRangeOptions.tests.tsx
  src/app/Components/ArtworkFilter/Filters/PriceRangeOptions.tsx
  src/app/store/AuthModel.tests.ts
  src/app/store/AuthModel.ts
  src/app/store/GlobalStoreModel.ts
  src/app/store/RecentPriceRangesModel.ts
  src/app/store/config/features.ts
  src/app/store/migration.tests.ts
  src/app/store/migration.ts
Labels: Jira Synced, Squash On Green

#7653 chore(CX-2805): redesign profile ui
  src/app/Scenes/MyProfile/MyProfileHeader.tsx
  src/app/Scenes/MyProfile/__tests__/MyProfileHeaderMyCollectionAndSavedWorks.tests.tsx
Labels: Jira Synced

#7614 feat(FX-4428): add "Consign with Artsy" section
  .secrets.baseline
  src/app/Scenes/Artwork/Artwork.tests.tsx
  src/app/Scenes/Artwork/Artwork.tsx
  src/app/Scenes/Artwork/Components/ArtworkConsignments.tests.tsx
  src/app/Scenes/Artwork/Components/ArtworkConsignments.tsx
  src/app/Scenes/Artwork/Components/ArtworkExtraLinks/index.tests.tsx
  src/app/Scenes/Artwork/Components/ArtworkExtraLinks/index.tsx
  src/app/Scenes/Artwork/Components/CommercialInformation.tests.tsx
  src/app/Scenes/Artwork/Components/CommercialInformation.tsx
Labels: Jira Synced, Squash On Green

#7623 feat(CX-3054): add full screen modal carousel
  images/my-collection-onboarding-image-1.webp
  images/my-collection-onboarding-image-1@2x.webp
  images/my-collection-onboarding-image-1@3x.webp
  images/my-collection-onboarding-image-2.webp
  images/my-collection-onboarding-image-2@2x.webp
  images/my-collection-onboarding-image-2@3x.webp
  images/my-collection-onboarding-image-3.webp
  images/my-collection-onboarding-image-3@2x.webp
  images/my-collection-onboarding-image-3@3x.webp
  ios/Podfile.lock
  package.json
  src/app/Components/StepWithImage/StepWithImage.tsx
  src/app/Icons/HomeFeedOnboarding/PhoneIcon.tsx
  src/app/Icons/HomeFeedOnboarding/SellWithEaseIcon.tsx
  src/app/Scenes/Home/Components/HomeFeedModalCarousel/HomeFeedModalCarousel.tests.tsx
  src/app/Scenes/Home/Components/HomeFeedModalCarousel/HomeFeedModalCarousel.tsx
  src/app/Scenes/Home/Components/HomeFeedModalCarousel/HomeFeedModalCarouselContainer.tsx
  src/app/Scenes/Home/Components/HomeFeedModalCarousel/HomeFeedModalCarouselScreenWrapper.tsx
  src/app/Scenes/Home/Components/HomeFeedOnboardingCard.tests.tsx
  src/app/Scenes/Home/Components/HomeFeedOnboardingCard.tsx
  src/app/Scenes/Home/Components/HomeFeedOnboardingRail.tests.tsx
  src/app/Scenes/Home/Components/HomeFeedOnboardingRail.tsx
  src/app/Scenes/SellWithArtsy/Components/HowItWorks.tsx
  src/palette/elements/index.tsx
  src/storybook/storybook.requires.js
  yarn.lock
Labels: Jira Synced

#7647 fix: Add min height to simple header for font scaling
  src/app/Components/PageWithSimpleHeader.tsx
  src/app/navigation/BackButton.tsx
Labels: Squash On Green

#7668 fix(CX-2078): do not deep link privacy and terms of conditions links
  android/app/src/main/AndroidManifest.xml
Labels: Jira Synced, Squash On Green

#7666 fix(CX-2486): show network status during the Onboarding
  ios/Artsy.xcodeproj/project.pbxproj
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: Jira Synced, Squash On Green

#7665 fix: deeplink fix for partner shows and works
  src/app/Scenes/Partner/Partner.tsx
  src/app/navigation/routes.tests.ts
  src/app/navigation/routes.ts
Labels: Jira Synced

#7669 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7667 fix: Do not allow submiting the artwork form multiple times
  src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx
Labels: Jira Synced

#7676 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7677 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7672 chore(FX-4442): change copies for "Saved" tab
  src/app/Scenes/Favorites/FavoriteArtworks.tsx
Labels: Jira Synced

#7681 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7683 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7673 fix: change password
  src/app/Scenes/MyAccount/MyAccountEditPassword.tsx
Labels: Jira Synced

#7687 feat(CX-3158): tracking MyCollection HomeFeed onboarding
  src/app/Scenes/Home/Components/HomeFeedModalCarousel/HomeFeedModalCarousel.tests.tsx
  src/app/Scenes/Home/Components/HomeFeedModalCarousel/HomeFeedModalCarouselContainer.tsx
  src/app/Scenes/Home/Components/HomeFeedOnboardingCard.tsx
  src/app/Scenes/Home/Components/HomeFeedOnboardingRail.tests.tsx
  src/app/Scenes/Home/Components/HomeFeedOnboardingRail.tsx
Labels: Jira Synced

#7675 fix(CX-2953): adjust About Artwork section
  src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkAbout/MyCollectionArtworkAboutWork.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkAbout/MyCollectionArtworkPurchaseDetails.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/Field.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtworkAbout.tests.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtworkAbout.tsx
Labels: Jira Synced

#7656 chore(CX-3142): show loading spinner while social login
  .secrets.baseline
  src/app/Components/Modals/LoadingModal.tsx
  src/app/Scenes/Onboarding/OnboardingCreateAccount/OnboardingSocialPick.tests.tsx
  src/app/Scenes/Onboarding/OnboardingSocialPick.tsx
  src/app/store/AuthModel.tests.ts
  src/app/store/AuthModel.ts
  src/app/store/migration.tests.ts
  src/setupJest.ts
Labels: Jira Synced

#7696 chore: set artists not in artsy ff as ready to be released
  src/app/store/config/features.ts
Labels: Squash On Green

#7688 fix: change partner overview query
  src/app/Scenes/Partner/Components/PartnerOverview.tests.tsx
  src/app/Scenes/Partner/Components/PartnerOverview.tsx
Labels: Jira Synced

#7648 feat: Large New Works Rail AB test
  src/app/Scenes/Home/Components/NewWorksForYouRail.tsx
  src/app/store/config/features.ts
Labels: Jira Synced

#7589 feat(NX-3318): Conditionally display "Bids" or "Inquiries" on the Inbox.
  src/app/Containers/Inbox.tests.tsx
  src/app/Containers/Inbox.tsx
Labels: Jira Synced

#7670 feat(FX-4438): Show curated collections on search screen
  src/app/Scenes/Search/CuratedCollectionItem.tsx
  src/app/Scenes/Search/CuratedCollections.tests.tsx
  src/app/Scenes/Search/CuratedCollections.tsx
  src/app/Scenes/Search/Search.tsx
  src/app/store/config/features.ts
Labels: Jira Synced

#7701 fix: second flaky test
  src/app/Scenes/Artwork/Artwork.tests.tsx
Labels: Squash On Green

#7657 feat(FX-4440): Pin Collector Profile-sourced price range as the last "recent" price range
  src/app/Components/ArtworkFilter/Filters/PriceRangeOptions.tests.tsx
  src/app/Components/ArtworkFilter/Filters/PriceRangeOptions.tsx
  src/app/Scenes/Search/UserPrefsModel.tsx
  src/app/store/RecentPriceRangesModel.ts
  src/app/store/migration.tests.ts
  src/app/store/migration.ts
Labels: Jira Synced

#7714 feat(FX-4446): tracks tap on curated collection
  src/app/Scenes/Search/CuratedCollectionItem.tsx
  src/app/Scenes/Search/CuratedCollections.tests.tsx
  src/app/Scenes/Search/CuratedCollections.tsx
Labels: Jira Synced

#7708 feat: Add save icon PLPs
  src/app/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
  src/app/Components/ArtworkGrids/ArtworkGridItem.tests.tsx
  src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
  src/app/Components/ArtworkGrids/GenericGrid.tests.tsx
  src/app/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx
  src/app/Components/ArtworkGrids/LotCloseInfo.tsx
  src/app/Scenes/Artwork/Components/AboutArtist.tests.tsx
  src/app/store/config/features.ts
  src/app/tests/renderWithWrappers.tsx
Labels: Jira Synced, Squash On Green

#7702 feat(FX-4452): display trending artists
  src/app/Components/Home/ArtistRails/ArtistCard.tsx
  src/app/Scenes/Search/Search.tsx
  src/app/Scenes/Search/TrendingArtists.tests.tsx
  src/app/Scenes/Search/TrendingArtists.tsx
  src/app/Scenes/Search/components/TrendingArtistCard.tsx
  src/app/Scenes/Search/components/placeholders/SearchPlaceholder.tsx
  src/app/Scenes/Search/useDisplayCuratedCollections.ts
  src/app/store/config/features.ts
Labels: Jira Synced, Squash On Green

#7690 feat(CX-2325): Make Scrolling from StickyTabPage Header Possible
  src/app/Components/StickyTabPage/StaticHeaderContainer.tsx
  src/app/Components/StickyTabPage/StickyTabPage.tsx
  src/app/Components/StickyTabPage/StickyTabPageContext.tsx
  src/app/Components/StickyTabPage/StickyTabPageFlatList.tsx
  src/app/store/config/features.ts
Labels: Jira Synced, Squash On Green

#7719 Fix(CX-3099): Do not display Banner after submitting a MyCollectionArtwork
  src/app/Scenes/SellWithArtsy/SubmitArtwork/SubmitArtwork.tests.tsx
  src/app/Scenes/SellWithArtsy/SubmitArtwork/SubmitArtwork.tsx
Labels: Jira Synced

#7724 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7710 fix(CX-2493): Fix Photo Added in Edit mode not updated on MyCollectionArtwork
  src/app/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionImageView.tsx
  src/app/Scenes/MyCollection/MyCollection.tsx
  src/app/Scenes/MyCollection/MyCollectionArtworks.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionArtworkHeader.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkList/MyCollectionArtworkGridItem.tsx
  src/setupJest.ts
Labels: Jira Synced

#7723 refactor: add reusable component that displays artwork images compositions
  src/app/Components/GenericArtistSeriesRail.tsx
  src/app/Components/Home/CardRailCard.tsx
  src/app/Components/ThreeUpImageLayout.tsx
  src/app/Scenes/Collection/Components/CollectionHubsRails/ArtistSeries/CollectionArtistSeriesRail.tests.tsx
  src/app/Scenes/Home/Components/CollectionsRail.tsx
  src/app/Scenes/Home/Components/FairsRail.tsx
  src/app/Scenes/Home/Components/SalesRail.tsx
Labels: Squash On Green

#7725 chore: use large card on tablets, small card on phones for trending artist rails
  src/app/Scenes/Search/Search.tests.tsx
  src/app/Scenes/Search/TrendingArtists.tsx
  src/app/Scenes/Search/components/TrendingArtistCard.tsx
  src/app/Scenes/Search/components/placeholders/SearchPlaceholder.tsx
  src/app/store/config/features.ts
Labels: Squash On Green

#7729 chore(FX-4471): Add analytics for the recent price ranges
  src/app/Components/ArtworkFilter/Filters/PriceRangeOptions.tests.tsx
  src/app/Components/ArtworkFilter/Filters/PriceRangeOptions.tsx
Labels: Jira Synced

#7728 feat(CX-2975): MyC Edit Artwork Page - Replace the "Delete Artwork" CTA with a Red link CTA [app]
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormMain.tsx
Labels: Jira Synced

#7731 chore: disable empty names onboarding creating account
  src/app/Scenes/Onboarding/OnboardingCreateAccount/OnboardingCreateAccount.tsx
Labels: Jira Synced, Squash On Green

#7732 chore: decreased padding between the histogram and the latest price ranges
  src/app/Components/ArtworkFilter/Filters/PriceRangeOptions.tsx
Labels: Squash On Green

#7734 fix(CX-3162): change email address from sell@artsymail.com to sell@artsy.net
  src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionSellingWithartsyFAQ.tsx
Labels: Jira Synced

#7733 refactor: analytics for search screen
  src/app/Scenes/Search/CuratedCollectionItem.tsx
  src/app/Scenes/Search/CuratedCollections.tests.tsx
  src/app/Scenes/Search/TrendingArtists.tests.tsx
  src/app/Scenes/Search/TrendingArtists.tsx
  src/app/Scenes/Search/components/TrendingArtistCard.tsx
Labels: Jira Synced, Squash On Green

#7730 fix: round up height/width sizes that we send to gemini
  src/app/Components/OpaqueImageView/createGeminiUrl.tsx
Labels: Jira Synced

#7727 chore(FX-4470): Convert Artsy Curated Collections list into a rail
  src/app/Scenes/Search/CuratedCollectionItem.tsx
  src/app/Scenes/Search/CuratedCollections.tsx
  src/app/Scenes/Search/Search.tests.tsx
  src/app/Scenes/Search/Search.tsx
  src/app/Scenes/Search/components/placeholders/SearchPlaceholder.tsx
Labels: Jira Synced

#7720 fix: handle marketing deeplinks on typescript side
  src/app/navigation/navigate.tests.tsx
  src/app/navigation/navigate.ts
Labels: Squash On Green

#7736 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7706 fix: SignUp continue with the link
  src/app/Scenes/Onboarding/OnboardingSocialPick.tsx
  src/app/store/AuthModel.ts
Labels: Jira Synced

#7741 chore: add the missed bottom offset for the trending artists rail
  src/app/Scenes/Search/TrendingArtists.tsx
Labels: Squash On Green

#7703 docs: testing docs 🎉
  EXAMPLES.md
  docs/best_practices.md
  docs/testing.md
  src/app/tests/extractText.ts
  src/app/tests/setupTestWrapper.tsx
  src/app/tests/waitUntil.ts
Labels: Squash On Green

#7745 docs: clear cache on troubleshooting
  docs/troubleshooting.md
Labels: Squash On Green

#7744 feat(FX-4274): Artwork screen header
  src/app/AppRegistry.tsx
  src/app/Scenes/Artwork/Artwork.tsx
  src/app/Scenes/Artwork/Components/ArtworkActions.tsx
  src/app/Scenes/Artwork/Components/ArtworkScreenHeader.tests.tsx
  src/app/Scenes/Artwork/Components/ArtworkScreenHeader.tsx
  src/app/Scenes/Artwork/Components/ArtworkScreenHeaderCreateAlert.tsx
  src/app/navigation/navigate.tests.tsx
  src/palette/atoms/BackButton/BackButton.tsx
Labels: Jira Synced

#7737 feat(CX-3186): add images gallery to android
  package.json
  patches/react-native-gesture-handler+2.5.0.patch
  src/app/Scenes/Artwork/Components/ImageCarousel/FullScreen/ImageCarouselFullScreen.tests.tsx
  src/app/Scenes/Artwork/Components/ImageCarousel/FullScreen/ImageCarouselFullScreenAndroid.tsx
  src/app/Scenes/Artwork/Components/ImageCarousel/FullScreen/ImageZoomViewAndroid.tsx
  src/app/Scenes/Artwork/Components/ImageCarousel/ImageCarousel.tests.tsx
  src/app/Scenes/Artwork/Components/ImageCarousel/ImageCarousel.tsx
  src/app/Scenes/Artwork/Components/ImageCarousel/ImageCarouselContext.tests.tsx
  src/app/Scenes/Artwork/Components/ImageCarousel/ImageCarouselContext.tsx
  src/app/Scenes/Artwork/Components/ImageCarousel/ImageCarouselEmbedded.tests.tsx
  src/app/Scenes/Artwork/Components/ImageCarousel/ImageCarouselEmbedded.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionArtworkHeader.tsx
  src/app/store/config/features.ts
  yarn.lock
Labels: Jira Synced

#7750 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7742 fix(CX-3188): padding issue on large rail
  src/app/Components/Artist/ArtistArtworks/ArtistNotableWorksRail.tests.tsx
  src/app/Components/ArtworkRail/ArtworkRailCard.tsx
  src/app/Components/ArtworkRail/LargeArtworkRail.tsx
  src/app/Components/ArtworkRail/SmallArtworkRail.tsx
  src/app/Scenes/Home/Components/HomeHeader.tsx
  src/app/Scenes/Home/Home.tsx
  src/app/Scenes/Sale/Components/NewBuyNowArtworksRail.tests.tsx
Labels: Jira Synced

#7753 chore: add save icon to artwork grids
  src/app/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
  src/app/Components/ArtworkGrids/ArtworkGridItem.tests.tsx
  src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
  src/app/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx
Labels: Jira Synced

#7700 fix: android crash on image picker
  ios/Podfile.lock
  package.json
  patches/react-native-image-crop-picker+0.38.1.patch
  src/setupJest.ts
  yarn.lock
Labels: Jira Synced
