Repository artsy/eigen, pull requests merged in 2022-07, with the labels that each got.

#7014 chore(deps): 🪦 deprecate enzyme 🪦
  HACKS.md
  docs/analytics_and_tracking.md
  docs/best_practices.md
  package.json
  patches/@wojtekmaj+enzyme-adapter-react-17+0.6.6.patch
  src/app/tests/MockRelayRenderer.tests.tsx
  src/app/tests/MockRelayRenderer.tsx
  src/app/tests/MockRelayRendererFixtures.tsx
  src/app/tests/renderRelayTree.tests.tsx
  src/app/tests/renderRelayTree.tsx
  src/app/tests/renderUntil.tests.tsx
  src/app/tests/renderUntil.tsx
  src/app/utils/track/index.tsx
  src/setupJest.ts
  yarn.lock
Labels: refinathon

#7005 chore: simplify error name for relay errors
  src/app/relay/createEnvironment.ts
  src/app/relay/middlewares/errorMiddleware.tests.ts
  src/app/relay/middlewares/errorMiddleware.ts
Labels: Jira Synced, refinathon, hack11

#7018 build: no need for resolutions
  package.json
Labels: refinathon, hack11

#7019 docs: tiny cleanup after enzyme
  dangerfile.ts
Labels: refinathon, hack11

#7027 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7026 feat [CX-2641]: Update collector profile header design
  src/app/Scenes/MyCollection/MyCollection.tsx
  src/app/Scenes/MyProfile/MyProfileHeader.tsx
Labels: Jira Synced

#7022 refactor: remove STRICTNESS_MIGRATION
  src/app/Components/Artist/ArtistShows/VariableSizeShowsList.tests.tsx
  src/app/Components/ArtistListItem.tsx
  src/app/Components/ArtworkFilter/FilterModal.tests.tsx
  src/app/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx
  src/app/Components/Bidding/BidFlow.tests.tsx
  src/app/Components/Bidding/Components/BidInfoRow.tsx
  src/app/Components/Bidding/Components/Containers.tsx
  src/app/Components/Bidding/Components/Divider.tsx
  src/app/Components/Bidding/Components/Icon.tsx
  src/app/Components/Bidding/Components/PaymentInfo.tests.tsx
  src/app/Components/Bidding/Components/PaymentInfo.tsx
  src/app/Components/Bidding/Elements/Flex.tsx
  src/app/Components/Bidding/Elements/Image.tsx
  src/app/Components/Bidding/Screens/BidResult.tsx
  src/app/Components/Bidding/Screens/ConfirmBid.tests.tsx
  src/app/Components/Bidding/Screens/ConfirmBid/PriceSummary.tsx
  src/app/Components/Bidding/Screens/ConfirmBid/index.tsx
  src/app/Components/Bidding/Screens/Registration.tsx
  src/app/Components/Countdown/StateManager.tsx
  src/app/Components/Countdown/Ticker.tsx
  src/app/Components/EntityList/index.tests.tsx
  src/app/Components/EntityList/index.tsx
  src/app/Components/Gene/Header.tsx
  src/app/Components/Lists/ShowItemRow.tsx
  src/app/Components/Markdown.tests.tsx
  src/app/Components/Modal.tsx
  src/app/Components/ReadMore.tsx
  src/app/Components/RelatedArtists/RelatedArtist.tsx
  src/app/Components/Show/ShowArtistsPreview.tsx
  src/app/Components/Show/ShowArtworksPreview.tsx
  src/app/Components/States/ZeroState.tests.tsx
  src/app/Components/StickyTabPage/reanimatedHelpers.ts
  src/app/Components/WorksForYou/Notification.tests.tsx
  src/app/Containers/WorksForYou.tests.tsx
  src/app/Scenes/Artwork/Components/ArtworkActions.tests.tsx
  src/app/Scenes/Artwork/Components/ArtworkActions.tsx
  src/app/Scenes/Artwork/Components/ArtworkTombstone.tsx
  src/app/Scenes/Artwork/Components/RequestConditionReport.tsx
  src/app/Scenes/Collection/Screens/CollectionHeader.tsx
  src/app/Scenes/Favorites/FavoriteArtworks.tsx
  src/app/Scenes/Favorites/FavoriteCategories.tsx
  src/app/Scenes/Favorites/FavoriteShows.tsx
  src/app/Scenes/Home/Components/SalesRail.tests.tsx
  src/app/Scenes/Inbox/Components/Conversations/UpdateConversation.ts
  src/app/Scenes/Map/Bucket.tests.ts
  src/app/Scenes/Map/MapRenderer.tsx
  src/app/relay/middlewares/cacheMiddleware.ts
  src/app/utils/__legacy_do_not_use__navigator-ios-shim.tsx
  src/palette/animation/CssTransition.tsx
Labels: Squash On Green, refinathon

#7029 fix [CX-2555]: update lock icon in my collection empty state screen
  images/lock.webp
  images/lock@2x.webp
  images/lock@3x.webp
  src/app/Scenes/MyCollection/MyCollectionArtworks.tsx
Labels: Jira Synced, Squash On Green

#7030 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7033 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7039 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7042 fix: minor ui fixes after sans/serif removal
  src/app/Scenes/Artwork/Components/ArtworkExtraLinks/AuctionFaqSection.tsx
Labels: Squash On Green

#7045 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7046 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7049 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#6736 feat: add preference to allow opting out of viewing room notifications
  src/app/Scenes/MyProfile/MyProfilePushNotifications.tests.tsx
  src/app/Scenes/MyProfile/MyProfilePushNotifications.tsx
Labels: Squash On Green

#7050 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7052 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7054 feat(MOPLAT-189): support mailto links for SDK 30 and above
  android/app/src/main/AndroidManifest.xml
Labels: Jira Synced

#7057 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7058 fix(NX-3201): changed modal title from Buy Now to Purchase
  src/app/Scenes/Artwork/Components/CommercialButtons/BuyNowButton.tsx
  src/app/Scenes/Artwork/Components/CommercialButtons/CommercialButtons.tests.tsx
Labels: Jira Synced

#7059 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7060 fix: small adjustment on text style after migrating to text from serif
  src/app/Scenes/Artwork/Components/ArtworkExtraLinks/index.tsx
Labels: Squash On Green

#7061 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7056 fix(CX-2661): Store Category and Medium Fields Properly
  src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkAbout/MyCollectionArtworkAboutWork.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/CategoryPicker.tests.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/CategoryPicker.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tests.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormArtwork.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormMain.tests.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormMain.tsx
  src/app/utils/artworkMediumCategories.tests.ts
  src/app/utils/artworkMediumCategories.ts
Labels: Jira Synced

#7065 fix(NX-3191): separate functionality for close and go to inbox button
  src/app/Scenes/Inbox/Components/Conversations/OfferSubmittedModal.tests.tsx
  src/app/Scenes/Inbox/Components/Conversations/OfferSubmittedModal.tsx
Labels: Jira Synced

#7064 fix (CX-2666): Don't show section title in MyCollection Insights when the data is not available
  src/app/Scenes/MyCollection/Screens/Insights/AverageAuctionPriceRail.tsx
Labels: Jira Synced

#6982 fix(CX-2172): refresh control rendering too high in MyC, MyC Insights, Saved
  src/app/Components/States/ZeroState.tsx
  src/app/Components/StickyTabPage/StickTabPageRefreshControl.tsx
  src/app/Scenes/Favorites/FavoriteArtists.tsx
  src/app/Scenes/Favorites/FavoriteArtworks.tsx
  src/app/Scenes/Favorites/FavoriteCategories.tsx
  src/app/Scenes/Favorites/FavoriteShows.tsx
  src/app/Scenes/MyCollection/MyCollection.tsx
  src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsights.tsx
  src/app/Scenes/MyProfile/MyProfileHeader.tsx
  src/app/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx
Labels: Jira Synced

#7069 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7071 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7074 fix(FX-4085): horizontal offset for popcorn auction banner
  src/app/Scenes/Artwork/Components/ArtworkTombstone.tsx
  src/app/Scenes/Artwork/Components/CascadingEndTimesBanner.tsx
  src/app/Scenes/Sale/Sale.tsx
Labels: Jira Synced, Squash On Green

#7070 feat: onboarding preparation pr
  src/app/Scenes/Onboarding/Onboarding.tsx
  src/app/Scenes/Onboarding/OnboardingPersonalization2/Hooks/useOnboardingContext.tsx
  src/app/Scenes/Onboarding/OnboardingPersonalization2/OnboardingPersonalization2.tsx
  src/app/Scenes/Onboarding/OnboardingPersonalization2/OnboardingPersonalizationWelcome.tests.tsx
  src/app/Scenes/Onboarding/OnboardingPersonalization2/OnboardingPersonalizationWelcome.tsx
  src/app/Scenes/Onboarding/OnboardingPersonalization2/config.tests.ts
  src/app/Scenes/Onboarding/OnboardingPersonalization2/config.ts
  src/app/store/config/features.ts
  src/app/utils/WorkflowEngine/WorkflowEngine.tests.tsx
  src/app/utils/WorkflowEngine/WorkflowEngine.tsx
Labels: Jira Synced

#7066 feat(FX-4089): replace `saleArtworksConnection` with `viewer.artworksConnection` for Auction screen
  src/app/Components/ArtworkFilter/ArtworkFilterHelpers.ts
  src/app/Components/ArtworkFilter/ArtworkFilterStore.tsx
  src/app/Components/ArtworkFilter/Filters/ArtistIDsOptionsScreen.tsx
  src/app/Components/ArtworkFilter/Filters/EstimateRangeOptions.tsx
  src/app/Components/ArtworkFilter/Filters/SortOptions.tsx
  src/app/Scenes/Sale/Components/NewSaleLotsList.tests.tsx
  src/app/Scenes/Sale/Components/NewSaleLotsList.tsx
  src/app/Scenes/Sale/Sale.tsx
  src/app/store/config/features.ts
Labels: Jira Synced

#7082 docs: Update README.md
  docs/README.md
Labels: Squash On Green

#7087 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7088 fix(NX-3243): adjust font size elements from md text
  src/app/Components/ReadMore.tsx
  src/app/Scenes/Inbox/Components/Conversations/Messages.tests.tsx
  src/app/Scenes/Inbox/Components/Conversations/OrderUpdate.tsx
  src/app/utils/renderMarkdown.tsx
  src/palette/elements/Text/LinkText.tsx
Labels: Jira Synced

#7092 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7093 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7094 fix: widget test missing prop
  ios/ArtsyTests/ArtsyWidget/ArtworkTests.swift
Labels: Merge On Green

#7081 feat(NX-3183): adjust order and components of Artwork screen
  src/app/Scenes/Artwork/Artwork.tsx
  src/app/Scenes/Artwork/Components/PartnerLink.tests.tsx
  src/app/Scenes/Artwork/Components/PartnerLink.tsx
  src/app/Scenes/Artwork/Components/Questions.tests.tsx
  src/app/Scenes/Artwork/Components/Questions.tsx
Labels: Jira Synced

#7096 feat(FX-4104): Hide the Featured Artists section when showFeaturedArtists is false
  src/app/Scenes/Collection/Collection.tests.tsx
  src/app/Scenes/Collection/Collection.tsx
Labels: Jira Synced

#7072 fix: view in room crashed on second modal spawn
  HACKS.md
  ios/Artsy.xcodeproj/project.pbxproj
  ios/Artsy/NativeModules/ARTNativeScreenPresenterModule.m
  ios/Podfile
  ios/Podfile.lock
Labels: Jira Synced

#7104 chore: make `AREnableArtworksConnectionForAuction` as ready for release
  src/app/store/config/features.ts
Labels: Squash On Green

#7108 fix: virtualized list should never be nested inside scrollview
  src/app/Scenes/Onboarding/OnboardingPersonalization/OnboardingPersonalization.tsx
Labels: Squash On Green

#7098 feat(GRO-1106): add Welcome screen and images
  images/OnboardingImage0AdesinaPaintingOfRechel.webp
  images/OnboardingImage0AdesinaPaintingOfRechel@2x.webp
  images/OnboardingImage0AdesinaPaintingOfRechel@3x.webp
  images/OnboardingImage1KatzYellowFlags.webp
  images/OnboardingImage1KatzYellowFlags@2x.webp
  images/OnboardingImage1KatzYellowFlags@3x.webp
  images/OnboardingImage2SuperFutureKidHazyDaisy2022.webp
  images/OnboardingImage2SuperFutureKidHazyDaisy2022@2x.webp
  images/OnboardingImage2SuperFutureKidHazyDaisy2022@3x.webp
  images/OnboardingImage3WangTheSnowflakeThatComesAlive.webp
  images/OnboardingImage3WangTheSnowflakeThatComesAlive@2x.webp
  images/OnboardingImage3WangTheSnowflakeThatComesAlive@3x.webp
  images/OnboardingImage4AndyWarholCow.webp
  images/OnboardingImage4AndyWarholCow@2x.webp
  images/OnboardingImage4AndyWarholCow@3x.webp
  src/app/Scenes/Onboarding/OnboardingPersonalization2/OnboardingPersonalization2.tsx
  src/app/Scenes/Onboarding/OnboardingPersonalization2/OnboardingPersonalizationWelcome.tsx
Labels: Jira Synced, Squash On Green

#7111 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7112 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7106 feat(FX-4106): use `artworksConnection` for auctions rail on home page
  src/app/Scenes/Home/Components/SalesRail.tests.tsx
  src/app/Scenes/Home/Components/SalesRail.tsx
Labels: Jira Synced

#7101 feat(TX-521): Erik/tx conversation support offers
  src/app/Components/ConnectivityBanner.tsx
  src/app/Containers/Inquiry.tsx
  src/app/Scenes/Inbox/Components/ActiveBids/ActiveBid.tsx
  src/app/Scenes/Inbox/Components/Conversations/ConversationCTA.tsx
  src/app/Scenes/Inbox/Components/Conversations/OrderUpdate.tests.tsx
  src/app/Scenes/Inbox/Components/Conversations/OrderUpdate.tsx
  src/app/Scenes/Inbox/Screens/ConversationDetails.tsx
  src/app/Scenes/MyBids/Components/SaleInfo.tsx
  src/app/Scenes/MyBids/SaleInfo.tests.tsx
  src/palette/Theme.tsx
Labels: Jira Synced

#7115 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7121 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#7053 Feat [CX-2642]: Add career highlights rail inside My Collection Insights
  images/career-highlights-promo-background-image.webp
  images/career-highlights-promo-background-image@2x.webp
  images/career-highlights-promo-background-image@3x.webp
  src/app/Scenes/MyCollection/Screens/Insights/AverageSalePriceAtAuction.tsx
  src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightCard.tsx
  src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightsRail.tests.tsx
  src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightsRail.tsx
  src/app/Scenes/MyCollection/Screens/Insights/MarketSignalsSectionHeader.tsx
  src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsights.tsx
  src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsightsOverview.tsx
  src/app/store/GlobalStore.tsx
  src/app/store/GlobalStoreModel.ts
  src/app/store/MyCollectionCareerHighlightsModel.ts
  src/app/store/migration.ts
Labels: Jira Synced

#7127 feat: add assets for loading screens
  images/CohnMakeAMountain.webp
  images/CohnMakeAMountain@2x.webp
  images/CohnMakeAMountain@3x.webp
  images/HirstTheWonder.webp
  images/HirstTheWonder@2x.webp
  images/HirstTheWonder@3x.webp
Labels: Jira Synced

#7128 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green
