Repository artsy/eigen, pull requests merged in 2023-11, with the labels that each got.

#9520 chore: rename rn patch after downgrade #trivial
  patches/react-native+0.70.13.patch
Labels: Squash On Green

#9514 feat: Add artist series filter to artist screen
  src/app/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
  src/app/Components/ArtworkFilter/ArtworkFilterHelpers.ts
  src/app/Components/ArtworkFilter/ArtworkFilterNavigator.tsx
  src/app/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx
  src/app/Components/ArtworkFilter/ArtworkFilterStore.tsx
  src/app/Components/ArtworkFilter/ArtworkFiltersStore.tests.tsx
  src/app/Components/ArtworkFilter/Filters/ArtistSeriesOptions.tests.tsx
  src/app/Components/ArtworkFilter/Filters/ArtistSeriesOptions.tsx.tsx
  src/app/Components/ArtworkFilter/types.ts
  src/app/store/config/features.ts
Labels: Jira Synced, Squash On Green

#9523 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9524 chore: prepare for 8.26.0
  app.json
Labels: Squash On Green

#9533 fix: typescript issue on artworks list
  src/app/Scenes/ArtworkList/ArtworkListEmptyState.tsx
Labels: Squash On Green

#9532 fix: Scroll to artwork grid
  src/app/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
Labels: Squash On Green

#9534 fix(flaky test): give all the live auction snapshots a tolerance
  ios/ArtsyTests/View_Controller_Tests/Live_Auction/LiveAuctionLotViewControllerTests.swift
Labels: Squash On Green

#9536 chore(codepush): disable codepush dialog
  docs/screenshots/codepush-update-dialog.jpeg
  docs/using_codepush.md
  src/app/system/codepush.ts
Labels: Jira Synced

#9537 fix(DIA-198): add better disabled control on login via email screen
  src/app/Scenes/Onboarding/OnboardingLogin.tests.tsx
  src/app/Scenes/Onboarding/OnboardingLogin.tsx
Labels: Jira Synced

#9535 chore: address some non-null assertions
  src/app/Components/Artist/Articles/Article.tsx
  src/app/Components/ContextMenu/ContextMenuArtwork.tsx
  src/app/Components/PartnerEntityHeader.tsx
  src/app/Scenes/Activity/hooks/useMarkNotificationsAsSeen.ts
  src/app/Scenes/Activity/mutations/useMarkNotificationAsRead.ts
  src/app/Scenes/Activity/utils/navigateToActivityItem.ts
  src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsTabs/ArtQuizArtist.tsx
  src/app/Scenes/Article/Components/Sections/ArticleSectionImageSet.tsx
  src/app/Scenes/ArtistSeries/ArtistSeriesArtworks.tsx
  src/app/Scenes/ArtistSeries/ArtistSeriesHeader.tsx
  src/app/Scenes/Artwork/Components/ArtworkExtraLinks/index.tsx
  src/app/Scenes/Artwork/Components/ArtworkMakerTitle.tsx
  src/app/Scenes/Artwork/Components/CommercialButtons/InquiryModal.tsx
  src/app/Scenes/Artwork/Components/OtherWorks/OtherWorks.tsx
  src/app/Scenes/Artwork/Components/PartnerCard.tsx
  src/app/Scenes/ArtworkList/views/EditArtworkListView/EditArtworkListView.tsx
  src/app/Scenes/BottomTabs/BottomTabsButton.tsx
  src/app/Scenes/City/CityFairList.tsx
  src/app/Scenes/City/Components/Event/index.tsx
  src/app/Scenes/City/cityTabs.ts
  src/app/Scenes/Fair/Components/FairExhibitorRail.tsx
  src/app/Scenes/Home/Components/ShowsRail.tsx
  src/app/Scenes/Inbox/Components/Conversations/ConversationCTA.tsx
  src/app/Scenes/Inbox/Components/Conversations/Conversations.tsx
  src/app/Scenes/MyBids/Components/Lot.tsx
  src/app/Scenes/MyBids/MyBids.tsx
  src/app/Scenes/MyCollection/MyCollection.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtworkAutosuggestResults.tsx
  src/app/Scenes/MyCollection/Screens/CollectedArtistsPrivacy/MyCollectionCollectedArtistsPrivacyArtistsList.tsx
  src/app/Scenes/Onboarding/OnboardingQuiz/OnboardingMarketingCollection.tsx
  src/app/Scenes/Sale/Components/BuyNowArtworksRail.tsx
  src/app/Scenes/Sale/Components/NewBuyNowArtworksRail.tsx
  src/app/Scenes/Sale/Components/SaleArtworkList.tsx
  src/app/Scenes/Sale/Components/SaleArtworkListItem.tsx
  src/app/Scenes/SavedSearchAlertsList/Components/SavedSearchesList.tsx
  src/app/Scenes/SellWithArtsy/Components/SellWithArtsyRecentlySold.tsx
  src/app/Scenes/Show/Components/ShowViewingRoom.tsx
  src/app/Scenes/Show/Screens/ShowMoreInfo.tsx
  src/app/Scenes/ViewingRoom/Components/ViewingRoomHeader.tsx
  src/app/Scenes/ViewingRoom/Components/ViewingRoomsHomeRail.tsx
  src/app/Scenes/ViewingRoom/Components/ViewingRoomsListFeatured.tsx
  src/app/Scenes/ViewingRoom/ViewingRoomArtworks.tsx
  src/app/Scenes/ViewingRoom/ViewingRoomsList.tsx
Labels: FF

#9539 chore: delete the problematic tests
  ios/Artsy.xcodeproj/project.pbxproj
  ios/ArtsyTests/ReferenceImages/LiveAuctionViewControllerTests/handles_splitting_in_an_iPad@3x.png
  ios/ArtsyTests/ReferenceImages/LiveAuctionViewControllerTests/looks_good_by_default@3x.png
  ios/ArtsyTests/ReferenceImages/LiveAuctionViewControllerTests/shows_a_removes_disconnected_screen_when_socket_reconnects@3x.png
  ios/ArtsyTests/ReferenceImages/LiveAuctionViewControllerTests/shows_a_socket_disconnect_screen_when_socket_fails@3x.png
  ios/ArtsyTests/ReferenceImages/LiveAuctionViewControllerTests/shows_an_error_screen_when_static_data_fails@3x.png
  ios/ArtsyTests/ReferenceImages/LiveAuctionViewControllerTests/shows_an_operator_disconnect_screen_when_operator_disconnects@3x.png
  ios/ArtsyTests/ReferenceImages/LiveAuctionViewControllerTests/shows_an_operator_disconnected_screen_when_operator_reconnects@3x.png
  ios/ArtsyTests/View_Controller_Tests/Auction/LiveAuctionTestUtils.swift
  ios/ArtsyTests/View_Controller_Tests/Live_Auction/LiveAuctionLotViewControllerTests.swift
Labels: Squash On Green

#9543 docs(codepush): update hotfix docs for codepush
  docs/deploy_a_hotfix.md
  fastlane/Fastfile
  scripts/codepush/promote-to-prod.sh
  scripts/codepush/update_rollout.sh
  src/app/system/codepush.ts
Labels: Jira Synced

#9548 build(deps): bumps sentry to latest
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: Squash On Green

#9549 fix: type castings from compact
  src/app/Components/GenericArtistSeriesRail.tsx
  src/app/Scenes/Home/Components/CollectionsRail.tsx
  src/app/Scenes/Home/Components/FairsRail.tsx
  src/app/Scenes/Home/Components/OldCollectionsRail.tsx
Labels: Squash On Green

#9550 build(deps): bumps unleash-proxy-client from 3.1.0 to 3.1.1
  package.json
  yarn.lock
Labels: Squash On Green

#9553 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9551 feat(ONYX-511): move custom inputs below
  src/app/Components/PriceRange/PriceRangeContainer.tsx
Labels: Jira Synced

#9556 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9552 docs(codepush): add apply fix script
  docs/deploy_a_hotfix.md
  scripts/codepush/apply-fix.sh
  scripts/codepush/calculate-native-hash.sh
Labels: Squash On Green

#9557 chore(analytics): add screen tracking for activity panel
  src/app/Scenes/Activity/Activity.tsx
Labels: Jira Synced, Squash On Green

#9559 feat: use Palette Pill implementation for recent price ranges
  src/app/Components/ArtworkFilter/RecentPriceRanges.tsx
Labels: Jira Synced, Squash On Green

#9554 fix: Make Alert form Save CTA sticky
  src/app/AppRegistry.tsx
  src/app/Components/Artist/ArtistArtworks/CreateSavedSearchModal.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormMain.tsx
  src/app/Scenes/SavedSearchAlert/Components/Form.tsx
  src/app/Scenes/SavedSearchAlert/SavedSearchAlertForm.tsx
  src/app/Scenes/SavedSearchAlert/SavedSearchAlertModel.ts
Labels: Jira Synced, Squash On Green

#9560 build(REVERT deps): bumps sentry to latest
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: Squash On Green

#9561 fix(DIA-310): empty state logic on Artist about tab
  src/app/Components/Artist/ArtistAbout/ArtistAbout.tests.tsx
  src/app/Components/Artist/ArtistAbout/ArtistAbout.tsx
Labels: Jira Synced

#9562 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9563 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9566 fix(ci): update path when using yarn in android
  scripts/ci/build-for-tests-android
Labels: Squash On Green

#9572 fix(alerts): ensure artist series in previews/pills when managing alerts
  src/app/Scenes/SavedSearchAlertsList/Components/SavedSearchesList.tsx
Labels: Jira Synced

#9573 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9567 feat: add suggested filters to saved searches
  src/app/Components/Artist/ArtistArtworks/CreateSavedSearchModal.tests.tsx
  src/app/Scenes/SavedSearchAlert/Components/Form.tsx
  src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterAdditionalGeneIDs.tsx
  src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterRarity.tsx
  src/app/Scenes/SavedSearchAlert/Components/SavedSearchNameInput.tsx
  src/app/Scenes/SavedSearchAlert/Components/SavedSearchSuggestedFilters.tests.tsx
  src/app/Scenes/SavedSearchAlert/Components/SavedSearchSuggestedFilters.tsx
  src/app/Scenes/SavedSearchAlert/CreateSavedSearchAlert.tests.tsx
  src/app/Scenes/SavedSearchAlert/EditSavedSearchAlert.tests.tsx
  src/app/Scenes/SavedSearchAlert/SavedSearchAlertForm.tests.tsx
  src/app/Scenes/SavedSearchAlert/helpers.ts
  src/app/store/config/features.ts
  src/app/utils/tests/setupTestWrapper.tsx
Labels: Jira Synced

#9569 feat(ONYX-375): add tracking to the new alerts flow
  src/app/Scenes/SavedSearchAlert/screens/ConfirmationScreen.tsx
  src/app/Scenes/SavedSearchAlert/screens/SavedSearchFilterScreen.tsx
  yarn.lock
Labels: Jira Synced, Squash On Green

#9574 feat: add ff to enable new relay middleware for all queries
  src/app/store/config/features.ts
  src/app/system/relay/middlewares/errorMiddleware.ts
Labels: Jira Synced

#9576 chore: Update app version to 8.27.0
  app.json
Labels: Squash On Green

#9577 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9579 fix: deepzoom crash type error
  src/app/Scenes/Artwork/Components/ImageCarousel/ImageCarouselContext.tsx
Labels: FF

#9582 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9585 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9587 chore: cleanup unused uploadMiddleware
  HACKS.md
  package.json
  patches/@types+extract-files+8.1.1.patch
  src/app/system/relay/defaultEnvironment.ts
  src/app/system/relay/middlewares/uploadMiddleware.tests.ts
  src/app/system/relay/middlewares/uploadMiddleware.ts
  yarn.lock
Labels: Jira Synced

#9586 chore(ONYX-536): make design adjustment to suggested filters
  package.json
  src/app/Scenes/SavedSearchAlert/Components/Form.tsx
  src/app/Scenes/SavedSearchAlert/Components/SavedSearchSuggestedFilters.tests.tsx
  src/app/Scenes/SavedSearchAlert/Components/SavedSearchSuggestedFilters.tsx
  yarn.lock
Labels: Jira Synced

#9323 build(tools): use xcode 15
  .circleci/config.yml
  .ruby-version
  .tool-versions
  docs/getting_started.md
  docs/screenshots/command-line-tools.png
  ios/ArtsyTests/ReferenceImages/ARTextViewSpec/with_HTML_looks_right_with_multiple_paragraphs@3x.png
  ios/ArtsyTests/ReferenceImages/AuctionInformationViewControllerTests/a_closed_sale__shows_the_sale_is_closed@3x.png
  ios/ArtsyTests/Supporting_Files/ARTestHelper.m
  ios/Podfile.lock
  scripts/ci/ci-setup-export-vars
Labels: Jira Synced, FF

#9590 chore: update alert screen routes
  android/app/src/main/AndroidManifest.xml
  src/app/Components/Artist/ArtistHeader.tsx
  src/app/Scenes/Artwork/ArtworkAuctionCreateAlertHeader.tsx
  src/app/Scenes/MyProfile/MyProfileSettings.tsx
  src/app/Scenes/SavedSearchAlert/SavedSearchAlertForm.tests.tsx
  src/app/Scenes/SavedSearchAlert/SavedSearchAlertForm.tsx
  src/app/Scenes/SavedSearchAlert/screens/ConfirmationScreen.tests.tsx
  src/app/Scenes/SavedSearchAlert/screens/ConfirmationScreen.tsx
  src/app/Scenes/SavedSearchAlertsList/Components/SavedSearchesList.tsx
  src/app/routes.ts
  src/app/system/navigation/navigate.tests.tsx
Labels: Jira Synced, Squash On Green

#9592 fix: broken padding in create alert screen
  src/app/Scenes/SavedSearchAlert/Components/Form.tsx
  src/app/Scenes/SavedSearchAlert/Components/SavedSearchSuggestedFilters.tsx
Labels: Squash On Green

#9578 feat(e2e): add Maestro and basic test scenarios
  e2e/README.md
  e2e/config.yml
  e2e/flows/onboarding/login.yml
  e2e/flows/onboarding/onboardingQuiz.js
  e2e/flows/onboarding/onboardingQuiz.yml
  e2e/flows/onboarding/signup.js
  e2e/flows/onboarding/signup.yml
  e2e/flows/onboarding/signupWithoutOnboarding.yml
  package.json
  src/app/Components/FancySwiper/FancySwiperIcons.tsx
  src/app/Scenes/Onboarding/OnboardingCreateAccount/TermsOfServiceCheckbox.tsx
Labels: Squash On Green

#9589 feat: Add title to "Clear Filters" alert on Alert Filter screen
  src/app/Scenes/SavedSearchAlert/screens/SavedSearchFilterScreen.tsx
Labels: Jira Synced

#9604 feat: Sort artwork lists by updated at desc
  src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/components/ArtworkLists.tsx
  src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/components/SelectArtworkListsForArtwork.tsx
  src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/components/SelectArtworkListsForArtworkHeader.tsx
Labels: Jira Synced

#9605 build(deps): bump @sentry/react-native from 5.9.1 to 5.14.1
  .circleci/config.yml
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: Jira Synced

#9609 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9602 chore(ONYX-337): retire enable android images gallery
  src/app/Scenes/Artwork/Components/ImageCarousel/ImageCarousel.tsx
  src/app/Scenes/Artwork/Components/ImageCarousel/ImageCarouselEmbedded.tsx
  src/app/store/config/features.ts
Labels: Jira Synced

#9610 fix: unable to load on see all matching artworks
  src/app/Components/ArtworkFilter/SavedSearch/convertersToFilterParams.ts
Labels: Jira Synced

#9611 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9612 feat: enable ARUsePrincipalFieldErrorHandlerMiddleware
  src/app/store/config/features.ts
Labels: Jira Synced

#9615 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green
