Repository artsy/eigen, pull requests merged in 2023-12, with the labels that each got.

#9620 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9622 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9595 feat(EMI-1557): Add Gallery Offer option in Push Notification settings screen
  src/app/Components/SwitchMenu.tsx
  src/app/Scenes/MyProfile/MyProfilePushNotifications.tests.tsx
  src/app/Scenes/MyProfile/MyProfilePushNotifications.tsx
  src/app/store/config/features.ts
Labels: Jira Synced

#9625 fix(ci): flaky android betas drop max memory
  android/gradle.properties
Labels: Jira Synced

#9629 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9630 fix(DIA-354): adds missing token to vimeo player
  src/app/Scenes/Artwork/Components/ImageCarousel/ImageCarouselVimeoVideo.tests.tsx
  src/app/Scenes/Artwork/Components/ImageCarousel/ImageCarouselVimeoVideo.tsx
Labels: Jira Synced, Squash On Green

#9627 chore(ONYX-580): update copy on create alert flow
  src/app/Scenes/SavedSearchAlert/Components/Form.tsx
  src/app/Scenes/SavedSearchAlert/Components/SavedSearchSuggestedFilters.tsx
Labels: Jira Synced, Squash On Green

#9635 feat: rename "Saved Alerts" to "Alerts"
  src/app/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
  src/app/Scenes/MyProfile/MyProfileSettings.tests.tsx
  src/app/Scenes/MyProfile/MyProfileSettings.tsx
  src/app/Scenes/SavedSearchAlert/Components/Form.tsx
  src/app/Scenes/SavedSearchAlertsList/Components/SavedSearchesList.tsx
  src/app/Scenes/SavedSearchAlertsList/SavedSearchAlertsList.tsx
Labels: Jira Synced

#9634 chore: UI improvements to saved searches
  src/app/Scenes/SavedSearchAlert/Components/EditSavedSearchAlertPlaceholder.tsx
  src/app/Scenes/SavedSearchAlert/Components/SavedSearchSuggestedFilters.tsx
Labels: Jira Synced

#9638 chore: retire AREnableMoneyFormattingInMyCollectionForm feature flag
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormMain.tsx
  src/app/store/config/features.ts
Labels: Jira Synced

#9640 chore: retire AREnableNewCollectionsRail feature flag
  src/app/Scenes/Home/Components/OldCollectionsRail.tests.tsx
  src/app/Scenes/Home/Components/OldCollectionsRail.tsx
  src/app/Scenes/Home/Home.tsx
  src/app/store/config/features.ts
Labels: Jira Synced, Squash On Green

#9626 feat(ONYX-379): add saved searches size filter
  src/app/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
  src/app/Components/Artist/ArtistArtworks/CreateSavedSearchModal.tsx
  src/app/Components/Artist/ArtistArtworks/hooks/useCreateSavedSearchModalFilters.ts
  src/app/Components/ArtworkFilter/ArtworkFilterNavigator.tsx
  src/app/Components/ArtworkFilter/Filters/CustomSizeInputs.tsx
  src/app/Components/ArtworkFilter/Filters/SizesOptionsScreen.tsx
  src/app/Components/ArtworkFilter/Filters/helpers.ts
  src/app/Scenes/Artwork/Components/ArtworkScreenHeader.tests.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/Dimensions.tsx
  src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterAppliedFilters.tsx
  src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterSize.tsx
  src/app/Scenes/SavedSearchAlert/Components/SavedSearchNameInput.tsx
  src/app/Scenes/SavedSearchAlert/CreateSavedSearchAlert.tsx
  src/app/Scenes/SavedSearchAlert/EditSavedSearchAlert.tests.tsx
  src/app/Scenes/SavedSearchAlert/EditSavedSearchAlert.tsx
  src/app/Scenes/SavedSearchAlert/SavedSearchAlertForm.tsx
  src/app/Scenes/SavedSearchAlert/SavedSearchAlertModel.ts
  src/app/Scenes/SavedSearchAlert/SavedSearchStore.tsx
  src/app/Scenes/SavedSearchAlert/containers/CreateSavedSearchContentContainer.tsx
  src/app/Scenes/SavedSearchAlert/helpers.ts
  src/app/Scenes/SavedSearchAlert/pillExtractors.ts
  src/app/Scenes/SavedSearchAlert/screens/ConfirmationScreen.tsx
  src/app/Scenes/SavedSearchAlert/screens/SavedSearchFilterScreen.tsx
  src/app/Scenes/SavedSearchAlert/useSavedSearchPills.ts
Labels: Jira Synced

#9637 chore: retire AREnableLargeArtworkRailSaveIcon feature flag
  src/app/Scenes/Home/Components/NewWorksForYouRail.tsx
  src/app/store/config/features.ts
Labels: Jira Synced, Squash On Green

#9641 chore: retire AREnableMyCollectionNotesField feature flag
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormMain.tsx
  src/app/Scenes/Onboarding/OnboardingQuiz/__tests__/OnboardingMarketingCollection.tests.tsx
  src/app/store/config/features.ts
Labels: Jira Synced, Squash On Green

#9639 chore: retire AREnableBrowseMoreArtworksCard feature flag
  src/app/Components/BrowseMoreRailCard.tsx
  src/app/store/config/features.ts
Labels: Jira Synced, Squash On Green

#9643 chore: remove experiment viewed event from the home screen
  src/app/Scenes/Home/Home.tsx
  src/app/Scenes/NewWorksForYou/NewWorksForYou.tsx
Labels: Jira Synced

#9623 refactor: sentry alert severity levels
  src/app/Components/ArtistAutosuggest/ArtistAutosuggestResults.tsx
  src/app/Components/ArtworkLists/views/CreateNewArtworkListView/components/CreateNewArtworkListForm.tsx
  src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/useSaveArtworkListsChanges.ts
  src/app/Components/AutosuggestResults/AutosuggestResults.tsx
  src/app/Components/Bidding/Screens/Registration.tsx
  src/app/Components/LoadFailureView.tsx
  src/app/Scenes/Activity/ActivityMarkAllAsReadSection.tsx
  src/app/Scenes/Activity/hooks/useMarkNotificationsAsSeen.ts
  src/app/Scenes/Activity/mutations/useMarkNotificationAsRead.ts
  src/app/Scenes/Artwork/Components/FollowArtistLink.tsx
  src/app/Scenes/ArtworkList/views/DeleteArtworkListView/DeleteArtworkListView.tsx
  src/app/Scenes/ArtworkList/views/EditArtworkListView/EditArtworkListView.tsx
  src/app/Scenes/BottomTabs/BottomTabsModel.ts
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormMain.tsx
  src/app/Scenes/MyProfile/__tests__/MyProfileEditForm.tests.tsx
  src/app/Scenes/MyProfile/useHandleVerification.tsx
  src/app/Scenes/Sale/Sale.tsx
  src/app/Scenes/SavedSearchAlertsList/Components/SavedSearchesList.tsx
  src/app/Scenes/SellWithArtsy/SubmitArtwork/SubmitArtwork.tsx
  src/app/Scenes/SellWithArtsy/SubmitArtwork/UploadPhotos/UploadPhotosForm.tsx
  src/app/store/config/EchoModel.tsx
  src/app/system/errorReporting/sentrySetup.ts
  src/app/system/relay/middlewares/principalFieldErrorHandlerMiddleware.ts
  src/app/utils/googleMaps.ts
Labels: Jira Synced

#9642 chore(ONYX-570): remove alert name from alert flow
  src/app/Components/Artist/ArtistArtworks/CreateSavedSearchModal.tests.tsx
  src/app/Components/ArtworkFilter/SavedSearch/types.ts
  src/app/Scenes/SavedSearchAlert/Components/EditSavedSearchAlertPlaceholder.tsx
  src/app/Scenes/SavedSearchAlert/Components/Form.tsx
  src/app/Scenes/SavedSearchAlert/Components/SavedSearchAlertSwitch.tsx
  src/app/Scenes/SavedSearchAlert/Components/SavedSearchNameInput.tsx
  src/app/Scenes/SavedSearchAlert/CreateSavedSearchAlert.tests.tsx
  src/app/Scenes/SavedSearchAlert/EditSavedSearchAlert.tests.tsx
  src/app/Scenes/SavedSearchAlert/SavedSearchAlertForm.tests.tsx
Labels: Jira Synced

#9644 chore(artist series): prepare for release via Echo flag
  src/app/store/config/features.ts
Labels: Squash On Green

#9648 fix(DIA-343): controls when more than one Popover tries to appear
  docs/add_progressive_onboarding.md
  src/app/Components/ProgressiveOnboarding/ProgressiveOnboardingFindSavedArtwork.tsx
  src/app/Components/ProgressiveOnboarding/ProgressiveOnboardingSaveArtwork.tsx
  src/app/Components/ProgressiveOnboarding/useSetActivePopover.tests.tsx
  src/app/Components/ProgressiveOnboarding/useSetActivePopover.ts
  src/app/store/ProgressiveOnboardingModel.ts
Labels: Jira Synced, Squash On Green

#9653 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9651 fix: error on pressing back from collection page on Android
  src/app/Components/ParentAwareScrollView.tsx
Labels: Jira Synced

#9617 fix: broken artist screen tests
  src/app/Components/Artist/ArtistHeader.tsx
  src/app/Scenes/Artist/Artist.tsx
  src/app/Scenes/Artist/ArtistSavedSearch.tests.tsx
  src/app/Scenes/Search/SearchArtworksContainer.tests.tsx
  src/setupJest.tsx
Labels: Squash On Green

#9654 fix(ci): android beta delivery
  Gemfile.lock
  fastlane/Fastfile
Labels: Jira Synced, Squash On Green

#9652 feat(EMI-1549): Handling deep linking and push notifications for Partner Offers
  android/app/src/main/AndroidManifest.xml
  src/app/AppRegistry.tsx
  src/app/Scenes/PartnerOffer/PartnerOfferContainer.tests.tsx
  src/app/Scenes/PartnerOffer/PartnerOfferContainer.tsx
  src/app/Scenes/PartnerOffer/mutations/usePartnerOfferCheckoutMutation.tsx
  src/app/routes.ts
  src/app/system/navigation/routes.tests.ts
Labels: Jira Synced

#9646 feat: add suggested filters tracking
  src/app/Scenes/SavedSearchAlert/Components/SavedSearchSuggestedFilters.tsx
Labels: Jira Synced

#9650 feat(ONYX-539): add new works for you feed
  src/app/AppRegistry.tsx
  src/app/Components/ArtworkRail/ArtworkRailCard.tsx
  src/app/Scenes/AuctionResults/AuctionResultsScreenWrapper.tsx
  src/app/Scenes/NewWorksForYou/Components/NewWorksForYouGrid.tests.tsx
  src/app/Scenes/NewWorksForYou/Components/NewWorksForYouGrid.tsx
  src/app/Scenes/NewWorksForYou/Components/NewWorksForYouHeader.tsx
  src/app/Scenes/NewWorksForYou/Components/NewWorksForYouList.tsx
  src/app/Scenes/NewWorksForYou/NewWorksForYou.tsx
  src/app/Scenes/Search/UserPrefsModel.tsx
  src/app/store/__tests__/migration.tests.ts
  src/app/store/config/features.ts
  src/app/store/migration.ts
Labels: Jira Synced, Squash On Green

#9657 feat(EMI-1593): Update save tooltip content for Partner Offer
  src/app/Components/ProgressiveOnboarding/ProgressiveOnboardingSaveArtwork.tests.tsx
  src/app/Components/ProgressiveOnboarding/ProgressiveOnboardingSaveArtwork.tsx
  src/app/store/config/features.ts
Labels: Jira Synced

#9658 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9660 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9661 chore: bump Eigen's version 8.29.0
  app.json
Labels: Squash On Green

#9664 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9663 feat(alerts): enable artist series suggestions
  src/app/Scenes/SavedSearchAlert/Components/SavedSearchSuggestedFilters.tests.tsx
  src/app/Scenes/SavedSearchAlert/Components/SavedSearchSuggestedFilters.tsx
  src/app/Scenes/SavedSearchAlert/EditSavedSearchAlert.tests.tsx
  src/app/Scenes/SavedSearchAlert/helpers.ts
  src/app/Scenes/SavedSearchAlert/pillExtractors.ts
  src/app/store/config/features.ts
Labels: Jira Synced

#9668 fix: broken bottom padding and aspect Ratio
  src/app/Components/ArtworkRail/ArtworkRailCard.tsx
  src/app/Scenes/NewWorksForYou/Components/NewWorksForYouGrid.tsx
  src/app/Scenes/NewWorksForYou/Components/NewWorksForYouList.tsx
  src/app/Scenes/NewWorksForYou/NewWorksForYou.tsx
Labels: Squash On Green

#9670 revert: add new works for you feed
  src/app/AppRegistry.tsx
  src/app/Components/ArtworkRail/ArtworkRailCard.tsx
  src/app/Scenes/AuctionResults/AuctionResultsScreenWrapper.tsx
  src/app/Scenes/NewWorksForYou/Components/NewWorksForYouGrid.tsx
  src/app/Scenes/NewWorksForYou/Components/NewWorksForYouHeader.tsx
  src/app/Scenes/NewWorksForYou/Components/NewWorksForYouList.tsx
  src/app/Scenes/NewWorksForYou/NewWorksForYou.tests.tsx
  src/app/Scenes/NewWorksForYou/NewWorksForYou.tsx
  src/app/Scenes/Search/UserPrefsModel.tsx
  src/app/store/__tests__/migration.tests.ts
  src/app/store/config/features.ts
  src/app/store/migration.ts
Labels: Jira Synced

#9671 fix: double navigate from background deep link
  src/app/utils/useDeepLinks.ts
Labels: Jira Synced

#9677 Chore: EMI-1622 - update auction registration credit card note
  src/app/Components/Bidding/Screens/CreditCardForm.tsx
Labels: Jira Synced

#9680 fix(fairs): Scrolling on fair exhibitors crashes the app
  src/app/Components/constants.ts
  src/app/Scenes/Fair/Components/FairExhibitorRail.tsx
  src/app/Scenes/Fair/Components/FairExhibitors.tsx
Labels: Jira Synced, Squash On Green

#9675 feat(DIA-70): Add progressive onboarding for alerts
  src/app/Components/Artist/ArtistArtworks/SavedSearchButtonV2.tsx
  src/app/Components/ArtworkFilter/ArtworkFilterNavigator.tsx
  src/app/Components/ArtworkFilter/components/ArtworkFilterApplyButton.tsx
  src/app/Components/ArtworkGrids/ArtworksFilterHeader.tests.tsx
  src/app/Components/ArtworkGrids/ArtworksFilterHeader.tsx
  src/app/Components/ProgressiveOnboarding/ProgressiveOnboardingAlertFilters.tests.tsx
  src/app/Components/ProgressiveOnboarding/ProgressiveOnboardingAlertFilters.tsx
  src/app/Components/ProgressiveOnboarding/ProgressiveOnboardingAlertFinish.tests.tsx
  src/app/Components/ProgressiveOnboarding/ProgressiveOnboardingAlertFinish.tsx
  src/app/Components/ProgressiveOnboarding/ProgressiveOnboardingFindSavedArtwork.tsx
  src/app/Components/ProgressiveOnboarding/ProgressiveOnboardingSaveAlert.tests.tsx
  src/app/Components/ProgressiveOnboarding/ProgressiveOnboardingSaveAlert.tsx
  src/app/Components/ProgressiveOnboarding/ProgressiveOnboardingSaveArtwork.tsx
  src/app/Components/ProgressiveOnboarding/useEnableProgressiveOnboarding.tsx
  src/app/Components/ProgressiveOnboarding/useSetActivePopover.ts
  src/app/Scenes/ArtworkList/ArtworkList.tests.tsx
  src/app/store/ProgressiveOnboardingModel.ts
  src/app/store/config/features.ts
  src/setupJest.tsx
Labels: Jira Synced

#9684 fix(ci): android memory issues
  android/gradle.properties
  fastlane/Fastfile
Labels: Squash On Green
