Repository artsy/eigen, pull requests merged in 2023-09, with the labels that each got.

#9213 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9215 feat(DIA-106): add artist cover image to the artist screen
  src/app/Components/Artist/ArtistHeader.tests.tsx
  src/app/Components/Artist/ArtistHeader.tsx
  src/app/Scenes/Artist/Artist.tsx
Labels: Jira Synced

#9197 build(codepush): codepush sdk integration
  .env.example
  .gitignore
  HACKS.md
  android/app/build.gradle
  android/app/src/main/java/net/artsy/app/MainApplication.java
  android/app/src/main/java/net/artsy/app/utils/newarchitecture/MainApplicationReactNativeHost.java
  android/app/src/main/res/values/strings.xml
  android/settings.gradle
  ios/Artsy/App/ARAppDelegate.mm
  ios/Podfile.lock
  package.json
  patches/react-native-code-push+7.1.0.patch
  scripts/download-assets
  src/app/App.tsx
  src/app/system/codepush.ts
  yarn.lock
Labels: Jira Synced

#9203 build(codepush): codepush dev menu options
  src/app/App.tsx
  src/app/AppRegistry.tsx
  src/app/Scenes/Onboarding/Onboarding.tsx
  src/app/system/devTools/DevMenu/CodePushOptions.tsx
  src/app/system/devTools/DevMenu/DevMenu.tsx
  src/app/system/devTools/DevMenu/DevMenuWrapper.tsx
Labels: Jira Synced, Squash On Green

#9220 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9218 feat(DIA-114): add highlights and achievements to artist about tab
  src/app/Components/Artist/ArtistAbout/ArtistAbout.tsx
  src/app/Components/Artist/ArtistAbout/ArtistCareerHighlights.tests.tsx
  src/app/Components/Artist/ArtistAbout/ArtistCareerHighlights.tsx
  src/app/Components/Artist/Biography.tsx
  src/app/Components/Expandable.tsx
Labels: Jira Synced

#9217 fix(ONYX-301): padding is wrong on the follows page, collected artists rail and myc empty state
  src/app/Scenes/Favorites/FavoriteArtists.tsx
  src/app/Scenes/Favorites/FavoriteCategories.tsx
  src/app/Scenes/Favorites/FavoriteShows.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtistsRail.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionZeroStateArtworks.tsx
  src/app/Scenes/MyCollection/MyCollection.tsx
Labels: Jira Synced

#9221 fix: make alert name multiline on android
  src/app/Scenes/SavedSearchAlert/Components/SavedSearchNameInput.tsx
Labels: Squash On Green

#9225 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9226 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9228 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9229 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9231 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9224 feat(DIA-69): add progressive onboarding model for saved artworks
  docs/add_a_visual_clue.md
  docs/add_progressive_onboarding.md
  src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
  src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/components/StickyBottomContent.tsx
  src/app/Components/ProgressiveOnboarding/ProgressiveOnboardingFindSavedArtwork.tests.tsx
  src/app/Components/ProgressiveOnboarding/ProgressiveOnboardingFindSavedArtwork.tsx
  src/app/Components/ProgressiveOnboarding/ProgressiveOnboardingSaveArtwork.tests.tsx
  src/app/Components/ProgressiveOnboarding/ProgressiveOnboardingSaveArtwork.tsx
  src/app/Components/ProgressiveOnboarding/useDismissSavedArtwork.tests.tsx
  src/app/Components/ProgressiveOnboarding/useDismissSavedArtwork.ts
  src/app/Components/ProgressiveOnboarding/useDismissSavedHighlight.tests.tsx
  src/app/Components/ProgressiveOnboarding/useDismissSavedHighlight.ts
  src/app/Components/ProgressiveOnboarding/useOnSaveArtwork.ts
  src/app/Scenes/ArtworkLists/ArtworkLists.tsx
  src/app/Scenes/BottomTabs/BottomTabsButton.tsx
  src/app/Scenes/BottomTabs/BottomTabsModel.ts
  src/app/Scenes/Fair/Components/FairArtworks.tsx
  src/app/Scenes/Home/Home.tsx
  src/app/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx
  src/app/store/GlobalStoreModel.ts
  src/app/store/ProgressiveOnboardingModel.ts
  src/app/store/VisualClueModel.ts
  src/app/store/__tests__/migration.tests.ts
  src/app/store/migration.ts
  src/app/system/devTools/DevMenu/DevMenu.tsx
  src/app/utils/ElementInView.tsx
  src/app/utils/hooks/useVisualClue.ts
Labels: Jira Synced

#9234 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9235 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9244 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9219 feat(DIA-105): Move follow button for artist and display count on button
  src/app/Components/Artist/ArtistHeader.tests.tsx
  src/app/Components/Artist/ArtistHeader.tsx
  src/app/Components/Artist/ArtistHeaderNavRight.tsx
  src/app/Components/Artist/useFollowArtist.ts
  src/app/Components/Button/FollowButton.tsx
  src/app/Providers.tsx
  src/app/Scenes/Artist/Artist.tests.tsx
  src/app/Scenes/Artist/Artist.tsx
Labels: Jira Synced

#9239 feat: add create alert at end of artworks list
  src/app/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
  src/app/store/config/features.ts
Labels: Jira Synced, Squash On Green

#9247 fix(DIA-126): uses the right dimensions for the images in Articles
  package.json
  src/app/Scenes/Article/Components/Sections/ArticleSectionImageCollection/ArticleSectionImageCollectionImage.tsx
  yarn.lock
Labels: Jira Synced

#9251 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9236 feat: mark ARUseNewErrorMiddleware as readyForRelease
  src/app/store/config/features.ts
Labels: Jira Synced

#9252 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9255 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9256 feat: add manage alerts button
  src/app/Scenes/Artwork/ArtworkAuctionCreateAlertHeader.tsx
Labels: Jira Synced, Squash On Green

#9258 feat(ONYX-255): add analytic tracking support for new component flows
  src/app/Components/Artist/ArtistArtworks/CreateArtworkAlertModal.tsx
  src/app/Components/Artist/ArtistArtworks/CreateSavedSearchModal.tsx
  src/app/Scenes/Artwork/ArtworkAuctionCreateAlertHeader.tsx
Labels: Jira Synced, Squash On Green

#9233 feat(ONYX-253): create suggested artworks screen
  .secrets.baseline
  src/app/AppRegistry.tsx
  src/app/Components/Artist/ArtistArtworks/CreateArtworkAlertModal.tsx
  src/app/Scenes/Artwork/ArtworkAuctionCreateAlertHeader.tsx
  src/app/Scenes/Artwork/Components/BrowseSimilarWorks/BrowseSimilarWorks.tsx
  src/app/Scenes/Artwork/Components/BrowseSimilarWorks/BrowseSimilarWorksContent.tsx
  src/app/Scenes/Artwork/Components/BrowseSimilarWorks/BrowseSimilarWorksErrorState.tsx
  src/app/routes.ts
Labels: Jira Synced, Squash On Green

#9259 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9260 feat(onyx-254): Add See more on Artsy button to end of Suggested artworks screen
  src/app/Scenes/Artwork/Components/BrowseSimilarWorks/BrowseSimilarWorksContent.tsx
  src/app/Scenes/Artwork/Components/BrowseSimilarWorks/BrowseSimilarWorksExploreMoreButton.tsx
Labels: Jira Synced

#9254 refactor: replace searchArtworksGrid with MasonryFlashList
  src/app/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
  src/app/Scenes/Search/SearchArtworksGrid.tsx
  src/app/utils/masonryHelpers/index.ts
  src/setupJest.tsx
Labels: Jira Synced

#9263 fix(images): use new default resize behavior to avoid overfetching
  package.json
  src/app/Scenes/Home/Components/HeroUnitsRail.tsx
  src/app/system/devTools/DevMenu/DevMenu.tsx
  yarn.lock
Labels: Jira Synced, Squash On Green

#9262 chore: use m1 machines in ci
  .circleci/config.yml
  .ruby-version
  .tool-versions
Labels: Jira Synced

#9266 fix(ONYX-273): refactor and add isInAuction for header create alert cta
  src/app/Scenes/Artwork/Components/ArtworkScreenHeaderCreateAlert.tsx
Labels: Jira Synced

#9277 feat: add AREnableAuctionHeaderAlertCTA echoFlagKey
  src/app/store/config/features.ts
Labels: Squash On Green

#9273 fix: hide empty sections on artist about page
  src/app/Components/Artist/ArtistAbout/ArtistAbout.tests.tsx
  src/app/Components/Artist/ArtistAbout/ArtistAbout.tsx
Labels: Jira Synced, Squash On Green

#9261 feat: Latest Activity Rail
  .secrets.baseline
  src/app/Components/SectionTitle.tsx
  src/app/Scenes/Activity/ActivityItem.tsx
  src/app/Scenes/Activity/ActivityItemTypeLabel.tsx
  src/app/Scenes/Activity/mutations/useMarkNotificationAsRead.ts
  src/app/Scenes/Activity/utils/getNotificationTypeLabel.ts
  src/app/Scenes/Activity/utils/navigateToActivityItem.ts
  src/app/Scenes/Home/Components/ActivityRail.tests.tsx
  src/app/Scenes/Home/Components/ActivityRail.tsx
  src/app/Scenes/Home/Components/ActivityRailItem.tsx
  src/app/Scenes/Home/Home.tsx
  src/app/Scenes/Home/homeAnalytics.ts
  src/app/Scenes/Home/useHomeModules.ts
  src/app/store/config/features.ts
Labels: Jira Synced, Squash On Green

#9276 fix: My Collection onboarding tooltip flow direction
  package.json
  src/app/Scenes/MyCollection/Components/MyCollectionStickyHeader.tsx
  yarn.lock
Labels: Squash On Green

#9281 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9279 fix: artist loading skeleton
  src/app/Components/Artist/ArtistHeader.tsx
  src/app/Scenes/Artist/Artist.tsx
  src/app/utils/placeholders.tsx
Labels: Jira Synced

#9278 chore: hide progressive onboarding on first session
  src/app/Components/ProgressiveOnboarding/ProgressiveOnboardingFindSavedArtwork.tsx
  src/app/store/AuthModel.ts
Labels: Jira Synced

#9274 fix: show auction results filtering button
  src/app/Components/Artist/ArtistInsights/ArtistInsights.tsx
  src/app/Components/Artist/ArtistInsights/ArtistInsightsAuctionResults.tests.tsx
  src/app/Components/Artist/ArtistInsights/ArtistInsightsAuctionResults.tsx
Labels: Jira Synced

#9272 fix: improve follow/unfollow UX in Artist page
  src/app/Components/Artist/ArtistHeaderNavRight.tsx
  src/app/Scenes/Artist/Artist.tests.tsx
  src/app/Scenes/Artist/Artist.tsx
Labels: Jira Synced

#9283 fix(DIA-162): misaligned view all button in articles rail
  src/app/Components/Artist/Articles/Articles.tsx
Labels: Jira Synced, Squash On Green

#9288 feat: add partner counts to partner follow button
  src/app/Scenes/Partner/Components/PartnerFollowButton.tests.tsx
  src/app/Scenes/Partner/Components/PartnerFollowButton.tsx
Labels: Jira Synced

#9287 fix(DIA-165): broken horizontal padding on artist page
  src/app/Components/Artist/Articles/Articles.tsx
  src/app/Components/Artist/ArtistAbout/ArtistAbout.tsx
  src/app/Components/Artist/ArtistAbout/ArtistAboutRelatedGenes.tsx
  src/app/Components/Artist/ArtistAbout/ArtistAboutShows.tsx
  src/app/Components/Artist/ArtistAbout/ArtistCareerHighlights.tsx
  src/app/Components/Artist/Biography.tsx
  src/app/Components/Artist/RelatedArtistsRail.tsx
  src/app/Scenes/ArtistSeries/ArtistSeriesMoreSeries.tsx
Labels: Jira Synced

#9290 chore: make my collection artists privacy modal less defensive
  src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtistsOnboardingModal.tsx
Labels: Jira Synced

#9291 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9282 refactor(PHIRE-228): More defensive Artwork page
  src/app/Scenes/Artwork/Artwork.tsx
  src/app/Scenes/Artwork/Components/AboutArtist.tsx
  src/app/Scenes/Artwork/Components/ArtworkConsignments.tsx
  src/app/Scenes/Artwork/Components/ArtworkDetails.tsx
  src/app/Scenes/Artwork/Components/ArtworkHeader.tsx
  src/app/Scenes/Artwork/Components/ArtworkHistory.tsx
  src/app/Scenes/Artwork/Components/ArtworksInSeriesRail.tsx
  src/app/Scenes/Artwork/Components/OtherWorks.tests.tsx
  src/app/Scenes/Artwork/Components/OtherWorks/OtherWorks.tsx
  src/app/Scenes/Artwork/Components/PartnerCard.tsx
  src/app/system/relay/middlewares/errorMiddleware.ts
  src/app/system/relay/middlewares/principalFieldErrorHandlerMiddleware.ts
Labels: Jira Synced

#9295 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9296 fix: disable the feature flag to fix the tests
  src/app/Scenes/Artwork/Artwork.tests.tsx
Labels: Squash On Green

#9298 feat(ONYX-316): Move Gallery Pill to the front so it is visible without scrolling
  src/app/Scenes/Search/constants.ts
Labels: Jira Synced

#9301 chore: set ARShowCreateAlertInArtistArtworksListFooter as ready for r…
  src/app/store/config/features.ts
Labels: Squash On Green

#9300 chore(onyx-356): add AREnableSingleActivityPanelScreen feature flag
  src/app/store/config/features.ts
Labels: Jira Synced

#9305 fix(DIA-168): onboarding quiz crash
  src/app/Components/FancySwiper/FancySwiper.tsx
  src/app/Scenes/ArtQuiz/ArtQuizArtworks.tsx
Labels: Jira Synced, Squash On Green

#9302 refactor: ArrayIndexOutOfBoundsException - remove obsolete cellItemRenderer
  src/app/Scenes/Fair/Fair.tsx
Labels: Jira Synced

#9313 chore: prep for 8.22.0
  app.json
Labels: Squash On Green

#9314 chore: Remove ARReorderSWAArtworkSubmissionFlow ff
  src/app/Scenes/SellWithArtsy/SubmitArtwork/SubmitArtwork.tsx
  src/app/store/config/features.ts
Labels: Jira Synced

#9315 chore: Remove AREnableNewRequestPriceEstimateLogic ff
  src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/RequestForPriceEstimate/RequestForPriceEstimateBanner.tests.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/RequestForPriceEstimate/RequestForPriceEstimateBanner.tsx
  src/app/store/config/features.ts
Labels: Squash On Green

#9320 refactor(cleanup): searchdiscovery ff
  src/app/Scenes/Search/Search.tsx
  src/app/Scenes/Search/components/placeholders/SearchPlaceholder.tsx
  src/app/Scenes/Search/useSearchDiscoveryContentEnabled.ts
  src/app/store/config/features.ts
Labels: Squash On Green, FF

#9317 refactor(cleanup 🧹): cleanup some unused stuff
  ios/Podfile.lock
  package.json
  src/app/Components/ArtworkGrids/utils/index.ts
  src/app/Components/ArtworkGrids/utils/layout.ts
  src/app/Components/ArtworkGrids/utils/sections.ts
  src/app/Components/Button/colors.ts
  src/app/Components/LegacyTabs/index.tsx
  src/app/Components/Pill/Pill.tsx
  src/app/Components/ScrollableTabBar.tsx
  src/app/Components/Select/index.tsx
  src/app/Scenes/Artwork/Components/ArtworkHeader.tsx
  src/app/Scenes/Artwork/Components/CommercialButtons/helpers.ts
  src/app/Scenes/MyCollection/Screens/CollectedArtistsPrivacy/MyCollectionCollectedArtistsPrivacyArtistsList.tsx
  src/app/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx
  src/app/Scenes/MyProfile/MyProfileSettings.tsx
  src/app/Scenes/Search/constants.ts
  src/app/utils/nextTick.ts
  src/app/utils/nullAndUndef.ts
  src/app/utils/resizeImage.ts
  src/app/utils/types/types.ts
  yarn.lock
Labels: FF

#9311 build(deps-cleanup): remove rn-async-storage-flipper patch
  HACKS.md
  package.json
  patches/rn-async-storage-flipper+0.0.10.patch
  src/app/App.tsx
  src/app/utils/useDebugging.ts
  yarn.lock
Labels: FF

#9318 build(deps): bump react-native-gesture-handler from 2.5.0 to 2.13.1
  ios/Podfile.lock
  package.json
  patches/react-native-gesture-handler+2.5.0.patch
  yarn.lock
Labels: FF

#9319 refactor(cleanup): clean up AREnableConversationalBuyNow
  src/app/Scenes/Inbox/Components/Conversations/ConversationCTA.tsx
  src/app/Scenes/Inbox/Components/Conversations/EditionSelectBox.tests.tsx
  src/app/Scenes/Inbox/Components/Conversations/EditionSelectBox.tsx
  src/app/Scenes/Inbox/Components/Conversations/OpenInquiryModalButton.tests.tsx
  src/app/Scenes/Inbox/Components/Conversations/OpenInquiryModalButton.tsx
  src/app/Scenes/Inbox/Components/Conversations/PurchaseModal.tests.tsx
  src/app/store/config/features.ts
Labels: Squash On Green, FF

#9312 build(deps): bump @react-native-async-storage/async-storage from 1.16.1 to 1.19.3
  HACKS.md
  ios/Podfile.lock
  package.json
  patches/@react-native-async-storage+async-storage+1.16.1.patch
  src/setupJest.tsx
  yarn.lock
Labels: FF

#9308 refactor(alerts): use eligibility flag from MP instead of computing locally
  src/app/Components/Artist/ArtistArtworks/CreateArtworkAlertModal.tests.tsx
  src/app/Components/Artist/ArtistArtworks/CreateArtworkAlertModal.tsx
  src/app/Scenes/Artwork/ArtworkAuctionCreateAlertHeader.tsx
  src/app/Scenes/Artwork/Components/ArtworkScreenHeader.tests.tsx
  src/app/Scenes/Artwork/Components/ArtworkScreenHeaderCreateAlert.tsx
  src/app/Scenes/Artwork/Components/BrowseSimilarWorks/BrowseSimilarWorks.tsx
Labels: Jira Synced

#9310 build(deps): bump @gorhom/bottom-sheet from 4.4.5 to 4.5.1
  package.json
  yarn.lock
Labels: FF

#9309 build(deps): bump react-native-action-cable from 1.1.0 to 1.1.4
  package.json
  yarn.lock
Labels: Squash On Green, FF

#9307 fix: update doctor script
  package.json
  scripts/doctor.js
  yarn.lock
Labels: FF

#9205 build(codepush) : codepush ci scripts + sentry handling
  .circleci/config.yml
  .env.example
  .gitignore
  Gemfile.lock
  app.json
  fastlane/Fastfile
  fastlane/Pluginfile
  fastlane/sentry_fastlane.rb
  fastlane/utility_fastlane.rb
  package.json
  scripts/codepush/calculate-native-hash.sh
  scripts/codepush/check-native-code.sh
  scripts/codepush/deploy-or-notify.sh
  scripts/codepush/deploy-to-codepush.sh
  scripts/codepush/determine-deployment-type.sh
  scripts/codepush/increment-native-code.sh
  scripts/setup-env-for-releases
  src/app/store/config/EchoModel.tests.tsx
  src/app/system/codepush.ts
  src/app/system/devTools/DevMenu/CodePushOptions.tsx
  src/app/system/errorReporting/sentrySetup.ts
Labels: Jira Synced

#9326 fix: login/signup buttons do not show up
  app.json
  src/app/Scenes/Onboarding/OnboardingWelcome.tsx
  src/app/utils/jsonFiles.ts
Labels: Jira Synced, Squash On Green

#9341 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9339 chore: use m1 machines in ci once again
  .circleci/config.yml
  .ruby-version
  .tool-versions
Labels: Jira Synced

#9342 chore: update podfile and increment native code #trivial #nochangelog
  app.json
  ios/Podfile.lock
Labels: Squash On Green

#9344 chore: Sentry error reporting improvements
  src/app/system/errorReporting/hooks.ts
  src/app/system/errorReporting/sentrySetup.ts
  src/app/system/relay/middlewares/errorMiddleware.ts
  src/app/system/relay/middlewares/principalFieldErrorHandlerMiddleware.ts
Labels: Squash On Green

#9332 refactor(PHIRE-218): use MasonryFlashList of full screen grids
  src/app/AppRegistry.tsx
  src/app/Components/ArtworkGrids/MasonryArtworkGridItem.tsx
  src/app/Components/ArtworkGrids/MasonryInfiniteScrollArtworkGrid.tsx
  src/app/Scenes/ArtworkList/ArtworkList.tsx
  src/app/Scenes/ArtworkList/ArtworkListArtworksGridHeader.tsx
  src/app/Scenes/ArtworkRecommendations/ArtworkRecommendations.tsx
  src/app/Scenes/LotsByArtistsYouFollow/LotsByArtistsYouFollow.tsx
  src/app/Scenes/NewWorksForYou/NewWorksForYou.tsx
  src/app/Scenes/NewWorksFromGalleriesYouFollow/NewWorksFromGalleriesYouFollow.tsx
  src/app/Scenes/RecentlyViewed/RecentlyViewed.tsx
  src/app/Scenes/SimilarToRecentlyViewed/SimilarToRecentlyViewed.tsx
  src/app/utils/masonryHelpers/index.ts
  src/app/utils/masonryHelpers/index.tsx
Labels: Jira Synced

#9338 chore: codepush ci refactor, check native code command
  .circleci/config.yml
  ios/ArtsyTests/ReferenceImages/ARTextViewSpec/with_HTML_looks_right_with_multiple_paragraphs@3x.png
  ios/ArtsyTests/Supporting_Files/ARTestHelper.m
  package.json
  scripts/codepush/calculate-native-hash.sh
  scripts/codepush/check-native-code.sh
  scripts/codepush/deploy-or-notify.sh
  scripts/codepush/determine-deployment-type.sh
  scripts/codepush/increment-native-code.sh
  scripts/source-for-bash-env
Labels: Squash On Green

#9345 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9348 chore: prep for new version
  app.json
Labels: Squash On Green

#9327 feat(onyx-356): single activity panel notification screen
  src/app/AppRegistry.tsx
  src/app/Scenes/Activity/ActivityItem.tsx
  src/app/Scenes/Activity/ActivityItemArtworksGrid.tsx
  src/app/Scenes/Activity/ActivityItemScreen.tsx
  src/app/Scenes/Home/Components/ActivityRailItem.tsx
  src/app/Scenes/MyCollection/Screens/Insights/ArtistItem.tsx
  src/app/routes.ts
Labels: Jira Synced

#9330 feat: add "Add filters" to create alert screen
  src/app/Components/MenuItem.tsx
  src/app/Scenes/SavedSearchAlert/Components/Form.tsx
  src/app/store/config/features.ts
Labels: Jira Synced, Squash On Green

#9356 fix: make sure the artistID is not null in SavedSearchAlertsList
  src/app/Scenes/SavedSearchAlertsList/SavedSearchAlertsList.tsx
Labels: Squash On Green

#9359 feat(DIA-109): add represented by section on Artist screen
  src/app/Components/Artist/ArtistHeader.tests.tsx
  src/app/Components/Artist/ArtistHeader.tsx
  src/app/Scenes/Artist/Artist.tsx
Labels: Jira Synced

#9354 fix(EMI-1396): Fix Android hardware back button in WebViews
  ios/Podfile.lock
  package.json
  src/app/Components/ArtsyWebView.tests.tsx
  src/app/Components/ArtsyWebView.tsx
  src/setupJest.tsx
  yarn.lock
Labels: Jira Synced
