Repository artsy/eigen, pull requests merged in 2023-02, with the labels that each got.

#8112 Update Changelog ✍️
  CHANGELOG/android-changelog.md
  CHANGELOG/ios-changelog.md
Labels: Merge On Green, Changelog Updater

#8114 Update Changelog ✍️
  CHANGELOG/android-changelog.md
Labels: Merge On Green, Changelog Updater

#8115 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#8116 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#8118 feat(FX-4537): Hide the global blue dot indicator if there are no unseen notifications
  src/app/Scenes/Activity/Activity.tsx
  src/app/Scenes/Activity/ActivityList.tsx
  src/app/Scenes/Activity/hooks/useMarkNotificationsAsSeen.ts
  src/app/Scenes/BottomTabs/BottomTabs.tests.tsx
  src/app/Scenes/BottomTabs/BottomTabsModel.ts
  src/app/store/migration.tests.ts
  src/app/store/migration.ts
Labels: Jira Synced, Squash On Green

#8119 Update Changelog ✍️
  CHANGELOG/android-changelog.md
  CHANGELOG/ios-changelog.md
Labels: Merge On Green, Changelog Updater

#8121 feat(TX-1032): Different bank account details per order currency
  src/app/Scenes/OrderHistory/OrderDetails/Components/WirePaymentSection.tsx
  src/app/Scenes/OrderHistory/OrderDetails/WirePaymentSection.tests.tsx
Labels: Jira Synced

#8122 Update Changelog ✍️
  CHANGELOG/android-changelog.md
  CHANGELOG/ios-changelog.md
Labels: Merge On Green, Changelog Updater

#8127 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#8126 build(deps): sentry cli bump
  package.json
  yarn.lock
Labels: Squash On Green

#8128 Update Changelog ✍️
  CHANGELOG/android-changelog.md
  CHANGELOG/ios-changelog.md
Labels: Merge On Green, Changelog Updater

#8129 Update Changelog ✍️
  CHANGELOG/android-changelog.md
  CHANGELOG/ios-changelog.md
Labels: Merge On Green, Changelog Updater

#8131 Update Changelog ✍️
  CHANGELOG/android-changelog.md
  CHANGELOG/ios-changelog.md
Labels: Merge On Green, Changelog Updater

#8089 feat: Empty fallback results tabs
  src/app/Scenes/ArtQuiz/ArtQuizArtworks.tsx
  src/app/Scenes/ArtQuiz/ArtQuizNavigation.tsx
  src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResults.tsx
  src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsLoader.tsx
  src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsTabs/ArtQuizLikedArtworks.tsx
  src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsTabs/ArtQuizResultsEmptyTabs.tsx
  src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsTabs/ArtQuizResultsTabs.tsx
  src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsTabs/ArtQuizResultsTabsHeader.tsx
Labels: Jira Synced, Squash On Green

#8113 feat(FX-4564): search es pills
  src/app/Scenes/Search/Search2.tests.tsx
  src/app/Scenes/Search/Search2.tsx
  src/app/Scenes/Search/SearchPills2.tsx
  src/app/Scenes/Search/components/SearchInput.tsx
  src/app/Scenes/Search/constants.ts
  src/app/Scenes/Search/useRefetchWhenQueryChanged.tsx
  src/app/Scenes/Search/useSearchQuery.tsx
Labels: Jira Synced

#8134 Update Changelog ✍️
  CHANGELOG/android-changelog.md
  CHANGELOG/ios-changelog.md
Labels: Merge On Green, Changelog Updater

#8143 chore: run yarn on main
  yarn.lock
Labels: Squash On Green

#8148 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#8142 feat: Artists result screen tab
  src/app/Scenes/ArtQuiz/ArtQuizArtworks.tsx
  src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsTabs/ArtQuizExploreArtist.tsx
  src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsTabs/ArtQuizExploreArtists.tsx
  src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsTabs/ArtQuizLikedArtworks.tsx
  src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsTabs/ArtQuizResultsTabs.tsx
  src/app/Scenes/ArtQuiz/ArtQuizWelcome.tsx
Labels: Jira Synced

#8152 tests: camera mock for tests, and less annoying eslint rule
  .eslintrc.js
  package.json
  src/setupJest.ts
  yarn.lock
Labels: Squash On Green

#8141 feat: optimize search query calls
  src/app/AppRegistry.tsx
  src/app/Scenes/Home/Home.tsx
  src/app/Scenes/Search/Search2.tests.tsx
  src/app/Scenes/Search/Search2.tsx
  src/app/Scenes/Search/components/CityGuideCTA.tsx
  src/app/Scenes/Search/useRefetchWhenQueryChanged.tsx
  src/app/Scenes/Search/useSearchQuery.tsx
  src/app/routes.ts
  src/app/utils/queryPrefetching.ts
Labels: Jira Synced

#8154 revert: reverts process color because the color doesn't work
  src/app/Components/OpaqueImageView/OpaqueImageView.tsx
Labels: Squash On Green

#8155 fix: JSON value ‘#E7E7E7’ of type NSString cannot be converted to a U…
  src/app/Components/OpaqueImageView/OpaqueImageView.tsx
Labels: Squash On Green

#8136 Feat(CX-3358): MoneyInput Improvements
  src/app/Components/Bidding/Screens/PhoneNumberForm.tests.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormMain.tsx
  src/app/store/config/features.ts
  src/palette/elements/Input/INTERNALSelectAndInputCombinationBase.tsx
  src/palette/elements/Input/Input.tsx
  src/palette/elements/Input/MoneyInput/MoneyInput.tests.tsx
  src/palette/elements/Input/MoneyInput/MoneyInput.tsx
  src/palette/elements/Input/MoneyInput/moneyInputHelpers.ts
  src/palette/elements/Input/PhoneInput/PhoneInput.tsx
Labels: Jira Synced

#8158 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#8159 fix: broken spacings in save artwrork modal and SWA flow
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/SavingArtworkModal.tsx
  src/app/Scenes/SellWithArtsy/Components/Header.tsx
  src/app/Scenes/SellWithArtsy/SubmitArtwork/SubmitArtwork.tsx
Labels: Squash On Green

#8160 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#8151 feat: Trending Collections and Trending Artists
  src/app/Scenes/ArtQuiz/ArtQuizArtworks.tsx
  src/app/Scenes/ArtQuiz/ArtQuizNavigation.tsx
  src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResults.tsx
  src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsLoader.tsx
  src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsTabs/ArtQuizArtist.tsx
  src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsTabs/ArtQuizExploreArtists.tsx
  src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsTabs/ArtQuizLikedArtworks.tsx
  src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsTabs/ArtQuizResultsEmptyTabs.tsx
  src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsTabs/ArtQuizResultsTabs.tsx
  src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsTabs/ArtQuizResultsTabsHeader.tsx
  src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsTabs/ArtQuizTrendingArtists.tsx
  src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsTabs/ArtQuizTrendingCollection.tsx
  src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsTabs/ArtQuizTrendingCollections.tsx
  src/app/Scenes/ArtQuiz/ArtQuizWelcome.tsx
Labels: Jira Synced

#8164 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#8163 fix(FX-4606): Don't display +n text in activity panel for non-artwork-based notifications
  src/app/Scenes/Activity/ActivityItem.tests.tsx
  src/app/Scenes/Activity/ActivityItem.tsx
Labels: Jira Synced

#8168 feat(FX-4607): Add "Artsy Editorial" prefix in activity panel
  src/app/Scenes/Activity/ActivityItem.tsx
  src/app/Scenes/Activity/ActivityItemTypeLabel.tsx
  src/app/Scenes/Activity/utils/shouldDisplayNotificationTypeLabel.ts
Labels: Jira Synced

#8170 feat: add analytics on es search results + bonus refactor
  src/app/Scenes/Search/SearchResults.tsx
  src/app/Scenes/Search/components/ElasticSearchResult.tsx
  src/app/Scenes/Search/components/ElasticSearchResults.tsx
  src/app/Scenes/Search/constants.ts
  src/app/Scenes/Search/types.ts
Labels: Jira Synced

#8172 fix: auction navigation android issue
  src/app/Scenes/Sales/Sales.tests.tsx
  src/app/Scenes/Sales/Sales.tsx
Labels: Squash On Green

#8174 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#8137 fix: Simplify MyC local image logic
  .secrets.baseline
  src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
  src/app/Components/ArtworkGrids/GenericGrid.tsx
  src/app/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tests.tsx
  src/app/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx
  src/app/Components/OpaqueImageView/OpaqueImageView.tsx
  src/app/Components/Toast/Toast.tests.tsx
  src/app/Scenes/Artwork/Components/ImageCarousel/FullScreen/ImageCarouselFullScreen.tests.tsx
  src/app/Scenes/Artwork/Components/ImageCarousel/ImageCarousel.tests.tsx
  src/app/Scenes/Artwork/Components/ImageCarousel/ImageCarousel.tsx
  src/app/Scenes/Artwork/Components/ImageCarousel/ImageCarouselContext.tests.tsx
  src/app/Scenes/Artwork/Components/ImageCarousel/ImageCarouselContext.tsx
  src/app/Scenes/Artwork/Components/ImageCarousel/ImageCarouselEmbedded.tests.tsx
  src/app/Scenes/Artwork/Components/ImageCarousel/ImageCarouselEmbedded.tsx
  src/app/Scenes/Artwork/Components/ImageCarousel/ImageWithLoadingState.tests.tsx
  src/app/Scenes/Artwork/Components/ImageCarousel/ImageWithLoadingState.tsx
  src/app/Scenes/Artwork/Components/ImageCarousel/geometry.ts
  src/app/Scenes/MyCollection/Components/MyCollectionArtworkList.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionArtworkListItem.tests.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionArtworkListItem.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionImageView.tests.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionImageView.tsx
  src/app/Scenes/MyCollection/MyCollection.tsx
  src/app/Scenes/MyCollection/MyCollectionArtworks.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionArtworkHeader.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionWhySell.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtworkAutosuggestResults.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tests.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionImageUtil.ts
  src/app/Scenes/MyCollection/Screens/ArtworkList/MyCollectionArtworkGridItem.tests.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkList/MyCollectionArtworkGridItem.tsx
  src/app/Scenes/MyCollection/mutations/myCollectionCreateArtwork.ts
  src/app/Scenes/MyCollection/utils/randomMyCollectionArtwork.ts
  src/app/Scenes/MyProfile/MyProfileEditForm.tsx
  src/app/Scenes/MyProfile/MyProfileHeader.tsx
  src/app/Scenes/MyProfile/__tests__/MyProfileHeaderMyCollectionAndSavedWorks.tests.tsx
  src/app/Scenes/Sale/Components/SaleArtworkListItem.tsx
  src/app/Scenes/SellWithArtsy/SubmitArtwork/UploadPhotos/UploadPhotosForm.tsx
  src/app/utils/LocalImageStore.tests.ts
  src/app/utils/LocalImageStore.ts
Labels: Jira Synced, Squash On Green

#8183 chore: prepare for 8.7.1
  app.json
  src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionArtworkHeader.tsx
Labels: Squash On Green

#8184 chore: prepare for 8.8.0
  app.json
Labels: Squash On Green

#8185 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#8081 [FF] refactor: bottom tabs tests
  src/app/Providers.tsx
  src/app/Scenes/BottomTabs/BottomTabs.tests.tsx
  src/app/Scenes/BottomTabs/BottomTabs.tsx
  src/app/Scenes/BottomTabs/BottomTabsButton.tsx
  src/app/Scenes/BottomTabs/BottomTabsModel.ts
  src/app/utils/tests/renderWithWrappers.tsx
  src/setupJest.ts
Labels: FF

#8189 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#8190 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#8191 feat(FX-4558): add save/saved label to save artwork button
  src/app/Scenes/Artwork/Components/AboveTheFoldArtworkPlaceholder.tsx
  src/app/Scenes/Artwork/Components/ArtworkScreenHeader.tsx
  src/app/Scenes/Artwork/Components/ArtworkScreenHeaderCreateAlert.tsx
Labels: Jira Synced

#8195 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#8200 feat(FX-4614): elastic pills not disabled when loading counts
  src/app/Scenes/Search/ElasticSearchPills.tsx
Labels: Jira Synced

#8202 fix(FX-4616): remove top padding from top pill results
  src/app/Scenes/Search/SearchResults.tsx
Labels: Jira Synced

#8203 feat: Use only large artwork rails on home screen
  src/app/Scenes/Home/Components/ArtworkModuleRail.tsx
  src/app/Scenes/Home/Components/ArtworkRecommendationsRail.tsx
  src/app/Scenes/Home/Components/NewWorksForYouRail.tsx
  src/app/Scenes/Home/Home.tsx
  src/app/store/config/features.ts
Labels: Jira Synced

#8204 feat(CX-3419): Display New Field Notes in MyCollection Artwork
  src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkAbout/MyCollectionArtworkAboutWork.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/Field.tests.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/Field.tsx
Labels: Jira Synced

#8205 fix: onScrollDragBegin dismiss keyboard and blur input
  src/app/Scenes/Search/AutosuggestResults.tsx
  src/app/Scenes/Search/SearchContext.ts
  src/app/Scenes/Search/components/AutosuggestSearchResult.tsx
  src/app/Scenes/Search/components/ElasticSearchResults.tests.tsx
  src/app/Scenes/Search/components/ElasticSearchResults.tsx
Labels: Jira Synced

#8207 fix: old button until palette button is ready
  package.json
  src/app/Providers.tsx
  src/app/Scenes/MyProfile/MyProfileSettings.tsx
  src/palette/Button/Button.tsx
  yarn.lock
Labels: Squash On Green

#8209 fix: use capital K for price values
  src/app/Scenes/Partner/Components/PartnerHeader.tests.tsx
  src/app/utils/formatLargeNumber.tests.ts
  src/app/utils/formatLargeNumber.ts
  src/app/utils/formatLargeNumberOfItems.tests.ts
Labels: Jira Synced

#8210 fix(FX-4617): position reset search result screen on query change
  src/app/Scenes/Search/AutosuggestResults.tsx
  src/app/Scenes/Search/components/ElasticSearchResults.tsx
Labels: Jira Synced

#8212 feat: Show save icon by default on large artwork rails
  src/app/Components/ArtworkRail/LargeArtworkRail.tsx
Labels: Jira Synced

#8213 fix(FX-4619): reduce the initial fetched artwork results
  src/app/Scenes/Search/SearchArtworksContainer.tsx
  src/app/Scenes/Search/SearchArtworksGrid.tsx
Labels: Jira Synced

#8218 fix: avoid double tracking marketing links
  src/app/utils/useDeepLinks.ts
Labels: Squash On Green

#8221 chore(devMenu): Move RN dev menu button to top
  src/app/utils/DevMenu.tsx
Labels: Merge On Green

#8222 feat(toolchain): Streamline DX around working with local palette-mobile
  .gitignore
  docs/README.md
  docs/developing_local_palette.md
  package.json
  scripts/yalc-link-local-palette
  scripts/yalc-unlink-local-palette
Labels: Squash On Green

#8220 Feat(CX-3377): Redesign the SWA Landing Page Part 2
  images/get-in-touch-banner-image-ipad@1x.png
  images/get-in-touch-banner-image-ipad@2x.png
  images/get-in-touch-banner-image-ipad@3x.png
  images/get-in-touch-banner-image@1x.png
  images/get-in-touch-banner-image@2x.png
  images/get-in-touch-banner-image@3x.png
  src/app/Scenes/SellWithArtsy/Components/GetInTouchBanner.tsx
  src/app/Scenes/SellWithArtsy/Components/HowItWorks.tsx
  src/app/Scenes/SellWithArtsy/SellWithArtsyHome.tsx
  src/app/store/config/features.ts
Labels: Jira Synced

#8211 feat: Use email campaign new works for you version
  .secrets.baseline
  src/app/Scenes/Home/Components/NewWorksForYouRail.tsx
  src/app/Scenes/Home/Home.tsx
  src/app/Scenes/NewWorksForYou/NewWorksForYou.tests.tsx
  src/app/Scenes/NewWorksForYou/NewWorksForYou.tsx
Labels: Jira Synced

#8231 Home screen reordering
  src/app/Scenes/Home/Home.tsx
Labels: Jira Synced

#8196 Feat(CX-3376): Redesign SWA Landing Page [Part 1]
  images/swa-landing-page-header@1x.png
  images/swa-landing-page-header@2x.png
  images/swa-landing-page-header@3x.png
  images/ways-we-sell-auction@1x.png
  images/ways-we-sell-auction@2x.png
  images/ways-we-sell-auction@3x.png
  images/ways-we-sell-online-storefront@1x.png
  images/ways-we-sell-online-storefront@2x.png
  images/ways-we-sell-online-storefront@3x.png
  images/ways-we-sell-private-sales@1x.png
  images/ways-we-sell-private-sales@2x.png
  images/ways-we-sell-private-sales@3x.png
  src/app/Scenes/SellWithArtsy/Components/Header.tsx
  src/app/Scenes/SellWithArtsy/Components/Highlights.tsx
  src/app/Scenes/SellWithArtsy/Components/WaysWeSell.tsx
  src/app/Scenes/SellWithArtsy/Components/icons/Icons.tsx
  src/app/Scenes/SellWithArtsy/SellWithArtsyHome.tsx
Labels: Jira Synced, Squash On Green

#8234 fix: fixes icon color / placeholder issues on artworkscreenheader
  src/app/Scenes/Artwork/Components/AboveTheFoldArtworkPlaceholder.tsx
  src/app/Scenes/Artwork/Components/ArtworkScreenHeaderCreateAlert.tsx
Labels: Squash On Green

#8242 fix(APPL-312): improvements for collections screen, empty artworks state
  src/app/Components/ArtworkGrids/FilteredArtworkGridZeroState.tsx
  src/app/Scenes/Collection/Screens/CollectionArtworks.tests.tsx
  src/app/Scenes/Collection/Screens/CollectionArtworks.tsx
Labels: Jira Synced, Squash On Green

#8243 fix(APPL-305): edit alert flow
  src/app/Scenes/SavedSearchAlert/EditSavedSearchAlert.tests.tsx
  src/app/Scenes/SavedSearchAlert/SavedSearchAlert.tsx
Labels: Jira Synced, Squash On Green

#8252 feat: specify which entities to get aggregations from on essearchpills
  src/app/Scenes/Search/ElasticSearchPills.tsx
Labels: Jira Synced

#8257 feat: Change home scren order again
  src/app/Scenes/Home/Home.tsx
Labels: Squash On Green

#8256 fix: display contact gallery button on inquireable partners
  src/app/Scenes/Artwork/Artwork.tests.tsx
  src/app/Scenes/Artwork/Artwork.tsx
Labels: Jira Synced

#8254 refactor: fix partner artist list
  src/app/Scenes/Partner/Components/PartnerArtistsList.tsx
  src/app/Scenes/Partner/Components/PartnerOverview.tests.tsx
  src/app/Scenes/Partner/Components/PartnerOverview.tsx
  src/app/Scenes/Partner/Partner.tsx
  src/app/utils/useClientQuery.ts
Labels: Jira Synced

#8232 feat: Curators Pick Emerging home screen rail
  images/curators-picks-header.jpg
  package.json
  src/app/Components/ArtworkRail/ArtworkRail.tsx
  src/app/Components/ArtworkRail/ArtworkRailCard.tsx
  src/app/Scenes/Home/Components/MarketingCollectionRail.tsx
  src/app/Scenes/Home/Home.tsx
  src/app/Scenes/Home/homeAnalytics.ts
  src/app/store/config/features.ts
  src/palette/elements/Touchable/Touchable.tsx
  yarn.lock
Labels: Jira Synced, Squash On Green

#8194 feat: request result email
  src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsTabs/ArtQuizResultsTabsHeader.tsx
Labels: Jira Synced

#8186 feat: explore artworks tab
  src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsTabs/ArtQuizExploreArtworks.tsx
  src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsTabs/ArtQuizResultsTabs.tsx
Labels: Jira Synced

#8264 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#8265 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#8266 refactor: remove dead code part 1 #FF
  .secrets.baseline
  ios/Artsy.xcodeproj/project.pbxproj
  ios/Artsy/App/ARAppDelegate.m
  ios/Artsy/Emission/EigenCommunications/ARTakeCameraPhotoModule.h
  ios/Artsy/Emission/EigenCommunications/ARTakeCameraPhotoModule.m
  src/app/Components/ArtsyWebViewScreens.tsx
  src/app/Components/ArtworkFilter/ArtworkFilterStore.tsx
  src/app/Components/DottedLine.tsx
  src/app/Components/LoadingIndicator.tsx
  src/app/Components/States/ZeroState.tests.tsx
  src/app/Components/constants.ts
  src/app/NativeModules/LegacyNativeModules.tsx
  src/app/NativeModules/triggerCamera.tsx
  src/app/Scenes/Artwork/Components/CommercialButtons/CommercialButtons.tests.tsx
  src/app/Scenes/Artwork/Components/CommercialButtons/CommercialButtons.tsx
  src/app/__fixtures__/ArtistFixture.ts
  src/app/__fixtures__/FairBoothShowFixture.ts
  src/app/utils/Context.tsx
  src/app/utils/convertCityToGeoJSON.ts
  src/app/utils/devCacheBust.ts
  src/app/utils/getTestWrapper.tsx
  src/app/utils/isCloseToBottom.ts
  src/app/utils/track/schema.ts
  src/setupJest.ts
Labels: FF

#8272 refactor: 🧹☠️ cleanup dead code 🧹☠️ pt2
  .secrets.baseline
  src/app/Components/Artist/ArtistInsights/ArtistInsights.tsx
  src/app/Components/ArtworkFilter/Filters/FilterToggleButton.tsx
  src/app/Components/ArtworkFilter/Filters/MultiSelectCheckOption.tsx
  src/app/Components/ArtworkFilter/Filters/SortOptions.tsx
  src/app/Components/ArtworkGrids/SaleArtworkGridItem.tsx
  src/app/Components/ArtworkGrids/__fixtures__/artwork.ts
  src/app/Components/ArtworkRail/SmallArtworkRail.tsx
  src/app/Components/Bidding/Components/BackButton.tsx
  src/app/Components/Bidding/Components/Containers.tsx
  src/app/Components/Bidding/types.ts
  src/app/Components/Show/ShowArtistsPreview.tests.tsx
  src/app/Components/Show/ShowArtistsPreview.tsx
  src/app/Components/Show/ShowArtworksPreview.tests.tsx
  src/app/Components/Show/ShowArtworksPreview.tsx
  src/app/Scenes/Artist/Artist.tsx
  src/app/Scenes/Artwork/ArtworkStore.tsx
  src/app/Scenes/Artwork/Components/ArtworkExtraLinks/index.tsx
  src/app/Scenes/Artwork/Components/CommercialButtons/InquiryButtons.tsx
  src/app/Scenes/Artwork/Components/CommercialButtons/helpers.ts
  src/app/Scenes/Collection/Components/__fixtures__/CollectionFixture.ts
  src/app/Scenes/Collection/Components/__fixtures__/index.ts
  src/app/Scenes/Fair/Components/SimpleTabs.tsx
  src/app/Scenes/Home/Components/HomeFeedOnboardingRail.tsx
  src/app/Scenes/Inbox/Components/Conversations/Avatar.tsx
  src/app/Scenes/Inbox/Components/Conversations/Messages.tsx
  src/app/Scenes/Inbox/Components/Conversations/ZeroStateInbox.tsx
  src/app/Scenes/Map/types.ts
  src/app/Scenes/MyBids/helpers/timely.ts
  src/app/Scenes/MyCollection/Screens/Insights/SelectArtistModal.tsx
  src/app/Scenes/Partner/Components/__fixtures__/PartnerArtwork-fixture.ts
  src/app/Scenes/Sales/Components/SectionHeader.tsx
  src/app/Scenes/SavedSearchAlert/pillExtractors.ts
  src/app/Scenes/SellWithArtsy/Components/TextContainer.tsx
  src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkDetails/validation.ts
  src/app/Scenes/SellWithArtsy/SubmitArtwork/UploadPhotos/utils/index.tsx
  src/app/Scenes/SellWithArtsy/SubmitArtwork/UploadPhotos/utils/uploadPhotoToGemini.ts
  src/app/Scenes/Show/Show.tsx
  src/app/utils/Websockets/auctions/AuctionSocketContext.tsx
  src/app/utils/tests/createMockNetworkLayer/CustomScalars/formatted_number.ts
  src/app/utils/tests/createMockNetworkLayer/index.ts
  src/app/utils/tests/mockTracking.ts
Labels: FF

#8274 feat: Make marketing collection rail header customizable
  images/curators-picks-header.jpg
  src/app/Components/ArtworkRail/ArtworkRail.tsx
  src/app/Scenes/Home/Components/MarketingCollectionRail.tsx
  src/app/Scenes/Home/Home.tsx
  src/app/Scenes/Home/homeAnalytics.ts
Labels: Jira Synced

#8268 feat: art quiz icon animation
  src/app/Scenes/ArtQuiz/ArtQuizArtworks.tsx
  src/app/Scenes/ArtQuiz/ArtQuizButton.tsx
Labels: Jira Synced

#8255 feat: Recently Viewed artwork grid screen
  .secrets.baseline
  src/app/AppRegistry.tsx
  src/app/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx
  src/app/Scenes/Home/Components/ArtworkModuleRail.tsx
  src/app/Scenes/Home/Home.tsx
  src/app/Scenes/RecentlyViewed/RecentlyViewed.tests.tsx
  src/app/Scenes/RecentlyViewed/RecentlyViewed.tsx
  src/app/routes.ts
  src/app/utils/refreshHelpers.tsx
Labels: Jira Synced, Squash On Green

#8279 feat: mark AREnableESOnlySearch as readyForRelease
  src/app/store/config/features.ts
Labels: Jira Synced, Squash On Green

#8280 feat: Adjust Upcoming Auctions rail and screen title
  src/app/Scenes/Home/Home.tsx
  src/app/Scenes/Sales/UpcomingAuctions.tsx
Labels: Jira Synced

#8276 feat: add tracking to home screen rails and improve performance
  src/app/Components/AboveTheFoldFlatList.tsx
  src/app/Components/ArtworkRail/ArtworkRail.tsx
  src/app/Components/Home/ArtistRails/ArtistRail.tsx
  src/app/Components/Home/ArtistRails/RecommendedArtistsRail.tsx
  src/app/Components/LotsByArtistsYouFollowRail/LotsByFollowedArtistsRail.tests.tsx
  src/app/Components/LotsByArtistsYouFollowRail/LotsByFollowedArtistsRail.tsx
  src/app/Scenes/Articles/ArticlesList.tsx
  src/app/Scenes/Home/Components/ArticlesRail.tsx
  src/app/Scenes/Home/Components/ArtworkModuleRail.tsx
  src/app/Scenes/Home/Components/ArtworkRecommendationsRail.tsx
  src/app/Scenes/Home/Components/AuctionResultsRail.tsx
  src/app/Scenes/Home/Components/CollectionsRail.tsx
  src/app/Scenes/Home/Components/ContentCards.tsx
  src/app/Scenes/Home/Components/FairsRail.tsx
  src/app/Scenes/Home/Components/HomeFeedOnboardingRail.tsx
  src/app/Scenes/Home/Components/HomeUpcomingAuctionsRail.tsx
  src/app/Scenes/Home/Components/MarketingCollectionRail.tsx
  src/app/Scenes/Home/Components/NewWorksForYouRail.tsx
  src/app/Scenes/Home/Components/OldCollectionsRail.tsx
  src/app/Scenes/Home/Components/SalesRail.tsx
  src/app/Scenes/Home/Components/ShowsRail.tsx
  src/app/Scenes/Home/Home.tsx
  src/app/Scenes/Home/homeAnalytics.ts
  src/app/Scenes/Home/homeModules.ts
  src/app/Scenes/Sales/UpcomingAuctions.tsx
  src/app/Scenes/ViewingRoom/Components/ViewingRoomsHomeRail.tsx
  src/app/store/config/features.ts
Labels: Jira Synced, Squash On Green

#8237 feat: return to last interacted artwork
  src/app/Scenes/ArtQuiz/ArtQuizArtworks.tsx
  src/app/Scenes/ArtQuiz/ArtQuizNavigation.tsx
  src/app/Scenes/ArtQuiz/ArtQuizWelcome.tsx
  src/app/Scenes/Onboarding/OnboardingQuiz/OnboardingWelcome.tsx
Labels: Jira Synced

#8282 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#8198 feat(pageable): Add ability to page through artworks
  docs/adding_new_components.md
  docs/developing_a_feature.md
  src/app/AppRegistry.tsx
  src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
  src/app/Components/ArtworkGrids/GenericGrid.tests.tsx
  src/app/Components/ArtworkGrids/GenericGrid.tsx
  src/app/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx
  src/app/Components/LotsByArtistsYouFollowRail/LotsByFollowedArtistsRail.tsx
  src/app/Components/PageableScreensView/PageableLazyScreen.tests.tsx
  src/app/Components/PageableScreensView/PageableLazyScreen.tsx
  src/app/Components/PageableScreensView/PageableScreensContext.tests.tsx
  src/app/Components/PageableScreensView/PageableScreensContext.ts
  src/app/Components/PageableScreensView/PageableScreensView.tests.tsx
  src/app/Components/PageableScreensView/PageableScreensView.tsx
  src/app/Scenes/Home/Components/ArtworkModuleRail.tsx
  src/app/Scenes/Home/Components/ArtworkRecommendationsRail.tsx
  src/app/Scenes/Home/Components/NewWorksForYouRail.tsx
  src/app/store/config/features.ts
  src/app/system/navigation/useNavigateToPageableRoute.tests.ts
  src/app/system/navigation/useNavigateToPageableRoute.ts
Labels: Jira Synced, Squash On Green

#8283 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#8120 feat(FX-4539): show unseen notifications count for app badge
  src/app/Scenes/Activity/ActivityItem.tests.tsx
  src/app/Scenes/Activity/ActivityItem.tsx
  src/app/Scenes/Activity/ActivityMarkAllAsReadSection.tsx
  src/app/Scenes/Activity/hooks/useMarkNotificationsAsSeen.ts
  src/app/Scenes/BottomTabs/BottomTabs.tsx
  src/app/Scenes/BottomTabs/BottomTabsModel.ts
  src/app/Scenes/Home/Components/HomeHeader.tests.tsx
  src/app/Scenes/Home/Components/HomeHeader.tsx
Labels: Jira Synced

#8292 fix: Move Home screen articles field to below query
  src/app/Scenes/Home/Home.tsx
Labels: Squash On Green
