Repository artsy/eigen, pull requests merged in 2023-10, with the labels that each got.

#9365 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9366 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9350 feat(ONYX-369): navigate to create alerts instead of filers
  src/app/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
  src/app/Components/Artist/ArtistArtworks/ArtistArtworksFilterHeader.tsx
  src/app/Components/Artist/ArtistArtworks/hooks/useCreateSavedSearchModalFilters.ts
  src/app/Components/ArtworkFilter/ArtworkFilterNavigator.tsx
Labels: Jira Synced

#9376 chore: update copy on create alert artist artworks footer
  src/app/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
Labels: Squash On Green

#9375 feat: opt in InboxQuery to new error middleware
  src/app/system/relay/middlewares/errorMiddleware.ts
Labels: Jira Synced

#9364 build(deps): remove native code + unused pods
  ios/Artsy.xcodeproj/project.pbxproj
  ios/Artsy/App/ARAppDelegate+Emission.m
  ios/Artsy/App/ARAppDelegate.mm
  ios/Artsy/App/ARApplicationShortcutItemDelegate.m
  ios/Artsy/ArtsyUIButtons/ARButtonSubclasses.m
  ios/Artsy/ArtsyUIColors/UIColor+ArtsyColors.h
  ios/Artsy/ArtsyUILabels/Artsy+UILabels.m
  ios/Artsy/Emission/Core/AREmission.m
  ios/Artsy/Emission/Core/AREventsModule.m
  ios/Artsy/Emission/Core/ARScrollViewHelpers.m
  ios/Artsy/Emission/Core/RCTScrollView+Artsy.m
  ios/Artsy/Emission/EigenCommunications/ARNotificationsManager.m
  ios/Artsy/Emission/EigenCommunications/ARPHPhotoPickerModule.m
  ios/Artsy/Emission/OpaqueImageViewComponent/AROpaqueImageViewManager.m
  ios/Artsy/Emission/ViewControllers/ARMapContainerViewController.m
  ios/Artsy/Extraction/ARSpinner.m
  ios/Artsy/NativeModules/ARTNativeScreenPresenterModule.m
  ios/Artsy/NativeModules/ARTOldAdminViewManager.h
  ios/Artsy/NativeModules/ARTOldAdminViewManager.m
  ios/Artsy/NativeModules/OldAdminView.swift
  ios/Artsy/Resources/Artsy-Bridging-Header.h
  ios/Artsy/View_Controllers/ARSerifNavigationViewController.m
  ios/Artsy/View_Controllers/Admin/ARAdminSettingsViewController.h
  ios/Artsy/View_Controllers/Admin/ARAdminSettingsViewController.m
  ios/Artsy/View_Controllers/Admin/ARAdminTableViewController.h
  ios/Artsy/View_Controllers/Admin/ARAdminTableViewController.m
  ios/Artsy/View_Controllers/Admin/AREchoContentsViewController.h
  ios/Artsy/View_Controllers/Admin/AREchoContentsViewController.m
  ios/Artsy/View_Controllers/Admin/Views/ARAdminTableViewCell.h
  ios/Artsy/View_Controllers/Admin/Views/ARAdminTableViewCell.m
  ios/Artsy/View_Controllers/Admin/Views/ARAnimatedTickView.h
  ios/Artsy/View_Controllers/Admin/Views/ARAnimatedTickView.m
  ios/Artsy/View_Controllers/Admin/Views/ARTickedTableViewCell.h
  ios/Artsy/View_Controllers/Admin/Views/ARTickedTableViewCell.m
  ios/Artsy/View_Controllers/Util/Logging/ARLogger.m
  ios/Artsy/Views/AuctionColors.swift
  ios/Artsy/Views/Styled_Subclasses/ARTextView.m
  ios/Artsy/Views/Styled_Subclasses/Buttons/ARBidButton.m
  ios/ArtsyTests/ReferenceImages/ARAnimatedTickViewSpec/deselected@3x.png
  ios/ArtsyTests/ReferenceImages/ARAnimatedTickViewSpec/selected@3x.png
  ios/ArtsyTests/View_Tests/ARAnimatedTickViewTest.m
  ios/Podfile
  ios/Podfile.lock
  src/app/AppRegistry.tsx
  src/app/NativeModules/DevMenuOld.tsx
  src/app/routes.ts
  src/app/system/devTools/DevMenu/DevMenu.tsx
  src/app/system/navigation/routes.tests.ts
Labels: Jira Synced

#9373 feat(DIA-181): add tracking when tapping verified representative
  src/app/Components/Artist/ArtistHeader.tests.tsx
  src/app/Components/Artist/ArtistHeader.tsx
Labels: Jira Synced

#9377 fix: remove third party content key causing upload fails #trivial
  fastlane/Deliverfile
Labels: Squash On Green

#9378 build(deps): bump fastlane-plugin-firebase_app_distribution
  Gemfile.lock
Labels: Squash On Green

#9379 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9381 chore: prep for 8.24.0
  app.json
  ios/Podfile.lock
Labels: Squash On Green

#9382 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9374 feat: opt in artist screen to new error middleware
  src/app/Components/Artist/ArtistHeaderNavRight.tsx
  src/app/Scenes/Artist/Artist.tsx
  src/app/system/relay/middlewares/errorMiddleware.ts
Labels: Jira Synced

#9383 refactor: prevent image requests with falsy height / width
  src/app/Components/OpaqueImageView/OpaqueImageView.tsx
  src/app/Components/OpaqueImageView2/OpaqueImageView2.tsx
Labels: Jira Synced

#9371 fix(alerts): don't include current artwork in suggested inventory
  src/app/Components/Artist/ArtistArtworks/CreateArtworkAlertModal.tests.tsx
  src/app/Components/Artist/ArtistArtworks/CreateArtworkAlertModal.tsx
  src/app/Components/Artist/ArtistArtworks/CreateSavedSearchModal.tsx
  src/app/Scenes/SavedSearchAlert/CreateSavedSearchAlert.tsx
  src/app/Scenes/SavedSearchAlert/SavedSearchAlertModel.ts
  src/app/Scenes/SavedSearchAlert/SavedSearchStore.tsx
  src/app/Scenes/SavedSearchAlert/screens/ConfirmationScreen.tsx
Labels: Jira Synced

#9394 fix: remove embedded vars
  .env.example
  fastlane/Fastfile
  package.json
  scripts/changelog/generateChangelog.ts
  scripts/setup-env-for-ci
  scripts/update-env-for-releases
Labels: Jira Synced

#9393 fix: Update webview progress bar
  src/app/Components/ArtsyWebView.tests.tsx
  src/app/Components/ArtsyWebView.tsx
Labels: Jira Synced

#9396 fix(codepush): don't show update dialog in dev
  src/app/system/codepush.ts
Labels: Squash On Green

#9395 feat(DIA-113): add missing track to some areas of artist screen
  src/app/Components/Artist/Articles/Article.tsx
  src/app/Components/Artist/Articles/Articles.tests.tsx
  src/app/Components/Artist/Articles/Articles.tsx
  src/app/Components/Artist/ArtistAbout/ArtistAbout.tsx
  src/app/Components/Artist/ArtistShows/ArtistShow.tests.tsx
  src/app/Components/Artist/ArtistShows/ArtistShow.tsx
  src/app/Components/Artist/ArtistShows/VariableSizeShowsList.tests.tsx
  src/app/Components/Artist/ArtistShows/VariableSizeShowsList.tsx
  src/app/Components/Artist/RelatedArtistsRail.tests.tsx
  src/app/Components/Artist/RelatedArtistsRail.tsx
  src/app/Components/Artist/RelatedArtistsRailCell.tests.tsx
  src/app/Components/Artist/RelatedArtistsRailCell.tsx
  src/app/Scenes/ArtistShows/ArtistShows2.tests.tsx
  src/app/Scenes/ArtistShows/ArtistShows2.tsx
  src/app/utils/mutations/useFollowArtist.ts
Labels: Jira Synced

#9389 feat: prevent backward navigation when clicking a link in a webview (EMI-1395)
  src/app/Components/ArtsyWebView.tests.tsx
  src/app/Components/ArtsyWebView.tsx
Labels: Jira Synced

#9370 build(ci): preboot simulators
  .circleci/config.yml
Labels: Squash On Green

#9400 build(ci): workflow review
  .circleci/config.yml
  .github/workflows/release-ios-app.yml
  docs/deploy_to_app_store.md
  scripts/release-ios-app
  scripts/release-ios-app-branch
Labels: Jira Synced

#9409 fix: Retire AREnablePriceEstimateRange ff
  src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkAbout/MyCollectionArtworkAboutWork.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtworkAbout.tests.tsx
  src/app/store/config/features.ts
Labels: Jira Synced

#9387 feat: create alerts filters screen
  src/app/Scenes/SavedSearchAlert/Components/AddFilterPill.tsx
  src/app/Scenes/SavedSearchAlert/Components/Form.tsx
  src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterAppliedFilters.tests.tsx
  src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterAppliedFilters.tsx
  src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterPill.tsx
  src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterRarity.tests.tsx
  src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterRarity.tsx
  src/app/Scenes/SavedSearchAlert/CreateSavedSearchAlert.tsx
  src/app/Scenes/SavedSearchAlert/SavedSearchAlertModel.ts
  src/app/Scenes/SavedSearchAlert/SavedSearchStore.tsx
  src/app/Scenes/SavedSearchAlert/helpers.ts
  src/app/Scenes/SavedSearchAlert/screens/SavedSearchFilterScreen.tests.tsx
  src/app/Scenes/SavedSearchAlert/screens/SavedSearchFilterScreen.tsx
Labels: Jira Synced

#9416 feat(DIA-135): add captions and navigation on artworks inside articles
  src/app/Scenes/Article/Components/Sections/ArticleSectionImageCollection/ArticleSectionArtworkCaption.tsx
  src/app/Scenes/Article/Components/Sections/ArticleSectionImageCollection/ArticleSectionArtworkImage.tsx
  src/app/Scenes/Article/Components/Sections/ArticleSectionImageCollection/ArticleSectionImageCollectionCaption.tsx
  src/app/Scenes/Article/Components/Sections/ArticleSectionImageCollection/ArticleSectionImageCollectionImage.tsx
  src/app/Scenes/Article/Components/Sections/ArticleSectionImageCollection/__tests__/ArticleSectionArtworkCaption.tests.tsx
  src/app/Scenes/Article/Components/Sections/ArticleSectionImageCollection/__tests__/ArticleSectionArtworkImage.tests.tsx
  src/app/Scenes/Article/Components/Sections/ArticleSectionImageCollection/__tests__/ArticleSectionImageCollectionCaption.tests.tsx
  src/app/Scenes/Article/Components/Sections/ArticleSectionImageCollection/__tests__/ArticleSectionImageCollectionImage.tests.tsx
Labels: Jira Synced

#9417 build(deps): bump sentry-cli from 2.12.0 to 2.21.2
  package.json
  yarn.lock
Labels: Squash On Green

#9420 fix: Align activity item styling
  src/app/Scenes/Activity/ActivityItem.tsx
  src/app/Scenes/Activity/ActivityItemScreen.tsx
  src/app/Scenes/Activity/ActivityItemTypeLabel.tsx
  src/app/Scenes/Home/Components/ActivityRailItem.tsx
Labels: Jira Synced

#9421 fix: Remove Latest Activity rail header font boldness
  src/app/Components/SectionTitle.tsx
  src/app/Scenes/Home/Components/ActivityRail.tsx
Labels: Jira Synced

#9418 fix: Home Activity Rail padding
  src/app/Scenes/Home/Home.tsx
  src/app/Scenes/Home/useHomeModules.ts
Labels: Jira Synced

#9423 feat: scroll back to artworks grid
  src/app/Scenes/Search/components/AutosuggestSearchResult.tsx
  src/app/routes.ts
Labels: Squash On Green

#9424 build(fix): remove option breaking external distribution
  fastlane/Fastfile
Labels: Squash On Green

#9415 feat: add price range filter to saved searches
  src/app/Components/PriceRange/PriceRangeContainer.tsx
  src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterPriceRange.tests.tsx
  src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterPriceRange.tsx
  src/app/Scenes/SavedSearchAlert/screens/SavedSearchFilterScreen.tsx
Labels: Jira Synced

#9428 fix: replace artist with article ownertype
  src/app/Scenes/Article/ArticleScreen.tsx
Labels: Merge On Green

#9426 feat: Add "Set Filters" button to Alerts filters screen
  src/app/Scenes/SavedSearchAlert/screens/SavedSearchFilterScreen.tsx
Labels: Jira Synced

#9432 feat: add ways to buy saved search filter
  src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterAppliedFilters.tsx
  src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterWaysToBuy.tests.tsx
  src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterWaysToBuy.tsx
  src/app/Scenes/SavedSearchAlert/SavedSearchStore.tsx
  src/app/Scenes/SavedSearchAlert/screens/SavedSearchFilterScreen.tsx
Labels: Squash On Green

#9412 feat: add medium filtering to saved seaches
  src/app/Components/ArtworkFilter/Filters/CategoriesOptions.tsx
  src/app/Components/ArtworkFilter/SavedSearch/types.ts
  src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterAdditionalGeneIDs.tests.tsx
  src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterAdditionalGeneIDs.tsx
  src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterAppliedFilters.tests.tsx
  src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterAppliedFilters.tsx
  src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterPill.tsx
  src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterRarity.tests.tsx
  src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterRarity.tsx
  src/app/Scenes/SavedSearchAlert/SavedSearchAlertForm.tests.tsx
  src/app/Scenes/SavedSearchAlert/pillExtractors.tests.ts
  src/app/Scenes/SavedSearchAlert/pillExtractors.ts
  src/app/Scenes/SavedSearchAlert/screens/ConfirmationScreen.tsx
  src/app/Scenes/SavedSearchAlert/screens/SavedSearchFilterScreen.tsx
  src/app/utils/artworkMediumCategories.ts
Labels: Jira Synced, Squash On Green

#9433 fix: Colour to color
  src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterColor.tests.tsx
  src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterColor.tsx
  src/app/Scenes/SavedSearchAlert/screens/SavedSearchFilterScreen.tsx
Labels: Squash On Green

#9436 feat(ONYX-452): add filters logic to edited saved searches
  src/app/AppRegistry.tsx
  src/app/Scenes/SavedSearchAlert/Components/EditSavedSearchAlertPlaceholder.tsx
  src/app/Scenes/SavedSearchAlert/EditSavedSearchAlert.tsx
  src/app/Scenes/SavedSearchAlert/EditSavedSearchAlertContent.tsx
  src/app/Scenes/SavedSearchAlert/SavedSearchAlertModel.ts
  src/app/Scenes/SavedSearchAlert/screens/SavedSearchFilterScreen.tsx
  src/app/Scenes/SavedSearchAlertsList/Components/SavedSearchesList.tsx
  src/app/Scenes/SavedSearchAlertsList/SavedSearchAlertsList.tsx
Labels: Jira Synced

#9437 fix: saved searches clear all button logic
  src/app/Scenes/SavedSearchAlert/SavedSearchStore.tsx
Labels: Jira Synced, Squash On Green

#9439 chore(ONYX-458): remove uknown edition as a rarity option
  src/app/Components/ArtworkFilter/Filters/AttributionClassOptions.tsx
  src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterRarity.tests.tsx
  src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterRarity.tsx
  src/app/Scenes/SavedSearchAlert/pillExtractors.tests.ts
  src/app/Scenes/SavedSearchAlert/pillExtractors.ts
Labels: Jira Synced

#9446 fix: Filter out notifications without images in Latest Activity rail
  src/app/Scenes/Home/Components/ActivityRail.tsx
  src/app/Scenes/Home/Home.tsx
Labels: Jira Synced

#9450 fix: update typo in promote_beta_android lane
  fastlane/Fastfile
Labels: Squash On Green

#9451 chore: Update app version to 8.25.0
  app.json
Labels: Squash On Green

#9452 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9457 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9453 chore: allow scroll to delete alert button
  src/app/Scenes/SavedSearchAlert/SavedSearchAlertForm.tsx
Labels: Jira Synced

#9456 chore(ONYX-463): save recent price ranges only after saving alert
  src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterPriceRange.tsx
  src/app/Scenes/SavedSearchAlert/SavedSearchAlertForm.tsx
  src/app/Scenes/SavedSearchAlert/containers/CreateSavedSearchContentContainer.tsx
Labels: Jira Synced

#9455 build(deps): bump react-native-screens from 3.23.0 to 3.26.0
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: Squash On Green

#9454 chore: show all mediums in case one medium is selected
  src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterAdditionalGeneIDs.tests.tsx
  src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterAdditionalGeneIDs.tsx
Labels: Jira Synced, Squash On Green

#9462 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9463 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9445 fix: marketing link tracking
  src/app/system/navigation/navigate.ts
  src/app/utils/useDeepLinks.ts
Labels: Jira Synced

#9459 fix: safer fetch plus error reporting
  src/app/Components/ShareSheet/ShareSheet.tsx
  src/app/Components/ShareSheet/helpers.ts
  src/app/store/config/EchoModel.tsx
  src/app/utils/PushNotification.ts
  src/app/utils/googleMaps.ts
Labels: Jira Synced

#9465 build(deps): move dev deps to dev deps on packagejson
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: FF

#9466 chore(cleanup): remove react-nanny dep and Wrap
  package.json
  src/app/utils/Wrap.tests.tsx
  src/app/utils/Wrap.tsx
  yarn.lock
Labels: FF

#9467 build(deps): bump unleash-proxy-client from 2.4.3 to 3.1.0
  package.json
  yarn.lock
Labels: FF

#9471 fix: inquiry message toast padding #trivial
  src/app/Scenes/Artwork/Components/CommercialButtons/InquirySuccessNotification.tsx
Labels: FF

#9470 fix: specify lineHeight to fix badge alignment #trivial
  src/app/Scenes/BottomTabs/BottomTabsButton.tsx
Labels: FF

#9475 feat(onyx-434): Add 'details' text input to create/update alert UI
  src/app/Scenes/SavedSearchAlert/Components/Form.tsx
  src/app/Scenes/SavedSearchAlert/EditSavedSearchAlert.tests.tsx
  src/app/Scenes/SavedSearchAlert/EditSavedSearchAlertContent.tsx
  src/app/Scenes/SavedSearchAlert/SavedSearchAlert.tsx
  src/app/Scenes/SavedSearchAlert/SavedSearchAlertForm.tests.tsx
  src/app/Scenes/SavedSearchAlert/SavedSearchAlertForm.tsx
  src/app/Scenes/SavedSearchAlert/SavedSearchAlertModel.ts
  src/app/store/config/features.ts
Labels: Jira Synced

#9477 chore(ONYX-272): cleanup ff related code
  src/app/Scenes/SavedSearchAlert/Components/Form.tsx
  src/app/Scenes/SavedSearchAlert/CreateSavedSearchAlert.tests.tsx
  src/app/Scenes/SavedSearchAlert/EditSavedSearchAlert.tests.tsx
  src/app/Scenes/SavedSearchAlert/SavedSearchAlertForm.tests.tsx
  src/app/store/config/features.ts
Labels: Jira Synced, Squash On Green

#9478 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9480 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9474 feat(DIA-134): add article slideshow
  src/app/AppRegistry.tsx
  src/app/Scenes/Article/Components/ArticleBody.tsx
  src/app/Scenes/Article/Components/ArticleSection.tsx
  src/app/Scenes/Article/Components/Sections/ArticleSectionImageCollection/ArticleSectionArtworkCaption.tsx
  src/app/Scenes/Article/Components/Sections/ArticleSectionImageCollection/ArticleSectionImageCollection.tsx
  src/app/Scenes/Article/Components/Sections/ArticleSectionImageSet.tsx
  src/app/Scenes/Article/Components/Sections/ArticleSectionText.tsx
  src/app/Scenes/Article/Components/Sections/__tests__/ArticleSectionImageSet.tests.tsx
  src/app/Scenes/Article/Components/Sections/__tests__/ArticleSectionText.tests.tsx
  src/app/Scenes/Article/Components/__tests__/ArticleBody.tests.tsx
  src/app/Scenes/ArticleSlideShow/ArticleSlideShow.tsx
  src/app/Scenes/ArticleSlideShow/Components/ArticleSlideShow.tsx
  src/app/Scenes/ArticleSlideShow/Components/ArticleSlideShowCaption.tsx
  src/app/Scenes/ArticleSlideShow/Components/ArticleSlideShowImage.tsx
  src/app/Scenes/ArticleSlideShow/Components/__tests__/ArticleSlideShow.tests.tsx
  src/app/Scenes/ArticleSlideShow/Components/__tests__/ArticleSlideShowCaption.tests.tsx
  src/app/Scenes/ArticleSlideShow/Components/__tests__/ArticleSlideShowImage.tests.tsx
  src/app/routes.ts
  src/app/store/config/features.ts
Labels: Jira Synced

#9487 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9490 feat(DIA-203): adjust Artist header image ratio and minor font and spacing values
  src/app/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
  src/app/Components/Artist/ArtistHeader.tsx
  src/app/Scenes/Artist/Artist.tsx
  src/app/utils/hardware.ts
Labels: Jira Synced

#9483 fix: Hide default price range in Recent price ranges
  src/app/Components/ArtworkFilter/RecentPriceRanges.tsx
Labels: Jira Synced

#9493 feat(DIA-189): show the Partner name in all rails' cells
  src/app/Components/ArtworkRail/ArtworkRail.tsx
Labels: Jira Synced

#9484 fix(ONYX-473): UI improvements to the new Create Alert modal
  src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterAdditionalGeneIDs.tsx
  src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterAppliedFilters.tsx
  src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterColor.tsx
  src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterPriceRange.tsx
  src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterRarity.tsx
  src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterWaysToBuy.tsx
Labels: Jira Synced

#9495 chore: replace error emoji with warning for codepush
  fastlane/utility_fastlane.rb
Labels: Squash On Green

#9488 build(deps): bump react-native from 0.70.13 to 0.70.14
  .circleci/config.yml
  Gemfile
  Gemfile.lock
  ios/Artsy.xcodeproj/project.pbxproj
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: Jira Synced

#9497 chore: update rn patch #trivial
  patches/react-native+0.70.14.patch
Labels: Squash On Green

#9499 chore: set alerts filters as ready for release
  src/app/Scenes/SavedSearchAlert/Components/Form.tsx
  src/app/store/config/features.ts
Labels: Squash On Green

#9503 fix: Update changelogTemplateSections import in danger.ts
  dangerfile.ts
Labels: Squash On Green

#9501 fix: remove redundant ArtsyKeyboardAvoidingView
  src/app/Scenes/SavedSearchAlert/screens/SavedSearchFilterScreen.tsx
Labels: Squash On Green

#9507 fix: line break when size filter is enabled
  src/app/Scenes/SavedSearchAlert/Components/Form.tsx
Labels: Squash On Green

#9491 refactor: replace isPad function with isTablet
  src/app/Components/Artist/ArtistAbout/ArtistAboutRelatedGenes.tsx
  src/app/Components/Artist/ArtistHeader.tsx
  src/app/Components/Artist/ArtistShows/VariableSizeShowsList.tsx
  src/app/Components/ArtworkGrids/GenericGrid.tsx
  src/app/Components/ArtworkRail/ArtworkRail.tsx
  src/app/Components/ArtworkRail/useExtraLargeWidth.tsx
  src/app/Components/AutosuggestResults/AutosuggestResults.tsx
  src/app/Components/Containers/Inquiry.tsx
  src/app/Components/ContextMenu/ContextMenuArtworkPreviewCard.tsx
  src/app/Components/HeaderArtworksFilter/HeaderArtworksFilter.tsx
  src/app/Components/Home/HeroUnit.tsx
  src/app/Components/LotsByArtistsYouFollowRail/LotsByFollowedArtistsRail.tsx
  src/app/Components/RelatedArtists/RelatedArtists.tsx
  src/app/Scenes/Articles/ArticlesList.tsx
  src/app/Scenes/Artwork/Components/ImageCarousel/ImageCarousel.tsx
  src/app/Scenes/Artwork/Components/ImageCarousel/ImageCarouselEmbedded.tsx
  src/app/Scenes/Artwork/helpers.ts
  src/app/Scenes/ArtworkLists/ArtworkLists.tsx
  src/app/Scenes/ArtworkLists/useArtworkListsColCount.ts
  src/app/Scenes/Feature/Feature.tsx
  src/app/Scenes/Feature/components/FeatureHeader.tsx
  src/app/Scenes/GalleriesForYou/Components/PartnerListItem.tsx
  src/app/Scenes/GalleriesForYou/GalleriesForYouScreen.tsx
  src/app/Scenes/Gene/Gene.tsx
  src/app/Scenes/Home/Components/ArticlesRail.tsx
  src/app/Scenes/Home/Components/GalleriesForYouBanner.tsx
  src/app/Scenes/Home/Home.tsx
  src/app/Scenes/Inbox/Components/ActiveBids/ActiveBid.tsx
  src/app/Scenes/Inbox/Components/Conversations/Messages.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormAddPhotos.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkList/MyCollectionArtworkGridItem.tsx
  src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightBottomSheet.tsx
  src/app/Scenes/MyCollection/Screens/Insights/Components/MyCollectionSelectArtist.tsx
  src/app/Scenes/MyCollection/Screens/MyCollectionAddCollectedArtists/MyCollectionAddCollectedArtistsAutosuggest.tsx
  src/app/Scenes/Search/CuratedCollectionItem.tsx
  src/app/Scenes/Search/Search.tsx
  src/app/Scenes/Search/TrendingArtists.tsx
  src/app/Scenes/Search/components/EntitySearchResults.tsx
  src/app/Scenes/Search/components/placeholders/SearchPlaceholder.tsx
  src/app/Scenes/SellWithArtsy/Components/CollectorsNetwork.tsx
  src/app/Scenes/SellWithArtsy/Components/FAQSWA.tsx
  src/app/Scenes/SellWithArtsy/Components/Footer.tsx
  src/app/Scenes/SellWithArtsy/Components/Header.tsx
  src/app/Scenes/SellWithArtsy/Components/MeetTheSpecialists.tsx
  src/app/Scenes/SellWithArtsy/Components/SpeakToTheTeam.tsx
  src/app/Scenes/SellWithArtsy/Components/Testimonials.tsx
  src/app/Scenes/ViewingRoom/Components/ViewingRoomsHomeRail.tsx
  src/app/system/navigation/NavStack.tsx
  src/app/utils/hardware.tests.ts
  src/app/utils/hardware.ts
Labels: Squash On Green

#9508 build(deps-REVERT): bump react-native from 0.70.13 to 0.70.14
  .circleci/config.yml
  Gemfile
  Gemfile.lock
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: Squash On Green

#9509 fix(ONYX-477): add hideSaveIcon to the artworks grid
  src/app/Scenes/SavedSearchAlert/screens/ConfirmationScreen.tsx
Labels: Jira Synced

#9512 fix: flaky native test #trivial
  ios/ArtsyTests/View_Controller_Tests/Live_Auction/LiveAuctionLotViewControllerTests.swift
Labels: Jira Synced, Squash On Green

#9513 chore: update node to current #trivial
  .circleci/config.yml
  .nvmrc
  .tool-versions
  src/app/Scenes/Inbox/Components/Conversations/Messages.tests.tsx
Labels: Squash On Green

#9518 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green
