Repository artsy/eigen, pull requests merged in 2023-08, with the labels that each got.

#9101 fix: Save artist details correctly when creating an artwork
  src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/methods/uploadArtwork.ts
  src/app/Scenes/MyCollection/mutations/createArtist.ts
Labels: Jira Synced

#9099 chore: make long press menu preview full width
  src/app/Components/ArtworkRail/ArtworkRailCard.tsx
  src/app/Components/ContextMenu/ContextMenuArtwork.tsx
  src/app/Components/ContextMenu/ContextMenuArtworkPreviewCard.tsx
Labels: Jira Synced, Squash On Green

#9104 fix: Adjust "Remove artist" copy
  src/app/Scenes/MyCollection/Components/MyCollectionBottomSheetModals/MyCollectionBottomSheetModalArtistPreview.tsx
Labels: Squash On Green

#9079 build(deps): bump react-native-reanimated from 2.13 to 3.3.0
  ios/Podfile.lock
  package.json
  src/app/Scenes/ArtQuiz/ArtQuizArtworks.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionSearchBar.tsx
  src/setupJest.tsx
  yarn.lock
Labels: Jira Synced, Squash On Green, FF

#9106 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9093 feat(ONYX-61): update MyC empty state screen and MyC onboarding
  images/homefeed-my-collection-onboarding-0.webp
  images/homefeed-my-collection-onboarding-0@2x.webp
  images/homefeed-my-collection-onboarding-0@3x.webp
  images/homefeed-my-collection-onboarding-1.webp
  images/homefeed-my-collection-onboarding-1@2x.webp
  images/homefeed-my-collection-onboarding-1@3x.webp
  images/myCollection-onboarding-image-1.webp
  images/myCollection-onboarding-image-1@2x.webp
  images/myCollection-onboarding-image-1@3x.webp
  images/myCollection-onboarding-image-4.webp
  images/myCollection-onboarding-image-4@2x.webp
  images/myCollection-onboarding-image-4@3x.webp
  src/app/Scenes/Home/Components/HomeFeedModalCarousel/HomeFeedModalCarousel.tsx
  src/app/Scenes/Home/Components/HomeFeedOnboardingRail.tsx
  src/app/Scenes/Home/Components/MeetYourNewAdvisorRail.tsx
  src/app/Scenes/Home/Components/ModalCarouselComponents/ModalCarousel.tests.tsx
  src/app/Scenes/Home/Components/ModalCarouselComponents/ModalCarousel.tsx
  src/app/Scenes/Home/Components/ModalCarouselComponents/ModalCarouselContainer.tsx
  src/app/Scenes/Home/Components/ModalCarouselComponents/ModalCarouselScreenWrapper.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionZeroState.tsx
Labels: Jira Synced, Squash On Green

#9057 refactor: remove remains of scrollable-tab-view
  HACKS.md
  package.json
  patches/react-native-scrollable-tab-view+1.0.0.patch
  src/app/Components/Containers/Inbox.tests.tsx
  src/app/Components/Containers/Inbox.tsx
  src/app/Scenes/City/City.tsx
  src/app/Scenes/City/Components/AllEvents.tsx
  src/app/Scenes/City/Components/Event/index.tsx
  src/app/Scenes/City/Components/EventList.tsx
  src/app/Scenes/City/Components/EventSection/index.tsx
  src/app/Scenes/City/Components/FairEventSection/index.tsx
  src/app/Scenes/City/Components/SavedEventSection/index.tsx
  src/app/Scenes/Inbox/Components/Conversations/Conversations.tsx
  src/app/Scenes/Inbox/Components/Conversations/NoMessages.tsx
  src/app/Scenes/MyBids/MyBids.tsx
  src/setupJest.tsx
  yarn.lock
Labels: Jira Synced

#9109 chore: Type my collection mutations correctly
  src/app/Scenes/MyCollection/mutations/createArtist.ts
  src/app/Scenes/MyCollection/mutations/createUserInterests.ts
  src/app/Scenes/MyCollection/mutations/updateUserInterest.ts
Labels: Squash On Green

#9107 fix: Artist list item meta text
  src/app/Components/ArtistListItem.tsx
Labels: Jira Synced, Squash On Green

#9117 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9119 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9095 chore: Enable ARShowCollectedArtistOnboarding and AREnableMyCollectionCollectedArtists
  src/app/store/config/features.ts
Labels: Jira Synced

#9122 feat(ONYX-214): add zero state for collected artsits search results
  src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtistsView.tsx
Labels: Jira Synced

#9121 fix(ONYX-213): reload MyCollection when setting and unsetting the privacy toggle
  src/app/Scenes/MyCollection/Components/MyCollectionBottomSheetModals/MyCollectionBottomSheetModalArtistPreview.tsx
Labels: Jira Synced, Squash On Green

#9125 fix: inbox empty state
  src/app/Scenes/Inbox/Components/Conversations/Conversations.tsx
Labels: Squash On Green

#9130 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9132 fix: disable tab scroll on Profile screen
  src/app/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx
Labels: Jira Synced, Squash On Green

#9134 docs: add android emulator wifi section [skip ci]
  docs/getting_started.md
Labels: Squash On Green

#9133 feat: add flipper performance monitor plugin
  android/app/src/debug/java/net/artsy/app/ReactNativeFlipper.java
  docs/debugging.md
  ios/Artsy/App/ARAppDelegate.mm
  ios/Podfile.lock
  package.json
  scripts/build-for-tests-ios
  yarn.lock
Labels: Squash On Green

#9127 chore: check-code ci job uses danger-github-oss context
  .circleci/config.yml
Labels: Jira Synced

#9139 fix: Partner shows rail padding
  src/app/Scenes/Partner/Components/PartnerShows.tsx
Labels: Jira Synced

#9140 fix: pass GCC_PREPROCESSOR_DEFINITIONS flag to skip flipper on test ios job
  scripts/test-ios
Labels: Squash On Green

#9141 fix(ONYX-221): fix margin
  src/app/Scenes/MyCollection/Components/MyCollectionBottomSheetModals/MyCollectionBottomSheetModalArtistPreview.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionBottomSheetModals/MyCollectionBottomSheetModalArtistPreview/ArtistKindPills.tsx
Labels: Jira Synced, Squash On Green

#9143 fix(ONYX-225): show showAddToMyCollectionBottomSheet on the MyC empty state
  src/app/Components/LoadFailureView.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionZeroState.tsx
Labels: Jira Synced

#9142 fix(ONYX-224): add refreshControl to the MyC empty state
  src/app/Scenes/MyCollection/MyCollection.tsx
Labels: Jira Synced

#9151 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9155 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9153 chore(ONYX-138): Remove "Recommended" artwork grid sort on show/booth pages
  src/app/Components/ArtworkFilter/Filters/SortOptions.tsx
Labels: Jira Synced

#9157 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9158 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9159 chore: Update app version to 8.19.0
  app.json
Labels: Squash On Green

#9161 fix: My Collection artwork form test
  .secrets.baseline
  src/app/Scenes/Home/Components/ModalCarouselComponents/ModalCarousel.tests.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionSearchBar.tests.tsx
  src/app/Scenes/MyCollection/MyCollection.tests.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tests.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormMain.tests.tsx
Labels: Squash On Green

#9152 feat(ONYX-60): Collected Artists tooltip onboarding
  src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtistsOnboardingModal.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtistsRail.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionStickyHeader.tsx
  src/app/Scenes/MyCollection/MyCollection.tsx
  src/app/Scenes/MyCollection/Screens/Insights/MedianAuctionPriceListItem.tsx
  src/app/store/config/visualClues.ts
Labels: Jira Synced, Squash On Green

#9170 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9171 feat(onyx-251): create AREnableAuctionHeaderAlertCTA feature flag
  src/app/Scenes/Artwork/Artwork.tsx
  src/app/Scenes/Artwork/ArtworkAuctionCreateAlertHeader.tsx
  src/app/store/config/features.ts
Labels: Jira Synced

#9176 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9173 fix: do not show artwork lists prompt during the onboarding
  src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
  src/app/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx
  src/app/Scenes/Onboarding/OnboardingQuiz/OnboardingMarketingCollection.tsx
Labels: Jira Synced

#9181 fix: reflect rarity changes after editing an artwork
  src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tsx
Labels: Jira Synced

#9183 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9185 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9186 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9165 feat: Use generated displayName in Saved Search form
  src/app/Components/Artist/ArtistArtworks/CreateArtworkAlertModal.tests.tsx
  src/app/Components/Artist/ArtistArtworks/CreateArtworkAlertModal.tsx
  src/app/Components/Artist/ArtistArtworks/CreateSavedSearchModal.tests.tsx
  src/app/Components/ArtworkFilter/ArtworkFilterNavigator.tsx
  src/app/Components/ArtworkFilter/SavedSearch/searchCriteriaHelpers.tests.ts
  src/app/Components/ArtworkFilter/SavedSearch/types.ts
  src/app/Scenes/SavedSearchAlert/Components/Form.tsx
  src/app/Scenes/SavedSearchAlert/Components/SavedSearchNameInput.tsx
  src/app/Scenes/SavedSearchAlert/CreateSavedSearchAlert.tests.tsx
  src/app/Scenes/SavedSearchAlert/EditSavedSearchAlert.tests.tsx
  src/app/Scenes/SavedSearchAlert/EditSavedSearchAlert.tsx
  src/app/Scenes/SavedSearchAlert/SavedSearchAlert.tsx
  src/app/Scenes/SavedSearchAlert/SavedSearchAlertForm.tests.tsx
  src/app/Scenes/SavedSearchAlert/SavedSearchAlertModel.ts
  src/app/Scenes/SavedSearchAlert/SavedSearchStore.tsx
  src/app/Scenes/SavedSearchAlert/helpers.ts
  src/app/Scenes/SavedSearchAlert/screens/AlertPriceRangeScreen.tests.tsx
  src/app/Scenes/SavedSearchAlert/screens/ConfirmationScreen.tests.tsx
  src/app/Scenes/SavedSearchAlertsList/Components/SavedSearchesList.tsx
  src/app/store/config/features.ts
Labels: Jira Synced, Squash On Green

#9164 chore(ONYX-13, ONYX-12): remove old saves implementation
  src/app/Components/ArtworkLists/useSaveArtworkToArtworkLists.ts
  src/app/Scenes/Artwork/Components/ArtworkActions.tests.tsx
  src/app/Scenes/Favorites/FavoriteArtworks.tsx
  src/app/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx
  src/app/utils/mutations/useLegacySaveArtwork.ts
  src/app/utils/mutations/useSaveArtwork.ts
Labels: Jira Synced, Squash On Green

#9135 feat: performant masonry grids on ArtistArtworks grid
  ios/Podfile.lock
  package.json
  src/app/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
  src/app/Components/Artist/ArtistArtworks/hooks/useShowArtworksFilterModal.ts
  src/app/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx
  src/app/Scenes/Artist/ArtistSavedSearch.tests.tsx
  src/app/utils/tests/getMockCollapsibleTabView.tsx
  src/setupJest.tsx
  yarn.lock
Labels: Jira Synced, Squash On Green

#9192 build(deps): update ruby deps
  Gemfile.lock
Labels: Squash On Green

#9193 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9198 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9194 build(deps): get rid of jsc-android
  android/app/build.gradle
  android/build.gradle
  package.json
  yarn.lock
Labels: Jira Synced

#9199 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9179 feat(onyx-252): Auction header alert CTA - display correct data and create alert button
  src/app/Scenes/Artwork/Artwork.tsx
  src/app/Scenes/Artwork/ArtworkAuctionCreateAlertHeader.tsx
Labels: Jira Synced, Squash On Green

#9202 chore: cleanup of iOS intl polyfills
  package.json
  src/app/App.tsx
  yarn.lock
Labels: Jira Synced, Squash On Green

#9207 feat: refactor navigate to on dev menu to work on android
  src/app/utils/DevMenu.tsx
Labels: Squash On Green

#9204 feat(ONYX-273): hide Create Alert CTA in the auction header
  src/app/Scenes/Artwork/ArtworkAuctionCreateAlertHeader.tsx
  src/app/Scenes/Artwork/Components/ArtworkScreenHeaderCreateAlert.tsx
  src/app/Scenes/Artwork/helpers.ts
  src/app/Scenes/Artwork/utils/hasBiddingEnded.tsx
  src/app/Scenes/Artwork/utils/isLotClosed.tsx
Labels: Jira Synced

#9210 chore: Fix CreateSavedSearchAlert tests after enabling feature flag
  src/app/Components/Artist/ArtistArtworks/CreateSavedSearchModal.tests.tsx
  src/app/Scenes/SavedSearchAlert/CreateSavedSearchAlert.tests.tsx
  src/app/Scenes/SavedSearchAlert/SavedSearchAlertForm.tests.tsx
Labels: Squash On Green

#9209 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9212 feat: copy change for My Collection > Collected Artists onboarding
  src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtistsOnboardingModal.tsx
Labels: Jira Synced
