Repository artsy/eigen, pull requests merged in 2023-05, with the labels that each got.

#8601 fix: move flag out of session state so it stays between sessions
  src/app/Scenes/Home/HomeContainer.tsx
  src/app/store/AuthModel.ts
  src/app/store/__tests__/migration.tests.ts
  src/app/store/migration.ts
  src/app/utils/PushNotification.ts
Labels: Squash On Green

#8605 fix: downgrade reanimated
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: Squash On Green

#8583 feat: artwork list screen with dummy data
  src/app/Scenes/ArtworkLists/ArtworkListItem.tsx
  src/app/Scenes/ArtworkLists/ArtworkLists.tsx
  src/app/Scenes/ArtworkLists/ArtworkNoImage.tsx
  src/app/Scenes/ArtworkLists/FourUpImageLayout.tsx
  src/app/Scenes/ArtworkLists/StackedImageLayout.tsx
  src/app/Scenes/ArtworkLists/components/ArtworkListImage.tsx
  src/app/Scenes/ArtworkLists/components/ArtworkListImageBorder.tsx
  src/app/Scenes/ArtworkLists/components/ArtworkListNoImage.tsx
  src/app/Scenes/ArtworkLists/dummyData.ts
  src/app/Scenes/ArtworkLists/useArtworkListsColCount.ts
Labels: Jira Synced

#8610 chore(tracking): track unable to load
  src/app/Components/LoadFailureView.tsx
Labels: Jira Synced

#8613 fix(artwork): Make pager more performant
  src/app/Components/PageableScreensView/PageableLazyScreen.tests.tsx
  src/app/Components/PageableScreensView/PageableLazyScreen.tsx
  src/app/Components/PageableScreensView/PageableScreensContext.tests.tsx
  src/app/Components/PageableScreensView/PageableScreensContext.ts
  src/app/Components/PageableScreensView/PageableScreensView.tests.tsx
  src/app/Scenes/Artwork/Artwork.tsx
Labels: Jira Synced, Squash On Green

#8619 chore: make my c auction results query optional
  src/app/Scenes/MyCollection/Screens/Insights/AuctionResultsForArtistsYouCollect.tsx
Labels: Squash On Green

#8615 refactor: useCreateArtworkAlert hook to reuse functionality
  src/app/Scenes/Artwork/Artwork.tests.tsx
  src/app/Scenes/Artwork/Artwork.tsx
  src/app/Scenes/Artwork/Components/ArtworkScreenHeader.tests.tsx
  src/app/Scenes/Artwork/Components/ArtworkScreenHeader.tsx
  src/app/Scenes/Artwork/Components/ArtworkScreenHeaderCreateAlert.tsx
  src/app/Scenes/Artwork/Components/CreateArtworkAlertButtonsSection.tests.tsx
  src/app/Scenes/Artwork/Components/CreateArtworkAlertButtonsSection.tsx
  src/app/utils/hooks/useCreateArtworkAlert.ts
Labels: Squash On Green

#8620 feat: enable react/jsx-no-leaked-render eslint rule
  .eslintrc.js
Labels: Squash On Green

#8617 chore: add empty state screens and implement filtering logic [part 1]
  .secrets.baseline
  images/my-collection-empty-state.webp
  images/my-collection-empty-state@2x.webp
  images/my-collection-empty-state@3x.webp
  src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtistsRail.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionStickyHeader.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionZeroState.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionZeroStateArtworks.tsx
  src/app/Scenes/MyCollection/MyCollection.tests.tsx
  src/app/Scenes/MyCollection/MyCollection.tsx
  src/app/Scenes/MyCollection/MyCollectionArtworks.tsx
  src/app/Scenes/MyCollection/State/MyCollectionTabsStore.tsx
  src/app/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx
  src/app/Scenes/SellWithArtsy/Components/MeetTheSpecialists.tsx
Labels: Jira Synced, Squash On Green

#8614 feat: Query and render real artwork lists for artwork lists screen
  src/app/Scenes/ArtworkLists/ArtworkListItem.tsx
  src/app/Scenes/ArtworkLists/ArtworkLists.tests.tsx
  src/app/Scenes/ArtworkLists/ArtworkLists.tsx
  src/app/Scenes/ArtworkLists/FourUpImageLayout.tsx
  src/app/Scenes/ArtworkLists/dummyData.ts
  src/app/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx
Labels: Jira Synced, Squash On Green

#8625 fix: update palette for reanimated crashes #trivial
  package.json
  yarn.lock
Labels: Squash On Green

#8607 feat(FX-4759): Display toast with actions summary for artwork lists flow
  src/app/Components/ArtworkLists/ArtworkListsContext.tests.tsx
  src/app/Components/ArtworkLists/ArtworkListsContext.tsx
  src/app/Components/ArtworkLists/components/ArtworkInfo.tests.tsx
  src/app/Components/ArtworkLists/components/ArtworkInfo.tsx
  src/app/Components/ArtworkLists/types.ts
  src/app/Components/ArtworkLists/useArtworkListsToast.ts
  src/app/Components/ArtworkLists/useSaveArtworkToArtworkLists.ts
  src/app/Components/ArtworkLists/views/CreateNewArtworkListView/CreateNewArtworkListView.tests.tsx
  src/app/Components/ArtworkLists/views/CreateNewArtworkListView/components/CreateNewArtworkListForm.tsx
  src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/components/ArtworkListItem.tsx
  src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/components/ArtworkLists.tsx
  src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/components/SelectArtworkListsForArtworkFooter.tsx
Labels: Jira Synced

#8630 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#8623 feat: Replace showsByFollowedArtists with showsConnection for the "Shows for You" rail
  src/app/Scenes/Home/Components/ShowsRail.tests.tsx
  src/app/Scenes/Home/Home.tsx
  src/app/Scenes/Home/useHomeModules.ts
Labels: Jira Synced

#8631 feat(CX-3636): create add to my collection bottom sheet
  src/app/AppRegistry.tsx
  src/app/Components/ArtworkLists/components/AutomountedBottomSheetModal.tsx
  src/app/Components/BottomSheet/DefaultBottomSheetBackdrop.tsx
  src/app/Components/MenuItem.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionBottomSheetModals/MyCollectionBottomSheetModalAdd.tests.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionBottomSheetModals/MyCollectionBottomSheetModalAdd.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionBottomSheetModals/MyCollectionBottomSheetModals.tests.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionBottomSheetModals/MyCollectionBottomSheetModals.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionStickyHeader.tsx
  src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightBottomSheet.tsx
  src/app/Scenes/MyCollection/Screens/Insights/Components/CareerHighlightBottomSheetItem.tsx
  src/app/Scenes/MyCollection/State/MyCollectionTabsStore.tsx
  src/app/Scenes/MyProfile/MyProfileHeader.tsx
  src/app/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx
  src/app/Scenes/MyProfile/__tests__/MyProfileHeaderMyCollectionAndSavedWorks.tests.tsx
Labels: Jira Synced, Squash On Green

#8591 Fix(CX-3612): Fix Artwork Save Tracking on Home Rails and Grids
  src/app/Components/Artist/ArtistArtworks/ArtistNotableWorksRail.tests.tsx
  src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
  src/app/Components/ArtworkGrids/GenericGrid.tsx
  src/app/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx
  src/app/Components/ArtworkRail/ArtworkRail.tsx
  src/app/Components/ArtworkRail/ArtworkRailCard.tsx
  src/app/Components/ArtworkRail/LargeArtworkRail.tsx
  src/app/Components/ArtworkRail/SmallArtworkRail.tsx
  src/app/Scenes/Artwork/Components/ArtworksInSeriesRail.tests.tsx
  src/app/Scenes/Artwork/Components/OtherWorks/OtherWorks.tsx
  src/app/Scenes/ArtworkRecommendations/ArtworkRecommendations.tsx
  src/app/Scenes/Home/Components/ArtworkModuleRail.tsx
  src/app/Scenes/Home/Components/ArtworkRecommendationsRail.tsx
  src/app/Scenes/Home/Components/AuctionResultsRail.tsx
  src/app/Scenes/Home/Components/MarketingCollectionRail.tsx
  src/app/Scenes/Home/Components/NewWorksForYouRail.tsx
  src/app/Scenes/Home/Home.tsx
  src/app/Scenes/Home/useHomeModules.ts
  src/app/Scenes/NewWorksForYou/NewWorksForYou.tsx
  src/app/Scenes/NewWorksFromGalleriesYouFollow/NewWorksFromGalleriesYouFollow.tsx
  src/app/Scenes/RecentlyViewed/RecentlyViewed.tsx
  src/app/Scenes/SimilarToRecentlyViewed/SimilarToRecentlyViewed.tsx
  src/app/utils/mutations/useSaveArtwork.ts
  src/app/utils/refreshHelpers.tsx
  src/app/utils/track/ArtworkActions.ts
Labels: Jira Synced

#8640 fix: solve safe area issues on my collection
  src/app/Scenes/MyCollection/MyCollection.tsx
  src/app/Scenes/MyProfile/MyProfileHeader.tsx
  src/app/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx
Labels: Squash On Green

#8639 fix: Use standard header for Contact screen to avoid back button overlapping text
  src/app/Scenes/SellWithArtsy/ConsignmentInquiry/ConsignmentInquiryForm.tsx
  src/app/Scenes/SellWithArtsy/ConsignmentInquiry/ConsignmentInquiryScreen.tsx
Labels: Jira Synced

#8637 refactor(context): Decouple create alert and colocate context menu code
  src/app/Components/Artist/ArtistArtworks/CreateArtworkAlertModal.tests.tsx
  src/app/Components/Artist/ArtistArtworks/CreateArtworkAlertModal.tsx
  src/app/Components/Artist/ArtistArtworks/CreateSavedSearchModal.tsx
  src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
  src/app/Components/ArtworkRail/ArtworkRailCard.tsx
  src/app/Components/ContextMenu/ContextMenuArtwork.tsx
  src/app/Components/ContextMenu/useArtworkContextMenu.ts
  src/app/Scenes/Artwork/Artwork.tsx
  src/app/Scenes/Artwork/Components/ArtworkScreenHeader.tests.tsx
  src/app/Scenes/Artwork/Components/ArtworkScreenHeaderCreateAlert.tsx
Labels: Squash On Green

#8643 chore: remove lockfile removal in script, prevent unnecessary installation #trivial
  scripts/setup-fastlane-env
Labels: Squash On Green

#8644 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#8627 feat(FX-4762): Support CTA in Toast
  src/app/Components/ArtworkLists/useArtworkListsToast.ts
  src/app/Components/Toast/ToastComponent.tsx
  src/app/Components/Toast/types.ts
Labels: Jira Synced

#8636 fix: use the same relay env between Home screen and `useMutation`
  src/app/Components/Artist/ArtistHeader.tsx
  src/app/Components/ArtworkLists/useSaveArtworkToArtworkLists.ts
  src/app/Components/ArtworkRail/ArtworkRailCard.tsx
  src/app/Scenes/Home/Home.tests.tsx
  src/app/Scenes/Home/Home.tsx
  src/app/utils/mutations/useSaveArtwork.ts
  src/app/utils/refreshHelpers.tsx
Labels: Jira Synced, Squash On Green

#8653 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#8657 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#8641 build(deps): update to RN 0.69.10
  .circleci/config.yml
  .gitignore
  .secrets.baseline
  Gemfile
  Gemfile.lock
  HACKS.md
  android/app/build.gradle
  android/app/src/debug/AndroidManifest.xml
  android/app/src/debug/java/net/artsy/app/ReactNativeFlipper.java
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/net/artsy/app/MainActivity.java
  android/app/src/main/java/net/artsy/app/MainApplication.java
  android/app/src/main/java/net/artsy/app/utils/newarchitecture/MainApplicationReactNativeHost.java
  android/app/src/main/java/net/artsy/app/utils/newarchitecture/components/MainComponentsRegistry.java
  android/app/src/main/java/net/artsy/app/utils/newarchitecture/modules/MainApplicationTurboModuleManagerDelegate.java
  android/app/src/main/jni/Android.mk
  android/app/src/main/jni/MainApplicationModuleProvider.cpp
  android/app/src/main/jni/MainApplicationModuleProvider.h
  android/app/src/main/jni/MainApplicationTurboModuleManagerDelegate.cpp
  android/app/src/main/jni/MainApplicationTurboModuleManagerDelegate.h
  android/app/src/main/jni/MainComponentsRegistry.cpp
  android/app/src/main/jni/MainComponentsRegistry.h
  android/app/src/main/jni/OnLoad.cpp
  android/build.gradle
  android/gradle.properties
  android/gradle/wrapper/gradle-wrapper.properties
  android/gradlew
  android/settings.gradle
  ios/.xcode.env
  ios/Artsy.xcodeproj/project.pbxproj
  ios/Artsy/App/ARAppDelegate.mm
  ios/Podfile
  ios/Podfile.lock
  package.json
  patches/@segment+analytics-react-native-appboy+1.5.0.patch
  patches/react-native+0.67.5.patch
  patches/react-native+0.69.10.patch
  patches/react-native-credit-card-input+0.4.1.patch
  patches/react-native-scrollable-tab-view+1.0.0.patch
  src/app/Scenes/Article/ArticleScreen.tests.tsx
  src/app/Scenes/Article/Components/Sections/ArticleSectionImageCollection/ArticleSectionImageCollection.tsx
  src/app/Scenes/Artwork/Components/CommercialButtons/InquiryButtons.tests.tsx
  src/app/Scenes/Sale/SaleHeader.tests.tsx
  src/app/utils/placeholders.tsx
  yarn.lock
Labels: Jira Synced

#8645 feat: Artwork list screen
  src/app/AppRegistry.tsx
  src/app/Scenes/ArtworkList/ArtworkList.tests.tsx
  src/app/Scenes/ArtworkList/ArtworkList.tsx
  src/app/Scenes/ArtworkList/ArtworkListArtworksGridHeader.tsx
  src/app/Scenes/ArtworkList/ArtworkListHeader.tsx
  src/app/Scenes/ArtworkLists/ArtworkListItem.tsx
  src/app/routes.ts
Labels: Jira Synced

#8663 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#8664 fix: Adjust Meet the Specialists filtering
  src/app/Scenes/SellWithArtsy/Components/MeetTheSpecialists.tsx
  src/app/Scenes/SellWithArtsy/utils/useSWALandingPageData.tsx
Labels: Jira Synced

#8662 feat: artwork list empty state
  src/app/Scenes/ArtworkList/ArtworkList.tsx
  src/app/Scenes/ArtworkList/ArtworkListArtworksGridHeader.tsx
  src/app/Scenes/ArtworkList/ArtworkListEmptyState.tests.tsx
  src/app/Scenes/ArtworkList/ArtworkListEmptyState.tsx
  src/app/Scenes/ArtworkList/ArtworkListTitle.tsx
Labels: Jira Synced

#8651 fix: deeplink analytics issues
  ios/Artsy.xcodeproj/project.pbxproj
  ios/Artsy/App/ARAnalyticsConstants.h
  ios/Artsy/App/ARAnalyticsConstants.m
  ios/Artsy/App/ARAppActivityContinuationDelegate.m
  ios/Artsy/App/ARAppDelegate+Analytics.h
  ios/Artsy/App/ARAppDelegate+Analytics.m
  ios/Artsy/App/ARAppDelegate.mm
  ios/ArtsyTests/App_Tests/ARAppActivityContinuationDelegateTests.m
  src/app/Scenes/Home/Home.tsx
  src/app/Scenes/Home/homeAnalytics.ts
  src/app/Scenes/NewWorksForYou/NewWorksForYou.tsx
  src/app/system/navigation/navigate.ts
  src/setupJest.ts
Labels: Jira Synced

#8647 feat(FX-4763): propagate artwork lists to other surfaces
  .secrets.baseline
  src/app/Components/Artist/ArtistArtworks/ArtistNotableWorksRail.tests.tsx
  src/app/Components/ArtworkGrids/ArtworkGridItem.tests.tsx
  src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
  src/app/Components/ArtworkRail/ArtworkRailCard.tsx
  src/app/Providers.tsx
  src/app/Scenes/Artist/Artist.tests.tsx
  src/app/Scenes/Artist/ArtistSavedSearch.tests.tsx
  src/app/Scenes/Artwork/Components/ArtworksInSeriesRail.tests.tsx
  src/app/Scenes/Fair/FairArtworks.tests.tsx
  src/app/Scenes/NewWorksForYou/NewWorksForYou.tests.tsx
  src/app/Scenes/Show/ShowArtworks.tests.tsx
  src/app/Scenes/Tag/Tag.tests.tsx
Labels: Jira Synced, Squash On Green

#8669 chore(FX-4762, FX-4759): display CTA when artwork saved to saved artworks (default artwork list)
  src/app/Components/ArtworkLists/useArtworkListsToast.ts
Labels: Jira Synced, Squash On Green

#8666 fix(CX-3694): Fix My Collection top padding
  src/app/Scenes/MyCollection/MyCollection.tsx
  src/app/Scenes/MyProfile/MyProfileHeader.tsx
  src/app/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx
Labels: Jira Synced, Squash On Green

#8656 feat(CX-3637): add collected artists rail
  src/app/Components/Artist/ArtistInsights/MarketStats.tsx
  src/app/Components/ArtistListItem.tests.tsx
  src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsTabs/ArtQuizArtist.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionArtworkListItem.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtistsRail.tests.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtistsRail.tsx
  src/app/Scenes/MyCollection/MyCollection.tsx
  src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightBigCard.tsx
  src/app/Scenes/MyCollection/Screens/Insights/MedianSalePriceAtAuction.tsx
  src/app/Scenes/MyCollection/Screens/Insights/SelectArtistModal.tsx
Labels: Jira Synced

#8646 fix: Android back button takes you back
  src/app/Scenes/Artwork/Artwork.tsx
  src/app/Scenes/Artwork/Components/CertificateAuthenticity.tests.tsx
  src/app/Scenes/Artwork/Components/CertificateAuthenticity.tsx
  src/app/Scenes/ArtworkAttributionClassFAQ/ArtworkAttributionClassFAQ.tsx
  src/app/Scenes/ArtworkMedium/ArtworkMedium.tsx
  src/app/Scenes/BottomTabs/BottomTabsNavigator.tsx
  src/app/Scenes/Collection/Collection.tsx
  src/app/utils/hooks/useBackHandler.tests.ts
  src/app/utils/hooks/useBackHandler.ts
Labels: Jira Synced

#8673 fix: remove extra suspense from artquiz
  src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResults.tsx
Labels: Squash On Green

#8677 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#8672 feat: Artwork list sorting
  src/app/Components/SortByModal/SortByModal.tests.tsx
  src/app/Components/SortByModal/SortByModal.tsx
  src/app/Scenes/ArtworkList/ArtworkList.tsx
  src/app/Scenes/ArtworkList/ArtworkListArtworksGridHeader.tsx
  src/app/Scenes/SavedSearchAlertsList/Components/SavedSearchesList.tsx
  src/app/utils/refreshHelpers.tsx
Labels: Jira Synced

#8658 feat(android): Enable hermes
  android/app/build.gradle
  android/app/proguard-rules.pro
  babel.config.js
  fastlane/Fastfile
  package.json
  scripts/hermes-android-bundle-bytecode.sh
  scripts/hermes-android-bundle.sh
  scripts/hermes-android-sourcemap.sh
  yarn.lock
Labels: Jira Synced

#8687 refactor: update empty state for artwork lists
  src/app/Scenes/ArtworkList/ArtworkListEmptyState.tests.tsx
  src/app/Scenes/ArtworkList/ArtworkListEmptyState.tsx
Labels: Squash On Green

#8667 feat(cx-3696): refresh auction lots rail when lots close
  src/app/Components/LotsByArtistsYouFollowRail/LotsByFollowedArtistsRail.tsx
  src/app/Components/SaleArtworkTileRailCard/SaleArtworkTileRailCard.tsx
  src/app/Components/SaleArtworkTileRailCard/UrgencyInfo.tests.tsx
  src/app/Components/SaleArtworkTileRailCard/UrgencyInfo.tsx
Labels: Jira Synced

#8694 fix(CX-3637): adjust the avatar add button design
  src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtistsRail.tsx
Labels: Jira Synced

#8684 RFC: Add Geolocation service
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: Jira Synced

#8697 fix: hot reload when app is run using yarn start
  package.json
  src/app/system/relay/middlewares/metaphysicsMiddleware.ts
Labels: Squash On Green

#8665 [CX-3630] feat: Add location support to "Shows for You" rail
  .secrets.baseline
  android/app/src/main/AndroidManifest.xml
  src/app/Scenes/Home/Components/ShowsRail.tests.tsx
  src/app/Scenes/Home/Components/ShowsRail.tsx
  src/app/Scenes/Home/Home.tsx
  src/app/Scenes/Home/useHomeModules.ts
  src/app/store/config/features.ts
  src/app/utils/hooks/useLocationOrIpAddress.ts
  src/setupJest.ts
Labels: Jira Synced, Squash On Green

#8688 fix(CX-3703): fix errors in the contact the specialist form
  src/app/Scenes/SellWithArtsy/ConsignmentInquiry/ConsignmentInquiryForm.tsx
  src/app/Scenes/SellWithArtsy/ConsignmentInquiry/ConsignmentInquiryScreen.tsx
Labels: Jira Synced

#8701 Revert "fix: hot reload when app is run using yarn start"
  package.json
  src/app/system/relay/middlewares/metaphysicsMiddleware.ts
Labels: Squash On Green

#8703 chore: update release note 8.12.5
  fastlane/metadata/android/en-US/changelogs/default.txt
  fastlane/metadata/en-US/release_notes.txt
Labels: Squash On Green

#8659 feat(iOS): Enable hermes on iOS
  .circleci/config.yml
  ios/Artsy.xcodeproj/project.pbxproj
  ios/Artsy/App/ARAppDelegate.mm
  ios/Podfile
  ios/Podfile.lock
  package.json
  scripts/hermes-ios-bundle-bytecode.sh
  scripts/hermes-ios-bundle-sourcemap.sh
  scripts/hermes-ios-bundle.sh
  src/app/App.tsx
  yarn.lock
Labels: Jira Synced, Squash On Green

#8708 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#8707 chore: podfile update
  ios/Podfile.lock
Labels: Squash On Green

#8692 fix(GRO-1645): add padding to results grid
  src/app/Scenes/ArtQuiz/ArtQuizLoader.tsx
  src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResults.tests.tsx
  src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsTabs/ArtQuizResultsTabs.tsx
  src/app/Scenes/ArtQuiz/ArtQuizWelcome.tsx
  src/app/Scenes/Onboarding/Onboarding.tsx
  src/app/Scenes/Onboarding/OnboardingQuiz/OnboardingMarketingCollection.tsx
  src/app/Scenes/Onboarding/OnboardingQuiz/OnboardingQuestionThree.tsx
Labels: Merge On Green, Jira Synced

#8718 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#8717 fix: Disable Shows for You location feature flag
  .secrets.baseline
  src/app/Scenes/Home/Components/ShowsRail.tests.tsx
  src/app/Scenes/Home/Components/ShowsRail.tsx
  src/app/Scenes/Home/Home.tsx
  src/app/store/config/features.ts
  src/app/utils/hooks/useLocationOrIpAddress.ts
Labels: Squash On Green

#8686 feat(CX-3642): create artist preview bottom sheet modal
  src/app/Components/Tabs/TabBarContainer.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionBottomSheetModals/MyCollectionBottomSheetModalArtist.tests.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionBottomSheetModals/MyCollectionBottomSheetModalArtist.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionBottomSheetModals/MyCollectionBottomSheetModalArtistPrevie.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionBottomSheetModals/MyCollectionBottomSheetModalArtistPreview/ArtistKindPills.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionBottomSheetModals/MyCollectionBottomSheetModals.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtistItem.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormMain.tsx
  src/app/Scenes/MyCollection/State/MyCollectionTabsStore.tsx
  src/app/Scenes/Onboarding/OnboardingCreateAccount/EmailSubscriptionCheckbox.tsx
Labels: Jira Synced, Squash On Green

#8722 fix: add missed build phase change
  ios/Artsy.xcodeproj/project.pbxproj
Labels: Squash On Green

#8728 feat(FX-4794): correctly display total selected artwork lists counter
  src/app/Components/ArtworkLists/ArtworkListsContext.tests.tsx
  src/app/Components/ArtworkLists/ArtworkListsContext.tsx
  src/app/Components/ArtworkLists/types.ts
  src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/components/ArtworkLists.tsx
  src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/components/SelectArtworkListsForArtworkFooter.tsx
  src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/utils/getSelectedArtworkListIds.tests.ts
  src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/utils/getSelectedArtworkListIds.ts
Labels: Jira Synced, Squash On Green

#8729 fix: home modules analytics events
  src/app/Scenes/Home/Components/HomeFeedModalCarousel/HomeFeedModalCarouselContainer.tsx
  src/app/system/navigation/NavStack.tsx
Labels: Squash On Green

#8606 feat(MOPLAT-619): Context menu for artwork items
  ios/Podfile.lock
  package.json
  src/app/Components/Artist/ArtistArtworks/ArtistNotableWorksRail.tests.tsx
  src/app/Components/Artist/ArtistArtworks/CreateArtworkAlertModal.tests.tsx
  src/app/Components/Artist/ArtistArtworks/CreateArtworkAlertModal.tsx
  src/app/Components/Artist/ArtistArtworks/CreateSavedSearchModal.tsx
  src/app/Components/ArtworkGrids/ArtworkGridItem.tests.tsx
  src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
  src/app/Components/ArtworkRail/ArtworkRail.tsx
  src/app/Components/ArtworkRail/ArtworkRailCard.tsx
  src/app/Components/ContextMenu/ContextMenuArtwork.tsx
  src/app/Scenes/Artwork/Components/ArtworkScreenHeader.tests.tsx
  src/app/Scenes/Artwork/Components/ArtworkScreenHeaderCreateAlert.tsx
  src/app/Scenes/Artwork/Components/ArtworksInSeriesRail.tests.tsx
  src/app/Scenes/Onboarding/OnboardingQuiz/__tests__/OnboardingQuestionTemplate.tests.tsx
  src/app/Scenes/Sale/BuyNowArtworksRail.tests.tsx
  src/app/Scenes/Sale/Components/NewBuyNowArtworksRail.tests.tsx
  src/app/Scenes/Search/SearchArtworksGrid.tests.tsx
  src/app/__fixtures__/ArtistFixture.js
  src/app/store/config/features.ts
  yarn.lock
Labels: Jira Synced

#8731 fix: hide context menu on android
  src/app/Components/ContextMenu/ContextMenuArtwork.tsx
Labels: Jira Synced

#8732 fix: dev menu weirdness on android
  src/app/AppRegistry.tsx
  src/app/utils/DevMenu.tsx
Labels: Jira Synced

#8734 fix: use large again for test js job
  .circleci/config.yml
Labels: Squash On Green

#8735 fix: specify fix version of segment for crash
  android/app/build.gradle
Labels: Squash On Green

#8736 chore: mark vir ready for release #trivial
  src/app/store/config/features.ts
Labels: Squash On Green

#8738 fix: point to really fixed segment version
  android/app/build.gradle
Labels: Squash On Green

#8740 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#8742 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#8720 feat(FX-4793): Ability to edit artwork list
  src/app/Components/ArtworkLists/components/CreateOrEditArtworkListForm.tsx
  src/app/Components/ArtworkLists/views/CreateNewArtworkListView/components/CreateNewArtworkListForm.tsx
  src/app/Scenes/ArtworkList/ManageArtworkListView.tsx
  src/app/Scenes/ArtworkList/views/EditArtworkListView/EditArtworkListView.tsx
  src/app/Scenes/ArtworkList/views/EditArtworkListView/useEditArtworkList.ts
Labels: Jira Synced, Squash On Green

#8747 chore: mark `AREnableArtworkLists` as ready for release
  src/app/store/config/features.ts
Labels: Squash On Green

#8749 chore: Update app version to 8.13.0
  app.json
Labels: Squash On Green

#8751 chore: add instructions for debugging on device on iOS
  docs/debugging.md
Labels: Squash On Green

#8752 feat: don't display contextual menu button for "Saved Artworks" list
  src/app/Scenes/ArtworkList/ArtworkList.tests.tsx
  src/app/Scenes/ArtworkList/ArtworkList.tsx
  src/app/Scenes/ArtworkList/ArtworkListEmptyState.tsx
  src/app/Scenes/ArtworkList/ArtworkListHeader.tsx
Labels: Squash On Green

#8757 chore: Location detection visualiser dev toggle
  src/app/Scenes/Home/Components/ShowsRail.tsx
  src/app/store/config/features.ts
Labels: Squash On Green

#8745 feat(sticky-tabs-2): sticky animated header
  .secrets.baseline
  src/app/Components/Artist/ArtistAbout/ArtistAbout.tests.tsx
  src/app/Components/Artist/ArtistHeader.tests.tsx
  src/app/Components/Artist/ArtistHeader.tsx
  src/app/Components/Button/FollowButton.tsx
  src/app/Components/Gene/About.tests.tsx
  src/app/Components/Gene/GeneArtworks.tests.tsx
  src/app/Components/Gene/Header.tsx
  src/app/Components/Tabs/AnimatedTabsHeader.tsx
  src/app/Components/Tabs/TabFlatList.tsx
  src/app/Components/Tabs/TabScrollView.tsx
  src/app/Components/Tabs/TabsContext.tsx
  src/app/Components/Tabs/TabsWithHeader.tsx
  src/app/Components/Tabs/useListenForTabContentScroll.tsx
  src/app/Providers.tsx
  src/app/Scenes/Activity/Activity.tsx
  src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsTabs/ArtQuizArtist.tsx
  src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsTabs/ArtQuizResultsEmptyTabs.tsx
  src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsTabs/ArtQuizResultsTabs.tsx
  src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsTabs/ArtQuizResultsTabsHeader.tsx
  src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsTabs/ArtQuizTrendingCollection.tsx
  src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsTabs/ArtQuizTrendingCollections.tsx
  src/app/Scenes/Artist/Artist.tsx
  src/app/Scenes/Favorites/Favorites.tsx
  src/app/Scenes/Gene/Gene.tests.tsx
  src/app/Scenes/Gene/Gene.tsx
  src/app/Scenes/Partner/Components/PartnerHeader.tests.tsx
  src/app/Scenes/Partner/Components/PartnerHeader.tsx
  src/app/Scenes/Partner/Partner.tsx
  src/app/Scenes/Tag/Tag.tsx
  src/app/Scenes/Tag/TagArtworks.tsx
  src/app/Scenes/Tag/TagArtworksFilterHeader.tsx
Labels: Jira Synced

#8763 chore(FX-4795): artwork list analytics (stage 1)
  src/app/Scenes/ArtworkList/ArtworkList.tsx
  src/app/Scenes/ArtworkList/views/DeleteArtworkListView/DeleteArtworkListView.tsx
  src/app/Scenes/ArtworkList/views/EditArtworkListView/EditArtworkListView.tsx
Labels: Jira Synced, Squash On Green

#8758 fix: Get public IP for Shows for You rail location
  .secrets.baseline
  ios/Podfile.lock
  package.json
  src/app/Scenes/Home/Components/ShowsRail.tests.tsx
  src/app/utils/hooks/useLocationOrIpAddress.ts
  yarn.lock
Labels: Jira Synced

#8754 feat(CX-3702): create artists grid view
  docs/debugging.md
  docs/getting_started.md
  src/app/Components/Artist/ArtistArtworks/SavedSearchButtonV2.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtistGridItem.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtistsRail.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtistsView.tests.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtistsView.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkArtistMarket.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormAddPhotos.tsx
  src/app/Scenes/Sales/Components/SaleList.tsx
Labels: Jira Synced

#8764 chore(FX-4795): artwork list analytics (stage 2)
  src/app/Components/ArtworkGrids/GenericGrid.tsx
  src/app/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx
  src/app/Components/ArtworkLists/views/CreateNewArtworkListView/components/CreateNewArtworkListForm.tsx
  src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/components/SelectArtworkListsForArtworkFooter.tsx
  src/app/Components/ArtworkRail/ArtworkRailCard.tsx
  src/app/Components/SaleArtworkTileRailCard/SaleArtworkTileRailCard.tsx
  src/app/Scenes/Artwork/Artwork.tsx
  src/app/Scenes/ArtworkList/ArtworkList.tsx
  src/app/Scenes/Sale/Components/SaleArtworkListItem.tsx
  src/app/system/analytics/AnalyticsContext.tsx
Labels: Jira Synced

#8771 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#8762 fix(CX-3722): add badge style to the pill component
  src/app/Components/Pill/Pill.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionBottomSheetModals/MyCollectionBottomSheetModalArtistPreview/ArtistKindPills.tsx
Labels: Jira Synced, Squash On Green

#8778 refactor: use correct image placeholders for artwork lists
  src/app/Components/ArtworkLists/components/ArtworkInfo.tsx
  src/app/Components/ArtworkLists/components/ArtworkListImage.tsx
  src/app/Components/ArtworkLists/components/ArtworkListImagePreview.tsx
  src/app/Components/ArtworkLists/components/ArtworkListNoImage.tsx
  src/app/Components/ArtworkLists/components/EntityPreview.tsx
  src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/components/ArtworkListItem.tsx
  src/app/Scenes/ArtworkLists/FourUpImageLayout.tsx
  src/app/Scenes/ArtworkLists/StackedImageLayout.tsx
  src/app/Scenes/ArtworkLists/components/ArtworkListImage.tsx
  src/app/Scenes/ArtworkLists/components/ArtworkListImageBorder.tsx
  src/app/Scenes/ArtworkLists/components/ArtworkListNoImage.tsx
Labels: Squash On Green

#8775 fix: Check location permission for Android
  src/app/utils/hooks/useLocationOrIpAddress.ts
Labels: Jira Synced, Squash On Green

#8780 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#8786 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#8787 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#8774 feat(CX-3663): Sort Auction lots ending for you soon by timely_at
  src/app/Components/LotsByArtistsYouFollowRail/LotsByFollowedArtistsRail.tsx
Labels: Jira Synced
