Repository artsy/eigen, pull requests merged in 2023-07, with the labels that each got.

#8951 feat: update empty state for alerts
  src/app/Scenes/SavedSearchAlertsList/Components/EmptyMessage.tsx
  src/app/Scenes/SavedSearchAlertsList/Components/SavedSearchesList.tests.tsx
Labels: Jira Synced

#8952 feat: enable native articles
  src/app/Components/HTML.tsx
  src/app/store/config/features.ts
Labels: Squash On Green

#8957 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#8958 fix: Prevent Shows for You rail to reload when scrolling
  src/app/Scenes/Home/Components/ShowsRail.tsx
Labels: Jira Synced

#8960 fix: low quality share images
  src/app/Components/ShareSheet/ShareSheet.tsx
  src/app/Components/ShareSheet/helpers.ts
  src/app/Components/ShareSheet/types.ts
  src/app/Scenes/Artwork/Components/ArtworkHeader.tsx
Labels: Squash On Green

#8963 fix(onyx-112): fixes '-1 lists selected' appearing in artwork list sheet
  src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/components/SelectArtworkListsForArtworkHeader.tsx
Labels: Jira Synced

#8964 chore: long press feedback
  src/app/Components/ContextMenu/ContextMenuArtwork.tsx
Labels: Jira Synced

#8956 fix: partner coordinates being null issue
  src/app/Scenes/GalleriesForYou/Components/PartnerListItem.tsx
  src/app/Scenes/GalleriesForYou/GalleriesForYouScreen.tsx
  src/app/Scenes/GalleriesForYou/helpers.tsx
Labels: Squash On Green

#8968 feat: clean up article ff
  src/app/Components/ArticleCard.tsx
  src/app/routes.ts
  src/app/store/config/features.ts
Labels: Jira Synced, Squash On Green

#8966 chore: refresh long press ff
  src/app/Components/ContextMenu/ContextMenuArtwork.tsx
  src/app/store/config/features.ts
Labels: Squash On Green

#8962 feat(onyx-113): Do not dispatch new artwork lists behavior when tapping 'Watch lot' on artwork screen
  src/app/Components/ArtworkLists/useSaveArtworkToArtworkLists.ts
  src/app/Scenes/Artwork/Components/ArtworkActions.tsx
  src/app/Scenes/Artwork/Components/ArtworkSaveButton.tsx
  src/app/Scenes/Artwork/utils/isOpenOrUpcomingSale.ts
Labels: Jira Synced

#8972 fix: change rn-patch version
  patches/react-native+0.69.12.patch
Labels: Squash On Green

#8961 feat(DIA-40): change editorial in Artist/About tab
  src/app/Components/Artist/Articles/Article.tsx
  src/app/Components/Artist/Articles/Articles.tests.tsx
  src/app/Components/Artist/Articles/Articles.tsx
  src/app/Components/Artist/ArtistAbout/ArtistAbout.tests.tsx
  src/app/Components/Artist/ArtistAbout/ArtistAbout.tsx
  src/app/Components/MasonryStatic.tsx
Labels: Jira Synced

#8974 chore: cleanup article flag
  src/app/Components/Artist/Articles/Article.tsx
  src/app/Components/Artist/Articles/Articles.tests.tsx
Labels: Squash On Green

#8862 fix: move push prompt logic to typescript, fix token registration bugs
  android/app/src/main/AndroidManifest.xml
  android/build.gradle
  ios/Artsy/App/ARAnalyticsConstants.h
  ios/Artsy/App/ARAnalyticsConstants.m
  ios/Artsy/App/ARAppDelegate+Emission.m
  ios/Artsy/App/ARAppNotificationsDelegate.h
  ios/Artsy/App/ARAppNotificationsDelegate.m
  ios/Artsy/Constants/ARDefaults.h
  ios/Artsy/Constants/ARDefaults.m
  ios/Artsy/Emission/TemporaryAPI/ARTemporaryAPIModule.h
  ios/Artsy/Emission/TemporaryAPI/ARTemporaryAPIModule.m
  ios/Artsy/View_Controllers/Admin/ARAdminSettingsViewController.m
  ios/Podfile.lock
  package.json
  scripts/changelog/generateChangelog.ts
  src/app/Components/ArtsyWebView.tests.tsx
  src/app/Components/ArtsyWebView.tsx
  src/app/NativeModules/LegacyNativeModules.tsx
  src/app/Scenes/Home/Home.tsx
  src/app/Scenes/Home/HomeContainer.tsx
  src/app/Scenes/MyProfile/MyProfilePushNotifications.tsx
  src/app/Scenes/SavedSearchAlert/helpers.ts
  src/app/store/ArtsyPrefsModel.ts
  src/app/store/AuthModel.ts
  src/app/store/GlobalStore.tsx
  src/app/store/PushPromptLogicModel.ts
  src/app/store/__tests__/migration.tests.ts
  src/app/store/migration.ts
  src/app/utils/PushNotification.ts
  src/app/utils/requestPushNotificationsPermission.ts
  src/app/utils/requestPushNotificationsPermissions.tests.ts
  src/setupJest.tsx
  yarn.lock
Labels: Jira Synced, Squash On Green

#8978 chore: 🧹 clean up dead component 💀
  src/app/Components/Disappearable.tests.tsx
  src/app/Components/Disappearable.tsx
  src/app/Components/Home/ArtistRails/ArtistRail.tsx
Labels: Squash On Green

#8984 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#8985 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#8954 feat(FX-4806): price control for create / edit alert flows
  src/app/Components/ArtworkFilter/Filters/PriceRangeOptions.tsx
  src/app/Components/ArtworkFilter/RecentPriceRanges.tsx
  src/app/Components/ArtworkGrids/GenericGrid.tsx
  src/app/Components/PriceRange/PriceRangeContainer.tsx
  src/app/Components/PriceRange/PriceRangeSlider.tsx
  src/app/Components/PriceRange/constants.ts
  src/app/Components/PriceRange/types.ts
  src/app/Components/PriceRange/utils.ts
  src/app/Scenes/Artist/Artist.tsx
  src/app/Scenes/ArtistSeries/ArtistSeries.tsx
  src/app/Scenes/ArtworkRecommendations/ArtworkRecommendations.tsx
  src/app/Scenes/Fair/Fair.tsx
  src/app/Scenes/Fair/FairAllFollowedArtists.tsx
  src/app/Scenes/Gene/Gene.tsx
  src/app/Scenes/Inbox/Components/Conversations/Messages.tests.tsx
  src/app/Scenes/LotsByArtistsYouFollow/LotsByArtistsYouFollow.tsx
  src/app/Scenes/MyCollection/MyCollection.tsx
  src/app/Scenes/NewWorksForYou/NewWorksForYou.tsx
  src/app/Scenes/NewWorksFromGalleriesYouFollow/NewWorksFromGalleriesYouFollow.tsx
  src/app/Scenes/RecentlyViewed/RecentlyViewed.tsx
  src/app/Scenes/SavedSearchAlert/CreateSavedSearchAlert.tsx
  src/app/Scenes/SavedSearchAlert/EditSavedSearchAlert.tsx
  src/app/Scenes/SavedSearchAlert/screens/AlertPriceRangeScreen.tests.tsx
  src/app/Scenes/SavedSearchAlert/screens/AlertPriceRangeScreen.tsx
  src/app/Scenes/Search/components/placeholders/SearchArtworksGridPlaceholder.tsx
  src/app/Scenes/Show/Show.tsx
  src/app/Scenes/SimilarToRecentlyViewed/SimilarToRecentlyViewed.tsx
  src/app/Scenes/Tag/Tag.tsx
  src/app/utils/placeholderGrid.tsx
  src/app/utils/placeholders.tsx
Labels: Jira Synced

#8988 chore: Prepare for 8.17.0
  app.json
Labels: Squash On Green

#8989 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#8993 doc: update getting_started doc slightly for first-timers
  docs/getting_started.md
Labels: Squash On Green

#8994 feat(DIA-3): replace related artists section
  src/app/Components/Artist/ArtistAbout/ArtistAbout.tsx
  src/app/Components/Artist/RelatedArtistsRail.tests.tsx
  src/app/Components/Artist/RelatedArtistsRail.tsx
  src/app/Components/Artist/RelatedArtistsRailCell.tests.tsx
  src/app/Components/Artist/RelatedArtistsRailCell.tsx
  src/app/utils/mutations/useFollowArtist.ts
  src/app/utils/tests/setupTestWrapper.tsx
Labels: Jira Synced

#8999 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#8997 feat(ONYX-51): add follow button to a gallery page; refactor class to FC
  src/app/Scenes/Partner/Components/PartnerFollowButton.tsx
  src/app/Scenes/Partner/Components/PartnerHeader.tsx
  src/app/Scenes/Partner/Components/PartnerLocationSection.tsx
  src/app/Scenes/Partner/Partner.tsx
Labels: Jira Synced

#9003 chore: remove algolia-backed components
  package.json
  scripts/algolia-example-galleries-near-me.ts
  src/app/AppRegistry.tsx
  src/app/Scenes/Home/Home.tsx
  src/app/Scenes/Search/CuratedCollections.tests.tsx
  src/app/Scenes/Search/RefetchWhenApiKeyExpired.tsx
  src/app/Scenes/Search/Search.tests.tsx
  src/app/Scenes/Search/Search.tsx
  src/app/Scenes/Search/Search2.tests.tsx
  src/app/Scenes/Search/Search2.tsx
  src/app/Scenes/Search/SearchPills.tsx
  src/app/Scenes/Search/SearchResults.tsx
  src/app/Scenes/Search/SearchSwitchContainer.tsx
  src/app/Scenes/Search/components/AlgoliaSearchResults.tsx
  src/app/Scenes/Search/components/ElasticSearchResult.tests.tsx
  src/app/Scenes/Search/components/ElasticSearchResult.tsx
  src/app/Scenes/Search/components/EntitySearchResults.tests.tsx
  src/app/Scenes/Search/components/EntitySearchResults.tsx
  src/app/Scenes/Search/components/SearchHighlight.tsx
  src/app/Scenes/Search/components/SearchPills.tests.tsx
  src/app/Scenes/Search/components/SearchPills.tsx
  src/app/Scenes/Search/components/SearchResult.tests.tsx
  src/app/Scenes/Search/components/SearchResult.tsx
  src/app/Scenes/Search/components/SingleIndexEmptyResultsMessage.tests.tsx
  src/app/Scenes/Search/components/SingleIndexEmptyResultsMessage.tsx
  src/app/Scenes/Search/components/placeholders/SingleIndexSearchPlaceholder.tsx
  src/app/Scenes/Search/constants.ts
  src/app/Scenes/Search/helpers.ts
  src/app/Scenes/Search/types.ts
  src/app/Scenes/Search/useRefetchWhenQueryChanged.tsx
  src/app/Scenes/Search/useSearchQuery.tsx
  src/app/routes.ts
  src/app/store/config/features.ts
  src/app/utils/useAlgoliaClient.ts
  src/app/utils/useAlgoliaIndices.ts
  src/app/utils/useSearchInsightsConfig.ts
  yarn.lock
Labels: Jira Synced

#8942 feat(alerts): add confirmation modal with matching artworks
  src/app/Components/Artist/ArtistArtworks/CreateSavedSearchModal.tests.tsx
  src/app/Components/Artist/ArtistArtworks/CreateSavedSearchModal.tsx
  src/app/Components/ArtworkGrids/GenericGrid.tsx
  src/app/Scenes/SavedSearchAlert/CreateSavedSearchAlert.tsx
  src/app/Scenes/SavedSearchAlert/SavedSearchAlertForm.tsx
  src/app/Scenes/SavedSearchAlert/SavedSearchAlertModel.ts
  src/app/Scenes/SavedSearchAlert/screens/ConfirmationScreen.tests.tsx
  src/app/Scenes/SavedSearchAlert/screens/ConfirmationScreen.tsx
Labels: Jira Synced

#9007 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9008 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9001 feat(onyx-124): Do not auto-persist pending changes on artwork lists sheet dismissal
  src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/SelectArtworkListsForArtworkView.tsx
  src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/components/StickyBottomContent.tsx
  src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/useSaveArtworkListsChanges.ts
Labels: Jira Synced

#9010 fix: broken infinite scroll artist artwork grid
  src/app/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
  src/app/Components/TabsFlatlist.tsx
Labels: Jira Synced, Squash On Green

#9005 feat(DIA-4): add related genes to artist about tab
  src/app/Components/Artist/ArtistAbout/ArtistAbout.tsx
  src/app/Components/Artist/ArtistAbout/ArtistAboutRelatedGenes.tests.tsx
  src/app/Components/Artist/ArtistAbout/ArtistAboutRelatedGenes.tsx
Labels: Jira Synced

#9006 feat(ONYX-123): Reposition default toast position to bottom position
  src/app/Components/ArtworkLists/ArtworkListsContext.tsx
  src/app/Components/ArtworkLists/types.ts
  src/app/Components/ArtworkLists/useArtworkListsToast.ts
  src/app/Components/Toast/ToastComponent.tsx
  src/app/Components/Toast/types.ts
  src/app/Scenes/Artwork/Components/ArtworkStickyBottomContent.tsx
Labels: Jira Synced

#9016 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9013 fix: problematic android infinite scroll grids
  src/app/Components/Gene/GeneArtworks.tsx
  src/app/Components/TabsFlatlist.tsx
  src/app/Scenes/MyCollection/MyCollection.tsx
  src/app/Scenes/Partner/Components/PartnerArtwork.tsx
  src/app/Scenes/Tag/TagArtworks.tsx
Labels: Jira Synced

#9019 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9012 feat(DIA-5): cleanup of ArtistAbout tab
  .secrets.baseline
  src/app/Components/Artist/ArtistAbout/ArtistAbout.tests.tsx
  src/app/Components/Artist/ArtistAbout/ArtistAbout.tsx
  src/app/Components/Artist/ArtistAbout/ArtistAboutRelatedGenes.tests.tsx
  src/app/Components/Artist/ArtistAbout/ArtistAboutRelatedGenes.tsx
  src/app/Components/Artist/ArtistAbout/ArtistAboutShow.tsx
  src/app/Components/Artist/ArtistAbout/ArtistAboutShows.tsx
  src/app/Components/Artist/ArtistArtworks/ArtistCollectionsRail.tests.tsx
  src/app/Components/Artist/ArtistArtworks/ArtistCollectionsRail.tsx
  src/app/Components/Artist/ArtistArtworks/ArtistNotableWorksRail.tests.tsx
  src/app/Components/Artist/ArtistArtworks/ArtistNotableWorksRail.tsx
  src/app/Components/Artist/ArtistConsignButton.tests.tsx
  src/app/Components/Artist/ArtistConsignButton.tsx
  src/app/Components/Artist/Biography.tsx
  src/app/Components/GenericArtistSeriesRail.tsx
Labels: Jira Synced

#9021 build(deps): update fastlane and other deps
  Gemfile.lock
Labels: Jira Synced, Squash On Green

#9023 fix: increase default storage capacity of async storage on Android
  android/gradle.properties
Labels: Jira Synced

#9024 fix: Use userInterestsConnection in collected artist rail and view
  src/app/Scenes/MyCollection/Components/MyCollectionBottomSheetModals/MyCollectionBottomSheetModals.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtistGridItem.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtistItem.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtistsRail.tests.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtistsRail.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtistsView.tests.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtistsView.tsx
  src/app/Scenes/MyCollection/State/MyCollectionTabsStore.tsx
Labels: Jira Synced

#9020 feat: Create custom artists when adding collected artists
  src/app/Scenes/MyCollection/Screens/MyCollectionAddCollectedArtists/MyCollectionAddCollectedArtists.tests.tsx
  src/app/Scenes/MyCollection/Screens/MyCollectionAddCollectedArtists/MyCollectionAddCollectedArtists.tsx
  src/app/Scenes/MyCollection/Screens/MyCollectionAddCollectedArtists/MyCollectionAddCollectedArtistsAutosuggest.tsx
  src/app/Scenes/MyCollection/mutations/createArtist.ts
  src/app/Scenes/MyCollection/mutations/createUserInterests.ts
Labels: Squash On Green

#9025 chore(ONYX-157): show artist preview bottom sheet on artists rail press
  src/app/Scenes/MyCollection/Components/MyCollectionBottomSheetModals/MyCollectionBottomSheetModalArtistPreview.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionBottomSheetModals/MyCollectionBottomSheetModals.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtistsRail.tests.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtistsRail.tsx
Labels: Jira Synced

#9027 chore(ONYX-150): use myCollectionConnection to fetch artworks count within my collection
  src/app/Scenes/MyCollection/Components/MyCollectionBottomSheetModals/MyCollectionBottomSheetModalArtistPreview.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionBottomSheetModals/MyCollectionBottomSheetModals.tsx
Labels: Jira Synced, Squash On Green

#9026 chore: Rename mockCollectedArtist to mockUserInterest in MyCollectionCollectedArtistsView.tests.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtistsView.tests.tsx
Labels: Squash On Green

#9035 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9039 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9040 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9049 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9050 fix(DIA-67): do not perform image resize in HeroRails
  src/app/Scenes/Home/Components/HeroUnitsRail.tsx
Labels: Jira Synced

#9051 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9042 feat: long press custom preview component
  ios/Podfile.lock
  package.json
  src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
  src/app/Components/ContextMenu/ContextMenuArtwork.tsx
  src/app/Components/ContextMenu/ContextMenuArtworkPreviewCard.tsx
  yarn.lock
Labels: Jira Synced

#9048 build(deps): update flipper and dev deps
  android/gradle.properties
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: Jira Synced

#9034 feat(ONYX-149): trigger mutations on artist preview bottom sheet
  src/app/Scenes/MyCollection/Components/MyCollectionBottomSheetModals/MyCollectionBottomSheetModalArtistPreview.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionBottomSheetModals/MyCollectionBottomSheetModals.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtistGridItem.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtistItem.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtistsRail.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtistsView.tsx
  src/app/Scenes/MyCollection/State/MyCollectionTabsStore.tsx
  src/app/Scenes/MyCollection/mutations/updateUserInterest.ts
Labels: Jira Synced

#9052 fix(ONYX-164): fix loading skeleton for my collection tab when the ff is enabled
  src/app/Scenes/MyCollection/MyCollection.tsx
Labels: Jira Synced

#9055 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9053 fix(ONYX-166): Make the search bar on my collection full screen | Artist pill
  src/app/Scenes/MyCollection/Components/MyCollectionArtistFiltersStickyTab.tsx
Labels: Jira Synced

#9054 feat(ONYX-168): add privacy icon to the artist preview bottom sheet
  src/app/Scenes/MyCollection/Components/MyCollectionBottomSheetModals/MyCollectionBottomSheetModalArtistPreview.tsx
Labels: Jira Synced

#9062 fix(ONYX-167): navigate to my collection after deleting artwork
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormMain.tsx
Labels: Jira Synced, Squash On Green

#9061 feat(ONYX-152): add missing mutations to select artists you collect
  src/app/AppRegistry.tsx
  src/app/Components/ArtistListItem.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtistsOnboardingModal.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtistsPrivacy.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtistsView.tsx
  src/app/Scenes/MyCollection/Components/SelectArtistToShareListItem.tsx
  src/app/Scenes/MyCollection/MyCollection.tsx
  src/app/Scenes/MyCollection/Screens/CollectedArtistsPrivacy/MyCollectionCollectedArtistsPrivacy.tests.tsx
  src/app/Scenes/MyCollection/Screens/CollectedArtistsPrivacy/MyCollectionCollectedArtistsPrivacy.tsx
  src/app/Scenes/MyCollection/Screens/CollectedArtistsPrivacy/MyCollectionCollectedArtistsPrivacyArtistsList.tsx
  src/app/Scenes/MyCollection/Screens/CollectedArtistsPrivacy/UserInterestsStore.ts
  src/app/Scenes/MyCollection/Screens/CollectedArtistsPrivacy/updateUserInterests.ts
  src/app/store/VisualClueModel.ts
  src/app/utils/extractEdges.ts
  src/app/utils/hooks/useVisualClue.ts
Labels: Jira Synced

#9059 fix(modals): remove extra insets in some surfaces
  src/app/AppRegistry.tsx
  src/app/Components/Bidding/Screens/Registration.tsx
  src/app/Scenes/About/About.tests.tsx
  src/app/Scenes/About/About.tsx
  src/app/Scenes/Artwork/Components/ArtworkDetails.tests.tsx
  src/app/Scenes/Artwork/Components/ArtworkDetails.tsx
  src/app/Scenes/Artwork/Components/ArtworkLotDetails/ArtworkLotDetails.tsx
  src/app/Scenes/Artwork/Components/AuctionPrice.tsx
  src/app/Scenes/Artwork/Components/CertificateAuthenticity.tsx
  src/app/Scenes/ArtworkAttributionClassFAQ/ArtworkAttributionClassFAQ.tests.tsx
  src/app/Scenes/ArtworkAttributionClassFAQ/ArtworkAttributionClassFAQ.tsx
  src/app/Scenes/ArtworkMedium/ArtworkMedium.tsx
  src/app/Scenes/AuctionBuyersPremium/AuctionBuyersPremium.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/RequestForPriceEstimate/RequestForPriceEstimateForm.tsx
  src/app/Scenes/PrivacyRequest/PrivacyRequest.tests.tsx
  src/app/Scenes/PrivacyRequest/PrivacyRequest.tsx
  src/app/Scenes/SellWithArtsy/ConsignmentInquiry/ConsignmentInquiryForm.tsx
  src/app/routes.ts
  src/app/system/navigation/routes.tests.ts
Labels: Jira Synced

#9071 build(deps): remove @react-native-camera-roll/camera-roll
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: FF

#9077 build(deps): bump @testing-library/react-native from 12.1.2 to 12.1.3
  package.json
  yarn.lock
Labels: Squash On Green

#9074 fix: Dont show follow button for personal collected artists
  src/app/Scenes/MyCollection/Components/MyCollectionBottomSheetModals/MyCollectionBottomSheetModalArtistPreview.tsx
Labels: Squash On Green

#9072 fix: Close My Collection Bottom Sheet when tapping option
  src/app/Scenes/MyCollection/Components/MyCollectionBottomSheetModals/MyCollectionBottomSheetModalAdd.tsx
Labels: Squash On Green

#9078 chore: improve loading behaviour add artists you collect
  src/app/Scenes/MyCollection/Screens/MyCollectionAddCollectedArtists/MyCollectionAddCollectedArtists.tsx
Labels: Jira Synced

#9080 chore(ONYX-190): dismiss keyboard after leaving add personal artist route
  src/app/Scenes/MyCollection/Screens/Artist/AddMyCollectionArtist.tests.tsx
  src/app/Scenes/MyCollection/Screens/Artist/AddMyCollectionArtist.tsx
Labels: Jira Synced

#9084 Revert "chore(deps): update dep @artsy/palette-mobile from 11.2.10 to v11.2.11"
  package.json
  yarn.lock
Labels: Squash On Green

#9083 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9081 fix(ONYX-191): padding in add artists you collect
  src/app/Scenes/MyCollection/Screens/MyCollectionAddCollectedArtists/MyCollectionAddCollectedArtistsAutosuggest.tsx
Labels: Jira Synced

#9089 fix(ONYX-182): My collection pills animation transition on android
  src/app/Scenes/MyCollection/MyCollection.tsx
  src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsights.tsx
Labels: Jira Synced

#9087 fix: reverse artist is checked value
  src/app/Scenes/MyCollection/Components/MyCollectionBottomSheetModals/MyCollectionBottomSheetModalArtistPreview.tsx
Labels: Jira Synced

#9091 fix: Use `userinterestsConnection` instead of `collectedArtistsConnection`
  .secrets.baseline
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtistAutosuggest.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tests.tsx
  src/app/Scenes/MyCollection/Screens/Insights/SelectArtist.tests.tsx
  src/app/Scenes/MyCollection/Screens/Insights/SelectArtistModal.tsx
  src/app/Scenes/MyCollection/Screens/MyCollectionAddCollectedArtists/MyCollectionAddCollectedArtists.tests.tsx
  src/app/Scenes/MyCollection/Screens/MyCollectionAddCollectedArtists/MyCollectionAddCollectedArtistsAutosuggest.tsx
  src/app/Scenes/MyCollection/utils/filterArtistsByKeyword.ts
  src/app/store/config/features.ts
  src/app/utils/normalizeText.ts
Labels: Jira Synced

#9092 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9096 fix(ONYX-175): remove FooterComponent from the InfiniteScrollArtworksGridContainer
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtworkAutosuggest.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtworkAutosuggestResults.tsx
Labels: Jira Synced
