Repository artsy/eigen, pull requests merged in 2023-03, with the labels that each got.

#8278 Feat(cx-3379): SWA collectors network
  images/world-map@1x.png
  images/world-map@2x.png
  images/world-map@3x.png
  src/app/Scenes/SellWithArtsy/Components/CollectorsNetwork.tsx
  src/app/Scenes/SellWithArtsy/SellWithArtsyHome.tsx
Labels: Jira Synced

#8297 Chore: Update version to v8.8.2
  app.json
Labels: Squash On Green

#8295 Feat(cx-3380): Redesign SWA previously sold
  src/app/Components/ArtworkRail/ArtworkRail.tsx
  src/app/Components/ArtworkRail/ArtworkRailCard.tsx
  src/app/Scenes/SellWithArtsy/Components/SellWithArtsyRecentlySold.tsx
Labels: Jira Synced

#8289 feat: Artwork Recommendations screen
  .secrets.baseline
  src/app/AppRegistry.tsx
  src/app/Scenes/ArtworkRecommendations/ArtworkRecommendations.tests.tsx
  src/app/Scenes/ArtworkRecommendations/ArtworkRecommendations.tsx
  src/app/Scenes/Home/Components/ArtworkRecommendationsRail.tsx
  src/app/Scenes/Sales/UpcomingAuctions.tsx
  src/app/routes.ts
Labels: Jira Synced, Squash On Green

#8301 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#8305 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#8306 Feat(CX-3381): Redesign swa Landing page P6 [Testimonials, Footer]
  images/swa-faq-image@1x.png
  images/swa-faq-image@2x.png
  images/swa-faq-image@3x.png
  src/app/Scenes/Artwork/Components/ImageCarousel/ImageCarouselPaginationIndicator.tsx
  src/app/Scenes/SellWithArtsy/Components/FAQSWA.tsx
  src/app/Scenes/SellWithArtsy/Components/Footer.tsx
  src/app/Scenes/SellWithArtsy/Components/Testimonials.tsx
  src/app/Scenes/SellWithArtsy/SellWithArtsyHome.tsx
Labels: Jira Synced

#8300 feat: New Works from Galleries You Follow screen
  .secrets.baseline
  src/app/AppRegistry.tsx
  src/app/Scenes/Home/Components/ArtworkModuleRail.tsx
  src/app/Scenes/Home/Home.tsx
  src/app/Scenes/Home/homeModules.ts
  src/app/Scenes/NewWorksFromGalleriesYouFollow/NewWorksFromGalleriesYouFollow.tests.tsx
  src/app/Scenes/NewWorksFromGalleriesYouFollow/NewWorksFromGalleriesYouFollow.tsx
  src/app/routes.ts
Labels: Jira Synced, Squash On Green

#8311 Feat(CX-3494): Implement Tracking in new SWA modules
  images/get-in-touch-banner-image-ipad.png
  images/get-in-touch-banner-image.png
  images/swa-faq-image.png
  images/swa-landing-page-header.png
  images/ways-we-sell-auction.png
  images/ways-we-sell-online-storefront.png
  images/ways-we-sell-private-sales.png
  images/world-map.png
  src/app/Scenes/SellWithArtsy/Components/Footer.tsx
  src/app/Scenes/SellWithArtsy/Components/Header.tsx
  src/app/Scenes/SellWithArtsy/Components/HowItWorks.tsx
  src/app/Scenes/SellWithArtsy/Components/MeetTheSpecialists.tsx
  src/app/Scenes/SellWithArtsy/Components/SpeakToTheTeam.tsx
  src/app/Scenes/SellWithArtsy/SellWithArtsyHome.tsx
  src/app/Scenes/SellWithArtsy/index.tests.tsx
Labels: Jira Synced

#8309 fix: Hide collections in collection rail on home screen if the collection is empty
  src/app/Scenes/Home/Components/MarketingCollectionRail.tsx
Labels: Jira Synced

#8310 feat: Similar to Works You've Viewed screen
  src/app/AppRegistry.tsx
  src/app/Scenes/Home/Components/ArtworkModuleRail.tsx
  src/app/Scenes/SimilarToRecentlyViewed/SimilarToRecentlyViewed.tests.tsx
  src/app/Scenes/SimilarToRecentlyViewed/SimilarToRecentlyViewed.tsx
  src/app/routes.ts
Labels: Jira Synced, Squash On Green

#8296 feat(DO-640): add "Artsy Auction" to organization filters
  src/app/Components/ArtworkFilter/Filters/AuctionHouseOptions.tests.tsx
  src/app/Components/ArtworkFilter/Filters/AuctionHouseOptions.tsx
Labels: Jira Synced

#8315 feat(CX-3466): Add edition number to My Collection artworks
  src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkAbout/MyCollectionArtworkAboutWork.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/Field.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtworkAbout.tests.tsx
Labels: Jira Synced

#8323 feat: add track rail viewed
  src/app/Scenes/Home/Home.tsx
Labels: Jira Synced

#8324 feat: fix swa buttons
  src/app/Components/ArtworkRail/ArtworkRailCard.tsx
  src/app/Scenes/SellWithArtsy/Components/Header.tsx
  src/app/Scenes/SellWithArtsy/SellWithArtsyHome.tsx
Labels: Jira Synced

#8329 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#8335 chore: remove unused zustand dependency
  package.json
  yarn.lock
Labels: Easy First Task, Squash On Green

#8337 chore: bump version
  app.json
Labels: Squash On Green

#8340 feat(cx-3516): SWA Lp UI Updates
  images/get-in-touch-banner-image-ipad.png
  images/get-in-touch-banner-image-ipad@2x.png
  images/get-in-touch-banner-image-ipad@3x.png
  images/get-in-touch-banner-image.png
  images/get-in-touch-banner-image@2x.png
  images/get-in-touch-banner-image@3x.png
  images/swa-faq-image.png
  images/swa-faq-image@2x.png
  images/swa-faq-image@3x.png
  images/swa-landing-page-header.png
  images/swa-landing-page-header@2x.png
  images/swa-landing-page-header@3x.png
  src/app/Components/ArtworkRail/ArtworkRailCard.tsx
  src/app/Scenes/SellWithArtsy/Components/CollectorsNetwork.tsx
  src/app/Scenes/SellWithArtsy/Components/FAQSWA.tsx
  src/app/Scenes/SellWithArtsy/Components/Header.tsx
  src/app/Scenes/SellWithArtsy/Components/HowItWorks.tsx
  src/app/Scenes/SellWithArtsy/Components/MeetTheSpecialists.tsx
  src/app/Scenes/SellWithArtsy/Components/SpeakToTheTeam.tsx
  src/app/Scenes/SellWithArtsy/SellWithArtsyHome.tsx
  src/app/Scenes/SellWithArtsy/SubmitArtwork/UploadPhotos/utils/index.tests.tsx
  src/app/Scenes/SellWithArtsy/index.tests.tsx
  src/app/utils/useStatusBarStyle.ts
Labels: Jira Synced

#8343 chore: update rn share
  ios/Podfile.lock
  package.json
  src/app/Components/ShareSheet/ShareSheet.tests.tsx
  src/app/Components/ShareSheet/ShareSheet.tsx
  src/app/Scenes/Artwork/Components/ArtworkHeader.tsx
  yarn.lock
Labels: Jira Synced

#8342 chore: update unleash
  package.json
  src/app/utils/experiments/unleashClient.ts
  yarn.lock
Labels: Jira Synced

#8325 fix: dimiss modal after make offer
  src/app/Components/ArtsyWebView.tsx
Labels: Jira Synced

#8347 chore: remove unused rn-geolocation dependency
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: Jira Synced, Squash On Green

#8348 chore: update remove-markdown to latest
  package.json
  yarn.lock
Labels: Squash On Green

#8349 chore: update supercluster to latest
  package.json
  yarn.lock
Labels: Squash On Green

#8352 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#8341 chore: show only past auction results inside insights
  src/app/Scenes/MyCollection/Screens/Insights/AuctionResultsForArtistsYouCollect.tsx
Labels: Jira Synced

#8353 fix: Prevent simultaneously adding and deleting images in SWA form to prevent race condition
  src/app/Scenes/SellWithArtsy/SubmitArtwork/UploadPhotos/UploadPhotosForm.tsx
  src/palette/elements/PhotoRow/PhotoRow.tsx
Labels: Jira Synced

#8357 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#8358 feat: Display all auction result lists as rail on home screen
  src/app/Scenes/Home/Components/AuctionResultsRail.tests.tsx
  src/app/Scenes/Home/Components/AuctionResultsRail.tsx
  src/app/Scenes/Home/Components/HomeUpcomingAuctionsRail.tsx
  src/app/Scenes/Home/Components/MarketingCollectionRail.tsx
  src/app/Scenes/Home/Home.tsx
  src/app/Scenes/Home/useHomeModules.ts
Labels: Jira Synced

#8360 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#8363 fix: Don't hide Auction Lots for You Ending Soon home screen rail
  src/app/Scenes/Home/Home.tsx
  src/app/Scenes/Home/useHomeModules.ts
Labels: Squash On Green

#8364 fix: Upcoming auction results view all URL
  src/app/Scenes/Home/Components/AuctionResultsRail.tsx
Labels: Squash On Green

#8367 fix(CX-3467): Update Edition Number spacing in My Collection artwork details
  src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkAbout/MyCollectionArtworkAboutWork.tsx
Labels: Jira Synced

#8260 feat: upgrade to react-native 0.67
  HACKS.md
  android/app/build.gradle
  android/app/src/main/res/drawable/rn_edit_text_material.xml
  android/app/src/main/res/values/styles.xml
  android/build.gradle
  android/gradle/wrapper/gradle-wrapper.properties
  ios/Artsy.xcodeproj/project.pbxproj
  ios/Podfile.lock
  package.json
  patches/react-native+0.67.5.patch
  src/app/App.tsx
  src/app/Components/Bidding/BidFlow.tests.tsx
  src/app/Components/Bidding/Screens/ConfirmBid.tests.tsx
  src/app/Components/Bidding/Screens/ConfirmBid/index.tsx
  src/app/Components/Bidding/Screens/Registration.tests.tsx
  src/app/Components/Bidding/Screens/Registration.tsx
  src/app/Components/Bidding/Screens/SelectMaxBid.tsx
  yarn.lock
Labels: Jira Synced

#8339 fix(CX-3266): Update AddPhotos image URLs
  src/app/Scenes/MyCollection/Components/MyCollectionImageView.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormAddPhotos.tsx
Labels: Jira Synced

#8354 feat(CX-3516): SWA Lp updates part 2
  src/app/Components/ArtworkRail/ArtworkRailCard.tsx
  src/app/Components/ArtworkRail/useExtraLargeWidth.tsx
  src/app/Scenes/SellWithArtsy/Components/CollectorsNetwork.tsx
  src/app/Scenes/SellWithArtsy/Components/FAQSWA.tsx
  src/app/Scenes/SellWithArtsy/Components/Footer.tsx
  src/app/Scenes/SellWithArtsy/Components/Header.tsx
  src/app/Scenes/SellWithArtsy/Components/Highlights.tsx
  src/app/Scenes/SellWithArtsy/Components/HowItWorks.tsx
  src/app/Scenes/SellWithArtsy/Components/MeetTheSpecialists.tsx
  src/app/Scenes/SellWithArtsy/Components/SellWithArtsyRecentlySold.tsx
  src/app/Scenes/SellWithArtsy/Components/SpeakToTheTeam.tsx
  src/app/Scenes/SellWithArtsy/Components/WaysWeSell.tsx
  src/app/Scenes/SellWithArtsy/Components/icons/Icons.tsx
  src/app/Scenes/SellWithArtsy/SellWithArtsyHome.tsx
  src/app/Scenes/SellWithArtsy/index.tests.tsx
  src/app/store/config/features.ts
Labels: Jira Synced

#8369 refactor(FX-4682): Move save artwork button to artwork actions
  src/app/Scenes/Artwork/Components/AboveTheFoldArtworkPlaceholder.tsx
  src/app/Scenes/Artwork/Components/ArtworkActions.tests.tsx
  src/app/Scenes/Artwork/Components/ArtworkActions.tsx
  src/app/Scenes/Artwork/Components/ArtworkSaveButton.tsx
  src/app/Scenes/Artwork/Components/ArtworkScreenHeader.tests.tsx
  src/app/Scenes/Artwork/Components/ArtworkScreenHeader.tsx
Labels: Jira Synced

#8344 chore: update auction result screen
  src/app/Scenes/AuctionResult/AuctionResult.tests.tsx
  src/app/Scenes/AuctionResult/AuctionResult.tsx
Labels: Jira Synced

#8373 fix: show only past auction results on my collection insights
  src/app/Scenes/MyCollection/Screens/Insights/AuctionResultsForArtistsYouCollectRail.tsx
Labels: Squash On Green

#8379 update useSWAlandingpagedata url
  src/app/Scenes/SellWithArtsy/utils/useSWALandingPageData.tsx
Labels: Squash On Green

#8382 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#8383 Update SWA LP copy
  src/app/Scenes/SellWithArtsy/Components/FAQSWA.tsx
  src/app/Scenes/SellWithArtsy/Components/Header.tsx
  src/app/Scenes/SellWithArtsy/Components/SpeakToTheTeam.tsx
  src/app/Scenes/SellWithArtsy/Components/WaysWeSell.tsx
Labels: Squash On Green

#8380 feat: Add browse more card to auction rails
  src/app/Components/ArtworkRail/ArtworkRail.tsx
  src/app/Components/BrowseMoreRailCard.tsx
  src/app/Scenes/Home/Components/AuctionResultsRail.tsx
  src/app/Scenes/Home/Components/SalesRail.tsx
  src/app/Scenes/Home/homeAnalytics.ts
Labels: Jira Synced

#8386 fix: auction result screen header
  src/app/AppRegistry.tsx
  src/app/Scenes/AuctionResult/AuctionResult.tsx
Labels: Squash On Green

#8387 fix(CX-3542): photos validation issue on swa form
  src/app/Scenes/SellWithArtsy/SubmitArtwork/UploadPhotos/UploadPhotos.tsx
  src/app/Scenes/SellWithArtsy/SubmitArtwork/UploadPhotos/UploadPhotosForm.tsx
Labels: Jira Synced, Squash On Green

#8388 fix(CX-3403): address UI bugs
  src/app/Scenes/AuctionResult/AuctionResult.tests.tsx
  src/app/Scenes/AuctionResult/AuctionResult.tsx
Labels: Jira Synced, Squash On Green

#8389 feat(CX-3416): hide upcoming auction results filters if none are available
  src/app/Components/Artist/ArtistInsights/ArtistInsightsAuctionResults.tsx
  src/app/Components/ArtworkFilter/ArtworkFilterHelpers.ts
  src/app/Components/ArtworkFilter/components/ArtworkFilterOptionCheckboxItem.tsx
Labels: Jira Synced

#8394 chore: run yarn in main
  yarn.lock
Labels: Squash On Green

#8395 fix: remove duplicate filter for upcoming auctio nresults
  src/app/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx
  src/app/Components/ArtworkFilter/components/ArtworkFilterOptionCheckboxItem.tsx
Labels: Jira Synced, Squash On Green

#8390 chore(CX-3487): do not show estimate if an auction is in the past
  src/app/Components/Lists/AuctionResultListItem.tests.tsx
  src/app/Components/Lists/AuctionResultListItem.tsx
  src/app/Scenes/AuctionResult/AuctionResult.tsx
Labels: Jira Synced

#8302 chore: upgrade relay deps and fix typing issues
  package.json
  patches/@types+react-relay+11.0.3.patch
  patches/@types+relay-test-utils+6.0.5.patch
  patches/relay-mock-network-layer+3.0.0.patch
  patches/relay-runtime+14.0.0.patch
  src/app/Components/Artist/ArtistInsights/MarketStats.tests.tsx
  src/app/Components/Artist/ArtistInsights/MarketStats.tsx
  src/app/Providers.tsx
  src/app/Scenes/Artist/Artist.tests.tsx
  src/app/Scenes/Artist/ArtistSavedSearch.tests.tsx
  src/app/Scenes/Artist/SearchCriteria.tests.tsx
  src/app/Scenes/Artwork/Artwork.tsx
  src/app/Scenes/Artwork/Components/OtherWorks.tests.tsx
  src/app/Scenes/Artwork/Components/OtherWorks/OtherWorks.tsx
  src/app/Scenes/BottomTabs/BottomTabs.tests.tsx
  src/app/Scenes/Home/Home.tests.tsx
  src/app/Scenes/Inbox/Components/Conversations/OpenInquiryModalButton.tests.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tests.tsx
  src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsights.tsx
  src/app/Scenes/MyProfile/LoggedInUserInfo.tests.tsx
  src/app/Scenes/Sale/Sale.tests.tsx
  src/app/Scenes/Sale/Sale.tsx
  src/app/Scenes/SavedAddresses/SavedAddresses.tests.tsx
  src/app/Scenes/Search/AutosuggestResults.tests.tsx
  src/app/Scenes/SellWithArtsy/ConsignmentInquiry/ConsignmentInquiryScreen.tsx
  src/app/Scenes/SellWithArtsy/SubmitArtwork/SubmitArtwork.tests.tsx
  src/app/Scenes/SellWithArtsy/index.tests.tsx
  src/app/system/relay/createEnvironment.ts
  src/app/system/relay/defaultEnvironment.ts
  src/app/utils/AboveTheFoldQueryRenderer.tsx
  src/app/utils/tests/resolveMostRecentRelayOperation.ts
  src/app/utils/useImageSearch.ts
  typings/relay-runtime-test.d.ts
  yarn.lock
Labels: Squash On Green

#8396 refactor(practice): Update articles test
  src/app/Scenes/Articles/Articles.tests.tsx
  src/app/Scenes/Articles/ArticlesList.tsx
Labels: Squash On Green

#8397 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#8402 chore: change SWA images
  images/ways-we-sell-auction.png
  images/ways-we-sell-auction@2x.png
  images/ways-we-sell-auction@3x.png
  images/ways-we-sell-online-storefront.png
  images/ways-we-sell-online-storefront@2x.png
  images/ways-we-sell-online-storefront@3x.png
  images/ways-we-sell-private-sales.png
  images/ways-we-sell-private-sales@2x.png
  images/ways-we-sell-private-sales@3x.png
  src/app/Scenes/SellWithArtsy/Components/WaysWeSell.tsx
Labels: Squash On Green

#8403 chore: update redux-flipper to latest version
  package.json
  yarn.lock
Labels: Squash On Green

#8400 fix(quiz): remove html from trending collections desc
  src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsTabs/ArtQuizTrendingCollection.tsx
Labels: Jira Synced

#8405 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#8406 chore: release notes 8.10.0
  fastlane/metadata/android/en-US/changelogs/default.txt
  fastlane/metadata/en-US/release_notes.txt
Labels: Squash On Green

#8409 chore: prepare for new app version
  app.json
Labels: Squash On Green

#8408 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#8410 fix(CX-3581): adjust images container naf the text in the footer
  images/ways-we-sell-auction.png
  images/ways-we-sell-auction@2x.png
  images/ways-we-sell-auction@3x.png
  images/ways-we-sell-online-storefront.png
  images/ways-we-sell-online-storefront@2x.png
  images/ways-we-sell-online-storefront@3x.png
  images/ways-we-sell-private-sales.png
  images/ways-we-sell-private-sales@2x.png
  images/ways-we-sell-private-sales@3x.png
  src/app/Scenes/SellWithArtsy/Components/Footer.tsx
  src/app/Scenes/SellWithArtsy/Components/WaysWeSell.tsx
Labels: Jira Synced

#8417 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#8413 chore: reposition works from galleries you follow
  src/app/Scenes/Home/useHomeModules.ts
Labels: Jira Synced

#8414 chore: rename upcoming auction lots components
  src/app/Scenes/AuctionResults/AuctionResultsScreenWrapper.tsx
  src/app/Scenes/Home/useHomeModules.ts
Labels: Jira Synced

#8412 chore: use version C for new works for you rail
  src/app/Scenes/NewWorksForYou/NewWorksForYou.tsx
Labels: Jira Synced

#8404 chore: update artist rail card
  src/app/Components/Home/ArtistRails/ArtistCard.tsx
Labels: Jira Synced, Squash On Green

#8418 feat: update flip table script to remove __generated__ files
  scripts/flip-table
Labels: Squash On Green

#8415 refactor(cleanup): remove bmw references
  .secrets.baseline
  docs/adding_new_components.md
  ios/Artsy/Emission/ViewControllers/ARMapContainerViewController.m
  src/app/AppRegistry.tsx
  src/app/Scenes/City/City.tsx
  src/app/Scenes/City/CityBMWList.tsx
  src/app/Scenes/City/CityBMWSponsorship.tsx
  src/app/Scenes/City/CityPicker.tsx
  src/app/Scenes/City/Components/AllEvents.tsx
  src/app/Scenes/City/Components/BMWEventSection/index.tests.tsx
  src/app/Scenes/City/Components/BMWEventSection/index.tsx
  src/app/Scenes/City/Components/Event/index.tsx
  src/app/Scenes/City/Components/SavedEventSection/index.tsx
  src/app/Scenes/Fair/Components/FairHeader.tsx
  src/app/Scenes/Fair/FairBMWArtActivation.tests.tsx
  src/app/Scenes/Fair/FairBMWArtActivation.tsx
  src/app/Scenes/Fair/FairHeader.tests.tsx
  src/app/Scenes/Fair/FairMoreInfo.tests.tsx
  src/app/Scenes/Fair/FairMoreInfo.tsx
  src/app/Scenes/Map/Components/CitySwitcherButton.tsx
  src/app/Scenes/Map/GlobalMap.tsx
  src/app/Scenes/Map/types.ts
  src/app/Scenes/Search/components/CityGuideCTA.tests.tsx
  src/app/Scenes/Search/components/CityGuideCTA.tsx
  src/app/__fixtures__/CityFixture.ts
  src/app/routes.ts
  src/app/system/navigation/routes.tests.ts
  src/app/utils/track/schema.ts
Labels: Jira Synced

#8421 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#8422 chore: remove x button
  src/app/Components/Home/ArtistRails/ArtistCard.tsx
  src/app/Components/Home/ArtistRails/ArtistRail.tsx
Labels: Squash On Green

#8423 build(deps): ts updates and linting
  package.json
  src/app/Scenes/Artwork/Components/ImageCarousel/ImageCarousel.tsx
  src/app/Scenes/ArtworkRecommendations/ArtworkRecommendations.tests.tsx
  src/app/Scenes/ArtworkRecommendations/ArtworkRecommendations.tsx
  src/app/Scenes/NewWorksFromGalleriesYouFollow/NewWorksFromGalleriesYouFollow.tests.tsx
  src/app/Scenes/NewWorksFromGalleriesYouFollow/NewWorksFromGalleriesYouFollow.tsx
  src/app/Scenes/RecentlyViewed/RecentlyViewed.tests.tsx
  src/app/Scenes/RecentlyViewed/RecentlyViewed.tsx
  src/app/Scenes/Sales/UpcomingAuctions.tsx
  src/app/Scenes/SimilarToRecentlyViewed/SimilarToRecentlyViewed.tests.tsx
  src/app/Scenes/SimilarToRecentlyViewed/SimilarToRecentlyViewed.tsx
  src/app/utils/refreshHelpers.tsx
  yarn.lock
Labels: Squash On Green, hack12

#8429 fix: step 2 needs resolution to work properly 😅
  package.json
  yarn.lock
Labels: hack12

#8427 fix: remove psych, causing setup issues
  Gemfile
  Gemfile.lock
Labels: Squash On Green
