Repository artsy/eigen, pull requests merged in 2023-04, with the labels that each got.

#8444 fix Failing SWA tests
  src/app/Scenes/SellWithArtsy/index.tests.tsx
Labels: Squash On Green

#7024 fix: allow building eigen for oss contributors
  .env.example
  .gitignore
  docs/getting_started.md
  ios/Artsy.xcodeproj/project.pbxproj
  ios/Artsy/App/ARAppDelegate.m
  ios/Artsy/ArtsyUIFonts/UIFont+ArtsyFonts.m
  ios/Artsy/fonts/Unica77LL-Italic.otf
  ios/Artsy/fonts/Unica77LL-Medium.otf
  ios/Artsy/fonts/Unica77LL-MediumItalic.otf
  ios/Artsy/fonts/Unica77LL-Regular.otf
  ios/Podfile
  scripts/setup-env-for-oss
  scripts/setup-oss-fonts
  src/app/App.tsx
  src/app/system/errorReporting/sentrySetup.ts
  src/app/utils/experiments/hooks.ts
  src/app/utils/experiments/unleashClient.ts
  src/palette/Theme.tsx
Labels: Jira Synced, refinathon, hack11, hack12

#8442 fix: Update home screen on artist follow and artwork save
  src/app/Components/Artist/ArtistHeader.tsx
  src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
  src/app/Components/ArtworkRail/ArtworkRailCard.tsx
  src/app/Scenes/Artwork/Components/ArtworkActions.tests.tsx
  src/app/Scenes/Artwork/Components/ArtworkDetailsRow.tsx
  src/app/Scenes/Artwork/Components/ArtworkSaveButton.tsx
  src/app/Scenes/Home/Components/ArtworkModuleRail.tsx
  src/app/Scenes/Home/Components/MarketingCollectionRail.tsx
  src/app/Scenes/Home/Home.tsx
  src/app/utils/mutations/useSaveArtwork.ts
  src/app/utils/refreshHelpers.tsx
Labels: Jira Synced, Squash On Green

#8445 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#8446 chore: improve home rail views logic
  src/app/Scenes/Home/Home.tsx
  src/app/Scenes/Home/useHomeModules.ts
Labels: Jira Synced

#8449 chore: adjust artist notable works image width
  src/app/Components/Home/ArtistRails/ArtistCard.tsx
Labels: Squash On Green

#8452 fix: round auction sort filter button
  src/app/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx
Labels: Squash On Green

#8435 fix(CX-3570): adjust settings menu to the new requirements
  src/app/Scenes/MyProfile/MyProfileSettings.tests.tsx
  src/app/Scenes/MyProfile/MyProfileSettings.tsx
Labels: Jira Synced

#8456 chore(CX-3371): remove feature flag related logic
  src/app/Components/ArtworkRail/ArtworkRailCard.tsx
  src/app/Scenes/SellWithArtsy/Components/Footer.tsx
  src/app/Scenes/SellWithArtsy/Components/Header.tsx
  src/app/Scenes/SellWithArtsy/Components/HowItWorks.tsx
  src/app/Scenes/SellWithArtsy/Components/SellWithArtsyRecentlySold.tsx
  src/app/Scenes/SellWithArtsy/Components/WhySellWithArtsy.tsx
  src/app/Scenes/SellWithArtsy/SellWithArtsyHome.tsx
  src/app/Scenes/SellWithArtsy/index.tests.tsx
  src/app/store/config/features.ts
Labels: Jira Synced

#8416 chore: sort upcoming auction results by date asc
  src/app/Scenes/AuctionResults/AuctionResultsScreenWrapper.tsx
  src/app/Scenes/AuctionResults/AuctionResultsUpcoming.tsx
  src/app/Scenes/Home/Home.tsx
Labels: Jira Synced, Squash On Green

#8461 fix: position y tracking on artwork rails typo
  src/app/Scenes/Home/Home.tsx
Labels: Squash On Green

#8462 chore: update podfile.lock
  ios/Podfile.lock
Labels: Squash On Green

#8443 feat: update pre-bid checkbox copy
  src/app/Components/Bidding/Screens/ConfirmBid.tests.tsx
  src/app/Components/Bidding/Screens/ConfirmBid/index.tsx
  src/app/Components/Bidding/Screens/Registration.tsx
Labels: hack12

#8448 feat: enable hermes
  HACKS.md
  android/app/build.gradle
  android/app/proguard-rules.pro
  babel.config.js
  package.json
  src/app/utils/DevMenu.tsx
  yarn.lock
Labels: Jira Synced

#8471 chore: Update app version to 8.12.0
  app.json
Labels: Squash On Green

#8470 build(deps): bump @artsy/palette-mobile from 11.0.6 to 11.0.7
  package.json
  yarn.lock
Labels: Squash On Green

#8475 chore: update copy to follow new designs
  src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkSubmitted.tsx
Labels: Jira Synced, Squash On Green

#8472 refactor(palette-migration): Migrate more internal palette components to @artsy/palette-mobile
  package.json
  src/app/Components/ArtistListItem.tsx
  src/app/Components/ArtworkFilter/Filters/AggregationOptionCommonValidation.tsx
  src/app/Components/ArtworkFilter/Filters/SingleSelectOption.tsx
  src/app/Components/ArtworkFilter/Filters/SizesOptionsScreen.tsx
  src/app/Components/ArtworkFilter/Filters/SortOptions.tests.tsx
  src/app/Components/PartnerEntityHeader.tsx
  src/app/Scenes/ArtistSeries/ArtistSeriesMeta.tests.tsx
  src/app/Scenes/ArtistSeries/ArtistSeriesMeta.tsx
  src/app/Scenes/Artwork/Components/ArtworkEditionSetItem.tsx
  src/app/Scenes/Artwork/Components/PartnerCard.tests.tsx
  src/app/Scenes/Artwork/Components/PartnerCard.tsx
  src/app/Scenes/BottomTabs/BottomTabsButton.tsx
  src/app/Scenes/Inbox/Components/Conversations/EditionSelectBox.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/Dimensions.tsx
  src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightBigCard.tsx
  src/app/Scenes/Onboarding/OnboardingQuiz/Components/ArtistListItem.tsx
  src/app/Scenes/Onboarding/OnboardingQuiz/Components/PartnerListItem.tsx
  src/app/Scenes/SavedSearchAlertsList/Components/SortByModal.tsx
  src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkDetails/ArtworkDetailsForm.tsx
  src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkSubmitted.tsx
  src/palette/elements/EntityHeader/EntityHeader.tsx
  src/palette/elements/EntityHeader/index.tsx
  src/palette/elements/Header/ArtsyLogoHeader.tsx
  src/palette/elements/Header/Header.stories.tsx
  src/palette/elements/Header/index.tsx
  src/palette/elements/PopIn/PopIn.tsx
  src/palette/elements/PopIn/index.ts
  src/palette/elements/Radio/RadioButton.stories.tsx
  src/palette/elements/Radio/RadioButton.tests.tsx
  src/palette/elements/Radio/RadioButton.tsx
  src/palette/elements/Radio/RadioDot.tsx
  src/palette/elements/Radio/index.tsx
  src/palette/elements/Select/SelectV2.tsx
  src/palette/elements/VisualClue/VisualClueText.tsx
  src/palette/elements/index.tsx
  src/storybook/storybook.requires.js
  yarn.lock
Labels: Jira Synced

#8476 chore: Fix home viewAreaCoveragePercentThreshold fields and type
  src/app/Components/PrefetchFlatList.tsx
  src/app/Scenes/Home/Home.tsx
Labels: Squash On Green

#8464 chore: prompt to overwrite current running beta build
  scripts/deploy-beta-android
  scripts/deploy-beta-ios
Labels: Squash On Green

#8474 chore(TX-1114): update wire transfer details
  src/app/Scenes/OrderHistory/OrderDetails/Components/WirePaymentSection.tsx
  src/app/Scenes/OrderHistory/OrderDetails/WirePaymentSection.tests.tsx
Labels: Jira Synced

#8485 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#8370 feat: integrate Sift SDK (PRO-87)
  ios/Podfile.lock
  package.json
  src/app/App.tsx
  src/app/store/AuthModel.ts
  src/app/utils/useIdentifyUser.ts
  src/app/utils/useSiftConfig.ts
  src/setupJest.ts
  yarn.lock
Labels: Jira Synced

#8488 feat: Add Price Database route
  android/app/src/main/AndroidManifest.xml
  src/app/AppRegistry.tsx
  src/app/Scenes/PriceDatabase/PriceDatabase.tests.tsx
  src/app/Scenes/PriceDatabase/PriceDatabase.tsx
  src/app/routes.ts
Labels: Jira Synced, Squash On Green

#8490 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#8317 chore: remove adjust sdk
  android/app/build.gradle
  android/app/src/main/java/net/artsy/app/MainApplication.java
  ios/Artsy/App/ARAppActivityContinuationDelegate.m
  ios/Artsy/App/ARAppDelegate.m
  ios/Podfile
  ios/Podfile.lock
  package.json
  src/app/utils/track/SegmentTrackingProvider.ts
  yarn.lock
Labels: Jira Synced, Squash On Green

#8494 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#8473 build: enable hermes on android
  android/app/build.gradle
  fastlane/Fastfile
  package.json
  scripts/build-for-tests-android
Labels: Jira Synced, Squash On Green

#8487 chore: Add artist ID to saveArtwork event
  package.json
  src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx
  yarn.lock
Labels: Squash On Green

#8496 Fix(CX-3599): Fix broken vanityURLs in Webview
  src/app/Components/ArtsyWebView.tsx
  src/app/Scenes/VanityURL/VanityURLEntity.tsx
Labels: Jira Synced

#8489 feat: Price Database form
  package.json
  src/app/Components/ArtistAutosuggest/ArtistAutosuggest.tsx
  src/app/Components/ArtistAutosuggest/ArtistAutosuggestRow.tsx
  src/app/Components/ArtworkFilter/components/ArtworkFilterBackHeader.tsx
  src/app/Scenes/PriceDatabase/PriceDatabase.tests.tsx
  src/app/Scenes/PriceDatabase/PriceDatabase.tsx
  src/app/Scenes/PriceDatabase/components/MediumOptions.tsx
  src/app/Scenes/PriceDatabase/components/PriceDatabaseSearch.tsx
  src/app/Scenes/PriceDatabase/components/SizesOptions.tsx
  src/app/Scenes/PriceDatabase/utils/helpers.tests.ts
  src/app/Scenes/PriceDatabase/utils/helpers.ts
  src/app/Scenes/PriceDatabase/validation.ts
  src/app/store/AuthModel.ts
  yarn.lock
Labels: Jira Synced

#8501 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#8502 chore: Upgrade Cohesion to 4.124.0
  package.json
  src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tsx
  yarn.lock
Labels: Squash On Green

#8503 Feat: Update Copy Changes
  src/app/Scenes/MyCollection/MyCollection.tests.tsx
  src/app/Scenes/MyCollection/MyCollectionArtworks.tsx
  src/app/Scenes/SellWithArtsy/Components/Footer.tsx
Labels: Jira Synced

#8499 chore: support only ios 13 and above
  ios/Artsy.xcodeproj/project.pbxproj
  ios/Podfile
  ios/Podfile.lock
Labels: Jira Synced

#8507 chore: change title
  src/app/Scenes/MyAccount/MyAccount.tsx
Labels: Squash On Green

#8498 feat(CX-3598): add new onboarding cards to home screen
  images/meet-your-new-art-advisor-0.jpg
  images/meet-your-new-art-advisor-0@2x.jpg
  images/meet-your-new-art-advisor-0@3x.jpg
  images/meet-your-new-art-advisor-1.jpg
  images/meet-your-new-art-advisor-1@2x.jpg
  images/meet-your-new-art-advisor-1@3x.jpg
  images/meet-your-new-art-advisor-2.jpg
  images/meet-your-new-art-advisor-2@2x.jpg
  images/meet-your-new-art-advisor-2@3x.jpg
  images/meet-your-new-art-advisor-3.jpg
  images/meet-your-new-art-advisor-3@2x.jpg
  images/meet-your-new-art-advisor-3@3x.jpg
  src/app/Scenes/Home/Components/ContentCards.tsx
  src/app/Scenes/Home/Components/HomeFeedModalCarousel/HomeFeedModalCarouselContainer.tsx
  src/app/Scenes/Home/Components/HomeFeedOnboardingCard.tsx
  src/app/Scenes/Home/Components/MeetYourNewAdvisorRail.tests.tsx
  src/app/Scenes/Home/Components/MeetYourNewAdvisorRail.tsx
  src/app/Scenes/Home/Home.tsx
  src/app/Scenes/Home/useHomeModules.ts
Labels: Jira Synced, Squash On Green

#8505 fix(NX-3507): use the right backgroundColor for counterOffer banner
  src/app/Scenes/Inbox/Components/Conversations/Composer.tests.tsx
  src/app/Scenes/Inbox/Components/Conversations/ConversationCTA.tests.tsx
  src/app/Scenes/Inbox/Components/Conversations/OrderUpdate.tsx
  src/app/Scenes/Inbox/Components/Conversations/ReviewOfferButton.tsx
Labels: Jira Synced

#8512 fix: Add keyboardShouldPersistTaps to price database scroll view
  src/app/Scenes/PriceDatabase/components/PriceDatabaseSearch.tsx
Labels: Squash On Green

#8514 build(deps): bumps palette version with reanimated fixes
  package.json
  yarn.lock
Labels: Squash On Green

#8515 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#8518 feat(CX-3596): Apply filters from Price Database form to Artist Auction Results
  src/app/Components/Artist/ArtistInsights/ArtistInsights.tsx
  src/app/Components/Artist/ArtistInsights/ArtistInsightsAuctionResults.tsx
  src/app/Components/ArtworkFilter/ArtworkFilterHelpers.ts
  src/app/Scenes/Artist/Artist.tsx
  src/app/routes.ts
Labels: Jira Synced, Squash On Green

#8504 fix(FX-4728): inconsistency in auction countdown on home feed
  src/app/Components/Artist/ArtistArtworks/ArtistNotableWorksRail.tests.tsx
  src/app/Components/ArtworkRail/ArtworkRailCard.tsx
Labels: Jira Synced, Squash On Green

#8510 add back button to the price database screen
  src/app/Scenes/PriceDatabase/PriceDatabase.tests.tsx
  src/app/Scenes/PriceDatabase/PriceDatabase.tsx
  src/app/Scenes/PriceDatabase/components/PriceDatabaseSearch.tsx
Labels: Jira Synced

#8520 chore: Use keyboardShouldPersistTaps always in price database
  src/app/Scenes/PriceDatabase/components/PriceDatabaseSearch.tsx
Labels: Squash On Green

#8521 revert(build): enable hermes on android
  android/app/build.gradle
  fastlane/Fastfile
  package.json
  scripts/build-for-tests-android
Labels: Squash On Green

#8522 revert(feat): enable hermes
  HACKS.md
  android/app/build.gradle
  android/app/proguard-rules.pro
  babel.config.js
  package.json
  src/app/utils/DevMenu.tsx
  yarn.lock
Labels: Squash On Green

#8525 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#8527 fix(FX-4741): Ended auctions can accept bidding on and the end date gets extended
  src/app/Scenes/Artwork/Components/ArtworkStickyBottomContent.tests.tsx
  src/app/Scenes/Artwork/Components/ArtworkStickyBottomContent.tsx
Labels: Jira Synced

#8532 chore(registry): Alphabetize AppRegistry definition
  src/app/AppRegistry.tsx
Labels: Squash On Green

#8533 chore: specify new mac resource in config
  .circleci/config.yml
Labels: Jira Synced

#8535 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#8536 chore(CX-3624): Prepare feature flags for the release
  src/app/store/config/features.ts
Labels: Jira Synced, Squash On Green

#8538 fix: update url for advisor rail
  src/app/Scenes/Home/Components/MeetYourNewAdvisorRail.tests.tsx
  src/app/Scenes/Home/Components/MeetYourNewAdvisorRail.tsx
Labels: Squash On Green

#8543 chore: add artwork lists feature flag
  src/app/store/config/features.ts
Labels: Squash On Green

#8545 chore(GRO-1554): change artist page rail title to Featured Works
  src/app/Components/Artist/ArtistArtworks/ArtistNotableWorksRail.tsx
Labels: Merge On Green, Jira Synced

#8541 fix: make sure user is identified before requesting services
  ios/Podfile.lock
  src/app/App.tsx
  src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResults.tsx
  src/app/Scenes/Home/Home.tsx
  src/app/Scenes/NewWorksForYou/NewWorksForYou.tsx
  src/app/Scenes/Onboarding/OnboardingSocialPick.tsx
  src/app/store/AuthModel.ts
  src/app/system/devTools/useRageShakeDevMenu.ts
  src/app/utils/PushNotification.tests.ts
  src/app/utils/experiments/UnleashProvider.tsx
  src/app/utils/experiments/helpers.ts
  src/app/utils/experiments/unleashClient.ts
  src/app/utils/useIdentifyUser.ts
  src/setupJest.ts
Labels: Jira Synced

#8542 chore(NX-3493): replace Zendesk with Salesforce links
  src/app/Scenes/Artwork/Components/ArtworkLotDetails/LotCascadingEndTimesBanner.tsx
  src/app/Scenes/Artwork/Components/CascadingEndTimesBanner.tsx
  src/app/Scenes/Artwork/Components/CertificateAuthenticity.tests.tsx
  src/app/Scenes/Artwork/Components/CertificateAuthenticity.tsx
  src/app/Scenes/Inbox/Components/Conversations/Support.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/ArtworkSubmissionStatusFAQ.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionSellingWithartsyFAQ.tsx
  src/app/Scenes/SellWithArtsy/Components/FAQSWA.tsx
  src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkDetails/ArtworkDetails.tsx
Labels: Jira Synced, help links migration

#8551 chore: update version, update fastlane #trivial
  Gemfile.lock
  app.json
Labels: Squash On Green

#8544 feat(FX-4753): save/unsave artwork to the default artwork list when the 💙 button is pressed on artwork detail screen
  src/app/Components/ArtworkLists/ArtworkListsContext.tsx
  src/app/Components/ArtworkLists/useArtworkListsToast.ts
  src/app/Components/ArtworkLists/useSaveArtworkToArtworkLists.ts
  src/app/Scenes/Artwork/Artwork.tsx
  src/app/Scenes/Artwork/Components/ArtworkActions.tests.tsx
  src/app/Scenes/Artwork/Components/ArtworkHeader.tests.tsx
  src/app/Scenes/Artwork/Components/ArtworkSaveButton.tsx
  src/app/utils/mutations/useSaveArtwork.ts
Labels: Jira Synced

#8554 feat(FX-4753, FX-4754, FX-4757): add bottom sheets for artwork lists
  src/app/Components/ArtworkLists/ArtworkListsContext.tsx
  src/app/Components/ArtworkLists/components/ArtworkListsBottomSheetBackdrop.tsx
  src/app/Components/ArtworkLists/components/AutomountedBottomSheetModal.tsx
  src/app/Components/ArtworkLists/views/CreateNewArtworkListView.tsx
  src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView.tests.tsx
  src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView.tsx
Labels: Jira Synced

#8556 feat(FX-4757): Create new list bottom sheet logic
  src/app/Components/ArtworkLists/ArtworkListsContext.tsx
  src/app/Components/ArtworkLists/components/ArtworkListsBottomSheetSectionTitle.tsx
  src/app/Components/ArtworkLists/views/CreateNewArtworkListView.tsx
  src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView.tsx
  src/app/Components/BottomSheetInput.tsx
Labels: Jira Synced

#8561 chore: enable impressions tracking for artworks in home feed
  src/app/store/config/features.ts
Labels: Squash On Green

#8562 chore(CX-3625): change the Assets and the copy of the "Meet your new art advisor" as according to design
  images/meet-your-new-art-advisor-0.jpg
  images/meet-your-new-art-advisor-0@2x.jpg
  images/meet-your-new-art-advisor-0@3x.jpg
  images/meet-your-new-art-advisor-1.jpg
  images/meet-your-new-art-advisor-1@2x.jpg
  images/meet-your-new-art-advisor-1@3x.jpg
  images/meet-your-new-art-advisor-2.jpg
  images/meet-your-new-art-advisor-2@2x.jpg
  images/meet-your-new-art-advisor-2@3x.jpg
  images/meet-your-new-art-advisor-3.jpg
  images/meet-your-new-art-advisor-3@2x.jpg
  images/meet-your-new-art-advisor-3@3x.jpg
  src/app/Scenes/Home/Components/MeetYourNewAdvisorRail.tsx
Labels: Jira Synced

#8546 feat: update view in room, allow more instant placement
  .circleci/config.yml
  ios/Artsy.xcodeproj/project.pbxproj
  ios/Artsy/NativeModules/ARTNativeScreenPresenterModule.m
  ios/Artsy/Resources/Artsy-Bridging-Header.h
  ios/Artsy/View_Controllers/ARVIR/Assets/ARVIRModalClose.png
  ios/Artsy/View_Controllers/ARVIR/Assets/ARVIRModalClose@2x.png
  ios/Artsy/View_Controllers/ARVIR/Assets/ARVIRModalClose@3x.png
  ios/Artsy/View_Controllers/ARVIR/Assets/ARVIRShadow.png
  ios/Artsy/View_Controllers/ARVIR/Assets/ARVIRTick.png
  ios/Artsy/View_Controllers/ARVIR/Assets/ARVIRTick@2x.png
  ios/Artsy/View_Controllers/ARVIR/Assets/ARVIRTick@3x.png
  ios/Artsy/View_Controllers/ARVIR/Assets/ar_vir_opening_frame.jpg
  ios/Artsy/View_Controllers/ARVIR/Nodes/AppleARCode/FocusSquare.swift
  ios/Artsy/View_Controllers/ARVIR/Nodes/AppleARCode/FocusSquareSegment.swift
  ios/Artsy/View_Controllers/ARVIR/Nodes/AppleARCode/LICENSE/LICENSE.txt
  ios/Artsy/View_Controllers/ARVIR/Nodes/AppleARCode/Utilities.swift
  ios/Artsy/View_Controllers/ARVIR/Nodes/VirtualArtwork.swift
  ios/Artsy/View_Controllers/ARVIR/VCs/ARAugmentedFloorBasedVIRViewController.m
  ios/Artsy/View_Controllers/ARVIR/VCs/ARAugmentedVIRSetupViewController.h
  ios/Artsy/View_Controllers/ARVIR/VCs/ARAugmentedVIRSetupViewController.m
  ios/Artsy/View_Controllers/ARVIR/VCs/ARAugmentedWallBasedVIRViewController.swift
  ios/Artsy/View_Controllers/ARVIR/Views/ARInformationView.h
  ios/Artsy/View_Controllers/Live_Auctions/LiveActionStateReconciler.swift
  ios/ArtsyTests/View_Controller_Tests/ARVIR/ARAugmentRealitySetupViewControllerSpec.m
  src/app/NativeModules/LegacyNativeModules.tsx
  src/app/Scenes/Artwork/Components/ArtworkActions.tsx
  src/app/Scenes/ViewingRoom/ViewingRoomArtwork.tsx
  src/app/store/config/features.ts
  src/app/utils/DevMenu.tsx
Labels: Jira Synced

#8564 fix: Update useFeatureFlag imports to fix failing tests
  src/app/Scenes/Artwork/Components/ArtworkActions.tsx
  src/app/Scenes/ViewingRoom/ViewingRoomArtwork.tsx
Labels: Squash On Green

#8565 fix: Update CI badge url
  README.md
Labels: Squash On Green

#8566 fix: double x button in purchase flows
  src/app/Components/ArtsyWebView.tsx
Labels: Jira Synced

#8557 feat(FX-4754, FX-4755): fetch artwork lists + pagination + pull-to-refresh
  src/app/Components/ArtworkLists/ArtworkListsContext.tests.tsx
  src/app/Components/ArtworkLists/ArtworkListsContext.tsx
  src/app/Components/ArtworkLists/components/AutomountedBottomSheetModal.tsx
  src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView.tests.tsx
  src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/SelectArtworkListsForArtworkView.tsx
  src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/components/ArtworkListItem.tsx
  src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/components/ArtworkLists.tsx
  src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/components/ArtworkListsLoadingIndicator.tsx
  src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/components/SelectArtworkListsForArtwork.tsx
  src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/utils/getSelectedArtworkListIds.tests.ts
  src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/utils/getSelectedArtworkListIds.ts
Labels: Jira Synced

#8570 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#8549 feat(CX-3604): Urgency Info | New Auction Lots For You ending soon
  src/app/Components/LotsByArtistsYouFollowRail/LotsByFollowedArtistsRail.tsx
  src/app/Components/SaleArtworkTileRailCard/SaleArtworkTileRailCard.tsx
  src/app/Components/SaleArtworkTileRailCard/UrgencyInfo.tests.tsx
  src/app/Components/SaleArtworkTileRailCard/UrgencyInfo.tsx
  src/app/Scenes/Home/Home.tsx
  src/app/store/config/features.ts
Labels: Jira Synced

#8573 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#8581 chore: add collected artists feature flag
  src/app/store/config/features.ts
Labels: Jira Synced, Squash On Green

#8563 refactor: make share sheet global
  src/app/Components/Artist/ArtistHeaderFloatingButtons.tsx
  src/app/Components/CustomShareSheet.tsx
  src/app/Components/ShareSheet/ShareSheet.tests.tsx
  src/app/Components/ShareSheet/ShareSheet.tsx
  src/app/Components/ShareSheet/ShareSheetContext.tsx
  src/app/Components/ShareSheet/ShareSheetItem.tsx
  src/app/Components/ShareSheet/helpers.tests.ts
  src/app/Components/ShareSheet/helpers.ts
  src/app/Components/ShareSheet/types.ts
  src/app/Providers.tsx
  src/app/Scenes/Artwork/Components/ArtworkHeader.tsx
  src/app/Scenes/Sale/Components/SaleHeader.tsx
  src/app/Scenes/ViewingRoom/ViewingRoom.tsx
Labels: Squash On Green

#8571 feat(FX-4754): display artwork data in artwork lists bottom sheet
  src/app/Components/ArtworkLists/ArtworkListsContext.tests.tsx
  src/app/Components/ArtworkLists/components/ArtworkInfo.tests.tsx
  src/app/Components/ArtworkLists/components/ArtworkInfo.tsx
  src/app/Components/ArtworkLists/components/ArtworkListsBottomSheetSectionTitle.tsx
  src/app/Components/ArtworkLists/views/CreateNewArtworkListView.tsx
  src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/SelectArtworkListsForArtworkView.tsx
Labels: Jira Synced, Squash On Green

#8586 fix: don't let the bidders call get cached
  ios/Artsy/Networking/ARRouter.m
Labels: Jira Synced, Squash On Green

#8580 feat: update show rail card
  src/app/Components/ShowCard.tests.tsx
  src/app/Components/ShowCard.tsx
Labels: Jira Synced

#8575 feat(FX-4755): Select lists for this artwork view
  src/app/Components/ArtworkLists/ArtworkListsContext.tests.tsx
  src/app/Components/ArtworkLists/components/ArtworkInfo.tsx
  src/app/Components/ArtworkLists/components/EntityPreview.tsx
  src/app/Components/ArtworkLists/views/CreateNewArtworkListView.tsx
  src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/SelectArtworkListsForArtworkView.tsx
  src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/components/ArtworkListItem.tsx
  src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/components/ArtworkListItemSelectedIcon.tsx
  src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/components/SelectArtworkListsForArtwork.tsx
  src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/components/SelectArtworkListsForArtworkFooter.tsx
  src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/components/SelectArtworkListsForArtworkHeader.tsx
  src/app/Components/ArtworkLists/views/constants.ts
Labels: Jira Synced

#8585 feat(FX-4756): Save updated artwork lists for artwork
  src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/components/SelectArtworkListsForArtwork.tsx
  src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/components/SelectArtworkListsForArtworkFooter.tsx
  src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/useUpdateArtworkListsForArtwork.tests.ts
  src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/useUpdateArtworkListsForArtwork.ts
Labels: Jira Synced

#8589 fix: Adjust Meet the Specialists animation
  src/app/Scenes/SellWithArtsy/Components/MeetTheSpecialists.tsx
  src/app/utils/animations/AnimateHeight.tsx
Labels: Jira Synced

#8592 fix(CX-3661): Correct Urgency Info text color
  src/app/Components/SaleArtworkTileRailCard/UrgencyInfo.tests.tsx
  src/app/Components/SaleArtworkTileRailCard/UrgencyInfo.tsx
  src/app/store/config/features.ts
Labels: Jira Synced, Squash On Green

#8594 fix: only request push notifications once per login session
  ios/Artsy/App/ARAppNotificationsDelegate.m
  src/app/Scenes/Home/HomeContainer.tsx
  src/app/store/AuthModel.ts
Labels: Jira Synced, Squash On Green

#8595 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#8597 chore: restore haptic effect for "Save" button
  src/app/Scenes/Artwork/Components/ArtworkSaveButton.tsx
Labels: Squash On Green

#8582 feat(CX-3635):update my collection sticky tab
  src/app/Components/ArtworkGrids/ArtworksFilterHeader.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionStickyHeader.tsx
  src/app/Scenes/MyCollection/MyCollection.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkArtistAuctionResults.tsx
  src/app/Scenes/Search/components/SearchPills.tsx
  src/app/utils/hooks/useMeasure.ts
Labels: Jira Synced

#8598 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#8596 chore(easy-peasy): Upgrade to 6
  .secrets.baseline
  package.json
  src/app/Components/Artist/ArtistInsights/ArtistInsightsAuctionResults.tests.tsx
  src/app/Components/ArtworkFilter/ArtworkFilterStore.tsx
  src/app/Components/ArtworkFilter/FilterModal.tests.tsx
  src/app/Components/ArtworkFilter/FilterTestHelper.tsx
  src/app/Components/ArtworkFilter/Filters/AdditionalGeneIDsOptions.tests.tsx
  src/app/Components/ArtworkFilter/Filters/AggregationOptionCommonValidation.tsx
  src/app/Components/ArtworkFilter/Filters/ArtistIDsArtworksOptions.tests.tsx
  src/app/Components/ArtworkFilter/Filters/ArtistIDsSaleArtworksOptionsScreen.tests.tsx
  src/app/Components/ArtworkFilter/Filters/ArtistNationalitiesOptions.tests.tsx
  src/app/Components/ArtworkFilter/Filters/AttributionClassOptions.tests.tsx
  src/app/Components/ArtworkFilter/Filters/AuctionHouseOptions.tests.tsx
  src/app/Components/ArtworkFilter/Filters/CategoriesOptions.tests.tsx
  src/app/Components/ArtworkFilter/Filters/ColorsOptions.tests.tsx
  src/app/Components/ArtworkFilter/Filters/GalleriesAndInstitutionsOptions.tests.tsx
  src/app/Components/ArtworkFilter/Filters/KeywordFilter.tests.tsx
  src/app/Components/ArtworkFilter/Filters/LocationCitiesOptions.tests.tsx
  src/app/Components/ArtworkFilter/Filters/MaterialsTermsOptions.tests.tsx
  src/app/Components/ArtworkFilter/Filters/PriceRangeOptions.tests.tsx
  src/app/Components/ArtworkFilter/Filters/SizesOptionsScreen.tests.tsx
  src/app/Components/ArtworkFilter/Filters/SortOptions.tests.tsx
  src/app/Components/ArtworkFilter/Filters/TimePeriodOptions.tests.tsx
  src/app/Components/ArtworkFilter/Filters/WaysToBuyOptions.tests.tsx
  src/app/Components/ArtworkFilter/Filters/YearOptions.tests.tsx
  src/app/Components/ArtworkFilter/Filters/useMultiSelect.tests.tsx
  src/app/Components/ArtworkFilter/components/ArtworkFilterOptionCheckboxItem.tests.tsx
  src/app/Components/HeaderArtworksFilter/HeaderArtworksFilterWithTotalArtworks.tests.tsx
  src/app/NativeModules/ARScreenPresenterModule.tsx
  src/app/Scenes/Artwork/Artwork.tsx
  src/app/Scenes/Artwork/ArtworkStore.tsx
  src/app/Scenes/Artwork/Components/ArtworkEditionSetInformation.tests.tsx
  src/app/Scenes/Artwork/Components/ArtworkPrice.tests.tsx
  src/app/Scenes/Artwork/Components/ArtworkStickyBottomContent.tests.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/RequestForPriceEstimate/RequestForPriceEstimateBanner.tests.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tests.tsx
  src/app/Scenes/MyProfile/MyProfilePaymentNewCreditCard.tsx
  src/app/Scenes/Sale/SaleLotsList.tests.tsx
  src/app/Scenes/SavedSearchAlert/CreateSavedSearchAlert.tests.tsx
  src/app/Scenes/SavedSearchAlert/EditSavedSearchAlert.tsx
  src/app/Scenes/SavedSearchAlert/SavedSearchAlertForm.tests.tsx
  src/app/Scenes/SavedSearchAlert/SavedSearchStore.tsx
  src/app/Scenes/SavedSearchAlert/screens/CreateSavedSearchAlertScreen.tsx
  src/app/Scenes/Search/SearchModel.tests.tsx
  src/app/store/AuthModel.ts
  src/app/store/GlobalStore.tsx
  src/app/store/config/features.ts
  src/app/store/migration.ts
  src/app/store/persistence.ts
  src/app/system/relay/middlewares/checkAuthenticationMiddleware.tests.ts
  src/app/system/relay/usePurgeCacheOnAppUpdate.ts
  src/app/utils/DevMenu.tsx
  yarn.lock
Labels: Jira Synced, Squash On Green

#8600 fix: add missing tag deeplink to android
  android/app/src/main/AndroidManifest.xml
Labels: Squash On Green

#8593 feat(FX-4757, FX-4758): Create new artwork list UI
  src/app/Components/ArtworkLists/ArtworkListsContext.tsx
  src/app/Components/ArtworkLists/views/CreateNewArtworkListView/CreateNewArtworkListView.tests.tsx
  src/app/Components/ArtworkLists/views/CreateNewArtworkListView/CreateNewArtworkListView.tsx
  src/app/Components/ArtworkLists/views/CreateNewArtworkListView/components/CreateNewArtworkListForm.tsx
  src/app/Components/ArtworkLists/views/CreateNewArtworkListView/components/CreateNewArtworkListInput.tsx
  src/app/Components/ArtworkLists/views/CreateNewArtworkListView/components/RemainingCharactersLabel.tsx
  src/app/Components/ArtworkLists/views/CreateNewArtworkListView/useCreateNewArtworkList.ts
  src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/components/ArtworkLists.tsx
Labels: Jira Synced
