Repository artsy/eigen, pull requests merged in 2024-09, with the labels that each got.

#10697 feat(EMI-2050): replace watch lot icon with heart icon
  src/app/Scenes/Artwork/Components/ArtworkSaveButton.tsx
Labels: Jira Synced, Squash On Green

#10571 feat: add galleries near you rail
  data/schema.graphql
  src/app/Scenes/HomeView/HomeView.tsx
  src/app/Scenes/HomeView/Sections/GalleriesHomeViewSection.tests.tsx
  src/app/Scenes/HomeView/Sections/GalleriesHomeViewSection.tsx
  src/app/Scenes/HomeView/Sections/Section.tsx
Labels: Jira Synced, Squash On Green, Art Advisor

#10692 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10702 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10698 fix: Update view saves button issue
  src/app/Components/ArtworkLists/useArtworkListsToast.ts
  src/app/routes.ts
Labels: Jira Synced

#10699 feat(EMI-2044): Add tracking to Auction Signals
  src/app/Components/ArtworkGrids/ArtworkGridItem.tests.tsx
  src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
  src/app/Components/ArtworkRail/LargeArtworkRail.tsx
  src/app/Components/ArtworkRail/SmallArtworkRail.tsx
  src/app/Scenes/Artwork/Components/ArtworkCommercialButtons.tests.tsx
  src/app/Scenes/Artwork/Components/ArtworksInSeriesRail.tests.tsx
  src/app/Scenes/Artwork/Components/ArtworksInSeriesRail.tsx
  src/app/Scenes/Artwork/Components/CommercialButtons/BidButton.tsx
  src/app/Scenes/Artwork/Components/CommercialButtons/ContactGalleryButton.tests.tsx
  src/app/Scenes/Artwork/Components/CommercialButtons/ContactGalleryButton.tsx
  src/app/Scenes/Fair/Components/FairExhibitorRail.tsx
  src/app/Scenes/Fair/Components/FairFollowedArtistsRail.tsx
  src/app/Scenes/Fair/FairExhibitorRail.tests.tsx
  src/app/Scenes/Fair/FairFollowedArtistsRail.tests.tsx
  src/app/Scenes/Home/Components/ArtworkRecommendationsRail.tsx
  src/app/Scenes/Home/Components/NewWorksForYouRail.tsx
  src/app/Scenes/Home/homeAnalytics.ts
  src/app/Scenes/SavedSearchAlert/screens/ConfirmationScreen.tests.tsx
  src/app/Scenes/SavedSearchAlert/screens/ConfirmationScreen.tsx
  src/app/utils/getArtworkSignalTrackingFields.ts
Labels: Jira Synced

#10710 fix(EMI-2051): adjust icon size on artwork rail card component
  src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
  src/app/Components/ArtworkRail/ArtworkRailCard.tsx
  src/app/Components/constants.ts
Labels: Jira Synced

#10716 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10719 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10701 feat: improve visual parity with existing home screen
  src/app/Scenes/HomeView/Components/ActivityIndicator.tests.tsx
  src/app/Scenes/HomeView/Components/ActivityIndicator.tsx
  src/app/Scenes/HomeView/Components/HomeHeader.tests.tsx
  src/app/Scenes/HomeView/Components/HomeHeader.tsx
  src/app/Scenes/HomeView/HomeView.tsx
Labels: Jira Synced, Squash On Green

#10721 chore: Prepare for v8.51.0
  app.json
Labels: Squash On Green

#10591 refactor(masonry): Migrate ArtistSeries Artworks to use MasonryTabs
  src/app/Components/constants.ts
  src/app/Scenes/ArtistSeries/ArtistSeries.tests.tsx
  src/app/Scenes/ArtistSeries/ArtistSeries.tsx
  src/app/Scenes/ArtistSeries/ArtistSeriesArtworks.tests.tsx
  src/app/Scenes/ArtistSeries/ArtistSeriesArtworks.tsx
  src/app/Scenes/ArtistSeries/ArtistSeriesHeader.tests.tsx
  src/app/Scenes/ArtistSeries/ArtistSeriesHeader.tsx
  src/app/Scenes/ArtistSeries/ArtistSeriesMeta.tests.tsx
  src/app/Scenes/ArtistSeries/ArtistSeriesMeta.tsx
  src/app/Scenes/ArtistSeries/ArtistSeriesMoreSeries.tsx
  src/app/Scenes/Fair/Fair.tsx
Labels: Jira Synced, Squash On Green

#10723 feat(onyx-1259): home view sections use use behaviors.viewAll.href field for navigation
  src/app/Scenes/Home/Components/ArticlesRail.tsx
  src/app/Scenes/HomeView/Sections/ActivityRailHomeViewSection.tsx
  src/app/Scenes/HomeView/Sections/ArticlesCardsHomeViewSection.tests.tsx
  src/app/Scenes/HomeView/Sections/ArticlesCardsHomeViewSection.tsx
  src/app/Scenes/HomeView/Sections/ArticlesRailHomeViewSection.tsx
  src/app/Scenes/HomeView/Sections/ArtistsRailHomeViewSection.tsx
  src/app/Scenes/HomeView/Sections/ArtworksRailHomeViewSection.tsx
  src/app/Scenes/HomeView/Sections/AuctionResultsRailHomeViewSection.tests.tsx
  src/app/Scenes/HomeView/Sections/AuctionResultsRailHomeViewSection.tsx
  src/app/Scenes/HomeView/Sections/FairsRailHomeViewSection.tsx
  src/app/Scenes/HomeView/Sections/FeaturedCollectionHomeViewSection.tsx
  src/app/Scenes/HomeView/Sections/GalleriesHomeViewSection.tests.tsx
  src/app/Scenes/HomeView/Sections/GalleriesHomeViewSection.tsx
  src/app/Scenes/HomeView/Sections/MarketingCollectionsRailHomeViewSection.tsx
  src/app/Scenes/HomeView/Sections/SalesRailHomeViewSection.tests.tsx
  src/app/Scenes/HomeView/Sections/SalesRailHomeViewSection.tsx
  src/app/Scenes/HomeView/Sections/ViewingRoomsRailHomeViewSection.tsx
Labels: Jira Synced

#10706 feat: add ArtworksRailHomeViewSection tracking
  src/app/Scenes/HomeView/Sections/ArtworksRailHomeViewSection.tests.tsx
  src/app/Scenes/HomeView/Sections/ArtworksRailHomeViewSection.tsx
Labels: Jira Synced, Squash On Green, Art Advisor

#10731 chore: Fix breaking tests after releasing Auction Signals
  src/app/Components/ArtworkGrids/ArtworkGridItem.tests.tsx
  src/app/Components/ArtworkRail/ArtworkRailCard.tests.tsx
  src/app/Scenes/Artwork/Components/ArtworkCommercialButtons.tests.tsx
  src/app/Scenes/Artwork/Components/ArtworksInSeriesRail.tests.tsx
  src/app/Scenes/Artwork/Components/CommercialButtons/ContactGalleryButton.tests.tsx
  src/app/Scenes/Fair/FairExhibitorRail.tests.tsx
  src/app/Scenes/Fair/FairFollowedArtistsRail.tests.tsx
  src/app/Scenes/SavedSearchAlert/screens/ConfirmationScreen.tests.tsx
Labels: Squash On Green

#10724 feat(art advisor): enable Milestone 1
  src/app/AppRegistry.tsx
  src/app/Scenes/Home/HomeContainer.tests.tsx
  src/app/Scenes/Home/HomeContainer.tsx
  src/app/Scenes/HomeView/Components/AlphaVersionIndicator.tsx
  src/app/Scenes/HomeView/Components/HomeHeader.tsx
  src/app/Scenes/HomeView/HomeView.tsx
  src/app/store/config/features.ts
Labels: Jira Synced

#10705 feat: add ArtistsRailHomeViewSection tracking
  src/app/Scenes/Home/homeAnalytics.ts
  src/app/Scenes/HomeView/Sections/ArtistsRailHomeViewSection.tests.tsx
  src/app/Scenes/HomeView/Sections/ArtistsRailHomeViewSection.tsx
Labels: Jira Synced, Squash On Green, Art Advisor

#10707 feat: add ActivityRailHomeViewSection tracking
  src/app/Scenes/Home/homeAnalytics.ts
  src/app/Scenes/HomeView/Sections/ActivityRailHomeViewSection.tests.tsx
  src/app/Scenes/HomeView/Sections/ActivityRailHomeViewSection.tsx
Labels: Jira Synced, Art Advisor

#10709 feat: add AuctionResultsRailHomeViewSection tracking
  src/app/Components/Lists/AuctionResultListItem.tsx
  src/app/Scenes/HomeView/Sections/AuctionResultsRailHomeViewSection.tests.tsx
  src/app/Scenes/HomeView/Sections/AuctionResultsRailHomeViewSection.tsx
Labels: Jira Synced, Squash On Green, Art Advisor

#10728 feat: add ViewingRoomsRailHomeViewSection tracking
  src/app/Scenes/HomeView/Sections/ViewingRoomsRailHomeViewSection.tests.tsx
  src/app/Scenes/HomeView/Sections/ViewingRoomsRailHomeViewSection.tsx
  src/app/Scenes/ViewingRoom/Components/ViewingRoomsHomeRail.tsx
  src/app/Scenes/ViewingRoom/Components/ViewingRoomsListFeatured.tsx
Labels: Jira Synced

#10713 feat: add new home view fairs tracking
  src/app/Scenes/Home/homeAnalytics.ts
  src/app/Scenes/HomeView/Sections/FairRailItem.tsx
  src/app/Scenes/HomeView/Sections/FairsRailHomeViewSection.tests.tsx
  src/app/Scenes/HomeView/Sections/FairsRailHomeViewSection.tsx
Labels: Jira Synced, Art Advisor

#10735 build(deps): bumps @artsy/palette-mobile from 13.2.27 to 13.2.28
  HACKS.md
  ios/Podfile.lock
  package.json
  patches/react-native-reanimated+3.3.0.patch
  src/app/Components/BottomSheet/AutoHeightBottomSheet.tsx
  src/app/Scenes/SavedSearchAlertsList/Components/AlertBottomSheet.tsx
  yarn.lock
Labels: Jira Synced, Squash On Green, post-react-conf-updates

#10730 feat: add GalleriesHomeViewSection tracking
  src/app/Scenes/HomeView/Sections/GalleriesHomeViewSection.tests.tsx
  src/app/Scenes/HomeView/Sections/GalleriesHomeViewSection.tsx
Labels: Jira Synced

#10712 feat: add ShowsRailHomeViewSection tracking
  src/app/Scenes/Home/Components/ShowsRail.tsx
  src/app/Scenes/HomeView/Sections/ShowsRailHomeViewSection.tests.tsx
  src/app/Scenes/HomeView/Sections/ShowsRailHomeViewSection.tsx
Labels: Jira Synced, Squash On Green, Art Advisor

#10720 chore: enable sentry performance metrics
  index-common.js
  src/app/App.tsx
  src/app/Components/AutosuggestResults/AutosuggestResults.tests.tsx
  src/app/Scenes/Home/HomeContainer.tsx
  src/app/Scenes/MyProfile/__tests__/MyProfileEditForm.tests.tsx
  src/app/store/config/features.ts
  src/app/system/devTools/DevMenu/Components/DevTools.tsx
  src/app/system/errorReporting/hooks.ts
  src/app/system/errorReporting/sentrySetup.ts
  src/app/system/errorReporting/setupSentry.ts
  src/app/system/navigation/ModalStack.tsx
  src/app/system/relay/middlewares/errorMiddleware.tests.ts
  src/app/utils/AboveTheFoldQueryRenderer.tsx
  src/app/utils/volleyClient.tests.ts
  src/setupJest.tsx
Labels: Jira Synced

#10741 chore: update metaphysics graphql schema
  data/schema.graphql
  src/app/Scenes/Collection/Components/FeaturedArtists.tests.tsx
  src/app/Scenes/Collection/Components/FullFeaturedArtistList.tsx
  src/app/Scenes/Collection/Components/__fixtures__/CollectionFixture.ts
Labels: Squash On Green

#10546 feat: add home view section screen
  src/app/AppRegistry.tsx
  src/app/Scenes/HomeView/Sections/ArtworksRailHomeViewSection.tsx
  src/app/Scenes/HomeView/helpers/getSectionHref.tests.ts
  src/app/Scenes/HomeView/helpers/getSectionHref.ts
  src/app/Scenes/HomeViewSectionScreen/HomeViewSectionScreen.tsx
  src/app/Scenes/HomeViewSectionScreen/HomeViewSectionScreenArtworks.tsx
  src/app/Scenes/HomeViewSectionScreen/HomeViewSectionScreenArtworksPlaceholder.tsx
  src/app/Scenes/HomeViewSectionScreen/HomeViewSectionScreenContent.tsx
  src/app/Scenes/HomeViewSectionScreen/HomeViewSectionScreenPlaceholder.tsx
  src/app/routes.ts
Labels: Jira Synced, Art Advisor

#10687 chore: rename homeview section names
  data/schema.graphql
  src/app/Scenes/Home/HomeContainer.tests.tsx
  src/app/Scenes/Home/HomeContainer.tsx
  src/app/Scenes/HomeView/HomeView.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionActivity.tests.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionActivity.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArticles.tests.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArticles.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArticlesCards.tests.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArticlesCards.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArtists.tests.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArtists.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArtworks.tests.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArtworks.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionAuctionResults.tests.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionAuctionResults.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionFairs.tests.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionFairs.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionFairsFairItem.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionFeaturedCollection.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionGalleries.tests.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionGalleries.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionGeneric.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionHeroUnits.tests.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionHeroUnits.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionMarketingCollections.tests.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionMarketingCollections.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionMarketingCollectionsItem.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionSales.tests.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionSales.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionSalesItem.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionShows.tests.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionShows.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionViewingRooms.tests.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionViewingRooms.tsx
  src/app/Scenes/HomeView/Sections/Section.tsx
  src/app/Scenes/HomeViewSectionScreen/HomeViewSectionScreen.tsx
  src/app/Scenes/HomeViewSectionScreen/HomeViewSectionScreenArtworks.tsx
Labels: Jira Synced, Art Advisor

#10456 chore(ONYX-1108): retrieve swa specialists data from MP
  src/app/Scenes/SellWithArtsy/Components/MeetTheSpecialists.tsx
  src/app/Scenes/SellWithArtsy/Components/Testimonials.tsx
  src/app/Scenes/SellWithArtsy/SellWithArtsyHome.tests.tsx
  src/app/Scenes/SellWithArtsy/SellWithArtsyHome.tsx
  src/app/Scenes/SellWithArtsy/utils/useSWALandingPageData.tsx
Labels: Jira Synced, Squash On Green

#10742 fix: wait for nav to be ready to follow push notifications
  src/app/Components/Toast/ToastComponent.tsx
  src/app/NativeModules/ARScreenPresenterModule.tsx
  src/app/Scenes/Onboarding/OnboardingCreateAccount/OnboardingCreateAccount.tsx
  src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkProgressBar.tsx
  src/app/Scenes/SellWithArtsy/ArtworkForm/SubmitArtworkForm.tsx
  src/app/store/GlobalStore.tsx
  src/app/system/navigation/ModalStack.tsx
  src/app/utils/PushNotification.tests.ts
  src/app/utils/PushNotification.ts
  src/app/utils/hooks/useSelectedTab.ts
  src/app/utils/useInitialNotification.ts
Labels: Squash On Green

#10737 chore(analytics): add useHomeViewTracking hook
  package.json
  src/app/Components/Lists/AuctionResultListItem.tsx
  src/app/Scenes/Home/Components/ArticlesRail.tsx
  src/app/Scenes/Home/Components/ShowsRail.tsx
  src/app/Scenes/HomeView/Components/ActivityIndicator.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionActivity.tests.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionActivity.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArticles.tests.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArticles.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArtists.tests.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArtists.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArtworks.tests.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArtworks.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionAuctionResults.tests.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionAuctionResults.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionFairs.tests.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionFairs.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionGalleries.tests.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionGalleries.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionHeroUnits.tests.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionHeroUnits.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionMarketingCollections.tests.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionMarketingCollections.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionMarketingCollectionsItem.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionSales.tests.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionSales.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionShows.tests.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionShows.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionViewingRooms.tests.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionViewingRooms.tsx
  src/app/Scenes/HomeView/useHomeViewTracking.ts
  src/app/Scenes/ViewingRoom/Components/ViewingRoomsHomeRail.tsx
  yarn.lock
Labels: Squash On Green

#10749 feat(EMI-2027): Add Curators' Pick and Increased Interest signals
  src/app/Components/ArtworkGrids/ArtworkGridItem.tests.tsx
  src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
  src/app/Components/ArtworkGrids/ArtworkSocialSignal.tests.tsx
  src/app/Components/ArtworkGrids/ArtworkSocialSignal.tsx
  src/app/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx
  src/app/Components/ArtworkRail/ArtworkRail.tsx
  src/app/Components/ArtworkRail/ArtworkRailCard.tests.tsx
  src/app/Components/ArtworkRail/ArtworkRailCard.tsx
  src/app/Scenes/Artwork/Artwork.tsx
  src/app/Scenes/Artwork/Components/ArtworkCuratorsPickIncreasedInterestCollectorSignal.tests.tsx
  src/app/Scenes/Artwork/Components/ArtworkCuratorsPickIncreasedInterestCollectorSignal.tsx
  src/app/Scenes/Collection/Screens/CollectionArtworks.tsx
  src/app/Scenes/Home/Components/MarketingCollectionRail.tsx
  src/app/Scenes/Onboarding/OnboardingQuiz/OnboardingMarketingCollection.tsx
  src/app/store/config/features.ts
Labels: Jira Synced

#10756 feat(DIA-556): remove collector settings ff dead code
  src/app/Components/ProgressiveOnboarding/useDismissSavedHighlight.ts
  src/app/Scenes/MyProfile/MyProfileHeader.tests.tsx
  src/app/Scenes/MyProfile/MyProfileHeader.tsx
  src/app/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx
  src/app/Scenes/MyProfile/MyProfileSettings.tests.tsx
  src/app/Scenes/MyProfile/MyProfileSettings.tsx
  src/app/store/config/features.ts
Labels: Jira Synced

#10764 fix(EMI-2079): Hide signals in the Trending Now collection
  src/app/Scenes/Collection/Screens/CollectionArtworks.tests.tsx
  src/app/Scenes/Collection/Screens/CollectionArtworks.tsx
Labels: Jira Synced, Squash On Green

#10765 fix: Flip Increased Interest and Curators' Pick prioritization
  src/app/Components/ArtworkGrids/ArtworkGridItem.tests.tsx
  src/app/Components/ArtworkGrids/ArtworkSocialSignal.tests.tsx
  src/app/Components/ArtworkGrids/ArtworkSocialSignal.tsx
  src/app/Components/ArtworkRail/ArtworkRailCard.tests.tsx
  src/app/Scenes/Artwork/Components/ArtworkCuratorsPickIncreasedInterestCollectorSignal.tests.tsx
  src/app/Scenes/Artwork/Components/ArtworkCuratorsPickIncreasedInterestCollectorSignal.tsx
Labels: Squash On Green

#10757 feat(onyx-1283): pull-to-refresh for new home view screen
  src/app/Scenes/HomeView/HomeView.tsx
Labels: Jira Synced

#10753 fix(ONYX-1287): broken spacing between home view sections
  src/app/Scenes/HomeView/HomeView.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionActivity.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArticles.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArticlesCards.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArtists.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArtworks.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionAuctionResults.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionFairs.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionFeaturedCollection.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionGalleries.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionGeneric.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionHeroUnits.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionMarketingCollections.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionSales.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionShows.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionViewingRooms.tsx
Labels: Jira Synced, Squash On Green, Art Advisor

#10770 chore: Mark AREnableCuratorsPicksAndInterestSignals as ready for release
  src/app/store/config/features.ts
Labels: Squash On Green

#10738 feat: adding display of showing collector signal to artwork page
  src/app/Scenes/Artwork/Artwork.tests.tsx
  src/app/Scenes/Artwork/Artwork.tsx
  src/app/Scenes/Artwork/Components/ArtworkCommercialButtons.tests.tsx
  src/app/Scenes/Artwork/Components/ArtworkShowingNowCollectorSignal.tests.tsx
  src/app/Scenes/Artwork/Components/ArtworkShowingNowCollectorSignal.tsx
Labels: Squash On Green

#10767 build(deps): remove sentry cli from packagejson
  fastlane/Fastfile
  fastlane/sentry_fastlane.rb
  package.json
  yarn.lock
Labels: Jira Synced

#10772 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10774 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10775 chore: add dev tool to request push permissions #trivial
  src/app/system/devTools/DevMenu/Components/DevTools.tsx
  src/app/utils/requestPushNotificationsPermission.ts
Labels: Squash On Green

#10777 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10776 chore: turn off sentry user interaction tracking for now #trivial
  src/app/system/errorReporting/setupSentry.ts
Labels: Squash On Green

#10768 feat(onyx-1276): restore progressive onboarding tooltips for new home view
  src/app/Scenes/HomeView/HomeView.tsx
Labels: Jira Synced, Art Advisor

#10769 feat(onyx-1278): restore prompt for app store review for new home view
  src/app/Scenes/HomeView/HomeView.tsx
Labels: Jira Synced, Art Advisor

#10773 chore: improve home view screen memory consumption
  src/app/Components/ArtworkRail/ArtworkRail.tsx
  src/app/Scenes/Home/Components/ArticlesRail.tsx
  src/app/Scenes/Home/Components/ShowsRail.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionActivity.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArtists.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionAuctionResults.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionFairs.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionHeroUnits.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionMarketingCollections.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionSales.tsx
  src/app/Scenes/HomeView/helpers/constants.ts
Labels: Art Advisor, post-react-conf-updates

#10782 chore(analytics): use schema-provided contextModule for home view sections
  src/app/Scenes/HomeView/Sections/HomeViewSectionActivity.tests.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionActivity.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArticles.tests.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArticles.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArtists.tests.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArtists.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArtworks.tests.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArtworks.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionAuctionResults.tests.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionAuctionResults.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionFairs.tests.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionFairs.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionFeaturedCollection.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionGalleries.tests.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionGalleries.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionHeroUnits.tests.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionHeroUnits.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionMarketingCollections.tests.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionMarketingCollections.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionSales.tests.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionSales.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionShows.tests.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionShows.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionViewingRooms.tests.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionViewingRooms.tsx
  src/app/Scenes/HomeView/useHomeViewTracking.ts
Labels: Art Advisor

#10781 feat(onyx-1279): prefetch tabs from new home view screen
  src/app/Scenes/HomeView/HomeView.tsx
Labels: Jira Synced, Art Advisor

#10763 feat: Implement Loading Skeletons for all home view sections
  src/app/App.tsx
  src/app/Components/ArticleCard.tsx
  src/app/Components/Cards/MediumCard.tsx
  src/app/Components/FiveUpImageLayout.tsx
  src/app/Components/Home/ArtistRails/ArtistCard.tsx
  src/app/Components/Lists/AuctionResultListItem.tsx
  src/app/Components/ThreeUpImageLayout.tsx
  src/app/Scenes/Home/Components/ActivityRailItem.tsx
  src/app/Scenes/Home/Components/HeroUnitsRail.tsx
  src/app/Scenes/Home/Components/ShowsRail.tsx
  src/app/Scenes/HomeView/HomeView.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionActivity.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArticles.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArticlesCards.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArtists.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArtworks.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionAuctionResults.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionFairs.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionFeaturedCollection.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionGalleries.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionHeroUnits.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionMarketingCollections.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionMarketingCollectionsItem.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionSales.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionShows.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionViewingRooms.tsx
  src/app/Scenes/HomeView/Sections/Section.tsx
Labels: Jira Synced, Squash On Green, Art Advisor

#10787 feat(onyx-1277): enable context menu for new works for you rail on new home screen
  src/app/Scenes/HomeView/Sections/HomeViewSectionArtworks.tsx
Labels: Jira Synced, Art Advisor

#10792 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10788 chore(analytics): wire up section view all analytics events
  src/app/Components/BrowseMoreRailCard.tsx
  src/app/Scenes/Home/Components/ActivityRail.tsx
  src/app/Scenes/HomeView/Components/ActivityIndicator.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionActivity.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArticles.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArticlesCards.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArtists.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArtworks.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionAuctionResults.tests.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionAuctionResults.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionFairs.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionFeaturedCollection.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionGalleries.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionHeroUnits.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionMarketingCollections.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionSales.tests.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionSales.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionShows.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionViewingRooms.tsx
  src/app/Scenes/HomeView/helpers/getSectionHref.tests.ts
  src/app/Scenes/HomeView/helpers/getSectionHref.ts
  src/app/Scenes/HomeView/useHomeViewTracking.ts
Labels: Art Advisor

#10783 feat(onyx-1280): request push notifications permission from new home view screen
  src/app/Scenes/HomeView/HomeView.tests.tsx
  src/app/Scenes/HomeView/HomeView.tsx
Labels: Jira Synced

#10766 fix(EMI-2066): use primaryLabel for tracking and remove auction signal tracking
  src/app/Components/ArtworkGrids/ArtworkGridItem.tests.tsx
  src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
  src/app/Components/ArtworkRail/ArtworkRailCard.tsx
  src/app/Components/ArtworkRail/LargeArtworkRail.tsx
  src/app/Components/ArtworkRail/SmallArtworkRail.tsx
  src/app/Scenes/Artwork/Components/ArtworkCommercialButtons.tests.tsx
  src/app/Scenes/Artwork/Components/ArtworksInSeriesRail.tests.tsx
  src/app/Scenes/Artwork/Components/CommercialButtons/ContactGalleryButton.tests.tsx
  src/app/Scenes/Artwork/Components/CommercialButtons/ContactGalleryButton.tsx
  src/app/Scenes/Fair/FairExhibitorRail.tests.tsx
  src/app/Scenes/Fair/FairFollowedArtistsRail.tests.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArtworks.tests.tsx
  src/app/Scenes/HomeViewSectionScreen/HomeViewSectionScreenArtworks.tests.tsx
  src/app/Scenes/SavedSearchAlert/screens/ConfirmationScreen.tests.tsx
  src/app/utils/getArtworkSignalTrackingFields.ts
Labels: Jira Synced

#10794 chore: upgrade Sentry to v5.24.1
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: Squash On Green

#10796 fix(APPL-1107): Dismiss Create New List/Offer Settings modal on Android back
  src/app/Components/BottomSheet/AutomountedBottomSheetModal.tsx
Labels: Jira Synced

#10801 chore: Simplify Previously Sold on Artsy artworks rail
  src/app/Components/ArtworkRail/ArtworkRail.tsx
  src/app/Components/ArtworkRail/ArtworkRailCard.tsx
  src/app/Components/ContextMenu/ContextMenuArtwork.tsx
  src/app/Components/ContextMenu/ContextMenuArtworkPreviewCard.tsx
  src/app/Scenes/SellWithArtsy/Components/SellWithArtsyRecentlySold.tsx
Labels: Jira Synced

#10799 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10803 fix(ActivityScreen): activity screen suspending
  src/app/Scenes/Activity/ActivityItem.tsx
  src/app/Scenes/Activity/components/CollectorUpdateNotification.tsx
  src/app/Scenes/Activity/components/__tests__/CollectorUpdateNotification.tests.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionArtistsPrompt/MyCollectionArtistsPrompt.tsx
Labels: Jira Synced

#10800 feat(onyx-1282): error boundary around new home view screen
  src/app/Scenes/HomeView/HomeView.tsx
Labels: Jira Synced, Art Advisor

#10802 chore: Clean up artwork rail and extact sub components
  src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
  src/app/Components/ArtworkRail/ArtworkRail.tsx
  src/app/Components/ArtworkRail/ArtworkRailCard.tests.tsx
  src/app/Components/ArtworkRail/ArtworkRailCard.tsx
  src/app/Components/ArtworkRail/ArtworkRailCardImage.tsx
  src/app/Components/ArtworkRail/LegacyArtworkRailCardImage.tsx
  src/app/Components/ContextMenu/ContextMenuArtwork.tsx
  src/app/Components/ContextMenu/ContextMenuArtworkPreviewCard.tsx
  src/app/Components/ContextMenu/ContextMenuArtworkPreviewCardImage.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArtworks.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionFeaturedCollection.tsx
  src/app/Scenes/SellWithArtsy/Components/SellWithArtsyRecentlySold.tsx
  src/app/store/config/features.ts
Labels: Jira Synced, Squash On Green

#10807 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10791 chore(EMI-2082): refactor collector signals on Artwork details screen
  src/app/Scenes/Artwork/Artwork.tsx
  src/app/Scenes/Artwork/Components/ArtworkCuratorsPickIncreasedInterestCollectorSignal.tests.tsx
  src/app/Scenes/Artwork/Components/ArtworkCuratorsPickIncreasedInterestCollectorSignal.tsx
  src/app/Scenes/Artwork/Components/ArtworkDetailsCollectorSignal.tests.tsx
  src/app/Scenes/Artwork/Components/ArtworkDetailsCollectorSignal.tsx
  src/app/Scenes/Artwork/Components/ArtworkDimensionsClassificationAndAuthenticity/ArtworkAuthenticityCertificate.tsx
  src/app/Scenes/Artwork/Components/ArtworkShowingNowCollectorSignal.tests.tsx
  src/app/Scenes/Artwork/Components/ArtworkShowingNowCollectorSignal.tsx
Labels: Jira Synced

#10798 fix: android app crash
  .circleci/config.yml
  HACKS.md
  ios/Podfile.lock
  package.json
  patches/react-native-reanimated+3.3.0.patch
  yarn.lock
Labels: Jira Synced, Squash On Green

#10810 chore: bump palette mobile #trivial
  package.json
  yarn.lock
Labels: Squash On Green

#10739 build(deps): bump react-native from 0.72.17 to 0.73.9 #WIP #DONOTMERGE
  .circleci/config.yml
  .secrets.baseline
  .tool-versions
  Gemfile
  Gemfile.lock
  HACKS.md
  alias.js
  android/app/build.gradle
  android/app/src/debug/AndroidManifest.xml
  android/app/src/debug/java/net/artsy/app/ReactNativeFlipper.java
  android/app/src/main/java/net/artsy/app/MainActivity.java
  android/app/src/main/java/net/artsy/app/MainActivity.kt
  android/app/src/main/java/net/artsy/app/MainApplication.java
  android/app/src/main/java/net/artsy/app/MainApplication.kt
  android/app/src/release/java/net/artsy/app/ReactNativeFlipper.java
  android/build.gradle
  android/gradle/wrapper/gradle-wrapper.jar
  android/gradle/wrapper/gradle-wrapper.properties
  android/gradlew
  babel.config.js
  ios/Artsy.xcodeproj/project.pbxproj
  ios/Artsy/App/ARAppDelegate.mm
  ios/Artsy/App_Resources/Info.plist
  ios/Podfile
  ios/Podfile.lock
  metro.config.js
  package.json
  patches/@jest+fake-timers+29.7.0.patch
  patches/@react-native-community+cli-platform-ios+12.3.7.patch
  patches/react-native+0.73.9.patch
  patches/react-native-reanimated+3.3.0.patch
  scripts/city-guide/generate-cities-cache.js
  src/app/Components/PopoverMessage/PopoverMessageProvider.tsx
  src/app/Components/WithCurrentTime.tsx
  src/app/Scenes/Artwork/Components/CommercialButtons/BuyNowButton.tsx
  src/app/Scenes/Artwork/Components/CommercialButtons/InquirySuccessNotification.tsx
  src/app/Scenes/Artwork/Components/RequestConditionReport.tests.tsx
  src/app/Scenes/MyCollection/Screens/Insights/SelectArtist.tests.tsx
  src/app/Scenes/Search/components/EntitySearchResults.tests.tsx
  src/app/Scenes/Search/components/EntitySearchResults.tsx
  src/app/utils/PushNotification.ts
  src/setupJest.tsx
  tsconfig.json
  yarn.lock
Labels: Jira Synced, Squash On Green, post-react-conf-updates

#10771 fix(EMI-2054): make Bidding live now bold everywhere
  src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
Labels: Jira Synced

#10821 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10819 fix(EMI-2053): Hide register by signal on auction screen
  src/app/Components/ArtworkGrids/ArtworkAuctionTimer.tests.tsx
  src/app/Components/ArtworkGrids/ArtworkAuctionTimer.tsx
  src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
  src/app/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx
  src/app/Scenes/Sale/Components/SaleLotsList.tsx
Labels: Jira Synced

#10468 feat(POC): add error boundary to withSuspense
  package.json
  src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterPriceRange.tests.tsx
  src/app/Scenes/SavedSearchAlert/screens/AlertPriceRangeScreen.tsx
  src/app/utils/hooks/withSuspense.tsx
  yarn.lock
Labels: Jira Synced, Squash On Green

#10823 feat(Revert-POC): add error boundary to withSuspense
  package.json
  src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterPriceRange.tests.tsx
  src/app/Scenes/SavedSearchAlert/screens/AlertPriceRangeScreen.tsx
  src/app/utils/hooks/withSuspense.tsx
  yarn.lock
Labels: Squash On Green

#10816 feat: add rail viewed events to home view section
  src/app/Scenes/HomeView/Components/HomeViewSectionSentinel.tsx
  src/app/Scenes/HomeView/HomeView.tsx
  src/app/Scenes/HomeView/HomeViewContext.ts
  src/app/Scenes/HomeView/Sections/HomeViewSectionActivity.tests.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionActivity.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArticles.tests.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArticles.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArticlesCards.tests.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArticlesCards.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArtists.tests.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArtists.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArtworks.tests.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArtworks.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionAuctionResults.tests.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionAuctionResults.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionFairs.tests.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionFairs.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionFeaturedCollection.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionGalleries.tests.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionGalleries.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionGeneric.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionHeroUnits.tests.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionHeroUnits.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionMarketingCollections.tests.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionMarketingCollections.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionSales.tests.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionSales.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionShows.tests.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionShows.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionViewingRooms.tests.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionViewingRooms.tsx
  src/app/Scenes/HomeView/Sections/Section.tsx
  src/app/Scenes/HomeView/useHomeViewTracking.ts
  src/app/Scenes/HomeViewSectionScreen/HomeViewSectionScreenArtworks.tests.tsx
  src/app/utils/Sentinel.tsx
Labels: Jira Synced

#10822 refactor(onyx-1304): use viewingRoomsConnection instead of deprecated viewingRooms query
  src/app/Scenes/Home/Home.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionViewingRooms.tests.tsx
  src/app/Scenes/ViewingRoom/Components/ViewingRoomsHomeRail.tsx
  src/app/Scenes/ViewingRoom/Components/ViewingRoomsListFeatured.tests.tsx
  src/app/Scenes/ViewingRoom/Components/ViewingRoomsListFeatured.tsx
  src/app/Scenes/ViewingRoom/ViewingRoomsList.tests.tsx
  src/app/Scenes/ViewingRoom/ViewingRoomsList.tsx
Labels: Jira Synced

#10815 chore: Simplify artwork rail code II
  src/app/Components/ArtworkRail/ArtworkRail.tsx
  src/app/Components/ArtworkRail/ArtworkRailCard.tsx
  src/app/Components/Disappearable.tsx
  src/app/Scenes/Artwork/Components/ArtworksInSeriesRail.tsx
  src/app/Scenes/HomeView/helpers/constants.ts
Labels: Jira Synced

#10830 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10829 chore: separate artwork card meta
  src/app/Components/ArtworkRail/ArtworkRailCard.tsx
  src/app/Components/ArtworkRail/ArtworkRailCardMeta.tsx
  src/app/Components/ArtworkRail/LegacyArtworkRailCardImage.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArtworks.tsx
Labels: Jira Synced

#10831 fix(EMI-2083): Add bottom padding to Limited-Time Offer badge
  src/app/Scenes/Activity/components/PartnerOffeBadge.tsx
Labels: Jira Synced, Squash On Green

#10833 fix(EMI-1897): Update Contact Gallery requirement to send messages
  src/app/Scenes/Artwork/Components/CommercialButtons/InquiryModal.tests.tsx
  src/app/Scenes/Artwork/Components/CommercialButtons/InquiryModal.tsx
Labels: Jira Synced, Squash On Green

#10834 fix: layout shifts for artwork rails
  src/app/Components/ArtworkRail/ArtworkRail.tsx
  src/app/Components/ArtworkRail/ArtworkRailCard.tsx
  src/app/Components/ArtworkRail/ArtworkRailCardMeta.tsx
  src/app/Components/PrefetchFlashList.tsx
  src/app/Scenes/SellWithArtsy/Components/SellWithArtsyRecentlySold.tsx
Labels: Jira Synced, Squash On Green

#10835 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10832 feat(DIA-806): Recaptcha mechanism
  src/app/Components/Recaptcha/Recaptcha.tsx
  src/app/Components/Recaptcha/RecaptchaWebView.tsx
Labels: Jira Synced

#10841 fix: tests after AREnableNewTermsAndConditions release
  src/app/Components/Bidding/Screens/ConfirmBid.tests.tsx
  src/app/Components/Bidding/Screens/Registration.tests.tsx
  src/app/Scenes/About/About.tests.tsx
  src/app/Scenes/Onboarding/OnboardingCreateAccount/TermsOfServiceCheckbox.tests.tsx
  src/app/Scenes/Onboarding/OnboardingSocialPick.tests.tsx
Labels: Squash On Green

#10837 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10845 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10850 feat: use Flatlist for new homeview
  src/app/Scenes/HomeView/HomeView.tsx
Labels: Jira Synced, Squash On Green

#10851 feat: render new Homeview for artsy people
  src/app/AppRegistry.tsx
  src/app/Scenes/Home/Home.tsx
  src/app/Scenes/Home/HomeContainer.tests.tsx
  src/app/Scenes/Home/HomeContainer.tsx
Labels: Jira Synced, Squash On Green

#10839 feat(EMI-2112): failed payment order history
  src/app/Scenes/OrderHistory/OrderDetails/Components/OrderDetailsHeader.tsx
  src/app/Scenes/OrderHistory/OrderDetails/Components/TrackOrderSection.tsx
  src/app/Scenes/OrderHistory/OrderHistoryRow.tests.tsx
  src/app/Scenes/OrderHistory/OrderHistoryRow.tsx
  src/app/utils/getOrderStatus.tests.ts
  src/app/utils/getOrderStatus.ts
Labels: Jira Synced

#10854 fix: fix some unable to loads
  src/app/AppRegistry.tsx
  src/app/Components/LoadFailureView.tsx
  src/app/Components/RetryErrorBoundary.tsx
  src/app/Providers.tsx
  src/app/Scenes/Artist/Artist.tsx
  src/app/Scenes/Artwork/Artwork.tsx
  src/app/Scenes/Home/Home.tsx
  src/app/Scenes/MyCollection/MyCollection.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtworkAutosuggestResults.tsx
  src/app/Scenes/Sale/Sale.tsx
  src/app/Scenes/SellWithArtsy/ArtworkForm/SubmitArtworkFormEdit.tsx
  src/app/utils/AboveTheFoldQueryRenderer.tsx
  src/app/utils/renderWithPlaceholder.tsx
  src/app/utils/useDeepLinks.ts
Labels: Jira Synced, Squash On Green

#10856 fix: artworks screen loading skeleton
  src/app/Scenes/HomeViewSectionScreen/HomeViewSectionScreenArtworks.tsx
  src/app/Scenes/HomeViewSectionScreen/HomeViewSectionScreenPlaceholder.tsx
Labels: Squash On Green

#10859 fix: add save icons back
  src/app/Scenes/Home/Components/ArtworkModuleRail.tsx
  src/app/Scenes/Home/Components/ArtworkRecommendationsRail.tsx
  src/app/Scenes/Home/Components/MarketingCollectionRail.tsx
Labels: Jira Synced, Squash On Green

#10865 fix(PBRW-59): Crash on iOS when navigating to saves from Activity Panel partner offer
  src/app/Scenes/Activity/components/PartnerOfferCreatedNotification.tsx
  src/app/Scenes/Activity/components/__tests__/PartnerOfferCreatedNotification.tests.tsx
  src/app/routes.ts
  src/app/system/navigation/routes.tests.ts
Labels: Jira Synced

#10857 feat(ONYX-1285): change of the image size dimensions of an artwork rail card
  src/app/Components/ArtworkRail/ArtworkRail.tsx
  src/app/Components/ArtworkRail/ArtworkRailCard.tests.tsx
  src/app/Components/ArtworkRail/ArtworkRailCard.tsx
  src/app/Components/ArtworkRail/ArtworkRailCardImage.tsx
  src/app/Components/ArtworkRail/LegacyArtworkRailCardImage.tsx
  src/app/Components/ContextMenu/ContextMenuArtworkPreviewCardImage.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArtworks.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionFeaturedCollection.tsx
Labels: Jira Synced
