Repository artsy/eigen, pull requests merged in 2024-05, with the labels that each got.

#10179 build(tools): add latest betas script #trivial
  fastlane/Fastfile
  scripts/deploys/latest-betas
Labels: Jira Synced

#10178 chore(tracking): Add Private Artwork Tracking (mobile)
  src/app/Components/Expandable.tsx
  src/app/Scenes/Artwork/Artwork.tests.tsx
  src/app/Scenes/Artwork/Components/AboutArtist.tests.tsx
  src/app/Scenes/Artwork/Components/AboutArtist.tsx
  src/app/Scenes/Artwork/Components/PrivateArtwork/PrivateArtworkExclusiveAccess.tsx
  src/app/Scenes/Artwork/Components/PrivateArtwork/PrivateArtworkMetadata.tsx
  src/app/Scenes/Artwork/Components/PrivateArtwork/__tests__/PrivateArtworkMetadata.tests.tsx
Labels: Jira Synced

#10183 fix(conversations): Images no longer rendering on conversations
  src/app/Scenes/Inbox/Components/Conversations/Preview/ArtworkPreview.tsx
Labels: Jira Synced

#10165 feat: Reorganize sell screen
  src/app/Scenes/SellWithArtsy/Components/Footer.tsx
  src/app/Scenes/SellWithArtsy/Components/Header.tsx
  src/app/Scenes/SellWithArtsy/Components/HowItWorks.tsx
  src/app/Scenes/SellWithArtsy/Components/MeetTheSpecialists.tsx
  src/app/Scenes/SellWithArtsy/Components/SellWithArtsyRecentlySold.tsx
  src/app/Scenes/SellWithArtsy/Components/StickySWAHeader.tsx
  src/app/Scenes/SellWithArtsy/SellWithArtsyHome.tsx
  src/app/Scenes/SellWithArtsy/index.tests.tsx
Labels: Jira Synced

#10155 feat: remove contact information step from SWA flow
  src/app/Components/ArtistAutosuggest/ArtistAutosuggest.tsx
  src/app/Components/ArtistAutosuggest/ArtistAutosuggestRow.tsx
  src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkDetails/ArtworkDetails.tests.tsx
  src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkDetails/ArtworkDetails.tsx
  src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkDetails/ArtworkDetailsForm.tsx
  src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkDetails/utils/createOrUpdateSubmission.ts
  src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkDetails/utils/fetchUserContactInformation.ts
  src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkDetails/validation.ts
  src/app/Scenes/SellWithArtsy/SubmitArtwork/ContactInformation/ContactInformation.tests.tsx
  src/app/Scenes/SellWithArtsy/SubmitArtwork/ContactInformation/ContactInformation.tsx
  src/app/Scenes/SellWithArtsy/SubmitArtwork/ContactInformation/validation.ts
  src/app/Scenes/SellWithArtsy/SubmitArtwork/SubmitArtwork.tests.tsx
  src/app/Scenes/SellWithArtsy/SubmitArtwork/SubmitArtwork.tsx
  src/app/Scenes/SellWithArtsy/SubmitArtwork/UploadPhotos/UploadPhotos.tests.tsx
  src/app/Scenes/SellWithArtsy/SubmitArtwork/UploadPhotos/validation.ts
Labels: Jira Synced, Squash On Green

#10182 fix: add error messages to view in room
  ios/Artsy/View_Controllers/ARVIR/VCs/ARAugmentedWallBasedVIRViewController.swift
Labels: Jira Synced

#10184 chore(ONYX-923): remove keyboard prop from edition text inputs
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/Rarity.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/RarityLegacy.tsx
  src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkDetails/ArtworkDetailsForm.tsx
Labels: Jira Synced

#10188 fix(images): enforce image props + fix some bugs
  src/app/Components/Artist/ArtistShows/ArtistShow.tests.tsx
  src/app/Components/Artist/ArtistShows/ArtistShow.tsx
  src/app/Components/Artist/ArtistShows/VariableSizeShowsList.tests.tsx
  src/app/Components/Artist/ArtistShows/VariableSizeShowsList.tsx
  src/app/Components/ArtistAutosuggest/ArtistAutosuggestRow.tsx
  src/app/Components/Cards/LargeCard.tsx
  src/app/Components/Home/HeroUnit.tsx
  src/app/Components/OpaqueImageView2/OpaqueImageView2.tsx
  src/app/Components/RelatedArtists/RelatedArtist.tsx
  src/app/Components/RelatedArtists/RelatedArtists.tsx
  src/app/Scenes/ArtistShows/ArtistShows2.tsx
  src/app/Scenes/Artwork/Components/ImageCarousel/FullScreen/ImageZoomView.tsx
  src/app/Scenes/Home/Components/Trove.tests.tsx
  src/app/Scenes/Home/Components/Trove.tsx
  src/app/Scenes/Inbox/Components/Conversations/Preview/ShowPreview.tsx
  src/app/Scenes/Sale/Components/SaleHeader.tsx
  src/app/Scenes/Sales/Components/SaleListItem.tsx
  src/app/Scenes/Search/components/SearchResultImage.tsx
  src/app/Scenes/Show/Components/ShowContextCard.tsx
Labels: Jira Synced

#10121 feat: Add Interested in Selling tooltip to MyC
  src/app/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkList/MyCollectionArtworkGridItem.tsx
  src/app/store/ProgressiveOnboardingModel.ts
  src/app/store/config/features.ts
Labels: Jira Synced, Squash On Green

#10140 chore: update required fields for submission
  src/app/Components/ArtistAutosuggest/ArtistAutosuggest.tsx
  src/app/Scenes/Artwork/Components/ArtworkConsignments.tests.tsx
  src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkDetails/ArtworkDetails.tsx
  src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkDetails/ArtworkDetailsForm.tsx
  src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkDetails/utils/createOrUpdateSubmission.ts
  src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkDetails/validation.ts
  src/app/store/GlobalStore.tsx
  src/app/store/config/features.ts
  src/app/system/navigation/navigate.tests.tsx
Labels: Jira Synced

#10191 chore(version): version bump
  app.json
Labels: Squash On Green

#10193 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10194 chore(tracking): Render tax info and link to help center for unlisted works + tracking events
  src/app/Scenes/Artwork/Components/ShippingAndTaxes.tests.tsx
  src/app/Scenes/Artwork/Components/ShippingAndTaxes.tsx
Labels: Jira Synced

#10204 Fix: Address cohesion type errors to get on latest version of cohesion
  package.json
  src/app/Scenes/Artwork/Components/CommercialButtons/BuyNowButton.tsx
  src/app/Scenes/Inbox/Components/Conversations/OpenInquiryModalButton.tests.tsx
  src/app/Scenes/Inbox/Components/Conversations/OpenInquiryModalButton.tsx
  src/app/Scenes/SellWithArtsy/utils/TrackingEvent.ts
  yarn.lock
Labels: Squash On Green

#10195 chore(tracking): Render artsy guarantee component for private artworks + add tap event tracking
  src/app/Scenes/Artwork/Artwork.tsx
  src/app/Scenes/Artwork/Components/ArtsyGuarantee.tests.tsx
  src/app/Scenes/Artwork/Components/ArtsyGuarantee.tsx
  src/app/Scenes/Artwork/Components/ShippingAndTaxes.tests.tsx
  src/app/Scenes/Artwork/Components/ShippingAndTaxes.tsx
Labels: Jira Synced, Squash On Green

#10202 chore(tracking): Add generic tap event for read more taps on artwork details
  src/app/Scenes/Artwork/Components/ArtworkDetails.tsx
Labels: Jira Synced, Squash On Green

#10198 feat(onyx-915): use new consignmentSubmission MP fields when rendering submission state section
  src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionArtworkHeader.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionArtworkSubmissionStatus.tests.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionArtworkSubmissionStatus.tsx
Labels: Jira Synced

#10197 feat: highlight invalid fields on SWA flow
  src/app/Components/ArtistAutosuggest/ArtistAutosuggest.tests.tsx
  src/app/Components/ArtistAutosuggest/ArtistAutosuggest.tsx
  src/app/Components/Select/Components/SelectButton.tsx
  src/app/Components/Select/Select.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/CategoryPicker.tsx
  src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkDetails/ArtworkDetails.tests.tsx
  src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkDetails/ArtworkDetails.tsx
  src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkDetails/ArtworkDetailsForm.tsx
  src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkDetails/utils/testUtils.ts
  src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkDetails/validation.ts
  src/app/Scenes/SellWithArtsy/SubmitArtwork/SubmitArtwork.tests.tsx
  src/app/Scenes/SellWithArtsy/SubmitArtwork/SubmitArtwork.tsx
Labels: Jira Synced

#10207 chore: bump detect-secrets baseline version
  .secrets.baseline
Labels: Squash On Green

#10206 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10203 build(tools): generate universal android apk script
  Gemfile.lock
  fastlane/Fastfile
  fastlane/Pluginfile
  scripts/deploys/create-android-apk
Labels: Jira Synced

#10209 chore: Adding exclusive access text to conversations
  src/app/Scenes/Inbox/Components/Conversations/ConversationSnippet.tests.tsx
  src/app/Scenes/Inbox/Components/Conversations/ConversationSnippet.tsx
Labels: Jira Synced

#10213 build(releases): automate next version increment
  .circleci/config.yml
  fastlane/Fastfile
  fastlane/utility_fastlane.rb
  scripts/deploys/create-next-version-if-needed
Labels: Jira Synced

#10218 chore: regenerate .secrets.baseline
  .secrets.baseline
  scripts/detect-secrets/secrets-generate-baseline
Labels: Squash On Green

#10221 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10222 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10225 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10230 fix: Update tests after releasing the feature
  src/app/Scenes/Activity/components/__tests__/NotificationCommercialButtons.tests.tsx
  src/app/Scenes/Artwork/Artwork.tests.tsx
  src/app/Scenes/Artwork/Artwork.tsx
  src/app/Scenes/Artwork/Components/ArtworkPrice.tests.tsx
Labels: Squash On Green

#10231 chore: hide settings behind ff
  src/app/Scenes/MyProfile/MyProfileSettings.tests.tsx
  src/app/Scenes/MyProfile/MyProfileSettings.tsx
Labels: Squash On Green

#10228 fix: display MyC Interested in selling tooltip only for P1 artists
  src/app/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx
Labels: Squash On Green

#10223 feat: automate uploads for maestro copilot builds
  .circleci/config.yml
  scripts/deploys/upload-betas-maestro-copilot
  scripts/maestro/build-android.sh
  scripts/maestro/build-ios.sh
Labels: Jira Synced

#10233 refactor(follow): use follow button from palette
  src/app/Components/Artist/ArtistHeaderNavRight.tsx
  src/app/Components/ArtistListItem.tsx
  src/app/Components/Button/FollowButton.tsx
  src/app/Components/Button/index.ts
  src/app/Components/Gene/Header.tsx
  src/app/Components/Home/ArtistRails/ArtistCard.tsx
  src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsTabs/ArtQuizArtist.tsx
  src/app/Scenes/Partner/Components/PartnerFollowButton.tsx
  yarn.lock
Labels: Jira Synced

#10234 fix: attempt to fix Cannot convert undefined value to object
  src/app/Scenes/Onboarding/OnboardingSocialLink.tsx
Labels: Jira Synced

#10235 feat(EMI-1875): Update Partner Offer Notification for offers for abandoned orders
  src/app/Scenes/Activity/components/PartnerOfferCreatedNotification.tsx
  src/app/Scenes/Activity/components/__tests__/PartnerOfferCreatedNotification.tests.tsx
Labels: Jira Synced

#10236 fix: broken validation on SWA flow
  src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkDetails/ArtworkDetails.tsx
  src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkDetails/ArtworkDetailsForm.tsx
  src/app/Scenes/SellWithArtsy/SubmitArtwork/SubmitArtwork.tsx
  src/app/Scenes/SellWithArtsy/utils/submissionModelState.tsx
  src/app/store/__tests__/migration.tests.ts
  src/app/store/migration.ts
Labels: Jira Synced

#9993 chore: CircleCI performance improvements on PRs
  .circleci/config.yml
  scripts/ci/ci-test-js-pr
Labels: Squash On Green, build-me

#10244 ci(releases): automate android rollout
  .circleci/config.yml
  HACKS.md
  fastlane/Fastfile
  fastlane/actions/google_play_track_rollout_percentages.rb
  fastlane/supply_reader_extension.rb
  scripts/deploys/update-android-rollout-if-needed
Labels: Jira Synced, Squash On Green

#10251 chore: consolidate sell routes in app
  src/app/AppRegistry.tsx
  src/app/Scenes/BottomTabs/BottomTabsNavigator.tsx
  src/app/Scenes/Home/Home.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionWhySell.tests.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionWhySell.tsx
  src/app/Scenes/SellWithArtsy/SellWithArtsyHome.tsx
  src/app/routes.ts
  src/app/system/navigation/routes.tests.ts
  src/app/utils/router.ts
Labels: Jira Synced

#10252 chore(ONYX-955): update artwork details screen to match new designs
  src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkAddDetails.tests.tsx
  src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkAddDetails.tsx
  src/app/Scenes/SellWithArtsy/ArtworkForm/Utils/validation.ts
  src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkDetails/utils/acceptableCategoriesForSubmission.ts
Labels: Jira Synced

#10250 build(deps): update fastlane plugins and gems versions
  Gemfile.lock
Labels: Squash On Green

#10254 chore: update artwork dimensions screen in new submit artwork flow
  src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkAddDimensions.tsx
Labels: Jira Synced

#10253 chore: update submit artwork start flow
  images/submit_artwork_complete_submission.webp
  images/submit_artwork_complete_submission@2x.webp
  images/submit_artwork_complete_submission@3x.webp
  images/submit_artwork_tell_us_about_your_work.webp
  images/submit_artwork_tell_us_about_your_work@2x.webp
  images/submit_artwork_tell_us_about_your_work@3x.webp
  images/submit_artwork_upload_artwork_image.webp
  images/submit_artwork_upload_artwork_image@2x.webp
  images/submit_artwork_upload_artwork_image@3x.webp
  src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkBottomNavigation.tests.tsx
  src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkBottomNavigation.tsx
  src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkStartFlow.tsx
  src/app/store/config/features.ts
Labels: Jira Synced

#10249 fix: broken start selling button padding on android
  src/app/Scenes/SellWithArtsy/Components/StickySWAHeader.tsx
  src/app/Scenes/SellWithArtsy/SellWithArtsyHome.tsx
Labels: Jira Synced

#10255 build(deps): @sentry/cli from 2.31.0 to 2.31.2
  package.json
  yarn.lock
Labels: Squash On Green

#10258 fix: padding for artist series
  src/app/Components/Artist/ArtistAbout/ArtistAbout.tsx
  src/app/Scenes/ArtistSeries/ArtistSeriesMoreSeries.tsx
Labels: Jira Synced, bugbash

#10257 fix: add ListFooterComponent to RelatedArtistsRail for padding
  src/app/Components/Artist/RelatedArtistsRail.tsx
Labels: Jira Synced, bugbash

#10259 chore: silence sentry noise for codepush deploys #trivial
  fastlane/Fastfile
  fastlane/sentry_fastlane.rb
Labels: Jira Synced, Squash On Green, bugbash

#10260 feat: initialize submission from my collection artwork
  src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionWhySell.tsx
  src/app/Scenes/MyCollection/utils/initializeSubmissionArtworkForm.ts
  src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkBottomNavigation.tests.tsx
  src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkBottomNavigation.tsx
  src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkSelectArtist.tsx
  src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkTopNavigation.tsx
  src/app/Scenes/SellWithArtsy/ArtworkForm/SubmitArtworkForm.tsx
  src/app/Scenes/SellWithArtsy/ArtworkForm/Utils/navigationHelpers.ts
  src/app/Scenes/SellWithArtsy/SubmitArtwork/SubmitArtwork.tsx
Labels: Jira Synced

#10264 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10261 fix(APPL-565): Fix external url issue in Android webview
  src/app/Components/ArtsyWebView.tsx
Labels: Jira Synced, bugbash

#10238 refactor: upload maestro builds nightly to maestro cloud
  .circleci/config.yml
  scripts/maestro/build-android.sh
  scripts/maestro/build-ios.sh
Labels: Jira Synced, Squash On Green

#10269 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10271 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10267 feat(ONYX-956): add purchase history screen
  src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkAddProvenance.tests.tsx
  src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkAddProvenance.tsx
  src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkPurchaseHistory.tests.tsx
  src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkPurchaseHistory.tsx
  src/app/Scenes/SellWithArtsy/ArtworkForm/SubmitArtworkForm.tsx
  src/app/Scenes/SellWithArtsy/ArtworkForm/Utils/constants.ts
  src/app/Scenes/SellWithArtsy/ArtworkForm/Utils/navigationHelpers.ts
  src/app/Scenes/SellWithArtsy/ArtworkForm/Utils/validation.ts
  src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkDetails/utils/createOrUpdateSubmission.ts
  src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkDetails/validation.ts
Labels: Jira Synced

#10282 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10284 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10227 feat: Add My Collection artwork form location autocomplete
  .secrets.baseline
  src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkAbout/MyCollectionArtworkAboutWork.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionWhySell.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtworkAbout.tests.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/MyCollectionArtworkForm.tests.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkEdit.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormMain.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/methods/uploadArtwork.ts
  src/app/Scenes/MyCollection/State/MyCollectionArtworkModel.tests.tsx
  src/app/Scenes/MyCollection/State/MyCollectionArtworkModel.tsx
  src/app/utils/LocalImageStore.ts
Labels: Jira Synced

#10287 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10288 fix: follow button
  package.json
  src/app/Scenes/Partner/Components/PartnerFollowButton.tsx
  yarn.lock
Labels: Squash On Green

#10281 feat(ONYX-986): support save and exit in new submission flow
  src/app/AppRegistry.tsx
  src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkPurchaseHistory.tests.tsx
  src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkSelectArtist.tsx
  src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkTopNavigation.tsx
  src/app/Scenes/SellWithArtsy/ArtworkForm/SubmitArtworkForm.tsx
  src/app/Scenes/SellWithArtsy/ArtworkForm/SubmitArtworkFormEdit.tsx
  src/app/Scenes/SellWithArtsy/ArtworkForm/Utils/constants.ts
  src/app/Scenes/SellWithArtsy/ArtworkForm/Utils/getInitialNavigationState.ts
  src/app/Scenes/SellWithArtsy/ArtworkForm/Utils/getInitialSubmissionValues.ts
  src/app/Scenes/SellWithArtsy/ArtworkForm/Utils/navigationHelpers.ts
  src/app/Scenes/SellWithArtsy/ArtworkForm/Utils/validation.ts
  src/app/Scenes/SellWithArtsy/Components/Header.tsx
  src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkDetails/validation.ts
  src/app/Scenes/SellWithArtsy/SubmitArtwork/SubmitArtwork.tsx
  src/app/Scenes/SellWithArtsy/utils/submissionModelState.tsx
  src/app/routes.ts
  src/app/store/__tests__/migration.tests.ts
  src/app/store/config/features.ts
  src/app/store/migration.ts
  src/app/utils/hooks/withSuspense.tsx
Labels: Jira Synced

#10292 chore: new submission flow bug fixes
  src/app/Components/ArtistAutosuggest/ArtistAutosuggestResults.tsx
  src/app/Components/AutosuggestResults/AutosuggestResults.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtistAutosuggest.tsx
  src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkAddDetails.tsx
  src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkAddDimensions.tsx
  src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkAddPhotos.tsx
  src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkAddTitle.tsx
  src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkArtistRejected.tsx
  src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkBottomNavigation.tests.tsx
  src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkBottomNavigation.tsx
  src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkCompleteYourSubmission.tsx
  src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkPurchaseHistory.tsx
  src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkSelectArtist.tests.tsx
  src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkSelectArtist.tsx
  src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkSelectArtworkMyCollectionArtwork.tsx
  src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkStartFlow.tsx
  src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkTopNavigation.tsx
  src/app/Scenes/SellWithArtsy/ArtworkForm/SubmitArtworkForm.tsx
  src/app/Scenes/SellWithArtsy/ArtworkForm/Utils/constants.ts
  src/app/Scenes/SellWithArtsy/ArtworkForm/Utils/getInitialSubmissionValues.ts
  src/app/Scenes/SellWithArtsy/ArtworkForm/Utils/navigationHelpers.ts
  src/app/Scenes/SellWithArtsy/ArtworkForm/Utils/validation.ts
Labels: Jira Synced, Squash On Green

#10294 chore: update transition spec on android
  src/app/AppRegistry.tsx
  src/app/Scenes/SellWithArtsy/ArtworkForm/SubmitArtworkForm.tsx
Labels: Squash On Green

#10295 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10297 fix: hide keyboard after each step on new submission flow
  src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkAddPhotos.tsx
  src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkSelectArtist.tsx
  src/app/Scenes/SellWithArtsy/ArtworkForm/SubmitArtworkForm.tsx
Labels: Jira Synced

#10303 fix: show exit if save and exit ff is disabled
  src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkTopNavigation.tsx
Labels: Jira Synced

#10298 fix: white block on top of input
  src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkAddDetails.tsx
  src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkAddDimensions.tsx
  src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkAddPhotos.tsx
  src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkAddTitle.tsx
  src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkArtistRejected.tsx
  src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkCompleteYourSubmission.tsx
  src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkPurchaseHistory.tsx
  src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkSelectArtist.tsx
  src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkSelectArtworkMyCollectionArtwork.tsx
  src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkStartFlow.tsx
Labels: Jira Synced

#10300 fix: artwork details year issues
  src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkAddDetails.tsx
Labels: Jira Synced

#10301 fix: eligibility alignment on artist rejected screen
  src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkArtistRejected.tsx
Labels: Jira Synced, Squash On Green

#10304 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10307 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10306 fix: android anrs due to popover
  src/app/Scenes/MyCollection/Screens/ArtworkList/MyCollectionArtworkGridItem.tests.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkList/MyCollectionArtworkGridItem.tsx
Labels: Jira Synced

#10313 chore: prep for 8.42.0
  app.json
Labels: Squash On Green

#10285 fix: Fix flashing SWA landing page image
  src/app/Scenes/SellWithArtsy/SellWithArtsyHome.tsx
  src/app/Scenes/SellWithArtsy/index.tests.tsx
Labels: Jira Synced, Squash On Green

#10317 build(deps): bump @react-native-community/netinfo from 9.3.11 to 11.3.2
  package.json
  yarn.lock
Labels: bugbash

#10319 fix: crash on masonry dynamic columns empty state
  src/app/Components/ArtworkGrids/MasonryInfiniteScrollArtworkGrid.tsx
  src/app/Scenes/NewWorksFromGalleriesYouFollow/Components/NewWorksFromGalleriesYouFollow.tsx
Labels: Jira Synced, Squash On Green, bugbash

#10320 fix: onboarding crash android hardware back button
  src/app/Scenes/Onboarding/OnboardingQuiz/Components/OnboardingQuestionTemplate.tsx
Labels: Jira Synced
