Repository artsy/eigen, pull requests merged in 2024-11, with the labels that each got.

#11051 fix: fix broken animation SWA flow Android
  src/app/Scenes/SellWithArtsy/ArtworkForm/SubmitArtworkForm.tsx
Labels: Squash On Green

#11053 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11036 feat(DIA-899): One-Shot Google Sign-In
  src/app/Scenes/Onboarding/Auth2/scenes/LoginWelcomeStep.tsx
  src/app/store/AuthModel.ts
  src/app/store/__tests__/AuthModel.tests.ts
Labels: Jira Synced, Squash On Green

#11058 fix: remove focus from a test in the AuthModel test suite
  src/app/store/__tests__/AuthModel.tests.ts
Labels: Squash On Green

#11059 feat(home view, analytics): fire experiment event only once per session
  src/app/Scenes/HomeView/HomeViewContext.ts
  src/app/Scenes/HomeView/__tests__/HomeView.tests.tsx
  src/app/Scenes/HomeView/useHomeViewExperimentTracking.ts
Labels: Jira Synced

#11063 refactor(home view): organize hooks
  src/app/Components/Tasks/Task.tsx
  src/app/Scenes/HomeView/Components/ActivityIndicator.tsx
  src/app/Scenes/HomeView/Components/HomeViewSectionSentinel.tsx
  src/app/Scenes/HomeView/Components/PaymentFailureBanner.tsx
  src/app/Scenes/HomeView/Components/__tests__/PaymentFailureBanner.tests.tsx
  src/app/Scenes/HomeView/HomeView.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionActivity.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArticles.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArticlesCards.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArtists.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArtworks.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionAuctionResults.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionCard.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionCards.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionCardsChips.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionFairs.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionFeaturedCollection.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionHeroUnits.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionMarketingCollections.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionSales.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionShows.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionViewingRooms.tsx
  src/app/Scenes/HomeView/hooks/useHomeViewExperimentTracking.ts
  src/app/Scenes/HomeView/hooks/useHomeViewTracking.ts
  src/app/Scenes/HomeViewSectionScreen/HomeViewSectionScreen.tsx
Labels: Art Advisor

#11060 feat(DIA-903): One-Shot Facebook Login
  src/app/Scenes/Onboarding/Auth2/scenes/LoginWelcomeStep.tsx
  src/app/store/AuthModel.ts
  src/app/store/__tests__/AuthModel.tests.ts
  src/app/utils/auth/authHelpers.ts
  src/app/utils/auth/socialSignInHelpers.ts
Labels: Jira Synced

#11065 fix(EMI-2170): Fix Android ghost task after tapping on it
  src/app/Scenes/HomeView/Sections/HomeViewSectionTasks.tsx
Labels: Jira Synced, Squash On Green

#11075 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11076 feat(DIA-973): add social account linking to auth2
  src/app/Scenes/Onboarding/Auth2/scenes/LoginWelcomeStep.tsx
  src/app/Scenes/Onboarding/Onboarding.tsx
  src/app/utils/auth/socialSignInHelpers.ts
Labels: Jira Synced

#11068 test(home view): improve coverage
  src/app/Scenes/HomeView/Sections/HomeViewSectionArticlesCards.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionCardsChips.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionFeaturedCollection.tsx
  src/app/Scenes/HomeView/Sections/Section.tsx
  src/app/Scenes/HomeView/Sections/__tests__/HomeViewSectionArticles.tests.tsx
  src/app/Scenes/HomeView/Sections/__tests__/HomeViewSectionCards.tests.tsx
  src/app/Scenes/HomeView/Sections/__tests__/HomeViewSectionFeaturedCollection.tests.tsx
  src/app/Scenes/HomeView/Sections/__tests__/HomeViewSectionSales.tests.tsx
  src/app/Scenes/HomeView/Sections/__tests__/HomeViewSectionViewingRooms.tests.tsx
  src/app/Scenes/HomeView/Sections/__tests__/Section.tests.tsx
  src/app/Scenes/HomeView/__tests__/HomeView.tests.tsx
Labels: Jira Synced, Squash On Green

#11079 feat: add Unauthorized routes to Navigation
  src/app/Navigation/AuthenticatedRoutes/Tabs.tsx
  src/app/Navigation/Navigation.tsx
  src/app/Scenes/Onboarding/Onboarding.tsx
  src/app/system/devTools/DevMenu/DevMenu.tsx
Labels: Squash On Green

#11077 chore: enable AREnableSignupLoginFusion
  src/app/Scenes/Onboarding/OnboardingCreateAccount/Onboarding.tests.tsx
  src/app/store/config/features.ts
Labels: Squash On Green

#11084 fix: fix broken test
  src/app/Scenes/Home/Components/ActivityRailItem.tests.tsx
Labels: Squash On Green

#11087 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11091 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11062 feat(ONYX-1293): redesign save cta and add follow cta
  src/app/Components/Artist/ArtistHeaderNavRight.tsx
  src/app/Components/Artist/useFollowArtist.ts
  src/app/Components/ArtworkGrids/ArtworkGridItem.tests.tsx
  src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
  src/app/Components/ArtworkGrids/MasonryArtworkGridItem.tsx
  src/app/Components/ArtworkGrids/MasonryInfiniteScrollArtworkGrid.tsx
  src/app/Components/ArtworkRail/ArtworkRail.tsx
  src/app/Components/ArtworkRail/ArtworkRailCard.tests.tsx
  src/app/Components/ArtworkRail/ArtworkRailCard.tsx
  src/app/Components/ArtworkRail/ArtworkRailCardMeta.tsx
  src/app/Components/Home/ArtistRails/ArtistCard.tsx
  src/app/Components/constants.ts
  src/app/Scenes/Artwork/Components/ArtworkItemCTAs.tests.tsx
  src/app/Scenes/Artwork/Components/ArtworkItemCTAs.tsx
  src/app/Scenes/Artwork/Components/ArtworkSaveButton.tsx
  src/app/Scenes/Artwork/utils/getNewSaveAndFollowOnArtworkCardExperimentVariant.tsx
  src/app/Scenes/HomeView/Components/HomeViewSectionSentinel.tsx
  src/app/Scenes/HomeView/HomeView.tsx
  src/app/Scenes/HomeView/HomeViewContext.ts
  src/app/Scenes/HomeView/Sections/HomeViewSectionArtworks.tsx
  src/app/store/config/features.ts
  src/app/system/devTools/DevMenu/Components/ExperimentFlagItem.tsx
  src/app/utils/experiments/experiments.ts
  src/app/utils/experiments/hooks.ts
Labels: Jira Synced, Squash On Green

#11094 fix: heart icon placement on grid new save and follow
  src/app/Components/ArtworkGrids/ArtworkGridItem.tests.tsx
  src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
  src/app/Components/ArtworkGrids/MasonryArtworkGridItem.tsx
  src/app/Components/ArtworkGrids/MasonryInfiniteScrollArtworkGrid.tsx
  src/app/Components/ArtworkRail/ArtworkRailCard.tsx
  src/app/Components/ArtworkRail/ArtworkRailCardMeta.tsx
  src/app/Scenes/Artwork/Components/ArtworkItemCTAs.tests.tsx
  src/app/Scenes/Artwork/Components/ArtworkItemCTAs.tsx
  src/app/Scenes/Artwork/Components/ArtworkSaveButton.tsx
  src/app/Scenes/Artwork/utils/getNewSaveAndFollowOnArtworkCardExperimentVariant.tsx
  src/app/Scenes/Artwork/utils/useGetNewSaveAndFollowOnArtworkCardExperimentVariant.tsx
Labels: Squash On Green

#11082 fix(ONYX-1386): Update routes for alerts and saves to match web and fix deep linking
  src/app/Components/ArtworkLists/useArtworkListsToast.ts
  src/app/Scenes/Activity/Activity.tsx
  src/app/Scenes/Activity/components/AlertNotification.tsx
  src/app/Scenes/Activity/components/PartnerOfferCreatedNotification.tsx
  src/app/Scenes/Activity/components/__tests__/AlertNotification.tests.tsx
  src/app/Scenes/Activity/components/__tests__/PartnerOfferCreatedNotification.tests.tsx
  src/app/Scenes/Artwork/ArtworkAuctionCreateAlertHeader.tsx
  src/app/Scenes/MyProfile/MyProfileHeader.tests.tsx
  src/app/Scenes/MyProfile/MyProfileHeader.tsx
  src/app/Scenes/SavedSearchAlert/AlertArtworksGrid.tests.tsx
  src/app/Scenes/SavedSearchAlert/AlertArtworksGrid.tsx
  src/app/Scenes/SavedSearchAlert/SavedSearchAlertForm.tests.tsx
  src/app/Scenes/SavedSearchAlert/SavedSearchAlertForm.tsx
  src/app/Scenes/SavedSearchAlert/screens/ConfirmationScreen.tests.tsx
  src/app/Scenes/SavedSearchAlert/screens/ConfirmationScreen.tsx
  src/app/Scenes/SavedSearchAlertsList/Components/AlertBottomSheet.tests.tsx
  src/app/Scenes/SavedSearchAlertsList/Components/AlertBottomSheet.tsx
  src/app/Scenes/SavedSearchAlertsList/Components/SavedSearchesList.tsx
  src/app/routes.ts
  src/app/system/navigation/navigate.tests.tsx
Labels: Jira Synced

#11115 fix: broken artworks empty state on show screen
  src/app/Scenes/Show/Components/ShowArtworks.tsx
  src/app/Scenes/Show/Show.tsx
  src/app/Scenes/Show/ShowArtworks.tests.tsx
Labels: Squash On Green

#11033 feat: prepare for new search modal
  package.json
  src/app/Components/GlobalSearchInput.tests.tsx
  src/app/Components/GlobalSearchInput.tsx
  src/app/Components/GlobalSearchInputOverlay.tsx
  src/app/Providers.tsx
  src/app/Scenes/HomeView/Components/HomeHeader.tsx
  src/app/Scenes/HomeView/HomeView.tsx
  src/app/Scenes/Search/Search.tests.tsx
  src/app/Scenes/Search/Search.tsx
  src/app/Scenes/Search/components/placeholders/SearchPlaceholder.tsx
  src/app/store/config/features.ts
Labels: Jira Synced

#11125 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11103 feat: Prefetch viewing rooms on home screen
  src/app/AppRegistry.tsx
  src/app/Scenes/ViewingRoom/Components/ViewingRoomsHomeRail.tsx
  src/app/Scenes/ViewingRoom/ViewingRoom.tsx
Labels: Squash On Green

#11102 fix: address new save and follow issues
  src/app/Components/ArtworkGrids/ArtworkGridItem.tests.tsx
  src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
  src/app/Components/ArtworkGrids/MasonryArtworkGridItem.tsx
  src/app/Components/ArtworkGrids/MasonryInfiniteScrollArtworkGrid.tsx
  src/app/Components/ArtworkRail/ArtworkRailCardMeta.tsx
  src/app/Components/constants.ts
  src/app/Scenes/Activity/components/NotificationArtworkList.tsx
  src/app/Scenes/Artwork/Components/ArtworkItemCTAs.tests.tsx
  src/app/Scenes/Artwork/Components/ArtworkItemCTAs.tsx
  src/app/Scenes/Artwork/Components/ArtworkSaveButton.tsx
Labels: Squash On Green

#11092 feat: search modal content
  src/app/Components/GlobalSearchInput.tests.tsx
  src/app/Components/GlobalSearchInput/GlobalSearchInput.tsx
  src/app/Components/GlobalSearchInput/GlobalSearchInputOverlay.tsx
  src/app/Components/GlobalSearchInput/GlobalSearchInputOverlayEmptyState.tsx
  src/app/Components/GlobalSearchInput/GlobalSearchOverlay.tsx
  src/app/Components/GlobalSearchInput/useSearch.ts
  src/app/Components/GlobalSearchInputOverlay.tsx
  src/app/Scenes/HomeView/Components/HomeHeader.tsx
  src/app/Scenes/Search/Search.tsx
Labels: Jira Synced, Squash On Green

#11128 refactor: proper usage for useSharedValue
  docs/best_practices.md
  src/app/Components/AnimatableHeader/AnimatableHeaderProvider.tsx
  src/app/Components/Disappearable.tsx
  src/app/Components/Swipeable/Swipeable.tsx
  src/app/Scenes/Onboarding/OnboardingQuiz/OnboardingWelcome.tsx
  src/app/Scenes/Onboarding/OnboardingWelcome.tsx
  src/app/Scenes/Playground/Animation/L2-Shared-Values/App1.tsx
  src/app/Scenes/Playground/Animation/L2-Shared-Values/App2.tsx
  src/app/Scenes/Playground/Animation/L2-Shared-Values/App3.tsx
  src/app/Scenes/Playground/Animation/L2-Shared-Values/App4.tsx
  src/app/Scenes/Playground/Animation/L2-Shared-Values/App5.tsx
  src/app/Scenes/Playground/Animation/L5-Exercice/index.tsx
  src/app/Scenes/SavedSearchAlertsList/Components/SavedSearchListItem.tsx
  src/app/utils/animations/useSkeletonAnimation.tsx
Labels: Jira Synced, Squash On Green

#11130 fix: podfile lock diff
  ios/Podfile.lock
Labels: Squash On Green

#11119 docs: debugging docs
  docs/debugging.md
  docs/generate_a_release_build_for_local_testing.md
  docs/getting_started.md
  package.json
Labels: Jira Synced

#11134 fix: remove redundant flex component
  src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
Labels: Squash On Green

#11133 fix(EMI-2174): Refetch tasks on the home view
  src/app/Components/Tasks/Task.tests.tsx
  src/app/Components/Tasks/Task.tsx
  src/app/Scenes/HomeView/HomeView.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionTasks.tsx
  src/app/Scenes/HomeView/Sections/Section.tsx
  src/app/Scenes/HomeView/Sections/__tests__/HomeViewSectionTasks.tests.tsx
Labels: Jira Synced

#11138 chore(tests): delete tests that fail for uncontrolled input
  src/app/Scenes/Onboarding/OnboardingCreateAccount/OnboardingCreateAccountEmail.tests.tsx
  src/app/Scenes/Onboarding/OnboardingCreateAccount/OnboardingCreateAccountName.tests.tsx
  src/app/Scenes/Onboarding/OnboardingCreateAccount/OnboardingCreateAccountPassword.tests.tsx
  src/app/Scenes/Search/components/SearchInput.tests.tsx
Labels: Squash On Green

#11139 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11136 chore: Remove dynamic home view feature flags
  src/app/Scenes/Home/HomeContainer.tests.tsx
  src/app/Scenes/Home/HomeContainer.tsx
  src/app/store/config/features.ts
  src/app/utils/useHideSplashScreen.ts
Labels: Jira Synced

#11144 chore: increase search button hitslop
  package.json
  src/app/Components/GlobalSearchInput/GlobalSearchInput.tsx
  yarn.lock
Labels: Squash On Green

#11147 chore: update placeholder copy on search modal
  src/app/Components/GlobalSearchInput/GlobalSearchInput.tests.tsx
  src/app/Components/GlobalSearchInput/GlobalSearchInput.tsx
  src/app/Scenes/Search/Search.tests.tsx
  src/app/Scenes/Search/Search.tsx
Labels: Squash On Green

#11150 chore(Revert): "refactor: replace prefetchFlashList with PrefetchFlatList on rails"
  src/app/Components/ArtworkRail/ArtworkRail.tsx
Labels: Squash On Green

#11153 chore: update copy on search modal overlay
  src/app/Components/GlobalSearchInput/GlobalSearchInputOverlayEmptyState.tsx
Labels: Squash On Green

#11137 fix: city picker padding on city guide
  src/app/Scenes/Map/GlobalMap.tsx
Labels: Squash On Green

#11157 chore(DIA-629): address eslint errors in ConfirmBid component and tests
  src/app/Components/Bidding/Screens/ConfirmBid.tests.tsx
  src/app/Components/Bidding/Screens/ConfirmBid/index.tsx
Labels: Jira Synced

#11155 chore: make text non selectable on search modal
  src/app/Components/GlobalSearchInput/GlobalSearchInputOverlayEmptyState.tsx
Labels: Squash On Green

#11148 chore(ONYX-1403): cleanup AREnableArtworkRailRedesignImageAspectRatio feature flag
  src/app/Components/ArtworkRail/ArtworkRail.tsx
  src/app/Components/ArtworkRail/ArtworkRailCard.tests.tsx
  src/app/Components/ArtworkRail/ArtworkRailCard.tsx
  src/app/Components/ArtworkRail/LegacyArtworkRailCardImage.tsx
  src/app/Components/ContextMenu/ContextMenuArtworkPreviewCardImage.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArtworks.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionFeaturedCollection.tsx
  src/app/store/config/features.ts
Labels: Jira Synced

#11161 chore(DIA-629): retire AREnableNewTermsAndConditions for real
  src/app/Components/Bidding/Screens/Registration.tests.tsx
  src/app/Components/Bidding/Screens/Registration.tsx
  src/app/Scenes/About/About.tests.tsx
  src/app/Scenes/About/About.tsx
  src/app/Scenes/Onboarding/OnboardingCreateAccount/TermsOfServiceCheckbox.tests.tsx
  src/app/Scenes/Onboarding/OnboardingCreateAccount/TermsOfServiceCheckbox.tsx
  src/app/Scenes/Onboarding/OnboardingSocialPick.tests.tsx
  src/app/Scenes/Onboarding/OnboardingSocialPick.tsx
  src/app/store/config/features.ts
Labels: Jira Synced

#11159 chore: hide view follows link on the toast on the onboarding grid
  src/app/Components/Artist/useFollowArtist.ts
  src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
  src/app/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx
  src/app/Scenes/Artwork/Components/ArtworkItemCTAs.tsx
  src/app/Scenes/Onboarding/OnboardingQuiz/OnboardingMarketingCollection.tsx
Labels: Squash On Green

#11171 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11173 fix: navigate back to tab behaviour
  src/app/Navigation/AuthenticatedRoutes/Tabs.tsx
Labels: Squash On Green

#11172 fix: explore Works Link on Inbox
  src/app/Scenes/Inbox/Components/Conversations/NoMessages.tests.tsx
  src/app/Scenes/Inbox/Components/Conversations/NoMessages.tsx
Labels: Squash On Green

#11175 feat: simplify bottom tabs logic
  src/app/Navigation/AuthenticatedRoutes/Tabs.tsx
  src/app/Navigation/Utils/useBottomTabsBadges.tests.ts
  src/app/Navigation/Utils/useBottomTabsBadges.ts
  src/app/Scenes/BottomTabs/bottomTabsConfig.tsx
Labels: Squash On Green

#11182 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11183 chore(DIA-942): test auth2 login welcome step
  src/app/Scenes/Onboarding/Auth2/scenes/LoginWelcomeStep.tsx
  src/app/Scenes/Onboarding/Auth2/scenes/__tests__/LoginWelcomeStep.test.tsx
  src/app/Scenes/Onboarding/Auth2/scenes/__tests__/LoginWelcomeStep.tests.tsx
Labels: Jira Synced, Squash On Green

#11191 fix: hide hidden header logic
  src/app/Navigation/AuthenticatedRoutes/StackNavigator.tsx
Labels: Squash On Green

#11184 chore: Retire HomeContainer
  src/app/AppRegistry.tsx
  src/app/Scenes/Home/HomeContainer.tsx
  src/app/Scenes/HomeView/HomeView.tsx
Labels: Jira Synced, Squash On Green

#11188 fix: adjust SellWithArtsyRecentlySold rail card height
  src/app/Components/ArtworkRail/ArtworkRailCard.tsx
  src/app/Components/ArtworkRail/ArtworkRailCardMeta.tsx
  src/app/Scenes/SellWithArtsy/Components/SellWithArtsyRecentlySold.tsx
Labels: Jira Synced

#11097 fix: avoid prefetching when following deeplinks
  src/app/Scenes/HomeView/HomeView.tsx
  src/app/Scenes/HomeView/__tests__/HomeView.tests.tsx
  src/app/utils/hooks/useIsDeepLink.tests.ts
  src/app/utils/hooks/useIsDeepLink.ts
  src/app/utils/useHideSplashScreen.ts
Labels: Jira Synced, Squash On Green

#11127 chore: Refactor and simplify query prefetching
  src/app/Components/PrefetchFlashList.tsx
  src/app/utils/queryPrefetching.ts
  src/app/utils/useHideSplashScreen.ts
  src/setupJest.tsx
Labels: Squash On Green

#11196 fix(ONYX-1390): fix Context Menu Artwork Preview Card Image dimensions
  src/app/Components/ContextMenu/ContextMenuArtworkPreviewCard.tsx
  src/app/Components/ContextMenu/ContextMenuArtworkPreviewCardImage.tsx
Labels: Jira Synced

#11100 feat: Add Availability filter to artwork filters
  src/app/Components/ArtworkFilter/ArtworkFilterHelpers.ts
  src/app/Components/ArtworkFilter/ArtworkFilterNavigator.tsx
  src/app/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx
  src/app/Components/ArtworkFilter/Filters/AvailabilityOptions.tests.tsx
  src/app/Components/ArtworkFilter/Filters/AvailabilityOptions.tsx
  src/app/Components/ArtworkFilter/types.ts
  src/app/store/config/features.ts
Labels: Jira Synced, Squash On Green

#11192 chore(DIA-942): add tests for auth2
  src/app/Scenes/Onboarding/Auth2/scenes/ForgotPasswordStep.tsx
  src/app/Scenes/Onboarding/Auth2/scenes/LoginPasswordStep.tsx
  src/app/Scenes/Onboarding/Auth2/scenes/SignUpPasswordStep.tsx
  src/app/Scenes/Onboarding/Auth2/scenes/__tests__/ForgotPasswordStep.test.tsx
  src/app/Scenes/Onboarding/Auth2/scenes/__tests__/ForgotPasswordStep.tests.tsx
  src/app/Scenes/Onboarding/Auth2/scenes/__tests__/LoginPasswordStep.test.tsx
  src/app/Scenes/Onboarding/Auth2/scenes/__tests__/LoginPasswordStep.tests.tsx
  src/app/Scenes/Onboarding/Auth2/scenes/__tests__/SignUpPasswordStep.test.tsx
  src/app/Scenes/Onboarding/Auth2/scenes/__tests__/SignUpPasswordStep.tests.tsx
Labels: Jira Synced

#11201 fix(betas): update mapbox to fix bitcode submission issue
  .circleci/config.yml
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: Squash On Green

#11207 fix(ONYX-1383): some artwork rail images get mangled after horizontal scrolling
  src/app/Components/ArtworkRail/ArtworkRail.tsx
  src/app/Components/ArtworkRail/ArtworkRailCard.tsx
  src/app/Components/ArtworkRail/ArtworkRailCardImage.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArtworks.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionFeaturedCollection.tsx
  src/app/Scenes/SellWithArtsy/Components/SellWithArtsyRecentlySold.tsx
Labels: Jira Synced, Squash On Green

#11216 fix: bottom sheet edit alert
  src/app/Scenes/SavedSearchAlertsList/Components/AlertBottomSheet.tsx
Labels: Squash On Green

#11221 fix: Revert: "fix: deep link analytics event triggered twice"
  src/app/utils/useDeepLinks.ts
Labels: Squash On Green

#11225 feat: gh action release
  .github/workflows/release.yml
Labels: Squash On Green

#11222 fix: Correct artwork count update on the Artist screen's artwork grid
  src/app/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
Labels: Jira Synced

#11217 feat: Add Availibility filter to all artwork grids
  src/app/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx
Labels: Jira Synced

#11229 fix(REVERT): bring back double deeplink tracking
  src/app/utils/useDeepLinks.ts
Labels: Squash On Green

#11227 fix(ONYX-1422): do not switch tabs when navigating to follows
  src/app/Components/Artist/useFollowArtist.ts
Labels: Jira Synced
