Repository artsy/eigen, pull requests merged in 2024-03, with the labels that each got.

#9915 feat: add 404 page to artwork
  src/app/Scenes/Artwork/Artwork.tsx
  src/app/Scenes/Artwork/Components/ArtworkError.tests.tsx
  src/app/Scenes/Artwork/Components/ArtworkError.tsx
Labels: Jira Synced

#9925 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9926 chore: Use totalCount for offer notifications
  src/app/Scenes/Activity/components/NewActivityHeader.tsx
Labels: Jira Synced

#9923 fix: enable scroll only when there is more than one elements in the a…
  src/app/Scenes/Activity/ActivityEmptyView.tsx
  src/app/Scenes/Activity/ActivityList.tsx
Labels: Squash On Green

#9927 fix: missing new works for you rail on artwork page
  src/app/Scenes/Artwork/Components/ArtworkError.tests.tsx
  src/app/Scenes/Artwork/Components/ArtworkError.tsx
Labels: Squash On Green

#9933 fix: parsing of Google Places API details request
  src/app/utils/googleMaps.tests.ts
  src/app/utils/googleMaps.ts
Labels: Jira Synced

#9930 feat(EMI-1715): Add share list toggle in create new list
  src/app/Components/ArtworkLists/components/CreateOrEditArtworkListForm.tsx
  src/app/Components/ArtworkLists/views/CreateNewArtworkListView/CreateNewArtworkListView.tests.tsx
  src/app/Components/ArtworkLists/views/CreateNewArtworkListView/components/CreateNewArtworkListForm.tsx
  src/app/store/config/features.ts
Labels: Jira Synced

#9836 chore: add animations playground
  docs/README.md
  docs/intro_animations_in_eigen.md
  src/app/Components/MenuItem.tsx
  src/app/Scenes/Home/HomeContainer.tsx
  src/app/Scenes/Playground/Animation/L0-Reanimated/index.tsx
  src/app/Scenes/Playground/Animation/L1-Animated-Components/index.tsx
  src/app/Scenes/Playground/Animation/L2-Shared-Values/App1.tsx
  src/app/Scenes/Playground/Animation/L2-Shared-Values/App2.tsx
  src/app/Scenes/Playground/Animation/L2-Shared-Values/App3.tsx
  src/app/Scenes/Playground/Animation/L2-Shared-Values/App4.tsx
  src/app/Scenes/Playground/Animation/L2-Shared-Values/App5.tsx
  src/app/Scenes/Playground/Animation/L2-Shared-Values/index.tsx
  src/app/Scenes/Playground/Animation/L3-Moti/index.tsx
  src/app/Scenes/Playground/Animation/L4-Gestures/index.tsx
  src/app/Scenes/Playground/Animation/L5-Exercice/index.tsx
  src/app/Scenes/Playground/Animation/index.tsx
  src/app/Scenes/Playground/Playground.tsx
  src/app/store/config/features.ts
Labels: Squash On Green

#9919 build(deps): bump react-native-fbsdk-next from 11.0.0 to 12.1.4
  ios/Artsy/App/ARAppDelegate.mm
  ios/Podfile
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: Jira Synced

#9940 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9922 fix(ONYX-822): fix broken ArtsyWebView paddings
  src/app/Components/ArtsyWebView.tsx
  src/app/Scenes/VanityURL/VanityURLPossibleRedirect.tests.tsx
  src/app/Scenes/VanityURL/VanityURLPossibleRedirect.tsx
Labels: Jira Synced

#9936 fix: inquiry notifs
  src/app/system/navigation/navigate.ts
Labels: Jira Synced

#9944 fix: Missing Activity item divider
  src/app/Scenes/Activity/ActivityItem.tsx
  src/app/Scenes/Activity/ActivityItemTypeLabel.tsx
  src/app/Scenes/Home/Components/ActivityRailItem.tsx
Labels: Jira Synced

#9945 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9947 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9949 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9952 chore: Fix broken Activity panel tests after enabling feature flags
  src/app/Scenes/Activity/Activity.tests.tsx
  src/app/Scenes/Activity/ActivityItem.tests.tsx
  src/app/Scenes/Home/Components/ActivityRail.tests.tsx
Labels: Squash On Green

#9905 chore(onyx-467): migrate from savedSearches to alerts
  src/app/Components/Artist/ArtistArtworks/CreateSavedSearchModal.tests.tsx
  src/app/Components/Artist/ArtistHeader.tests.tsx
  src/app/Components/Artist/ArtistHeader.tsx
  src/app/Scenes/Artist/Artist.tsx
  src/app/Scenes/Artist/ArtistSavedSearch.tests.tsx
  src/app/Scenes/Artist/SearchCriteria.tests.tsx
  src/app/Scenes/Artist/SearchCriteria.tsx
  src/app/Scenes/SavedSearchAlert/Components/SavedSearchSuggestedFilters.tsx
  src/app/Scenes/SavedSearchAlert/CreateSavedSearchAlert.tests.tsx
  src/app/Scenes/SavedSearchAlert/EditSavedSearchAlert.tests.tsx
  src/app/Scenes/SavedSearchAlert/EditSavedSearchAlert.tsx
  src/app/Scenes/SavedSearchAlert/SavedSearchAlert.tsx
  src/app/Scenes/SavedSearchAlert/SavedSearchAlertForm.tests.tsx
  src/app/Scenes/SavedSearchAlert/SavedSearchAlertForm.tsx
  src/app/Scenes/SavedSearchAlert/SavedSearchAlertModel.ts
  src/app/Scenes/SavedSearchAlert/SavedSearchStore.tsx
  src/app/Scenes/SavedSearchAlert/mutations/createSavedSearchAlert.ts
  src/app/Scenes/SavedSearchAlert/mutations/deleteSavedSearchAlert.ts
  src/app/Scenes/SavedSearchAlert/mutations/updateSavedSearchAlert.ts
  src/app/Scenes/SavedSearchAlert/queries/getAlertByCriteria.ts
  src/app/Scenes/SavedSearchAlert/queries/getSavedSearchIdByCriteria.ts
  src/app/Scenes/SavedSearchAlert/screens/ConfirmationScreen.tests.tsx
  src/app/Scenes/SavedSearchAlert/screens/ConfirmationScreen.tsx
  src/app/Scenes/SavedSearchAlertsList/Components/SavedSearchesList.tests.tsx
  src/app/Scenes/SavedSearchAlertsList/Components/SavedSearchesList.tsx
  src/app/Scenes/SavedSearchAlertsList/SavedSearchAlertsList.tsx
Labels: Jira Synced

#9953 chore: Adjust Activity related tests for new design
  src/app/Scenes/Activity/Activity.tests.tsx
  src/app/Scenes/Activity/ActivityItem.tests.tsx
Labels: Squash On Green

#9955 feat(onyx-733): design changes in alerts list screen
  docs/add_a_new_screen.md
  src/app/AppRegistry.tsx
  src/app/Scenes/SavedSearchAlertsList/Components/SavedSearchAlertsListPlaceholder.tsx
  src/app/Scenes/SavedSearchAlertsList/Components/SavedSearchListItem.tsx
  src/app/Scenes/SavedSearchAlertsList/Components/SavedSearchesList.tests.tsx
  src/app/Scenes/SavedSearchAlertsList/Components/SavedSearchesList.tsx
  src/app/Scenes/SavedSearchAlertsList/SavedSearchAlertsList.tsx
  src/app/system/navigation/navigate.tests.tsx
Labels: Jira Synced

#9745 feat(h13): add Blurhash to Artworks
  .secrets.baseline
  src/app/Components/Artist/ArtistHeader.tsx
  src/app/Components/Artist/ArtistShows/ArtistShow.tsx
  src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
  src/app/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx
  src/app/Components/ArtworkRail/ArtworkRailCard.tsx
  src/app/Components/Lists/SavedItemRow.tsx
  src/app/Components/OpaqueImageView/OpaqueImageView.tsx
  src/app/Components/OpaqueImageView2/OpaqueImageView2.tsx
  src/app/Components/SaleArtworkTileRailCard/SaleArtworkTileRailCard.tsx
  src/app/Scenes/Article/Components/ArticleHero.tsx
  src/app/Scenes/Article/Components/Sections/ArticleSectionImageCollection/__tests__/ArticleSectionImageCollectionImage.tests.tsx
  src/app/Scenes/ArtistSeries/ArtistSeriesHeader.tsx
  src/app/Scenes/ArtistSeries/ArtistSeriesListItem.tsx
  src/app/Scenes/Artwork/Components/AboveTheFoldArtworkPlaceholder.tsx
  src/app/Scenes/Artwork/Components/ImageCarousel/FullScreen/ImageCarouselFullScreen.tests.tsx
  src/app/Scenes/Artwork/Components/ImageCarousel/ImageCarousel.tests.tsx
  src/app/Scenes/Artwork/Components/ImageCarousel/ImageCarousel.tsx
  src/app/Scenes/Artwork/Components/ImageCarousel/ImageCarouselContext.tests.tsx
  src/app/Scenes/Artwork/Components/ImageCarousel/ImageCarouselContext.tsx
  src/app/Scenes/Artwork/Components/ImageCarousel/ImageCarouselEmbedded.tests.tsx
  src/app/Scenes/Artwork/Components/ImageCarousel/ImageCarouselEmbedded.tsx
  src/app/Scenes/Artwork/Components/ImageCarousel/ImageWithLoadingState.tests.tsx
  src/app/Scenes/Artwork/Components/ImageCarousel/ImageWithLoadingState.tsx
  src/app/Scenes/Artwork/Components/InstagramStoryViewShot.tsx
  src/app/Scenes/Artwork/helpers.ts
  src/app/Scenes/ArtworkList/ArtworkList.tsx
  src/app/Scenes/ArtworkRecommendations/ArtworkRecommendations.tsx
  src/app/Scenes/Collection/Components/CollectionHubsRails/FeaturedCollections/FeaturedCollectionsRail.tests.tsx
  src/app/Scenes/Collection/Components/CollectionHubsRails/FeaturedCollections/FeaturedCollectionsRail.tsx
  src/app/Scenes/Home/Components/MarketingCollectionRail.tsx
  src/app/Scenes/Inbox/Components/ActiveBids/ActiveBid.tsx
  src/app/Scenes/Inbox/Components/Conversations/ConversationSnippet.tsx
  src/app/Scenes/Inbox/Components/Conversations/ItemArtwork.tsx
  src/app/Scenes/Inbox/Components/Conversations/Preview/ArtworkPreview.tsx
  src/app/Scenes/Inbox/Components/Conversations/Preview/ShowPreview.tsx
  src/app/Scenes/LotsByArtistsYouFollow/LotsByArtistsYouFollow.tsx
  src/app/Scenes/MyBids/Components/Lot.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionImageView.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkList/MyCollectionArtworkGridItem.tsx
  src/app/Scenes/NewWorksForYou/Components/NewWorksForYouArtworks.tsx
  src/app/Scenes/NewWorksFromGalleriesYouFollow/Components/NewWorksFromGalleriesYouFollow.tsx
  src/app/Scenes/OrderHistory/OrderHistoryRow.tsx
  src/app/Scenes/Partner/Components/PartnerShowRailItem.tsx
  src/app/Scenes/Partner/Components/PartnerShows.tests.tsx
  src/app/Scenes/RecentlyViewed/Components/RecentlyViewedArtworks.tsx
  src/app/Scenes/Sales/Components/SaleListItem.tsx
  src/app/Scenes/Search/components/SearchResultImage.tsx
  src/app/Scenes/Show/Components/ShowContextCard.tsx
  src/app/Scenes/SimilarToRecentlyViewed/SimilarToRecentlyViewed.tsx
  src/app/store/config/features.ts
Labels: Jira Synced, hackathon

#9956 feat: add revert sort ability on ff dev menu
  src/app/system/devTools/DevMenu/DevMenu.tsx
Labels: Squash On Green

#9937 fix(ONYX-825): "Latest Activity" rail item design fixes
  src/app/Scenes/Activity/ActivityItem.tests.tsx
  src/app/Scenes/Activity/ActivityItem.tsx
  src/app/Scenes/Activity/ActivityItemTypeLabel.tsx
  src/app/Scenes/Activity/utils/getNotificationTypeLabel.ts
  src/app/Scenes/Activity/utils/shouldDisplayNotificationTypeLabel.ts
  src/app/Scenes/Home/Components/ActivityRail.tests.tsx
  src/app/Scenes/Home/Components/ActivityRailItem.tsx
Labels: Jira Synced

#9963 chore: show feedback after copying URL to clipboard
  src/app/system/devTools/DevMenu/Components/ExperimentFlagItem.tsx
Labels: Squash On Green

#9961 feat(onyx-735): open alert bottom sheet when tapping on an alert
  src/app/Components/ArtworkLists/views/CreateNewArtworkListView/CreateNewArtworkListView.tsx
  src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/SelectArtworkListsForArtworkView.tsx
  src/app/Components/BottomSheet/AutoHeightBottomSheet.tsx
  src/app/Components/BottomSheet/AutomountedBottomSheetModal.tsx
  src/app/Scenes/ArtworkList/ManageArtworkListView.tsx
  src/app/Scenes/ArtworkList/views/DeleteArtworkListView/DeleteArtworkListView.tsx
  src/app/Scenes/ArtworkList/views/EditArtworkListView/EditArtworkListView.tsx
  src/app/Scenes/SavedSearchAlertsList/Components/AlertBottomSheet.tests.tsx
  src/app/Scenes/SavedSearchAlertsList/Components/AlertBottomSheet.tsx
  src/app/Scenes/SavedSearchAlertsList/Components/SavedSearchesList.tests.tsx
  src/app/Scenes/SavedSearchAlertsList/Components/SavedSearchesList.tsx
  src/app/store/config/features.ts
Labels: Jira Synced

#9964 feat(onyx-736): view arworks screen for alert matches
  src/app/AppRegistry.tsx
  src/app/Scenes/SavedSearchAlert/AlertArtworks.tsx
  src/app/Scenes/SavedSearchAlert/AlertArtworksGrid.tests.tsx
  src/app/Scenes/SavedSearchAlert/AlertArtworksGrid.tsx
  src/app/Scenes/SavedSearchAlert/AlertArtworksPills.tests.tsx
  src/app/Scenes/SavedSearchAlert/AlertArtworksPills.tsx
  src/app/Scenes/SavedSearchAlert/EditSavedSearchAlert.tsx
  src/app/Scenes/SavedSearchAlert/SavedSearchAlertModel.ts
  src/app/Scenes/SavedSearchAlertsList/Components/AlertBottomSheet.tsx
  src/app/Scenes/SavedSearchAlertsList/Components/SavedSearchesList.tests.tsx
  src/app/routes.ts
  src/app/store/config/features.ts
Labels: Jira Synced

#9968 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9969 fix: onboarding follow galleries follow btn state
  src/app/Scenes/Onboarding/OnboardingQuiz/Components/OnboardingPartnerListItem.tsx
  src/app/Scenes/Onboarding/OnboardingQuiz/Components/OnboardingQuestionTemplate.tsx
Labels: Squash On Green

#9972 feat(dev menu): add copy push notif to clipboard helper
  src/app/system/devTools/DevMenu/Components/DevTools.tsx
Labels: Jira Synced, Squash On Green

#9974 build(feat): latest submissions script #trivial
  docs/deploy_a_hotfix.md
  scripts/deploys/latest-submissions
Labels: Jira Synced, Squash On Green

#9979 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9981 fix: display alert artworks grid when there is only 1 artwork
  src/app/Scenes/SavedSearchAlert/AlertArtworksGrid.tsx
Labels: Jira Synced

#9982 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9983 fix(onyx-736): refetch pills and artworks when navigating to alerts View Artworks screen
  src/app/Scenes/SavedSearchAlert/AlertArtworks.tsx
  src/app/Scenes/SavedSearchAlert/AlertArtworksGrid.tests.tsx
  src/app/Scenes/SavedSearchAlert/AlertArtworksGrid.tsx
  src/app/Scenes/SavedSearchAlert/AlertArtworksPills.tsx
Labels: Jira Synced

#9986 fix: Update Activity panel Partner Offer purchase button
  src/app/Scenes/Activity/components/NotificationCommercialButtons.tsx
  src/app/Scenes/Artwork/Components/CommercialButtons/BuyNowButton.tsx
Labels: Jira Synced

#9992 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9994 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9995 chore(tool): required apis script
  .secrets.baseline
  scripts/utils/required_reason_api_usage.sh
Labels: Jira Synced

#9988 chore: add patch to avoid required apis usage in device info
  HACKS.md
  patches/react-native-device-info+10.3.0.patch
Labels: Jira Synced

#9980 feat(ONYX-813): hide bottom tabs when submitting an artwork to sell
  src/app/AppRegistry.tsx
  src/app/Scenes/SellWithArtsy/SubmitArtwork/SubmitArtwork.tsx
  src/app/Scenes/SellWithArtsy/SubmitArtwork/UploadPhotos/UploadPhotos.tsx
Labels: Jira Synced, Squash On Green

#10000 fix(build): update react native to fix flipper issues
  Gemfile
  Gemfile.lock
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: Jira Synced, Squash On Green

#10001 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10002 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10003 feat(onyx-737): swipe to delete alert
  jest.config.js
  src/app/Scenes/SavedSearchAlertsList/Components/SavedSearchListItem.tsx
  src/app/Scenes/SavedSearchAlertsList/Components/SavedSearchesList.tests.tsx
  src/app/Scenes/SavedSearchAlertsList/Components/SavedSearchesList.tsx
  src/setupJest.tsx
Labels: Jira Synced

#10006 chore: update patches for rn upgrade #trivial
  patches/@react-native-community+cli-platform-ios+11.4.1.patch
  patches/react-native+0.72.12.patch
Labels: Squash On Green

#10009 chore(tool): add script for finding common sdk usages
  scripts/utils/required_reason_common_sdk_names.txt
  scripts/utils/required_reason_common_sdks.sh
Labels: Jira Synced

#9999 feat: Add Offer Settings modal
  src/app/Components/ArtworkLists/ArtworkListsContext.tests.tsx
  src/app/Components/ArtworkLists/ArtworkListsContext.tsx
  src/app/Components/ArtworkLists/components/ArtworkListItem.tsx
  src/app/Components/ArtworkLists/components/ArtworkLists.tsx
  src/app/Components/ArtworkLists/components/ArtworkListsLoadingIndicator.tsx
  src/app/Components/ArtworkLists/components/CreateOrEditArtworkListForm.tsx
  src/app/Components/ArtworkLists/types.ts
  src/app/Components/ArtworkLists/views/ArtworkListOfferSettingsView/ArtworkListOfferSettingsView.tsx
  src/app/Components/ArtworkLists/views/ArtworkListOfferSettingsView/components/ArtworkListOfferSettings.tsx
  src/app/Components/ArtworkLists/views/ArtworkListOfferSettingsView/components/ArtworkListOfferSettingsHeader.tsx
  src/app/Components/ArtworkLists/views/ArtworkListOfferSettingsView/components/ArtworkListOfferSettingsStickyBottomContent.tsx
  src/app/Components/ArtworkLists/views/ArtworkListOfferSettingsView/useSaveArtworkListsOfferSettingsChanges.ts
  src/app/Components/ArtworkLists/views/ArtworkListOfferSettingsView/useUpdateArtworkListOfferSettings.ts
  src/app/Components/ArtworkLists/views/CreateNewArtworkListView/CreateNewArtworkListView.tests.tsx
  src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/SelectArtworkListsForArtworkView.tsx
  src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/components/ArtworkListItem.tsx
  src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/components/SelectArtworkListStickyBottomContent.tsx
  src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/components/SelectArtworkListsForArtwork.tsx
  src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/useSaveArtworkListsChanges.ts
  src/app/Components/ArtworkLists/views/constants.ts
  src/app/Components/LineGraph/LineGraphCategoryPicker.tsx
  src/app/Scenes/ArtworkList/ArtworkList.tests.tsx
  src/app/Scenes/ArtworkList/ArtworkList.tsx
  src/app/Scenes/ArtworkList/ArtworkListArtworksGridHeader.tsx
  src/app/Scenes/ArtworkList/ArtworkListEmptyState.tests.tsx
  src/app/Scenes/ArtworkList/ArtworkListEmptyState.tsx
  src/app/Scenes/ArtworkList/ArtworkListTitle.tsx
  src/app/Scenes/ArtworkLists/ArtworkListItem.tsx
  src/app/Scenes/ArtworkLists/ArtworkLists.tsx
  src/app/Scenes/ArtworkLists/SavesTabHeader.tsx
  src/app/Scenes/SellWithArtsy/index.tests.tsx
Labels: Jira Synced

#10014 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green
