Repository artsy/eigen, pull requests merged in 2024-10, with the labels that each got.

#10872 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10874 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10866 chore: remove artwork size prop from Auction Lots For You rail
  src/app/Scenes/Home/Components/RecommendedAuctionLotsRail.tsx
  src/app/Scenes/Home/Home.tsx
  src/app/Scenes/Sales/Sales.tsx
Labels: Jira Synced

#10875 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10877 fix: use inquire copy for sales rail
  src/app/Scenes/Sale/BuyNowArtworksRail.tests.tsx
  src/app/Scenes/Sale/Components/BuyNowArtworksRail.tsx
  src/app/Scenes/Sale/Components/NewBuyNowArtworksRail.tests.tsx
  src/app/Scenes/Sale/Components/NewBuyNowArtworksRail.tsx
Labels: Jira Synced, Squash On Green

#10870 fix(HomeView): ensure consistent highlight opacity for articles rail
  src/app/Components/ArticleCard.tests.tsx
  src/app/Components/ArticleCard.tsx
Labels: Squash On Green

#10861 feat(DIA-896): add an auth model method to identify email addresses
  src/app/Components/ArtsyWebView.tests.tsx
  src/app/store/AuthModel.ts
  src/app/store/GlobalStore.tsx
  src/app/store/__tests__/AuthModel.tests.ts
  src/setupJest.tsx
Labels: Jira Synced

#10746 feat(DIA-785): fuse signup and login flows into a single user experience
  src/app/Components/Recaptcha/RecaptchaWebView.tsx
  src/app/Scenes/Onboarding/AuthenticationDialog/AuthenticationDialog.tsx
  src/app/Scenes/Onboarding/AuthenticationDialog/EmailStep.tsx
  src/app/Scenes/Onboarding/AuthenticationDialog/ForgotPasswordStep.tsx
  src/app/Scenes/Onboarding/AuthenticationDialog/LoginOTPStep.tsx
  src/app/Scenes/Onboarding/AuthenticationDialog/LoginPasswordStep.tsx
  src/app/Scenes/Onboarding/AuthenticationDialog/SignUpNameStep.tsx
  src/app/Scenes/Onboarding/AuthenticationDialog/SignUpPasswordStep.tsx
  src/app/Scenes/Onboarding/AuthenticationDialog/WelcomeStep.tsx
  src/app/Scenes/Onboarding/Onboarding.tsx
  src/app/Scenes/Onboarding/OnboardingHome.tsx
  src/app/store/config/features.ts
Labels: Jira Synced

#10882 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10892 fix(home view): status bar safe area
  src/app/Scenes/HomeView/Components/HomeHeader.tsx
  src/app/Scenes/HomeView/HomeView.tsx
Labels: Jira Synced

#10895 refactor(auth2): More smoothing out of auth screens
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormArtist.tsx
  src/app/Scenes/Onboarding/Auth2/AuthContext.tsx
  src/app/Scenes/Onboarding/Auth2/AuthScenes.tsx
  src/app/Scenes/Onboarding/Auth2/__tests__/AuthApp.test.tsx
  src/app/Scenes/Onboarding/Auth2/__tests__/AuthContext.test.tsx
  src/app/Scenes/Onboarding/Auth2/__tests__/AuthScenes.test.tsx
  src/app/Scenes/Onboarding/Auth2/components/AuthModal.tsx
  src/app/Scenes/Onboarding/Auth2/components/__tests__/AuthScreen.test.tsx
  src/app/Scenes/Onboarding/Auth2/hooks/__tests__/useAuthNavigation.test.tsx
  src/app/Scenes/Onboarding/Auth2/hooks/useInputAutofocus.tsx
  src/app/Scenes/Onboarding/Auth2/scenes/ForgotPasswordStep.tsx
  src/app/Scenes/Onboarding/Auth2/scenes/LoginOTPStep.tsx
  src/app/Scenes/Onboarding/Auth2/scenes/LoginPasswordStep.tsx
  src/app/Scenes/Onboarding/Auth2/scenes/LoginWelcomeStep.tsx
  src/app/Scenes/Onboarding/Auth2/scenes/SignUpNameStep.tsx
  src/app/Scenes/Onboarding/Auth2/scenes/SignUpPasswordStep.tsx
  src/app/Scenes/Onboarding/Auth2/scenes/__tests__/ForgotPasswordStep.test.tsx
  src/app/Scenes/Onboarding/Auth2/scenes/__tests__/LoginOTPStep.test.tsx
  src/app/Scenes/Onboarding/Auth2/scenes/__tests__/LoginPasswordStep.test.tsx
  src/app/Scenes/Onboarding/Auth2/scenes/__tests__/LoginWelcomeStep.test.tsx
  src/app/Scenes/Onboarding/Auth2/scenes/__tests__/SignUpNameStep.test.tsx
  src/app/Scenes/Onboarding/Auth2/scenes/__tests__/SignUpPasswordStep.test.tsx
  src/app/Scenes/Onboarding/Auth2/utils/waitForSubmit.tsx
Labels: Squash On Green

#10879 feat(EMI-2095): Add Swipeable component
  src/app/Components/Swipeable/Swipeable.tests.tsx
  src/app/Components/Swipeable/Swipeable.tsx
Labels: Jira Synced, Squash On Green

#10897 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10884 fix: debounce push analytics call to avoid double tracking
  src/app/utils/PushNotification.ts
Labels: Jira Synced

#10898 fix(auth2): PR follow-ups
  src/app/Scenes/Onboarding/Auth2/components/AuthModal.tsx
Labels: Squash On Green

#10901 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10902 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10893 fix: fix placeholders on the new home view
  src/app/Components/SectionTitle.tsx
  src/app/Scenes/Home/Components/ShowsRail.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionActivity.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArticles.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArtists.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArtworks.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionAuctionResults.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionFairs.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionSales.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionShows.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionViewingRooms.tsx
Labels: Squash On Green

#10904 feat(DIA-898): use shared password field for sign-up and login [WIP]
  src/app/Scenes/Onboarding/Auth2/components/PasswordInput.tsx
  src/app/Scenes/Onboarding/Auth2/scenes/LoginPasswordStep.tsx
  src/app/Scenes/Onboarding/Auth2/scenes/SignUpPasswordStep.tsx
Labels: Jira Synced

#10824 feat(POC): add error boundary to withSuspense
  package.json
  src/app/Components/WorksForYouArtworks.tsx
  src/app/Scenes/Activity/ActivityItemScreen.tsx
  src/app/Scenes/Activity/components/ActivityErrorScreen.tsx
  src/app/Scenes/Artwork/Components/ArtworkError.tsx
  src/app/Scenes/Artwork/Components/BrowseSimilarWorks/BrowseSimilarWorks.tsx
  src/app/Scenes/Artwork/Components/BrowseSimilarWorks/BrowseSimilarWorksContent.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionActivity.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArticles.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArticlesCards.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArtists.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArtworks.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionAuctionResults.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionDiscoverMarketingCollections.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionFairs.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionFeaturedCollection.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionGalleries.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionHeroUnits.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionMarketingCollections.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionSales.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionShows.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionViewingRooms.tsx
  src/app/Scenes/HomeViewSectionScreen/HomeViewSectionScreen.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/MyCollectionArtworkFormDeleteArtworkModal.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkEdit.tsx
  src/app/Scenes/MyCollection/Screens/CollectedArtistsPrivacy/MyCollectionCollectedArtistsPrivacy.tsx
  src/app/Scenes/MyProfile/MyProfileHeader.tsx
  src/app/Scenes/NewWorksFromGalleriesYouFollow/Components/NewWorksFromGalleriesYouFollow.tsx
  src/app/Scenes/RecentlyViewed/Components/RecentlyViewedArtworks.tsx
  src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterArtistSeries.tsx
  src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterPriceRange.tests.tsx
  src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterPriceRange.tsx
  src/app/Scenes/SavedSearchAlert/screens/AlertPriceRangeScreen.tsx
  src/app/Scenes/SavedSearchAlert/screens/ConfirmationScreen.tsx
  src/app/Scenes/SellWithArtsy/ArtworkForm/SubmitArtworkFormEdit.tsx
  src/app/utils/hooks/withSuspense.tsx
  test-patches/whatwg-fetch+3.0.0.patch
  yarn.lock
Labels: Jira Synced

#10907 feat: Add Task component
  src/app/Components/Tasks/Task.tests.tsx
  src/app/Components/Tasks/Task.tsx
Labels: Jira Synced

#10913 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10918 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10919 fix: Handle home screen network errors
  src/app/Scenes/HomeView/HomeView.tsx
Labels: Jira Synced

#10923 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10912 feat: Add swipe-to-interact functionality to `Swipeable` component
  src/app/Components/Swipeable/Swipeable.tsx
Labels: Jira Synced

#10927 fix(DiscoverSomethingNew): fix graphql type
  src/app/Scenes/HomeView/Sections/HomeViewSectionDiscoverMarketingCollections.tests.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionDiscoverMarketingCollections.tsx
  src/app/Scenes/HomeView/Sections/Section.tsx
  src/app/store/config/features.ts
Labels: Squash On Green

#10921 feat(DIA-902): login welcome step omnibus
  src/app/Scenes/Onboarding/Auth2/components/PasswordInput.tsx
  src/app/Scenes/Onboarding/Auth2/scenes/ForgotPasswordStep.tsx
  src/app/Scenes/Onboarding/Auth2/scenes/LoginOTPStep.tsx
  src/app/Scenes/Onboarding/Auth2/scenes/LoginPasswordStep.tsx
  src/app/Scenes/Onboarding/Auth2/scenes/LoginWelcomeStep.tsx
  src/app/Scenes/Onboarding/Auth2/scenes/SignUpNameStep.tsx
  src/app/Scenes/Onboarding/Auth2/scenes/SignUpPasswordStep.tsx
Labels: Squash On Green

#10929 chore: update glog and DoubleConversion pods
  ios/Podfile.lock
Labels: Squash On Green

#10911 chore(releases): add username to changelog
  docs/pull_request_template.md
  package.json
  scripts/changelog/generateChangelog.ts
  scripts/changelog/parsePRDescription.ts
  yarn.lock
Labels: Jira Synced, Squash On Green

#10886 feat(art advisor): introduce AREnableDynamicHomeView for M2
  docs/developing_a_feature.md
  src/app/Scenes/Home/HomeContainer.tests.tsx
  src/app/Scenes/Home/HomeContainer.tsx
  src/app/Scenes/HomeView/Components/AlphaVersionIndicator.tsx
  src/app/Scenes/HomeView/Components/HomeHeader.tsx
  src/app/store/config/features.ts
Labels: Jira Synced, Squash On Green, Art Advisor

#10935 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10932 feat: add email confirmation banner to new HomeView
  src/app/Scenes/HomeView/HomeView.tests.tsx
  src/app/Scenes/HomeView/HomeView.tsx
Labels: Art Advisor

#10922 feat(home view): support a singular Card section and deprecate the current Galleries section component
  data/schema.graphql
  src/app/Scenes/HomeView/Sections/HomeViewSectionCard.tests.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionCard.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionGalleries.tests.tsx
  src/app/Scenes/HomeView/Sections/Section.tsx
Labels: Jira Synced, Art Advisor

#10939 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10940 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10931 fix: Make RetryErrorBoundary work with useLazyLoadQuery
  src/app/Components/RetryErrorBoundary.tsx
  src/app/Scenes/HomeView/HomeView.tsx
Labels: Jira Synced, Squash On Green, Art Advisor

#10914 feat(DIA-882): add explore by categories to the home view
  src/app/AppRegistry.tsx
  src/app/Scenes/CollectionsByCategory/CollectionsByCategory.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionCards.tests.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionCards.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionDiscoverMarketingCollections.tests.tsx
  src/app/Scenes/HomeView/Sections/Section.tsx
  src/app/routes.ts
Labels: Jira Synced, Art Advisor

#10944 fix: show images low quality
  src/app/Components/ShowCard.tsx
Labels: Art Advisor

#10937 refactor: unable to load screen to add tracking for screens
  src/app/Components/LoadFailureView.tsx
Labels: Jira Synced

#10945 fix: shows for you rail broken padding
  src/app/Scenes/Home/Components/ShowsRail.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionShows.tsx
Labels: Art Advisor

#10952 feat: ensure a max of 2 lines for activity rail items
  src/app/Scenes/Home/Components/ActivityRailItem.tests.tsx
  src/app/Scenes/Home/Components/ActivityRailItem.tsx
Labels: Art Advisor

#10955 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10951 fix: keep splash screen visible for 500ms
  src/app/utils/useHideSplashScreen.ts
Labels: Squash On Green

#10957 feat(HomeView): add chips to discover something new
  src/app/Components/Chip.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionCardsChips.tsx
  src/app/Scenes/HomeView/Sections/Section.tsx
  src/app/Scenes/HomeView/Sections/__tests__/HomeViewSectionCardsChips.tests.tsx
  src/app/Scenes/HomeView/Sections/__tests__/HomeViewSectionDiscoverMarketingCollections.tests.tsx
Labels: Jira Synced, Art Advisor

#10956 feat: Improve swipeable task animation
  src/app/Components/Swipeable/Swipeable.tests.tsx
  src/app/Components/Swipeable/Swipeable.tsx
  src/app/Components/Tasks/Task.tsx
Labels: Jira Synced

#10962 fix: Swipeable action color definition
  src/app/Components/Swipeable/Swipeable.tsx
  src/app/Components/Tasks/Task.tsx
Labels: Squash On Green

#10963 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10964 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10959 fix(EMI-2122): Fix padding issue in collector signals in Artwork Details screen
  src/app/Scenes/Artwork/Components/ArtworkDetailsCollectorSignal.tsx
Labels: Jira Synced

#10968 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10970 feat(DIA-931): implement the chips and footer of collections by category screen
  src/app/Scenes/CollectionsByCategory/Body.tsx
  src/app/Scenes/CollectionsByCategory/CollectionsByCategory.tsx
  src/app/Scenes/CollectionsByCategory/CollectionsChips.tsx
  src/app/Scenes/CollectionsByCategory/Footer.tsx
  src/app/Scenes/CollectionsByCategory/__tests__/CollectionsChips.tests.tsx
  src/app/Scenes/CollectionsByCategory/__tests__/Footer.tests.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionCards.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionCardsChips.tsx
  src/app/Scenes/HomeView/Sections/__tests__/HomeViewSectionCards.tests.tsx
  src/app/utils/hooks/withSuspense.tsx
Labels: Jira Synced

#10979 chore: remove sentry bootstrap environment
  index-common.js
  src/app/system/errorReporting/setupSentry.ts
Labels: Jira Synced

#10982 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10981 chore: remove maestro cloud upload workflows
  .circleci/config.yml
  scripts/maestro/build-android.sh
  scripts/maestro/build-ios.sh
  scripts/maestro/run-android-nightly.sh
  scripts/maestro/run-ios-nightly.sh
Labels: Jira Synced

#10978 fix(DIA-815): add AuthImpression and ResetYourPassword events (and more!)
  src/app/Scenes/Onboarding/Auth2/components/AuthModal.tsx
  src/app/Scenes/Onboarding/Auth2/hooks/useOnboardingAuth2Tracking.tsx
  src/app/Scenes/Onboarding/Auth2/scenes/ForgotPasswordStep.tsx
  src/app/Scenes/Onboarding/OnboardingCreateAccount/EmailSubscriptionCheckbox.tsx
  src/app/store/AuthModel.ts
Labels: Jira Synced

#10983 chore: util script for exporting notion cards to jira
  package.json
  scripts/utils/exportNotionTicketsToJira.ts
Labels: Squash On Green

#10984 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10990 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10987 fix: Track Activity item screen event correctly
  src/app/Scenes/Activity/ActivityItemScreen.tsx
Labels: Jira Synced

#10991 feat(EMI-2147): Acknowledge tasks when tapping on them
  src/app/Components/Tasks/Task.tests.tsx
  src/app/Components/Tasks/Task.tsx
  src/app/utils/mutations/useAcknowledgeTask.ts
Labels: Jira Synced

#10994 feat: Update Danger's changelog message in PRs
  dangerfile.ts
Labels: Squash On Green

#10989 feat(DIA-931): add collection artwork rails
  src/app/Components/ArtworkRail/ArtworkRail.tsx
  src/app/Scenes/CollectionsByCategory/Body.tsx
  src/app/Scenes/CollectionsByCategory/CollectionRail.tsx
  src/app/Scenes/CollectionsByCategory/__tests__/Body.tests.tsx
  src/app/Scenes/CollectionsByCategory/__tests__/CollectionRail.tests.tsx
  src/app/Scenes/Home/Home.tsx
Labels: Jira Synced, Art Advisor

#10998 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10999 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11000 feat(EMI-2098): Add tracking for Tasks
  src/app/Components/Tasks/Task.tests.tsx
  src/app/Components/Tasks/Task.tsx
  src/app/Scenes/HomeView/Sections/__tests__/HomeViewSectionTasks.tests.tsx
  src/app/Scenes/HomeView/useHomeViewTracking.ts
Labels: Jira Synced, Squash On Green

#11003 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11001 chore: update unable to load tracking - send screen message if screen present, tab otherwise
  src/app/Components/LoadFailureView.tsx
Labels: Jira Synced

#11012 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11018 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11015 fix(ONYX-1375): fix SellWithArtsyRecentlySold Rail layout
  src/app/Scenes/SellWithArtsy/Components/SellWithArtsyRecentlySold.tsx
Labels: Jira Synced, Squash On Green

#11005 feat(ONYX-1294): redesign badges and urgency signals on artwork card
  .secrets.baseline
  src/app/Components/ArtworkGrids/ArtworkGridItem.tests.tsx
  src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
  src/app/Components/ArtworkGrids/ArtworkSocialSignal.tsx
  src/app/Components/ArtworkRail/ArtworkRailCard.tests.tsx
  src/app/Components/ArtworkRail/ArtworkRailCardMeta.tsx
  src/app/Components/ArtworkRail/ArtworkRailUtils.tsx
  src/app/Components/ArtworkRail/ArtworkSaleMessage.tsx
  src/app/Components/ContextMenu/ContextMenuArtworkPreviewCard.tsx
  src/app/Components/ContextMenu/ContextMenuArtworkPreviewCardImage.tsx
  src/app/Scenes/Artwork/Components/ArtworkDetailsCollectorSignal.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkList/MyCollectionArtworkGridItem.tests.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkList/MyCollectionArtworkGridItem.tsx
  src/app/utils/getSaleMessgeOrBidInfo.ts
Labels: Jira Synced

#10993 fix(feature): rendering of associated set's markdown
  src/app/Scenes/Feature/Feature.tsx
Labels: Jira Synced

#11016 fix: design QA fixes omnibus
  src/app/Components/Recaptcha/Recaptcha.tsx
  src/app/Scenes/Onboarding/Auth2/components/AuthModal.tsx
  src/app/Scenes/Onboarding/Auth2/scenes/ForgotPasswordStep.tsx
  src/app/Scenes/Onboarding/Auth2/scenes/LoginWelcomeStep.tsx
Labels: Jira Synced

#11019 feat(ExploreBy): fix and add missing tracking
  src/app/Scenes/CollectionsByCategory/CollectionRail.tsx
  src/app/Scenes/CollectionsByCategory/CollectionsByCategory.tsx
  src/app/Scenes/CollectionsByCategory/CollectionsChips.tsx
  src/app/Scenes/CollectionsByCategory/__tests__/CollectionRail.tests.tsx
  src/app/Scenes/CollectionsByCategory/__tests__/CollectionsChips.tests.tsx
  src/app/Scenes/CollectionsByCategory/hooks/useCollectionByCategoryTracking.ts
  src/app/Scenes/HomeView/Sections/HomeViewSectionCards.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionCardsChips.tsx
  src/app/Scenes/HomeView/Sections/__tests__/HomeViewSectionCards.tests.tsx
  src/app/Scenes/HomeView/useHomeViewTracking.ts
  src/app/store/config/features.ts
Labels: Jira Synced, Squash On Green, Art Advisor

#11022 chore: Add screen tracking to Saves screen
  src/app/Scenes/SavedArtworks/SavedArtworks.tsx
Labels: Jira Synced

#11024 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11020 feat(DIA-927): conditionally display email enrollment checkbox during sign-up
  e2e/flows/onboarding/signup.yml
  src/app/Scenes/Onboarding/Auth2/hooks/useCountryCode.tsx
  src/app/Scenes/Onboarding/Auth2/scenes/SignUpNameStep.tsx
  src/app/Scenes/Onboarding/Auth2/scenes/__tests__/SignUpNameStep.test.tsx
  src/app/Scenes/Onboarding/Auth2/scenes/__tests__/SignUpNameStep.tests.tsx
  src/app/Scenes/Onboarding/OnboardingCreateAccount/EmailSubscriptionCheckbox.tsx
  src/app/Scenes/Onboarding/OnboardingCreateAccount/TermsOfServiceCheckbox.tsx
Labels: Jira Synced

#11011 fix: StatusBar fixes
  src/app/Scenes/Home/HomeContainer.tsx
  src/app/Scenes/Onboarding/OnboardingWelcome.tsx
  src/app/utils/useAndroidAppStyling.ts
Labels: Jira Synced

#11039 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11031 feat(EMI-2146): Add Task onboarding animation
  HACKS.md
  patches/react-native-gesture-handler+2.19.0.patch
  src/app/Components/Swipeable/Swipeable.tsx
  src/app/Components/Tasks/Task.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionTasks.tsx
  src/app/store/ProgressiveOnboardingModel.ts
Labels: Jira Synced

#11035 fix: unable to load fixes
  src/app/Components/ErrorView/SimpleErrorMessage.tsx
  src/app/Scenes/HomeView/HomeView.tsx
  src/app/Scenes/Inbox/Screens/Conversation.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormArtist.tsx
  src/app/Scenes/Search/SearchArtworksContainer.tests.tsx
  src/app/Scenes/Search/SearchArtworksContainer.tsx
  src/app/Scenes/Search/components/EntitySearchResults.tsx
Labels: Jira Synced

#11040 feat(CollectionsByCategory): collections ordering
  src/app/Scenes/CollectionsByCategory/Body.tsx
Labels: Squash On Green, Art Advisor

#11043 feat(gap): replace gap calls with our spacing tokens
  package.json
  src/app/Components/ArtworkRail/ArtworkRail.tsx
  src/app/Components/Bidding/Screens/CreditCardForm.tsx
  src/app/Components/Stack.tsx
  src/app/Scenes/Activity/ActivityEmptyView.tsx
  src/app/Scenes/Activity/components/NotificationCommercialButtons.tsx
  src/app/Scenes/Articles/News/ArticlesCards.tsx
  src/app/Scenes/CollectionsByCategory/Body.tsx
  src/app/Scenes/CollectionsByCategory/CollectionsByCategory.tsx
  src/app/Scenes/CollectionsByCategory/CollectionsChips.tsx
  src/app/Scenes/CollectionsByCategory/Footer.tsx
  src/app/Scenes/CompleteMyProfile/ChangesSummary.tsx
  src/app/Scenes/CompleteMyProfile/Header.tsx
  src/app/Scenes/CompleteMyProfile/IdentityVerificationStep.tsx
  src/app/Scenes/CompleteMyProfile/ImageSelector.tsx
  src/app/Scenes/Fair/Fair.tsx
  src/app/Scenes/Fair/FairOverview.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArticlesCards.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionCards.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionArtistsPrompt/MyCollectionArtistsAutosuggest.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionArtistsPrompt/MyCollectionArtistsAutosuggestItem.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionArtistsPrompt/MyCollectionArtistsPrompt.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionArtistsPrompt/MyCollectionArtistsPromptFooter.tsx
  src/app/Scenes/MyProfile/Components/UserProfileFields.tsx
  src/app/Scenes/MyProfile/MyProfileEditForm.tsx
  src/app/Scenes/MyProfile/MyProfileHeader.tsx
  src/app/Scenes/SavedArtworks/SavedArtworks.tsx
  src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkAdditionalDocuments.tsx
  src/app/Scenes/SellWithArtsy/SubmitArtwork/UploadPhotos/UploadPhotosForm.tsx
  yarn.lock
Labels: Squash On Green

#11044 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11045 fix: Missing artwork ID in SWA My Collection flow
  src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkFromMyCollectionArtworks.tsx
  src/app/Scenes/SellWithArtsy/ArtworkForm/Components/__tests__/SubmitArtworkFromMyCollection.tests.tsx
Labels: Jira Synced, Squash On Green

#11046 fix: Missing artwork ID in My Collection Submit for Sale flow
  src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionWhySell.tests.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionWhySell.tsx
  src/app/Scenes/SellWithArtsy/ArtworkForm/Components/SubmitArtworkFromMyCollectionArtworks.tsx
Labels: Jira Synced

#11047 fix: partner name android not truncated properly
  src/app/Components/ArtworkRail/ArtworkRailCardMeta.tsx
Labels: Jira Synced
