Repository artsy/eigen, pull requests merged in 2024-12, with the labels that each got.

#11230 chore: prep for 8.58.0
  app.json
Labels: Squash On Green

#11234 build(deps): bump react-native-image-crop-picker from 0.41.2 to 0.41.6
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: Squash On Green

#11233 fix: Add bottom padding to search results
  src/app/Scenes/Search/components/EntitySearchResults.tsx
Labels: Jira Synced

#11236 fix: react-native-image-crop-picker patch version
  patches/react-native-image-crop-picker+0.41.6.patch
Labels: Squash On Green

#11235 chore: improve tab press event performance
  src/app/Navigation/AuthenticatedRoutes/Tabs.tsx
Labels: Squash On Green

#11239 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11096 feat(perf): search perf
  src/app/Components/AutosuggestResults/AutosuggestResults.tests.tsx
  src/app/Components/AutosuggestResults/AutosuggestResults.tsx
  src/app/Components/InfiniteScrollFlashList.tsx
  src/app/Scenes/Search/components/EntitySearchResults.tsx
Labels: Jira Synced, Squash On Green

#11241 fix(deeplinks): fix deeplinks from killed state on iOS 17
  src/app/Navigation/Navigation.tsx
  src/app/store/GlobalStoreModel.ts
  src/app/system/navigation/ModalStack.tsx
Labels: Jira Synced

#10961 feat: Implement Home view tasks section list
  src/app/Components/Swipeable/Swipeable.tsx
  src/app/Components/Tasks/Task.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionTasks.tsx
  src/app/Scenes/HomeView/Sections/__tests__/HomeViewSectionTasks.tests.tsx
Labels: Jira Synced

#11243 fix: NSInternalInconsistencyException sentry crash iOS 17
  HACKS.md
  ios/Podfile.lock
  package.json
  patches/react-native-fast-image+8.6.3.patch
  yarn.lock
Labels: Jira Synced, Squash On Green

#11244 chore(ONYX-1426): remove AREnableSubmitArtworkTier2Information ff related logic
  src/app/Scenes/MyCollection/Screens/Artwork/ArtworkSubmissionStatusFAQ.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionArtworkHeader.tests.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionArtworkHeader.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionArtworkSubmissionStatus.tests.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionArtworkSubmissionStatus.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtworkInsights.tests.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtworkInsights.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkList/MyCollectionArtworkGridItem.tsx
  src/app/store/config/features.ts
Labels: Jira Synced

#11251 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11252 feat: Automatically opt into sharing collected artists with galleries and layout fix
  src/app/Scenes/MyCollection/Screens/MyCollectionAddCollectedArtists/MyCollectionAddCollectedArtists.tests.tsx
  src/app/Scenes/MyCollection/Screens/MyCollectionAddCollectedArtists/MyCollectionAddCollectedArtists.tsx
  src/app/Scenes/MyCollection/Screens/MyCollectionAddCollectedArtists/MyCollectionAddCollectedArtistsAutosuggest.tsx
  src/app/Scenes/MyCollection/hooks/useAddUserInterestArtists.ts
Labels: Jira Synced, Squash On Green

#11253 fix: erroneous char in devmenu #trivial
  src/app/system/devTools/DevMenu/DevMenu.tsx
Labels: Squash On Green

#11246 chore: better screens definition
  src/app/App.tsx
  src/app/AppRegistry.tsx
  src/app/Navigation/AuthenticatedRoutes/HomeTab.tsx
  src/app/Navigation/AuthenticatedRoutes/InboxTab.tsx
  src/app/Navigation/AuthenticatedRoutes/ProfileTab.tsx
  src/app/Navigation/AuthenticatedRoutes/SearchTab.tsx
  src/app/Navigation/AuthenticatedRoutes/SellTab.tsx
  src/app/Navigation/AuthenticatedRoutes/SharedRoutes.tsx
  src/app/Navigation/AuthenticatedRoutes/Tabs.tsx
  src/app/Navigation/AuthenticatedRoutes/modalRoutes.tsx
  src/app/Navigation/AuthenticatedRoutes/sharedRoutes.tsx
  src/app/system/ignoreLogs.ts
Labels: Jira Synced

#11255 fix: screen presentation issues
  src/app/Navigation/AuthenticatedRoutes/StackNavigator.tsx
Labels: Squash On Green

#11257 chore: remove image resize requests on already resized images
  src/app/Components/ArtworkLists/components/ArtworkListImage.tsx
  src/app/Scenes/Activity/ActivityItemArtworksGrid.tsx
  src/app/Scenes/Artwork/Components/ImageCarousel/FullScreen/ImageZoomViewAndroid.tsx
  src/app/Scenes/Artwork/Components/ImageCarousel/ImageWithLoadingState.tsx
  src/app/Scenes/HomeView/Components/ArtistRails/ArtistCard.tsx
  src/app/Scenes/OrderHistory/OrderHistoryRow.tsx
Labels: Jira Synced

#11261 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11248 feat(DIA-1014): create an entry point for infinite discovery
  src/app/AppRegistry.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionCard.tsx
  src/app/Scenes/HomeView/Sections/__tests__/HomeViewSectionCard.tests.tsx
  src/app/Scenes/HomeView/Sections/__tests__/Section.tests.tsx
  src/app/Scenes/InfiniteDiscovery/InfiniteDiscovery.tsx
  src/app/Scenes/InfiniteDiscovery/InfiniteDiscoveryContext.ts
  src/app/Scenes/InfiniteDiscovery/__tests__/InfiniteDiscovery.tests.tsx
  src/app/Scenes/InfiniteDiscovery/__tests__/InfiniteDiscoveryContext.tests.tsx
  src/app/routes.ts
  src/app/store/config/features.ts
Labels: Jira Synced

#11266 fix: conversation screen padding
  src/app/Scenes/Inbox/Screens/Conversation.tsx
Labels: Squash On Green

#11268 fix: city guide warnings
  src/app/Scenes/Map/GlobalMap.tsx
Labels: Jira Synced

#11260 fix(EMI-2227): Attempt to fix tasks animation sluggishness
  src/app/Scenes/HomeView/Sections/HomeViewSectionTasks.tsx
Labels: Jira Synced

#11271 fix: telegram sharing
  ios/Artsy/App_Resources/Info.plist
  src/app/Components/ShareSheet/ShareSheet.tsx
Labels: Jira Synced

#11262 fix: hide header on art quiz
  src/app/AppRegistry.tsx
Labels: Squash On Green

#11265 fix: prefer canonical artist bio on artwork screen
  src/app/Scenes/Artwork/Components/AboutArtist.tsx
Labels: Jira Synced

#11273 chore: wrap individual screens with error boundary
  src/app/Components/NotFoundFailureView.tsx
  src/app/Navigation/AuthenticatedRoutes/StackNavigator.tsx
Labels: Squash On Green

#11275 fix(EMI-2201): fix sending multiple analytics events on task swipe
  src/app/Components/Swipeable/Swipeable.tsx
Labels: Jira Synced

#11274 fix: broken photo picker padding, remove excluded_arch flags
  .circleci/config.yml
  ios/Artsy.xcodeproj/project.pbxproj
  ios/ArtsyTests/ReferenceImages/ARAugmentedVIRViewControllerSpec/defaults_to_showing_info.png
  ios/ArtsyTests/ReferenceImages/ARAugmentedVIRViewControllerSpec/shows_the_right_info_when_a_wall_is_registered.png
  ios/ArtsyTests/ReferenceImages/ARAugmentedVIRViewControllerSpec/shows_the_right_info_when_an_artwork_was_placed.png
  ios/ArtsyTests/ReferenceImages/ARNavigationButtonSpecSpec/ARNavigationButton_default_border_really_long_title_and_subtitle.png
  ios/ArtsyTests/ReferenceImages/ARNavigationButtonSpecSpec/ARNavigationButton_default_border_really_long_title_and_subtitle@3x.png
  ios/ArtsyTests/ReferenceImages/ARNavigationButtonSpecSpec/ARSerifNavigationButton_really_long_title_and_subtitle.png
  ios/ArtsyTests/ReferenceImages/ARNavigationButtonSpecSpec/ARSerifNavigationButton_really_long_title_and_subtitle@3x.png
  ios/ArtsyTests/ReferenceImages/ARNavigationButtonSpecSpec/navigationButtonWithTitle.png
  ios/ArtsyTests/ReferenceImages/ARNavigationButtonSpecSpec/navigationButtonWithTitle@3x.png
  ios/ArtsyTests/ReferenceImages/ARNavigationButtonSpecSpec/navigationButtonWithTitleAnd5pxBorder.png
  ios/ArtsyTests/ReferenceImages/ARNavigationButtonSpecSpec/navigationButtonWithTitleAnd5pxBorder@3x.png
  ios/ArtsyTests/ReferenceImages/ARNavigationButtonSpecSpec/navigationButtonWithTitleAndNoBorder.png
  ios/ArtsyTests/ReferenceImages/ARNavigationButtonSpecSpec/navigationButtonWithTitleAndNoBorder@3x.png
  ios/ArtsyTests/ReferenceImages/ARNavigationButtonSpecSpec/navigationButtonWithTitleAndSubtitle.png
  ios/ArtsyTests/ReferenceImages/ARNavigationButtonSpecSpec/navigationButtonWithTitleAndSubtitle@3x.png
  ios/ArtsyTests/ReferenceImages/ARNavigationButtonSpecSpec/navigationButtonWithTitleAndSubtitleAnd5pxBorder.png
  ios/ArtsyTests/ReferenceImages/ARNavigationButtonSpecSpec/navigationButtonWithTitleAndSubtitleAnd5pxBorder@3x.png
  ios/ArtsyTests/ReferenceImages/ARNavigationButtonSpecSpec/navigationButtonWithTitleAndSubtitleAndNoBorder.png
  ios/ArtsyTests/ReferenceImages/ARNavigationButtonSpecSpec/navigationButtonWithTitleAndSubtitleAndNoBorder@3x.png
  ios/ArtsyTests/ReferenceImages/ARNavigationButtonSpecSpec/serifNavigationButtonWithTitle.png
  ios/ArtsyTests/ReferenceImages/ARNavigationButtonSpecSpec/serifNavigationButtonWithTitle@3x.png
  ios/ArtsyTests/ReferenceImages/ARNavigationButtonSpecSpec/serifNavigationButtonWithTitleAndSubtitle.png
  ios/ArtsyTests/ReferenceImages/ARNavigationButtonSpecSpec/serifNavigationButtonWithTitleAndSubtitle@3x.png
  ios/ArtsyTests/ReferenceImages/ARSerifNavigationViewControllerSpec/_handles_the_fake_navigation_close_button_correctly.png
  ios/ArtsyTests/ReferenceImages/AuctionInformationViewControllerTests/a_closed_sale__shows_the_sale_is_closed@3x.png
  ios/ArtsyTests/ReferenceImages/AuctionLotMetadataStackScrollViewTests/looks_as_expected_when_small@3x.png
  ios/ArtsyTests/ReferenceImages/AuctionLotMetadataStackScrollViewTests/looks_right_when_expanded@3x.png
  ios/ArtsyTests/ReferenceImages/LiveAuctionBidButtonTests/has_valid_snapshot_passed@3x.png
  ios/ArtsyTests/ReferenceImages/LiveAuctionLoadingViewSpec/looks_good_by_default@3x.png
  ios/ArtsyTests/ReferenceImages/SaleOnHoldOverlayViewTests/looks_right_by_default_on_iPad@3x.png
  ios/ArtsyTests/ReferenceImages/SaleOnHoldOverlayViewTests/looks_right_with_a_custom_message_on_iPad@3x.png
  ios/Podfile
  ios/Podfile.lock
Labels: Jira Synced

#11264 chore: cleanup images, officially retire OpaqueImageView
  src/app/Components/ArticleCard.tsx
  src/app/Components/Artist/ArtistShows/ArtistShow.tsx
  src/app/Components/ArtistAutosuggest/ArtistAutosuggestRow.tsx
  src/app/Components/ArtworkLists/components/ArtworkListImage.tsx
  src/app/Components/Cards/MediumCard.tsx
  src/app/Components/Lists/SavedItemRow.tsx
  src/app/Components/Lists/ShowItemRow.tsx
  src/app/Components/OpaqueImageView/OpaqueImageView.tsx
  src/app/Components/OpaqueImageView/createGeminiUrl.tsx
  src/app/Components/OpaqueImageView2/OpaqueImageView2.tsx
  src/app/Components/OpaqueImageView2/index.ts
  src/app/Components/RelatedArtists/RelatedArtist.tsx
  src/app/Components/SaleArtworkTileRailCard/SaleArtworkTileRailCard.tests.tsx
  src/app/Components/SaleArtworkTileRailCard/SaleArtworkTileRailCard.tsx
  src/app/Components/ShowCard.tsx
  src/app/Components/ThreeUpImageLayout.tsx
  src/app/Components/Toast/ToastComponent.tsx
  src/app/Scenes/ArtistSeries/ArtistSeriesHeader.tsx
  src/app/Scenes/ArtistSeries/ArtistSeriesListItem.tests.tsx
  src/app/Scenes/ArtistSeries/ArtistSeriesListItem.tsx
  src/app/Scenes/Artwork/Components/ImageCarousel/FullScreen/DeepZoom/DeepZoomTile.tsx
  src/app/Scenes/Artwork/Components/ImageCarousel/FullScreen/ImageZoomView.tsx
  src/app/Scenes/Artwork/Components/ImageCarousel/ImageCarousel.tsx
  src/app/Scenes/City/Components/FairEventSection/Components/FairEventSectionCard.tsx
  src/app/Scenes/City/Components/TabFairItemRow/index.tsx
  src/app/Scenes/Collection/Components/CollectionHubsRails/ArtistSeries/CollectionArtistSeriesRail.tests.tsx
  src/app/Scenes/Collection/Components/CollectionHubsRails/FeaturedCollections/FeaturedCollectionsRail.tsx
  src/app/Scenes/Collection/Screens/CollectionHeader.tests.tsx
  src/app/Scenes/Collection/Screens/CollectionHeader.tsx
  src/app/Scenes/Fair/Components/FairEditorial.tsx
  src/app/Scenes/Fair/FairArticles.tsx
  src/app/Scenes/Feature/components/FeatureFeaturedLink.tsx
  src/app/Scenes/Feature/components/FeatureHeader.tsx
  src/app/Scenes/GalleriesForYou/Components/PartnerListItem.tsx
  src/app/Scenes/HomeView/Components/ArtistRails/ArtistCard.tsx
  src/app/Scenes/Inbox/Components/ActiveBids/ActiveBid.tsx
  src/app/Scenes/Inbox/Components/Conversations/ConversationSnippet.tsx
  src/app/Scenes/Inbox/Components/Conversations/ItemArtwork.tsx
  src/app/Scenes/Inbox/Components/Conversations/ItemShow.tsx
  src/app/Scenes/Inbox/Components/Conversations/Preview/Attachment/ImagePreview.tsx
  src/app/Scenes/MyBids/Components/Lot.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionImageView.tsx
  src/app/Scenes/MyCollection/Screens/Insights/ArtistItem.tsx
  src/app/Scenes/MyCollection/Screens/Insights/MedianAuctionPriceListItem.tsx
  src/app/Scenes/MyCollection/Screens/Insights/MedianSalePriceAtAuction.tsx
  src/app/Scenes/Sale/Components/SaleArtworkListItem.tsx
  src/app/Scenes/Sale/Components/SaleHeader.tsx
  src/app/Scenes/Sales/Components/SaleListItem.tsx
  src/app/Scenes/Search/components/SearchResultImage.tsx
  src/app/Scenes/Search/components/TrendingArtistCard.tsx
  src/app/Scenes/Show/Components/ShowContextCard.tsx
  src/app/Scenes/Show/Components/ShowInstallShots.tsx
  src/app/Scenes/Show/ShowContextCard.tests.tsx
  src/app/Scenes/ViewingRoom/ViewingRoomArtworks.tsx
  src/app/store/config/features.ts
Labels: Jira Synced

#11279 fix: add back button to auction results screen
  src/app/Scenes/AuctionResults/AuctionResultsScreenWrapper.tsx
Labels: Squash On Green

#11276 fix: home view performance
  src/app/Components/ArtworkRail/ArtworkRail.tsx
  src/app/Components/Containers/Inbox.tsx
  src/app/Navigation/AuthenticatedRoutes/StackNavigator.tsx
  src/app/Scenes/Activity/Activity.tests.tsx
  src/app/Scenes/Articles/Articles.tests.tsx
  src/app/Scenes/HomeView/HomeView.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionActivity.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArticles.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArticlesCards.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArtists.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArtworks.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionAuctionResults.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionCard.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionCards.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionCardsChips.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionFairs.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionFeaturedCollection.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionHeroUnits.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionMarketingCollections.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionSales.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionShows.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionTasks.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionViewingRooms.tsx
  src/app/Scenes/MyProfile/MyProfile.tsx
  src/app/Scenes/Search/Search.tsx
  src/app/Scenes/SellWithArtsy/SubmitArtwork/UploadPhotos/utils/index.tsx
Labels: Squash On Green

#11281 chore(tools): skip pre-commit hook during merge
  .husky/pre-commit
Labels: Squash On Green

#11283 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11277 docs(home view): add note about user agent string
  src/app/store/GlobalStore.tsx
Labels: Squash On Green

#11286 fix: broken image layouts
  src/app/Scenes/City/Components/FairEventSection/Components/FairEventSectionCard.tsx
  src/app/Scenes/Inbox/Components/ActiveBids/ActiveBid.tsx
  src/app/Scenes/Inbox/Components/Conversations/ConversationSnippet.tsx
  src/app/Scenes/Inbox/Components/Conversations/Preview/Attachment/AttachmentPreview.tsx
  src/app/Scenes/Inbox/Components/Conversations/Preview/Attachment/ImagePreview.tsx
Labels: Jira Synced

#11282 feat: Modernize Info Button Bottom Sheets
  src/app/Components/Artist/ArtistInsights/ArtistInsightsAuctionResults.tests.tsx
  src/app/Components/Artist/ArtistInsights/ArtistInsightsAuctionResults.tsx
  src/app/Components/Artist/ArtistInsights/MarketStats.tsx
  src/app/Components/Bidding/Screens/BillingAddress.tsx
  src/app/Components/BottomSheet/AutomountedBottomSheetModal.tsx
  src/app/Components/Buttons/InfoButton.tests.tsx
  src/app/Components/Buttons/InfoButton.tsx
  src/app/Scenes/AuctionResult/AuctionResult.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkArtistMarket.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkDemandIndex.tsx
  src/app/Scenes/SavedSearchAlert/Components/Form.tsx
Labels: Squash On Green

#11291 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11256 feat: consolidate paths and screens
  docs/adding_a_new_route.md
  src/app/AppRegistry.tsx
  src/app/Components/ArtsyWebView.tsx
  src/app/Components/Toast/ToastComponent.tsx
  src/app/Navigation/AuthenticatedRoutes/HomeTab.tsx
  src/app/Navigation/AuthenticatedRoutes/InboxTab.tsx
  src/app/Navigation/AuthenticatedRoutes/ProfileTab.tsx
  src/app/Navigation/AuthenticatedRoutes/SearchTab.tsx
  src/app/Navigation/AuthenticatedRoutes/SellTab.tsx
  src/app/Navigation/AuthenticatedRoutes/StackNavigator.tsx
  src/app/Navigation/AuthenticatedRoutes/Tabs.tsx
  src/app/Navigation/AuthenticatedRoutes/modalRoutes.tsx
  src/app/Navigation/AuthenticatedRoutes/sharedRoutes.tsx
  src/app/Navigation/Utils/isModalScreen.tsx
  src/app/Navigation/routes.tests.ts
  src/app/Navigation/routes.tsx
  src/app/Navigation/utils/LargeHeaderView.tsx
  src/app/Navigation/utils/addRoute.ts
  src/app/Navigation/utils/getDomainMap.ts
  src/app/Navigation/utils/isModalScreen.tsx
  src/app/Navigation/utils/modules.ts
  src/app/Navigation/utils/useBottomTabsBadges.tests.ts
  src/app/Navigation/utils/useBottomTabsBadges.ts
  src/app/Scenes/Activity/utils/navigateToActivityItem.ts
  src/app/Scenes/HomeView/Components/ActivityRail.tsx
  src/app/Scenes/MyAccount/MyAccountEditEmail.tsx
  src/app/Scenes/MyAccount/MyAccountEditPassword.tsx
  src/app/Scenes/MyAccount/MyAccountEditPhone.tsx
  src/app/Scenes/MyProfile/MyProfileSettings.tsx
  src/app/Scenes/VanityURL/VanityURLPossibleRedirect.tsx
  src/app/routes.ts
  src/app/system/devTools/DevMenu/DevMenu.tsx
  src/app/system/navigation/navigate.ts
  src/app/system/navigation/utils/RouteMatcher.tests.ts
  src/app/system/navigation/utils/RouteMatcher.ts
  src/app/system/navigation/utils/getCurrentURL.ts
  src/app/system/navigation/utils/matchRoute.ts
  src/app/system/navigation/utils/replaceParams.ts
  src/app/system/relay/middlewares/cacheHeaderMiddleware.ts
  src/app/utils/hooks/useIsDeepLink.tests.ts
  src/app/utils/hooks/useIsDeepLink.ts
  src/app/utils/queryPrefetching.ts
Labels: Jira Synced

#11288 feat: Add prefetching capability to artwork grids
  src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
  src/app/store/config/features.ts
  src/app/utils/queryPrefetching.ts
Labels: Jira Synced

#11294 chore(ONYX-1433): add processing state to the images that do not have image path, enable Continue CTA
  src/app/Scenes/SellWithArtsy/ArtworkForm/Utils/validation.ts
  src/app/Scenes/SellWithArtsy/SubmitArtwork/UploadPhotos/UploadPhotosPhotoItem.tsx
Labels: Jira Synced

#11305 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11308 chore: preferred pattern for image tests #trivial #nochangelog
  src/app/Components/ImageWithFallback/ImageWithFallback.tests.tsx
Labels: Squash On Green

#11309 fix(APPLAUSE-6697021): auth2 back button double tap crash
  src/app/Scenes/Onboarding/Auth2/AuthContext.tsx
  src/app/Scenes/Onboarding/Auth2/__tests__/AuthContext.tests.tsx
Labels: Jira Synced

#11311 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11313 build(deps): bump fastlane deps
  Gemfile.lock
Labels: Squash On Green

#11314 fix: galleries for you fallback height
  src/app/Components/ImageWithFallback/ImageWithFallback.tests.tsx
  src/app/Components/ImageWithFallback/ImageWithFallback.tsx
  src/app/Scenes/GalleriesForYou/Components/PartnerListItem.tsx
Labels: Squash On Green

#11317 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11322 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11324 fix(tools): use session auth and reintroduce license check
  .circleci/config.yml
  fastlane/utility_fastlane.rb
  scripts/deploys/notify-if-new-license-agreement
Labels: Jira Synced

#11326 chore(cleanup): remove stale hacks entries
  HACKS.md
Labels: Squash On Green

#11325 feat(EMI-2217): Animate tasks on tap or clear
  HACKS.md
  patches/react-native-reanimated+3.16.3.patch
  src/app/Scenes/HomeView/Sections/HomeViewSectionTasks.tsx
Labels: Jira Synced

#11316 chore: upgrade react native to 0.76
  Gemfile
  Gemfile.lock
  android/app/src/main/java/net/artsy/app/MainApplication.kt
  android/build.gradle
  android/gradle.properties
  android/gradle/wrapper/gradle-wrapper.properties
  android/gradlew
  android/gradlew.bat
  ios/Artsy.xcodeproj/project.pbxproj
  ios/Podfile
  ios/Podfile.lock
  package.json
  patches/@react-native-community+cli-platform-ios+14.1.0.patch
  yarn.lock
Labels: Jira Synced

#11327 docs: update debugging doc links
  docs/debugging.md
Labels: Squash On Green

#11321 fix(ONYX-1442): adjust HomeViewSectionCard component for bigger screens
  src/app/Scenes/HomeView/Components/HeroUnit.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionCard.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionHeroUnits.tsx
Labels: Jira Synced

#11328 feat(ONYX-1458): add information and guidance to the saves, follows and alerts screens
  src/app/Components/Buttons/InfoButton.tsx
  src/app/Scenes/ArtworkLists/SavesTabHeader.tsx
  src/app/Scenes/Favorites/Favorites.tsx
  src/app/Scenes/SavedArtworks/SavedArtworks.tsx
  src/app/Scenes/SavedSearchAlertsList/Components/SavedSearchesList.tsx
Labels: Jira Synced
