Repository artsy/eigen, pull requests merged in 2024-01, with the labels that each got.

#9685 fix: broken tests careerhighlights
  src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightBottomSheet.tests.tsx
Labels: Jira Synced, Squash On Green

#9692 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9690 feat: New notification screen structure
  src/app/AppRegistry.tsx
  src/app/Scenes/Activity/ActivityItemScreen.tsx
  src/app/Scenes/Activity/components/AlertNotification.tsx
  src/app/Scenes/Activity/components/FollowNotification.tsx
Labels: Jira Synced

#9688 feat: Add new works for you screen + fixes
  src/app/AppRegistry.tsx
  src/app/Components/ArtworkRail/ArtworkRailCard.tsx
  src/app/Scenes/AuctionResults/AuctionResultsScreenWrapper.tsx
  src/app/Scenes/NewWorksForYou/Components/NewWorksForYouGrid.tests.tsx
  src/app/Scenes/NewWorksForYou/Components/NewWorksForYouGrid.tsx
  src/app/Scenes/NewWorksForYou/Components/NewWorksForYouHeader.tsx
  src/app/Scenes/NewWorksForYou/Components/NewWorksForYouList.tsx
  src/app/Scenes/NewWorksForYou/NewWorksForYou.tsx
  src/app/Scenes/Search/UserPrefsModel.tsx
  src/app/store/__tests__/migration.tests.ts
  src/app/store/config/features.ts
  src/app/store/migration.ts
Labels: Jira Synced

#9695 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9434 feat(onyx-355): Apply filters on artist artworks grid when opened via deep link
  src/app/Components/ArtworkFilter/ArtworkFilterHelpers.ts
  src/app/Components/ArtworkFilter/Filters/SingleSelectOption.tsx
  src/app/Components/ArtworkFilter/Filters/SortOptions.tests.tsx
  src/app/Components/ArtworkFilter/Filters/SortOptions.tsx
  src/app/Scenes/Artist/Artist.tsx
  src/app/Scenes/Artist/ArtistSavedSearch.tests.tsx
Labels: Jira Synced

#9697 refactor: adjust sentry alerts
  src/app/Scenes/BottomTabs/BottomTabsModel.ts
  src/app/system/relay/middlewares/simpleLoggerMiddleware.ts
Labels: Jira Synced

#9698 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9691 fix: extract artist series title for alert criteria pills
  src/app/Scenes/SavedSearchAlert/helpers.tests.ts
  src/app/Scenes/SavedSearchAlert/helpers.ts
  src/app/Scenes/SavedSearchAlert/pillExtractors.tests.ts
  src/app/Scenes/SavedSearchAlert/pillExtractors.ts
Labels: Jira Synced

#9701 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9686 feat(EMI-1604): Add header content in Saves tab
  src/app/Components/ArtworkLists/ArtworkListsContext.tests.tsx
  src/app/Components/ArtworkLists/ArtworkListsContext.tsx
  src/app/Components/ArtworkLists/types.ts
  src/app/Components/ProgressiveOnboarding/ProgressiveOnboardingSignalInterest.tests.tsx
  src/app/Components/ProgressiveOnboarding/ProgressiveOnboardingSignalInterest.tsx
  src/app/Scenes/ArtworkLists/ArtworkLists.tsx
  src/app/Scenes/ArtworkLists/SavesTabHeader.tsx
  src/app/store/ProgressiveOnboardingModel.ts
Labels: Jira Synced

#9707 fix(DIA-381): progressive onboarding blocking create alert button on Artist screen
  src/app/Components/Artist/ArtistArtworks/SavedSearchButtonV2.tsx
Labels: Jira Synced, Squash On Green

#9705 fix(ONYX-648): allow saving alerts after tapping on a suggested filter
  src/app/Scenes/SavedSearchAlert/Components/Form.tsx
  src/app/Scenes/SavedSearchAlert/Components/SavedSearchFilterPill.tsx
  src/app/Scenes/SavedSearchAlert/EditSavedSearchAlert.tests.tsx
  src/app/Scenes/SavedSearchAlert/SavedSearchAlertForm.tests.tsx
  src/app/Scenes/SavedSearchAlert/SavedSearchStore.tsx
Labels: Jira Synced

#9710 fix: refresh node_modules cache
  .circleci/config.yml
Labels: Squash On Green

#9711 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9715 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9717 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9718 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9719 chore: prep for version 8.31.0
  Gemfile.lock
  app.json
Labels: Squash On Green

#9716 feat(ONYX-620): Activity List: Implement management action sheet
  src/app/Scenes/Activity/Activity.tests.tsx
  src/app/Scenes/Activity/Activity.tsx
  src/app/Scenes/Activity/ActivityMarkAllAsReadSection.tsx
  src/app/Scenes/Activity/hooks/useMarkAllNotificationsAsRead.ts
Labels: Jira Synced, Squash On Green

#9720 feat(EMI-1603): Update Save Artwork flow to match the web
  src/app/Components/ArtworkLists/ArtworkListsContext.tsx
  src/app/Components/ArtworkLists/useArtworkListsToast.ts
  src/app/Components/ArtworkLists/useSaveArtworkToArtworkLists.ts
  src/app/Components/Toast/Toast.tests.tsx
  src/app/Components/Toast/ToastComponent.tsx
  src/app/Components/Toast/types.ts
  src/app/Scenes/Artwork/Components/ArtworkActions.tests.tsx
Labels: Jira Synced

#9721 fix: wrong artwork image flashing onScoll
  src/app/Scenes/NewWorksForYou/Components/NewWorksForYouList.tsx
Labels: Jira Synced, Squash On Green

#9725 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9724 chore: do not throttle experiment_viewed events
  docs/add_an_experiment.md
  src/app/utils/experiments/hooks.ts
  src/app/utils/experiments/reporter.ts
Labels: Jira Synced

#9727 feat(ONYX-651): Implement tracking events for NWFY
  src/app/Scenes/NewWorksForYou/NewWorksForYou.tsx
  src/app/store/config/features.ts
  src/app/utils/experiments/reporter.ts
Labels: Jira Synced, Squash On Green

#9728 feat(EMI-1606): Add partner offer banners for unavailable/expired offers
  src/app/Scenes/Artwork/Artwork.tsx
  src/app/Scenes/Artwork/ArtworkAuctionCreateAlertHeader.tsx
  src/app/Scenes/Artwork/Components/ArtworkHeader.tsx
  src/app/Scenes/Artwork/Components/ArtworkMessages.tsx
  src/app/Scenes/Artwork/Components/InstagramStoryViewShot.tsx
  src/app/Scenes/PartnerOffer/PartnerOfferContainer.tests.tsx
  src/app/Scenes/PartnerOffer/PartnerOfferContainer.tsx
Labels: Jira Synced

#9730 fix(EMI-1644): Update partner offer help link
  src/app/Scenes/ArtworkLists/SavesTabHeader.tsx
Labels: Jira Synced, Squash On Green

#9732 build(deps): bump react native and react native screens
  HACKS.md
  ios/Podfile.lock
  package.json
  patches/react-native+0.72.9.patch
  yarn.lock
Labels: Jira Synced

#9726 feat: Follow & Alert Notification Screen
  src/app/Scenes/Activity/ActivityItemScreen.tsx
  src/app/Scenes/Activity/components/AlertNotification.tsx
  src/app/Scenes/Activity/components/ArtworkPublishedNotification.tsx
  src/app/Scenes/Activity/components/FollowNotification.tsx
  src/app/Scenes/Activity/components/NotificationArtworkList.tsx
  src/app/Scenes/Activity/components/__tests__/AlertNotification.tests.tsx
  src/app/Scenes/Activity/components/__tests__/ArtworkPublishedNotification.tests.tsx
  src/app/Scenes/Activity/utils/getNotificationTitle.ts
Labels: Jira Synced

#9729 chore: Rename `activity` routes to `notifications`
  src/app/Scenes/Activity/ActivityItem.tsx
  src/app/Scenes/Home/Components/ActivityIndicator.tsx
  src/app/Scenes/Home/Components/ActivityRail.tests.tsx
  src/app/Scenes/Home/Components/ActivityRail.tsx
  src/app/Scenes/Home/Components/ActivityRailItem.tsx
  src/app/routes.ts
Labels: Jira Synced, Squash On Green

#9733 chore: cleanup prev map hackathon work
  android/app/src/main/AndroidManifest.xml
  src/app/AppRegistry.tsx
  src/app/Scenes/Map/NewMap.tsx
  src/app/routes.ts
Labels: hackathon

#9737 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9739 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9740 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9746 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9751 chore: enable new works for you screen feed for everyone
  src/app/store/config/features.ts
Labels: Squash On Green

#9722 chore: adjust toast placement on screens without tab bar
  src/app/Components/Toast/ToastComponent.tsx
Labels: Jira Synced

#9752 feat: Add partner offer notifications to the Activity rail
  src/app/Scenes/Activity/ActivityItem.tsx
  src/app/Scenes/Activity/components/ExpiresInTimer.tsx
  src/app/Scenes/Home/Components/ActivityRail.tsx
  src/app/Scenes/Home/Components/ActivityRailItem.tsx
  src/app/Scenes/Home/Home.tsx
Labels: Squash On Green

#9754 build(deps): bump @testing-library/react-native to 12.4.3
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: Squash On Green

#9756 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9748 feat(ONYX-619): implement filter pills
  package.json
  src/app/Scenes/Activity/Activity.tsx
  src/app/Scenes/Activity/ActivityContainer.tsx
  src/app/Scenes/Activity/ActivityEmptyView.tsx
  src/app/Scenes/Activity/ActivityItem.tests.tsx
  src/app/Scenes/Activity/ActivityItem.tsx
  src/app/Scenes/Activity/ActivityList.tsx
  src/app/Scenes/Activity/ActivityScreenStore.tsx
  src/app/Scenes/Activity/ActivityTabPlaceholder.tsx
  src/app/Scenes/Activity/NewActivityScreen.tsx
  src/app/Scenes/Activity/components/ExpiresInTimer.tsx
  src/app/Scenes/Activity/components/NewActivityHeader.tsx
  src/app/Scenes/Activity/types.ts
  src/app/Scenes/Activity/utils/getNotificationTypes.ts
  src/app/store/config/features.ts
Labels: Jira Synced, Squash On Green

#9765 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9766 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9767 chore: Prepare for 8.32.0
  app.json
Labels: Squash On Green

#9768 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9769 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9774 build(codepush): make fastlane message for native code more descriptive
  fastlane/utility_fastlane.rb
Labels: Squash On Green

#9777 build(deps): bump fastlane deps & sentry cli
  Gemfile.lock
  package.json
  yarn.lock
Labels: FF

#9771 feat: support lists on recently viewed screen
  .secrets.baseline
  src/app/AppRegistry.tsx
  src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
  src/app/Components/ArtworkGrids/MasonryArtworkGridItem.tsx
  src/app/Components/ArtworkGrids/MasonryInfiniteScrollArtworkGrid.tsx
  src/app/Scenes/NewWorksForYou/NewWorksForYou.tsx
  src/app/Scenes/RecentlyViewed/Components/RecentlyViewedArtworks.tsx
  src/app/Scenes/RecentlyViewed/Components/RecentlyViewedPlaceholder.tsx
  src/app/Scenes/RecentlyViewed/RecentlyViewed.tests.tsx
  src/app/Scenes/RecentlyViewed/RecentlyViewed.tsx
  src/app/Scenes/Search/UserPrefsModel.tsx
  src/app/store/__tests__/migration.tests.ts
  src/app/store/config/features.ts
  src/app/store/migration.ts
Labels: Jira Synced

#9778 chore: Use notification headline field as title and better errors
  src/app/Scenes/Activity/components/AlertNotification.tsx
  src/app/Scenes/Activity/components/ArtworkPublishedNotification.tsx
  src/app/Scenes/Activity/components/__tests__/AlertNotification.tests.tsx
  src/app/Scenes/Activity/components/__tests__/ArtworkPublishedNotification.tests.tsx
  src/app/Scenes/Activity/utils/getNotificationTitle.ts
Labels: Jira Synced, Squash On Green

#9781 feat(ONYX-689): support viewOption toggle on NWFGYF
  .secrets.baseline
  src/app/AppRegistry.tsx
  src/app/Scenes/NewWorksFromGalleriesYouFollow/Components/NewWorksFromGalleriesYouFollow.tsx
  src/app/Scenes/NewWorksFromGalleriesYouFollow/Components/NewWorksFromGalleriesYouFollowPlaceholder.tsx
  src/app/Scenes/NewWorksFromGalleriesYouFollow/NewWorksFromGalleriesYouFollow.tests.tsx
  src/app/Scenes/NewWorksFromGalleriesYouFollow/NewWorksFromGalleriesYouFollow.tsx
Labels: Jira Synced

#9764 feat(ONYX-658): update notification list item design
  src/app/Scenes/Activity/ActivityItem.tests.tsx
  src/app/Scenes/Activity/ActivityItem.tsx
  src/app/Scenes/Activity/ActivityItemTypeLabel.tsx
  src/app/Scenes/Activity/ActivityList.tsx
  src/app/Scenes/Activity/ActivityTabPlaceholder.tsx
  src/app/Scenes/Activity/utils/getNotificationTypeLabel.ts
Labels: Jira Synced, Squash On Green

#9787 chore: refresh cache
  .circleci/config.yml
Labels: Squash On Green

#9784 chore: add A/B testing logic to NWFGYF and RecentlyViewed
  src/app/Scenes/NewWorksFromGalleriesYouFollow/NewWorksFromGalleriesYouFollow.tsx
  src/app/Scenes/RecentlyViewed/RecentlyViewed.tsx
Labels: Jira Synced

#9789 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9790 build(deps): remove unused deps
  package.json
  yarn.lock
Labels: Jira Synced

#9791 build(deps): bump react-native-svg from 9.13.3 to 14.1.0
  ios/Podfile.lock
  package.json
  src/app/Components/Icons/GridViewIcon.tsx
  src/app/Components/Icons/ListViewIcon.tsx
  yarn.lock
Labels: Squash On Green

#9794 fix: swap view mode icons on the NWFY and similar screens
  src/app/Scenes/NewWorksForYou/NewWorksForYou.tsx
  src/app/Scenes/NewWorksFromGalleriesYouFollow/NewWorksFromGalleriesYouFollow.tsx
  src/app/Scenes/RecentlyViewed/RecentlyViewed.tsx
Labels: Squash On Green

#9798 fix: Update the content of the saves toast
  src/app/Components/ArtworkLists/useArtworkListsToast.ts
Labels: Squash On Green

#9800 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9801 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9802 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9804 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#9799 chore: clean up ARUsePrincipalFieldErrorHandlerMiddleware
  src/app/store/config/features.ts
  src/app/system/relay/middlewares/errorMiddleware.tests.ts
  src/app/system/relay/middlewares/errorMiddleware.ts
Labels: Jira Synced

#9806 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green
