Repository artsy/eigen, pull requests merged in 2025-01, with the labels that each got.

#11319 feat: implement activity dot indicator experiment
  src/app/Components/SaleArtworkTileRailCard/UrgencyInfo.tests.tsx
  src/app/Navigation/utils/useBottomTabsBadges.tests.ts
  src/app/Navigation/utils/useBottomTabsBadges.ts
  src/app/Scenes/HomeView/Components/ActivityIndicator.tsx
  src/app/Scenes/HomeView/HomeView.tsx
  src/app/utils/experiments/experiments.ts
  src/app/utils/experiments/useActivityDotExperiment.ts
  yarn.lock
Labels: Jira Synced

#11280 build(deps): bump @testing-library/react-native to latest
  jest.config.js
  package.json
  src/app/Components/ArtworkFilter/Filters/AdditionalGeneIDsOptions.tests.tsx
  src/app/Components/ArtworkFilter/Filters/ArtistIDsArtworksOptions.tests.tsx
  src/app/Components/ArtworkFilter/Filters/ArtistIDsSaleArtworksOptionsScreen.tests.tsx
  src/app/Components/ArtworkFilter/Filters/ArtistSeriesOptions.tests.tsx
  src/app/Components/ArtworkFilter/Filters/AttributionClassOptions.tests.tsx
  src/app/Components/ArtworkFilter/Filters/AuctionHouseOptions.tests.tsx
  src/app/Components/ArtworkFilter/Filters/AvailabilityOptions.tests.tsx
  src/app/Components/ArtworkFilter/Filters/CategoriesOptions.tests.tsx
  src/app/Components/ArtworkFilter/Filters/GalleriesAndInstitutionsOptions.tests.tsx
  src/app/Components/ArtworkFilter/Filters/LocationCitiesOptions.tests.tsx
  src/app/Components/ArtworkFilter/Filters/MaterialsTermsOptions.tests.tsx
  src/app/Components/ArtworkFilter/Filters/MultiSelectCheckOption.tsx
  src/app/Components/ArtworkFilter/Filters/MultiSelectOptionItem.tsx
  src/app/Components/ArtworkFilter/Filters/SizesOptionsScreen.tests.tsx
  src/app/Components/ArtworkFilter/Filters/TimePeriodOptions.tests.tsx
  src/app/Components/ArtworkFilter/Filters/WaysToBuyOptions.tests.tsx
  src/app/Components/ArtworkLists/ArtworkListsContext.tests.tsx
  src/app/Components/ArtworkLists/components/ArtworkListItem.tsx
  src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/components/ArtworkListItemSelectedIcon.tsx
  src/app/Components/Bidding/Screens/ConfirmBid.tests.tsx
  src/app/Components/Bidding/Screens/Registration.tests.tsx
  src/app/Components/FancyModal/FancyModalHeader.tsx
  src/app/Scenes/Article/Components/ArticleRelatedArticlesRail.tsx
  src/app/Scenes/Article/Components/Sections/ArticleSectionImageCollection/__tests__/ArticleSectionImageCollection.tests.tsx
  src/app/Scenes/Article/Components/Sections/ArticleSectionImageCollection/__tests__/ArticleSectionImageCollectionImage.tests.tsx
  src/app/Scenes/Article/Components/__tests__/ArticleBody.tests.tsx
  src/app/Scenes/Article/Components/__tests__/ArticleHero.tests.tsx
  src/app/Scenes/Article/Components/__tests__/ArticleShareButton.tests.tsx
  src/app/Scenes/Article/Components/__tests__/ArticleWebViewScreen.tests.tsx
  src/app/Scenes/Article/__tests__/ArticleScreen.tests.tsx
  src/app/Scenes/Artwork/Artwork.tests.tsx
  src/app/Scenes/Artwork/Components/ImageCarousel/ImageWithLoadingState.tests.tsx
  src/app/Scenes/Artwork/Components/ImageCarousel/ImageWithLoadingState.tsx
  src/app/Scenes/Collection/Components/CollectionHubsRails/ArtistSeries/CollectionArtistSeriesRail.tests.tsx
  src/app/Scenes/Collection/Screens/CollectionHeader.tests.tsx
  src/app/Scenes/CompleteMyProfile/__tests__/ProfessionStep.tests.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/CategoryPicker.tests.tsx
  src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightBottomSheet.tests.tsx
  src/app/Scenes/Onboarding/OnboardingCreateAccount/EmailSubscriptionCheckbox.tsx
  src/app/Scenes/Onboarding/OnboardingCreateAccount/Onboarding.tests.tsx
  src/app/Scenes/Onboarding/OnboardingCreateAccount/OnboardingCreateAccountName.tests.tsx
  src/app/Scenes/Onboarding/OnboardingCreateAccount/TermsOfServiceCheckbox.tsx
  src/app/Scenes/OrderHistory/OrderDetails/TrackOrderSection.tests.tsx
  src/app/Scenes/Sales/Sales.tests.tsx
  src/app/Scenes/SavedSearchAlert/EditSavedSearchAlert.tests.tsx
  src/app/Scenes/SavedSearchAlert/screens/SavedSearchFilterScreen.tests.tsx
  src/app/Scenes/SellWithArtsy/ArtworkForm/Components/__tests__/SubmitArtworkCondition.tests.tsx
  src/app/Scenes/SellWithArtsy/ArtworkForm/Components/__tests__/SubmitArtworkFromMyCollection.tests.tsx
  src/app/Scenes/SellWithArtsy/ArtworkForm/Components/__tests__/SubmitArtworkShippingLocation.tests.tsx
  src/setupJest.tsx
  yarn.lock
Labels: Jira Synced, Squash On Green

#11339 fix: fetch unleash toggles/variants after user has logged in
  src/app/store/AuthModel.ts
  src/app/utils/experiments/UnleashProvider.tsx
  src/app/utils/experiments/unleashClient.ts
Labels: Jira Synced

#11341 chore: fix flaky Activity rail tests
  src/app/Scenes/Activity/ActivityItem.tests.tsx
  src/app/Scenes/HomeView/Components/ActivityRail.tests.tsx
Labels: Squash On Green

#11343 fix: Avoid double spacing when hiding artwork in rail
  src/app/Components/ArtworkRail/ArtworkRail.tsx
  src/app/Components/ArtworkRail/ArtworkRailCard.tsx
  src/app/store/config/features.ts
Labels: Squash On Green

#11344 chore: disable biome
  .vscode/settings.json
Labels: Merge On Green

#11345 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11338 fix: tab views tracking
  src/app/Navigation/AuthenticatedRoutes/Tabs.tsx
  src/app/system/navigation/navigate.ts
Labels: Squash On Green

#11342 refactor: remove google-libphonenumber and replace it with custom logic
  package.json
  src/app/Components/Bidding/Screens/PhoneNumberForm.tests.tsx
  src/app/Components/Input/PhoneInput/PhoneInput.tsx
  src/app/utils/isValidPhoneNumber.tests.ts
  src/app/utils/isValidPhoneNumber.ts
  src/app/utils/validatePhoneNumber.ts
  yarn.lock
Labels: Jira Synced

#11352 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11353 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11340 fix: Allow editing MyC artworks that do not have submission
  src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tests.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tsx
Labels: Squash On Green

#11347 chore: Clean AREnableNewSearchModal ff related code
  src/app/Components/GlobalSearchInput/GlobalSearchInputOverlay.tsx
  src/app/Scenes/HomeView/Components/HomeHeader.tsx
  src/app/Scenes/Search/RecentSearches.tsx
  src/app/Scenes/Search/Search.tsx
  src/app/Scenes/Search/SearchModel.tests.tsx
  src/app/Scenes/Search/SearchModel.tsx
  src/app/Scenes/Search/components/AutosuggestSearchResult.tsx
  src/app/Scenes/Search/components/placeholders/SearchPlaceholder.tsx
  src/app/store/config/features.ts
Labels: Jira Synced

#11356 chore: clear cache
  .circleci/config.yml
Labels: Squash On Green

#11334 feat(EMI-2237): Update iOS in-app push notification style
  ios/Artsy/App/ARAppDelegate.mm
  ios/Artsy/App/ARAppNotificationsDelegate.h
  ios/Artsy/App/ARAppNotificationsDelegate.m
  ios/ArtsyTests/App_Tests/ARAppNotificationsDelegateTests.m
Labels: Jira Synced

#11292 feat(DIA-1015): infinite discovery swiping behavior
  src/app/Components/FancySwiper/FancySwiper.tsx
  src/app/Components/FancySwiper/FancySwiperCard.tsx
  src/app/Navigation/routes.tsx
  src/app/Scenes/InfiniteDiscovery/InfiniteDiscovery.tsx
  src/app/Scenes/InfiniteDiscovery/InfiniteDiscoveryContext.ts
  src/app/Scenes/InfiniteDiscovery/__tests__/InfiniteDiscovery.tests.tsx
  src/app/Scenes/InfiniteDiscovery/__tests__/InfiniteDiscoveryContext.tests.tsx
Labels: Squash On Green

#11372 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11378 fix: fix typo
  src/app/Scenes/ArtworkLists/SavesTabHeader.tsx
Labels: Squash On Green

#11293 feat: Introduce RouterLink component to prefetch links as they enter the viewport
  src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
  src/app/Components/SectionTitle.tsx
  src/app/Navigation/routes.tsx
  src/app/Scenes/Activity/ActivityContent.tsx
  src/app/Scenes/Activity/ActivityItem.tsx
  src/app/Scenes/Activity/ActivityItemScreen.tsx
  src/app/Scenes/Activity/components/ActivityHeader.tsx
  src/app/Scenes/Activity/utils/getActivityItemHref.ts
  src/app/Scenes/Fair/FairFollowedArtistsRail.tests.tsx
  src/app/Scenes/HomeView/Components/ActivityRail.tests.tsx
  src/app/Scenes/HomeView/Components/ActivityRailItem.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionActivity.tsx
  src/app/system/navigation/RouterLink.tests.tsx
  src/app/system/navigation/RouterLink.tsx
  src/app/utils/queryPrefetching.ts
Labels: Jira Synced

#11380 chore: Rename routerProps to navigationProps in RouterLink
  src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
  src/app/Scenes/Activity/ActivityItem.tsx
  src/app/Scenes/HomeView/Components/ActivityRailItem.tsx
  src/app/system/navigation/RouterLink.tests.tsx
  src/app/system/navigation/RouterLink.tsx
Labels: Squash On Green

#11381 fix: Auction Lots for You rail flickering
  src/app/Scenes/HomeView/Components/RecommendedAuctionLotsRail.tsx
  src/app/Scenes/Sales/Sales.tsx
Labels: Jira Synced

#11384 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11385 fix: Remove extra padding on Previously sold on Artsy rail
  src/app/Scenes/SellWithArtsy/Components/SellWithArtsyRecentlySold.tsx
Labels: Squash On Green

#11386 docs: update debugging docs
  docs/debugging.md
  docs/getting_started.md
  package.json
Labels: Jira Synced

#11379 feat: add ttid to all tab screens
  src/app/Components/Containers/Inbox.tsx
  src/app/Scenes/HomeView/HomeView.tsx
  src/app/Scenes/MyProfile/MyProfileHeaderMyCollectionAndSavedWorks.tsx
  src/app/Scenes/Search/Search.tsx
  src/app/Scenes/SellWithArtsy/SellWithArtsyHome.tsx
  src/setupJest.tsx
Labels: Jira Synced

#11390 build(deps): bump fastlane plugins
  Gemfile.lock
Labels: Squash On Green

#11393 fix: Remove italic prop from title on artwork context menu
  src/app/Components/ContextMenu/ContextMenuArtworkPreviewCard.tsx
Labels: Squash On Green

#11376 chore: deprecate FancyModal
  .secrets.baseline
  src/app/Components/AbandonFlowModal.tsx
  src/app/Components/ArtsyWebView.tests.tsx
  src/app/Components/ArtsyWebView.tsx
  src/app/Components/ArtworkFilter/Filters/SingleSelectOption.tsx
  src/app/Components/Bidding/Screens/BidResult.tsx
  src/app/Components/Bidding/Screens/BillingAddress.tsx
  src/app/Components/Bidding/Screens/ConfirmBid/index.tsx
  src/app/Components/Bidding/Screens/CreditCardForm.tsx
  src/app/Components/Bidding/Screens/PhoneNumberForm.tsx
  src/app/Components/Bidding/Screens/Registration.tsx
  src/app/Components/Bidding/Screens/RegistrationResult.tsx
  src/app/Components/Bidding/Screens/SelectMaxBid.tsx
  src/app/Components/FancyModal/FancyModal.tsx
  src/app/Components/NavigationHeader.tsx
  src/app/Components/ShareSheet/ShareSheet.tsx
  src/app/Components/SortByModal/SortByModal.tsx
  src/app/Providers.tsx
  src/app/Scenes/Artwork/Components/ArtworkError.tsx
  src/app/Scenes/Artwork/Components/BrowseSimilarWorks/BrowseSimilarWorksContent.tsx
  src/app/Scenes/Artwork/Components/BrowseSimilarWorks/BrowseSimilarWorksErrorState.tsx
  src/app/Scenes/Artwork/Components/CommercialButtons/InquiryModal.tsx
  src/app/Scenes/Artwork/Components/CommercialButtons/ShippingModal.tsx
  src/app/Scenes/ArtworkList/ArtworkListHeader.tsx
  src/app/Scenes/Inbox/Components/Conversations/MakeOfferModal.tsx
  src/app/Scenes/Inbox/Components/Conversations/OfferSubmittedModal.tsx
  src/app/Scenes/Inbox/Components/Conversations/PurchaseModal.tsx
  src/app/Scenes/MyCollection/Screens/Artist/AddMyCollectionArtist.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/RarityLegacy.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormAddPhotos.tests.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormAddPhotos.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormArtist.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormArtwork.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormMain.tests.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormMain.tsx
  src/app/Scenes/MyCollection/Screens/Insights/CareerHighlightsBigCardsSwiper.tsx
  src/app/Scenes/MyCollection/Screens/Insights/SelectArtist.tests.tsx
  src/app/Scenes/MyCollection/Screens/Insights/SelectArtistModal.tsx
  src/app/Scenes/MyProfile/MyProfileEditModal.tsx
  src/app/Scenes/SavedSearchAlert/CreateSavedSearchAlert.tsx
  src/app/Scenes/SavedSearchAlert/containers/CreateSavedSearchContentContainer.tsx
  src/app/Scenes/SavedSearchAlert/screens/ConfirmationScreen.tsx
  src/app/Scenes/SavedSearchAlert/screens/EmailPreferencesScreen.tsx
  src/app/Scenes/SavedSearchAlert/screens/SavedSearchFilterScreen.tsx
  src/app/Scenes/SavedSearchAlertsList/Components/SavedSearchesList.tests.tsx
  src/app/Scenes/SavedSearchAlertsList/Components/SavedSearchesList.tsx
  src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkDetails/InfoModal/InfoModal.tsx
  src/app/utils/useStickyScrollHeader.tsx
Labels: Squash On Green, FF

#11394 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11397 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11383 feat: Replace Touchable with Routerlink for prefetching on artwork and artist rails
  src/app/Components/ArtworkRail/ArtworkRail.tsx
  src/app/Components/ArtworkRail/ArtworkRailCard.tsx
  src/app/Components/ShowCard.tsx
  src/app/Navigation/routes.tsx
  src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsTabs/ArtQuizArtist.tsx
  src/app/Scenes/ArtQuiz/ArtQuizResults/ArtQuizResultsTabs/ArtQuizTrendingCollection.tsx
  src/app/Scenes/Artist/Artist.tsx
  src/app/Scenes/Artwork/Components/ArtworksInSeriesRail.tsx
  src/app/Scenes/CollectionsByCategory/CollectionRail.tsx
  src/app/Scenes/Fair/Components/FairExhibitorRail.tsx
  src/app/Scenes/Fair/Components/FairFollowedArtistsRail.tsx
  src/app/Scenes/Fair/FairFollowedArtistsRail.tests.tsx
  src/app/Scenes/HomeView/Components/ArtistRails/ArtistCard.tsx
  src/app/Scenes/HomeView/Components/ArtistRails/ArtistRail.tsx
  src/app/Scenes/HomeView/Components/ArtistRails/RecommendedArtistsRail.tsx
  src/app/Scenes/HomeView/Components/ArtworkModuleRail.tsx
  src/app/Scenes/HomeView/Components/ArtworkRecommendationsRail.tsx
  src/app/Scenes/HomeView/Components/NewWorksForYouRail.tsx
  src/app/Scenes/HomeView/Components/RecommendedAuctionLotsRail.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArtworks.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionFeaturedCollection.tsx
  src/app/Scenes/Sale/Components/BuyNowArtworksRail.tsx
  src/app/Scenes/Sale/Components/NewBuyNowArtworksRail.tsx
  src/app/Scenes/SellWithArtsy/Components/SellWithArtsyRecentlySold.tsx
  src/app/Scenes/Show/Show.tsx
  src/app/Scenes/ViewingRoom/Components/ViewingRoomArtworkRail.tsx
  src/app/system/navigation/RouterLink.tests.tsx
  src/app/system/navigation/RouterLink.tsx
  src/app/utils/queryPrefetching.ts
Labels: Jira Synced

#11401 fix: Avoid double prefetching on artwork grid
  src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
Labels: Squash On Green

#11388 fix: ensure better resolution for ArtistCard images
  src/app/Scenes/HomeView/Components/ArtistRails/ArtistCard.tsx
Labels: Jira Synced

#11403 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11406 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11395 feat(DIA-1062): refetch infinite discovery
  src/app/Components/FancySwiper/__tests__/FancySwiper.tests.tsx
  src/app/Components/FancySwiper/__tests__/utils.ts
  src/app/Scenes/InfiniteDiscovery/InfiniteDiscovery.tsx
  src/app/Scenes/InfiniteDiscovery/__tests__/InfiniteDiscovery.tests.tsx
Labels: Squash On Green

#11402 fix: direct opens tracking for braze
  ios/Artsy/App/ARAppNotificationsDelegate.m
Labels: Jira Synced

#11410 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11413 fix: prevent users from saving empty phone number
  src/app/Scenes/MyAccount/MyAccountEditPhone.tsx
Labels: Squash On Green

#11412 fix: bump RCT-Folly checksum
  ios/Podfile.lock
Labels: Merge On Green

#11405 feat(ONYX-1486): Section title prefetching and refactoring
  src/app/Components/EmbeddedCarousel.tsx
  src/app/Components/SectionTitle.tsx
  src/app/Navigation/routes.tsx
  src/app/Scenes/HomeView/Components/ActivityRail.tsx
  src/app/Scenes/HomeView/Components/ArticlesRail.tsx
  src/app/Scenes/HomeView/Components/ArtistRails/ArtistRail.tsx
  src/app/Scenes/HomeView/Components/ArtistRails/RecommendedArtistsRail.tsx
  src/app/Scenes/HomeView/Components/ArtworkModuleRail.tsx
  src/app/Scenes/HomeView/Components/ArtworkRecommendationsRail.tsx
  src/app/Scenes/HomeView/Components/ShowsRail.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionActivity.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArticles.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArticlesCards.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArtists.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArtworks.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionAuctionResults.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionCardsChips.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionFairs.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionFeaturedCollection.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionMarketingCollections.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionSales.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionViewingRooms.tsx
  src/app/Scenes/HomeView/Sections/__tests__/HomeViewSectionAuctionResults.tests.tsx
  src/app/Scenes/HomeView/helpers/getHomeViewSectionHref.ts
  src/app/Scenes/HomeViewSectionScreen/HomeViewSectionScreen.tsx
  src/app/Scenes/MyAccount/MyAccount.tests.tsx
  src/app/Scenes/MyAccount/MyAccount.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkComparableWorks.tsx
  src/app/Scenes/Sale/Components/BuyNowArtworksRail.tsx
  src/app/Scenes/Sale/Components/NewBuyNowArtworksRail.tsx
  src/app/Scenes/Sale/Components/SaleArtworksRail.tsx
  src/app/Scenes/Sales/Components/SaleList.tsx
  src/app/Scenes/Search/CuratedCollections.tsx
  src/app/Scenes/Search/RecentSearches.tsx
  src/app/Scenes/Search/TrendingArtists.tsx
  src/app/Scenes/ViewingRoom/ViewingRoomsList.tsx
  src/app/utils/queryPrefetching.ts
Labels: Jira Synced, Squash On Green

#11416 fix(iOS): foreground notifications linking (/w images)
  ios/Artsy/App/ARAppNotificationsDelegate.m
Labels: Squash On Green

#11418 chore: Bump minimum iOS version requirement
  ios/Artsy.xcodeproj/project.pbxproj
  ios/ArtsyWidget/FullBleed/FullBleed+View.swift
  ios/Podfile
Labels: hackathon

#11419 chore: refresh caches
  .circleci/config.yml
Labels: Squash On Green

#11422 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11420 fix: Modernize iOS widget config
  ios/Artsy.xcodeproj/project.pbxproj
  ios/ArtsyWidget/FeaturedArtworks/FeaturedArtworks+LargeView.swift
  ios/ArtsyWidget/FeaturedArtworks/FeaturedArtworks+MediumView.swift
  ios/ArtsyWidget/FeaturedArtworks/FeaturedArtworks+SmallView.swift
  ios/ArtsyWidget/FeaturedArtworks/FeaturedArtworks+Widget.swift
  ios/ArtsyWidget/FullBleed/FullBleed+View.swift
  ios/ArtsyWidget/FullBleed/FullBleed+Widget.swift
  ios/ArtsyWidget/LatestArticles/LatestArticles+LargeView.swift
  ios/ArtsyWidget/LatestArticles/LatestArticles+MediumView.swift
  ios/ArtsyWidget/LatestArticles/LatestArticles+SmallView.swift
  ios/ArtsyWidget/LatestArticles/LatestArticles+Widget.swift
Labels: hackathon

#11423 fix(PBRW-359): broken presentation on tooltip icon
  src/app/Components/Buttons/InfoButton.tsx
Labels: Jira Synced

#11426 chore: podfile checksum
  ios/Podfile.lock
Labels: Squash On Green

#11424 fix(PBRW-338): broken info button inside modals
  src/app/Components/Buttons/InfoButton.tsx
  src/app/Scenes/SavedSearchAlert/Components/Form.tsx
  src/app/Scenes/SavedSearchAlert/CreateSavedSearchAlert.tsx
Labels: Jira Synced

#11427 fix: Complete My Profile flow "Save and Exit" buttons
  src/app/Scenes/CompleteMyProfile/hooks/useCompleteProfile.ts
Labels: Jira Synced, Squash On Green

#11429 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11431 fix: remove cacheable from fair page
  src/app/Scenes/Fair/Fair.tsx
Labels: Squash On Green

#11433 fix: interaction with toggles messes with offer modal
  src/app/Components/ArtworkLists/views/ArtworkListOfferSettingsView/ArtworkListOfferSettingsView.tsx
Labels: Jira Synced, Squash On Green

#11434 chore: prepare for next release
  app.json
Labels: Squash On Green

#11438 chore: add pickup available line to shipping infor on artwork
  src/app/Scenes/Artwork/Components/ShippingAndTaxes.tests.tsx
  src/app/Scenes/Artwork/Components/ShippingAndTaxes.tsx
Labels: hackathon, hack15

#11437 build(deps): bump react-native-keychain to latest
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: hackathon, hack15

#11440 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11442 fix: Sell flow navigation on hardware back button press for Android
  src/app/Scenes/SellWithArtsy/ArtworkForm/Utils/useSubmissionContext.ts
Labels: Jira Synced, Squash On Green

#11444 chore: remove buggy license agreement check for now #trivial
  .circleci/config.yml
Labels: Jira Synced, Squash On Green

#11443 fix: navigate to home on back press quiz
  src/app/Scenes/HomeView/HomeView.tsx
Labels: Squash On Green

#11435 feat: add framed works filter to artwork screens
  data/schema.graphql
  src/app/Components/ArtworkFilter/ArtworkFilterHelpers.ts
  src/app/Components/ArtworkFilter/ArtworkFilterNavigator.tsx
  src/app/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx
  src/app/Components/ArtworkFilter/Filters/FramedOptions.tests.tsx
  src/app/Components/ArtworkFilter/Filters/FramedOptions.tsx
  src/app/Components/ArtworkFilter/types.ts
  src/app/store/config/features.ts
Labels: hackathon, hack15

#11359 feat: Long-press artwork context menu for Android
  src/app/Components/ArtworkRail/ArtworkRailCard.tsx
  src/app/Components/ContextMenu/ContextMenuArtwork.tsx
  src/app/Components/ContextMenu/__tests__/ContextMenuArtwork.tests.tsx
  src/app/store/config/features.ts
Labels: Jira Synced, Squash On Green

#11447 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11407 feat(EMI-2187): Refresh Bids screen every 10 secs
  src/app/Scenes/MyBids/MyBids.tests.tsx
  src/app/Scenes/MyBids/MyBids.tsx
  src/app/utils/useAppState.tsx
Labels: Jira Synced

#11448 fix(PBRW-375): navigation on the cascade bidding auction screen
  src/app/Scenes/Sale/Sale.tests.tsx
  src/app/Scenes/Sale/Sale.tsx
Labels: Jira Synced, Squash On Green

#11449 fix: cannot skip onboarding art quiz
  src/app/Scenes/ArtQuiz/ArtQuizWelcome.tsx
Labels: Jira Synced, Squash On Green

#11366 fix: Filter out disliked artworks correctly on the home screen for all recommendation rails
  src/app/Components/ContextMenu/ContextMenuArtwork.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionActivity.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArtworks.tsx
  src/app/Scenes/HomeView/Sections/__tests__/HomeViewSectionArtworks.tests.tsx
  src/app/store/config/features.ts
  src/app/utils/isDislikeArtworksEnabledFor.ts
Labels: Jira Synced, Squash On Green

#11452 fix: fix logic for canSave
  src/app/Scenes/MyAccount/MyAccountEditPhone.tsx
Labels: Jira Synced, Squash On Green

#11451 chore(ONYX-1497): remove Artwork Rail Card Redesign experiment logic
  src/app/Components/Artist/ArtistHeaderNavRight.tsx
  src/app/Components/Artist/useFollowArtist.ts
  src/app/Components/ArtworkGrids/ArtworkGridItem.tests.tsx
  src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
  src/app/Components/ArtworkGrids/MasonryArtworkGridItem.tsx
  src/app/Components/ArtworkGrids/MasonryInfiniteScrollArtworkGrid.tsx
  src/app/Components/ArtworkRail/ArtworkRailCard.tests.tsx
  src/app/Components/ArtworkRail/ArtworkRailCard.tsx
  src/app/Components/ArtworkRail/ArtworkRailCardMeta.tsx
  src/app/Components/constants.ts
  src/app/Scenes/Activity/components/NotificationArtworkList.tsx
  src/app/Scenes/Artwork/Components/ArtworkItemCTAs.tests.tsx
  src/app/Scenes/Artwork/Components/ArtworkItemCTAs.tsx
  src/app/Scenes/Artwork/Components/ArtworkSaveButton.tsx
  src/app/Scenes/Artwork/utils/useGetNewSaveAndFollowOnArtworkCardExperimentVariant.tsx
  src/app/Scenes/HomeView/Components/ArtistRails/ArtistCard.tsx
  src/app/Scenes/HomeView/HomeView.tsx
  src/app/store/config/features.ts
Labels: Jira Synced, Squash On Green

#11425 refactor(hack15): deprecate fancy modal + ArtsyKeyboardAvoidingView
  src/app/Components/ArtsyWebView.tsx
  src/app/Components/Bidding/Screens/BillingAddress.tsx
  src/app/Components/Bidding/Screens/CreditCardForm.tsx
  src/app/Components/Buttons/BottomAlignedButtonWrapper.tsx
  src/app/Components/Containers/Inquiry.tsx
  src/app/Components/FancyModal/FancyModal.tsx
  src/app/Components/FancyModal/FancyModalCard.tsx
  src/app/Components/FancyModal/FancyModalContext.tsx
  src/app/Components/Select/SelectV2.tsx
  src/app/Providers.tsx
  src/app/Scenes/Inbox/Components/Conversations/Composer.tsx
  src/app/Scenes/MyAccount/Components/MyAccountFieldEditScreen.tsx
  src/app/Scenes/MyAccount/MyAccountDeleteAccount.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionArtistsPrompt/MyCollectionArtistsAutosuggest.tsx
  src/app/Scenes/MyCollection/Screens/Artist/AddMyCollectionArtist.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/RequestForPriceEstimate/RequestForPriceEstimateForm.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/RequestForPriceEstimate/RequestForPriceEstimateScreen.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Screens/MyCollectionArtworkFormMain.tsx
  src/app/Scenes/MyProfile/MyProfileEditForm.tsx
  src/app/Scenes/Onboarding/ForgotPasswordForm.tsx
  src/app/Scenes/Onboarding/Onboarding.tsx
  src/app/Scenes/Onboarding/OnboardingCreateAccount/OnboardingCreateAccount.tsx
  src/app/Scenes/Onboarding/OnboardingLogin.tsx
  src/app/Scenes/Onboarding/OnboardingLoginWithOTP.tsx
  src/app/Scenes/PriceDatabase/components/PriceDatabaseSearch.tsx
  src/app/Scenes/SavedSearchAlert/EditSavedSearchAlert.tsx
  src/app/Scenes/Search/Search.tsx
  src/app/Scenes/SellWithArtsy/ArtworkForm/SubmitArtworkForm.tsx
  src/app/Scenes/SellWithArtsy/ConsignmentInquiry/ConsignmentInquiryScreen.tsx
  src/app/Scenes/SellWithArtsy/SubmitArtwork/ArtworkDetails/InfoModal/InfoModal.tsx
  src/app/utils/ArtsyKeyboardAvoidingView.tsx
Labels: hackathon, hack15

#11457 feat: Modernize iOS widget
  ios/Artsy.xcodeproj/project.pbxproj
  ios/Artsy.xcodeproj/xcshareddata/xcschemes/ArtsyWidgetExtension.xcscheme
  ios/ArtsyWidget/ArtsyWidgets.swift
  ios/ArtsyWidget/Assets.xcassets/Contents.json
  ios/ArtsyWidget/Assets.xcassets/PrimaryArticleImage.imageset/Contents.json
  ios/ArtsyWidget/Assets.xcassets/PrimaryArticleImage.imageset/larger-1.jpg
  ios/ArtsyWidget/Assets.xcassets/PrimaryArticleImage.imageset/larger-2.jpg
  ios/ArtsyWidget/Assets.xcassets/PrimaryArticleImage.imageset/larger-3.jpg
  ios/ArtsyWidget/Assets.xcassets/QuaternaryArticleImage.imageset/Contents.json
  ios/ArtsyWidget/Assets.xcassets/QuaternaryArticleImage.imageset/larger-3.jpg
  ios/ArtsyWidget/Assets.xcassets/QuaternaryArticleImage.imageset/larger-4.jpg
  ios/ArtsyWidget/Assets.xcassets/QuaternaryArticleImage.imageset/larger-5.jpg
  ios/ArtsyWidget/Assets.xcassets/SecondaryArticleImage.imageset/Contents.json
  ios/ArtsyWidget/Assets.xcassets/SecondaryArticleImage.imageset/LlvT0YMuMETC0VYbgsJR4g_New+Collector+copy-1.jpg
  ios/ArtsyWidget/Assets.xcassets/SecondaryArticleImage.imageset/LlvT0YMuMETC0VYbgsJR4g_New+Collector+copy-2.jpg
  ios/ArtsyWidget/Assets.xcassets/SecondaryArticleImage.imageset/LlvT0YMuMETC0VYbgsJR4g_New+Collector+copy.jpg
  ios/ArtsyWidget/Assets.xcassets/TertiaryArticleImage.imageset/Contents.json
  ios/ArtsyWidget/Assets.xcassets/TertiaryArticleImage.imageset/larger-2.jpg
  ios/ArtsyWidget/Assets.xcassets/TertiaryArticleImage.imageset/larger-3.jpg
  ios/ArtsyWidget/Assets.xcassets/TertiaryArticleImage.imageset/larger-4.jpg
  ios/ArtsyWidget/FeaturedArtworks/FeaturedArtworks+Entry.swift
  ios/ArtsyWidget/FeaturedArtworks/FeaturedArtworks+LargeView.swift
  ios/ArtsyWidget/FeaturedArtworks/FeaturedArtworks+MediumView.swift
  ios/ArtsyWidget/FeaturedArtworks/FeaturedArtworks+Provider.swift
  ios/ArtsyWidget/FeaturedArtworks/FeaturedArtworks+SmallView.swift
  ios/ArtsyWidget/FeaturedArtworks/FeaturedArtworks+Timeline.swift
  ios/ArtsyWidget/FeaturedArtworks/FeaturedArtworks+View.swift
  ios/ArtsyWidget/FeaturedArtworks/FeaturedArtworks+Widget.swift
  ios/ArtsyWidget/FeaturedArtworks/FeaturedArtworks.swift
  ios/ArtsyWidget/Fixtures.swift
  ios/ArtsyWidget/FullBleed/FullBleed+View.swift
  ios/ArtsyWidget/FullBleed/FullBleed+Widget.swift
  ios/ArtsyWidget/LatestArticles/LatestArticles+LargeView.swift
  ios/ArtsyWidget/LatestArticles/LatestArticles+MediumView.swift
  ios/ArtsyWidget/LatestArticles/LatestArticles+SmallView.swift
  ios/ArtsyWidget/LatestArticles/LatestArticles+View.swift
  ios/ArtsyWidget/LatestArticles/LatestArticles+Widget.swift
  ios/ArtsyWidget/Models/Article.swift
  ios/ArtsyWidget/Models/ArticleParser.swift
  ios/ArtsyWidget/Models/ArticleStore.swift
Labels: hackathon

#11461 chore: commit artifacts that appeared in project after git pull && yarn install:all
  ios/Artsy.xcodeproj/project.pbxproj
Labels: Squash On Green

#11462 fix: Hides onboarding flow after sign in
  src/app/Scenes/Onboarding/OnboardingCreateAccount/Onboarding.tests.tsx
  src/app/store/AuthModel.ts
  src/app/store/OnboardingModel.ts
Labels: Squash On Green

#11464 chore: set AREnableProgressiveOnboardingAlerts readyForRelease to true
  src/app/store/config/features.ts
Labels: Squash On Green

#11463 feat: Long Press Context Menu Tooltip
  src/app/Components/ProgressiveOnboarding/ProgressiveOnboardingLongPressContextMenu.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArtworks.tsx
  src/app/store/ProgressiveOnboardingModel.ts
  src/app/store/config/features.ts
Labels: Jira Synced

#11466 chore: make AREnableFramedFilter ready for release
  src/app/store/config/features.ts
Labels: Squash On Green

#11469 chore: Set AREnableArtworkCardContextMenuAndroid ff as ready for release
  src/app/store/config/features.ts
Labels: Squash On Green

#11446 feat(deps): migrate to more secure library for secret management
  .circleci/config.yml
  .env.example
  .gitignore
  .secrets.baseline
  HACKS.md
  android/app/build.gradle
  android/app/src/main/java/net/artsy/app/MainApplication.kt
  android/app/src/main/java/net/artsy/app/utils/ReactNativeConfigUtils.java
  android/build.gradle
  android/gradle.properties
  docs/adding_new_keys.md
  fastlane/Fastfile
  ios/Artsy.xcodeproj/project.pbxproj
  ios/Artsy.xcodeproj/xcshareddata/xcschemes/Artsy.xcscheme
  ios/Artsy/App/ARAppDelegate+Emission.m
  ios/Artsy/App/ARAppDelegate.mm
  ios/Artsy/App/ARAppNotificationsDelegate.m
  ios/Artsy/App/ArtsyEcho.m
  ios/Artsy/Networking/ARRouter.m
  ios/Podfile.lock
  keys.example.json
  package.json
  patches/react-native-keys+0.7.11.patch
  scripts/setup/setup-env-for-artsy
  scripts/setup/setup-env-for-ci
  scripts/setup/setup-env-for-oss
  scripts/setup/update-env-for-artsy
  scripts/utils/doctor.js
  src/app/App.tsx
  src/app/Components/LocationMap/LocationMap.tsx
  src/app/Components/Recaptcha/RecaptchaWebView.tsx
  src/app/Components/ShareSheet/ShareSheet.tsx
  src/app/Scenes/Artwork/Components/ImageCarousel/ImageCarouselVimeoVideo.tsx
  src/app/Scenes/Map/GlobalMap.tsx
  src/app/Scenes/Partner/Components/PartnerMap.tsx
  src/app/store/AuthModel.ts
  src/app/store/config/features.ts
  src/app/system/codepush.ts
  src/app/system/devTools/DevMenu/Components/DevTools.tsx
  src/app/system/errorReporting/setupSentry.ts
  src/app/utils/Websockets/GravityWebsocketContext.tsx
  src/app/utils/experiments/unleashClient.ts
  src/app/utils/googleMaps.ts
  src/app/utils/track/SegmentTrackingProvider.ts
  src/app/utils/useSiftConfig.ts
  src/setupJest.tsx
  typings/react-native-config.d.ts
  yarn.lock
Labels: Jira Synced
