Repository artsy/eigen, pull requests merged in 2025-07, with the labels that each got.

#12388 fix(EMI-2606): phone number displays country code in order details
  src/app/Scenes/OrderHistory/OrderDetail/Components/OrderDetailFulfillment.tsx
Labels: Jira Synced

#12389 chore: Add loading skeleton to Order Details
  src/app/Scenes/OrderHistory/OrderDetail/OrderDetail.tsx
Labels: Squash On Green

#12391 feat: convert activity dots to blue
  src/app/Navigation/utils/useBottomTabsBadges.ts
  src/app/Scenes/HomeView/Components/ActivityIndicator.tsx
Labels: Jira Synced

#12288 feat: Android widget - Featured Artwork
  .circleci/config.yml
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/net/artsy/app/widgets/FullBleedWidgetProvider.kt
  android/app/src/main/java/net/artsy/app/widgets/client/ArtsyApiClient.kt
  android/app/src/main/java/net/artsy/app/widgets/models/Artist.kt
  android/app/src/main/java/net/artsy/app/widgets/models/Artwork.kt
  android/app/src/main/java/net/artsy/app/widgets/models/ArtworkImage.kt
  android/app/src/main/res/drawable/widget_preview_image.jpg
  android/app/src/main/res/layout/widget_fullbleed.xml
  android/app/src/main/res/layout/widget_fullbleed_preview.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/xml/fullbleed_widget_info.xml
  android/app/src/test/java/net/artsy/app/widgets/ArtworkRotationTest.kt
  android/app/src/test/java/net/artsy/app/widgets/FullBleedWidgetProviderTest.kt
  docs/testing.md
  docs/widgets.md
  package.json
Labels: FF

#12398 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12306 feat: android e2e tests on CI
  .circleci/config.yml
  .github/workflows/android-e2e-maestro.yml
  android/app/src/main/AndroidManifest.xml
  e2e/flows/deeplinks.yml
  e2e/flows/login.yml
  e2e/flows/signup.yml
  fastlane/utility_fastlane.rb
  scripts/ci/build-for-tests-android
  scripts/ci/ci-android
  scripts/ci/ci-ios
  scripts/ci/upload-emu-app
  scripts/utils/run_maestro_shard_android
Labels: Jira Synced

#12400 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12403 feat: migrate iOS maestro tests to gh actions
  .circleci/config.yml
  .github/workflows/android-e2e-maestro.yml
  .github/workflows/ios-e2e-maestro.yml
  scripts/utils/run_maestro_shard
  scripts/utils/run_maestro_shard_android
Labels: Jira Synced

#12414 chore: Fix broken tests
  src/app/Scenes/OrderHistory/__tests__/OrderHistoryRow.tests.tsx
Labels: Squash On Green

#12415 chore: update Order History row tests
  src/app/Scenes/OrderHistory/__tests__/OrderHistoryRow.tests.tsx
Labels: Squash On Green

#12417 chore: update S3 presign screenshot url expiration to 15 days in report-maestro-test-failure script
  scripts/ci/report-maestro-test-failure
Labels: Jira Synced, Squash On Green

#12419 fix(ONYX-1783): fix MyCollectionArtworkScreenQuery prefetching
  src/app/Navigation/routes.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/MyCollectionArtwork.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkList/MyCollectionArtworkGridItem.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkList/__tests__/MyCollectionArtworkGridItem.tests.tsx
Labels: Jira Synced, Squash On Green

#12412 chore: delete city guide native code
  ios/Artsy.xcodeproj/project.pbxproj
  ios/Artsy/Emission/Data/ARCity+GeospatialAdditions.h
  ios/Artsy/Emission/Data/ARCity+GeospatialAdditions.m
  ios/Artsy/Emission/Data/ARCity.h
  ios/Artsy/Emission/Data/ARCity.m
  ios/Artsy/Emission/ViewControllers/ARCityComponentViewController.h
  ios/Artsy/Emission/ViewControllers/ARCityComponentViewController.m
  ios/Artsy/Emission/ViewControllers/ARCityPickerComponentViewController.h
  ios/Artsy/Emission/ViewControllers/ARCityPickerComponentViewController.m
  ios/Artsy/Emission/ViewControllers/ARMapComponentViewController.h
  ios/Artsy/Emission/ViewControllers/ARMapComponentViewController.m
  ios/Artsy/Emission/ViewControllers/ARMapContainerViewController.h
  ios/Artsy/Emission/ViewControllers/ARMapContainerViewController.m
  ios/Artsy/NativeModules/ARTCityGuideManager.m
  ios/Artsy/NativeModules/CityGuideView.swift
  ios/Artsy/Resources/Artsy-Bridging-Header.h
  ios/Podfile
  ios/Podfile.lock
Labels: Jira Synced

#12426 fix: move asset download to prep-android-env
  .circleci/config.yml
Labels: Jira Synced, Squash On Green

#12434 chore: update notion script to use team rather than components
  scripts/utils/exportNotionTicketsToJira.ts
Labels: Jira Synced

#12437 fix: apple icon not visible on dark mode
  src/app/Scenes/MyAccount/MyAccount.tsx
Labels: Jira Synced, Squash On Green

#12421 fix: increase tappable area on city guide and status bar on android
  src/app/Scenes/Map/GlobalMap.tsx
Labels: Jira Synced

#12443 fix(PBRW-981): broken view artsy price database link
  src/app/Components/Artist/ArtistInsights/ArtistsInsightsEmpty.tsx
Labels: Jira Synced, Squash On Green

#12447 fix(PBRW-978): broken follow button on artist list item
  src/app/Scenes/Artist/Artist.tsx
Labels: Jira Synced, Squash On Green

#12446 build(deps): bump fastlane deps
  Gemfile.lock
Labels: Squash On Green

#12449 build(deps): bump @react-native-async-storage/async-storage from 2.1.2 to 2.2.0
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: Squash On Green

#12448 fix: add artist title to artist screen
  src/app/Components/Artist/ArtistHeaderNavRight.tsx
  src/app/Components/Artist/__tests__/ArtistHeaderNavRight.tests.tsx
  src/app/Navigation/routes.tsx
  src/app/Scenes/Artist/Artist.tsx
Labels: Squash On Green

#12451 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12458 chore: bump target sdk version to 35
  android/build.gradle
Labels: Jira Synced

#12457 build(deps): bump react-native-bootsplash from 6.3.4 to 6.3.10
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: FF

#12453 fix(PBRW-994, PBRW-974, ONYX-1566): use auto-height bottom sheet for the artist preview modal
  src/app/Scenes/MyCollection/Components/MyCollectionBottomSheetModals/MyCollectionBottomSheetModalArtistPreview.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionBottomSheetModals/MyCollectionBottomSheetModals.tsx
Labels: Jira Synced

#12471 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12473 chore: assign bugs to teams script adjustments
  scripts/utils/assignPBRWTicketsToTeams.ts
Labels: Jira Synced

#12470 chore: add timeout for build processing
  fastlane/Fastfile
Labels: Jira Synced

#12475 fix(ONYX-1760): fix broken back navigation on the favorites tab (remove back actions)
  src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
  src/app/Scenes/Favorites/Favorites.tsx
Labels: Jira Synced

#12476 fix(analytics): don't track home view on tab switch
  src/app/Navigation/AuthenticatedRoutes/Tabs.tsx
Labels: Jira Synced

#12431 chore: track app state changes
  src/app/App.tsx
  src/app/utils/useTrackAppState.ts
Labels: Jira Synced, Squash On Green

#12481 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12482 fix(DIA-1411): National Gallery of Art, Washington, D.C.
  src/app/Components/Artist/ArtistAbout/ArtistCareerHighlights.tsx
  src/app/Components/Artist/ArtistAbout/__tests__/ArtistCareerHighlights.tests.tsx
Labels: Jira Synced

#12483 feat(ONYX-1813): add price range onboarding popover to home
  src/app/Components/ProgressiveOnboarding/ProgressiveOnboardingPriceRangeHome.tsx
  src/app/Components/ProgressiveOnboarding/__tests__/ProgressiveOnboardingPriceRangeHome.tests.tsx
  src/app/Navigation/AuthenticatedRoutes/Tabs.tsx
  src/app/store/ProgressiveOnboardingModel.ts
  src/app/store/config/features.ts
Labels: Jira Synced

#12496 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12493 chore: remove Echo flagging for blue activity dot
  src/app/Navigation/utils/__tests__/useBottomTabsBadges.tests.ts
  src/app/Navigation/utils/useBottomTabsBadges.ts
  src/app/Scenes/HomeView/Components/ActivityIndicator.tsx
  src/app/store/config/features.ts
Labels: Jira Synced

#12498 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12499 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12500 chore: [HomeView Performance] do not re-render Header
  src/app/Scenes/HomeView/Components/HomeHeader.tsx
Labels: performance

#12505 chore: [HomeView Performance] do not re-render hero units
  src/app/Components/PaginationDots.tsx
  src/app/Scenes/HomeView/Components/HeroUnit.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionHeroUnits.tsx
Labels: performance

#12511 chore: [HomeView Performance] do not re-render shows
  src/app/Components/ShowCard.tsx
  src/app/Scenes/HomeView/Components/ShowsRail.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionShows.tsx
Labels: performance

#12510 chore: [HomeView Performance] do not re-render artists
  src/app/Scenes/HomeView/Components/ArtistRails/ArtistCard.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArtists.tsx
Labels: performance

#12512 chore: [HomeView Performance] do not re-render articles
  src/app/Components/ArticleCard.tsx
  src/app/Scenes/HomeView/Components/ArticlesRail.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArticles.tsx
Labels: performance

#12515 chore: add price range saved tracking
  src/app/Scenes/MyAccount/MyAccountEditPriceRange.tsx
Labels: Jira Synced, Squash On Green

#12468 build(deps): bump expo to 52.0.27 and rn to 77
  .circleci/config.yml
  HACKS.md
  android/build.gradle
  app.json
  ios/Artsy/AppDelegate.mm
  ios/Podfile
  ios/Podfile.lock
  jest.config.js
  metro.config.js
  package.json
  patches/@rnmapbox+maps+10.1.38.patch
  patches/expo-updates+0.27.4.patch
  src/app/Components/BottomSheet/AutomountedBottomSheetModal.tsx
  src/app/utils/hooks/__tests__/useBackHandler.tests.ts
  src/app/utils/hooks/useBackHandler.ts
  yarn.lock
Labels: Jira Synced, Squash On Green

#12524 chore: [HomeView Performance] do not use impressionsTracking infra unless enabled
  src/app/Scenes/HomeView/Sections/HomeViewSectionArtworks.tsx
Labels: Squash On Green, performance

#12523 chore: [HomeView Performance] use optimised artwork images for rails
  src/app/Components/ArtworkRail/ArtworkRailCardImage.tsx
Labels: performance

#12502 fix(ONYX-1820): adjust the layout of search results screens
  src/app/Components/AutosuggestResults/AutosuggestResults.tsx
  src/app/Components/GlobalSearchInput/GlobalSearchInputOverlay.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtistAutosuggest.tsx
  src/app/Scenes/Search/RecentSearches.tsx
  src/app/Scenes/Search/Search.tsx
  src/app/Scenes/Search/SearchArtworksGrid.tsx
  src/app/Scenes/Search/SearchResults.tsx
  src/app/Scenes/Search/components/AutosuggestSearchResult.tsx
  src/app/Scenes/Search/components/EntitySearchResults.tsx
Labels: Jira Synced

#12522 feat(EMI-2488): Add conversation link to order details
  src/app/Scenes/OrderHistory/OrderDetail/Components/MessageDetails.tsx
  src/app/Scenes/OrderHistory/OrderDetail/Components/OrderDetailMessage.tsx
  src/app/Scenes/OrderHistory/OrderDetail/Components/__tests__/OrderDetailMessage.tests.tsx
  src/app/Scenes/OrderHistory/OrderDetail/hooks/useOrderDetailTracking.ts
Labels: Jira Synced

#12529 fix: broken bottom padding after navigating back
  src/app/Navigation/AuthenticatedRoutes/ScreenWrapper.tsx
Labels: Jira Synced

#12530 fix: Artist screen shipping and taxes learn more layout issue for Android
  src/app/Scenes/Artwork/Components/ShippingAndTaxes.tsx
Labels: Jira Synced, Squash On Green

#12535 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12536 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12541 chore: ignore .claude/settings.local.json folder
  .gitignore
Labels: Merge On Green

#12542 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12532 chore: [HomeView Performance] impress useImpressions tracking logic
  src/app/Scenes/HomeView/hooks/useImpressionsTracking.ts
Labels: performance

#12556 chore: cleaner name setting
  src/app/utils/track/AddAppNamePlugin.ts
Labels: Squash On Green

#12563 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12566 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12560 feat(ONYX-1811): add price range onboarding to sign up
  docs/add_screen_to_onboarding_workflow.md
  docs/screenshots/onboarding-workflow.png
  src/app/Components/PriceRange/constants.ts
  src/app/Scenes/MyAccount/MyAccountEditPriceRange.tsx
  src/app/Scenes/Onboarding/OnboardingQuiz/Components/OnboardingQuestionTemplate.tsx
  src/app/Scenes/Onboarding/OnboardingQuiz/Hooks/useOnboardingContext.tsx
  src/app/Scenes/Onboarding/OnboardingQuiz/OnboardingPriceRange.tsx
  src/app/Scenes/Onboarding/OnboardingQuiz/OnboardingQuestionThree.tsx
  src/app/Scenes/Onboarding/OnboardingQuiz/OnboardingQuestionTwo.tsx
  src/app/Scenes/Onboarding/OnboardingQuiz/OnboardingQuiz.tsx
  src/app/Scenes/Onboarding/OnboardingQuiz/__tests__/OnboardingQuestionTemplate.tests.tsx
  src/app/Scenes/Onboarding/OnboardingQuiz/__tests__/config.tests.ts
  src/app/Scenes/Onboarding/OnboardingQuiz/config.ts
  src/app/Scenes/Onboarding/OnboardingQuiz/utils/__tests__/shouldShowPriceRange.tests.ts
  src/app/Scenes/Onboarding/OnboardingQuiz/utils/shouldShowPriceRange.ts
  src/app/store/config/features.ts
  src/app/system/devTools/DevMenu/Components/DevTools.tsx
  src/app/utils/WorkflowEngine/WorkflowEngine.tsx
Labels: Jira Synced, Squash On Green

#12573 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green
