Repository artsy/eigen, pull requests merged in 2025-08, with the labels that each got.

#12575 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12579 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12581 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12576 fix: bring back missing artworks from collection screen
  src/app/utils/masonryHelpers/index.tsx
Labels: Jira Synced

#12589 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12590 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12592 fix: change spec repo order to avoid dep confusion attacks
  ios/Podfile
Labels: Squash On Green

#12594 chore: add a scroll to delay deeplink test
  e2e/flows/deeplinks.yml
Labels: Jira Synced

#12595 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12591 fix: android hardware back button and gesture behavior on Profile tab
  src/app/Components/BottomSheet/AutomountedBottomSheetModal.tsx
  src/app/utils/hooks/useBackHandler.ts
Labels: Jira Synced

#12597 fix: podfile checksum
  ios/Podfile.lock
Labels: Squash On Green

#12601 fix: deeplink nav loop
  src/app/utils/fetchMarketingURL.ts
  src/app/utils/useDeepLinks.ts
Labels: Jira Synced

#12588 feat(ONYX-1812): scroll depth, onboard users into setting a price range after scrolling over We Think You'll Love
  src/app/Components/PriceRange/fetchPriceRange.tsx
  src/app/Components/ProgressiveOnboarding/ProgressiveOnboardingPriceRangeHome.tsx
  src/app/Components/Toast/ToastComponent.tsx
  src/app/Components/Toast/types.ts
  src/app/Scenes/HomeViewSectionScreen/HomeViewSectionScreenArtworks.tsx
  src/app/Scenes/HomeViewSectionScreen/hooks/useSetPriceRangeReminder.tests.tsx
  src/app/Scenes/HomeViewSectionScreen/hooks/useSetPriceRangeReminder.tsx
  src/app/Scenes/MyAccount/MyAccountEditPriceRange.tsx
  src/app/store/VisualClueModel.ts
  src/app/store/config/features.ts
  src/app/store/config/visualClues.ts
  src/app/system/devTools/DevMenu/Components/DevTools.tsx
Labels: Jira Synced, Squash On Green

#12608 fix: update onboarding navigation to use native stack and adjust screen options for orientation
  src/app/Scenes/Onboarding/Onboarding.tsx
  src/app/Scenes/Onboarding/OnboardingQuiz/OnboardingQuiz.tsx
Labels: Jira Synced

#12612 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12621 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12623 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12626 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12627 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12629 feat: hide fair date for specific Artsy Edition Shop instance
  src/app/Scenes/Fair/Components/FairHeader.tsx
  src/app/Scenes/Fair/__tests__/FairHeader.tests.tsx
Labels: Jira Synced

#12639 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12645 feat: consolidate app version handling with fallback mechanism
  src/app/Components/__tests__/ArtsyWebView.tests.tsx
  src/app/Scenes/About/About.tsx
  src/app/Scenes/MyProfile/MyProfileSettings.tsx
  src/app/store/config/EchoModel.tsx
  src/app/system/devTools/DevMenu/DevMenu.tsx
  src/app/system/errorReporting/setupSentry.ts
  src/app/system/relay/usePurgeCacheOnAppUpdate.ts
  src/app/utils/appVersion.tests.ts
  src/app/utils/appVersion.ts
Labels: Squash On Green

#12648 chore: upgrade @stripe/stripe-react-native
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: Jira Synced

#12650 fix(EMI-2739): Add empty state and error state for Order Details screen
  src/app/Scenes/OrderHistory/OrderDetails/OrderDetails.tsx
Labels: Jira Synced

#12649 chore: upgrade sift-react-native
  .circleci/config.yml
  ios/Podfile.lock
  package.json
  patches/sift-react-native+0.1.15.patch
  patches/sift-react-native+0.1.8.patch
  src/setupJest.tsx
  yarn.lock
Labels: Jira Synced, Squash On Green

#12657 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12659 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12655 chore: adjustment on force update debug message
  src/app/Scenes/ForceUpdate/ForceUpdate.tsx
Labels: Squash On Green

#12669 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12670 build(deps): bump react-native-localize to a version that supports newarch
  .circleci/config.yml
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: Jira Synced

#12672 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12677 chore: update react-native-document picker to fix compilation on new arch
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: Jira Synced

#12678 chore: c++ compilation issues on new arch
  ios/Artsy.xcodeproj/project.pbxproj
  ios/Artsy/App/ArtsyEcho.mm
  ios/Artsy/Networking/API_Modules/ARUserManager.mm
  ios/Artsy/Networking/API_Modules/ArtsyAPI+CurrentUserFunctions.m
  ios/Artsy/Networking/API_Modules/ArtsyAPI+DeviceTokens.m
  ios/Artsy/Networking/API_Modules/ArtsyAPI+Following.m
  ios/Artsy/Networking/API_Modules/ArtsyAPI+Notifications.m
  ios/Artsy/Networking/API_Modules/ArtsyAPI+Pages.m
  ios/Artsy/Networking/API_Modules/ArtsyAPI+Profiles.m
  ios/Artsy/Networking/API_Modules/ArtsyAPI+RelatedModels.m
  ios/Artsy/Networking/API_Modules/ArtsyAPI+Sales.m
  ios/Artsy/Networking/API_Modules/ArtsyAPI+SystemTime.m
  ios/Artsy/Networking/ARRouter+RestAPI.h
  ios/Artsy/Networking/ARRouter+RestAPI.m
  ios/Artsy/Networking/ARRouter.h
  ios/Artsy/Networking/ARRouter.mm
  ios/Artsy/Networking/ArtsyAPI.m
  ios/ArtsyTests/Networking_Tests/ARRouterTests.m
Labels: Jira Synced

#12661 build(refactor): maestro builds with fastlane instead of local
  .github/workflows/build-maestro-android.yml
  .github/workflows/build-maestro-ios.yml
  fastlane/Fastfile
  fastlane/utility_fastlane.rb
Labels: Squash On Green

#12687 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green
