Repository artsy/eigen, pull requests merged in 2025-03, with the labels that each got.

#11619 fix(PBRW-518): Bring back Android status bar
  src/app/Scenes/HomeView/HomeView.tsx
Labels: Jira Synced

#11611 feat: hide Bidding info for live auction in progress as it's not reliable.
  src/app/Scenes/MyBids/ActiveLotStanding.tests.tsx
  src/app/Scenes/MyBids/ClosedLotStanding.tests.tsx
  src/app/Scenes/MyBids/Components/ActiveLotStanding.tsx
  src/app/Scenes/MyBids/Components/BiddingStatuses.tsx
  src/app/Scenes/MyBids/Components/ClosedLotStanding.tsx
  src/app/Scenes/MyBids/Components/LotStatusListItem.tsx
  src/app/Scenes/Sale/Components/SaleActiveBidItem.tsx
  src/app/Scenes/Sale/Components/SaleActiveBids.tsx
  src/app/Scenes/Sale/SaleActiveBidItem.tests.tsx
Labels: Jira Synced

#11622 fix(PBRW-510): Fix issue with the app freezing after Make Offer flow
  src/app/Scenes/Inbox/Components/Conversations/OfferSubmittedModal.tests.tsx
  src/app/Scenes/Inbox/Components/Conversations/OfferSubmittedModal.tsx
Labels: Jira Synced

#11630 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11628 fix(PBRW-567): Remove "sell art" from the login screen
  src/app/Scenes/Onboarding/Auth2/components/AuthBackground.tsx
  src/app/Scenes/Onboarding/OnboardingWelcome.tsx
Labels: Jira Synced

#11595 feat: add infinite discovery onboarding skeleton
  src/app/Scenes/InfiniteDiscovery/Components/InfiniteDiscoveryOnboarding.tsx
  src/app/Scenes/InfiniteDiscovery/InfiniteDiscovery.tsx
  src/app/store/InfiniteDiscoveryModel.ts
  src/app/store/__tests__/migration.tests.ts
  src/app/store/migration.ts
  src/app/system/devTools/DevMenu/Components/DevTools.tsx
Labels: Jira Synced

#11629 feat(DIA-1165): Add an optional “Save” copy to the save widget in Eigen.
  src/app/Scenes/InfiniteDiscovery/Components/InfiniteDiscoveryArtworkCard.tsx
Labels: Jira Synced

#11601 feat(dia-1067): infinite disco bottom sheet tracking (demo)
  src/app/Components/ArtistFollowButton.tsx
  src/app/Components/PartnerFollowButton.tsx
  src/app/Scenes/Activity/components/PartnerOfferCreatedNotification.tsx
  src/app/Scenes/Artwork/Components/ArtworkCommercialButtons.tests.tsx
  src/app/Scenes/Artwork/Components/CommercialButtons/BuyNowButton.tsx
  src/app/Scenes/Artwork/Components/CommercialButtons/ContactGalleryButton.tests.tsx
  src/app/Scenes/Artwork/Components/CommercialButtons/ContactGalleryButton.tsx
  src/app/Scenes/Artwork/Components/CommercialButtons/MakeOfferButton.tsx
  src/app/Scenes/InfiniteDiscovery/Components/InfiniteDiscoveryAboutTheWorkTab.tsx
  src/app/Scenes/InfiniteDiscovery/Components/InfiniteDiscoveryBottomSheetFooter.tsx
  src/app/Scenes/InfiniteDiscovery/Components/InfiniteDiscoveryMoreWorksTab.tsx
  src/app/system/analytics/AnalyticsContext.tsx
Labels: Jira Synced

#11636 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11637 chore: revert version upgrade
  ios/Artsy.xcodeproj/project.pbxproj
  ios/Podfile
  ios/Podfile.lock
Labels: Squash On Green

#11642 chore: revert update iOS in-app push notification style
  ios/Artsy/App/ARAppDelegate.mm
  ios/Artsy/App/ARAppNotificationsDelegate.h
  ios/Artsy/App/ARAppNotificationsDelegate.m
  ios/ArtsyTests/App_Tests/ARAppNotificationsDelegateTests.m
Labels: Jira Synced, Squash On Green

#11644 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11634 chore: close out activity dot experiment
  src/app/Navigation/utils/useBottomTabsBadges.tests.ts
  src/app/Navigation/utils/useBottomTabsBadges.ts
  src/app/Scenes/HomeView/Components/ActivityIndicator.tsx
  src/app/Scenes/HomeView/HomeView.tsx
  src/app/utils/experiments/experiments.ts
  src/app/utils/experiments/useActivityDotExperiment.ts
Labels: Jira Synced

#11646 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11649 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11654 fix: prevent users from seeing rewinded cards
  src/app/Navigation/routes.tsx
Labels: Jira Synced, Squash On Green

#11661 fix: infinite discovery onboarding issues
  src/app/Scenes/InfiniteDiscovery/Components/InfiniteDiscoveryOnboarding.tsx
  src/app/Scenes/InfiniteDiscovery/Components/Swiper/Swiper.tsx
Labels: Jira Synced

#11664 fix(InfiniteDiscovery): disable gestures on infinite discovery
  src/app/Navigation/routes.tsx
Labels: Jira Synced

#11663 fix(InfiniteDiscovery): send top artwork as seen
  src/app/Navigation/routes.tsx
  src/app/Scenes/HomeView/HomeView.tsx
  src/app/Scenes/InfiniteDiscovery/InfiniteDiscovery.tsx
Labels: Jira Synced

#11659 feat(InfiniteDiscovery): add save artwork tooltip after no saves
  src/app/Scenes/InfiniteDiscovery/Components/InfiniteDiscoveryArtworkCard.tsx
  src/app/Scenes/InfiniteDiscovery/Components/Swiper/Swiper.tsx
  src/app/store/InfiniteDiscoveryModel.ts
  src/app/store/ProgressiveOnboardingModel.ts
  src/app/store/__tests__/migration.tests.ts
  src/app/store/migration.ts
Labels: Squash On Green

#11662 fix(InfiniteDiscovery): infinite discovery bottom sheet issues
  src/app/Scenes/InfiniteDiscovery/Components/InfiniteDiscoveryArtworkCard.tsx
  src/app/Scenes/InfiniteDiscovery/Components/InfiniteDiscoveryBottomSheet.tsx
  src/app/Scenes/InfiniteDiscovery/Components/InfiniteDiscoveryBottomSheetBackdrop.tsx
  src/app/Scenes/InfiniteDiscovery/Components/InfiniteDiscoveryBottomSheetFooter.tsx
  src/app/Scenes/InfiniteDiscovery/Components/InfiniteDiscoveryBottomSheetHandle.tsx
  src/app/Scenes/InfiniteDiscovery/hooks/useBottomSheetAnimatedStyles.ts
Labels: Jira Synced

#11670 fix(DIA-1201): reintroduce artwork card rotation and rounded corners
  src/app/Scenes/InfiniteDiscovery/Components/InfiniteDiscoveryArtworkCard.tsx
  src/app/Scenes/InfiniteDiscovery/Components/Swiper/AnimatedView.tsx
Labels: Jira Synced

#11671 fix(DIA-1189): Additional copy and creative fixes for Discovery Daily
  src/app/Components/Toast/types.ts
  src/app/Scenes/InfiniteDiscovery/Components/InfiniteDiscoveryOnboarding.tsx
  src/app/Scenes/InfiniteDiscovery/InfiniteDiscovery.tsx
Labels: Jira Synced

#11676 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11683 fix: Unleash client start sequence
  src/app/utils/experiments/UnleashProvider.tsx
Labels: Jira Synced

#11682 feat(Infinite-discovery): save artworks on double tap
  src/app/Scenes/InfiniteDiscovery/Components/InfiniteDiscoveryArtworkCard.tsx
Labels: Jira Synced

#11688 feat: Prefetch all links on Partner screen
  src/app/Components/Artist/ArtistShows/ArtistShow.tsx
  src/app/Navigation/routes.tsx
  src/app/Scenes/ArtistShows/ArtistShows.tests.tsx
  src/app/Scenes/ArtistShows/ArtistShows.tsx
  src/app/Scenes/Partner/Components/PartnerLocationSection.tsx
  src/app/Scenes/Partner/Components/PartnerShowRailItem.tsx
  src/app/Scenes/Partner/Components/PartnerShows.tsx
  src/app/Scenes/Partner/Components/PartnerShowsRail.tsx
  src/app/Scenes/Partner/Screens/PartnerLocations.tsx
Labels: Jira Synced

#11692 feat: Prefetch Search screen rail links
  src/app/Scenes/Search/CuratedCollectionItem.tsx
  src/app/Scenes/Search/CuratedCollections.tests.tsx
  src/app/Scenes/Search/TrendingArtists.tsx
  src/app/Scenes/Search/components/TrendingArtistCard.tsx
Labels: Jira Synced

#11694 fix(InfiniteDiscovery): resets the footer visibility to true given top artwork changed
  src/app/Scenes/InfiniteDiscovery/Components/InfiniteDiscoveryBottomSheet.tsx
Labels: Jira Synced, Squash On Green

#11657 feat(ONYX-1604): track progressive onboarding tooltips
  src/app/Components/ProgressiveOnboarding/ProgressiveOnboardingAlertFilters.tsx
  src/app/Components/ProgressiveOnboarding/ProgressiveOnboardingAlertFinish.tsx
  src/app/Components/ProgressiveOnboarding/ProgressiveOnboardingAlertReminder.tsx
  src/app/Components/ProgressiveOnboarding/ProgressiveOnboardingLongPressContextMenu.tsx
  src/app/Components/ProgressiveOnboarding/ProgressiveOnboardingOfferSettings.tsx
  src/app/Components/ProgressiveOnboarding/ProgressiveOnboardingSaveAlert.tsx
  src/app/Components/ProgressiveOnboarding/ProgressiveOnboardingSaveArtwork.tsx
  src/app/Components/ProgressiveOnboarding/ProgressiveOnboardingSignalInterest.tsx
  src/app/Components/ProgressiveOnboarding/useProgressiveOnboardingTracking.tsx
Labels: Jira Synced, Squash On Green

#11650 feat: Prefetch links on Artwork screen
  src/app/Components/ArtistListItem.tests.tsx
  src/app/Components/ArtistListItem.tsx
  src/app/Navigation/routes.tsx
  src/app/Scenes/ArtistSeries/ArtistSeries.tsx
  src/app/Scenes/ArtistSeries/ArtistSeriesFullArtistSeriesList.tsx
  src/app/Scenes/ArtistSeries/ArtistSeriesMoreSeries.tsx
  src/app/Scenes/Artwork/Components/ArtworkDetails.tsx
  src/app/Scenes/Artwork/Components/ArtworkMakerTitle.tsx
  src/app/Scenes/Artwork/Components/ArtworksInSeriesRail.tsx
  src/app/Scenes/Artwork/Components/ContextCard.tsx
  src/app/Scenes/Artwork/Components/OtherWorks/ContextGridCTA.tsx
  src/app/Scenes/Artwork/Components/PartnerCard.tsx
  src/app/Scenes/Artwork/Components/ShortContactGallery.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtistItem.tsx
  src/app/Scenes/MyCollection/Components/SelectArtistToShareListItem.tsx
  src/app/Scenes/Partner/Partner.tsx
  src/app/system/navigation/navigate.ts
Labels: Jira Synced, Squash On Green

#11699 fix: Use Palettes Touchable component for RouterLinks
  src/app/Scenes/Articles/News/ArticlesCards.tsx
  src/app/system/navigation/RouterLink.tsx
Labels: Jira Synced, Squash On Green

#11703 fix(DIA-1116): Refactored Onboarding Art Quiz header
  src/app/Scenes/Onboarding/OnboardingQuiz/Components/OnboardingQuestionTemplate.tsx
  src/app/Scenes/Onboarding/OnboardingQuiz/__tests__/OnboardingQuestionTemplate.tests.tsx
Labels: Jira Synced

#11706 fix(full-screen-image): Fixes fullscreen close button issues
  src/app/Scenes/Artwork/Components/ImageCarousel/FullScreen/ImageCarouselCloseButton.tsx
  src/app/Scenes/Artwork/Components/ImageCarousel/FullScreen/ImageCarouselFullScreenAndroid.tsx
  src/app/Scenes/InfiniteDiscovery/Components/__tests__/InfiniteDiscoveryAboutTheWorkTab.tests.tsx
Labels: Jira Synced

#11700 feat: Prefetch links on Viewing Room screen
  src/app/Components/AnimatedBottomButton.tsx
  src/app/Scenes/ViewingRoom/Components/ViewingRoomArtworkRail.tsx
  src/app/Scenes/ViewingRoom/Components/ViewingRoomHeader.tsx
  src/app/Scenes/ViewingRoom/Components/ViewingRoomViewWorksButton.tsx
  src/app/Scenes/ViewingRoom/Components/ViewingRoomsHomeRail.tsx
  src/app/Scenes/ViewingRoom/Components/ViewingRoomsListFeatured.tsx
  src/app/Scenes/ViewingRoom/Components/ViewingRoomsListItem.tsx
  src/app/Scenes/ViewingRoom/ViewingRoom.tsx
  src/app/Scenes/ViewingRoom/ViewingRoomArtwork.tsx
  src/app/Scenes/ViewingRoom/ViewingRoomArtworks.tests.tsx
  src/app/Scenes/ViewingRoom/ViewingRoomArtworks.tsx
Labels: Jira Synced, Squash On Green

#11686 feat: add Favorites tab to bottom navigation
  src/app/Navigation/AuthenticatedRoutes/FavoritesTab.tsx
  src/app/Navigation/AuthenticatedRoutes/Tabs.tsx
  src/app/Navigation/routes.tsx
  src/app/Scenes/BottomTabs/BottomTabType.ts
  src/app/Scenes/BottomTabs/BottomTabsIcon.tsx
  src/app/Scenes/BottomTabs/bottomTabsConfig.tsx
  src/app/Scenes/Favorites/AlertsTab.tsx
  src/app/Scenes/Favorites/Favorites.tsx
  src/app/Scenes/Favorites/FavoritesContextStore.tsx
  src/app/Scenes/Favorites/FollowsTab.tsx
  src/app/Scenes/Favorites/SavesTab.tsx
  src/app/Scenes/LegacyFavorites/FavoriteArtists.tsx
  src/app/Scenes/LegacyFavorites/FavoriteCategories.tsx
  src/app/Scenes/LegacyFavorites/FavoriteShows.tsx
  src/app/Scenes/LegacyFavorites/Favorites.tsx
  src/app/store/config/features.ts
Labels: Jira Synced, Squash On Green

#11653 fix(ONYX-1589): add long press tracking, fix Create Alert tracking
  src/app/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
  src/app/Components/Artist/ArtistArtworks/CreateArtworkAlertModal.tests.tsx
  src/app/Components/Artist/ArtistArtworks/CreateArtworkAlertModal.tsx
  src/app/Components/Artist/ArtistArtworks/SavedSearchButtonV2.tsx
  src/app/Components/ArtworkFilter/ArtworkFilterNavigator.tsx
  src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
  src/app/Components/ArtworkRail/ArtworkRailCard.tsx
  src/app/Components/ContextMenu/ContextMenuArtwork.tsx
  src/app/Scenes/Activity/components/NotificationCommercialButtons.tsx
  src/app/Scenes/Artwork/ArtworkAuctionCreateAlertHeader.tsx
  src/app/Scenes/Artwork/Components/ArtworkScreenHeaderCreateAlert.tsx
  src/app/Scenes/Collection/Screens/CollectionArtworks.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArtworks.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionFeaturedCollection.tsx
  src/app/Scenes/SavedSearchAlert/CreateSavedSearchModal.tests.tsx
  src/app/Scenes/SavedSearchAlert/CreateSavedSearchModal.tsx
  src/app/Scenes/SavedSearchAlert/useCreateAlertTracking.ts
Labels: Jira Synced

#11673 feat: Prefetch links on Artist screen
  src/app/Components/Artist/Articles/Article.tsx
  src/app/Components/Artist/Articles/Articles.tsx
  src/app/Components/Artist/ArtistAbout/ArtistAboutEmpty.tsx
  src/app/Components/Artist/ArtistHeader.tsx
  src/app/Components/Artist/ArtistInsights/ArtistInsightsAuctionResults.tsx
  src/app/Components/Artist/ArtistInsights/ArtistsInsightsEmpty.tsx
  src/app/Components/Artist/ArtistShows/ArtistShow.tsx
  src/app/Components/Artist/RelatedArtistsRailCell.tsx
  src/app/Components/LatestAuctionResultsRail.tsx
  src/app/Components/Lists/AuctionResultListItem.tests.tsx
  src/app/Components/Lists/AuctionResultListItem.tsx
  src/app/Navigation/routes.tsx
  src/app/Scenes/ArtistArticles/ArtistArticles.tsx
  src/app/Scenes/ArtistSeries/ArtistSeriesFullArtistSeriesList.tsx
  src/app/Scenes/ArtistSeries/ArtistSeriesListItem.tests.tsx
  src/app/Scenes/ArtistSeries/ArtistSeriesListItem.tsx
  src/app/Scenes/ArtistSeries/ArtistSeriesMoreSeries.tests.tsx
  src/app/Scenes/AuctionResult/AuctionResult.tsx
  src/app/Scenes/AuctionResult/ComparableWorks.tsx
  src/app/Scenes/Gene/Gene.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkArtistAuctionResults.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkComparableWorks.tsx
  src/app/Scenes/MyCollection/Screens/Insights/AuctionResultsForArtistsYouCollectRail.tsx
Labels: Jira Synced

#11705 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11707 fix: Re-prefetch queries when they have been garbage collected
  src/app/system/navigation/RouterLink.tsx
  src/app/utils/queryPrefetching.ts
Labels: Jira Synced

#11710 fix: make only artwork image tappable
  src/app/Scenes/InfiniteDiscovery/Components/InfiniteDiscoveryArtworkCard.tsx
Labels: Squash On Green

#11708 feat: Prefetch links on Fair screen
  src/app/Navigation/routes.tsx
  src/app/Scenes/Fair/Components/FairCollections.tsx
  src/app/Scenes/Fair/Components/FairEditorial.tsx
  src/app/Scenes/Fair/Components/FairExhibitorRail.tsx
  src/app/Scenes/Fair/Components/FairFollowedArtistsRail.tsx
  src/app/Scenes/Fair/FairAllFollowedArtists.tsx
  src/app/Scenes/Fair/FairArticles.tsx
  src/app/Scenes/Fair/FairMoreInfo.tsx
  src/app/Scenes/Fair/FairOverview.tsx
Labels: Jira Synced

#11712 fix: Artwork card context menu with dark background.
  src/app/Components/ContextMenu/ContextMenuArtwork.tsx
Labels: Jira Synced, Squash On Green

#11714 chore: setup internal testing experiment
  src/app/Scenes/HomeView/HomeView.tsx
  src/app/system/flags/experiments.ts
Labels: Squash On Green

#11715 fix: fix progressive onboarding tooltips
  src/app/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx
  src/app/Components/ProgressiveOnboarding/ProgressiveOnboardingAlertFilters.tsx
  src/app/Components/ProgressiveOnboarding/ProgressiveOnboardingAlertReminder.tsx
  src/app/Components/ProgressiveOnboarding/ProgressiveOnboardingLongPressContextMenu.tsx
  src/app/Components/ProgressiveOnboarding/ProgressiveOnboardingSaveAlert.tsx
  src/app/Components/ProgressiveOnboarding/ProgressiveOnboardingSaveArtwork.tsx
  src/app/Components/ProgressiveOnboarding/ProgressiveOnboardingSignalInterest.tsx
  src/app/store/ProgressiveOnboardingModel.ts
  src/app/system/devTools/DevMenu/DevMenuWrapper.tsx
  src/setupJest.tsx
Labels: Squash On Green

#11719 feat: Prefetch all links on Activity screen
  src/app/Scenes/Activity/ActivityEmptyView.tsx
  src/app/Scenes/Activity/components/AlertNotification.tsx
  src/app/Scenes/Activity/components/ArticleFeaturedArtistNotification.tsx
  src/app/Scenes/Activity/components/ArtworkPublishedNotification.tsx
  src/app/Scenes/Activity/components/NotificationCommercialButtons.tsx
  src/app/Scenes/Activity/components/PartnerOfferCreatedNotification.tsx
  src/app/Scenes/Activity/components/ViewingRoomPublishedNotificationsList.tsx
  src/app/Scenes/SavedSearchAlert/EditSavedSearchAlert.tsx
  src/app/Scenes/SavedSearchAlert/SavedSearchAlert.tsx
Labels: Jira Synced

#11725 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11728 feat: add follows to favorites tab
  src/app/Scenes/Favorites/Components/FollowedArtists.tests.tsx
  src/app/Scenes/Favorites/Components/FollowedArtists.tsx
  src/app/Scenes/Favorites/Components/FollowedGalleries.tests.tsx
  src/app/Scenes/Favorites/Components/FollowedGalleries.tsx
  src/app/Scenes/Favorites/Components/FollowedShows.tests.tsx
  src/app/Scenes/Favorites/Components/FollowedShows.tsx
  src/app/Scenes/Favorites/Favorites.tsx
  src/app/Scenes/Favorites/FollowsTab.tsx
Labels: Jira Synced, Squash On Green

#11733 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11734 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11735 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11732 feat(ONYX-1606): increase title size on Activity and Favorites
  src/app/Scenes/Activity/Activity.tsx
  src/app/Scenes/Activity/components/ActivityHeader.tsx
  src/app/Scenes/Favorites/Favorites.tsx
Labels: Jira Synced, Squash On Green

#11720 feat: Replace remaining Touchables with RouterLink for navigation
  src/app/Components/ArtistListItemShort.tsx
  src/app/Components/ArtworkRail/ArtworkRail.tsx
  src/app/Components/BrowseMoreRailCard.tsx
  src/app/Components/LatestAuctionResultsRail.tsx
  src/app/Components/MenuItem.tsx
  src/app/Components/PartnerEntityHeader.tsx
  src/app/Components/PartnerListItemShort.tsx
  src/app/Components/ShowItem.tsx
  src/app/Scenes/About/About.tsx
  src/app/Scenes/ArtworkLists/ArtworkListItem.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionAuctionResults.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionFeaturedCollection.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionSales.tsx
  src/app/Scenes/MyAccount/MyAccount.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkAbout/MyCollectionArtworkArticles.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/ArtworkInsights/MyCollectionArtworkArtistArticles.tsx
  src/app/Scenes/MyProfile/MyProfilePayment.tsx
  src/app/Scenes/MyProfile/MyProfileSettings.tsx
  src/app/Scenes/PriceDatabase/components/PriceDatabaseBenefits.tsx
  src/app/Scenes/Sale/Components/SaleArtworkListItem.tsx
  src/app/Scenes/SaleInfo/SaleInfo.tsx
  src/app/Scenes/Sales/Components/SaleListItem.tsx
  src/app/Scenes/SavedSearchAlert/Components/SavedSearchSuggestedFilters.tsx
  src/app/Scenes/Search/components/CityGuideCTA.tsx
Labels: Jira Synced, Squash On Green

#11739 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11740 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11741 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11742 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11738 fix: "Profile" tab prefetching
  src/app/Navigation/routes.tsx
  src/app/Scenes/MyCollection/MyCollection.tsx
  src/app/Scenes/MyProfile/MyProfileHeader.tsx
Labels: Jira Synced

#11745 fix: Increase Artwork grid page size and threshold
  src/app/utils/masonryHelpers/index.tsx
Labels: Jira Synced, Squash On Green

#11747 build(ci): remove react-native-config remains
  .circleci/config.yml
Labels: Squash On Green, FF

#11748 build(deps): bumps flashlist and palette-mobile to latest
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: Squash On Green, FF

#11752 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11743 chore(infinite-discovery): Add some polish on swipe back
  src/app/Scenes/InfiniteDiscovery/Components/Swiper/Swiper.tsx
Labels: Squash On Green

#11753 chore: bump @gorhom/bottom-sheet from 5.0.5 to 5.1.2
  package.json
  yarn.lock
Labels: Merge On Green

#11737 feat(ONYX-1601): add saves view
  src/app/Scenes/ArtworkLists/ArtworkLists.tsx
  src/app/Scenes/Favorites/Components/SavesHeader.tsx
  src/app/Scenes/Favorites/Favorites.tsx
  src/app/Scenes/Favorites/SavesTab.tsx
Labels: Jira Synced

#11702 feat(ONYX-1609, ONYX-1610): adjust Offer settings and Create new List modals
  src/app/Components/ArtworkLists/ArtworkListsContext.tests.tsx
  src/app/Components/ArtworkLists/components/ArtworkListImagePreview.tsx
  src/app/Components/ArtworkLists/components/ArtworkListItem.tsx
  src/app/Components/ArtworkLists/components/ArtworkListsBottomSheetSectionTitle.tsx
  src/app/Components/ArtworkLists/components/CreateOrEditArtworkListForm.tsx
  src/app/Components/ArtworkLists/views/ArtworkListOfferSettingsView/components/ArtworkListOfferSettings.tsx
  src/app/Components/ArtworkLists/views/ArtworkListOfferSettingsView/components/ArtworkListOfferSettingsHeader.tsx
  src/app/Components/ArtworkLists/views/CreateNewArtworkListView/CreateNewArtworkListView.tests.tsx
  src/app/Components/ArtworkLists/views/CreateNewArtworkListView/CreateNewArtworkListView.tsx
  src/app/Components/ArtworkLists/views/CreateNewArtworkListView/components/CreateNewArtworkListForm.tsx
  src/app/Scenes/ArtworkList/ManageArtworkListMenuItem.tsx
  src/app/Scenes/ArtworkList/ManageArtworkListView.tsx
  src/app/Scenes/ArtworkList/views/DeleteArtworkListView/DeleteArtworkListView.tsx
  src/app/Scenes/ArtworkList/views/EditArtworkListView/EditArtworkListView.tsx
Labels: Squash On Green

#11754 fix(DIA-1233): other works tab doesn't scroll on android
  src/app/Scenes/InfiniteDiscovery/Components/InfiniteDiscoveryMoreWorksTab.tsx
Labels: Jira Synced

#11757 build(deps): bump react-native-image-crop-picker to latest
  .circleci/config.yml
  ios/Podfile.lock
  package.json
  patches/react-native-image-crop-picker+0.42.0.patch
  yarn.lock
Labels: Jira Synced, Squash On Green

#11762 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11764 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11765 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11766 chore: Refactor screens to use network policy instead of cache config
  src/app/Navigation/routes.tsx
  src/app/Scenes/Artist/SearchCriteria.tsx
  src/app/Scenes/ArtistShows/ArtistShows.tsx
  src/app/Scenes/Artwork/Artwork.tsx
  src/app/Scenes/AuctionResults/AuctionResultsForArtistsYouFollow.tsx
  src/app/Scenes/AuctionResults/AuctionResultsScreenWrapper.tsx
  src/app/Scenes/Collection/Components/FullFeaturedArtistList.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionBottomSheetModals/MyCollectionBottomSheetModalArtistPreview.tsx
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/ArtworkAutosuggestResults.tsx
  src/app/Scenes/MyProfile/MyProfilePayment.tsx
  src/app/Scenes/SavedSearchAlert/EditSavedSearchAlert.tsx
  src/app/Scenes/SavedSearchAlert/containers/CreateSavedSearchContentContainer.tsx
  src/app/Scenes/SavedSearchAlert/queries/getAlertByCriteria.ts
  src/app/Scenes/SavedSearchAlertsList/SavedSearchAlertsList.tsx
Labels: Jira Synced

#11761 feat: add Learn more bottom sheet to Favorites tab
  src/app/Scenes/Favorites/Components/CollapseWithTitle.tsx
  src/app/Scenes/Favorites/Components/FavoritesLearnMore.tsx
  src/app/Scenes/Favorites/Favorites.tsx
Labels: Jira Synced

#11771 fix: add missing suspense to Favorites
  src/app/Scenes/ArtworkLists/ArtworkLists.tsx
  src/app/Scenes/Favorites/Favorites.tsx
Labels: Squash On Green

#11773 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11770 fix(EMI-2347): Remove estimated values when bidding has closed
  src/app/Scenes/Artwork/Artwork.tsx
Labels: Jira Synced

#11768 chore: update follows radio buttons
  package.json
  src/app/Scenes/Activity/Activity.tsx
  src/app/Scenes/Favorites/Favorites.tsx
  src/app/Scenes/Favorites/FollowsTab.tsx
  yarn.lock
Labels: Squash On Green

#11781 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11778 feat: prepare settings tab redesign
  src/app/Scenes/About/About.tsx
  src/app/Scenes/MyProfile/Components/MyProfileHeader.tsx
  src/app/Scenes/MyProfile/MyProfile.tsx
  src/app/Scenes/MyProfile/MyProfileSettings.tsx
  src/app/store/config/features.ts
  src/app/system/devTools/useSetDevMode.tsx
Labels: Jira Synced

#11784 refactor(ContextGridCTA): convert class component to functional component and fix tracking
  src/app/Scenes/Artwork/Components/OtherWorks/ContextGridCTA.tsx
Labels: Jira Synced, Squash On Green

#11788 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11789 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11791 fix: redirect to Follows doesn't work
  src/app/Navigation/routes.tsx
Labels: Squash On Green

#11790 chore: add tracking to account settings
  src/app/Scenes/MyProfile/MyProfileSettings.tsx
Labels: Jira Synced

#11792 fix: navigation to favorites
  src/app/Navigation/routes.tests.ts
  src/app/Navigation/routes.tsx
  src/app/Scenes/BottomTabs/bottomTabsConfig.tsx
  src/app/Scenes/Favorites/Components/AlertsList.tsx
  src/app/Scenes/LegacyFavorites/LegacyFavorites.tsx
Labels: Squash On Green

#11786 fix(DIA-1239): artist avatar is slow to load in discover daily
  src/app/Components/ArtistListItem.tsx
Labels: Jira Synced

#11793 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11794 chore: remove new favorites route, hide activity if ff is enabled
  src/app/Navigation/routes.tests.ts
  src/app/Navigation/routes.tsx
  src/app/Scenes/MyProfile/MyProfileHeader.tsx
Labels: Squash On Green

#11795 chore: remove pull to refresh from the saved lists modal
  src/app/Components/ArtworkLists/components/ArtworkLists.tsx
Labels: Jira Synced, Squash On Green

#11797 fix(PBRW-610): Broken artwork context menu on Android
  src/app/Components/ContextMenu/ContextMenuArtwork.tsx
  src/app/Components/ContextMenu/ContextMenuArtworkPreviewCard.tests.tsx
Labels: Jira Synced, Squash On Green

#11801 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11802 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11803 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11804 build(deps): bump react-native-share to latest
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: Jira Synced

#11808 fix: missing tappedCardGroup event on home screen
  src/app/Scenes/HomeView/Sections/HomeViewSectionCardsChips.tsx
  src/app/Scenes/HomeView/Sections/__tests__/HomeViewSectionCardsChips.tests.tsx
Labels: Squash On Green

#11813 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green
