Repository artsy/eigen, pull requests merged in 2025-04, with the labels that each got.

#11814 fix: double navigation on android notifications
  .secrets.baseline
  src/app/utils/PushNotification.tests.ts
  src/app/utils/PushNotification.ts
Labels: Jira Synced

#11817 fix: alerts view screen fixes
  src/app/Scenes/Favorites/Components/Alerts.tsx
  src/app/Scenes/Favorites/Components/AlertsList.tests.tsx
  src/app/Scenes/Favorites/Components/AlertsList.tsx
  src/app/Scenes/Favorites/Components/AlertsSortByModal.tsx
  src/app/Scenes/SavedSearchAlert/CreateSavedSearchAlert.tsx
  src/app/Scenes/SavedSearchAlertsList/Components/AlertBottomSheet.tsx
  src/app/Scenes/SavedSearchAlertsList/Components/EmptyMessage.tsx
  src/app/Scenes/SavedSearchAlertsList/Components/SavedSearchListItem.tsx
  src/app/Scenes/SavedSearchAlertsList/Components/SavedSearchesList.tests.tsx
  src/app/Scenes/SavedSearchAlertsList/Components/SavedSearchesList.tsx
Labels: Jira Synced, Squash On Green

#11819 fix: fit messages to viewport on tablets
  src/app/Scenes/Inbox/Components/Conversations/Messages.tsx
Labels: Jira Synced, Squash On Green

#11818 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11820 fix: android navigation issues
  src/app/Scenes/Onboarding/Onboarding.tsx
  src/app/Scenes/Onboarding/OnboardingCreateAccount/Onboarding.tests.tsx
  src/app/system/devTools/DevMenu/DevMenu.tsx
Labels: Squash On Green

#11812 fix: improve push notification permission handling and tracking
  ios/Artsy/App/ARAppNotificationsDelegate.m
  ios/Artsy/Constants/ARAppConstants.h
  ios/Artsy/Constants/ARAppConstants.m
  src/app/utils/requestPushNotificationsPermission.ts
Labels: Jira Synced

#11823 build(deps): bump pod-install to latest
  package.json
  yarn.lock
Labels: Squash On Green

#11822 fix(PBRW-558): Fix error on tapping Make Offer
  src/app/Scenes/Artwork/Components/ArtworkCommercialButtons.tests.tsx
  src/app/Scenes/Artwork/Components/ArtworkCommercialButtons.tsx
Labels: Jira Synced

#11829 fix(DIA-1261): cannot read property internalID of undefined in Discover Daily
  src/app/Scenes/InfiniteDiscovery/Components/Swiper/Swiper.tsx
Labels: Squash On Green

#11830 fix: Sentinel component "maximum update depth exceeded" error
  src/app/utils/Sentinel.tsx
Labels: Jira Synced

#11831 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11833 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11834 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11837 build(deps): bump react-native from 0.76.7 to 0.76.9
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: Squash On Green

#11839 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11838 chore: update sentry to fix compilation error
  ios/Podfile.lock
  package.json
  src/app/Navigation/Navigation.tsx
  src/app/system/errorReporting/setupSentry.ts
  yarn.lock
Labels: Jira Synced, Squash On Green

#11841 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11843 build(releases): update sentry url to production
  fastlane/sentry_fastlane.rb
Labels: Squash On Green, FF

#11847 build(deps): update react-tracking to latesT
  package.json
  yarn.lock
Labels: Squash On Green

#11848 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11849 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11854 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11855 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11856 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11857 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11851 fix: Replace black30 text color with black60 for higher contrast
  src/app/Components/AnimatableHeader/AnimatableHeader.tsx
  src/app/Components/ArtworkFilter/components/ArtworkFilterApplyButton.tsx
  src/app/Components/NavigationHeader.tsx
  src/app/Scenes/Inbox/Components/Conversations/ConversationSnippet.tsx
  src/app/Scenes/Inbox/Components/Conversations/Messages.tests.tsx
  src/app/Scenes/Inbox/Components/Conversations/TimeSince.tsx
Labels: Jira Synced, Squash On Green

#11845 fix: favorites tab Wrapper issues
  src/app/Scenes/ArtworkLists/ArtworkLists.tsx
  src/app/Scenes/Favorites/Components/FavoritesLearnMore.tsx
  src/app/Scenes/Favorites/SavesTab.tsx
Labels: Jira Synced

#11832 fix(DIA-1173): some users cannot send password reset emails
  .circleci/config.yml
  .secrets.baseline
  src/app/store/AuthModel.ts
  src/app/store/__tests__/AuthModel.tests.ts
  src/app/utils/PushNotification.tests.ts
Labels: Jira Synced

#11861 fix: remove Apple Pay Mark Icon
  src/app/Scenes/OrderHistory/OrderDetails/Components/OrderDetailsPayment.tsx
Labels: Squash On Green

#11815 feat(ONYX-1633): add tracking events
  src/app/Scenes/ArtworkLists/ArtworkListItem.tsx
  src/app/Scenes/BottomTabs/BottomTabType.ts
  src/app/Scenes/Favorites/Components/Alerts.tsx
  src/app/Scenes/Favorites/Components/AlertsList.tsx
  src/app/Scenes/Favorites/Components/FavoritesLearnMore.tsx
  src/app/Scenes/Favorites/Components/SavesHeader.tsx
  src/app/Scenes/Favorites/Favorites.tsx
  src/app/Scenes/Favorites/FollowsTab.tsx
  src/app/Scenes/Favorites/SavesTab.tsx
  src/app/Scenes/Favorites/useFavoritesTracking.ts
  src/app/Scenes/SavedSearchAlert/AlertArtworksGrid.tsx
Labels: Jira Synced, Squash On Green

#11870 fix: bootsplash sentry crash report
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: Jira Synced, Squash On Green

#11874 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11876 chore: add TappedFollowsGroup event
  package.json
  src/app/Scenes/Favorites/Components/FollowedArtists.tsx
  src/app/Scenes/Favorites/Components/FollowedGalleries.tsx
  src/app/Scenes/Favorites/useFavoritesTracking.ts
  yarn.lock
Labels: Squash On Green

#11880 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11878 chore: remove brew installed detect secrets
  Brewfile
  scripts/utils/install_detect_secrets.sh
Labels: Squash On Green

#11886 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11887 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11888 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11867 fix: More Home view prefetching and better test coverage
  .secrets.baseline
  src/app/Components/Cards/CardWithMetaData.tsx
  src/app/Scenes/HomeView/Components/ActivityRail.tests.tsx
  src/app/Scenes/HomeView/Components/ActivityRail.tsx
  src/app/Scenes/HomeView/Components/HeroUnit.tests.tsx
  src/app/Scenes/HomeView/Components/HeroUnit.tsx
  src/app/Scenes/HomeView/Components/ShowsRail.tests.tsx
  src/app/Scenes/HomeView/Components/ShowsRail.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionActivity.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArticlesCards.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionCard.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionHeroUnits.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionMarketingCollections.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionMarketingCollectionsItem.tsx
  src/app/Scenes/HomeView/Sections/__tests__/HomeViewSectionActivity.tests.tsx
  src/app/Scenes/HomeView/Sections/__tests__/HomeViewSectionArticlesCards.tests.tsx
  src/app/Scenes/HomeView/Sections/__tests__/HomeViewSectionCard.tests.tsx
  src/app/Scenes/HomeView/Sections/__tests__/HomeViewSectionHeroUnits.tests.tsx
  src/app/Scenes/HomeView/Sections/__tests__/HomeViewSectionMarketingCollections.tests.tsx
Labels: Jira Synced, Squash On Green

#11893 chore: add comment on navigation emittence
  src/app/Scenes/Favorites/Favorites.tsx
Labels: Squash On Green

#11899 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11901 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11903 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11905 fix: Add prepareVariables to follows route
  src/app/Navigation/routes.tsx
Labels: Squash On Green

#11898 chore: revert modular headers (#11718)"
  HACKS.md
  ios/Artsy.xcodeproj/project.pbxproj
  ios/Artsy/App/ARAppDelegate.mm
  ios/Artsy/App/ARAppNotificationsDelegate.m
  ios/Artsy/ArtsyUIButtons/ARButtonSubclasses.m
  ios/Artsy/Extraction/ARSpinner.m
  ios/Artsy/Resources/Artsy-Bridging-Header.h
  ios/Artsy/View_Controllers/ARVIR/VCs/ARAugmentedFloorBasedVIRViewController.m
  ios/Artsy/View_Controllers/ARVIR/VCs/ARAugmentedVIRSetupViewController.m
  ios/Artsy/View_Controllers/ARVIR/Views/ARInformationView.m
  ios/Artsy/View_Controllers/Util/ARNavigationController.m
  ios/Artsy/View_Controllers/Util/Logging/ARLogger.h
  ios/ArtsyTests/App_Tests/ARAppNotificationsDelegateTests.m
  ios/Podfile
  ios/Podfile.lock
Labels: Jira Synced

#11908 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11912 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11891 feat: make header favorites tab header non sticky
  src/app/Scenes/Favorites/Favorites.tsx
  src/app/Scenes/Favorites/FavoritesContextStore.tsx
Labels: Jira Synced

#11914 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11915 feat: Add dark mode support to web views
  src/app/Components/ArtsyWebView.tests.tsx
  src/app/Components/ArtsyWebView.tsx
Labels: Jira Synced, Squash On Green

#11916 fix: tab bar label position on tablets
  src/app/Navigation/AuthenticatedRoutes/Tabs.tsx
Labels: Jira Synced, Squash On Green

#11918 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11907 feat: update login and security screens UI
  src/app/Components/SectionTitle.tsx
  src/app/Navigation/routes.tsx
  src/app/Scenes/MyAccount/MyAccount.tests.tsx
  src/app/Scenes/MyAccount/MyAccount.tsx
  src/app/Scenes/MyAccount/MyAccountEditEmail.tests.tsx
  src/app/Scenes/MyAccount/MyAccountEditEmail.tsx
  src/app/Scenes/MyAccount/MyAccountEditPassword.tests.tsx
  src/app/Scenes/MyAccount/MyAccountEditPassword.tsx
  src/app/Scenes/MyAccount/MyAccountEditPhone.tests.tsx
  src/app/Scenes/MyAccount/MyAccountEditPhone.tsx
  src/app/Scenes/MyProfile/Components/MyProfileScreenWrapper.tsx
  src/app/Scenes/MyProfile/MyProfileSettings.tsx
  src/app/Scenes/Onboarding/OnboardingSocialLink.tsx
  src/app/utils/LinkedAccounts/apple.ts
  src/app/utils/LinkedAccounts/facebook.ts
  src/app/utils/LinkedAccounts/google.ts
Labels: Jira Synced

#11919 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11921 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11922 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11923 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11924 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11928 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11929 fix: Re-render app on theme change
  src/app/Providers.tsx
Labels: Squash On Green

#11930 fix: Make dark mode settings radio button pressable
  src/app/Scenes/MyProfile/DarkModeSettings.tests.tsx
  src/app/Scenes/MyProfile/DarkModeSettings.tsx
Labels: Squash On Green

#11931 fix: Text color on save artwork toast in dark mode
  src/app/Scenes/InfiniteDiscovery/InfiniteDiscovery.tsx
Labels: Squash On Green

#11935 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11936 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11939 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11940 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11942 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11943 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11946 fix(tests): after merging AREnableFavoritesTab
  src/app/Scenes/MyProfile/MyProfileHeader.tests.tsx
Labels: Squash On Green

#11933 fix: Set UIUserInterfaceStyle to Automatic to adopt system color theme
  ios/Artsy/App_Resources/Info.plist
Labels: Jira Synced

#11917 feat: Prefetch Search result items
  src/app/Components/Artist/ArtistArtworks/ArtistArtworks.tsx
  src/app/Scenes/Artist/Artist.tsx
  src/app/Scenes/Search/components/AutosuggestSearchResult.tests.tsx
  src/app/Scenes/Search/components/AutosuggestSearchResult.tsx
  src/app/system/navigation/navigate.ts
  src/setupJest.tsx
Labels: Jira Synced

#11949 build(deps): bump react-native-clipboard to latest version
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: Squash On Green

#11957 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11955 feat(ONYX-1643): update menu item
  src/app/Components/MenuItem.tests.tsx
  src/app/Components/MenuItem.tsx
  src/app/Scenes/About/About.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionBottomSheetModals/MyCollectionBottomSheetModalAdd.tsx
  src/app/Scenes/MyProfile/MyProfileSettings.tsx
  src/app/Scenes/Playground/Animation/L5-Exercice/index.tsx
  src/app/Scenes/SavedSearchAlert/Components/Form.tsx
  src/app/Scenes/SavedSearchAlert/Components/SavedSearchSuggestedFilters.tsx
Labels: Jira Synced, Squash On Green

#11964 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11965 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11972 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11973 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11975 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11976 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11978 chore: Add ARDarkModeSupport echo flag key
  src/app/store/config/features.ts
Labels: Jira Synced, Squash On Green

#11967 chore: add artsy icons check eslint rule
  .eslintrc.js
  eslint-local-rules.js
  package.json
  yarn.lock
Labels: Squash On Green

#11981 chore: Mark ARDarkModeSupport as ready for release
  src/app/store/config/features.ts
Labels: Jira Synced, Squash On Green

#11979 chore: Upgrade palette-mobile to v17.2.0
  package.json
  yarn.lock
Labels: Squash On Green

#11982 fix: removed additional triggered home view event
  src/app/Navigation/AuthenticatedRoutes/Tabs.tsx
  src/app/Scenes/HomeView/HomeView.tsx
Labels: Squash On Green

#11991 fix: discover daily missing from home view
  ios/Artsy.xcodeproj/project.pbxproj
  src/app/Scenes/HomeView/Sections/HomeViewSectionCard.tsx
  src/app/Scenes/InfiniteDiscovery/Components/InfiniteDiscoveryArtworkCard.tsx
  src/app/Scenes/InfiniteDiscovery/InfiniteDiscovery.tsx
Labels: Squash On Green

#11971 fix(DIA-1249): follow-up tweaks for multiple artwork images in Discover Daily
  src/app/Scenes/InfiniteDiscovery/Components/InfiniteDiscoveryArtworkCard.tsx
Labels: Squash On Green

#11987 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11985 fix: Favorites screen dark mode pill icon color
  package.json
  src/app/Scenes/Favorites/Favorites.tsx
  yarn.lock
Labels: Squash On Green

#11990 fix: fix refresh control on the payment screen
  src/app/Scenes/Favorites/Components/FollowedArtists.tsx
  src/app/Scenes/MyProfile/Components/MyProfileScreenWrapper.tsx
  src/app/Scenes/MyProfile/MyProfilePayment.tsx
Labels: Squash On Green

#11993 feat: update notifications screen to use new UI
  src/app/Navigation/routes.tsx
  src/app/Scenes/MyAccount/MyAccountEditPriceRange.tests.tsx
  src/app/Scenes/MyAccount/MyAccountEditPriceRange.tsx
  src/app/Scenes/MyProfile/Components/MyProfileScreenWrapper.tsx
  src/app/Scenes/MyProfile/DarkModeSettings.tsx
  src/app/Scenes/MyProfile/MyProfilePreferences.tsx
  src/app/Scenes/MyProfile/MyProfilePrivacy.tsx
  src/app/Scenes/MyProfile/MyProfilePushNotifications.tests.tsx
  src/app/Scenes/MyProfile/MyProfilePushNotifications.tsx
  src/app/Scenes/MyProfile/MyProfileSettings.tsx
  src/app/Scenes/MyProfile/MyProfileTermsAndConditions.tsx
  src/app/Scenes/PrivacyRequest/PrivacyRequest.tsx
Labels: Jira Synced, Squash On Green

#11999 fix: sentry sourcemaps attempt
  fastlane/sentry_fastlane.rb
  index.android.js
  index.ios.js
  index.js
  ios/Artsy.xcodeproj/project.pbxproj
  package.json
  scripts/hermes/hermes-android-bundle.sh
  scripts/hermes/hermes-ios-bundle.sh
Labels: Jira Synced

#12006 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11994 feat: Dark mode onboarding
  src/app/Scenes/HomeView/HomeView.tsx
  src/app/Scenes/HomeView/hooks/useDarkModeOnboarding.tests.tsx
  src/app/Scenes/HomeView/hooks/useDarkModeOnboarding.tsx
  src/app/store/ProgressiveOnboardingModel.ts
  src/app/store/config/features.ts
Labels: Jira Synced, Squash On Green

#12001 feat: prepare collector profile skeleton
  src/app/Components/constants.ts
  src/app/Navigation/routes.tsx
  src/app/Scenes/Favorites/Favorites.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionStickyHeader.tsx
  src/app/Scenes/MyCollection/MyCollection.tests.tsx
  src/app/Scenes/MyCollection/MyCollection.tsx
  src/app/Scenes/MyCollection/MyCollectionArtworks.tsx
  src/app/Scenes/MyCollection/MyCollectionLegacy.tsx
  src/app/Scenes/MyCollection/State/MyCollectionTabsStore.tsx
  src/app/Scenes/MyCollection/utils/localArtworkSortAndFilter.ts
  src/app/Scenes/MyProfile/Components/MyProfileHeader.tsx
Labels: Jira Synced

#12011 fix: menu item layout on large text
  src/app/Components/MenuItem.tsx
Labels: Accessibility

#12016 fix: navigation goBack issues on search portal
  src/app/Components/GlobalSearchInput/GlobalSearchInputOverlay.tsx
Labels: Jira Synced, Squash On Green

#12003 feat(home view): add support for additional nav pill icons
  src/app/Scenes/HomeView/Sections/HomeViewSectionNavigationPills.tsx
Labels: Jira Synced

#12020 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12021 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12022 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11951 chore: Restrict using `navigate` in favor of `RouterLink` with eslint
  .eslintrc.js
Labels: Squash On Green

#12012 feat(ONYX-1675): add collector profile header card to the new settings screen
  images/user_account_mc_empty_state.webp
  images/user_account_mc_empty_state@2x.webp
  images/user_account_mc_empty_state@3x.webp
  src/app/Navigation/routes.tsx
  src/app/Scenes/MyProfile/Components/MyProfileHeader.tsx
  src/app/Scenes/MyProfile/Components/UserAccountHeader/MyCollectionBannerEmptyState.tests.tsx
  src/app/Scenes/MyProfile/Components/UserAccountHeader/MyCollectionBannerEmptyState.tsx
  src/app/Scenes/MyProfile/Components/UserAccountHeader/MyCollectionPreview.tests.tsx
  src/app/Scenes/MyProfile/Components/UserAccountHeader/MyCollectionPreview.tsx
  src/app/Scenes/MyProfile/Components/UserAccountHeader/ProfileErrorMessage.tsx
  src/app/Scenes/MyProfile/Components/UserAccountHeader/UserAccountHeader.tests.tsx
  src/app/Scenes/MyProfile/Components/UserAccountHeader/UserAccountHeader.tsx
  src/app/Scenes/MyProfile/MyProfile.tsx
  src/app/Scenes/MyProfile/MyProfilePayment.tsx
  src/app/Scenes/MyProfile/MyProfileSettings.tsx
Labels: Jira Synced

#12031 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green
