Repository artsy/eigen, pull requests merged in 2025-02, with the labels that each got.

#11474 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11477 fix: Android long-press back button fix
  src/app/Components/BottomSheet/AutomountedBottomSheetModal.tsx
  src/app/Components/ContextMenu/ContextMenuArtwork.tsx
Labels: Jira Synced

#11485 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11471 feat(dia-1105): infinite disco - save artworks to lists
  src/app/Scenes/InfiniteDiscovery/Components/InfiniteDiscoveryArtworkCard.tsx
Labels: Jira Synced

#11482 fix: keyboardavoidingview issues
  src/app/Scenes/Inbox/Components/Conversations/Composer.tsx
  src/app/Scenes/SellWithArtsy/ArtworkForm/SubmitArtworkForm.tsx
Labels: Jira Synced

#11486 feat: optional chaining for safer access to notificationPreferences
  src/app/Scenes/SavedSearchAlert/EditSavedSearchAlert.tsx
  src/app/Scenes/SavedSearchAlert/containers/CreateSavedSearchContentContainer.tsx
Labels: Jira Synced, Squash On Green

#11481 fix(PBRW-397): Dismiss modal on foreground Push Notification tap
  src/app/Components/ArtsyWebView.tsx
  src/app/store/NativeModel.ts
  src/app/utils/PushNotification.ts
Labels: Jira Synced

#11490 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11483 feat(DIA-1101): cast a shadow while an artwork card is being swiped
  src/app/Components/FancySwiper/FancySwiper.tsx
  src/app/Components/FancySwiper/FancySwiperCard.tsx
  src/app/Scenes/InfiniteDiscovery/Components/InfiniteDiscoveryArtworkCard.tsx
  src/app/Scenes/InfiniteDiscovery/InfiniteDiscovery.tsx
Labels: Squash On Green

#11492 fix: purchase button disappears
  LICENSE
  package.json
  src/app/Components/ArtsyWebView.tsx
Labels: Jira Synced

#11494 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11501 fix: Correctly filter CollectorProfileUpdatePromptNotificationItem in Activity rail
  src/app/Scenes/Activity/ActivityList.tsx
  src/app/Scenes/Activity/utils/__tests__/shouldDisplayNotification.tests.ts
  src/app/Scenes/Activity/utils/shouldDisplayNotification.ts
  src/app/Scenes/HomeView/Components/ActivityRail.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionActivity.tsx
Labels: Jira Synced

#11500 feat: add your active bids section to sales screen
  src/app/Scenes/Sales/Components/SaleListActiveBids.tests.tsx
  src/app/Scenes/Sales/Components/SaleListActiveBids.tsx
  src/app/Scenes/Sales/Sales.tsx
Labels: Jira Synced

#11504 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11509 fix: Info button modal max content size for iOS
  src/app/Components/Buttons/InfoButton.tsx
Labels: Squash On Green

#11455 fix: Close Info bottom sheet on tapping Close button
  src/app/Components/Artist/ArtistInsights/ArtistInsightsAuctionResults.tests.tsx
  src/app/Components/BottomSheet/AutoHeightBottomSheet.tsx
  src/app/Components/ContextMenu/ContextMenuArtwork.tsx
  src/app/Components/ContextMenu/__tests__/ContextMenuArtwork.tests.tsx
  src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionArtworkSubmissionStatus.tests.tsx
Labels: Squash On Green

#11508 chore: align framed experience with web
  src/app/Components/ArtworkFilter/ArtworkFilterHelpers.ts
  src/app/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx
  src/app/Components/ArtworkFilter/Filters/FramedOptions.tests.tsx
Labels: Squash On Green

#11498 chore: Replace `ElementInView` with `Sentinel`
  src/app/Components/ProgressiveOnboarding/ProgressiveOnboardingOfferSettings.tests.tsx
  src/app/Components/ProgressiveOnboarding/ProgressiveOnboardingSaveArtwork.tests.tsx
  src/app/Components/ProgressiveOnboarding/ProgressiveOnboardingSaveArtwork.tsx
  src/app/Components/ProgressiveOnboarding/ProgressiveOnboardingSignalInterest.tests.tsx
  src/app/Scenes/InfiniteDiscovery/Components/InfiniteDiscoveryAboutTheWorkTab.tsx
  src/app/Scenes/Onboarding/OnboardingQuiz/__tests__/OnboardingMarketingCollection.tests.tsx
  src/app/Scenes/SavedSearchAlert/screens/ConfirmationScreen.tests.tsx
  src/app/system/navigation/RouterLink.tests.tsx
  src/app/system/navigation/RouterLink.tsx
  src/app/utils/ElementInView.tsx
  src/app/utils/Sentinel.tsx
  src/setupJest.tsx
Labels: Jira Synced, Squash On Green

#11503 feat(ONYX-1506): add LatestAuctioResultsRail to the auctions (Sales) screen
  src/app/Components/LatestAuctionResultsRail.tests.tsx
  src/app/Components/LatestAuctionResultsRail.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionAuctionResults.tsx
  src/app/Scenes/Sales/Sales.tests.tsx
  src/app/Scenes/Sales/Sales.tsx
Labels: Jira Synced, Squash On Green

#11511 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11512 fix: truncated title on artworkgriditem
  src/app/Components/ArtworkGrids/ArtworkGridItem.tsx
Labels: Jira Synced

#11497 feat: Home view prefetching part III
  src/app/Components/ArticleCard.tsx
  src/app/Navigation/routes.tsx
  src/app/Scenes/Article/ArticleScreen.tsx
  src/app/Scenes/HomeView/Components/ActivityIndicator.tsx
  src/app/Scenes/HomeView/Components/ActivityRailItem.tsx
  src/app/Scenes/HomeView/Components/NewWorksForYouRail.tsx
Labels: Jira Synced

#11517 feat(DIA-1106): updating 'back' and 'exit' icons for infinite discovery
  src/app/Scenes/InfiniteDiscovery/InfiniteDiscovery.tsx
  src/app/Scenes/InfiniteDiscovery/__tests__/InfiniteDiscovery.tests.tsx
Labels: Jira Synced

#11519 chore: app metadata updates #trivial
  fastlane/metadata/android/en-US/full_description.txt
  fastlane/metadata/android/en-US/title.txt
  fastlane/metadata/en-US/description.txt
  fastlane/metadata/en-US/keywords.txt
  fastlane/metadata/en-US/name.txt
Labels: Squash On Green

#11520 fix(DIA-1068): prevent artwork cards from freezing
  src/app/Components/FancySwiper/FancySwiper.tsx
  src/app/Components/FancySwiper/__tests__/FancySwiper.tests.tsx
  src/app/Scenes/ArtQuiz/ArtQuizArtworks.tsx
  src/app/Scenes/InfiniteDiscovery/InfiniteDiscovery.tsx
Labels: Jira Synced, Squash On Green

#11525 chore: Disable Artwork context menu in test environment
  src/app/Components/ContextMenu/ContextMenuArtwork.tsx
Labels: Squash On Green

#11524 feat: Do not show Long Press quick tip on first app launch
  src/app/Components/ProgressiveOnboarding/ProgressiveOnboardingLongPressContextMenu.tsx
Labels: Squash On Green

#11532 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11535 chore(tools): update notion export to use shared bug fields
  scripts/utils/exportNotionTicketsToJira.ts
Labels: Jira Synced, Squash On Green

#11531 fix: infinite discovery issues
  src/app/Components/ArtworkLists/useArtworkListsToast.ts
  src/app/Components/Toast/ToastComponent.tsx
  src/app/Scenes/Artwork/Components/ArtworkPrice.tsx
  src/app/Scenes/InfiniteDiscovery/InfiniteDiscovery.tsx
Labels: Squash On Green

#11538 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11544 chore: refactor input variants
  package.json
  src/app/Components/CreditCardField/CreditCardField.tsx
  src/app/Components/Select/Components/SelectButton.tsx
  src/app/Scenes/HomeView/Components/HomeViewSectionCardsCard.tsx
  yarn.lock
Labels: Squash On Green

#11549 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11545 chore: Retire PrefetchFlatList (and replace with FlatList and RouterLink)
  src/app/Components/AboveTheFoldFlatList.tsx
  src/app/Components/CardRail/CardRailFlatList.tsx
  src/app/Components/InfiniteScrollFlashList.tsx
  src/app/Components/PrefetchFlashList.tsx
  src/app/Components/PrefetchFlatList.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionFairs.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionFairsFairItem.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionSales.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionSalesItem.tsx
  src/app/Scenes/ViewingRoom/Components/ViewingRoomsHomeRail.tsx
Labels: Jira Synced

#11558 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11559 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11561 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11562 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11563 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11564 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11522 fix(EMI-2224): Refactor Register to Bid flow
  src/app/Components/Bidding/BidFlow.tests.tsx
  src/app/Components/Bidding/Components/PaymentInfo.tests.tsx
  src/app/Components/Bidding/Components/PaymentInfo.tsx
  src/app/Components/Bidding/Components/PhoneInfo.tsx
  src/app/Components/Bidding/Context/BidFlowContextProvider.tests.tsx
  src/app/Components/Bidding/Context/BidFlowContextProvider.tsx
  src/app/Components/Bidding/Screens/BidResult.tests.tsx
  src/app/Components/Bidding/Screens/BidResult.tsx
  src/app/Components/Bidding/Screens/ConfirmBid.tests.tsx
  src/app/Components/Bidding/Screens/ConfirmBid/BidderPositionQuery.ts
  src/app/Components/Bidding/Screens/ConfirmBid/PriceSummary.tsx
  src/app/Components/Bidding/Screens/ConfirmBid/index.tsx
  src/app/Components/Bidding/Screens/CreditCardForm.tests.tsx
  src/app/Components/Bidding/Screens/CreditCardForm.tsx
  src/app/Components/Bidding/Screens/PhoneNumberForm.tests.tsx
  src/app/Components/Bidding/Screens/PhoneNumberForm.tsx
  src/app/Components/Bidding/Screens/Registration.tests.tsx
  src/app/Components/Bidding/Screens/Registration.tsx
  src/app/Components/Bidding/Screens/RegistrationResult.tests.tsx
  src/app/Components/Bidding/Screens/RegistrationResult.tsx
  src/app/Components/Bidding/Screens/SelectMaxBid.tests.tsx
  src/app/Components/Bidding/Screens/SelectMaxBid.tsx
  src/app/Components/Bidding/types.ts
  src/app/Components/Containers/BidFlow.tsx
  src/app/Components/Containers/RegistrationFlow.tsx
  src/app/Components/CreditCardField/CreditCardField.tsx
  src/app/Components/Select/Components/SelectModal.tsx
  src/app/Navigation/AuthenticatedRoutes/BiddingNavigator.tsx
  src/app/Scenes/Artwork/Components/ArtworkExtraLinks/partnerName.tests.tsx
  src/app/Scenes/Artwork/Components/ArtworkExtraLinks/partnerName.tsx
  src/app/Scenes/SavedSearchAlert/SavedSearchAlertForm.tsx
  src/app/utils/__legacy_do_not_use__navigator-ios-shim.tsx
  src/app/utils/hooks/usePromisedMutation.ts
  src/app/utils/hooks/withSuspense.tsx
  src/app/utils/mutations/useCreateBidderPosition.ts
  src/app/utils/mutations/useCreateCreditCard.ts
  src/app/utils/mutations/useUpdateUserPhoneNumber.ts
  src/setupJest.tsx
Labels: Jira Synced

#11567 fix: margins on browseSimilarScreen
  src/app/Scenes/Artwork/Components/BrowseSimilarWorks/BrowseSimilarWorksContent.tsx
Labels: Jira Synced

#11568 fix: android dev menu navigateTo input
  src/app/system/devTools/DevMenu/Components/NavigateTo.tsx
Labels: Squash On Green

#11569 fix(EMI-2279): Attempt to improve HomeView Tasks performance
  package.json
  src/app/Components/Artist/useFollowArtist.ts
  src/app/Components/ArtworkLists/views/CreateNewArtworkListView/useCreateNewArtworkList.ts
  src/app/Components/ArtworkLists/views/SelectArtworkListsForArtworkView/useUpdateArtworkListsForArtwork.ts
  src/app/Components/Tasks/Task.tsx
  src/app/Scenes/ArtworkList/views/DeleteArtworkListView/useDeleteArtworkList.ts
  src/app/Scenes/HomeView/Sections/HomeViewSectionTasks.tsx
  src/app/utils/mutations/useDislikeArtwork.ts
  src/app/utils/useMutation.ts
  yarn.lock
Labels: Jira Synced

#11571 fix(PBRW-487): Fix double artwork navigation issues
  src/app/Scenes/Artwork/Components/BrowseSimilarWorks/BrowseSimilarWorksContent.tsx
  src/app/Scenes/SavedSearchAlert/AlertArtworksGrid.tsx
  src/app/Scenes/SavedSearchAlert/screens/ConfirmationScreen.tsx
Labels: Jira Synced, Squash On Green

#11573 chore: fix yarn:doctor script
  scripts/utils/doctor.js
Labels: Squash On Green

#11574 chore(build): support user installations of asdf at ~/$HOME/.asdf
  ios/Artsy.xcodeproj/xcshareddata/xcschemes/Artsy.xcscheme
Labels: Squash On Green

#11570 feat(dia-1025): infinite discovery tracking
  src/app/Components/ArtistListItem.tsx
  src/app/Scenes/InfiniteDiscovery/Components/InfiniteDiscoveryArtworkCard.tsx
  src/app/Scenes/InfiniteDiscovery/Components/InfiniteDiscoveryBottomSheetTabs.tsx
  src/app/Scenes/InfiniteDiscovery/InfiniteDiscovery.tsx
Labels: Jira Synced

#11575 fix: text color on onboarding welcome screen in dark mode
  src/app/Scenes/Onboarding/Auth2/components/AuthBackground.tsx
Labels: Squash On Green

#11576 fix: wrong key for braze prod
  ios/Artsy/App/ARAppDelegate.mm
Labels: Jira Synced, Squash On Green

#11578 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11579 fix: dark mode issues on infinite discovery
  src/app/Scenes/HomeView/Sections/HomeViewSectionCard.tsx
  src/app/Scenes/InfiniteDiscovery/Components/InfiniteDiscoveryBottomSheet.tsx
  src/app/Scenes/InfiniteDiscovery/Components/InfiniteDiscoveryBottomSheetHandle.tsx
Labels: Squash On Green

#11566 chore: Remove old code from BidFlow refactor
  src/app/Components/Bidding/Screens/BidResult.tsx
  src/app/Components/Bidding/Screens/ConfirmBid.tests.tsx
  src/app/Components/Bidding/Screens/ConfirmBid/PriceSummary.tsx
  src/app/Components/Bidding/Screens/ConfirmBid/index.tsx
  src/app/Components/Bidding/Screens/SelectMaxBid.tsx
Labels: Squash On Green

#11583 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11555 feat(ONYX-509): create shows for you screen
  src/app/Components/ArticleCard.tsx
  src/app/Components/Cards/CardWithMetaData.tsx
  src/app/Components/ShowCard.tsx
  src/app/Navigation/routes.tsx
  src/app/Scenes/Articles/Articles.tsx
  src/app/Scenes/Articles/ArticlesList.tsx
  src/app/Scenes/Articles/News/News.tsx
  src/app/Scenes/ArtistArticles/ArtistArticles.tsx
  src/app/Scenes/GalleriesForYou/GalleriesForYouScreen.tsx
  src/app/Scenes/HomeView/Components/ShowsRail.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionArticles.tsx
  src/app/Scenes/Shows/ShowsForYou.tests.tsx
  src/app/Scenes/Shows/ShowsForYou.tsx
Labels: Jira Synced

#11586 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11588 chore: fix project.pbxproj diff
  ios/Artsy.xcodeproj/project.pbxproj
Labels: Squash On Green

#11591 chore: update entry point button placement
  src/app/Scenes/HomeView/Sections/HomeViewSectionCard.tsx
Labels: Squash On Green

#11592 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11528 feat(home view): add icons to navigation pills
  src/app/Scenes/HomeView/Sections/HomeViewSectionNavigationPills.tsx
  src/app/Scenes/HomeView/Sections/__tests__/HomeViewSectionNavigationPills.tests.tsx
Labels: Jira Synced, Squash On Green

#11593 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11598 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11589 feat(dia-1149): store up to 1000 discovered artworks in local storage
  src/app/store/InfiniteDiscoveryModel.ts
Labels: Jira Synced

#11602 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11604 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11605 fix(ONYX-1559): fix padding on the info modal
  src/app/Components/Buttons/InfoButton.tsx
Labels: Jira Synced, Squash On Green

#11606 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11607 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11609 fix(PBRW-503): Fix artwork partner offer note issue
  src/app/Scenes/Artwork/Components/ArtworkPartnerOfferNote.tsx
Labels: Jira Synced, Squash On Green

#11476 feat: Featured Fairs screen
  src/app/Components/Cards/CardWithMetaData.tsx
  src/app/Components/ThreeUpImageLayout.tsx
  src/app/Navigation/routes.tsx
  src/app/Scenes/Artwork/Components/ArtworkError.tsx
  src/app/Scenes/Fair/FeaturedFairsScreen.tests.tsx
  src/app/Scenes/Fair/FeaturedFairsScreen.tsx
  src/app/Scenes/HomeView/Sections/FairCard.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionFairs.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionFairsFairItem.tsx
Labels: Jira Synced

#11608 fix(DIA-1002): Allowing for coverArtwork for avatar images on artist search results
  src/app/Components/ArtistListItem.tsx
  src/app/Components/AutosuggestResults/AutosuggestResults.tsx
  src/app/Scenes/Collection/Components/FeaturedArtists.tests.tsx
  src/app/Scenes/Collection/Components/__fixtures__/CollectionFixture.ts
  src/app/Scenes/Search/components/AutosuggestSearchResult.tsx
Labels: Jira Synced

#11614 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11615 chore: adjust featured fairs screen and add href to featured fairs homeview component
  src/app/Scenes/Fair/FeaturedFairsScreen.tsx
  src/app/Scenes/HomeView/Components/ShowsRail.tsx
  src/app/Scenes/HomeView/Sections/HomeViewSectionFairs.tsx
  src/app/Scenes/HomeView/Sections/__tests__/HomeViewSectionFairs.tests.tsx
Labels: Squash On Green

#11616 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green
