Repository artsy/eigen, pull requests merged in 2025-05, with the labels that each got.

#12032 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12033 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12034 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12037 fix: Dark Mode TextInput text color
  src/app/Scenes/AuctionResult/AuctionResult.tsx
  src/app/Scenes/Inbox/Components/Conversations/Composer.tsx
  src/app/system/devTools/DevMenu/Components/ExperimentFlagItem.tsx
Labels: Jira Synced

#12041 fix: Delete artwork background color in dark mode
  src/app/Scenes/MyCollection/Screens/ArtworkForm/Components/MyCollectionArtworkFormDeleteArtworkModal.tsx
Labels: Jira Synced, Squash On Green

#12028 fix: fix refresh, adjust placeholder
  src/app/Scenes/MyProfile/MyProfilePayment.tsx
  src/app/Scenes/MyProfile/MyProfilePaymentNewCreditCard.tsx
  src/app/utils/refreshHelpers.tsx
Labels: Squash On Green

#12038 fix: Shipping modal dark mode background
  src/app/Scenes/Artwork/Components/CommercialButtons/ShippingModal.tsx
Labels: Jira Synced

#12044 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12048 fix: Add bottom safe area for Add Artists screen on Android
  src/app/Scenes/MyCollection/Screens/MyCollectionAddCollectedArtists/MyCollectionAddCollectedArtists.tsx
Labels: Jira Synced

#12024 feat: Add new My Collection Insights tab
  src/app/Scenes/MyCollection/Components/MyCollectionCollectedArtists.tsx
  src/app/Scenes/MyCollection/MyCollection.tsx
  src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsights.tsx
  src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsightsOverview.tsx
Labels: Jira Synced, Squash On Green

#12054 fix: Set Onboarding screen background to black in light and dark mode
  src/app/Scenes/Onboarding/Auth2/components/AuthBackground.tsx
Labels: Squash On Green

#12058 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12060 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12061 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12053 chore: Add Dark Mode update tracking
  src/app/Scenes/MyProfile/DarkModeSettings.tsx
  src/app/Scenes/MyProfile/DevicePrefsModel.ts
Labels: Squash On Green

#12059 refactor(icons): update FollowArtistIcon
  src/app/Scenes/HomeView/Sections/HomeViewSectionNavigationPills.tsx
  src/app/Scenes/LegacyFavorites/LegacyFavorites.tsx
Labels: Jira Synced

#12065 feat(ONYX-1715): adjust id and email verifications component
  src/app/Scenes/MyProfile/MyProfileEditForm.tsx
  src/app/Scenes/MyProfile/__tests__/MyProfileEditForm.tests.tsx
Labels: Jira Synced

#12076 fix: darkmode ff tests
  src/app/store/__tests__/GlobalStoreModel.tests.ts
Labels: Squash On Green

#12078 fix: Complete Profile Identity Verification Step FAQ link layout on Android
  src/app/Scenes/CompleteMyProfile/IdentityVerificationStep.tsx
Labels: Squash On Green

#12074 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12080 fix: typo only visible in dev mode
  src/app/Navigation/Navigation.tsx
Labels: Squash On Green

#12075 fix: Galleries for You casing
  src/app/Scenes/GalleriesForYou/GalleriesForYouScreen.tests.tsx
  src/app/Scenes/GalleriesForYou/GalleriesForYouScreen.tsx
Labels: Squash On Green

#12083 fix: x icon on emailbanner darkmode and delete unused images
  images/close-x.webp
  images/close-x@2x.webp
  images/close-x@3x.webp
  images/consignments/close-x.webp
  images/consignments/close-x@2x.webp
  src/app/Scenes/HomeView/Components/EmailConfirmationBanner.tsx
Labels: Squash On Green

#12084 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12089 fix: stop firing experiment_viewed event when search screen is rendered
  src/app/Scenes/Search/Search.tsx
Labels: Squash On Green

#12088 fix: native screen presenter not finding window
  ios/Artsy/AppDelegate.h
  ios/Artsy/AppDelegate.mm
  ios/ArtsyTests/App_Tests/AppDelegate+ContinuationTests.m
  ios/ArtsyTests/App_Tests/AppDelegate+NotificationsTests.m
  ios/ArtsyTests/View_Controller_Tests/Web_Browsing/ARInternalMobileWebViewControllerTests.m
Labels: Jira Synced, Squash On Green

#12092 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12082 build(fastlane): bump fastlane deps
  Gemfile.lock
Labels: Squash On Green

#12095 chore: update version number to prep for version 8.72.0
  app.json
Labels: Squash On Green

#12096 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12087 feat(analytics): add screen tracking to reorganized account area
  src/app/Scenes/MyAccount/MyAccount.tsx
  src/app/Scenes/MyAccount/MyAccountDeleteAccount.tsx
  src/app/Scenes/MyAccount/MyAccountEditEmail.tsx
  src/app/Scenes/MyAccount/MyAccountEditPassword.tsx
  src/app/Scenes/MyAccount/MyAccountEditPhone.tsx
  src/app/Scenes/MyAccount/MyAccountEditPriceRange.tsx
  src/app/Scenes/MyProfile/DarkModeSettings.tsx
  src/app/Scenes/MyProfile/MyProfilePayment.tsx
  src/app/Scenes/MyProfile/MyProfilePaymentNewCreditCard.tsx
  src/app/Scenes/MyProfile/MyProfilePreferences.tsx
  src/app/Scenes/MyProfile/MyProfilePrivacy.tsx
  src/app/Scenes/MyProfile/MyProfilePushNotifications.tsx
  src/app/Scenes/MyProfile/MyProfileTermsAndConditions.tsx
  src/app/Scenes/OrderHistory/OrderHistory.tsx
Labels: Jira Synced

#12104 chore: mark AREnableRedesignedSettings as ready for release
  src/app/Scenes/MyProfile/MyProfileSettings.tests.tsx
  src/app/store/config/features.ts
Labels: Squash On Green

#12107 fix: unable to load in favorites tab - alerts
  src/app/utils/Sentinel.tsx
Labels: Jira Synced

#12114 fix: memoize the theme to prevent navigating to home view when changing dark mode settings
  src/app/Providers.tsx
Labels: Jira Synced

#12115 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12116 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12118 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12121 feat: add missing new profile and myc tracking
  package.json
  src/app/Scenes/MyCollection/MyCollection.tsx
  src/app/Scenes/MyProfile/Components/UserAccountHeader/UserAccountHeader.tsx
  src/app/Scenes/MyProfile/MyProfileSettings.tsx
  yarn.lock
Labels: Squash On Green

#12122 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12124 chore: remove non valid a11y props and excess containers
  package.json
  src/app/Components/Bidding/Screens/Registration.tests.tsx
  src/app/Scenes/Onboarding/Auth2/scenes/SignUpNameStep.tsx
  src/app/Scenes/Onboarding/OnboardingCreateAccount/EmailSubscriptionCheckbox.tsx
  src/app/Scenes/Onboarding/OnboardingCreateAccount/OnboardingCreateAccountName.tsx
  src/app/Scenes/Onboarding/OnboardingCreateAccount/TermsOfServiceCheckbox.tsx
  yarn.lock
Labels: Jira Synced, Squash On Green

#12128 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12129 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12132 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12133 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12127 feat(auctions): update Auctions home screen header and whitespace
  src/app/Components/LatestAuctionResultsRail.tsx
  src/app/Scenes/Sales/CurrentlyRunningAuctions.tsx
  src/app/Scenes/Sales/Sales.tests.tsx
  src/app/Scenes/Sales/Sales.tsx
  src/app/Scenes/Sales/UpcomingAuctions.tsx
Labels: Jira Synced

#12136 chore: update metaphysics schema
  data/schema.graphql
  src/app/Scenes/OrderHistory/OrderDetail/OrderDetail.tsx
Labels: Squash On Green

#12138 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12137 build(deps): fastlane deps
  Gemfile.lock
Labels: Squash On Green

#12147 chore: fix MyCollectionAddCollectedArtists test
  src/app/Scenes/MyCollection/Screens/MyCollectionAddCollectedArtists/MyCollectionAddCollectedArtists.tests.tsx
Labels: Squash On Green

#12140 feat(devx): add `which-build` script for tracing commits to beta or submission builds
  package.json
  scripts/deploys/which-build
Labels: Squash On Green

#12153 fix: broken myCollection tests after flag enabled
  src/app/Scenes/MyCollection/Components/MyCollectionZeroArtists.tsx
  src/app/Scenes/MyCollection/Components/MyCollectionZeroState.tsx
  src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsights.tests.tsx
  src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsightsEmptyState.tests.tsx
  src/app/Scenes/MyCollection/Screens/Insights/MyCollectionInsightsEmptyState.tsx
Labels: Squash On Green

#12145 chore(MOPRAT-842): Update ArrowUpRight icons
  src/app/Components/ArtworkGrids/ArtworkSocialSignal.tsx
  src/app/Scenes/Artwork/Components/ArtworkDetailsCollectorSignal.tsx
Labels: Jira Synced

#12161 feat: collect screen
  android/app/src/main/AndroidManifest.xml
  src/app/Components/ArtworkFilter/ArtworkFilterHelpers.ts
  src/app/Components/ArtworkFilter/ArtworkFilterNavigator.tsx
  src/app/Components/ArtworkFilter/ArtworkFilterOptionsScreen.tsx
  src/app/Components/ArtworkFilter/ArtworkFilterStore.tsx
  src/app/Components/ArtworkFilter/Filters/SortOptions.tsx
  src/app/Components/ArtworkFilter/useArtworkFilters.ts
  src/app/Navigation/routes.tsx
  src/app/Scenes/Collect/Collect.tsx
  src/app/Scenes/HomeView/Components/ActivityIndicator.tsx
  src/app/utils/track/schema.ts
Labels: Jira Synced, Squash On Green

#12166 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12117 feat(EMI-2444): Add new route for the new Order Details screen
  src/app/Navigation/routes.tsx
  src/app/Scenes/OrderHistory/OrderHistoryRow.tests.tsx
  src/app/Scenes/OrderHistory/OrderHistoryRow.tsx
  src/app/system/navigation/RouterLink.tsx
Labels: Jira Synced

#12167 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12156 chore(releases): expo functional dev build + updates
  HACKS.md
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/net/artsy/app/MainActivity.kt
  android/app/src/main/res/values/strings.xml
  app.json
  code-signing/certificate.pem
  fastlane/Fastfile
  fingerprint.config.js
  index.js
  ios/Artsy.xcodeproj/project.pbxproj
  ios/Artsy/AppDelegate.mm
  ios/Artsy/Supporting/Expo.plist
  ios/Artsy/Supporting/QA/ExpoQA.plist
  patches/expo-updates+0.27.4.patch
  scripts/deploys/expo-updates/deploy-to-expo-updates
  scripts/deploys/expo-updates/deploy-to-production
  scripts/deploys/expo-updates/expo-publish-selfhosted
  scripts/deploys/expo-updates/get-runtime-version.js
  scripts/deploys/expo-updates/get-submission-tag
  scripts/deploys/expo-updates/update-fingerprint
  src/app/store/config/EchoModel.tests.tsx
  src/app/system/devTools/DevMenu/Components/ExpoUpdatesOptions.tsx
  src/app/system/devTools/DevMenu/DevMenu.tsx
  src/app/system/errorReporting/setupSentry.ts
  src/app/utils/jsonFiles.ts
Labels: Jira Synced, Squash On Green

#12169 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12171 chore(DIA-1307): capture sentry messages when verifyUser fails
  src/app/store/AuthModel.ts
Labels: Jira Synced, Squash On Green

#12172 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12177 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12179 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12174 fix: notification preferences
  src/app/Scenes/MyProfile/MyProfilePushNotifications.tests.tsx
  src/app/Scenes/MyProfile/MyProfilePushNotifications.tsx
Labels: Jira Synced, Squash On Green

#12180 fix: stuck splash screen in onboarding
  src/app/utils/useHideSplashScreen.ts
Labels: Jira Synced

#12185 fix: broken back button behaviour on android
  src/app/Scenes/Onboarding/OnboardingQuiz/__tests__/OnboardingMarketingCollection.tests.tsx
  src/app/utils/hooks/useBackHandler.tests.ts
  src/app/utils/hooks/useBackHandler.ts
Labels: Jira Synced, Squash On Green

#12188 fix: do not restart app after color scheme change
  src/app/Providers.tsx
  src/app/Scenes/MyProfile/DarkModeSettings.tsx
  src/app/Scenes/MyProfile/DevicePrefsModel.ts
  src/app/system/navigation/useReloadedDevNavigationState.ts
Labels: Jira Synced

#12189 chore: remove favorites ff
  src/app/Navigation/AuthenticatedRoutes/Tabs.tsx
  src/app/Navigation/routes.tests.ts
  src/app/Navigation/routes.tsx
  src/app/Scenes/Activity/Activity.tsx
  src/app/Scenes/Favorites/Favorites.tsx
  src/app/Scenes/LegacyFavorites/FavoriteArtists.tsx
  src/app/Scenes/LegacyFavorites/FavoriteCategories.tsx
  src/app/Scenes/LegacyFavorites/FavoriteShows.tsx
  src/app/Scenes/LegacyFavorites/LegacyFavorites.tsx
  src/app/store/config/features.ts
Labels: Jira Synced

#12192 fix: faq link text on complete profile
  src/app/Scenes/CompleteMyProfile/IdentityVerificationStep.tsx
Labels: Jira Synced, Squash On Green

#12195 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12194 fix: pbxproj diff
  ios/Artsy.xcodeproj/project.pbxproj
Labels: Squash On Green

#12173 refactor: import icons from @artsy/icons
  src/app/Components/ArtworkGrids/ArtworkSocialSignal.tsx
  src/app/Scenes/Artwork/Components/ArtworkDetailsCollectorSignal.tsx
  src/app/Scenes/MyBids/Components/BiddingStatuses.tsx
  src/app/Scenes/MyBids/Components/SaleInfo.tsx
  src/app/Scenes/MyBids/SaleInfo.tests.tsx
Labels: Jira Synced

#12197 fix: dark mode on learn more modal
  src/app/Scenes/HomeView/Components/ModalCarouselComponents/ModalCarouselContainer.tsx
Labels: Jira Synced

#12210 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green
