Repository artsy/eigen, pull requests merged in 2025-10, with the labels that each got.

#12802 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12804 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12803 chore: disable 3rd party postinstall scripts #trivial
  .yarnrc.yml
Labels: Jira Synced

#12813 chore: missed internal package exclusions #trivial #skipci
  .yarnrc.yml
Labels: Squash On Green

#12818 fix: keyboard blocks password field in account delete
  src/app/Scenes/MyAccount/MyAccountDeleteAccount.tsx
Labels: Jira Synced, Squash On Green

#12824 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green
